### ISSUE TITLE
Support yields in gaiohttp for middlewares

### ISSUE THREAD

**Issue by asvetlov** [benoitc/gunicorn#1009]
See getsentry/raven-python#599 for details

**Comment by benoitc** [comment]
can you summarise what it would imply?

**Comment by benoitc** [comment]
@asvetlov ping.

**Comment by asvetlov** [comment]
I need to investigate. Author of initial issue blames that middleware which yields (not returns whole HTTP body) doesn't work.

**Comment by urbaniak** [comment]
Is there any progress on that?

I can do some investigation, cause I'm really missing raven on gaiohttp, but have no idea where to start, any advices?

**Comment by asvetlov** [comment]
Perhaps it's aihttp bug.
You may start from writing a test code to reproduce the issue in simple way.
That's help me a lot to dig into the problem quickly.

**Comment by urbaniak** [comment]
Hi, here's the example `app.py` that is not working with Sentry middleware which yields the response:

   from raven.middleware import Sentry


    def app(environ, start_response):
        data = b"Hello, World!\n"
        start_response("200 OK", [
              ("Content-Type", "text/plain"),
              ("Content-Length", str(len(data)))
        ])
        return iter([data])

    app = Sentry(app)

I'm using those packages with python 3.4

    aiohttp==0.16.5
    gunicorn==19.3.0
    raven==5.3.1

Running it like that `gunicorn -k gaiohttp app:app --reload`

I'm getting

    RuntimeError: Task got bad yield: b'Hello, World!\n'

The expected result with Sentry middleware should be the same as without it.

**Comment by benoitc** [comment]
What's the result when you're using another worker?

**Comment by urbaniak** [comment]
It's working as expected - returning 200 OK and "Hello world" response via http - with sync worker.

That only affects gaiohttp.

**Comment by benoitc** [comment]
@urbaniak thanks for your answer. It will be fixed soon.

**Comment by urbaniak** [comment]
cool!

**Comment by vasa-chi** [comment]
Sorry for bumping, but is there any update on this issue?

**Comment by urbaniak** [comment]
I'm afraid that a proper fix will require supporting only python 3.5 and using the async/await keywords.

**Comment by tilgovi** [comment]
Maybe this is actually a bug in aiohttp?

**Comment by JTCunning** [comment]
Hey everyone, raven-python contributor here. This issue has been fixed and [included in our latest release, 5.25.0](https://github.com/getsentry/raven-python/compare/5512871260343cb769ca0648f90c314a93dc6edd...8ad915783ee9ef68cb6e77941c3ce13e8758ea3d). Feel free to close this ticket or resubmit the issue back to raven-python.

**Comment by tilgovi** [comment]
Looking over those changes, I think this looks correct. Thanks, @JTCunning, I'll close. If anyone sees an actionable change we should still make to Gunicorn please open an issue for it.
