### ISSUE TITLE
'gthread' not added to supporded workers.

### ISSUE THREAD

**Issue by vlad-dragos** [benoitc/gunicorn#1011]
I'm trying to use the 'gthread' worker however I'm getting this error:
```python
File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 131, in load_class
    section, uri)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2629, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('gunicorn.workers', 'gthread') not found
```
Upon investigation I found that the `gthread` worker is not included in`gunicorn.workers.SUPPORTED_WORKERS`. 

Is this intended or it's a bug?

**Comment by berkerpeksag** [comment]
Looks like a bug to me. Relevant commit is https://github.com/benoitc/gunicorn/commit/a397d90774d3b8975fc0c1120e52529b1de08c97. Feel free to send a PR. Thanks!

**Comment by vlad-dragos** [comment]
Will do a push request later tonight. :)

**Comment by vlad-dragos** [comment]
Should I add a check for Python3?

**Comment by berkerpeksag** [comment]
No, gthread should work in both Python 2 and Python 3 as far as I know
