### ISSUE TITLE
releasing more often, new release procedure?

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1021]
From some talks I had recently it appears to me that we don't tag/release very often while we continuously update the master. Since people are waiting a formal release to deploy a new gunicorn, I propose to release a snapshot of master more often to the world. 

Since it's some kind an arbitrary release, I propose to **have a release each month, the first tuesday** (except of course if nothing happened in between).

While I'm here I propose the following change in the way we are managing releases:
- **By default all releases will be micro releases**. 
- Minor or Major releases target should be created via a ticket describing what the next release will be about and why it should be required. Eventually an accepted version will result in a milestones on github.

Mostly based on semantic versioning but not only, I propose the following definition for our versioning:
- **micro releases** are patch releases, only containing  backwards compatible fixes
- **minor versions** are versions with backwards compatibles changes and new features insides. They can also deprecate some features.
- **major releases** are releases which contains important new features or architecture changes, non backwards compatible changes

We still continue to support only X.Y and (X-1) .

Thoughts?

**Comment by berkerpeksag** [comment]
> micro releases are patch releases, only containing backwards compatible fixes
minor versions are versions with backwards compatibles changes and new features insides. They can also deprecate some features.
major releases are releases which contains important new features or architecture changes, non backwards compatible changes

+1

We'll also need to create branches for minor versions.

**Comment by matrixise** [comment]
+1 but will you have time ? ;-) because you are busy ...

**Comment by tilgovi** [comment]
If we can make sure the release procedures is documented we can have >1 person able to release.

**Comment by benoitc** [comment]
release should be automated at some points. will make a proposal in the morning. also i agree with @tilgovi more than one person should be able to make a release.. let create this RELEASE.md file :)

**Comment by benoitc** [comment]
@berkerpeksag also true...

**Comment by benoitc** [comment]
OK So I think we have the consensus. Let's start on our new release cycle on the next Tuesday 2015-06-02. I will create the release ticket later in the day. 

TODO:
- Please have a look on #1028. Would be cool to make all the process mostly automatic once we have tagged.
- Describe our release cycle in a doc

**Comment by tilgovi** [comment]
Just checked and made sure I have access to PyPI. Anything else we need this issue open for?

**Comment by benoitc** [comment]
@tilgovi i am closing it, we still need to handle #1028 which obviously would make everything simpler, but it's now superseded by #1170
