### ISSUE TITLE
moving gunicorn to its own github organisation 

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1022]
Last call before moving the gunicorn repository to its own organisation. If anyone disagree let me know :)

**Comment by berkerpeksag** [comment]
+1 How will you move it? By using GitHub's repo transfer feature or manually?

**Comment by benoitc** [comment]
github repo transfert this time

**Comment by berkerpeksag** [comment]
That's great, thanks! :) You may want to delete https://github.com/gunicorn/gunicorn before transfering this repo to the org.

**Comment by GMLudo** [comment]
+1

**Comment by benoitc** [comment]
OK, so i will do last check so we make sure to not loose any useful information when moving the repo: tickets and PRs, can anyone confirm they will be kept?

Also for the sake of sanity we may want to release a 19.4 first which could be done at the beginning of the week.

**Comment by berkerpeksag** [comment]
> can anyone confirm they will be kept?

I've used the repo transfer feature before (for https://github.com/berkerpeksag/astor), you'll only need to delete gunicorn/gunicorn.

**Comment by benoitc** [comment]
@berkerpeksag thanks for the confirmation :) Also https://help.github.com/articles/transferring-a-repository/ make it clear they will be kept.

**Comment by wong2** [comment]
:clap:

**Comment by benoitc** [comment]
obviously this hasn't been done.
