### ISSUE TITLE
freeze features on python 2?

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1029]
Related to #1015 I wonder if we shouldn't freeze the features on python 2 and start to implement new things on python3. It will ease our work somehow...

**Comment by GMLudo** [comment]
+10, the time of the big migration to Python 3 should start somewhere: Python 3 should become the first class citizen, and Python 2 should the legacy. As [David Beazley tweets](https://twitter.com/dabeaz/status/597328085948768256), Javascript is in pertual revolution, compare to Python. I don't believe that the high level of changes in Javascript ecosystem is really sustainable in the long term, however, it the time right now that Python developers stop their laziness to migrate to Python 3, but the great Python 2 support of mainstream libraries isn't an incentive to migrate.

**Comment by fletom** [comment]
+1 for keeping a legacy Python 2 version available (and supported with bug/security fixes) but having new versions of gunicorn be Python 3 only

**Comment by berkerpeksag** [comment]
Gunicorn 20.0 will be a major release, we can use it as a starting point and make 19.x series LTS/legacy.

**Comment by benoitc** [comment]
closing issue we are agree on the freeze of features. Gunicorn 19.x will continue to be maintained over the time but without major new features.
