### ISSUE TITLE
Document that REMOTE_ADDR is not necessarily the user IP

### ISSUE THREAD

**Issue by Starefossen** [benoitc/gunicorn#1035]
#633 removed functionality which made Gunicron update `REMOTE_ADDR` to what a trusted upstream client sent in the `X-Forwared-For` header. This was a violation of [RFC 3875 CGI Version 1.1](http://www.ietf.org/rfc/rfc3875) which states the following:

```
4.1.8.  REMOTE_ADDR

   The REMOTE_ADDR variable MUST be set to the network address of the
   client sending the request to the server.
```

Because of this change, if your Gunicorn server is behind any proxy you will only get the proxy's IP address as the `REMOTE_ADDR`.

I think there should be some sort of mention of this *pitfall* in the documentation along with a suggested good workaround (if there exists any). I'll see if I get the time to submit a PR at the end of this weekend.

**Comment by berkerpeksag** [comment]
Fixed by https://github.com/benoitc/gunicorn/commit/85d857d7116dc58cd979650c5dc8b803c660a338.
