### ISSUE TITLE
Weird worker response caching for some pages

### ISSUE THREAD

**Issue by adontz** [benoitc/gunicorn#1043]
I have Gunicorn running Django application. There is NGiNX in front, but issue can be reproduced on pure Gunicorn so I do not include NGiNX details here.

Gunicorn==19.2.1 (Also got the same result with 19.3 and 18.0)
Django==1.7.4

My Django application provides REST API page which gets username and password as HTTP "Authentication: Basic ...." header and outputs JSON data, some numbers read from database.

The problem is that page output is somehow cached on per worker basis for this page and is not for very similar other page which outputs nearly identical JSON.

So, for instance, if I have 4 workers and I do the following:
* Restart gunicorn
* Request page, get value of 100
* Update database, to value 101
* Request page, get value of 101
* Update database, to value 102
* Request page, get value of 102
* Update database, to value 103
* Request page, get value of 103

Then whatever database value is I get 101, 102, 103 or 104 until I restart Gunicorn again. I'm not always lucky enough to fill all four worker caches with different values, but is still easy to reproduce. Also, if I modify my config and set max_requests option to "1" everything works correctly. Changing other options, like binding on TCP port instead of UNIX socket do not change anything. error and access log contain nothing different to chached and noncached pages.

But so some other page everything is OK and values are always read from database. I cannot blame any caching because I do not use any at all. Actually caching middleware is not even enabled. Also, both pages call one and the same data access method, so there is absolutely no difference in how data is read from database.

I have got this issue on production environment so I will be happy to get not only solution but any temporary workaround tips except setting max_requests to 1 as that has great impact on performance.

Here is my gunicorn.py

    chdir   = '/data/django/'
    raw_env = [ 'DJANGO_SETTINGS_MODULE=settings' ]

    accesslog = '/var/log/gunicorn-access.log'
    errorlog  = '/var/log/gunicorn-error.log'
    pidfile   = '/var/run/gunicorn.pid'
    loglevel  = 'warning'

    bind    = 'unix:/var/run/gunicorn.sock'
    backlog = 2048

    limit_request_line       = 1024 * 1024
    limit_request_field_size = 1024 * 1024
    limit_request_fields     =  256

    workers      = 4
    threads      = 1
    max_requests = 4096
    max_requests_jitter = 512

    timeout          = 30
    keepalive        = 30
    graceful_timeout = 30

    daemon = True

And my systemd gunicorn.service

    [Unit]
    Description=gunicorn daemon

    [Service]
    Type=forking
    PIDFile=/var/run/gunicorn.pid
    User=root
    WorkingDirectory=/usr/bin
    ExecStart=/usr/bin/gunicorn --config /data/django/gunicorn.py wsgi:application
    ExecReload=/bin/kill -s HUP $MAINPID
    ExecStop=/bin/kill -s QUIT $MAINPID

    [Install]
    WantedBy=multi-user.target

Headers of cached request

    HTTP/1.1 200 OK
    Server: gunicorn/19.2.1
    Date: Tue, 09 Jun 2015 22:46:03 GMT
    Connection: close
    Transfer-Encoding: chunked
    Vary: Cookie, Accept-Language
    Content-Type: application/json; charset=utf-8
    Content-Language: en-us
    X-Frame-Options: SAMEORIGIN
    Set-Cookie: language_code=en-us; expires=Wed, 08-Jun-2016 22:46:03 GMT; Max-Age=31536000; Path=/
    Set-Cookie: sessionid=olyy8a8hzc89261yf5nr4tufnf3fchgu; expires=Tue, 09-Jun-2015 22:47:03 GMT; HttpOnly; Max-Age=60; Path=/
    Set-Cookie: csrftoken=aJXxhxQH1hpHFJzVMbbRYMiGGASj1yej; expires=Tue, 07-Jun-2016 22:46:03 GMT; Max-Age=31449600; Path=/

Headers of non-cached request

    HTTP/1.1 200 OK
    Server: gunicorn/19.2.1
    Date: Tue, 09 Jun 2015 22:46:44 GMT
    Connection: close
    Transfer-Encoding: chunked
    Vary: Cookie, Accept-Language
    Content-Type: application/json; charset=utf-8
    Content-Language: en-us
    X-Frame-Options: SAMEORIGIN
    Set-Cookie: language_code=en-us; expires=Wed, 08-Jun-2016 22:46:44 GMT; Max-Age=31536000; Path=/
    Set-Cookie: sessionid=9ddzpxvcsqzh9z4a8l5bnvd2g3us5u0p; expires=Tue, 16-Jun-2015 22:46:44 GMT; HttpOnly; Max-Age=604800; Path=/
    Set-Cookie: csrftoken=ufBN8PIH0i9k9SLuj3e4IcAOMS4QgKaw; expires=Tue, 07-Jun-2016 22:46:44 GMT; Max-Age=31449600; Path=/

**Comment by tilgovi** [comment]
Gunicorn does no caching of its own. I think you must be caching something somewhere whether you know it or not. Perhaps a template cache? I don't know Django well enough to know all the places this could happen.

**Comment by benoitc** [comment]
Like @tilgovi said, gunicorn doesn't cache anything.

**Comment by adontz** [comment]
As I said caching middleware is not even enabled. I'll try to implement exhaustive logging next week to see which code exactly is actually executed, and which does not.

**Comment by oppianmatt** [comment]
Be careful you're not using a python object that is causing this. For example reusing a django HttpResponse instead of creating a new one might do this.

**Comment by adontz** [comment]
After almost two months of debugging we found bug in custom middleware.
Very sorry for posting false negative report and taking your time.

**Comment by ibaguio** [comment]
@adontz can you post the bug? I also experience similar issues, and i leaning towards the problem is with gunicorn. it might not be the case.

**Comment by benoitc** [comment]
@ibaguio either post a new ticket with your issue.... Note that gunicorn is not caching anything.

**Comment by ibaguio** [comment]
@benoitc will do intensive testing and logging first with gunicorn before i will post the ticket. just to make sure the issue is with guni, it might be with a middleware as what others have experienced. thanks

**Comment by adontz** [comment]
@ibaguio Authentication library we used was caching user objects, and other library were saving in user objects, assuming request-long lifetime, not session-long.
