### ISSUE TITLE
Consider updating proxy server examples to only serve correct host(s)

### ISSUE THREAD

**Issue by carljm** [benoitc/gunicorn#1046]
The proxy server configs in the Gunicorn docs (https://github.com/benoitc/gunicorn/blob/master/docs/source/deploy.rst) and examples (https://github.com/benoitc/gunicorn/blob/master/examples/nginx.conf) set up a default server block to proxy to Gunicorn, meaning that all requests (regardless of Host header) will be proxied to Gunicorn.

In practice, this is usually a bad configuration. Web applications often rely on the Host header (for e.g. generating links or redirects), and allowing requests with spoofed or invalid Host headers to access the web application can be a security risk.

Some web frameworks (e.g. Django) require the developer to specify allowed Hosts to serve, and will error on invalid Host. Even in this case, it's preferable (both for efficiency and to reduce noisy error logs) if the proxy server filters out such requests before they ever reach Django.

Would you be open to updating the example configurations linked above so that they serve only a specific host (or hosts), and reject requests for other hosts? For nginx, this would mean changing the line `listen 80 default;` in the `server` block to something like `listen 80 example.com www.example.com;`, probably adding a comment to explain that you should change this line for your site's domain, and then also adding a default server block like this:

```
server {
    listen 80 default_server;
    return 444;
}
```

(The 444 status code is an nginx-specific status code that closes the connection immediately. Alternatively a 404 could be returned for a friendlier experience in case the bad Host was an accident rather than a spoofing attack.)

**Comment by berkerpeksag** [comment]
+1

(a little bit off topic, but it would be nice to avoid duplicate nginx examples)

**Comment by benoitc** [comment]
+1 can you send a pr?

**Comment by carljm** [comment]
PR sent: https://github.com/benoitc/gunicorn/pull/1048/files

**Comment by benoitc** [comment]
@carljm thanks! I just merged it.

@berkerpeksag agree. I am opening a ticket for that.
