### ISSUE TITLE
"Custom application" still tries to grab command line args

### ISSUE THREAD

**Issue by btubbs** [benoitc/gunicorn#1047]
I'm writing a mini framework that uses the "custom application" method described at http://docs.gunicorn.org/en/latest/custom.html.  My code is at https://github.com/btubbs/spa/blob/master/spa/utils.py#L15.

I'm finding that when I run py.test and using its [-k command line option](http://pytest.org/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name) to select tests, Gunicorn is interpreting that -k as specifying a worker class.  

```
(spa)vagrant@vagrant-ubuntu-trusty-64:/vagrant/github/spa$ py.test -k echo
======================================== test session starts ========================================
platform linux2 -- Python 2.7.6 -- py-1.4.28 -- pytest-2.7.1
rootdir: /vagrant/github/spa, inifile: 
collected 8 items 

test/test_websocket.py F
--------------------------------------- Captured stderr call ----------------------------------------

Error: class uri 'echo' invalid or not found: 

[Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/spa/local/lib/python2.7/site-packages/gunicorn/util.py", line 131, in load_class
    section, uri)
  File "/home/vagrant/.virtualenvs/spa/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vagrant/.virtualenvs/spa/local/lib/python2.7/site-packages/pkg_resources.py", line 2430, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('gunicorn.workers', 'echo') not found
]
```
I wouldn't expect Gunicorn to be parsing command line flags when I'm not using the 'gunicorn' executable from the command line.

**Comment by berkerpeksag** [comment]
Thanks for the report!

You need to do the configuration step in the `load_config` method (instead of the `init` method) as described at http://docs.gunicorn.org/en/latest/custom.html. `Application.load_config` creates an argument parser by default https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/base.py#L134.

**Comment by btubbs** [comment]
You're right.  Switching from init to load_config solved the issue.  I must have based my code on an earlier snippet from before the "custom application" use case became officially supported.
