### ISSUE TITLE
Make Application classes more subclass friendly

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#1049]
Currently, we need to provide our own `__init__` implementation. I think we can simplify the Application classes a bit to make them more subclass friendly(e.g. provide CmdlineApplication and StandaloneApplication classes).

There is no way to see which methods are public, so we should document them.

Also, there are too many methods to import/get a config file: https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/base.py#L80 I think we only need one or two methods.

**Comment by benoitc** [comment]
:+1:

**Comment by benoitc** [comment]
@berkerpeksag do you still want to do something there?

**Comment by berkerpeksag** [comment]
Yup, my ultimate goal is to get this in for 20.0 or the next major release (we probably need to collect feedback from the community), but I won't be able to work on it in near future (still have to attend some job interviews :()

And note that #935 may be a blocker since it will limit the usefulness of custom application classes (e.g. you can't actually use the `--reload` option)

**Comment by benoitc** [comment]
cc @berkerpeksag maybe we should close it?

**Comment by benoitc** [comment]
stalled
