### ISSUE TITLE
Update PPA for Ubuntu 14.04

### ISSUE THREAD

**Issue by tdbs** [benoitc/gunicorn#1053]
W: Failed to fetch http://ppa.launchpad.net/gunicorn/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

**Comment by benoitc** [comment]
this poa should be removed or updated :) @tilgovi do you think we still
need it?

**Comment by tilgovi** [comment]
The use case is to let non-admin users serve WSGI on privileged ports, I
guess. But I don't think it's that strong.

What do you think?

**Comment by tilgovi** [comment]
I'm going to close this. If someone can offer to help maintain a PPA we can link to it.

**Comment by benoitc** [comment]
+1 thanks
