### ISSUE TITLE
release now?

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1057]
Guys we are not very good in doing incremental releases. I would like to make a new release now with what we have in the current master. Do you seen any simple fixes that could also be added?

Also from now let's go back to the root and just release when fixes come. At least every month. Thoughts?

**Comment by urbaniak** [comment]
:+1:

When that release is planned? I'm wondering is it worth to build custom package with #1010 fixed or just wait for release.

**Comment by benoitc** [comment]
@urbaniak i will do it tomorrow.

**Comment by berkerpeksag** [comment]
+1

Can you also create a stable or development branch so we can work on 20.0 more easily?

**Comment by urbaniak** [comment]
ping, how's that release plan looking now? ;)

**Comment by benoitc** [comment]
heh, tonight or tomorrow early in the morning. Everything is OK, just need
to launch some tests before.

- benoit

**Comment by benoitc** [comment]
I still see that list:
https://github.com/benoitc/gunicorn/milestones/R19.4

Can try to sprint on it this week for a release? cc @tilgovi @berkerpeksag

**Comment by tilgovi** [comment]
Yes, I can help.

**Comment by benoitc** [comment]
cool will be online and pick one of the topics
