### ISSUE TITLE
gunicorn crashed on start with --reload flag

### ISSUE THREAD

**Issue by Schabernack** [benoitc/gunicorn#1058]
Setup: Vagrant, virtualenv, gunicorn 19.3.0:

The following command produces this stack:

`gunicorn -c /data/shared/api/gunicorn_config.py -b unix:/tmp/api-dev-gunicorn.sock --log-level INFO --reload  wsgi:app `

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.6/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/data/virtualenv/default/lib/python2.7/site-packages/gunicorn/reloader.py", line 41, in run
    for filename in self.get_files():
  File "/data/virtualenv/default/lib/python2.7/site-packages/gunicorn/reloader.py", line 30, in get_files
    if hasattr(module, '__file__')
  File "/data/virtualenv/default/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

If I remove --reload it boots up fine.

**Comment by wong2** [comment]
can you paste your config file (`gunicorn_config.py`) ?

**Comment by Schabernack** [comment]
```
import multiprocessing
workers = multiprocessing.cpu_count() * 2 + 1
worker_class = 'sync'
max_requests = 0
workers = 1
```

**Comment by benoitc** [comment]
@Schabernack can you increase the log level to debug? Maybe the trace will be more interesting there. It seems that `module.__file__` doesn't return a string there but I don't know why yet. Does one of your modules rewrite it?

**Comment by benoitc** [comment]
@Schabernack bump.

**Comment by Schabernack** [comment]
Sorry Benoit, I fixed this by reinstalling gunicorn and forgot about the ticket. This can be closed.

**Comment by benoitc** [comment]
@Schabernack np, thanks!

**Comment by jontonsoup** [comment]
I got this issue as well. I'm using docker. Removing --reload was the fix

**Comment by EdwardBetts** [comment]
I'm seeing this problem.
```
Python 3.6.4+ (default, Feb 12 2018, 08:25:03) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> [module for module in sys.modules.values() if hasattr(module, "__file__") and module.__file__ is None]
[<module 'keyrings' (namespace)>, <module 'logilab' (namespace)>, <module 'ruamel' (namespace)>]
>>> 
```

**Comment by EdwardBetts** [comment]
I think this change to cpython 3.6 is what is triggering the bug for me.
https://github.com/python/cpython/commit/a71397fb6603d0fe673acd7765c74699cd28fe7b

**Comment by grafa** [comment]
I can confirm this bug. Any chance to be fixed in next release?

**Comment by EdwardBetts** [comment]
@grafa: Fixed in 8e47986

**Comment by grafa** [comment]
Yes I see that but that means installing gunicorn from github/master and not from pypi.

**Comment by berkerpeksag** [comment]
We have an open issue to track 19.8 release: #1634 (TL;DR: There is one blocker remaining at the moment.)
