### ISSUE TITLE
Access Log line missing when client times out

### ISSUE THREAD

**Issue by dcosson** [benoitc/gunicorn#1060]
I noticed that when running gunicorn with access log enabled, if the client times out and disconnects gunicorn doesn't log anything to the access or error logs. This seems like a bug, the request code typically still runs normally (e.g. there may be new data in the database from this request) so it seems like there should be a record of it in the access log. Other web servers (nginx is the one I tested it on just now) still log to the access log when the client times out, nginx uses the status code 499 for this case.

A simple way to demonstrate -  in a request route in a wsgi app like flask, put in `time.sleep(5)`.  Then hit the route, say it's running locally on port 8000, with `curl --max-time 2 localhost:8000/`. The access log won't show any record of the request.

**Comment by georgexsh** [comment]
I guess you are using sync worker, as this type of worker cant terminate timed-out connection by it self, but be killed by arbiter use `SIGKILL`, so there is no chance for worker to write out log entry; arbiter error log mighty have lines like `WORKER TIMEOUT`.

**Comment by tilgovi** [comment]
We should look into this. From the description provided by @dcosson curl is timing out, not the gunicorn worker.

**Comment by dcosson** [comment]
Right. It would also be nice if a worker timeout could log all the access log fields instead of just the process id when it gets restarted. But I was talking here about when the client times out or otherwise disconnects, not the gunicorn worker.

**Comment by benoitc** [comment]
Hrmm not sure to see the issue there. Isn't the access log about **logging processed requests** by the server? 

If the client timeout then the requests isn't fully processed and the error is then logged in the error logs (depending on the level). Are there any server that log requests that client timeout in the access log?

**Comment by tilgovi** [comment]
Nginx.

**Comment by tilgovi** [comment]
499, as described. It's helpful to log these because if clients are timing out it might be because the requests are taking too long.

**Comment by dcosson** [comment]
And to address the only logging actually processed requests point: 

If a client times out, the request absolutely is still fully processed, the client just didn't get any data back. Even if it was a GET request, it still would be nice to know as it can be very helpful triage bugs, if e.g. a user reported a page was blank and you see a 499 status in the request log for the request to that page, you found the problem. If there's no sign of it in the logs, it could just as easily be a bug with your client code not making the request at all.

Similarly if a worker times out, the request was processed arbitrarily far so it would be nice to see all the info about it, with a status code indicating that the worker timed out at some point.

**Comment by tilgovi** [comment]
@dcosson do you think you could make a PR for this?

**Comment by tilgovi** [comment]
In all of the modules in `gunicorn/workers` you'll find calls to `log.access` toward the end of a `try`. I think you would need to move that to a finally clause and set the status code in an `except` clause that catches the client disconnect.

**Comment by dcosson** [comment]
Cool, thanks for the pointers. I'll give it a shot

**Comment by tilgovi** [comment]
Thanks! Let us know if you run into problems. I'd be happy to help.

**Comment by benoitc** [comment]
@tilgovi fair enough then . And for the record: 

> 499 / CLIENT CLOSED REQUEST
> “An Nginx HTTP server extension. This code is introduced to log the case when the connection is closed by client while HTTP server is processing its request, making server unable to send the HTTP header back.“ — wikipedia

http://httpstatus.es/499 

So it should be done on all reauqets that fail to return to the client because its socket is down. 

@dcosson thanks!

**Comment by tilgovi** [comment]
Huh. I wonder if that means this should really be changed in `gunicorn.http.wsgi:send_headers`. :-/

**Comment by benoitc** [comment]
@tilgovi you mean "only" there ?

**Comment by benoitc** [comment]
@dcosson about the other case. If a worker timeout there is no way to know which request was handled at that time since these information is not shared with other workers or the arbiter. In that case you should rather log the events you need inside the application imo.

**Comment by dcosson** [comment]
@benoitc that makes sense, thanks for clarifying

**Comment by benoitc** [comment]
@tilgovi can you expand what was your idea ? Happy to implement it for the next release. Eventually we could also return a 499.

**Comment by tilgovi** [comment]
I mean that in `send_headers` we can catch and error and set the status to 499, maybe? I was trying to decide if it makes sense to keep the response header once it's been sent to the client, but if sending the header fails then set it to 499.

**Comment by tilgovi** [comment]
Or maybe it makes sense to 499 no matter what if the response doesn't finish cleanly?

**Comment by benoitc** [comment]
Hr if the client timeout, we should probably just close indeed.... There is no point to send a reason if no-one will receive it. So yes let just catch it and end the request cleanly.
