### ISSUE TITLE
Integrate coveragepy into Travis CI

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#1063]

**Comment by tilgovi** [comment]
I've had a smooth time setting up landscape.io in the past and a TOXENV=coverage for travis. Should I set it up?

**Comment by benoitc** [comment]
@tilgovi yup go ahead. I guess it will trigger a lot of work right after ;)

**Comment by benoitc** [comment]
bump :)

**Comment by tilgovi** [comment]
I had been thinking about landscape but codecov.io looks like it has per-branch coverage.

**Comment by benoitc** [comment]
i looked at codecov.io but it requests the permissions for all the org i'm member of. So it's won't be done at least with my account. Maybe we should create a gunicorn user for it?

**Comment by javabrett** [comment]
I was going to raise a new mailing-list question "what is the best way to view code-coverage output", but found this issue open so asking here instead.

`coverage.xml` is produced by local builds, but it isn't rendered into anything useful that would align it with the actual source.

Adding to Travis CI sounds like a reasonable step and might allow coverage thresholds to be set.  Ideally we can inspect code without coverage and look a deltas introduced by PRs.

I know @benoitc tackled a similar app/privacy concern to that raised above when recently activating AppVeyor - not sure how that was resolved, and privacy issues are a nuisance, but wondering if there is now a way to activate _codecov.io_ or something similar.

In the interim, if there's any recommended steps or tips/tricks to help make any sense of the existing coverage report, please share.
