### ISSUE TITLE
'Connection reset by peer' in Nginx + Gunicorn

### ISSUE THREAD

**Issue by andyxning** [benoitc/gunicorn#1067]
we use Gunicorn 19.3.0 and with a Nginx in front of it. However, wen our client to do some requests we get 'error(104, Connection reset by peer)'. 

* We have configured Nginx to log error message. However, we found nothing in it.
* So, the only reason may cause this is that the connection is reset by Gunicorn. However, we found nothing about this in Gunicorn error log(log level is INFO).

We need some help.

**Comment by tilgovi** [comment]
Could you give some more information please?

- What worker are you using?
- Any framework?
- Does this correlate with load, or any other resource consumption?
- Where is this deployed? On your own servers, some PaaS provider?

Is there a possibility that the client is disconnecting and there is no issue on the server?

**Comment by andyxning** [comment]
* we do not make an explicit declaration about worker type. Just like this:   
    gunicorn --access-logfile=/var/log/supervisor/access.log --error-logfile=/var/log/supervisor/error.log pid=/var/run/gunicorn.pid --max-requests 2000 -w 24 -b 0.0.0.0:8080 wsgi:app  
* Flask
* No, at least from my own perspective. I have not seen a high load when reset was encountered
* In our own vm servers(OpenStack based) 

Can client bugs lead to the reset error in client?

**Comment by benoitc** [comment]
Just to be clear this is your client that receive such error? 

Can you increase the log level either in nginx and gunicorn?

**Comment by andyxning** [comment]
we use `notice` log level in Nginx, but got nothing logged. I think may be the request is not got into Nginx and internal router or network device made this happen.

**Comment by andyxning** [comment]
we use `notice` log level in Nginx, but got nothing logged. I think may be the request is not got into Nginx and internal router or network device made this happen.

**Comment by MattBlack85** [comment]
@andyxning does it work for some minutes if you restart the workers? I got into similar problems once

**Comment by andyxning** [comment]
No, we have encountered such situation rarely, almost in the last 180d with only about 10 connection reset error. So, we just do not try the **restart**
