### ISSUE TITLE
Print accesslog to stderr by default

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#1070]
Currently, we are printing everything to stderr by default except accesslog. It would be nice to be consistent and avoid passing `--access-logfile=-` to `gunicorn`.

**Comment by tilgovi** [comment]
:+1:

**Comment by romabysen** [comment]
Might be better to put it on stdout by default or at least have a way other than using /dev/stdout to get the accesslog to stdout.

**Comment by tilgovi** [comment]
Hmmm. Maybe stdout is more appropriate. I don't know. It makes some sense to me not to mix them and to have stderr be for error log only.

**Comment by benoitc** [comment]
hrm I wouldn't print by default the access logs. It can indteed slow down a lot the performances. Also it's only useful when you're using gunicorn standalone. Is there any other reason to want it?

**Comment by tilgovi** [comment]
I'm not moved by the performance argument because I think that defaults should not tune for performance over usability. Just as I would increase the number of workers in a production deployment I might turn off my access log _if_ I have a reverse proxy in front.

**Comment by benoitc** [comment]
@tilgovi fair enough.  About that what about introducing a `--silent`setting?

**Comment by tilgovi** [comment]
No opinion, except if that means no access log but still an error log that would be confusing maybe, no?

**Comment by benoitc** [comment]
silent would silent everything on the console  which is sometimes wanted.

**Comment by benoitc** [comment]
OK so i think I am OK to add the access logs to STDOUT. We simply need a way to disable it then, what would be the best way to do it? Coming to my mind:

- add a `-q` option (for `quiet) to silent all logs.
- add an `--access-logfile=no`

Or let the user log to `/dev/null`.  Thoughts?

**Comment by tilgovi** [comment]
Would -q only silence stdout? Other logging config would take precedence?

**Comment by benoitc** [comment]
yup I think do. It would only silent stdout and stderr.

**Comment by tilgovi** [comment]
Works for me.

**Comment by benoitc** [comment]
no move since and the features seems not that needed by people. closing the issue then,
