### ISSUE TITLE
Paste entry point fixed to 'main'

### ISSUE THREAD

**Issue by dmdm** [benoitc/gunicorn#1073]
Hello,
currently, it is impossible to start gunicorn --paste with a different app name than 'main', e.g. --paste development.ini#foo does not work.
It seems, https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/pasterapp.py#L35 is the reason. If I comment this line out, #foo works for me.

**Comment by tilgovi** [comment]
According to this commit, it should work: e5442332fe16ffa92cd4516c68ef45d93cc57349

The line you commented out should only affect the server that gets loaded, not the app. I'll take another look, though, when I can.

**Comment by tilgovi** [comment]
It seems to work fine here. Can you show your .ini file and how you call gunicorn?

**Comment by dmdm** [comment]
Thank you for looking into it. My INI is like this:
```
[app:main]
use = egg:MyProject

pyramid.includes =
    #pyramid_debugtoolbar
	pyramid_tm

[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 6543

#----------------------------------------------------------------------------

[app:socksrv]
use = egg:MyProject#socksrv

pyramid.includes =
	pyramid_tm

[server:socksrv]
use = egg:gunicorn#main
host = 127.0.0.1
port = 6544
workers = 1
worker_class = guv.GuvWorker
```
If the mentioned line is active (and cuts off he '#name'-part),
```
gunicorn --paste development.ini#socksrv
```
starts "main". With that line commented out, "socksrv" is started correctly.

**Comment by tilgovi** [comment]
I use Pyramid also. I'm surprised that your .ini works. For me, with multi-line `pyramid.includes` I have to make sure the `#` is the first character of the line (before any space) or it isn't treated as a comment.

But, let's assume that's not the issue at all. I can't reproduce this at all on Gunicorn 19.3.0. It works just fine.

What version of Gunicorn are you using?

**Comment by dmdm** [comment]
The same. Just tried it again and got this log, confirming the error:
With commented out line, gunicorn works as expected:
```
$ gunicorn  --paste development.ini#socksrv
[2015-07-10 07:41:34 +0200] [13824] [INFO] Starting gunicorn 19.3.0
[2015-07-10 07:41:34 +0200] [13824] [INFO] Listening at: http://127.0.0.1:6544 (13824)
[2015-07-10 07:41:34 +0200] [13824] [INFO] Using worker: guv.GuvWorker
```
and with it active:
```
$ gunicorn     --paste development.ini#socksrv
[2015-07-10 07:42:40 +0200] [13876] [INFO] Starting gunicorn 19.3.0
[2015-07-10 07:42:40 +0200] [13876] [INFO] Listening at: http://0.0.0.0:6543 (13876)
[2015-07-10 07:42:40 +0200] [13876] [INFO] Using worker: sync
```
As you can see, gunicorn now uses the configuration from the "main" section.

**Comment by tilgovi** [comment]
It seems you're talking about a different server name, not a different app name.

**Comment by tilgovi** [comment]
When I added support for using different apps I contemplated making it possible to use different servers but I couldn't decide on a syntax that I liked. Instead, I decided that since the server configuration can be entirely controlled by the command line I didn't think it was necessary.

In your case, you could do `gunicorn --paste development.ini#socksrv -b 127.0.0.1:6544 -k guv.GuvWorker`.

If you think it's important to allow selecting a different server block maybe we need a new switch, `--paste-server` or something like this.

**Comment by dmdm** [comment]
Sorry if I mixed up the words. I'd like to serve app "main" from server "main" and app "socksrv" from server "socksrv".

**Comment by tilgovi** [comment]
The problem is that I don't want to assume there is always a server and an app with the same name. I also do not like any syntax like `--paste config.ini#app#server` or `--paste config.ini#app@server` or anything like that.

But `--paste` and `--paste-server` would work.

Actually, `--paste` is short for `--paster`. I could make another alias, `--paster-app` and add `--paster-server` and that might be pretty nice.

**Comment by dmdm** [comment]
Ah, you give --paste before -b... Tried the command yesterday too but had --paste at the end and was surprised that the command line does not override the ini file settings.

If possible, I would like to use only the ini file, because then all configuration is in one place.
Does it cause any harm in other aspects, if that L35 is removed?

**Comment by dmdm** [comment]
--paste config.ini#app#server... I see what you mean ;) Hadn't thought about cases where app and server have different names.

**Comment by tilgovi** [comment]
If we remove L35 then when people are trying to launch a different app but not a different server they will get an error because the server maybe does not exist.

**Comment by dmdm** [comment]
You are right. The two pastries then would be great.

**Comment by tilgovi** [comment]
Mmmmm. ![Pastries](https://upload.wikimedia.org/wikipedia/commons/3/3a/Pastry_assortment.jpg)

I'm not sure when I'll get to it, but if you open a PR I'd be happy to review it.

**Comment by dmdm** [comment]
Reminds me of needing some breakfast. About the PR, I'll give it a try. cu

Btw, you don't happen to have experience in writing a websocket app with gunicorn and guv that shares code (esp. SQLAlchemy models) with the main app served by gunicorn syncronously - in regards to thread-safety and sharing the login session, do you?

**Comment by tilgovi** [comment]
No. I use ws4py with the gevent worker to serve websocket requests in the same app as the rest of my routes.

**Comment by tilgovi** [comment]
There are only some ws4py bugs that I have to work around with my own server class that extends the gevent one: https://github.com/hypothesis/h/blob/master/h/server.py

**Comment by tilgovi** [comment]
And the route is here: https://github.com/hypothesis/h/blob/master/h/streamer.py#L605

**Comment by dmdm** [comment]
Thanks. Interesting project, btw. Your main app then is served by the gevent workers, too?

**Comment by dmdm** [comment]
About the new CLI parameters:

1. Rationale

   * We have the switch `--paste` that governs the path to the ini file and the name of the application. Lets keep it that way.
   * Add a new switch `--paste-server NAME` to explicitly a different server name (while the above always uses "main" as server name).

2. Implementation

While the CLI switches can be added to gunicorn's code base, setting a different server name seems more complicated: gunicorn eventually delegates loading the config to PasteDeploy, so that this patch has to be applied there (`loadwsgi.py:_loadconfig()` and its callees).

Shall we do that?

Alternatively, more ugly and not that versatile, but quicker to implement, would be a gunicorn CLI parameter that switches L35 on (default, as-is) and off, so that we at least can use a different server if its app has the same name.

What do you think?

**Comment by tilgovi** [comment]
As you discovered when you commented out that line, the PasteDeploy functions will happily give you back the right thing if you give it a config URI with a # in it. There is no patch to PasteDeploy needed.

**Comment by dmdm** [comment]
But not for "people [who] are trying to launch a different app but not a different server". PasteDeploy does not discern app name and server name, there's only one.
(It's ok for me, though ;)

**Comment by tilgovi** [comment]
Yes, it does. `loadwsgi.loadapp` and `loadwsgi.loadserver` both take a `name` argument and both split on "#" in the config URI if `name` is `None`.

**Comment by dmdm** [comment]
Aha. `paste_config()` only loads the server section, not both, as I mistakenly thought. App section is loaded later on in `run()`. So, please see the PR.

**Comment by benoitc** [comment]
I am not a fan of having a `--paste-server` command. Servers settings should only be done via gunicorn in my opinion. In fact we should only take care about getting the wsgi application at that point. 

Why do you want to use the paster ini for it?

**Comment by dmdm** [comment]
Why did you let me implement it, then?

**Comment by benoitc** [comment]
@dmdm actually this is the first time i am commenting on that ticket. Also not the question mark ;)

**Comment by dmdm** [comment]
@benoitc Really? As head of a team you are held accountable for the actions of your team members.

As to your question: convenience. For me it is more convenient to have the server settings near any other settings, and to share them between waitress and gunicorn. Also, I am not a fan of configuration written in a programming language.

But also I do not insist on paster ini files. They are around only because I have not yet written a wrapper to port the server configuration to yaml. Like many people I have to deal with installing the same software on different hosts in different environments, and I like to have the configuration for all these situations in the same code base. Together with a central configuration, these situations build an inheritance tree. [Like this.](http://3amcode.de/pharaoh/Cms/pharaoh/parenchym/configuration/)

What I really would like to have is a means to integrate gunicorn's settings too into that system (and the paster inis were the most convenient way -- so far).

**Comment by benoitc** [comment]
On Sunday, July 12, 2015, Dirk Makowski <notifications@github.com> wrote:

> @benoitc <https://github.com/benoitc> Really? As head of a team you are
> held accountable for the actions of your team members.
>

The way tickets or PR are discussed is defined there:
https://github.com/benoitc/gunicorn/blob/master/CONTRIBUTING.md#decision-process


> As to your question: convenience. For me it is more convenient to have the
> server settings near any other settings, and to share them between waitress
> and gunicorn. Also, I am not a fan of configuration written in a
> programming language.
>
> But also I do not insist on paster ini files. They are around only because
> I have not yet written a wrapper to port the server configuration to yaml.
> Like many people I have to deal with installing the same software on
> different hosts in different environments, and I like to have the
> configuration for all these situations in the same code base. Together with
> a central configuration, these situations build an inheritance tree. Like
> this. <http://3amcode.de/pharaoh/Cms/pharaoh/parenchym/configuration/>
>
> What I really would like to have is a means to integrate gunicorn's
> settings too into that system (and the paster inis were the most convenient
> way -- so far).
>
Actually I think having a PR adding support for a configuration file in
plain text would be a good idea. About paster Server I am still undecided.
Especially since this part is generally used to handle a custom server
script. What do others think about it?


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benoitc/gunicorn/issues/1073#issuecomment-120763963>.
>


-- 
Sent from my Mobile

**Comment by benoitc** [comment]
@tilgovi sowhat do you think? Should we add the `--paste-server` setting?

**Comment by benoitc** [comment]
bump

**Comment by tilgovi** [comment]
We should either add the option or remove support for the paster server block and force all server settings to the CLI and --configfile

**Comment by benoitc** [comment]
@tilgovi but what's your preference ? :)

**Comment by tilgovi** [comment]
I think my slight preference is to remove the server block support. Then there is no possibility anymore for `use = egg:gunicorn` so no one would use the gunicorn worker with paster or pserve (they both preload the app, sadly). Also, since the keys in the server block end up being custom to gunicorn anyway, I think it's better to put them in the gunicorn config file.

This is what I am thinking. @dmdm might hate me for it, though.

**Comment by tilgovi** [comment]
There are not so many options (mostly just host and port) that are portable to different servers that the settings in the server block end up assuming gunicorn anyway. At that point, they should just be gunicorn command line options, or be in the gunicorn config file if they are non-trivial. This is my feeling.

**Comment by benoitc** [comment]
tilgovi +1. Let's do that.  

@dmdm Thanks a lot for your PR anyway, this is purely a design decision here, and not the easy one to take. Next will be the good :)

**Comment by dmdm** [comment]
Ok, then. Maybe another time.
