### ISSUE TITLE
No luck in running gunicorn under supervisor with the examples provided

### ISSUE THREAD

**Issue by tfarina** [benoitc/gunicorn#1077]
I'm getting the following:

2015-07-11 17:58:50,595 INFO supervisord started with pid 7580
2015-07-11 17:58:51,598 INFO spawned: 'gunicorn' with pid 7583
2015-07-11 17:58:51,605 INFO exited: gunicorn (exit status 127; not expected)

**Comment by tfarina** [comment]
Changing user=nobody to user=tfarina seems to help a little:

2015-07-11 18:00:43,128 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

But nginx still shows 502 Bad Gateway.

**Comment by tfarina** [comment]
Also I have to add 'sudo' to command=

**Comment by benoitc** [comment]
@tfarina can you paste here the configuration you give to supervisord?

**Comment by tfarina** [comment]
Sure.

$ cat ./supervisord.conf
[supervisord]
logfile=supervisord.log      ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=supervisord.pid      ; (supervisord pidfile;default supervisord.pid)
nodaemon=true                ; (start in foreground if true;default false)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)

[program:gunicorn]
command=sudo /usr/local/bin/gunicorn minitwit:app -c /home/tfarina/src/repos/github.com/tfarina/rsc/python/flask/examples/minitwit/gunicorn.py
directory=/home/tfarina/src/repos/github.com/tfarina/rsc/python/flask/examples/minitwit
user=tfarina
autostart=true
autorestart=true
redirect_stderr=true

**Comment by tfarina** [comment]
the gunicorn.py above should read gunicorn.conf.py, of course. Sorry for the typo.

**Comment by tfarina** [comment]
In case it helps, here is the gunicorn configuration file I'm using:

$ cat gunicorn.conf.py
# http://agiliq.com/blog/2014/06/minimal-gunicorn-configuration/
bind='127.0.0.1:8000'
backlog=2048
#workers=1
#worker_class='sync'
#worker_connections=1000
#timeout=30
#keepalive=2
#spew=False
daemon=False
pidfile=None
umask=0
user=None
group=None
tmp_upload_dir=None
proc_name=None
accesslog='gunicorn_access.log'
errorlog='gunicorn_error.log'

**Comment by tfarina** [comment]
Note that when I running the following from the command line, it works:

$ sudo gunicorn minitwit:app -c gunicorn.conf.py

**Comment by benoitc** [comment]
You should try to start gunicorn with the `--user`and `--group` directive [1] and make sure that gunicorn can start as root or nobody user. 

What are the logs of supervisord in error level?

[1] http://docs.gunicorn.org/en/19.3/settings.html#user

**Comment by tfarina** [comment]
Is there something else I could try? I didn't find any example on internet that mentions user and group.

Is this something related to nginx?

**Comment by tfarina** [comment]
Looks like the problem is setting up the right user for supervisor and gunicorn.

**Comment by benoitc** [comment]
@tfarina try to raise the log level of supervisord. It should give us more logs. Right now i don't know why it fails. it can also be an issue with the directory from where the project is loaded.

**Comment by benoitc** [comment]
bump

**Comment by benoitc** [comment]
@tfarina anything to add?

**Comment by tfarina** [comment]
Nope. Closing this. I think the problem is on my side. I will try supervisor mailing list perhaps.
