### ISSUE TITLE
travis ci is failing on python 2.6

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1081]
Latests tests fail under python 2.6 . Apparently this is a tox issue. Is there any version of tox that we should force on travis?

**Comment by jhekkanen** [comment]
Don't know about tox but the mock library has been recently updated and the pypi page states that it supports Python 2.7 and up. There is a SyntaxError being thrown from the mock code in the failing job. Looks like a dict comprehension which is a 2.7 feature if I'm not mistaken.

Maybe force older version of mock? Versions 1.0.1, 1.1.0 and 1.1.1 are all less than a week old.

**Comment by jhekkanen** [comment]
Releases in the github were all less than a week old but looks like the 1.0.1 is the one you need

[mock-1.0.1](https://pypi.python.org/pypi/mock/1.0.1):

    mock is tested on Python versions 2.5-2.7 and Python 3. 
    mock is also tested with the latest versions of Jython and pypy.
