### ISSUE TITLE
Reading settings from Django's

### ISSUE THREAD

**Issue by femesq** [benoitc/gunicorn#1086]
I achieved this (http://gunicorn-docs.readthedocs.org/en/latest/configure.html#framework-settings) with this code on gunicorn_config.py:

```python
try:
    sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'project_name'))
    script_file = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'project_name/local_settings.py')
    print script_file
    process = Popen(['python', script_file], stdout=PIPE)
    out, err = process.communicate()
    try:
        dict_params = ast.literal_eval(out)
        if 'BIND_PORT' in dict_params:
            bind = "127.0.0.1:" + str(dict_params['BIND_PORT'])
            print u"\nBIND_PORT. Obtained: %s" % str(bind)
        if 'DEBUG' in dict_params:
            if bool(dict_params['DEBUG']):
                worker = 1
                log_level = 'debug'
                debug = True
                proc_name += "_debug"
        if 'WORKER_PROCCESS' in dict_params:
            if int(dict_params['WORKER_PROCCESS']) == 0:
                workers = multiprocessing.cpu_count() * 2 + 1
                print u"\nWORKER_PROCCESS. Calculated: %s proccess" % str(workers)
            else:
                workers = int(dict_params['WORKER_PROCCESS'])
                print u"\nWORKER_PROCCESS. Obtained: %s proccess" % str(workers)
    except ValueError:
        pass
except CalledProcessError:
    pass
```

And then, on specific config_files (devel_settings,  production_settings, etc) I this in the bottom of the file:

```python
print "{'DEBUG': %s, 'BIND_PORT': %s, 'WORKER_PROCCESS': %s,  }" % \
      (str(DEBUG), str(BIND_PORT), str(WORKER_PROCCESS))
```

Probably not the most elegant way, but it is working...

PS.: I have the "default" settings on the top of gunicorn_config.py, so this code only changes that.

**Comment by benoitc** [comment]
mmm what arre you trying to achieve?

**Comment by femesq** [comment]
Getting framework's settings (Django, in my case). See link above...

**Comment by benoitc** [comment]
@femesq hrm to be more clear, do you want to add it in the doc? Or anything else? If you want to have it in the doc, don't hesitate to send us a PR :)

**Comment by femesq** [comment]
@benoitc Not sure about it..
It seens to hacky to be in the docs... :)

Maybe add this issue's link so that other users can comment/improve?

**Comment by benoitc** [comment]
@femesq mmm actually it could land as a configuration example in examples I think. Then link that example in the doc. If it's OK for you can you send a PR that does it?

**Comment by femesq** [comment]
Ok @benoitc.
I'm kind of new to git and this procedures (PR, etc) but I'll search how
and try to do so.

**Comment by benoitc** [comment]
sounds like it have been fixed. Closing it.
