### ISSUE TITLE
dictConfig in logconfig

### ISSUE THREAD

**Issue by roboslone** [benoitc/gunicorn#1087]
From logging docs:

> Note: The fileConfig() API is older than the dictConfig() API and does not provide functionality to cover certain aspects of logging. For example, you cannot configure Filter objects, which provide for filtering of messages beyond simple integer levels, using fileConfig(). If you need to have instances of Filter in your logging configuration, you will need to use dictConfig(). Note that future enhancements to configuration functionality will be added to dictConfig(), so it’s worth considering transitioning to this newer API when it’s convenient to do so.

Could you suppport [`dictConfig`](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig) in `logconfig` option?

**Comment by tilgovi** [comment]
Can you confirm what you mean. Having a dictionary somehow in the command line with `--log-config`, is not what you want, correct? But a dictionary when using the `logconfig` setting in your gunicorn conf python file you want to set a dictionary?

**Comment by RoboSloNE** [comment]
My application reads config from file and part of this config is for logging. I want to pass that part to dictConfig. I'm not using command line arguments for logging config at all.

**Comment by berkerpeksag** [comment]
Looks like a reasonable request to me. I think we can also deprecate `logconfig` (or encourage to use the new setting) and add a new setting for this.

**Comment by benoitc** [comment]
+1 . Any PR is welcome :)

**Comment by MatMoore** [comment]
Hello - I'm also interested in this feature. Is the PR above similar to what you had in mind?

**Comment by benoitc** [comment]
I fail to see how the command line can be used. Can someone provide a proper example? And test?

**Comment by MatMoore** [comment]
@benoitc is a CLI option needed for every setting? It's not something I've addressed in the pull request above - that just works with the python configuration file.

If it was a CLI option, how would you use it? The only way I could see it working is if the value is dumped in a json or yaml file and the filename is used as the setting - but that just makes things more complicated if you are already using the python config.

**Comment by akaihola** [comment]
Maybe the way Circus handles logging configuration could be used as a model? See [circus/util.py:configure_logger()](/dotmobo/circus/blob/967ec0296c101ec6deb4e9275bfb95f603d722d0/circus/util.py#L662).

**Comment by benoitc** [comment]
@akaihola how is it different from the way we are doing it now? Also we should not forget that the logging backend is pluggable in Gunicorn.

**Comment by ssalonen** [comment]
I found a workaround using `--config` parameter: one can use `dictConfig` there to setup the logging.

At least seems to work with the default worker type.

**Comment by gangefors** [comment]
> @ssalonen 
> I found a workaround using --config parameter: one can use dictConfig there to setup the logging.
>
> At least seems to work with the default worker type.

Can you give an example for this?

**Comment by wking** [comment]
Closable with #1602 landed, or is this staying open until a release is cut including #1602?

**Comment by StephanErb** [comment]
Please excuse my ignorance, but I am slightly confused how #1602 enables me to load a dict config via the gunicorn command line:

```
$ gunicorn --log-config-dict={} 'flask.main:app'
Error: Value is not a dictionary: {}

$ gunicorn --log-config-dict="{}" 'flask.main:app'
Error: Value is not a dictionary: {}
```

What am I missing?
