### ISSUE TITLE
BlockingIOError on Docker

### ISSUE THREAD

**Issue by dbrgn** [benoitc/gunicorn#1090]
I'm running Docker on Ubuntu VM on a XenCenter server.

One of my Flask apps using Gunicorn (directly, not behind Nginx) doesn't seem to work on that server. It works in Docker locally, but on the server I get the following exceptions:

```
[2015-07-30 16:41:52 +0000] [13] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 187, in handle_request
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python3.4/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/http/wsgi.py", line 411, in write_file
    self.sendfile_all(fileno, self.sock.fileno(), fo_offset, nbytes)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/http/wsgi.py", line 365, in sendfile_all
    sent += sendfile(sockno, fileno, offset + sent, nbytes - sent)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

I'm not sure what exactly is causing the problem, but it doesn't seem to happen when using the devserver (in the same Docker setup).

**Comment by dbrgn** [comment]
With `uwsgi` it seems to work too.

**Comment by benoitc** [comment]
what if you run gunicorn with `--no-sendfile`?

**Comment by tilgovi** [comment]
I would be interested to know what filesystem is on the host, too.

**Comment by dbrgn** [comment]
The host runs on ext4, as far as I remember (it was at work).

I'll test the ``--no-sendfile`` option tomorrow and will let you know.

**Comment by dbrgn** [comment]
Docker host:

```
$ docker info
Containers: 5
Images: 31
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 3.866 GiB
Name: moby
ID: VFHD:COTH:2VC2:ZFNI:QKZZ:TXR7:LMK6:J4TM:Q5IO:7PXD:7R5J:KTZ4
WARNING: No memory limit support
WARNING: No swap limit support
```

With ``--no-sendfile`` and current ``master`` of Gunicorn, the exception above does not occur anymore.

**Comment by benoitc** [comment]
By default sendfile is off on nginx. Is this enable in your conf?

**Comment by dbrgn** [comment]
There is no Nginx involved. Just plain Gunicorn.

**Comment by benoitc** [comment]
i meant when you tested with nginx....aka uwsgi.

**Comment by dbrgn** [comment]
Again, no nginx involved. I used the uwsgi program, not the uwsgi protocol through nginx.

**Comment by benoitc** [comment]
@dbrgn OK.

I looked at the [uwsgi documentation](http://uwsgi-docs.readthedocs.org/en/latest/StaticFiles.html) and it seems they are not using sendfile by themselves but instead rely on nginx or offer a possibility  to offload an send files using threads.

#1094 could probably helps to fix it anyway. 

> I wonder if we couldn't have also a way to offload file sending too.

**Comment by tilgovi** [comment]
Any help testing #1094 would be greatly appreciated. I've only done some manual tests.

**Comment by benoitc** [comment]
@tilgovi i will set a docket env and will let you know until thursday.

**Comment by benoitc** [comment]
we can probably close that ticket. cc @tilgovi

**Comment by tilgovi** [comment]
@dbrgn any chance you can experiment with master?

**Comment by dbrgn** [comment]
Sorry, I don't have access to that test environment anymore...

**Comment by tilgovi** [comment]
I'm going to close this and if someone comes upon a similar issue using Docker they can comment.

**Comment by cookkkie** [comment]
I have the exact same issue

**Comment by tilgovi** [comment]
@cookkkie can you test with master, by chance?

**Comment by tilgovi** [comment]
Or if someone can make a repro example I can look.

**Comment by pmayer** [comment]
I'm having the same issue with django and gunicorn in docker. It happens roughly once a day and I don't really know how to reproduce it.

**Comment by artyomtugaryov** [comment]
I'm having the same issue with Flask and gunicorn in Docker. It happens every time when I using flask.send_file for sending a large file.

**Comment by benoitc** [comment]
@artyomtugaryov do you have any simple code to help us to reproduce the issue. It doesn't have to be complete just show us the request handler and the functions call for it would help.
