### ISSUE TITLE
can't change the proctitle of master process

### ISSUE THREAD

**Issue by cryinstall** [benoitc/gunicorn#1093]
arbiter.py:

change over line 166 and line 167, make default proc title setting firstly so that I could change to custom title on  'when_ready'

```
def run(self):
    "Main master loop."
    util._setproctitle("master [%s]" % self.proc_name)
    self.start()
```
```
def when_ready(server):
    import setproctitle
    setproctitle.setproctitle('my_gunicorn_master')
```

**Comment by tilgovi** [comment]
Couldn't you set "server.proc_name"?

**Comment by cryinstall** [comment]
hi tilgovi,
the proctitle will set to 'gunicorn: master $proc_name' if I use server.proc_name,  
actually I couldn't use monitor tool to assign a name like this, or  kill use `killall $proc_name`,
and `ps -c -a`  doesn't show  my proc_name

**Comment by benoitc** [comment]
Why not simply using the `--name` [setting](http://docs.gunicorn.org/en/19.3/settings.html#proc-name) ? Is there any reason to remove gunicorn from the name?

**Comment by tilgovi** [comment]
@cryinstall gunicorn does not specifically set the process title to say "gunicorn" and from the code the master should be calling itself "master [%s]" where the interpolated value is the `--name` setting.

If you want to remove "gunicorn" from the name, you can create a symlink to `gunicorn` and it will have that name.

Is there more you need from this?

**Comment by benoitc** [comment]
@tilgovi maybe we can drop a note in the documentation? Other than that i think it's ok to close the issue.

**Comment by tilgovi** [comment]
Closing. Can re-open if we get more information.
