### ISSUE TITLE
Workers hanging when using requests future sessions in 2.7

### ISSUE THREAD

**Issue by jameskhedley** [benoitc/gunicorn#1100]
Following script runs with Flask dev server (and apache/modwsgi) but not gunicorn:

    from requests_futures.sessions import FuturesSession
    from flask import Flask
    app = Flask(__name__)
    
    session = FuturesSession()
    future = session.post(url="https://localhost:8000", 
                          data=u"name=myname&password=abc123",
                          **{'headers': {'Content-Type': 'application/x-www-form-urlencoded'}})

    print future.result()

This results in some console output:

    $ /usr/local/bin/gunicorn test2:app --workers=1 -t 5 -b 127.0.0.1:8080 --spew > /tmp/spew2
    [2015-08-19 14:05:15 +0000] [6872] [INFO] Starting gunicorn 19.3.0
    [2015-08-19 14:05:15 +0000] [6872] [INFO] Listening at: http://127.0.0.1:8080 (6872)
    [2015-08-19 14:05:15 +0000] [6872] [INFO] Using worker: sync
    [2015-08-19 14:05:15 +0000] [6877] [INFO] Booting worker with pid: 6877
    [2015-08-19 14:05:20 +0000] [6872] [CRITICAL] WORKER TIMEOUT (pid:6877)

I set t=5 here but it still happens with t=30.

Here's the end bit of the spew output, it's long so [pastebinned](http://pastebin.com/N015atgc).

**Comment by jameskhedley** [comment]
Hmm, I tried this in uwsgi today with the same result! So, maybe something wrong with requests..?

**Comment by tilgovi** [comment]
No follow-up. @jameskhedley bump this open if you have some more info. Thanks!
