### ISSUE TITLE
[Q] Bind to a file descriptor?

### ISSUE THREAD

**Issue by Ashald** [benoitc/gunicorn#1107]
Hi guys,

I guess whether it's possible to bind gunicorn to a file descriptor of the open socket? I looked at the code and it seems that there is some code that does this in `sock.py` but I'm not sure whether it's only for child workers purposes or I can specify that in `--bind` parameter somehow.

Thanks!

**Comment by benoitc** [comment]
You can bind it to a unix socket yes: `gunicorn -b unix:/path/to/socket ...`:
http://docs.gunicorn.org/en/19.3/run.html?highlight=unix#commonly-used-arguments

**Comment by Ashald** [comment]
@benoitc please note that I'm talking about `file descriptors`, not about `unix sockets`.

This is done using `socket.fromfd` func. There is already partial support for this in [`gunicorn.sock:create_sockets`] (https://github.com/benoitc/gunicorn/blob/89562c776e99b6e74a5fc6192372986a7fa2d131/gunicorn/sock.py#L138), but it can be used only with `systemd`. It'd be nice to follow other WSGI servers examples (like uWSGI, Chaussette etc) and add `fd://<number>` as one of supported schemas to `--bind`.

It's very useful in cases when user prefers to use process/socket management software like Supervisor or Circus (they can open sockets and pass their `fd`s into child processes).

**Comment by tilgovi** [comment]
A patch for `fd://` as a bind syntax sounds fine to me.

**Comment by benoitc** [comment]
indeed a PR would be accepted for it. Though it already works for systemd using the `LISTEN_FDS` environnement setting anyway. 

> Would be good if someone could champion a standard instead of expecting from other to maintain their own api...

**Comment by benoitc** [comment]
@Ashald ?

**Comment by Ashald** [comment]
Although I still believe that this functionality would be great right now I do not have time to contribute it. Maybe later this year.

**Comment by hramezani** [comment]
@benoitc, @tilgovi , I checked the `sock.py` and `arbiter.py`. it is difficult to implement this feature. because when we pass `fds` to `create_sockets` function, this creates sockets by fds and return listeners. in this case, other bind options(tcp and unix socket) are not considered. 
can you help me? I want to add this feature.

**Comment by apollo13** [comment]
Initial PR at #1809 -- comments appreciated
