### ISSUE TITLE
Is there a way to run Gunicorn frontend with application user account and backend to run flask app using root privilege

### ISSUE THREAD

**Issue by rrajaravi** [benoitc/gunicorn#1111]
I have a flask app that needs root privilege. I am able to demonize the app using gunicorn with root user. I assume that When guicorn handles the http request, it handles using the same root user privilege. I want that http(frond end) part to be running using an application user and flaskapp(backend) part to be running with root privilege. is there any way to do it with gunicorn?

**Comment by benoitc** [comment]
@rrajaravi yes you can play with the `--group`, `--user` and `--umask` settings for it. They allows you to start the worker under another user or group. Makes sure to correctly set the umask if you want to share the unix socket with the proxy and the temporary files with the arbiter launched as root.

**Comment by rrajaravi** [comment]
I'm running my flask app using gunicorn --user root user account and i'm not using any other web services like nginx, apache to serve static files. Here my question is,   Exposing my flask app using gunicorn which is running with root credentials, will that cause any security issues for my web application?

**Comment by benoitc** [comment]
using `--user=root` settings means that the worker will run as root. 

So your application will run as root and you risk to expose your system. Why do you need to run your application as root? Why starting the arbiter as root then the workers using a different user couldn't work?

**Comment by rrajaravi** [comment]
my application does system level configuration changes and handles installation, thus requires root privilege. Providing sudo privilege seems to be not good as sudo prompts tty, generates error ' no required tty'. The error can be solved by modifying sudoers file to add 'required no tty'.  But I want the root privilege for application through any other way then sudo which doesn't expose security issue.

**Comment by benoitc** [comment]
@rrajaravi I misunderstood your question I guess. If you only need to have the backend working as a root why not simply sharing a unix socket between your applications and gunicorn. Then you only need to give access to the socket in the application (using the environment or by the conf). The workers only needs to have a way to write and read on that socket. 

> The socket can also be a TCP socket, a ZMQ socket whatever...

**Comment by benoitc** [comment]
no answer since. closing the issue.
