### ISSUE TITLE
sync worker setting causes Traceback

### ISSUE THREAD

**Issue by rahulbishain** [benoitc/gunicorn#1120]
I am using an nginx+gunicorn setup for our django application. I tried gunicorn with the following settings:
worker_class = 'sync'
max_requests = 4
and observed the following errors (frequent, almost every 15 minutes or so when the application was being used by couple of users.) in the nohup file: This apparently did not seem to cause any application related issue as the application seemed to be working fine.  But during the live run (with almost 100+ users trying to login) gunicorn kept crashing every minute or so and woudnt be brought up by supervisord. any help would be highly appreciated
Unhandled exception in thread started by <bound method Reloader.__bootstrap of <Reloader(Thread-1, stopped daemon 140162676709120)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 823, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'

**Comment by rahulbishain** [comment]
Just wanted to add, that I later tried increasing max_requests to 40 but gunicorn still kept crashing. Finally changed to gevent with threads = 10 (and later removed threads and max_requests setting altogether), the system was now stable but many users complained of an extremely slow application response. (I am very new to application development so have tried these different settings with my limited knowledge of web apps. Currently I have resorted to using 'gevent' with workers=3*cpu+1 and with no other specifications but still face the issue of an unresponsive app, although it doesnt happen for all users)

**Comment by benoitc** [comment]
which version of gunicorn are you running?

**Comment by rahulbishain** [comment]
We are using 19.1.1

**Comment by benoitc** [comment]
So I don't reproduce this error at all.  Can you give me more info? How you're launching gunicorn, which kind of app (any snippet would be appreciated).

> Using --threads with the gevent worker won't do anything. Is your application doing any blocking work?

**Comment by rahulbishain** [comment]
We are using a shell script which uses the below:
nohup gunicorn app_name.wsgi --daemon -c gunicorn.conf.py --log-level debug --reload &

also, there is a supervisor running in the background
This app is used for auto evaluation of student assignments (their submissions are basically small cpp programs. so the students log in, upload their programs and try to evaluate/grade their submissions through the application). There was no on screen error as such. Just the students got 502 'bad gateway'  error, when I realized that gunicorn was down. After this we tried changing the parameters for sync workers (increased max_requests to 40 from 4, subsequently increased workers to 50 from 15) and restarted gunicorn, but it kept crashing (this time we did not notice any tracebacks).

**Comment by syaiful6** [comment]
hi @rahulbishain try use something like https://gist.github.com/syaiful6/200154f4d66bb2c0563b

Dont start it as daemonize if you use supervisor.

**Comment by rahulbishain** [comment]
Thanks syaiful. Will try your suggestion.

**Comment by benoitc** [comment]
@rahulbishain 
> After this we tried changing the parameters for sync workers (increased max_requests to 40 from 4, subsequently increased workers to 50 from 15) and restarted gunicorn, but it kept crashing (this time we did not notice any tracebacks).

Do you have a full log session with debug log level ? Why are you using max_requests? i'm interresting in the crash reason here. If max requests is achieved that is perfectly normal though. The NoneType issue should be fixed anyway.

**Comment by rahulbishain** [comment]
Hi,
Sorry I do not have the logs for this issue. I am unable to replicate it
myself now. I think it better to close the issue for now.

**Comment by tilgovi** [comment]
Thanks for following up. Please re-open or create a new issue if you replicate the problem and can provide more detail!
