### ISSUE TITLE
Documentation heading text should use the hyphens instead of underscore.

### ISSUE THREAD

**Issue by technochakra** [benoitc/gunicorn#1123]
See related issue https://github.com/benoitc/gunicorn/issues/1122

Priority: Low.
Type: Documentation improvement.

The gunicorn documentation uses heading text with underscores even though the actual option requires one to use hyphens.  The correct text is the one with hyphens.  If a user mistakenly copies from the heading text, the option is unrecognized at runtime.
  
For example I ran into this confusion when using the --ca-certs option as documented at  http://gunicorn-docs.readthedocs.org/en/latest/settings.html#ca-certs
It would be nice to have all heading text in the documentation match the actual option so that it doesn't cause any confusion.   

Please view the above link for more details.

**Comment by tilgovi** [comment]
The underscore version is correct if you set those variables in a configuration file (`--config`).

**Comment by benoitc** [comment]
Yup I am not sure it should be changed there. Maybe the introduction how ever is misleading:

> This is an exhaustive list of settings for Gunicorn. **Some settings are only able to be set from a configuration file**. The setting name is what should be used in the configuration file. The command line arguments are listed as well for reference on setting at the command line.

Also maybe we should generate a `usage` documentation showing only command line options?

**Comment by benoitc** [comment]
closing this issue as WONT FIX. Seems like the correct behavior right now. If someone thinks it's needed we can open a new ticket to create this specific command line usage page.

**Comment by shongololo** [comment]
I would suggest that the documentation wording should be clarified so that it is fairly obvious that if setting in the config file, just replace hyphens with underscores...
