### ISSUE TITLE
19.4 release on 2015-11-02

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1139]
this ticket to prepare the release of gunicorn 19.4. If you see any PR that could be merged right now let's track it here. Thanks!

> Sorry for the short notice. Next will be done with a few more days in advance.

**Comment by benoitc** [comment]
cvc @tilgovi @berkerpeksag

**Comment by dstufft** [comment]
Any idea how long until this happens?

**Comment by benoitc** [comment]
@dstufft working on it. by the end of the we anyway.

**Comment by dstufft** [comment]
Awesome, great.

**Comment by benoitc** [comment]
@tilgovi @berkerpeksag if none of you object will release our current master + tornado worker fix. Let me know :)

**Comment by berkerpeksag** [comment]
+1 for release. #1136 looks good to me.

**Comment by tilgovi** [comment]
No problem

**Comment by benoitc** [comment]
the release is ready in 5d902e2a07ecfb35f750b983c269b541fe841c5e . #1148 is a blocker though. The change has indeed ben introduced in this release via #1069 . Can we solve it today?

**Comment by benoitc** [comment]
#1148 have been fixed. 

#1151 is the new blocker though. Any feedback is welcome  :)

**Comment by fourbytes** [comment]
Any ETA on this now? #1151 looks to have been resolved.

**Comment by benoitc** [comment]
afaik it is released: https://pypi.python.org/pypi/gunicorn/ :)
