### ISSUE TITLE
Intermittent AttributeError:  workers not loading full app into memory

### ISSUE THREAD

**Issue by dwickwire** [benoitc/gunicorn#1143]
Hello,

I'm running a django 1.4 ecommerce app on gunicorn 0.14.5 and I'm trying to upgrade to 19.3.0 however I've been getting intermittent Attribute errors where a class is not a member of the imported models namespace. 

For example, I have this import at the top of my forms.py file:
```python
from membership import models as membership_models
# ....
            membership = user.get_current_membership() if user.is_authenticated() else None
            if isinstance(membership, membership_models.Membership):
                existing_free_products_count = membership.free_products.count()
```

Now only *periodically*, it fails with this attribute error.   That is, sometimes it hits this codepath without failing but sometimes it fails like so:
```
  File "/path/to/forms.py", line 234, in clean
    logger.info('membership models: %s' % str(membership_models.Membership))
AttributeError: 'module' object has no attribute 'Membership'
```
(This is true for the same session.  Like, I can go back and refresh and then try and reproduce and it does not fail)

I'm creating a bug here because it almost feels like some unicorn workers aren't loading the entire app into memory, which is really weird but I haven't a clue what else might be going on.  How else can I debug this?

Here's the relative part of my upstart config:
```conf
exec sudo -u $RUN_AS \
    $ENV_PATH/bin/gunicorn myapp.wsgi:application \
    --worker-class sync \
    --bind $SOCKET \
    --pid $PIDFILE \
    --user $RUN_AS \
    --group $RUN_AS \
    --umask $UMASK \
    --access-logfile $ACCESS_LOG \
    --error-logfile $ERROR_LOG \
    --workers $MAXCHILDREN \
    --max-requests $MAXREQUESTS \
    --pythonpath $SITE_PATH \
    --env DJANGO_SETTINGS_MODULE=$SETTINGS \
    --settings=$SETTINGS >> $STDOUT_LOG 2>>$STDERR_LOG
```

Note:  I've been better success reproducing this bug with the following steps:
1.  restart upstart
2.  open incognito
3.  add an item to the cart and proceed to checkout/remove item from cart which triggers that code path

**Comment by dwickwire** [comment]
One more thought:  we use 19.3.0 on a django 1.8 app and don't have any issues like this.  Perhaps its related to 19.3.0 together with django 1.4?

**Comment by benoitc** [comment]
what do you mean by later? when does it happen exactly?

**Comment by dwickwire** [comment]
By later I only meant "later" down in the code of that file.  The `membership_models.Membership` is what's throwing an attribute error because it doesn't realize its been imported at the top of the file.  To repeat myself slightly, this is intermittent and so it fails sometimes and other times it passes.

I'm not sure how else to debug this.  FWIW, we've just upgraded to django 1.8 on the app which contains this code and we are no longer having this issue, so it does indeed seem related to something between Gunicorn 19.3.0 and django 1.4, but I'm not sure what that might be.

**Comment by benoitc** [comment]
django 1.4 is 3 years old. I am temped to ignore that issue if it works with the latest stable. @tilgovi @berkerpeksag thoughts?

**Comment by tilgovi** [comment]
@benoitc fine for me. If someone comes along with a strong need and a fix we can do something, but it's hard to investigate more from here.
