### ISSUE TITLE
Error in the demo

### ISSUE THREAD

**Issue by jenia** [benoitc/gunicorn#1145]
Hello.

The last line in the demo example should be 

    return [bytes(data, "utf-8")]

**Comment by berkerpeksag** [comment]
Thanks for the report. Can you point the location of the demo? If you're talking about the one at http://gunicorn.org/, I think `data = "Hello, World!\n"` should be changed to `data = b"Hello, World!\n"`.

**Comment by jenia** [comment]
Hi Berkerpeksag.

Yea, the example on http://gunicorn.org
I think what you said should work perfectly well. But it's better to make the change though ;)
