### ISSUE TITLE
error while running tests under py3.5

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1150]
test_arbiter is failing under python 3.5:

https://travis-ci.org/benoitc/gunicorn/jobs/92251687

I didn't have a closer look on it yet but any help is appreciated. cc @berkerpeksag

**Comment by berkerpeksag** [comment]
This was a problem in pytest and they fixed it in a recent release of it. I'll update our pytest dependency when I get home tonight.

**Comment by benoitc** [comment]
@berkerpeksag i bumped the version but it isn't enough apparently :/ Let me know if you find anything :)
