### ISSUE TITLE
Is the --no-sendfile default confusing?

### ISSUE THREAD

**Issue by tilgovi** [benoitc/gunicorn#1156]
If you check the usage for gunicorn, the `--no-sendfile` option says:

      --no-sendfile         Disables the use of ``sendfile()``. [True]

To me, this looks like `--no-sendfile` defaults to `True` and that sendfile will by disabled by default.

**Comment by nMustaki** [comment]
I have just noticed this option this afternoon so I can give you my 2cents : the "True" is a bit misleading, but the name of the option itself "no-sendfile" is self-explanatory. I wouldn't expect this to be the default because then it wouldn't have any purpose.

**Comment by benoitc** [comment]
> To me, this looks like --no-sendfile defaults to True and that sendfile will by disabled by default.

Me either. This is misleading if you read:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/http/wsgi.py#L349-L350

I guess we should fix it.

**Comment by benoitc** [comment]
@tilgovi what do you think we could do there?

**Comment by tilgovi** [comment]
https://github.com/benoitc/gunicorn/compare/1156-clarify-sendfile-defaults?expand=1

I'm not sure how much better it is. Usage ends up looking like this:

    > gunicorn --help | grep sendfile
      --sendfile [SENDFILE]
                            Enables the use of ``sendfile()``. [True]
      --no-sendfile         Disables the use of ``sendfile()``. [None]

Valid command lines look like these:

- `gunicorn --sendfile -- module:app`
- `gunicorn --sendfile false module:app`
- `gunicorn --sendfile=false module:app`
- `gunicorn --no-sendfile module:app`

Default is `True`. I left the default for `--no-sendfile` as `None` so that there was no need to reason about precedence or introduce parser-level defaults to the configuration system.

The other weird thing is the fact that both will show up in the html documentation. Not sure what to do about that.

Feedback welcome.

**Comment by tilgovi** [comment]
Most confusing is the fact that I current have the `name` of the `--no-sendfile` option set to `no sendfile`. This is weird because it's the only thing that will show up in the documentations with a space instead of an underscore, but I didn't want people to think they could put `no_sendfile = True` in their gunicorn.conf.py file. Maybe just better documentation would make sure of that, or we could keep the `--no-sendfile` option out of the documentation to prevent confusion.

**Comment by benoitc** [comment]
why do we have so much options though. IMO sendfile should be either disable or enable. Why not introducing a --disable-sendfile option and deprecate older options?

**Comment by tilgovi** [comment]
Fine for me, but this was on the current milestone and I didn't want to
remove a CLI option in a patch release.

**Comment by berkerpeksag** [comment]
@tilgovi's patch looks good to me for 19.x.

**Comment by tilgovi** [comment]
Another option is to introduce parser-level default so `--no-sendfile` shows as `[None]` in the usage printout.

What do you think @benoitc?

**Comment by tilgovi** [comment]
I think I prefer this because it's much simpler, but I don't know if `is not False` is offensive to anyone ;).

https://github.com/benoitc/gunicorn/compare/1156-clarify-sendfile-defaults-alt?expand=1

**Comment by benoitc** [comment]
@tilgovi good idea!

What to you think about introducing `--sendfile=no` command? and deprecate the `--no-sendfine` ? So we only keep one command line. cc @berkerpeksag

**Comment by benoitc** [comment]
@tilgovi i'm fine with the is not false :)

**Comment by tilgovi** [comment]
Let's merge the second one, the -alt branch I just posted, then.

That is good for a patch release and then we can decide how to handle enable/disable flags and documentation for them for R20.

**Comment by berkerpeksag** [comment]
1156-clarify-sendfile-defaults-alt looks good to me.

**Comment by benoitc** [comment]
+1
