### ISSUE TITLE
Serving static files via whitenoise and gevent worker broken in 19.4

### ISSUE THREAD

**Issue by slafs** [benoitc/gunicorn#1162]
In gunicorn 19.4.x running an app that is serving static files via [whitenoise](http://whitenoise.evans.io/en/latest/) with gevent worker class seems broken. 

It looks like the connection while serving a given file hangs and thus client gets only some part of it (also from the number of downloaded bytes it looks like the connection hangs after downloading a multiple of 4kB). The behaviour can be observed on CentOS 6 (I couldn't reproduce it in Ubuntu for example) but also it's fairly easy to reproduce it with Docker (even based on the official Debian python image).

I've setup a Docker image in my repo (https://github.com/slafs/dockerfiles/tree/master/whitenoise-gunicorn-gevent-bug) and described steps to reproduce the bug there. 

Version `19.3` of gunicorn works fine.

**Comment by benoitc** [comment]
Thanks, will try ASAP. Did you also tried with the latest master ?

- benoit

**Comment by slafs** [comment]
Oh, yes. Current master seems to be working fine also, thanks.

**Comment by tilgovi** [comment]
Sounds like #1155.
