### ISSUE TITLE
test_factory in test_gaiohttp fails on 3.4+

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#1164]
Here's the output: https://travis-ci.org/benoitc/gunicorn/jobs/96861325

I haven't had a chance to investigate this further, could it be related to aiohttp?

**Comment by benoitc** [comment]
maybe we should upgrade gaihttp requirements ? cc @asvetlov

**Comment by benoitc** [comment]
ping @asvetlov it seems latest version of aiohttp doesn't work with gunicorn on latest python.

**Comment by benoitc** [comment]
@berkerpeksag change above fix it. Let me know what you think about it.

**Comment by berkerpeksag** [comment]
@benoitc looks good, but it contains unrelated changes from https://github.com/benoitc/gunicorn/pull/1168.

**Comment by benoitc** [comment]
yeah wanted that all tests pass :)

**Comment by asvetlov** [comment]
The fix looks good.
