### ISSUE TITLE
test OSX and other platforms in CI

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1170]
we should automate tests on all platform so things like d199e76cea45bb006eb15748da3fcb24754b21f0 can never happen again. 

IS there any CI service open-source friendly around that allows that? If not I can borrow a machine to someone that knows how to setup such things :)

Note the CI should support the following:
- Linux
- OSX/ Darwin
- FreeBSD
- NetBSD
- OpenBSD
- DragonflyBSD

if I forgot an OS just let me know. Also we should prepare us to test gunicorn on windows. 

Feedback/Help is welcome!

**Comment by benoitc** [comment]
https://buildkite.com looks interesting for that. Any opinion?

**Comment by tilgovi** [comment]
Indeed. Never used it. I don't see alternatives other than Jenkins or some other such thing we host ourselves.

**Comment by benoitc** [comment]
gitlab allows to have multiple runner we can plug to it:

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

I'm thinking to switch to it, at least for the CI. Thoughts?

**Comment by benoitc** [comment]
cc @tilgovi @berkerpeksag

**Comment by berkerpeksag** [comment]
Anything we won't have to maintain and can be used with GitHub is good IMO :) Do we have need to support all *BSDs? We can probably start with FreeBSD and OpenBSD. I can ping some FreeBSD people and ask for help if we can't find a suitable CI service.

**Comment by benoitc** [comment]
stalled issue
