### ISSUE TITLE
Slight text change on logging

### ISSUE THREAD

**Issue by jjvattamattom** [benoitc/gunicorn#1173]
In http://docs.gunicorn.org/en/19.3/settings.html#logging I guess a slight text change could convey message better.

In the section:

```
errorlog
--error-logfile FILE, --log-file FILE
-
The Error log file to write to.

“-” means log to stderr.
```

The last line should read:

```
Using - for FILE makes gunicorn log to stderr
```

Thanks for making Gunicorn!

**Comment by benoitc** [comment]
just did it thanks!
