### ISSUE TITLE
Correctly handle unavailable .fileno() support for io.BytesIO instances

### ISSUE THREAD

**Issue by wbolster** [benoitc/gunicorn#1174]
The changes introduced in https://github.com/benoitc/gunicorn/commit/98c9e3b3756717771fd6521dbb2dbec206ec5fc5#diff-6607b435d6ee868f251dbdd1a6d0edecL357 are wrong and lead to crashes for `io.BytesIO` instances which do have a `.fileno()` method but raise another exception instead:

```
>>> import io
>>> io.BytesIO().fileno()
Traceback (most recent call last):
  File "<ipython-input-3-7062c09d0c52>", line 1, in <module>
    io.BytesIO().fileno()
UnsupportedOperation: fileno
```

This exception was already caught properly in the earlier code, a few lines below.

**Comment by wbolster** [comment]
I guess this is a critical bug since it breaks a lot of cases like `flask.send_file()` (other frameworks with similar features aas well) with a `io.BytesIO()` instance, which is a rather common pattern.

**Comment by benoitc** [comment]
@wbolster thanks for the ticket. Can you test the change above?

@tilgovi what do you think about it?

**Comment by wbolster** [comment]
fwiw, `BytesIO` is specifically intended to be a file like object (according to the vague python definition of that term), so having a function `is_fileobject()` return `False` violates the principle of least surprise. :)  

I guess we were both looking at this at the same time, and I just posted #1176 with an alternative...

**Comment by benoitc** [comment]
Thanks for the patch!

The solutions are similar but I quite like the idea of having a function apart for it, so it may be later unit-tested eventually. 

File objects were better defined in old versions (and Gunicorn starts to get old) [1] . I see now that it has been reduced. Although this tests is done there to test if the file-like object return a usable file descriptior so we can use [`sendfile(2)`](http://man7.org/linux/man-pages/man2/sendfile.2.html) .So indeed we should change the name of the function to make it more descriptive. Thoughts?

[1] https://docs.python.org/2.5.2/lib/bltin-file-objects.html
[2] https://docs.python.org/3/glossary.html#term-file-object

**Comment by wbolster** [comment]
`is_usable_for_sendfile()`, or `has_fileno()`. or just `obtain_fileno()` in true eafp style but that requires a well defined exception.

**Comment by DCuddies** [comment]
Hi,

I'm not sure if this is exactly related, but I'm having a similar issue with the following Traceback:

Traceback (most recent call last):
  File "/home/dale/.local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/dale/.local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/home/dale/.local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 398, in write_file
    if not self.sendfile(respiter):
  File "/home/dale/.local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 357, in sendfile
    fileno = respiter.filelike.fileno()

Here is a git copy if it helps: https://github.com/DCuddies/simplecontract

I'm using BytesIO in order to store a docx object, and then let the users download that docx object.

I'm at a loss at this point as to how to fix the issue, any help would be appreciated.

**Comment by benoitc** [comment]
@DCuddies sorry have been side tracked. Patch is now is master. If everything goes fine, i will make a release over the week-end.

**Comment by benoitc** [comment]
@wbolster merged #1175 . Patch makes sure that in case the `fileno` method doesn't exist or is unavailable we fallback to the iteration loop.

**Comment by DCuddies** [comment]
@benoitc That's great, thanks.

**Comment by tilgovi** [comment]
Sorry I have been offline. Thanks for the support @benoitc. I will be more proactive about getting good feedback and testing, even for these one line fixes, going forward.

**Comment by benoitc** [comment]
@tilgovi np :) thanks for all the work you already do anyway :)

**Comment by wbolster** [comment]
awesome. any chance of cutting a new release? currently `pip install gunicorn` results in broken deployments in many environments.  (and gunicorn is often treated differently from normal requirements.txt entries)

**Comment by benoitc** [comment]
19.4.4 has just been released. enjoy! cc @wbolster @DCuddies

**Comment by tuco86** [comment]
```
Traceback (most recent call last):
  File ".env/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File ".env/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 163, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File ".env/lib/python2.7/site-packages/gunicorn/workers/async.py", line 110, in handle_request
    resp.write_file(respiter)
  File ".env/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 396, in write_file
    if not self.sendfile(respiter):
  File ".env/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 360, in sendfile
    offset = os.lseek(fileno, 0, os.SEEK_CUR)
NameError: global name 'fileno' is not defined
```

this doesn't seem right either, does it?

**Comment by tuco86** [comment]
see #1178

**Comment by DCuddies** [comment]
The update fixed it, thanks!

**Comment by zoltan-fedor** [comment]
I use 19.4.5 with flask and can't get around this issue either with the wsgi-disable-file-wrapper config param or with the del(request.environ['wsgi.file_wrapper'])

Here is my code:

```
    barc = barcode.get(reg.barcode_type, reg.registration_id, writer=ImageWriter())
    # write the barcode into a file-like object
    #del(request.env['wsgi.file_wrapper'])
   del(request.environ['wsgi.file_wrapper'])
    i = io.BytesIO()
    barc.write(i, {'module_height':10.0, 'text_distance':0.5, 'font_size':9}) 
    i.seek(0)  # seek to the beginning of the file
    return send_file(i,
                     attachment_filename='barcode.png',
                     mimetype='image/png')

```

Throws error:

> io.UnsupportedOperation: fileno
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "./app/main/views.py", line 731, in get_barcode
>     mimetype='image/png')
>   File "/usr/local/lib/python3.5/site-packages/flask/helpers.py", line 523, in send_file
>     data = wrap_file(request.environ, file)
>   File "/usr/local/lib/python3.5/site-packages/werkzeug/wsgi.py", line 726, in wrap_file
>     return environ.get('wsgi.file_wrapper', FileWrapper)(file, buffer_size)
> SystemError: <built-in function uwsgi_sendfile> returned a result with an error set
