### ISSUE TITLE
AttributeError when running gunicorn over HTTPS

### ISSUE THREAD

**Issue by TheMetaphorer** [benoitc/gunicorn#1177]
When running gunicorn with my certificate and keyfile over https, sending any request to the server gives me this error. 
```
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.run()
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 119, in run
    self.run_for_one(timeout)
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 66, in run_for_one
    self.accept(listener)
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
    self.handle(listener, client, addr)
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 141, in handle
    self.handle_error(req, client, addr, e)
  File "/opt/bitnami/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 213, in handle_error
    self.log.exception("Error handling request %s", req.uri)
AttributeError: 'NoneType' object has no attribute 'uri'
```

**Comment by benoitc** [comment]
Hi, thanks for the ticket! I don't reproduce it right now, can you give more detail?

how can I reproduce it? Which versions of Gunicorn are you running?

**Comment by TheMetaphorer** [comment]
I'm using 19.4.3. I ran it using the `--certfile` arguments and the `--keyfile` arguments, and provided an SSL Certificate and keyfile. However, whenever attempting to send a request, I simply get the above error.

**Comment by tilgovi** [comment]
This traceback appears when a client attempts to connect via HTTP (not HTTPS).

**Comment by tilgovi** [comment]
Either we can catch the `SSLError` in the base class `handle_error`:

	diff --git a/gunicorn/workers/base.py b/gunicorn/workers/base.py
	index 9ba8e75..488c2ea 100644
	--- a/gunicorn/workers/base.py
	+++ b/gunicorn/workers/base.py
	@@ -10,6 +10,7 @@ import sys
	 import time
	 import traceback
	 from random import randint
	+from ssl import SSLError
	 
	 
	 from gunicorn import util
	@@ -181,7 +182,8 @@ class Worker(object):
	         if isinstance(exc, (InvalidRequestLine, InvalidRequestMethod,
	                 InvalidHTTPVersion, InvalidHeader, InvalidHeaderName,
	                 LimitRequestLine, LimitRequestHeaders,
	-                InvalidProxyLine, ForbiddenProxyRequest)):
	+                InvalidProxyLine, ForbiddenProxyRequest,
	+                SSLError)):
	 
	             status_int = 400
	             reason = "Bad Request"

Or we should maybe move/change the line that depends on `req.uri` for logging the exception in the corresponding `else` clause.

This is a little verbose, even for debug, maybe:

	[2016-01-07 13:25:43 +0000] [16469] [DEBUG] Error processing SSL request.
	[2016-01-07 13:25:43 +0000] [16469] [DEBUG] Invalid request from ip=127.0.0.1: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1752)
	[2016-01-07 13:25:43 +0000] [16469] [DEBUG] Failed to send error message.

**Comment by benoitc** [comment]
@tilgovi the second solution is more explicit, isn't it?

**Comment by tilgovi** [comment]
@benoitc which? You mean moving the `req.uri` logging? I think I like that better.

**Comment by tilgovi** [comment]
We shouldn't be trying to use `req.uri` before we know it's valid, probably. That is easier to reason about.

**Comment by stgarf** [comment]
Excellent, just hit this :)
gunicorn (version 19.4.5)
Python 2.6.6

I'm using the patch at the moment because it at least stops the tracebacks in my output :+1:

**Comment by benoitc** [comment]
@tilgovi agree. go ahead :)

**Comment by Soviut** [comment]
For posterity, I also encountered this with gunicorn 19.4.5 running Python 2.7.3.

**Comment by edwardotis** [comment]
I'm confused. 
Gunicorn crashes immediately when failing to handle any non-https request after I provide a certfile and keyfile. Just make a GET request from any recent version of Chrome.
This means: Anybody, malicious or not,  can bring down a gunicorn server by trying to use http requests.

This behavior is not being considered a bug or even a priority?

gunicorn (version 19.4.5)
Python 3.5.1

**Comment by benoitc** [comment]
@edwardotis well patches are always welcome. people have been busy. anyway it will be fixed in this week release.

**Comment by edwardotis** [comment]
@benoitc Thanks, good to hear. Just surprised that the bug label was avoided during this discussion, when this presents a great security risk to the server.

**Comment by benoitc** [comment]
@edwardotis if you have some time please test the PR above. It should fix the issue. Let me know :)

**Comment by benoitc** [comment]
@edwardotis it's actually merged ;)

**Comment by atodorov** [comment]
Hi guys,
I see this has been merged already, will give it a try locally. However can you explain what exactly happens here ? 

If I access an https URL with a self signed certificate I see the above exception but the page still loads. This is done locally while testing a Django app. The same app, with same settings on Google Container Engine dies with a 500 error. I don't think I'm having the same problem, maybe only seeing the same exception intermittently in the logs. However I have no idea how to debug my particular problem ATM.

**Comment by benoitc** [comment]
"the page still load" which page?

**Comment by atodorov** [comment]
well the one which after I visit it produces errors in the logs

**Comment by benoitc** [comment]
sorry but i don't understand. where do you see the exception? how can ireproduce the issue?

the patch fixed the following:

- return a 403 error when smth bad with ssl happen
- test if the  request uri have already been parsed before trying to log . this one prevent any crash we had previously due to this.

**Comment by atodorov** [comment]
Hi @benoitc,
I have a Django app, using gnucorn. This is running in Google Cloud Engine with a self-signed SSL certificate. On some app URLs I get an 500 ISE error. When I check the logs which Google provides I
see the exact same traceback as in the first comment, although there isn't information to match the traceback to a specific URL so I'm assuming it's the one I'm trying to access.

I don't know what reproduces this and I'm not able to reproduce locally either. It only happens in GCE environment. Maybe the problem isn't related to this particular issue but I don't have more information so I don't really know. I'm trying to figure out what's going on. 

If you can tell me how to reproduce the problem which is discussed in this issue I'll test it locally and see if I still get 500 ISE or not. Then I will know if my problems are related to gunicorn or not. Thanks.

**Comment by tilgovi** [comment]
The problem in this issue is making an HTTP (insecure) request to a server
listening for HTTPS (secure) requests.

If you try to connect to your GCE app with HTTP and you forget the S that
would be this issue.

**Comment by atodorov** [comment]
@tilgovi - thanks, it looks like my problems are somewhere else then.
