### ISSUE TITLE
How do I print accesslog to STDOUT?

### ISSUE THREAD

**Issue by mrlamroger** [benoitc/gunicorn#1184]
Hi,

http://docs.gunicorn.org/en/stable/settings.html#accesslog is telling me `'-'` will output to stderr but we prefer STDOUT for logging purposes. Is there a way to do that?

Thanks!

**Comment by berkerpeksag** [comment]
The relevant line is here: https://github.com/benoitc/gunicorn/blame/master/gunicorn/glogging.py#L335 `logging.StreamHandler()` defaults to `sys.stderr`. Perhaps we could change accesslog to accept "stdout" and "stderr" as valid values and pass to  `logging.StreamHandler()`.

**Comment by berkerpeksag** [comment]
Another but less flexible solution:

The console handler already prints to `sys.stdout`: https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L64 We could set the handler to "console" for `gunicorn.accesslog`  as we already did for `gunicorn.error` in https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L55

**Comment by benoitc** [comment]
I'm confused. Doesn't the StreamHandler already log on sys.stdout?

**Comment by berkerpeksag** [comment]
No, the default value is `sys.stderr`: https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L955

**Comment by benoitc** [comment]
OK I understand now. Originally we were printing logs to stdout. IMO the access log should default to STDOUT.  Thoughts?

**Comment by tilgovi** [comment]
@benoitc :+1:

Access log on stdout
Error log on stderr

**Comment by emanuelcds** [comment]
any updates on this request?

**Comment by suriya** [comment]
@benoitc I am not sure this commit addresses this issue. Let us say I run, `gunicorn myapp:app` with no additional arguments. Is the expectation that gunicorn should log access records to standard output? If so, gunicorn doesn't do that.

In https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L302 without any command line arguments `self.cfg.accesslog` is `None` and the function returns early. As far as I can tell, there seems to be no way to log to stdout without specifing `--log-config` or `--log-syslog`. Is this correct?

**Comment by benoitc** [comment]
by default access log is disabled if this is what you mean?

**Comment by suriya** [comment]
@benoitc Yes. The discussion above seems to indicate that access logs will go to stdout and error logs to stderr. However, it looks like access logging is disabled by default.

BTW, with Python 2.7 I used to be able to do `--access-log /dev/stdout --error-log /dev/stderr` and that would work. With Python 3, passing `/dev/stdout` as an argument fails in https://github.com/benoitc/gunicorn/blob/f722a6eb65e51407c420ac3d6be72d03bd773ad0/gunicorn/util.py#L498

**Comment by amilstead** [comment]
👍  @suriya I think I'm looking for the same behavior you are -- I'd like to run `--capture-log` and enable `--access-log`, but I'd prefer my access log lines go to stdout not stderr.

**Comment by huoxy** [comment]
Yes, it looks like access logging is disabled by default.

**Comment by suriya** [comment]
@huoxy More than what the default is, I think the issue is more that there is no simple way to write access logs to standard output.

**Comment by benoitc** [comment]
@huoxy ˋ--access-logfile=-` should do the trick. let me k'ow if not.

- benoît

**Comment by benoitc** [comment]
also it is probably a doc issue. but access log must be printed to stdout
when `-` is used. otherwise it is a bug. Let me know...

**Comment by suriya** [comment]
@benoitc As mentioned in #1293, `gunicorn --access-log -` logs accesses to standard error. I tried with `gunicorn --access-log=-` and the log still goes to standard error.

**Comment by BeOleg** [comment]
according to this:
https://github.com/gunicorn/gunicorn/blob/master/gunicorn/glogging.py#L58

default logger is `console` which outputs to stdout, so I guess if you need everything to stdout like me, for everything to get to the gunicorn logging driver, you can just leave those options blank.

**Comment by BeOleg** [comment]
Also, the solution I would suggest, is to create a symbolic link for the log files to `/dev/stdout` or `/dev/stderror` if it does not work directly:

```
ln -sf /var/log/gunicorn.access.log  /dev/stdout
ln -sf /var/log/gunicorn.error.log  /dev/stderr

          exec newrelic-admin run-program gunicorn --chdir /usr/src/app --name nexchange --bind 0.0.0.0:${GUNICORN_PORT} --workers 3 --log-level=info --log-file=/var/log/gunicorn.error.log --access-logfile=/var/log/gunicorn.access.log nexchange.wsgi:application "$@"
```

**Comment by Ghazgkull** [comment]
I just moved to gunicorn 19.7.0 released last week. Unfortunately, I still can't get the access log written to anything other than stderr.

I've tried running gunicorn with no options and also with all permutations of including/not including "--access-logfile=- --error-logfile=- --log-level=DEBUG".

It seems like access logs are only written when log-level is DEBUG (although the code looks like it should be logging access at INFO?). And indeed the access messages are printed to stderr as DEBUG messages.

Really, all output from gunicorn is going to stderr... I'm not a Python expert by any means, but when I look in glogging.py at the info/debug/error/warn/log functions, they're all using error_log. Is this the intention? Am I missing something basic about gunicorn's logging?

**Comment by suriya** [comment]
With the application file [myapp.py](https://gist.github.com/suriya/1d9a11ea9ad33a5b1df0b2ba7ed0cd0e#file-myapp-py), I tried the following.

```
$ python --version
Python 3.5.2
$ gunicorn --version
gunicorn (version 19.7.0)
$ gunicorn --access-logfile - myapp:app 
```
I can confirm that the access log output goes to `stdout`.

**Comment by Ghazgkull** [comment]
I'm on Python 2.7.14. (Somehow missed the quick reply months ago.)

**Comment by deka108** [comment]
You can also use `accesslog  = "-"` in your gunicorn.config.py
