### ISSUE TITLE
Remove paste server block support

### ISSUE THREAD

**Issue by tilgovi** [benoitc/gunicorn#1189]
In issues like #1073 the paste `server` block has come up. Right now, gunicorn supports some config options there.

I'm tempted to propose deprecate support for that completely so that all the gunicorn config has to happen in a gunicorn config file.

Feedback requested.

**Comment by benoitc** [comment]
Just to clarify but we would keep the `--paste` option right?

**Comment by tilgovi** [comment]
Yes.

**Comment by benoitc** [comment]
:+1:  then :)

**Comment by benoitc** [comment]
bump
