### ISSUE TITLE
[doc] --cert-reqs option could be more descriptive

### ISSUE THREAD

**Issue by mtourne** [benoitc/gunicorn#1198]
Documentation is not super explicit on --cert-reqs

I was trying --certs-reqs 1 for a while and thinking it wasn't working as expected.
I had to read the code to understand that the value is passed straight into SSLContext.verify_mode, and that '1' didn't mean "turn on client cert validation" but instead codes for : ssl.CERT_OPTIONAL

--cert-reqs 2 (which is the value for ssl.CERT_REQUIRED) did the trick.

**Comment by berkerpeksag** [comment]
+1 Actually, the entire SSL section needs a bit of clarifying :) Would you like to send a pull request?

**Comment by benoitc** [comment]
@berkerpeksag what do we need exactly?

**Comment by tilgovi** [comment]
@benoitc I think we should support the symbolic constants, since they are a small, fixed, finite set of values, and we should clarify the documentation.
