### ISSUE TITLE
gunicorn old process should exit when new process finish initialization

### ISSUE THREAD

**Issue by kuangchanglang** [benoitc/gunicorn#1199]
I use "kill -HUP" to restart gunicorn, and I see from source code that old processes exit immediately when starting new processes. But my application take a few seconds to initialize. At this time all requests get stuck. 

Is there any way to solve this problem? If I can write a hook to tell master when it should switch old processes to new processes?

**Comment by benoitc** [comment]
if they exit immediately it means that no connections were running. Why do you think that requests get stuck?

The other way to reload your app without killing the workers is to use the USR2 signal:
http://docs.gunicorn.org/en/stable/signals.html

Once your new application is up you can kill the old master using that method.

**Comment by kuangchanglang** [comment]
Thank you very much, @benoitc . USR2 signal is exactly what I want.
