### ISSUE TITLE
Python3 and cyrillic in URLs

### ISSUE THREAD

**Issue by IlianIliev** [benoitc/gunicorn#1202]
I have problem with URLs containing cyrillic characters. For example the url `/малко кирилица/тест/` is correctly send from the browser with percent encoding as `/%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%B8%D1%86%D0%B0/`.
However at https://github.com/benoitc/gunicorn/blob/master/gunicorn/_compat.py#L82 it is decoded using `latin-1` instead of `utf-8` which messes the cyrillic characters.

Has anyone experienced the same issue and is there a specific reason for not using utf-8 here?

**Comment by IlianIliev** [comment]
P.S. I have changed it on my own fork, tested locally and it looks fine https://github.com/IlianIliev/gunicorn/commit/fcd9161c9e93a2819aa449989fe0279e680f8425

**Comment by benoitc** [comment]
@IlianIliev can you submit a PR with it?

**Comment by jamadden** [comment]
I'm pretty sure the WSGI spec [calls for Latin-1](https://www.python.org/dev/peps/pep-3333/#unicode-issues). We just dealt with this in gevent/gevent#712; decoding to UTF-8 breaks Django.

**Comment by jamadden** [comment]
The trick in the application is to know that PATH_INFO are decoded in latin-1, which doesn't lose any bytes, and then re-decode them with utf-8.

**Comment by IlianIliev** [comment]
At the same time http://tools.ietf.org/html/rfc3986 says that:

> When a new URI scheme defines a component that represents textual
> data consisting of characters from the Universal Character Set [UCS],
> the data should first be encoded as octets according to the UTF-8
> character encoding [STD63]; then only those octets that do not
> correspond to characters in the unreserved set should be percent-
> encoded

**Comment by jamadden** [comment]
True enough, but HTTP is not a *new* URI scheme by any definition. The HTTP URI was defined in [RFC2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2), which in turn references [RFC2396](https://www.ietf.org/rfc/rfc2396.txt), which only talks about ASCII and otherwise hex encoding.

**Comment by berkerpeksag** [comment]
I agree with @jamadden. It might be changed to use UTF-8 in an updated WSGI 1.1 spec (see web-sig on mail.python.org for details), but in the mean time we should follow what PEP 3333 says for backward compatibility reasons.

**Comment by IlianIliev** [comment]
You are totally right.
Actually it looks like it has been a bug in Falcon that has been already fixed - https://github.com/falconry/falcon/commit/6b011038f691d03174da26f06ddf45528d3cefd3

Sorry for wasting your time )
