### ISSUE TITLE
Document gthread and gaiohttp in worker_class Settings page

### ISSUE THREAD

**Issue by strife25** [benoitc/gunicorn#1204]
When visiting the settings page for [worker_class](http://docs.gunicorn.org/en/stable/settings.html#worker-class), the worker_class types for python3 are not documented.

These types are mentioned in the design area of the docs under [AsyncIO Workers](http://docs.gunicorn.org/en/latest/design.html#asyncio-workers) and the key names to use for the worker_class argument is defined in the [--worker-class argument list in the Running Gunicorn page](http://docs.gunicorn.org/en/stable/run.html#commonly-used-arguments).

It would be good to get these values added to the settings page as well for folks that land on there from searching.

**Comment by tilgovi** [comment]
Thanks, @strife25! The text you refer to is taken from the `desc` field of `WorkerClass`: https://github.com/benoitc/gunicorn/blob/master/gunicorn/config.py#L557

Would you please make a pull request that adds these?

**Comment by benoitc** [comment]
@strife25 ping

**Comment by benoitc** [comment]
actually this is just that we didn't make a release. The values are documented there:
http://docs.gunicorn.org/en/latest/settings.html#worker-class

Closing the issue then. Feel free to reopen it if I missed anything.
