### ISSUE TITLE
ckeditor work fine on runserver but not on gunicorn

### ISSUE THREAD

**Issue by xoac** [benoitc/gunicorn#1206]
Hello, guys. I really don't know what's wrong and how to exterminate problem.
It seem to be similar to https://github.com/benoitc/gunicorn/issues/1059

I have a vps on digitalocean [i use this tutorial to instal nginx gunicon and django on virtualenv](https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-14-04). 

When I run

> cd drewpol
> source drewpolenv/bin/activate 
> python manage.py runserver 0.0.0.0:8001

 everything works fine.

but if i do:

> sudo service gunicorn  start

not.

 /etc/init/gunicorn.conf
> start on runlevel [2345]
> stop on runlevel [!2345]
> 
> respawn
> setuid drewpol
> setgid www-data
> chdir /home/drewpol/drewpol
> 
> exec drewpolenv/bin/gunicorn --workers 3 --bind unix:/home/drewpol/drewpol/drewpol.sock drewpol.wsgi:application

I made test account to give you opportunity to see what is not working:

login: test 
password: gunicorn
don't working ckeditor: http://tartakwkipsznej.pl/admin/
working ckeditor:  http://tartakwkipsznej.pl:8001/admin/ (sometimes runserver is disabled please @ me to run it again)
try create or change sth

**Comment by nMustaki** [comment]
I've got a js error on a the Gunicorn instance : TypeError: editor.lang.bootstrapTabs is undefined

**Comment by xoac** [comment]
Thanks. You are right, it started working and the problem were in conf nginx I didn't notice that it fail restart. And all time see the old version of site.

**Comment by srijande** [comment]
**Add location of CKEditor static files in apache/Nginx sites-available**  

```
location /static/ckeditor/ {
      root /home/username/myProjectt/env/lib/python3.8/site-packages/ckeditor;
 }
```
