### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by genxstylez** [benoitc/gunicorn#1212]
I am using flask + gunicorn deployed on aws with elasticbeanstalk with multi-container docker

And when I upload a file to s3 from admin, I get this error from sentry.

```python
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
app/tools.py in _save_file at line 138

app.storage.save(filename, data)
app/storages/base.py in save at line 125

name = self.get_available_name(name)
app/storages/base.py in get_available_name at line 144

while self.exists(name):
app/storages/s3.py in exists at line 204

return bool(self.bucket.lookup(self._encode_name(name)))
```

strange thing is, when I ssh into the machine, attach my web-server docker and get into shell, run the same code as above. I don't get any errors.

I am not sure if gunicorn is causing it, but the way I see it, this is the only difference.

Please help.

**package info**
```python
gevent==1.1.0
greenlet==0.4.9
gunicorn==19.4.5
python==2.7.11
```

**Comment by tilgovi** [comment]
When you attach to the shell, are you in the same container running the application, or are you on the host machine?

If you're on the host, it could be that the host has different certificates installed than the container does.

I don't know what library you're using to access the s3 bucket, but it's possible installing the `certifi` package could help.

**Comment by genxstylez** [comment]
@tilgovi I am on the container, and `certif`i is installed

**Comment by allanlei** [comment]
Is there any indication that this is related to gevent?

**Comment by allanlei** [comment]
Also, the underlying lib for S3 is probably ```requests``` which has its own embedded ```certifi``` package and installing ```certifi``` doesn't really affect ```requests```.

**Comment by genxstylez** [comment]
@allanlei the s3 using boto

**Comment by allanlei** [comment]
Can you paste your Dockerfile or what the base container is?

**Comment by genxstylez** [comment]
it's based on alpine3.3 
based off https://github.com/orbweb/docker-python/blob/master/2.7.11/onbuild/Dockerfile

**Comment by allanlei** [comment]
Quite sure this problem is not related to gunicorn.

Things you can try:

- Set ```REQUESTS_CA_BUNDLE``` env var to ```certifi.old_where()```
- Update openssl

**Comment by benoitc** [comment]
That doesn't sound a gunicorn error but I don't understand that part:

> strange thing is, when I ssh into the machine, attach my web-server docker and get into shell, run the same code as above. I don't get any errors.


Does it means when you're requesting gunicorn inside the container? what if you call s3 from the container? Also I guess sentry is catching messages before gunicorn is even interacting, or are you using another kind of error tracking?

**Comment by genxstylez** [comment]
@benoitc I fixed it, turns out it's related to gevent's monkey patch and boto.

when I use guicorn + gevent boto doesn't work, fixed it with boto3

**Comment by benoitc** [comment]
@genxstylez ok thanks for the feedback :+1: . Closing the issue then :)
