### ISSUE TITLE
Worker can inherit unwriteable temporary directory

### ISSUE THREAD

**Issue by dracos** [benoitc/gunicorn#1215]
If gunicorn is run as root (as with the Debian package), with user/group parameters to switch the workers to, and libpam-tmpdir is installed (a PAM module that gives each user their own temporary directory by setting `TEMP`/`TMP`/`TMPDIR`/`TEMPDIR`), the workers are unable to create temporary files.

If `worker_tmp_dir` is not set (the default), then `gunicorn/workers/workertmp.py` [calls](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/workertmp.py#L23) `tempfile.mkstemp` with a `dir` of None, which causes `tempfile.gettempdir` to be called and the global `tempdir` variable to be set inside tempfile. At this point we are in the parent and so with libpam-tmpdir installed `tempdir` will be set to `/tmp/user/0`.

The workers are then initialized and have `setuid` and `setgid` called, but if they ever use tempfile, e.g. Django's `tempfile.NamedTemporaryFile(suffix='.upload')` is how I discovered this, then they continue to use the globally set `tempdir`, cannot write to `/tmp/user/0` and throw an exception.

A workaround is to pass fixed environment variables into the workers based upon the user, but I wondered if it were possible for gunicorn to set `tempfile.tempdir` to None when it switches user? This would mean the next time a tempfile function is called, it has to recalculate the `tempdir` and either finds the one of the correct user or falls back to a more global non-user location such as `/tmp`.

**Comment by tilgovi** [comment]
Thank you for the detailed report.

The workaround you ask for is not unreasonable. For your immediate use, you could use the `post_fork` hook to unset `tempfile.tempdir`.

Alternatively, #640 would make this unnecessary. Any news on that, @benoitc?

**Comment by benoitc** [comment]
@tilgovi I have some code actually using a new IPC library that should replace the tempfile system (see [my talk at the fosdem](https://speakerdeck.com/benoitc/gunicorn-more-than-a-wsgi-server) this year. I will create the branch next week when I'm back from my trip :)

But isn't `--worker-temp-dir` enough for doing above? 
http://docs.gunicorn.org/en/stable/settings.html#worker-tmp-dir

**Comment by tilgovi** [comment]
Yes, I think `--worker-temp-dir` is a sufficient workaround for the issue in the meantime and this issue can serve as documentation for other people searching around similar problems.

@dracos alright if we close this?

**Comment by dracos** [comment]
Sure; I'm setting `TEMPDIR` in the environment of the workers, using `--worker-temp-dir` or `post_fork` are other workarounds. Thanks :)
