### ISSUE TITLE
Is Gunicorn using Semantic Versioning?

### ISSUE THREAD

**Issue by vrde** [benoitc/gunicorn#1240]
I googled and the only reference to [semantic versioning](http://semver.org/) I found is #1021. Can I assume Gunicorn uses it? I need this information to know which version to pin in my `setup.py`.

**Comment by tilgovi** [comment]
Good question. I've been treating it roughly as semver. @berkerpeksag @benoitc @kennethreitz

**Comment by benoitc** [comment]
Official and advertised Gunicorn versions are "X.Y" . In between you have patch release X.Y.Z . Internally all tte releases follow roughly the semantic versioning. So X.Y becomes X.Y.0 for the package.
