### ISSUE TITLE
Logging not working propperly with django application in gunicorn 19.x

### ISSUE THREAD

**Issue by emanuelcds** [benoitc/gunicorn#1244]
Hello guys,
We are running in trouble to log properly the access and error log.

Take a look on this stackoverflow thread (8 months open and no solution):
http://stackoverflow.com/questions/31755087/cant-get-logging-to-file-to-work-in-gunicorn-19-x-works-in-version-18

It works properly on gunicorn 18, and no way to work in gunicorn 19+.

Here is my django logging configuration:
https://gist.github.com/emanuelcds/337791401692b681455311ee932c1113

I'm running gunicorn with this command line:
```
$ gunicorn contentools.wsgi:application --workers 8 -b unix:/tmp/gunicorn.sock --access-logfile /var/log/web.access.log --error-logfile /var/log/web.error.log
```

Double checked and all file permissions are ok and owned by gunicorn user.

**Comment by tilgovi** [comment]
What happens if, instead of passing `access-logfile` and `error-logfile`, you pass no logging options to Gunicorn and set up logging entirely through Django.

Tell Django to disable existing loggers and define the `gunicorn.error` and `gunicorn.access` logs there to your liking?

**Comment by tilgovi** [comment]
Sorry, my comment is useless. I'm investigating. I need to understand more how Django sets up logging.

**Comment by tilgovi** [comment]
@emanuelcds Gunicorn used to redirect stdout and stderr to its error log file, but that is not supported anymore.

If you're seeing a problem where gunicorn stops writing to _its_ error log when you see application logs in your file handler, add `disable_existing_loggers: False`.

**Comment by tilgovi** [comment]
This was called out in the changelog, but regrettably probably much more clearly.

http://docs.gunicorn.org/en/stable/2014-news.html:

    fix logging: don’t try to redirect stdout/stderr to the logfile.

Very sorry for the confusion. I'll close this bug, but please re-open if you think there is a defect and I have misunderstood your issue.

**Comment by emanuelcds** [comment]
Hey @tilgovi thank you for the explanation.
Actually its already set to ```False```, and not working yet.
I will debug it and find by any luck what I missed.

**Comment by tilgovi** [comment]
No problem. If you get stuck, please comment and elaborate and let us know
what behavior exactly you expect and what you're seeing. I tried to answer
the SO post, too, but not actually sure it's the same as your issue.

**Comment by tilgovi** [comment]
Looking at this again I think you may just need to move the empty logger key up to a top-level `root` dict. I was re-reading https://docs.python.org/2/library/logging.config.html#dictionary-schema-details and I had forgotten about that.

**Comment by emanuelcds** [comment]
Worked. Thank you.

**Comment by SillyMrTang** [comment]
我是在settings中配置的，本地可以写入到log文件  但我部署到服务器上就不会写入  不知道什么原因   我部署用的是uwsgi+nginx

**Comment by LoseBoycn** [comment]
> 我是在settings中配置的，本地可以写入到log文件 但我部署到服务器上就不会写入 不知道什么原因 我部署用的是uwsgi+nginx

我也是，你怎么解决的？
