### ISSUE TITLE
database: persistent connetion

### ISSUE THREAD

**Issue by chuan137** [benoitc/gunicorn#1247]
Hi 
From the mailing list, https://groups.google.com/a/lists.datastax.com/forum/#!topic/python-driver-user/XuSjjWVnE9Y, I read that, I could initialize the database connection in post_fork

Then, how do I access the db connection session later in app?

**Comment by tilgovi** [comment]
Store the reference somewhere accessible, like in some module state or global app data.

**Comment by tilgovi** [comment]
Unless you use the preloaded app setting, you can also get what you want by just doing it at module level in one of the modules imported at initialization time. There's no need to specifically use pre_fork.

If you have further questions, please use the mailing list as this issue tracker is primarily for bug reports and improvements.
