### ISSUE TITLE
Switch to a modern default for SSL/TLS protocol support

### ISSUE THREAD

**Issue by tilgovi** [benoitc/gunicorn#1249]
Right now we the constant for TLSv1 (`ssl.PROTOCOL_TLSv1`). We should switch to `ssl.PROTOCOL_TLv1_2` or `ssl.PROTOCOL_SSLv23`. The latter allows SSLv3 and TLS, and is the Python default meant for broad compatibility. It should be safe for most purposes, especially if #1140 implements server cipher preference.

See #1114.

**Comment by benoitc** [comment]
@tilgovi we only need to change the default in the config for this ticket?

**Comment by tilgovi** [comment]
Yes.

**Comment by benoitc** [comment]
what are the default to support? So we can close the issue?
