### ISSUE TITLE
Gunicorn should not swallow exceptions raised in worker exit handler

### ISSUE THREAD

**Issue by jgehrcke** [benoitc/gunicorn#1253]
The last steps before a worker process exits:

```python
        finally:
            self.log.info("Worker exiting (pid: %s)", worker_pid)
            try:
                worker.tmp.close()
                self.cfg.worker_exit(self, worker)
            except:
                pass
```
(currently: https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L538)

Instead of just `pass`ing on an exception, we should still emit the details. Otherwise people may just not realize that they have an error in their exit handler. I suggest adding `import traceback`  and then do `traceback.print_exc(file=sys.stdout)` instead of the `pass`. Swallowing exceptions is almost never a great approach.

Feedback welcome. If that seems useful, I am happy to submit a PR.

**Comment by tilgovi** [comment]
Seems fine to me to log a traceback.
