### ISSUE TITLE
timeout setting, silent definition

### ISSUE THREAD

**Issue by edgarcosta** [benoitc/gunicorn#1280]
Hello,

The current description of the timeout setting is a bit confusing to me, and it is not clear what is meant by "silent".

I found this description:
https://github.com/benoitc/gunicorn/blob/9d158bec94c91c62cd5cc28a27268a5b8804d795/examples/example_config.py#L57
which is a bit more clear to me. However, I'm not sure how accurate it is.
If it is not accurate, would you mind to clarify it?

In either case, I think the current description of the timeout setting would improve a lot if it were reworded, or at least defined what "silent" means.

Best,
Edgar

**Comment by tilgovi** [comment]
The linked text is correct. Worker implementations must notify the arbiter once per timeout interval or be killed. The mechanism of notification is part of the worker API: `gunicorn.workers.base.Worker#notify()`.

If you have a way to improve the text, please submit a pull request. Thanks :)

**Comment by edgarcosta** [comment]
Thank you
