### ISSUE TITLE
Incomplete privileges drop

### ISSUE THREAD

**Issue by aeris** [benoitc/gunicorn#1287]
Hello,

Seems uid/gid drop is incomplete on gunicorn. Setting uid doesn’t fetch real uid groups.
This behaviour is visible here :

```
# cat foo.py
#!/usr/bin/env python
import os
def application(env, response):
    response('200 OK', [('Content-Type', 'text/plain')])
    return [str((os.getuid(), os.getgid(), os.getgroups()))]

def nothing(status, headers):
    pass

if __name__ == '__main__':
    print(application(None, nothing))

# groups
root
# ./foo.py 
['(0, 0, [0])']  // Groups OK, [root]

# gunicorn -b 127.0.0.1:5000 foo:application
# curl localhost:5000
(0, 0, [0])  // Groups OK, [root]

# gunicorn -u www-data -g www-data -b 127.0.0.1:5000 foo:application
# curl localhost:5000
(33, 33, []) // Groups not OK, empty…

# su www-data -s /bin/sh
$ groups
www-data debian-tor
$ ./foo.py
['(33, 33, [33, 117])'] // Groups OK, [www-data, debian-tor]

$ gunicorn -b 127.0.0.1:5000 foo:application
$ curl localhost:5000
(33, 33, [33, 117])  // Groups OK, [www-data, debian-tor]
```

Running python script directly, groups are set for root (root) and www-data (www-data and debian-tor).
Running wsgi with gunicorn, ok from root and www-data.
Running wsgi with gunicorn from root and uid/gid www-data, not ok, groups are empty.

This is a problem because after privileges dropping, your app can’t access file with group restriction (in my case, unable to access file with debian-tor:debian-tor chown and 770 chmod).

Seems this is because groups are not initializated (`os.initgroups(username, groups)`) before privileges drop.
[This patch](https://github.com/aeris/gunicorn/commit/696c4bfd57ff851018687f7011a8e57608fcc367) may fix the trouble, but is not portable (UNIX only because of `pwd` package usage).

**Comment by benoitc** [comment]
@aeris Thanks for the report. please test #1290 and let us know.

**Comment by DavidWHarvey** [comment]
When running using gunicorn -u under Azure ARC DefaultAzureCredential gets Permission Denied opening a token file even when the uid is a member of the himds group. After a month  of searching & debug, we got this to work by adding --uid users --initgroups.  One would have expected that -u xxx --initgroups would have been sufficient but it seemed to be a noop.

**Comment by benoitc** [comment]
I don't know what you're reffering, there is no `--uid` command line parameter in gunicorn. Only -u/--user.

**Comment by DavidWHarvey** [comment]
Fixed my comment.  I needed to specify --group to get --initgroups to enable a different group for the user.  My main goal is to make this issue show up when searching for symptoms.
