### ISSUE TITLE
Help regarding socket option 'TCP_DEFER_ACCEPT'.

### ISSUE THREAD

**Issue by xitkov** [benoitc/gunicorn#1289]
I have seen posts on the internet blaming TCP_DEFER_ACCEPT for a lot of connection woes.

I am also facing one, and I need to know whether gunicorn use 'TCP_DEFER_ACCEPT' as enabled by default?

**Comment by benoitc** [comment]
@xitkov Right now it is not enabled, neither there is an option for:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/sock.py#L40

Is this an error you're receiving ? In that case can you tell me which OS and in which context it's reproducible?

**Comment by xitkov** [comment]
@benoitc I am not receiving any error from gunicorn or at gunicorn, I mean I am not messing with the code :).

The problem is,
i) There's an EC2 ELB, behind which I have instances running gunicorn as the web server.
ii) If a lot of instances are removed from the ELB together (more than 40-50%), the ELB shows a dip in total requests received.

The AWS guys told me TCP_DEFER_ACCEPT can be the culprit hence, I just wanted to confirm if this is enabled or not.

**Comment by tilgovi** [comment]
Gunicorn does not set this flag.
