### ISSUE TITLE
Possible mistake in FAQ "Why I don’t see any logs in the console?"

### ISSUE THREAD

**Issue by edmorley** [benoitc/gunicorn#1294]
This FAQ entry:
http://docs.gunicorn.org/en/latest/faq.html#why-i-don-t-see-any-logs-in-the-console

Says:

> In version R19, Gunicorn doesn’t log by default in the console. To watch the logs in the console you need to use the option --log-file=-. In version R20, Gunicorn logs to the console by default again.

I think "R20" should instead be "R19.2", given:
http://docs.gunicorn.org/en/latest/settings.html#errorlog

Also `--log-file=-` has been replaced by `--error-logfile=-` in v0.13.0.

**Comment by benoitc** [comment]
fixed in 1aa9cf0529fe87e4084dea9dadc97848934cceb4
