### ISSUE TITLE
binary empty string throwing error in postgres

### ISSUE THREAD

**Issue by kwatog** [benoitc/gunicorn#1302]
I'm trying to use django-comments on my site and am encountering the error below. Here's my env
- centos 6.6
- python 3.5
- django 1.9
- gunicorn
- postgres

```
File "/home/mkt/mktve/lib/python3.5/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)

The above exception (invalid input syntax for type inet: "b''"
LINE 1: ... '2016-06-29T01:49:20.676843+00:00'::timestamptz, E'b'''''::...
                                                             ^
) was the direct cause of the following exception:
```

I also raised the issue with django-comment in the link below.
https://github.com/django/django-contrib-comments/issues/93#issuecomment-229282319

**Comment by kwatog** [comment]
sorry, i'm closing it now. it could be  a problem of django_comments.

**Comment by tilgovi** [comment]
`REMOTE_ADDR` is not part of the WSGI spec, although Gunicorn tries to provide it. Sometimes, it cannot, such as when a unix socket is being used as the listener. It's not obvious to me that leaving it out is better or worse than setting it to `None` or an empty byte string (like we do now).

I just closed this, but actually I re-open it for the moment and ask for feedback from anyone who has thoughts here. My instinct is that django-contrib-comments should be checking the return value to see if it's non-empty and defensively handling the case where it does not parse as an IP address.

**Comment by benoitc** [comment]
no activy since. closing the issue. (I think you were right ;)
