### ISSUE TITLE
Tip of the hat to heroku maybe...

### ISSUE THREAD

**Issue by michaelcoconnor** [benoitc/gunicorn#1303]
On http://gunicorn.org/#deployment you state the need for nginx. Possibly you should include a parenthetical remark to the effect that "Note, however, that the use of a proxy server with gunicorn is unnecessary on the popular heroku.com system."

See in particular https://devcenter.heroku.com/articles/python-faq#do-python-applications-run-behind-nginx and note also that in that paragraph the heroku people say kind things about gunicorn.

**Comment by diwu1989** [comment]
you might want to think twice about not running gunicorn behind nginx on Heroku, see https://github.com/benoitc/gunicorn/issues/840

because of that issue, we've been running gunicorn on Heroku behind nginx connected via a unix socket, and letting nginx handle all of the request/response buffering

**Comment by michaelcoconnor** [comment]
Di Wu,

    Thanks so much for the note. Yes I am a noob wrt gunicorn, so you've
    been critically helpful.


-Mike

**Comment by tilgovi** [comment]
Any issues running Gunicorn on Heroku are considered bugs and our official recommendation should probably be to defer to the platform instructions. If Heroku says not to use nginx, we shouldn't contradict them.

Our wording could be clearer. We don't provide any justification for running behind nginx, I know of users who don't use a reverse proxy at all, and when a platform like Heroku provides the reverse proxying and response buffering and such we probably shouldn't be recommending to use nginx still.

Pull requests very welcome and we can discuss the actual wording more directly that way!

**Comment by michaelcoconnor** [comment]
Randall, thanks much for the advice.

-Mike

**Comment by benoitc** [comment]
@tilgovi what to add to the following sentence in deploy doc to make it clearer ?

```
 If you choose another proxy server you need to make sure that it buffers slow clients when you use default Gunicorn workers. Without this buffering Gunicorn will be easily susceptible to denial-of-service attacks. 
```

**Comment by tilgovi** [comment]
Sounds fine.

**Comment by benoitc** [comment]
done
