### ISSUE TITLE
Reason for upper bound on header size?

### ISSUE THREAD

**Issue by tobgu** [benoitc/gunicorn#1306]
What's the reason for having an upper bound of the header size (8190) but also making it possible to set it to 0 to have an unlimited size?

I have a situation now where I would like to set it to something higher than 8190 but still have an upper limit to avoid processing headers of arbitrary size. It would feel a lot better to be able to set it to 16000 (for example) than to release control of the upper limit completely.

I noticed there's a similar issue here #976 but it seem to have faded away. I'm happy to contribute with a PR if you think that removing the upper limit is a good idea. The default should remain the same and the meaning of 0 should remain the same.

**Comment by tilgovi** [comment]
I think that sounds reasonable. I don't see a reason to limit the operator's choice.

**Comment by benoitc** [comment]
any patch that goes in the spirit of the pr above is fine for me. Ie allows  the op to configure it and warn if it's unbounded or too large. Thoughts?
