### ISSUE TITLE
TypeError when header value is an integer

### ISSUE THREAD

**Issue by chripede** [benoitc/gunicorn#1308]
After upgrading to 19.6.0 I can no longer use an integer as the value in a header.

`TypeError: expected string or buffer`

This change https://github.com/benoitc/gunicorn/commit/1e10a02e73c87dfadc394b361af33864d0e59e24#diff-6607b435d6ee868f251dbdd1a6d0edecR274 seems to be the problem. I guess the same would happen if I set the header name to an integer.

**Comment by tilgovi** [comment]
How are you passing an integer as a header? HTTP headers are byte strings.

**Comment by chripede** [comment]
Using Falcon it's `append_header('x-rate-limit', 123)`

In 19.4.x it works

**Comment by tilgovi** [comment]
http://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Response.append_header

    value (str) – Value for the header. Must be of type str or StringType and contain only ISO-8859-1 characters. Under Python 2.x, the unicode type is also accepted, although such strings are also limited to ISO-8859-1.

You should convert to a string before you pass to that parameter. I am not sure it's Gunicorn's responsibility to silently coerce these values to strings.

**Comment by chripede** [comment]
@tilgovi even the documentation is against me ;) Thank you
