### ISSUE TITLE
clarification about worker types / resource usage

### ISSUE THREAD

**Issue by jjb** [benoitc/gunicorn#1312]
here: https://github.com/benoitc/gunicorn/blob/master/docs/source/design.rst#choosing-a-worker-type

> The default synchronous workers assume that your application is resource bound in terms of CPU and network bandwidth. Generally this means that your application shouldn't do anything that takes an undefined amount of time. For instance, a request to the internet meets this criteria. At some point the external network will fail in such a way that clients will pile up on your servers.

When the docs say "a request to the internet meets this criteria", does that mean "a request to the internet **does** take an undefined amount of time", or "a request to the internet **does not** take an undefined amount of time"?

**Comment by jjb** [comment]
I'm 95% sure it's the former, but I'm possibly confused in the context of this subject, so I'm checking just in case. I'll submit a PR with clarified language after I get the answer. Thanks!

**Comment by tilgovi** [comment]
It does take an indefinite amount of time because "at some point the external network will fail".

**Comment by tilgovi** [comment]
There could definitely be improvements to this text, though. If you have some ideas pleas open a PR.

**Comment by jjb** [comment]
Okay, PR here: https://github.com/benoitc/gunicorn/pull/1316

If you don't like that language, leave a comment with your preferred language and I'll put it in.

question: even without doing outgoing API requests, serving requests to clients also takes an undefined amount of time because of network and client variability, right? So wouldn't all web applications benefit from asynchronous workers? Or is this a different consideration for some reason?

**Comment by berkerpeksag** [comment]
Can this be closed now?

**Comment by jjb** [comment]
💥
