### ISSUE TITLE
docs: incorrect default value of setting `bind`

### ISSUE THREAD

**Issue by glarrain** [benoitc/gunicorn#1319]
According to [latest docs](http://docs.gunicorn.org/en/latest/settings.html#bind), the default value for setting `bind` is `['127.0.0.1:8000']`. However, **that is correct only** if env var `PORT` is not set because then default value is `['0.0.0.0:{0}'.format(os.environ.get('PORT'))]`, as can be seen in the [code](https://github.com/benoitc/gunicorn/blob/fdd5276/gunicorn/config.py#L520-L545). IMO that should be mentioned in the docs (I discovered this because that behavior bit me).

If the aforementioned is fixed, it would be a nice to improve the description title as well.

Something like

> List of addresses, ports or sockets to bind to.

seems more appropriate than

> The socket to bind.

Thanks

**Comment by benoitc** [comment]
"the socket to bind" is correct since -b can only be used for one socket. 

I'm not sure if we need to change the doc also since this is mainly an hack there. PORT will always be overridden if the bind option is used and the correct default will be displayed using the `--help` command line options.  cc @tilgovi @berkerpeksag @kennethreitz

**Comment by glarrain** [comment]
> I'm not sure if we need to change the doc also since this is mainly an hack there.

IMO the behavior of a program should be the same if a setting is not specified, or if it is set to the default value. That does not happen here. Env var `PORT` plays a hidden role in this case and it is not even mentioned in the docs.

> "the socket to bind" is correct since -b can only be used for one socket.

Indeed, but in the settings it is actually a list of sockets. The problem is the 1:1 mapping between a single value CLI argument and a multi-value setting.

**Comment by benoitc** [comment]
that's a longh time and nothing happened since. Doesn't seems it is a good idea now to change it as well. closing the issue then.
