### ISSUE TITLE
License and notice should be included in the Pypi wheel

### ISSUE THREAD

**Issue by pombredanne** [benoitc/gunicorn#1322]
This requires a simple manifest change in setup.cfg:
```
[metadata]
license_file = LICENSE
```

Unfortunately for now because of https://bitbucket.org/pypa/wheel/issues/138/include-more-than-one-license-file-or the NOTICE cannot be included too with the LICENSE, short of making these package data. This is still the case @dholth ?

One way out is to write a script to combine these at wheel/build time. Another is to concat LICENSE and NOTICE in a single LICENSE file.

**Comment by berkerpeksag** [comment]
They both included in [MANIFEST.in](https://github.com/benoitc/gunicorn/blob/master/MANIFEST.in). Do you know why it doesn't work with `bdist_wheel`?

**Comment by pombredanne** [comment]
@berkerpeksag See the link to the wheel "bug" above. wheels have some level of disrespect for MANIFEST.in

**Comment by dholth** [comment]
MANIFEST.in is about the sdist contents. Would 'setup.py install' copy your license and notice into site-packages? If not, then bdist_wheel won't include them.

**Comment by dholth** [comment]
@pombredanne did you get my e-mail about including more files in wheel? Please comment.

**Comment by pombredanne** [comment]
@dholth sorry, I have not. I can be reached @ pombredanne@gmail.com and pombredanne@nexb.com

**Comment by benoitc** [comment]
We won't for sure concat the license and the notice file. This is something that should be addressed by the package system.

Is the notice file shipped whit the package? how can we do it now without waiting for a possible change upstream?

**Comment by pombredanne** [comment]
@benoitc you can at least include the LICENSE file as suggested above: https://github.com/benoitc/gunicorn/issues/1322#issue-169333640 and in this simple PR #1326
To get both files in the wheel you would need to include them as package data I think?

**Comment by benoitc** [comment]
pr applied
