### ISSUE TITLE
Consul Health-Checks

### ISSUE THREAD

**Issue by trivigy** [benoitc/gunicorn#1323]
I am trying to write a consul health-checks for my aiohttp wsgi app running on gunicorn. I figured that the simplest approach is to just send HEAD requests to some path but if I do so, how could I prevent gunicorn.access from printing only for that path?! Alternatively, is there some other way I should go about doing this? Attaching a hook or something? Would love some professional input.

Thanks in advance.

**Comment by benoitc** [comment]
other than having your own logger, there is no way to filter access logs as of now. why don't you filter them after you retrieve the logs?

**Comment by benoitc** [comment]
closing issue, no answer since more than 1 month.
