### ISSUE TITLE
--umask doesn't support non-decimal values

### ISSUE THREAD

**Issue by JayH5** [benoitc/gunicorn#1325]
```
/app $ gunicorn --version
gunicorn (version 19.6.0)
/app $ python --version
Python 2.7.12
```

The [documentation](http://docs.gunicorn.org/en/19.6.0/settings.html#umask) says that Gunicorn should accept _"a string compatible with `int(value, 0)`"_. I don't know about in a config file, but when specifying via the command line (`--umask`,`-m`), only integers are supported. Hex strings are rejected...

```
/app $ gunicorn -m 0xFF
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: argument -m/--umask: invalid int value: '0xFF'
```

... and octals seem to be treated as decimals.

**Comment by benoitc** [comment]
It's not expected to give the umask as hexadecimal? Why do you needed it?

**Comment by berkerpeksag** [comment]
I don't find any `int(..., 0)` call in codebase. In any case, we should update documentation and `examples/example_config.py`. Also, `os.umask()` does the following:

```c
int i = (int)umask(mask);
return PyLong_FromLong((long)i);
```

**Comment by JayH5** [comment]
@benoitc well.. I didn't actually want to use hexadecimal, it was just the easiest example to show Gunicorn not working as documented.

Octal, on the other hand, is much friendlier than decimal for setting a umask and I spent quite a while trying to figure out why my permissions were all wrong before I realised the octal number I'd passed to Gunicorn (`0117`) was being interpreted as decimal (`117`) instead of what the documentation suggests (`int('0117', 0)` -> `79`).

**Comment by JayH5** [comment]
@berkerpeksag there's an `int(..., 0)` call when the argument is validated as a number: https://github.com/benoitc/gunicorn/blob/19.6.0/gunicorn/config.py#L320

That just doesn't seem to apply at the right stage in the processing of arguments... or something.. I'm not sure.

**Comment by hramezani** [comment]
#1465
