### ISSUE TITLE
config from python module isn't re-read on SIGHUP

### ISSUE THREAD

**Issue by darkrain42** [benoitc/gunicorn#1330]
A config file loaded via a Python module (added in #799) doesn't seem to behave the same way as specifying a file directly (the previous behavior, or with a `filename:` prefix) when sending gunicorn a SIGHUP.

(Testing by varying the number of workers)
- If a file is specified, a SIGHUP results in the file being re-read and re-executed -- changes in the file take effect.
- If a module is specified, a SIGHUP has no effect -- changes in the config module do not take effect.

I'm seeing this with gunicorn 19.6.0 in Python 2.7.  I haven't tested Python 3 yet, but I don't believe that's a relevant distinction.

The cause for this seems to be that [Application.get_config_from_filename](../blob/531133615e29e121b31042e0573b5a7aa893a164/gunicorn/app/base.py#L80) invokes `execfile_`, which will unconditionally execute the file (doesn't cache it; doesn't care if it might have changed or not). On the other hand, [Application.get_config_from_module_name](../blob/531133615e29e121b31042e0573b5a7aa893a164/gunicorn/app/base.py#L102) invokes `import_module`, which will return a reference to an already-loaded module, and only reads/loads the module the first time -- when gunicorn is started up.

It seems to me that loading a config via a Python module should behave closer to how loading via file does; I was thinking that it would make sense to [importlib.reload()](https://docs.python.org/3/library/importlib.html#importlib.reload) the module if already present (or perhaps even have a "load (or reload if already loaded)" helper function), but I haven't coded it up yet.

I think this might be the same thing that #1103 was reporting.

**Comment by darkrain42** [comment]
It occurs to me that that reloading the module might not be ideal either.

The Python docs do call out that values removed from the actual code file before the module is reloaded will remain ("If the new version of a module does not define a name that was defined by the old version, the old definition remains."), which would cause...unexpected... behavior when trying to remove a configuration option and then SIGHUP a running gunicorn.

**Comment by benoitc** [comment]
@darkrain42 I don't understand this ticket. What were you doing?

**Comment by darkrain42** [comment]
Sorry, missed that question.  (I also meant to circle back and build up a self-contained demonstration of this issue.  Still haven't done that...sorry.)

The problem here was that I was trying to reload gunicorn with a SIGHUP after making changes to my gunicorn config file, but my changes weren't taking effect.

I was running Gunicorn as `gunicorn -c python:app.conf.gunicorn app.wsgi` (so, specifying the config file is an importable Python module, as opposed to `gunicorn -c ./app/conf/gunicorn.py ...`).

When I sent a SIGHUP to the Gunicorn master, it would kill all the old workers and spin up new ones, but the configuration file wasn't actually being re-read / re-imported.  So, for instance, if I initially started Gunicorn with 4 workers, and then changed that to 16 workers and sent the master a SIGHUP, Gunicorn would start up 4 new workers.

Reloading the Gunicorn config file this way works properly if the config file is specified as a filesystem path.

**Comment by benoitc** [comment]
I see. We can indeed probably do better there even if using the signal `USR2` should work.  Out of curiosity , are you trying to load the config from a standard format like ini or yaml?

**Comment by benoitc** [comment]
bump.

**Comment by darkrain42** [comment]
I'm using Python config files.  I added a demonstration of this to the test suite in https://github.com/darkrain42/gunicorn/commit/7f6bccae574bf2f3da9bd1a048ed7d33e2b7460c.  The first two tests will pass, but `test_reload_config_module` fails.

**Comment by tilgovi** [comment]
If we did use `reload`, maybe we could work around the danger by explicitly `pop`ing all the Gunicorn config names from the module's dictionary before the reload, ensuring that any removed settings aren't retained.

**Comment by tilgovi** [comment]
Untested, but maybe this is in the right direction:

```python
diff --git a/gunicorn/app/base.py b/gunicorn/app/base.py
index f3d3b4f..c52efff 100644
--- a/gunicorn/app/base.py
+++ b/gunicorn/app/base.py
@@ -100,7 +100,15 @@ class Application(BaseApplication):
         return cfg
 
     def get_config_from_module_name(self, module_name):
-        return util.import_module(module_name).__dict__
+        resolved_name = util.resolve_name(module_name)
+        if resolved_name in sys.modules:
+            module = util.import_module(module_name)
+        else:
+            module = sys.modules[resolved_name]
+            for k in self.cfg.settings:
+                module.__dict__.pop(k, None)
+            util.reload(module)
+        return module.__dict__
 
     def load_config_from_module_name_or_filename(self, location):
         """
diff --git a/gunicorn/util.py b/gunicorn/util.py
index 3bbb92c..af01c73 100644
--- a/gunicorn/util.py
+++ b/gunicorn/util.py
@@ -64,12 +64,28 @@ except ImportError:
 
 
 try:
-    from importlib import import_module
+    from importlib import import_module, reload
+    from importlib.util import resolve_name
 except ImportError:
-    def _resolve_name(name, package, level):
+    reload = __builtins__.reload
+
+    def resolve_name(name, package):
         """Return the absolute name of the module to be imported."""
+        if name.startswith('.'):
+            if not package:
+                raise ValueError("relative names require the 'package' argument")
+        else:
+            return name
+
         if not hasattr(package, 'rindex'):
             raise ValueError("'package' not set to a string")
+
+        level = 0
+        for character in name:
+            if character != '.':
+                break
+            level += 1
+
         dot = len(package)
         for x in range(level, 1, -1):
             try:
@@ -87,15 +103,7 @@ specifies the package to use as the anchor point from which to resolve the
 relative import to an absolute import.
 
 """
-        if name.startswith('.'):
-            if not package:
-                raise TypeError("relative imports require the 'package' argument")
-            level = 0
-            for character in name:
-                if character != '.':
-                    break
-                level += 1
-            name = _resolve_name(name[level:], package, level)
+        name = resolve_name(name, package)
         __import__(name)
         return sys.modules[name]
 
```

**Comment by benoitc** [comment]
i'm just wondering in which case you need to use the `python:` why loading the config as we do isn't enough?

**Comment by darkrain42** [comment]
I have a webapp that bundles its own gunicorn config as, e.g. `myapp.conf.gunicorn`, and is typically run within a virtualenv.  (I use a pre-exec hook, which is part of the reason I'm using a Python config file).

The particular path of the config file varies, depending on where/how the virtualenv is installed, whether the application was installed in editable mode (`pip install -e .`) (a development environment on my laptop), and what version of Python is in-use -- so, it would have been easier for me to start gunicorn as `gunicorn -c python:myapp.conf.gunicorn`

Currently, I'm using roughly this, which is part of a wrapper script that does various things, and then invokes gunicorn within a virtualenv:

```python
script = "import importlib; " \
    "print(importlib.import_module('%s').__file__)"

args = [virtualenv_python, "-c", script % (gunicorn_config)]

# Return a relative path to the file from the working directory, which
# is the top of the virtualenv. Also ensure return value is a source
# file, and not bytecode (only seems to be necessary in Python 2)
return os.path.relpath(
    subprocess.check_output(args).rstrip(b"c\n").decode("utf8"),
    virtualenv_path,
)
```

The return value is then passed as the `-c` argument to gunicorn.

**Comment by benoitc** [comment]
fixed sometimes ago.

**Comment by mindojo-victor** [comment]
This was NOT fixed. See #2258

**Comment by egberts** [comment]
I have a working prototype for a reloadable configuration module having the application settings.

They are located elsewhere over at github.com/egberts/pelican.  Look at `load_source()` function in [pelican/settings.py](https://github.com/egberts/pelican/blob/7f328851827e02fab7586218e9d6b76b4b6536b2/pelican/settings.py#L180) under `pytest` branch.
