### ISSUE TITLE
Binding multiple port problem

### ISSUE THREAD

**Issue by telking** [benoitc/gunicorn#1332]
I use gunicorn configuration file(/tmp/c.conf):

bind = 'unix:/tmp/c.sock', '0.0.0.0:8080'
pidfile = '/var/run/gunicorn/c.pid'
workers = 2
worker_class = 'gevent' # sync, gevent, meinheld
worker_connections = 5120
max_requests = 51200
timeout = 30
daemon = True
proc_name = 'c.com'
user = 'user'
group = 'user'
tmp_upload_dir = '/tmp/'

Start command:start-stop-daemon --start --make-pidfile --quiet --chdir /var/c.com --exec /usr/local/bin/gunicorn --pidfile /var/run/gunicorn/c.pid -- -c /tmp/c.conf manage:app

gunicorn is start fail

but bind = "'unix:/tmp/c.sock'  gunicorn is start ok

**Comment by benoitc** [comment]
what is .conf ? an debian ini?

in the py conf, we expect to have a list: http://docs.gunicorn.org/en/stable/settings.html#bind

**Comment by benoitc** [comment]
closing issue. no news since last answer.
