### ISSUE TITLE
Importing app with NameError

### ISSUE THREAD

**Issue by ptbrowne** [benoitc/gunicorn#1333]
I launch my application with

```
gunicorn "my_app:create_app()"
```

In `create_app()`, if there is a `NameError` like if variable was not declared, I get an `AppImportError` which swallows the original exception. I think it would be useful to print the original exception when catching the `NameError`.

```
        exc_type, exc_value, exc_traceback = sys.exc_info()
        traceback.print_exception(exc_type, exc_value, exc_traceback,
                                  limit=3, file=sys.stdout)
```

Made a mini [PR](https://github.com/benoitc/gunicorn/pull/1334).

**Comment by benoitc** [comment]
applied. thanks!
