### ISSUE TITLE
Please sign release tags

### ISSUE THREAD

**Issue by lamby** [benoitc/gunicorn#1335]
Hi @benoitc ,

It would be great if — in future -— you could sign release tags with some GPG signature? :)

/lamby

**Comment by benoitc** [comment]
maybe. What does it really give though?

**Comment by lamby** [comment]
Prevents someone tagging a commit that isn't you and that ending up in, say, Debian. No worries if not, just wondering.

**Comment by benoitc** [comment]
Well due to the little attention I port to my gpg signature (i don't attend
these keys signing party), not sure how it would help since it's trust
circle is low. But that's probably something that could be fixed :)

**Comment by tilgovi** [comment]
Keybase makes key management a lot easier, and makes it possible to maybe get sufficient trust in who someone is (online, not legally), without meeting in person for a key signing party.

It doesn't really matter to me to meet the individual in person who is @benoitc, it just matters to me that all the online personas of that individual are under the same control as the person with the key, that @benoitc the-person-who-publishes-gunicorn is @benoitc on Github/Twitter/etc and that they are the one that signed a release.

If you need a keybase invitation I have plenty.

**Comment by benoitc** [comment]
@tilgovi ok. let's do it that way then :)

**Comment by benoitc** [comment]
@tilgovi we should start something about it. ping me when you have some time :)

**Comment by tilgovi** [comment]
I am https://keybase.io/tilgovi and I don't mind signing releases that I make.
