### ISSUE TITLE
TypeError under py3k if response headers are bytestrings

### ISSUE THREAD

**Issue by Changaco** [benoitc/gunicorn#1340]
Strictly speaking it's not a bug since PEP 3333 says that request and response headers should be "native strings" (the `str` type). However, gunicorn already disregards the spec by accepting `unicode` under python2, so it'd be nice if it also accepted `bytes` under python3.

https://github.com/benoitc/gunicorn/blob/9021cf80bb91e1a90625ab8dbc65704279732f94/gunicorn/http/wsgi.py#L269

**Comment by benoitc** [comment]
We are accepting the unicode in python 2 because of legacy. The change should be done at application level. For now I prefer to be strict.
