### ISSUE TITLE
StatsD latency numbers too low when using gaiohttp workers

### ISSUE THREAD

**Issue by nate-opti** [benoitc/gunicorn#1343]
With `gaiohtp` workers, `gunicorn.request.duration` seems to be off by a factor of 1,000,000: 

For a request that takes 5 seconds to complete, gunicorn will send StatsD the value `0.005`, rather than the expected `5,000`

With synchronous workers, StatsD receives the expected value of `5,000`

Possibily related to https://github.com/benoitc/gunicorn/issues/1300, and the linked aiohttp access log format issue.

Using Pyramid and Python 3.5

**Comment by nate-opti** [comment]
Actually just tested this with a patched version of aiohttp that includes this commit: https://github.com/KeepSafe/aiohttp/pull/1117

And the same issue is present, so maybe not related to access log parsing.

**Comment by benoitc** [comment]
closing since this worker is not part any more from gunicorn .
