### ISSUE TITLE
"--config python:foo" module search path

### ISSUE THREAD

**Issue by dimaqq** [benoitc/gunicorn#1349]
What I'm trying to do:

```
# myapp/gunicorn.py
from . import something

def on_starting(...): ...
```

If I try to run it with `gunicorn -c file:myapp/gunicorn.py ...` if fails with "cannot perform relative import" because this file is not loaded as a module. OK, I can accept that.

If I try to run it with `gunicorn -c python:myapp.gunicorn ...` it fails with "Error: no module named 'myapp'".

Digging deeper, I find that when I run `python`, I get following for `sys.path`:
`['', '/usr/local/lib/python35.zip', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/usr/local/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages']`

However, when I run `gunicorn`, it has following for `sys.path`:
`['/usr/local/bin', '/usr/local/lib/python35.zip', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/usr/local/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages']`

(nevermind system-wide paths, that's because docker)

What's the canonical way?
- install myapp into system path?
- teach gunicorn to add "." to system path? (is there a command-line argument?)
- ugly hack in my config? (e.g. `-c file:xxx` which will chain-load real config)

**Comment by tilgovi** [comment]
Usually I would recommend installing the app and gunicorn into a virtualenv. On docker, the virtualenv isn't necessary because the container provides the isolated environment. Note that PEP8 recommends always using absolute imports.

**Comment by tilgovi** [comment]
You could probably also set the PYTHONPATH environment variable if you really don't want to install as a package.

**Comment by tilgovi** [comment]
I wonder if Gunicorn should add the working directory to the python path, though. It might make sense.

**Comment by benoitc** [comment]
@tilgovi what do you mean ? :)

**Comment by dimaqq** [comment]
OT: I'm not working on that product any more. In the end I worked around the limitation using a bootstrap file (i.e. start `file:bootstrap.py` which in turn sets up `sys.path` and imports real code). Doing that was also convenient for other settings (e.g. gunicorn settings).

**Comment by tilgovi** [comment]
@benoitc looking at the paths in the example, only the first one is different.

Python has ''.
Gunicorn has '/usr/bin/python'

The current directory seems more appropriate than the location of the gunicorn script.

I'll have a look at what happens with other entry points style scripts and such. I'll see if there's a simple thing I can recommend.

**Comment by benoitc** [comment]
@tilgovi maybe doing something like we do when the pythonpath setting is given?

https://github.com/benoitc/gunicorn/blob/ab444eed50f34df33755f4e778825de8d1bf9668/gunicorn/app/base.py#L196-L201

though I noticed that we are already adding the current directory to the sys path:

https://github.com/benoitc/gunicorn/blob/2b839ca14437c61780d6eaaa8b24ad31e021f2c6/gunicorn/app/wsgiapp.py#L46

So not sure why it wouldn't be found. Otherwise we could simply add `''` to the sys.path in any case

**Comment by mindojo-victor** [comment]
Was there a release with these changes?

**Comment by benoitc** [comment]
i will make a release when i come back next week.

**Comment by YunLiaw** [comment]
Hi @benoitc, is there any plan for releasing this feature? Thanks!

**Comment by YunLiaw** [comment]
@tilgovi Thanks!
