### ISSUE TITLE
How do I pass an arg to the application that gunicorn runs?

### ISSUE THREAD

**Issue by mw44118** [benoitc/gunicorn#135]
Right now, I start my web app like this:

```
$ gunicorn webapp:application
```

I want to feed some parameters to the application function inside my webapp.py.  In particular, I want to use a config file to adjust how my webapp works.

I read the docs for how to configure gunicorn with a config file, but I don't want that.

I tried this and got an error:

```
$ gunicorn webapp:application dev.cfg
```

As far as I can tell, gunicorn tried to find a callable named named "application dev.cfg".

Any ideas?

**Comment by pellunutty** [comment]
@benoitc it's been several years, can you tell me if this answer is still correct? I've not been able to get this approach to work for me.

**Comment by berkerpeksag** [comment]
@pellunutty I don't think the answer is correct now. You can subclass one of the application classes (e.g. `BaseApplication`) and parse relevant information  in `load_config` method. See http://docs.gunicorn.org/en/stable/custom.html for an example.

**Comment by gaecom** [comment]
please use the following codo to get arguments,then the error will be fixed
parser.parse_known_args()[0]
