### ISSUE TITLE
Port replication when using gunicorn with celery on docker

### ISSUE THREAD

**Issue by odedhar** [benoitc/gunicorn#1356]
Using gunicron 19.6.0 with celery 3.1.23 and django 1.82(issue also seen in other versions of Django and celery)
Broker = Redis (same issue also seen with RabbitMQ)
Running in Docker container.
It seems that all threads opened by gunicorn are using the same ports towards the broker:
From within the container, lsof -P | grep 6379 gives:
gunicorn 42 root 22u IPv4 42597 0t0 TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 root 23u IPv4 42598 0t0 TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 50 root 22u IPv4 42597 0t0 TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 50 root 23u IPv4 42598 0t0 TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 51 root 22u IPv4 42597 0t0 TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 51 root 23u IPv4 42598 0t0 TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 52 root 22u IPv4 42597 0t0 TCP 7439c59c1cba:49958->40.114.6.39:6379 (ESTABLISHED)
gunicorn 42 52 root 23u IPv4 42598 0t0 TCP 7439c59c1cba:49960->40.114.6.39:6379 (ESTABLISHED)

As can be seen, ports 42587 and 42598 are used by all threads opened by worker PID 42. This causes messages not reaching the broker from time to time (without any celery exception).

**Comment by benoitc** [comment]
> It seems that all threads opened by gunicorn are using the same ports towards the broker:
From within the container,

I do not understand the issue. How are you launching gunicorn? And what are you doing exactly?

**Comment by benoitc** [comment]
bump @odedhar .

**Comment by benoitc** [comment]
no answer. closing the issue. Also it's quite expected that gunicorn share the same socket.
