### ISSUE TITLE
Ability to pass in all config values as environment variables.

### ISSUE THREAD

**Issue by jmagnusson** [benoitc/gunicorn#1360]
Would be nice to be able to pass in settings as environment variables. Perhaps prefixed with `GUNICORN_`, i.e. `bind = '127.0.0.1:5002'` becomes `export GUNICORN_BIND='127.0.0.1:5001'`

Perfect when using docker.

**Comment by tilgovi** [comment]
I don't see any reason not to support it. Pull requests welcome.

**Comment by tilgovi** [comment]
Feel free to give PRs for any or all options you would like to see supported as environment variables.

**Comment by hramezani** [comment]
PR #1385

**Comment by benoitc** [comment]
fixed in latest master
