### ISSUE TITLE
Documentation for loading worker classes using entry points

### ISSUE THREAD

**Issue by fredrikhl** [benoitc/gunicorn#1365]
Looks like commit a397d90 removed the entry points for worker classes (e.g. `egg:gunicorn#sync`), but it is still documented as a valid way to load worker classes in the [stable documentation](http://docs.gunicorn.org/en/stable/settings.html#worker-class).

**Comment by benoitc** [comment]
This change was only for the logger plugin. Loading a worker via an entry point still work.

**Comment by fredrikhl** [comment]
Well, I'm not sure I can agree. They are no longer actual entry points that can be located by `pkg_resources`, or specified as `egg:gunicorn#<shortname>`.

The last line of the documentation:

> Alternatively, the syntax can also load the gevent class with `egg:gunicorn#gevent`.

```bash
~ $ gunicorn -v
gunicorn (version 19.6.0)
```
```bash
~ $ gunicorn -k egg:gunicorn#sync -w 2 -b 127.0.0.1:8080 foo:bar

Error: class uri 'egg:gunicorn#sync' invalid or not found: 

[Traceback (most recent call last):
  File "/home/env/lib/python2.7/site-packages/gunicorn/util.py", line 115, in load_class
    return pkg_resources.load_entry_point(dist, section, name)
  File "/home/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2597, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('gunicorn.workers', 'sync') not found
]
```
```bash
~ $ python
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.load_entry_point("gunicorn", "gunicorn.workers", "sync")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2597, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('gunicorn.workers', 'sync') not found
>>> 
```

It's a minor issue, but it took me some time figuring out after reading the docs.

**Comment by tilgovi** [comment]
This appears to be a valid bug and I'm re-opening it.

a397d90774d3b8975fc0c1120e52529b1de08c97 removed the entry points.

**Comment by benoitc** [comment]
change have been done in 2013, so 3 years ago anyway (now 4) . So far pkg resources are still available but not for gunicorn internal workers. Imo we should just removed the example from the command line. Thoughts?

**Comment by berkerpeksag** [comment]
I agree that this is a documentation issue. I will update it if someone doesn't beat me to it.
