### ISSUE TITLE
Support using inotify with --reload

### ISSUE THREAD

**Issue by mark-adams** [benoitc/gunicorn#1368]
`--reload` is a very useful option when debugging and working on an application. However, in some situations (such as running gunicorn inside of a VM or a Docker container on Mac with host mounted directories), the current file polling method can cause high CPU load due to the overhead of dealing with a virtualized filesystem.

Many of these filesystems now have support for the kernel's inotify API which allows applications to monitor for filesytem events instead of polling. This is much less resource intensive and can improve CPU usage of the Reloader in many situations. It would be nice to either have gunicorn support inotify by default (on supporting platforms) or via an extra argument.

**Comment by benoitc** [comment]
good idea :)

Can you send us a PR? Looking at your patch I would prefer to set it by augmenting the current setting: `--reload=inotify`  . So we don't introduce another setting.

**Comment by elliotbay22** [comment]
Hey, I just happened upon this as something I'd like for my development flow too.  When should I expect this will be available on pip?

**Comment by mark-adams** [comment]
Just wanted to follow-up @benoitc, do you have an estimate on when the next gunicorn release will happen that will include these changes?

**Comment by benoitc** [comment]
@mark-adams there is 1-2 patch to add to this release but there is no reason it can't be done next week.

**Comment by elliotbay22** [comment]
Ping!  I keep finding that this would be useful to me, but I'd rather not cut myself off from pip to patch the implementation myself.

**Comment by mark-adams** [comment]
@benoitc I hope I'm not being a bother, but I wanted to follow-up on a release containing this version. Is there any way that I can get my hands dirty and help move us towards a release?

**Comment by berkerpeksag** [comment]
@mark-adams I think #1422 is the only blocker for a new release at the moment. You could help us to review #1430 :)

**Comment by mark-adams** [comment]
Just left a comment. Thanks @berkerpeksag
