### ISSUE TITLE
pidfile naming changed on 19.6.0

### ISSUE THREAD

**Issue by tbarbugli** [benoitc/gunicorn#1382]
The pidfile postfix for the cycled process changed from `.oldbin` to `.2`. Perhaps I am the only soul on this planet to rely on this but having that mentioned in the changelog was going to save me a couple of hours for sure :)

My restart flow works like this:

- kill USR2 to pid stored in pidfile
- sleep 10s
- kill TERM to pid.oldbin

**Comment by benoitc** [comment]
The ticket describing the change was linked in the changelog:
http://docs.gunicorn.org/en/stable/news.html#core-logging

I'm not sure how more descriptive we could have been ...

**Comment by tbarbugli** [comment]
Something like "pidfile name changed for USR2 reloads (link to issue)" perhaps? I guess not many people will be affected by this (how common is what I do for reloads?). For the ones that are affected this is going to be painful though

**Comment by benoitc** [comment]
Maybe. 

Anyway I will add a note on the signals doc about it to notice the change. I'm keeping the ticket open until it's done.

**Comment by tilgovi** [comment]
@tbarbugli if you would like to leave a PR, I would be happy to merge it!

**Comment by berkerpeksag** [comment]
I'm going to merge https://github.com/benoitc/gunicorn/pull/1444 unless there are no objections.

**Comment by tilgovi** [comment]
:+1:
