### ISSUE TITLE
supervisor stop gunicorn and then start again

### ISSUE THREAD

**Issue by xiazhibin** [benoitc/gunicorn#1386]
`[program:app]`
`command=/ptahtogunicorn/gunicorn -c /project/gunicorn.py hello:app`
`directory=/project/`
`startsecs=10`
`startretries=3`
`user=none`
`stopwaitsecs=3`
`autostart=false`
`autorestart=false`

Here is the scenario:
  my gunicorn app is runing. I code `supervisorctl stop app` to stop gunicorn app and then code `supervisorctl start app` to start app.But failed,Here is the error log.

`[2016-11-08 11:33:29 +0000] [5155] [INFO] Handling signal: term`
`[2016-11-08 11:33:29 +0000] [5161] [INFO] Worker exiting (pid: 5161)`
`[2016-11-08 11:33:29 +0000] [5162] [INFO] Worker exiting (pid: 5162)`
`[2016-11-08 10:48:16 +0000] [4065] [INFO] Starting gunicorn 19.6.0`
`[2016-11-08 10:48:16 +0000] [4065] [ERROR] Connection in use: ('127.0.0.1', 5000)`
`[2016-11-08 10:48:16 +0000] [4065] [ERROR] Retrying in 1 second.`
`[2016-11-08 10:48:17 +0000] [4065] [ERROR] Connection in use: ('127.0.0.1', 5000)`
`[2016-11-08 10:48:17 +0000] [4065] [ERROR] Retrying in 1 second.`
`[2016-11-08 10:48:18 +0000] [4065] [ERROR] Connection in use: ('127.0.0.1', 5000)`
`[2016-11-08 10:48:18 +0000] [4065] [ERROR] Retrying in 1 second.`
`[2016-11-08 10:48:19 +0000] [4065] [ERROR] Connection in use: ('127.0.0.1', 5000)`
`[2016-11-08 10:48:19 +0000] [4065] [ERROR] Retrying in 1 second.`
`[2016-11-08 10:48:20 +0000] [4065] [ERROR] Connection in use: ('127.0.0.1', 5000)`
`[2016-11-08 10:48:20 +0000] [4065] [ERROR] Retrying in 1 second.`
`[2016-11-08 10:48:21 +0000] [4065] [ERROR] Can't connect to ('127.0.0.1', 5000)`
`[2016-11-08 10:48:21 +0000] [3910] [INFO] Parent changed, shutting down: <Worker 3910>`
`[2016-11-08 10:48:21 +0000] [3910] [INFO] Worker exiting (pid: 3910)`
`[2016-11-08 10:48:21 +0000] [3914] [INFO] Parent changed, shutting down: <Worker 3914>`
`[2016-11-08 10:48:21 +0000] [3914] [INFO] Worker exiting (pid: 3914)`
`[2016-11-08 10:48:21 +0000] [3916] [INFO] Parent changed, shutting down: <Worker 3916>`
`[2016-11-08 10:48:21 +0000] [3916] [INFO] Worker exiting (pid: 3916)`
`[2016-11-08 1048:21 +0000] [3918] [INFO] Parent changed, shutting down: <Worker 3918>`
`[2016-11-08 10:48:21 +0000] [3918] [INFO] Worker exiting (pid: 3918)`

But when the app is stopped,I code `supervisorctl start app` is ok,the app can run normally

**Comment by xiazhibin** [comment]
I find the solution

**Comment by zhipcui** [comment]
how? you should share the solution, it will help the one who meet the same problem.
