### ISSUE TITLE
mypy/PEP-484 annotations?

### ISSUE THREAD

**Issue by surrealcristian** [benoitc/gunicorn#1393]
Are you interested in add mypy/PEP-484 annotations to gunicorn?

**Comment by tilgovi** [comment]
I have no objection. It's an accepted PEP after all! I cannot speak for everyone, though.

**Comment by tilgovi** [comment]
If we do this, we should do it in the [comment style](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) so that we maintain Python 2 compatibility.

**Comment by benoitc** [comment]
what would be the benefits for the project?

**Comment by tilgovi** [comment]
It functions as a form of documentation and mypy/pytype/pylint either support it or have plans to. It may help contributors this way. It also might work to gently discourage confusing behavior like functions returning multiple types depending on the code path, which I find more error prone and difficult to reason about.

Mostly, I see it as having no negative effect at all, and maybe some gentle positives.

**Comment by benoitc** [comment]
if someone want to take care of it please let me know. Otherwise let's drop it, there is no need to keep an issue open if no one want to take care of it.

**Comment by tilgovi** [comment]
I don't feel a need to take a hard stance like insisting new code has type annotations. However, now that we're on Python 3 only there's nothing preventing it, so we should accept code with proper type annotations. I may try to do it myself when making changes.

**Comment by tilgovi** [comment]
Closed because I don't think it's realistic to expect that the current contributors will put in significant time to add types to code where it doesn't already exist. If anyone would like to make PRs to add types to any modules, please feel free.
