### ISSUE TITLE
Read TLS key before dropping privileges

### ISSUE THREAD

**Issue by cochiseruhulessin** [benoitc/gunicorn#1404]
I want to secure my traffic using TLS; however gunicorn requires me to give the unprivileged worker processes read access to the TLS server key.

**Comment by benoitc** [comment]
@cochiseruhulessin ? Only the user launching gunicorn normally need it. How can I reproduce it?

**Comment by tilgovi** [comment]
@benoitc take a keyfile, like the one in examples, and remove read permissions to others (`chmod o-r server.key`) then start gunicorn like so:

`sudo /path/to/gunicorn --certfile server.crt --keyfile server.key --user nobody --group nogroup echo:app`

Trying to make a request will cause gunicorn to error with:

    Traceback (most recent call last):
      File "/home/tilgovi/src/gunicorn/gunicorn/workers/sync.py", line 131, in handle
        **self.cfg.ssl_options)
      File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
        ciphers=ciphers)
      File "/usr/lib/python2.7/ssl.py", line 544, in __init__
        self._context.load_cert_chain(certfile, keyfile)
    IOError: [Errno 13] Permission denied

**Comment by benoitc** [comment]
closing the issue in favour of #1140
