### ISSUE TITLE
Doesn't seem that statsd instumentation sending the metrics over UDP 8125 port for gunicorn 19.6

### ISSUE THREAD

**Issue by sakumar1** [benoitc/gunicorn#1405]
Ran a simple app using..
gunicorn --workers=2 --statsd-host=localhost:8125 test:app

It doesn't seems to be sending the metrics to localhost using UDP port 8125...

Tried to create a dump using below...But nothing is getting captured..
sudo tcpdump -i eno16780032 -w dd.trace -n -v udp and host localhost and port 8125

Is there any logging that I can setup to test if the gunicorn statsd client is actually sending the metrics?

**Comment by daker** [comment]
Can you give more details ? what version are you using ? which python version ? i have tested version 19.6.0 and metrics are sent to statsd. Can you try to capture the traffic using ```sudo tcpdump -i any -w statsd-ts.dump "(port 8125)"```

**Comment by benoitc** [comment]
@sakumar1 ?

**Comment by spacez320** [comment]
It looks like I'm facing the same issue. Gunicorn 19.6.0, Python 2.7.9, CentOS 7.1. Statsd options work on the Gunicorn 19.4.5 platform, and then metrics disappear after moving it to 19.6.0. It's difficult for me to immediately prove this with tcpdump, since the application itself is sending other Statsd things in a separate logging facility.

**Comment by spacez320** [comment]
After a little bit of investigation;

I spun up a very simple application on 19.6.0 and was able to confirm that:
1. UDP packets were being sent to the statsd endpoint.
2. Metrics were appearing in Statsd.

However, on a hunch (based on 1187) I took one of my complex applications and removed the `--logger-class` argument. Statistics reappeared in Graphite after I did this. I'm wondering if the `--logger-class`/`--statsd-*` incompatibility has been reintroduced.

**Comment by berkerpeksag** [comment]
@spacez320, thanks for triaging this! :) Could you share your application (the simple one) and Gunicorn configuration with us so we can quickly take a look at the issue?

**Comment by spacez320** [comment]
Let me have a day or two to test my hypothesis with a hello_world app that also uses a custom logger class and I'll share the results.

**Comment by spacez320** [comment]
Let me have a day or two to test my hypothesis with a hello_world app that also uses a custom logger class and I'll share the results.

**Comment by spacez320** [comment]
Ok, I have a better example now exhibiting this behavior. Attached is my sample app and test logger as a zip. Actual files are outlined below:

*app.py*
```python
import logging
import random
import time


def app(environ, start_response):
    """
    Simplest possible application object.
    """
    # Generate random data and wait a random amount of time.
    time.sleep(random.randint(0, 2))
    data = '{}\n'.format(random.getrandbits(random.randint(1, 1000000)))

    logging.error("I processed a request.")

    status = '200 OK'
    response_headers = [
        ('Content-type', 'text/plain'),
        ('Content-Length', str(len(data)))
    ]

    start_response(status, response_headers)

    return iter([data])
```
*test_logger.py*
```
from gunicorn.glogging import Logger


class TestLogger(Logger):
    def __init__(self, cfg):
        super(self.__class__, self).__init__(cfg)

        # ...

        super(self.__class__, self).setup(cfg)
```

Running this application under `19.6.0` with various arguments:

- `gunicorn 'test.app:app' --pythonpath '/path/to/sample/app' --statsd-host statsd.localhost:8125 --statsd-prefix test.gunicorn --log-file=/tmp/gunicorn.log`

  Produces udp packages to `statsd.localhost:8125` as expected.

- `gunicorn 'test.app:app' --pythonpath '/path/to/sample/app' --logger-class test.test_logger.TestLogger --statsd-host statsd.localhost:8125 --statsd-prefix test.gunicorn --log-file=/tmp/gunicorn.log`

  Does not produce udp packates to `statsd.localhost:8125`.

[gunicorn_1405.zip](https://github.com/benoitc/gunicorn/files/809715/gunicorn_1405.zip)

**Comment by czarneckid** [comment]
@spacez320 I ran into this exact issue this past Friday. To use a custom logger class and have information sent to the statsd host, I had to inherit my custom logger from the `Statsd` class as directed [here](https://github.com/benoitc/gunicorn/pull/1188). 

Try:

```python
from gunicorn.instrument.statsd import Statsd


class TestLogger(Statsd):
    def __init__(self, cfg):
        super(self.__class__, self).__init__(cfg)

        # ...

        super(self.__class__, self).setup(cfg)
```

Once I inherited from the `Statsd` class, things worked as expected.

**Comment by tilgovi** [comment]
Since we never got a follow-up from @sakumar1, should we close this issue and open a new issue for statsd breaking with a custom logger class? Should we re-work statsd logging to not depend on the logger class? I'm not sure what exactly we should do yet, so maybe a new ticket to discuss is the best way forward.

**Comment by berkerpeksag** [comment]
> I'm not sure what exactly we should do yet, so maybe a new ticket to discuss is the best way forward.

+1.

**Comment by tilgovi** [comment]
See #1564.
