### ISSUE TITLE
multiprocessing in gevent worker

### ISSUE THREAD

**Issue by GrayMissing** [benoitc/gunicorn#1407]
```python
def notify(self):
    super(GeventWorker, self).notify()
    if self.ppid != os.getppid():
        self.log.info("Parent changed, shutting down: %s", self)
        sys.exit(0)
```
I am confused about this function, since it refuse to create sub process, I can't use multiprocessing in gevent worker.
someone have any idea?

**Comment by tilgovi** [comment]
A quick search for "gevent multiprocessing" reveals this: http://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing

Using the gevent worker will monkey patch all the standard library. You may be able to find a solution from that issue by either avoiding the part of multiprocessing that is incompatible or using an alternative library.

**Comment by jamadden** [comment]
FWIW that SO answer is quite old and under gevent 1.1 (and 1.2a1) multiprocessing is much more usable in a monkey-patched system. `multiprocessing.Queue` is still not usable, though, when threads have been patched.

**Comment by tilgovi** [comment]
Thanks, @jamadden
