### ISSUE TITLE
References to Boom need to be changed to Hey

### ISSUE THREAD

**Issue by bobh66** [benoitc/gunicorn#1411]
The Boom project has been renamed to Hey to avoid name duplication.  The references to Boom in the documentation need to be updated accordingly.

See https://github.com/rakyll/boom and https://github.com/rakyll/hey

**Comment by berkerpeksag** [comment]
Done in https://github.com/benoitc/gunicorn/commit/9a9e3acb2ca0514e2014574e7427e7ce488fbcfc.
