### ISSUE TITLE
python 2.7.6: wheel install failed

### ISSUE THREAD

**Issue by catroot** [benoitc/gunicorn#1413]
pip install gunicorn
Downloading/unpacking gunicorn
  Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB): 114kB downloaded
Installing collected packages: gunicorn
Compiling /tmp/pip_build_lnd/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/tmp/pip_build_lnd/gunicorn/gunicorn/workers/_gaiohttp.py", line 84
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

**Comment by berkerpeksag** [comment]
Thanks for the report. That's an harmless exception because the aiohttp worker doesn't work on Python 2. Also, recent versions of pip (I think I've fixed it ~2 years ago) doesn't show `SyntaxError`s anymore.
