### ISSUE TITLE
--reload flag changed semantics

### ISSUE THREAD

**Issue by Doerge** [benoitc/gunicorn#1422]
I just upgraded from the 19.6.0 release to the latest commit c54426c1e4b26b30c5feee2cec4450656ae147a3

I previously ran gunicorn like `gunicorn --reload mymodule:app` during development. However now I get the following error:
```
$ gunicorn --reload mymodule:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: No application module specified.
```
If I put an option after the reload flag it works.
```
$ gunicorn --reload -w=1 mymodule:app
[2017-01-05 11:02:33 +0000] [102] [INFO] Starting gunicorn 19.6.0
[2017-01-05 11:02:33 +0000] [102] [INFO] Listening at:  (102)
[2017-01-05 11:02:33 +0000] [102] [INFO] Using worker: sync
[2017-01-05 11:02:33 +0000] [105] [INFO] Booting worker with pid: 105
```

Calling it like `gunicorn --reload auto mymodule:app` also works, but then the argument isn't really optional. Perhaps the reload type should be non-optional to avoid confusion?

**Comment by berkerpeksag** [comment]
Thanks for the report. I think this has been fixed in master in https://github.com/benoitc/gunicorn/commit/8dbb2963b299ebbef2bd21270ae203c1eabf9e0e. Could you please try the master branch?

**Comment by Doerge** [comment]
Thanks for replying.

The commit I used (c54426c1e4b26b30c5feee2cec4450656ae147a3) is 2 after the one you point at. I installed it like: 
```
pip3 install --force-reinstall --upgrade git+git://github.com/benoitc/gunicorn@c54426c1e4b26b30c5feee2cec4450656ae147a3
```

**Comment by berkerpeksag** [comment]
Oops, you're right! I think we've hit a bug in argparse: http://bugs.python.org/issue9338

Another workaround:

```sh
$ gunicorn --reload -- mymodule:app
```

**Comment by berkerpeksag** [comment]
Here is a test case:

```diff
diff --git a/tests/test_config.py b/tests/test_config.py
index 9f9a2fe..f00aa60 100644
--- a/tests/test_config.py
+++ b/tests/test_config.py
@@ -285,3 +285,17 @@ def test_always_use_configured_logger():
     c.set('statsd_host', 'localhost:12345')
     # still uses custom logger over statsd
     assert c.logger_class == MyLogger
+
+
+@pytest.mark.parametrize("options, expected", [
+    (["myapp:app"], "off"),
+    (["--reload=poll", "myapp:app"], "poll"),
+    (["--reload", "myapp:app"], "auto"),
+    (["--reload", "--", "myapp:app"], "auto"),
+])
+def test_reload(options, expected):
+    cmdline = ["prog_name"]
+    cmdline.extend(options)
+    with AltArgs(cmdline):
+        app = NoConfigApp()
+    assert app.cfg.reload == expected
```

**Comment by berkerpeksag** [comment]
> I think we've hit a bug in argparse: http://bugs.python.org/issue9338

I was wrong. Issue 9338 is different than this.

Here is a pure Python snippet:

```py
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("args", nargs="*", help=argparse.SUPPRESS)
parser.add_argument("--reload", nargs="?", const="auto", default="off", help=argparse.SUPPRESS)

tests = [
    ("app:app", 'off'),
    ("--reload app:app", 'auto'),
    ("--reload poll app:app", 'poll'),
    ("--reload -- app:app", 'auto'),
    ("app:app --reload", 'auto'),
]

for args, expected in tests:
    got = parser.parse_args(args.split()).reload
    print("[%s] Test: %25s Expected: %10s Got: %10s" % ("P" if got == expected else "X", args, expected, got))
```

My vote is to document using `--` as a workaround.

**Comment by berkerpeksag** [comment]
If I apply the patch from http://bugs.python.org/issue9338 and replace

```py
parser.add_argument("args", nargs="*", help=argparse.SUPPRESS)
```

with

```py
parser.add_argument("args", nargs="+", help=argparse.SUPPRESS)
```

in the snippet I gave in https://github.com/benoitc/gunicorn/issues/1422#issuecomment-271131630, `--reload app:app` works as expected.

Since the `app:app` part is the only required argument, it might make sense to change `nargs` from `"*"` to `"+"` in line 82 in `gunicorn/config.py`:

```py
parser.add_argument("args", nargs="+", help=argparse.SUPPRESS)
```

**Comment by benoitc** [comment]
@berkerpeksag but we need the patch in Python for it right?

**Comment by berkerpeksag** [comment]
I can commit the patch (it's not ready to commit btw) to next Python 3.5 and 3.6 releases, but that would only work for 3.5+.

I see two viable solutions:

* Document the current behavior and the `--` workaround
* Since this change is not released yet we can introduce a new setting like `--reloader-backend` and keep the old behavior of `--reload`

**Comment by benoitc** [comment]
@berkerpeksag i'm asking myself if we should keep the old behaviour at all ...

**Comment by benoitc** [comment]
ie. we can just force the user to choose the reload type it needs when using the `--reload` setting. Which would be simpler.

**Comment by benoitc** [comment]
@tilgovi just saw the pacth was yours, what do you think about it also? Should we keep the old behaviour and add another setting to the long list we have? Or force the usage of the new behaviour implying to pass the reload type?

**Comment by berkerpeksag** [comment]
It would be nice to keep the old behavior. Another alternative solution is to remove `--remove=...` options and use the best options available implicitly.

**Comment by tilgovi** [comment]
:+1: for just using the best available

**Comment by berkerpeksag** [comment]
Ok, I will open a PR to implement it this week :)

**Comment by mark-adams** [comment]
I just commented about this on #1430 but I wanted to echo the same idea here.

If we simply always use the best available, we could box the user in. I've ran into scenarios where I was on an inotify-supported Linux system but using a FS mount that didn't support inotify. If we changed to use best available, users in that scenario would be out of luck without a way to force polling.

**Comment by tilgovi** [comment]
It's not the presence of kernel support, but the Python library that allows using it. In this case, the user could install into a virtualenv that doesn't have the library. Is that still enough of a pain that it's likely to cause problems for many users?

**Comment by tilgovi** [comment]
If the user has an app that needs to use inotify for its own reasons, maybe.

An alternatively might be to use automatic selection with the CLI flag but allow the config file to specify explicitly, if we really want to avoid breaking change to the flag AND preserve the option.

**Comment by mark-adams** [comment]
I see what you're saying. If the user doesn't wish to use inotify, they simply wouldn't install the itnotify Python library. I still think that this unnecessarily restricts the developer in situations where they may not be in a virtualenv and may not control the site-packages (i.e. The inotify package must be installed on the host but the underlying FS the source is stored on doesn't support inotify notifications).

I think we have to have some sort of manual option via flag and config to allow the user to force polling.

**Comment by berkerpeksag** [comment]
Thanks for the feedback! :) I understand the concern, but it doesn't look like a common use case to me. I'd say let's try this in 19.7 and see if we get any user complaints.

**Comment by benoitc** [comment]
@berkerpeksag not sure. We should make sure to keep some kind of stability. The original idea was to keep the command line we had and pass an optional option. Thing that is not possible  in python 2.x then...

 Looking at this issue makes me rethink to the feature plugin system that must be added to gunicorn . IMO the `reload` feature is a good citizen for a such system. In such system the `reload` feature would be added, and arguments given would be handled by it. Ie. optioinal arguments added to the command line by the plugin. So I would propose the following:

- By default the `reload` agument takes the best available
- We have a `--reload-engine` argument added to force the engine to use 

Next major release will ship the reload module as a plugin. 

Thoughts?

**Comment by benoitc** [comment]
so in clear I would merge the current patch of @berkerpeksag and in a new one add an option to force the engine. @berkerpeksag let me know what you think about it

**Comment by benoitc** [comment]
?

**Comment by berkerpeksag** [comment]
> * By default the reload agument takes the best available
> * We have a --reload-engine argument added to force the engine to use

Sounds good to me.

**Comment by benoitc** [comment]
@berkerpeksag ok thanks. I will take care of it ASAP this week

**Comment by berkerpeksag** [comment]
Great, thanks! Should I merge https://github.com/benoitc/gunicorn/pull/1430 in the meantime?

**Comment by benoitc** [comment]
@berkerpeksag yes please do :)
