### ISSUE TITLE
wsgi apps are fail to start on boot

### ISSUE THREAD

**Issue by viirak** [benoitc/gunicorn#1433]
This only happen on system startup. wsgi apps are fail to start due to this random class error.
However, after system is up, restarting uwsgi service again wsgi app start perfectly.

import random
  File "/srv/http/xxx/.env/lib/python3.6/random.py", line 742, in <module>
    _inst = Random()
SystemError: <class 'random.Random'> returned a result with an error set

Anyone have any idea? Thanks.

**Comment by berkerpeksag** [comment]
Thanks for the report. This is a regression in Python 3.6.0 and it has already been fixed in the 3.6 branch. You can either build it yourself or wait for the 3.6.1 bugfix release (which will be released on early March)
