### ISSUE TITLE
Is there interest in supporting sched_setaffinity for workers?

### ISSUE THREAD

**Issue by zt-initech** [benoitc/gunicorn#1436]
I wondered if people think a feature that pins worker processes to CPU cores (in a way that spreads the load over all cores evenly) is useful (i.e. measurably improves performance) and whether anyone has such code already they can contribute.

I want to at least benchmark this. If no one has the code, I'll try to write it myself.

Should I work on this or do people already know that it's a bad idea, and that's why there is no code to do this?

I plan to use `os.sched_setaffinity()` on Python 3.3+ and `psutil.Process().cpu_affinity()` otherwise.

**Comment by berkerpeksag** [comment]
Thanks for the report. I don't remember if anyone has worked on this before so feel free to do an experiment!

I think you can just use `os.sched_setaffinity()`. The next major release will likely support Python 3.3 and later versions.

**Comment by zt-initech** [comment]
@berkerpeksag But the next major release won't drop support for python 2.7, right? I actually use python 2.7, but will of course test on python 3 too.

**Comment by berkerpeksag** [comment]
The next major release (20.0) will drop Python 2 support as well, but we will continue to maintain 19.x series.

**Comment by benoitc** [comment]
stalled issue

**Comment by neozhao98** [comment]
I found it here because I encountered similar problems in real production environment, I believe this feature is very valuable, and what do you think about this? @benoitc @berkerpeksag 
If you are willing to adopt this feature, I will endeavour to complete the corresponding Benchmark/Code/Document.
