### ISSUE TITLE
Supporting newest version of python

### ISSUE THREAD

**Issue by samuelcolvin** [benoitc/gunicorn#1439]
Gunicorn currently doesn't run tests with python3.6.

Since 3.6 is release and some of us are preparing to use it in production it would be great if gunicorn had confirmed support.

Also `setup.py` classifiers doesn't include 3.5 or 3.6.

**Comment by berkerpeksag** [comment]
Thanks for the report. Could you share which tests are broken?

**Comment by samuelcolvin** [comment]
I assume none are actually broken, I would assume it's as simple as adding python3.6 to tox?

(Unless of course you take the "if it's not tested, it's broken" approach, in which case they all are :smile:)

**Comment by berkerpeksag** [comment]
I just ran tests with my CPython copy (3.7.0a0) and they all passed so you're right :) We just need to update tox.ini, .travis.yml and setup.py.

(Glad to see someone's planning to use Python 3.6 in production :))

**Comment by samuelcolvin** [comment]
Personally I have

```yaml
python:
- '3.5'
- '3.6'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: '3.6-dev'
  - python: 'nightly'
```

For example [here](https://github.com/samuelcolvin/arq/blob/master/.travis.yml) so I know when future version of python are breaking. I assume you could setup the same thing with tox?

**Comment by berkerpeksag** [comment]
Thanks, I've implemented a similar idea with tox.
