### ISSUE TITLE
Consider deprecating --spew

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#1442]
Do we find `--spew` still useful? Its output is huge and rarely useful. We can deprecate it in 19.7 and remove in 20. It should be easily implemented by using the `on_starting` hook if needed.

**Comment by benoitc** [comment]
this options has proved to be useful in the past. Imo any instrumentation and way to log the internals should be the core of gunicorn

**Comment by benoitc** [comment]
@berkerpeksag maybe could be part of a more general `debug ` plugin?

**Comment by berkerpeksag** [comment]
> @berkerpeksag maybe could be part of a more general debug plugin?

+1, that would be a good idea.

**Comment by benoitc** [comment]
closing the issue. I think we should introduce tracing and such inside gunicorn but there is no need need to keep that ticket open right now.
