### ISSUE TITLE
When is 19.7 going to be released?

### ISSUE THREAD

**Issue by tgwizard** [benoitc/gunicorn#1445]
Hi,

I saw that the version had been bumped in https://github.com/benoitc/gunicorn/commit/467834ca0cf6d0f73c6d2bcd7470c914c15c7a95, but there's as of yet no new release on PyPI - over there it's still 19.6. When is 19.7 meant to be released?

I'm eagerly awaiting it - I'd like to have the functionality from https://github.com/benoitc/gunicorn/pull/1313.

I apologize if this has been brought already, or if I should have used the mailing list. It seems that the mailing list archive is down - http://lists.gunicorn.org/user, linked to from the http://docs.gunicorn.org/en/stable/community.html and http://gunicorn.org/#community, responds with a missing DNS.

**Comment by berkerpeksag** [comment]
Thanks for the report! I think there are a few blockers that we should address for 19.7. One of them is #1422.

> [...] It seems that the mailing list archive is down [...]

Yep, this is a known issue :) See #1362 for details.

**Comment by benoitc** [comment]
you can track the 19.7 progress here: https://github.com/benoitc/gunicorn/milestone/14 . I would say soon.
