### ISSUE TITLE
Warn users on unused command line options for specific workers

### ISSUE THREAD

**Issue by RyPeck** [benoitc/gunicorn#1447]
What the best way to communicate to a user that based on a specific worker type - a setting is ignored? Would this be desired?

Recently had an issue in dev where the application was working when using the `tornado` worker and not the `gevent` worker. Found out that the `tornado` worker uses it's own HTTP parser and doesn't use the `limit_request_field_size` other workers use which is the limit we were bumping up against and causing the bug.

Another example, at one point I had gone down the route of wondering why `threads` setting had no impact on the `gevent` worker type before I discovered it was `worker_connections` I need to use to limit the application the way intended.

This situation can be improved two ways, more explicit documentation around these settings or some kind of warning emitted when processing configuration that the certain options will be ignored for your worker type.

Happy to work on both with some guidance. Ideally without affecting the existing setting parameters drastically. Though initially I thought a [sub-parser](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers) for each worker types would be useful - that would be a big change and do nothing for any users who are using settings that are ignored by their chosen worker type. Though perhaps this could be a change in version 20.

Thoughts?

**Comment by berkerpeksag** [comment]
+1 for improving documentation. I'd be happy to review and merge a documentation PR :)

> Though initially I thought a sub-parser for each worker types would be useful - that would be a big change and do nothing for any users who are using settings that are ignored by their chosen worker type.

Assuming the number of incompatible settings are limited, we could store them in a dictionary [1] and raise a warning in `Config`.

[1] For example:

 ```py
incompatible_settings = {
    'worker_class': {
        'gtornado': ['limit_request_field_size'],
    }
}
```

**Comment by benoitc** [comment]
having a plugin system in mind, maybe we should have a config dependency system with a common ground? The current Config module is already able to take the config from imported module in it. Maybe we could have a way to set specific worker settings / workers. And then also check the config they import by using for example the gunicorn http parser or any module that advertise some config?

**Comment by benoitc** [comment]
no actions happened there and for me documlentation is clear enough. I'm closing the issue then. If any details on some option need to be added please open a ticket or a PR for it.
