### ISSUE TITLE
X-Accel-Redirect with non-ascii filenames

### ISSUE THREAD

**Issue by fle** [benoitc/gunicorn#1448]
Since the 19.4 release and this commit : https://github.com/benoitc/gunicorn/issues/1151, it seems like using `X-Accel-Redirect` with a non-ascii URI is not possible anymore.

Though RFC 7230 says that http headers _should_ be encoded in USASCII, shouldn't have we an exception for this kind of header? Without it, `X-Accel-Redirect` function is not available since we have files with a non-ascii filename.

Furthermore, it's curious that nginx still has a `X-Accel-Charset utf-8` by default.

Thanks for reading this,

**Comment by dracos** [comment]
You provide a URI in `X-Accel-Redirect`, not a filename, so can you not %-encode the filename first, as you normally would for a URI? For example, with the nginx docs example of `location /protected_files { internal; root /var/www; }`, and a file at `/var/www/protected_files/café.png`, an `X-Accel-Redirect` header of `/protected_files/caf%c3%a9.png` works fine.

`X-Accel-Charset` is for the content type of the file, not the headers.

**Comment by tilgovi** [comment]
@fle does the comment above help you or is this still an issue?

**Comment by Eugeny** [comment]
I had this problem and it worked for me
