### ISSUE TITLE
gunicorn fails with http status code 429

### ISSUE THREAD

**Issue by komuW** [benoitc/gunicorn#1451]
I have a web application with nginx sitting in front of gunicorn. 
Every so often, gunicorn fails a request and returns http status code 429 as seen in gunicorn_access.log 
         
`127.0.0.1 - - [01/Feb/2017:12:19:10 +0000] "POST /my-example-uri/ HTTP/1.0" 429 78 "-" "Go-http-client/1.1"`          
there's nowhere in my code where I return a 429 http status code, gunicorn is doing that on it's own.

my environment:                      
ubuntu 14.04                        
gunicorn version: 19.2.1      
aws t2.medium instance with 4GB ram and 2vCPUs           

and gunicorn is ran as:        

`gunicorn config.wsgi:application --workers=3 --bind="0.0.0.0:3000" --timeout=35 --access-logfile /var/log/gunicorn_access.log`

**Comment by benoitc** [comment]
gunicorn itself don't also send a status 429. Maybe the framwork is?

**Comment by komuW** [comment]
thanks, let me dig in further,

**Comment by komuW** [comment]
@benoitc thanks. 
stupid me, we are using django rest framework(djrf) and we have enabled API throttling on our requests. 
I hadn't realised that djrf, returns status 429 for throttled requests: https://github.com/tomchristie/django-rest-framework/blob/97d848413e5e13e9de83b7e840fc719b9ec0d9c7/rest_framework/exceptions.py#L205
