### ISSUE TITLE
SIGTERM not so graceful

### ISSUE THREAD

**Issue by pvalsecc** [benoitc/gunicorn#1457]
I was trying to get some code coverage for my application and was failing. While investigating, I found the problem: the worker processes are never gracefully shutdown.

According to the doc:

> TERM: Graceful shutdown. Waits for workers to finish their current requests up to the graceful timeout.

The worker_int callback is never called in my code.

If you look at the code, this is not what's being done:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L259

Shouldn't we add a line like that in `Arbiter.handle_term` before raising the exception?
```
self.stop(True)
```

**Comment by berkerpeksag** [comment]
Thanks for the report. I think your analysis is correct (haven't had a chance to try it myself yet) Would you like to send a pull request?

**Comment by berkerpeksag** [comment]
Hmm, on another hand, we already call `self.halt()` when `StopIteration` is raised (which `self.halt()` itself calls `self.stop()`)

**Comment by pvalsecc** [comment]
I've tried and the worker is still not calling the sig handler. There must be another problem. Even if I send INT TERM or QUIT to a slave process directly, the callbacks are not called. All my master side callbacks are OK, but the worker ones are just never called. Appart from the startup ones which are OK.

**Comment by pvalsecc** [comment]
All that for doing code coverage ;-)

**Comment by benoitc** [comment]
@pvalsecc can you give us more details? AMond details that could be useful:

- What is the worker used? 
- which version of gunicorn
- how do you know the hook is never called? Do you have any code that could help us to reproduce it? 

To my knowledge `worker_int` is only executed on QUIT or INT signal, not on TERM.  You can use the `worker_exit` hook on EXIT for it I think. Do you need to run your hook in the worker context?

**Comment by pvalsecc** [comment]
I use the default worker with 5 processes and 20 threads. Gunicorn version 19.6.0 (tried with master as well). I run with python 3.5.

The log message I've put in my hook is never shown and the atexit of coverage is not called.

I've tried all signals. Yes, I need it to be run in the worker context if I want code coverage for the stuff executed by the worker.

The code is a bit all over the place but the parts of interest for you are those:

- https://github.com/camptocamp/c2cwsgiutils/blob/coverage/c2cwsgiutils_run
- https://github.com/camptocamp/c2cwsgiutils/blob/coverage/c2cwsgiutils/gunicorn_config.py
- https://github.com/camptocamp/c2cwsgiutils/blob/coverage/c2cwsgiutils/wsgi_app.py

**Comment by tilgovi** [comment]
`worker_int` is only called for immediate shutdown (`QUIT` or `INT`). As far as I know, this should work.

It looks like the relevant code and links are no longer there. @pvalsecc if this is still an issue for you, please re-open and I can try to take a look.

**Comment by pvalsecc** [comment]
All good, now. Thanks.
