### ISSUE TITLE
[Request] Add keep alive on tcp socket to detect dead connections

### ISSUE THREAD

**Issue by zhangi** [benoitc/gunicorn#1458]
Is it possible to add a parameter to control the TCP keep-alive option to let gunicorn detect dead connections that have been aborted at client side? Sometimes the gunicorn server just hang and using netstats shows that the dead connections are the root cause.

**Comment by benoitc** [comment]
"the dead connections are the root cause." what do you mean there ? How to reproduce it?

**Comment by zhangi** [comment]
sorry, i will try to reproduce it and close it first.

**Comment by maxim-devpronet** [comment]
Here is the issue that I experience:

On macOS (Darwin .... 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64):

A client does not handle the handshake, i.e. syn (client->server) and syn+ack (server->client) but not ack from client and nothing else. I see just 2 packets. That is what I see in tcpdump. The connection is listed as ESTABLISHED in netstat. When I view the error log from gunicorn, I can see that some workers (sync type) do not end up with "Closing connection" message in the log. I see they handle GET or POST but there is no "Closing connection" following with the same PID. Such workers stuck and over time, it may end up with no workers. I have to kill them all and restart gunicorn. Hope that gives more information about the problem.
