### ISSUE TITLE
Provide a pre_exit server hook

### ISSUE THREAD

**Issue by arusahni** [benoitc/gunicorn#1464]
My application (sync worker, threaded) registers with an external service when it spins up.  Similarly, it must deregister when it exits.

Right now, I'm handling the deregistration via an `atexit` handler in my app, which does the job. However, it seems that it always takes `graceful_timeout` seconds to terminate the daemonized gunicorn process, even if there are no active requests.  Since gunicorn refuses incoming connections when `SIGTERM` is received, this leads to an awkward state where things are running, but not accepting new connections.

I'd like to be able to handle this deregistration when the gunicorn process starts shutting down. Is this something that could be supported, or is what I'm doing too much of an abomination? 😉

**Comment by benoitc** [comment]
`worker_int`  hook should do the trick.
