### ISSUE TITLE
Link to the mailing list archive is broken

### ISSUE THREAD

**Issue by surrealcristian** [benoitc/gunicorn#1470]
In http://gunicorn.org/#community, a paragraph says:

"The archive for this list can also be [browsed online](http://lists.gunicorn.org/user)."

The link http://lists.gunicorn.org/user is broken.

**Comment by berkerpeksag** [comment]
Thanks for the report! This is known problem and it's been discussed in #1362.

**Comment by benoitc** [comment]
also I decided to not use a mailing list and only use [Github](https://github.com/benoitc/gunicorn/projects) for the project management and discussions. Some projects Like spacemacs are already doing it with success.

I created a wiki that contains the rules: https://github.com/benoitc/gunicorn/wiki/Project-management 

will update the website later today and reference github issues to each projects today so it will be annonced with the release tomorrow.
