### ISSUE TITLE
Mailing list archive `lists.gunicorn.org` isn't resolvable.

### ISSUE THREAD

**Issue by spacez320** [benoitc/gunicorn#1474]
It looks like the archive mailing list link listed in the Community section of the Gunicorn documentation doesn't resolve anywhere. http://docs.gunicorn.org/en/stable/community.html#mailing-list

```
[matthew@chorismos ~]$ nslookup lists.gunicorn.org
Server:         139.162.131.5
Address:        139.162.131.5#53

** server can't find lists.gunicorn.org: NXDOMAIN
```

**Comment by benoitc** [comment]
@spacez320 it's a known issue. I decided sometimes ago to use github as the main canal of discussion and all discussion will be done via tickets. For more info have a look on https://github.com/benoitc/gunicorn/wiki/Project-management 

i will fix the doc for #1471

**Comment by spacez320** [comment]
Sounds good, thanks @benoitc, sorry for the noise.

**Comment by benoitc** [comment]
@spacez320 no pb, thanks for the report anyway. Doc is now fixed.
