### ISSUE TITLE
Python3 compatibility with inotify reload_engine

### ISSUE THREAD

**Issue by jcbelanger** [benoitc/gunicorn#1477]
While using the inotify reload_engine, I get the following error with python 3.6:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/reloader.py", line 106, in run
    self._watcher.add_watch(dirname, mask=self.event_mask)
  File "/usr/local/lib/python3.6/site-packages/inotify/adapters.py", line 67, in add_watch
    wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path, mask)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
````

According to the example from inotify's [readme](https://github.com/dsoprea/PyInotify/blob/74d182112332269d436b8381c02468f95fa87ca3/inotify/resources/README.rst#example)
 > Note that the directories to pass to the add_watch() and remove_watch() functions must be bytestring (in Python 3).  The same holds for the contents of the events that are returned.

It seems both calls to `add_watch` do not convert to bytes for Python 3:

[reloader.py:90](https://github.com/benoitc/gunicorn/blob/bc20bea7d9a86ebf2bd1cf62766ecc299b940d77/gunicorn/reloader.py#L90)

[reloader.py:106](https://github.com/benoitc/gunicorn/blob/bc20bea7d9a86ebf2bd1cf62766ecc299b940d77/gunicorn/reloader.py#L106)

It also seems the strings from inotify's events may also not be encoded properly:

[reloader.py:108](https://github.com/benoitc/gunicorn/blob/bc20bea7d9a86ebf2bd1cf62766ecc299b940d77/gunicorn/reloader.py#L108)

**Comment by ewjoachim** [comment]
(Reproduced with a bare setup (Python3 docker, pip install gunicorn inotify, gunicorn --reload, crashes on startup)

**Comment by benoitc** [comment]
should work with latest version.
