### ISSUE TITLE
How to print request and response header in log file

### ISSUE THREAD

**Issue by komaldedhia** [benoitc/gunicorn#1478]
Hi,

I am adding --access-logformat "%(t)s %({Header}i)s" while starting Gunicorn but only "[10/Mar/2017:03:13:19 +0000] -" gets printed. Any help is appreciated.

Thanks,
Komal.

**Comment by tuukkamustonen** [comment]
Which header are you trying to log? You should replace "Header" with the actual name of the header, like `%({Host}i)s` and also ensure you're actually sending that header.

**Comment by komaldedhia** [comment]
Hi,

I want to print request header with query params and response status.
If I don't specify any  "--access-logformat" in start, it prints request with query params and response status and sensitive information like IP address. My main reason for including --access-logformat is that I don't want to log IP address. 
I am using flask and I am no where capturing request header but still it gets printed in logs.
Any example with a sample flask might help me?

Thanks,
Komal.

**Comment by benoitc** [comment]
@komaldedhia have a look about the format there:

http://docs.gunicorn.org/en/stable/settings.html#access-log-format . You will need to pass the correct string to the setting. Headers need to be given using their name as you don't want to have all headers in one line generally. If you need more you can probably log them in your app also.

**Comment by benoitc** [comment]
no feedback from @komaldedhia but closing as it seems to have been answered.

**Comment by douloveppt** [comment]
哈哈哈

**Comment by krishmoodbidri** [comment]
I want to print the request header variables, like username etc in a file. Not access log. How do I go about it?
