### ISSUE TITLE
[Question] Scaling a Mobile API Backend w/ Gunicorn

### ISSUE THREAD

**Issue by aalhour** [benoitc/gunicorn#1484]
Hello there,

I didn't know how to ask this question better, this is why I opened an issue here.

I would like to first say thanks to everyone who is involved in making this great project happen.

I have a Python web service which is a backend for a mobile app running on a server with the following specs and I would like to know whether Gunicorn will be a good fit to make it scale for a predictable amount of traffic. The Web Service exposes a RESTful API written in Flask and SQLAlchemy, the database is on the same server, and it's powered by PostgreSQL. I would like to design a solution that would scale easily in the future in terms of requests per second. Here is the current server information and the Gunicorn configuration file I am playing with:

Server:
  * 2 GB RAM.
  * 1 CPU Core.
  * 30 GB SSD Storage.

Gunicorn config file:
```python
import os
import multiprocessing as mp
import configparser as cp

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGS_DIR = os.path.join(BASE_DIR, "logs")
CONFIG_DIR = os.path.join(BASE_DIR, "etc")
RUN_DIR = os.path.join(BASE_DIR, "run")
PID_FILE_PATH = os.path.join(RUN_DIR, "example.pid")
APP_CONF_FILE = os.path.join(CONFIG_DIR, "example.conf")

_config_reader = cp.ConfigParser()
_config_reader.read(APP_CONF_FILE)

# Make sure that the log file exists.
LOG_FILE_PATH = os.path.join(LOGS_DIR, str(_config_reader["logging"]["file_name"]))

bind = "0.0.0.0:5000"
preload_app = False

worker_class = "gevent"
workers = (int(mp.cpu_count()) * 2) + 1

pidfile = PID_FILE_PATH
daemon = False
proc_name = "my_own_server_name"
backlog = 2048
worker_connections = 1024
max_requests = 2048
max_requests_jitter = 100
timeout = 300
keepalive = 2
logger_class = "gunicorn.glogging.Logger"
loglevel = "info"
accesslog = LOG_FILE_PATH
errorlog = LOG_FILE_PATH
log_file = LOG_FILE_PATH
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" "response_time=%(L)s seconds"'
```

The APIs almost always touch the database whether by reading, writing or both. Drawing from other apps with somewhat close ideas and a targeted demographic of users, the traffic will not be less than 5k requests per second on average, I am shooting for a solution that solves the C10K problem.

Thanks a lot for your time,
Cheers!

**Comment by benoitc** [comment]
@aalhour there are large website that are using Gunicorn for such purpose. Reading the links below would help you to setup the infra you need for it:

- http://docs.gunicorn.org/en/stable/design.html
- http://docs.gunicorn.org/en/stable/deploy.html

Depending on your need you may want to use an async worker (if you do SSE or websockets for example). While you can't mix workers for now you can start different gunicorn nodes one, for quick and normal request using the sync worker, one for ws, ... And put that behind a router (varnish, nginx, ...) .

**Comment by aalhour** [comment]
Thanks @benoitc for your answer, I have read the referenced links.

The web application doesn't support SSE or WS requests, all requests are CRUD operations against a RESTful API that is backed by a relational database. Would starting Gunicorn with an Async worker type, such as `gevent`, and multiple worker processes solve the problem of supporting 10k req/s?
