### ISSUE TITLE
gunicorn: error: unrecognized arguments: --settings appname.wsgi with version 19.7.0 on python3

### ISSUE THREAD

**Issue by tarikki** [benoitc/gunicorn#1486]
Downgrading to 19.6.0 helped, starter script runs flawlessly.

**Comment by tarikki** [comment]
It's a bash script, here it is:

[myapp.txt](https://github.com/benoitc/gunicorn/files/854105/myapp.txt)

**Comment by tilgovi** [comment]
The `--settings` flag has been deprecated and removed in 19.7.0.

You have `DJANGO_SETTINGS_MODULE` configured already. I think this should just work. If you need to pass this environment variable to the workers explicitly, you can also use the `--raw-env` option: http://docs.gunicorn.org/en/stable/settings.html#raw-env
