### ISSUE TITLE
Worker processes documentation update for aiohttp 2.0

### ISSUE THREAD

**Issue by ekolve** [benoitc/gunicorn#1489]
With the release of aiohttp 2.0 the worker-class string needs to change to "aiohttp.GunicornWebWorker" from "gaiohttp". (http://aiohttp.readthedocs.io/en/stable/deployment.html#nginx-gunicorn)

http://docs.gunicorn.org/en/stable/settings.html#worker-processes should get updated to reflect the change and specify the correct string.

**Comment by benoitc** [comment]
does it means there is no more aiohttp worker in gunicorn that work with latest version of aiohttp?

**Comment by benoitc** [comment]
cc @fafhrd91 @asvetlov
