### ISSUE TITLE
Why arbiter 'wakeup' after handling signal in main loop 

### ISSUE THREAD

**Issue by xybaby** [benoitc/gunicorn#1490]
I has used gunicorn for a long time, and i like the source code very much. However, I have a question which confuse me a piece of time, i have googled,but got no answers. The question shows below:
in Arbiter.py, method "Arbiter.run" calls "self.wakeup" at line212:
![clipboard](https://cloud.githubusercontent.com/assets/26700964/24339238/19985660-12dd-11e7-87a6-1e1e30bf79c6.png)
 but i don't know why should we  call 'wakeup' here(at line212). I got that we use pipe to wakeup arbiter from sleeping, and arbiter would sleep only if no signal happen(at line196). The only reason i can guess is that the wakeup(at line 212) making the sleep call(at line 196) return immediately, but why it is necessary?

**Comment by tilgovi** [comment]
It does seem unnecessary to me, too. The code has been there for a very long time. The commit message in db01c210a2afd52ad4b373bb54c3e211c01cd99a does not really explain why this was added.

If there are pending signals, the queue should be empty so the sleep is skipped in the next iteration. If there are not pending signals then we should not sleep.

We might be able to take this out, but we would have to test carefully. I would not want to start missing signals.

**Comment by xybaby** [comment]
@tilgovi thank you!

**Comment by benoitc** [comment]
This allows the worker to not sleep to much and let the signals accumulate if i remember well.  I will reread that part more carefully over the week though :)

**Comment by benoitc** [comment]
closing issue as answered
