### ISSUE TITLE
Gunicorn not responding -- Ignored premature client disconnection.

### ISSUE THREAD

**Issue by brianmhunt** [benoitc/gunicorn#1497]
Given:

- gunicorn 19.7.1
- Python 2.7.9
- Debian 8 
- Kernel 3.16.39-1+deb8u2
- On Google Compute Engine

### wsgi.py
(this is just from a demo that ought to work; the "real" Flask application works fine without gunicorn but has the same timeout as this simple example)
```
def application(env, start_response):
    start_response('200 OK', [('Content-Type', 'text/html')])
    return ["Hello!"]
```

Running:
```bash
$ gunicorn wsgi --log-level=debug
```

Yields:

> [2017-04-10 18:01:25 +0000] [31956] [INFO] Starting gunicorn 19.7.1
> [2017-04-10 18:01:25 +0000] [31956] [DEBUG] Arbiter booted
> [2017-04-10 18:01:25 +0000] [31956] [INFO] Listening at: http://127.0.0.1:8000 (31956)
> [2017-04-10 18:01:25 +0000] [31956] [INFO] Using worker: sync
> [2017-04-10 18:01:25 +0000] [31961] [INFO] Booting worker with pid: 31961
> [2017-04-10 18:01:25 +0000] [31956] [DEBUG] 1 workers

Then using netcat to test it with e.g. `echo -en "GET /ping HTTP/1.0\n\n\n" | nc localhost 8000`  times out with:

> [2017-04-10 18:07:36 +0000] [31977] [CRITICAL] WORKER TIMEOUT (pid:31982)
> [2017-04-10 18:07:36 +0000] [31982] [INFO] Worker exiting (pid: 31982)
> [2017-04-10 18:07:36 +0000] [31985] [INFO] Booting worker with pid: 31985

Alternatively, sending SIGINT (ctrl-c) to `nc` instance while waiting yields:

> [2017-04-10 18:01:28 +0000] [31961] [DEBUG] Ignored premature client disconnection. No more data after: 'GET /ping HTTP/1.0\n\n\n'

Using `--spew` didn't illuminate anything obvious.

I searched but didn't find anything of any relevance on Google or GitHub searches, but will post back if I find something.

Cross-post with [Serverfault.SO](http://serverfault.com/q/843726/14686)

**Comment by brianmhunt** [comment]
In spite of no changes at all (other than the passage of time from yesterday to today), it's working as expected now.

If nobody else is reporting this, I'd say we chalk it up to user error.  :wink:

Closing for now lack of reproducibility.

**Comment by jadhavmanoj** [comment]
Hello @brianmhunt,
I am facing the same issue. couldn't find the workaround for this? 
Can you elaborate what you did?

Thanks

**Comment by brianmhunt** [comment]
The only thing that I can recall that might've made a difference is using gunicorn from `pip` instead of `apt-get`.

**Comment by ayushin** [comment]
Hmm ran into same

**Comment by rashidyusuf26feb** [comment]
> Hello @brianmhunt, I am facing the same issue. couldn't find the workaround for this? Can you elaborate what you did?
> 
> Thanks

Hi Manoj,Did you resolve this issue,I am facing the same issue
