### ISSUE TITLE
umask isn't applied to log files

### ISSUE THREAD

**Issue by palisadoes** [benoitc/gunicorn#1500]
I'm using:

1) Python 3.5.2
2) gunicorn (19.7.1)

The errorlog and accesslog options don't create files according to the umask setting. It looks like it should be set in glogging.py, but isn't.

This is a security issue for my application which creates log files 666 permissions instead of 664 or 660 as I'd like.

The documentation states that the umask is set for all files created by gunicorn. In this case it doesn't seem to be so. http://docs.gunicorn.org/en/stable/settings.html

**Comment by benoitc** [comment]
which command line were you using? Under which user did you launch gunicorn?

**Comment by palisadoes** [comment]
Benoit,

I'm using it in the AgentAPI class at this link
https://github.com/palisadoes/switchmap-ng/blob/master/switchmap/main/agent.py
.

It was derived from this: http://docs.gunicorn.org/en/latest/custom.html

Background Information:

This script starts / stops / restarts a pair of dependent Flask / Gunicorn
daemons used in a web application -
https://github.com/palisadoes/switchmap-ng/blob/master/bin/systemd/switchmap-ng-api


It uses the AgentAPI class which controls the Gunicorn daemon which is
causing the issue.

I'd like to know whether this is a bug, or an implementation error on my
part. The log file always gets 666 permissions no matter what I set the
umask to.

**Comment by palisadoes** [comment]
Do you need anything more from me?

**Comment by benoitc** [comment]
stalled issue. I don't reproduce it.
