### ISSUE TITLE
Worker shutdown hooks

### ISSUE THREAD

**Issue by tt-jsr** [benoitc/gunicorn#1508]
I have a worker that spawns a thread for some housekeeping duties. When the server is shutdown, is there a way to receive some sort of notification/callback so I can shutdown my thread?

**Comment by benoitc** [comment]
You can use the `worker_exit` hook for it: http://docs.gunicorn.org/en/stable/settings.html#worker-exit

**Comment by tt-jsr** [comment]
Thanks for the response, but I can't seem to import any of my modules in order to shutdown my threads. How do I access my server code from the config file? I've tried looking at the arbiter, but I don't see any way to attach any meaningful context or user data that would get passed into the hook.

**Comment by willpatera** [comment]
I am also looking for a way to import modules in my `gunicorn_config.py` within the `on_starting` server hook, but also am not able to import any modules into the config file. It seems that all paths are correctly specified. @benoitc could you please let us know if this is possible?

**Comment by jordaniversen** [comment]
Looking for this feature also.  Any update?

**Comment by benoitc** [comment]
`on_exit` or `worker_exit` hooks get either the server or worker ovbject directky which allows to handle this; old issue with no activitt since awhile closing it. If still requires pleas eopen a discussion about it.
