### ISSUE TITLE
docs are lacking.   kill -HUP masterpid results in internal server error

### ISSUE THREAD

**Issue by kinganu** [benoitc/gunicorn#1510]
just started using nginx gunicorn stack on ubuntu 16 for django web apps (in a python3.5 venv).  been a horrendous configuration so far.  heres what it says in the docs on restarting gunicorn, but its frustrating that no where is it stated how to find the masterPID of application:

You can gracefully reload by sending HUP signal to gunicorn: $ kill -HUP masterpid

after digging around I found this command: to locate pid:  pstree -ap|grep gunicorn

saw about 4 pids, and one main one (top left of tree).   why is there no where to easily find common gunicorn commands like restart, stop, start. enable, reload-daemon etc.

**Comment by benoitc** [comment]
How docs are lacking, here is HUP signalis associated to the master: http://docs.gunicorn.org/en/stable/signals.html#master-process

To find it you can either store its pid in a pidfile, check it by its name in `ps aux`, read the log, or use the first one listed in gunicorn processes (except on openbsd).

As for the extension of the command line, how would you know which server to handle if you launch multiple gunicorn on the same machine?

**Comment by tilgovi** [comment]
Thanks for your report, @kinganu.

Gunicorn is not a supervisor and so it doesn't have commands like start/stop/kill. You can run gunicorn under systemd or supervisor or whatever your choice if you want these commands. Gunicorn supports writing a pidfile if that's helpful for your situation.

If you have an actionable recommendation for ways we can improve the documentation, please let us know. The best would be to offer a PR.
