### ISSUE TITLE
Request parser strips leading slash from path

### ISSUE THREAD

**Issue by YuppY** [benoitc/gunicorn#1512]
I am faced with strange behavior of gunicorn: different requests `GET /foo` and `GET //foo` are parsed with same path `/foo`.
It is caused by fix of https://github.com/benoitc/gunicorn/issues/297

Here is PR with fix of this issue: https://github.com/benoitc/gunicorn/pull/1511
Could anyone review it?

**Comment by benoitc** [comment]
imo considering // as / is the correct behaviour and is in place since a long time. 

Did it cause any issue on your side? How to reproduce it?

**Comment by YuppY** [comment]
It is causing security issue. When we configure reverse proxy to pass all requests except `/secret/*` to gunicorn app, then an attacker bypasses this rule by requesting `//secret/*`.

**Comment by YuppY** [comment]
Replied with email.
