### ISSUE TITLE
How to pass args to workers?

### ISSUE THREAD

**Issue by smontanaro** [benoitc/gunicorn#1521]
I'm switching a Flask app from a multithreaded setup to a gunicorn-fronted multiprocess setup. (I've never tried gunicorn before.) I used to run my application like so:
`    python .../server.py --host=0.0.0.0 --port=NNNN --logfile=...`
etc. Those workers will still want to log (probably want to give each one its own log), and I might well want to use some of my debugging flags to inspect them. How does that change with a gunicorn setup?

**Comment by smontanaro** [comment]
(My apologies, I don't know how to make this issue go to the forums either...)

**Comment by tilgovi** [comment]
Gunicorn can be given a logging configuration and you can set the configuration for your application's package in the standard way that one configures Python logging.

There is no way to pass arguments to workers. Your `if __name__ == '__main__'` is never `True` when run through Gunicorn. Your app code is imported directly and called as a function.

Here are the log related settings: http://docs.gunicorn.org/en/latest/settings.html#logging
Also some notes here: http://docs.gunicorn.org/en/latest/deploy.html#logging

**Comment by ngolin** [comment]
@tilgovi Is there a way to share values between workers?

**Comment by tilgovi** [comment]
@ngolin there is not. It is recommended that you use some kind of disk or network storage for sharing data between workers.
