### ISSUE TITLE
Pylint failures on master

### ISSUE THREAD

**Issue by edmorley** [benoitc/gunicorn#1525]
There are pylint failures on retriggers of master:
https://travis-ci.org/benoitc/gunicorn/jobs/241969228

This is presumably due to the unpinned version of prospector.

**Comment by tilgovi** [comment]
@berkerpeksag since you seem to be doing a bunch of work on the linting, just wanted to flag you here so you can close this when it's time.

**Comment by berkerpeksag** [comment]
@tilgovi thanks for the ping! This is indeed can be closed now. The build is green since https://travis-ci.org/benoitc/gunicorn/builds/252849831

Thank you for the report, @edmorley.
