### ISSUE TITLE
syslog unix domain socket type assumption

### ISSUE THREAD

**Issue by guj-zz** [benoitc/gunicorn#1530]
Using syslog_addr='unix:///dev/log' on Linux leads to a crash due to unhandled exception in _connect_unixsocket self.socket.connect:

> socket.error: [Errno 91] Protocol wrong type for socket

This is caused by the assumption AF_UNIX -> SOCK_STREAM in parse_syslog_address:
`if addr.startswith("unix://"): sock_type = socket.SOCK_STREAM`
At least on Linux, Unix domain sockets may be, and in the case of syslog, actually are served by daemons expecting SOCK_DGRAM. Python 2.7 SysLogHandler does the right thing:

> For Unix sockets, you can also specify a socktype of None, in which case socket.SOCK_DGRAM will be used, falling back to socket.SOCK_STREAM.

I suggest defaulting sock_type to None, see https://github.com/guj-zz/gunicorn/commit/af92742143605e095d080e776579852394393937 (can send PR). Thanks.

**Comment by tilgovi** [comment]
Sounds great. I would be happy to review a PR.

**Comment by guj-zz** [comment]
Thank you. Here is #1547,  a trivial change that should avoid the problem.

**Comment by guj-zz** [comment]
Hello Randall.

Thank you for your reply.

On 14/07/2017 20:22, Randall Leeds wrote:
> Sounds great. I would be happy to review a PR.

Thanks. I created PR #1547 and added a comment on Issue #1530.

Cheers,
Steve

**Comment by tilgovi** [comment]
Closed by #1547
