### ISSUE TITLE
Error at install time with python 2.7

### ISSUE THREAD

**Issue by MikHulk** [benoitc/gunicorn#1531]
With python 2.7 we get an error on console when install gunicorn from Pipy:
```
pip install gunicorn
Downloading/unpacking gunicorn
  Downloading gunicorn-19.7.1-py2.py3-none-any.whl (111kB): 111kB downloaded
Installing collected packages: gunicorn
Compiling /tmp/pip-build-Igb5AO/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/tmp/pip-build-Igb5AO/gunicorn/gunicorn/workers/_gaiohttp.py", line 84
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

Successfully installed gunicorn
Cleaning up...
```

Install goes on, however, and gunciorn seems to work correctly.

**Comment by berkerpeksag** [comment]
Thanks for the report. That's an harmless exception because the aiohttp worker doesn't work on Python 2. Also, recent versions of pip (I think I've fixed it ~3 years ago) doesn't print `SyntaxError`s anymore. Please upgrade your pip version.

**Comment by MikHulk** [comment]
Ok thx.
