### ISSUE TITLE
utf8mb4 seems is not supported well by gunicorn

### ISSUE THREAD

**Issue by Colbert337** [benoitc/gunicorn#1534]
It seems that utf8mb4 is not supported well by gunicorn , I use utf8 is ok.

the logs is:

```
File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
LookupError: unknown encoding: utf8mb4
2017-06-23 16:06:45 [6826] [INFO] Worker exiting (pid: 6826)
2017-06-23 16:06:45 [6813] [INFO] Shutting down: Master
2017-06-23 16:06:45 [6813] [INFO] Reason: Worker failed to boot.
```

```
ubuntu@ubuntu:/var/www$ pip list
alembic (0.9.1)
apt-xapian-index (0.45)
argparse (1.2.1)
bcrypt (3.1.3)
cffi (1.10.0)
chardet (2.0.1)
click (6.7)
colorama (0.2.5)
configobj (4.7.2)
dataset (0.8.0)
Flask (0.12)
Flask-Caching (1.2.0)
Flask-Migrate (2.0.3)
Flask-Script (2.0.5)
Flask-Session (0.3.1)
Flask-SQLAlchemy (2.2)
gunicorn (19.7.1)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.9.6)
Landscape-Client (14.01)
Mako (1.0.6)
MarkupSafe (1.0)
mistune (0.7.4)
MySQL-python (1.2.5)
netaddr (0.7.19)
normality (0.4.2)
PAM (0.4.2)
passlib (1.7.1)
pip (1.5.4)
pycparser (2.17)
PyMySQL (0.7.10)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5)
python-debian (0.1.21-nmu2ubuntu2)
python-editor (1.0.3)
PyYAML (3.12)
requests (2.13.0)
setuptools (3.3)
six (1.10.0)
SQLAlchemy (1.1.6)
SQLAlchemy-Utils (0.32.12)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
Werkzeug (0.12.1)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)
```

**Comment by jamadden** [comment]
I don't see anything in your supplied stacktrace that implicates gunicorn. Perhaps it's MySQL or your MySQL driver that doesn't support this encoding. What makes you think this is a gunicorn-specific issue? Can you (not) reproduce the problem under other WSGI servers, such as gevent.pywsgi, waitress or wsgiref?

**Comment by berkerpeksag** [comment]
Yeah, I would check if utf8mb4 is supported by the MySQL version you've installed. In any case, I think this should be fixed either by SQLAlchemy or MySQL-python.

Also, I did a quick Google search and according to https://bitbucket.org/zzzeek/sqlalchemy/commits/5794b777cbb4 and https://bitbucket.org/zzzeek/sqlalchemy/commits/58ce4d53bf5e, SQLAlchemy already has a workaround for the `LookupError` exception (I didn't take a look at the latest version of that code)

I'm closing this as 'invalid'. Good luck with debugging!

**Comment by Colbert337** [comment]
thankyou! I will see it!
