### ISSUE TITLE
Drop aiohttp support

### ISSUE THREAD

**Issue by asvetlov** [benoitc/gunicorn#1536]
Sorry, @fafhrd91 and I are not responsible on fixing the project issues related to aiohttp.

We have own [gunicorn worker](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/worker.py) and do keep it in sync with all aiohttp changes but Gunicorn's version is outdated and literally doesn't work.

Please just drop it.

**Comment by berkerpeksag** [comment]
I will update #1418.

**Comment by berkerpeksag** [comment]
This has been done in PR #1569.
