### ISSUE TITLE
Gunicorn: Not able to start It from remote server

### ISSUE THREAD

**Issue by ethicalmohit** [benoitc/gunicorn#1545]
I am trying to run gunicorn for an application but it's not able to run from any remote server or by any other tool. However, When I am trying to execute the script from bash by logging in into the server then its working fine. I have also tried supervisord but getting the same error. Is there anything which I am missing out?

```
ssh -t ubuntu@ec2-xx-xx-xx.us-west-2.compute.amazonaws.com << EOF
bash /home/ubuntu/code/xyz/gunicorn_start2
EOF
gunicorn_start2
```

```
#!/bin/sh
export PROJECT_ENV="dev"
exec /home/ubuntu/code/xyz xyz.wsgi:application --name xyz --workers 4 --user=ubuntu --timeout=3600  --debug --log-level debug --daemon

```

**Comment by tilgovi** [comment]
I don't fully understand your question, @ethicalmohit. Can you give an example of a command that works and a command that does not work? What is `/home/ubuntu/code/xyz`?

**Comment by ethicalmohit** [comment]
@tilgovi It works. It has issues with the environmental variable.
