### ISSUE TITLE
Custom application slower than commandline version

### ISSUE THREAD

**Issue by tomjaguarpaw** [benoitc/gunicorn#1549]
I'm writing a "custom application" based on the code here: http://docs.gunicorn.org/en/latest/custom.html.  It runs correctly but it is much slower at processing requests than the version run from the command line.  I get about 2 requests per second, as opposed to 13 requests per second from the command line (which is about as fast as my app can run).

My "custom application" uses the same code from the snippet linked above to run a Flask app which runs Tensorflow.  I had to use `workers = 1` because the Tensorflow context can't be shared between multiple workers.  My understanding is that the command line version only uses a single worker anyway.  The command line I am using is

    gunicorn -b 0.0.0.0:5001 app:app --access-logfile=-

which is about as simple as can be.  Can anyone explain what might be causing the relative slowdown and what I can do about it?

**Comment by RyPeck** [comment]
@tomjaguarpaw is that command line you reference how you start the custom application? I would think that for a custom application you just run it with Python - not Gunicorn.

**Comment by tomjaguarpaw** [comment]
No, that's how I start the command line version.  I do indeed start the custom application with Python.

**Comment by tomjaguarpaw** [comment]
Actually cancel that.  The problem I was experiencing was due to something else entirely!

I can confirm that the "custom" recipe in the above link works well!

**Comment by djstrong** [comment]
What was your problem?

My tensorflow code is two times slower using gunicorn vs. command line. Is this issue applicable to gunicorn as well https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api ?

**Comment by tomjaguarpaw** [comment]
> What was your problem?

I'm afraid I can't remember at all!
