### ISSUE TITLE
Redandant 'is not None'

### ISSUE THREAD

**Issue by tomjaguarpaw** [benoitc/gunicorn#1550]
The `is not None` here looks redundant

https://github.com/benoitc/gunicorn/blob/56ef7710dd3e0b1343f3f157e2afb10a1237395d/gunicorn/app/base.py#L196

**Comment by berkerpeksag** [comment]
Thank you for the report. Would you like to send a PR?

**Comment by tomjaguarpaw** [comment]
Sure, here you go! https://github.com/benoitc/gunicorn/pull/1551/files

**Comment by tomjaguarpaw** [comment]
There's another one here.  I'm really puzzled by this style.  It makes me thing something I don't understand is going on.

https://github.com/benoitc/gunicorn/blob/56ef7710dd3e0b1343f3f157e2afb10a1237395d/gunicorn/app/wsgiapp.py#L16

**Comment by tomjaguarpaw** [comment]
I've submitted three more PRs for this.  If and when they are merged the issue can be closed.

https://github.com/benoitc/gunicorn/pull/1558

https://github.com/benoitc/gunicorn/pull/1557

https://github.com/benoitc/gunicorn/pull/1556

**Comment by berkerpeksag** [comment]
All PRs have been merged. Thanks!
