### ISSUE TITLE
Using SO_REUSEPORT is extremely counterintuitive

### ISSUE THREAD

**Issue by tomjaguarpaw** [benoitc/gunicorn#1553]
Using SO_REUSEPORT for binding sockets is extremely counterintuitive.  It's far more likely that I will reuse the wrong port by accident than it is that I really wanted to share the port.  Is there any chance this behaviour could be placed behind an option?

**Comment by tilgovi** [comment]
Sounds sensible. I would welcome a PR for that.

**Comment by tilgovi** [comment]
I am not sure what the right default is, though.

**Comment by tilgovi** [comment]
The ticket is to make SO_REUSEPORT opt-in.

**Comment by benoitc** [comment]
closing in favour of #1603
