### ISSUE TITLE
Expose metrics to outside world

### ISSUE THREAD

**Issue by vkaverin** [benoitc/gunicorn#1560]
Currently Gunicorn support export of internal metrics to Statsd (http://docs.gunicorn.org/en/stable/instrumentation.html).
But StatsD is not always part of a solution and may be undesirable (by any reason).

It would be nice if Gunicorn allow to get these metrics by HTTP `GET` request via some port/endpoint combination to any monitoring system could get it.

**Comment by jamadden** [comment]
Given that gunicorn is composed of multiple processes (and the OS does the distribution), that would seem to add substantial burden and difficulty. In effect, it would have to reimplement what statsd does (a distributed stat collection architecture), but poorly (only for one process tree). 

This seems very wrong to me.

**Comment by tilgovi** [comment]
I think I agree with @jamadden here. The best I can think is that in course of solving #1564 we could maybe expose a way to customize instrumentation in case someone has a use case for something other than statsd. @vvk do you think we can move this discussion over there? Maybe you can just comment there with your use case, so it can be considered as we discuss possibilities for future instrumentation code.

**Comment by vvk** [comment]
@jamadden, @tilgovi thank you guys for the comments.

My use case is quite simple: I have a set of Gunicorn workers (which actually running inside Docker) and a monitoring system that collects metrics over HTTP by some endpoints. It collects metrics not from Gunicorn only, but from many modules in the solution which provide metrics by HTTP as JSON.

It think that idea of #1564 is quite good and may cover this scenario as well if the workers could write not StatsD only, but in other systems/databases like InfluxDB (in my case) directly.

**Comment by benoitc** [comment]
maybe we should have a prometheus instrumentation and offer a configurable metrics handler ? at least wiyh the prometheus instrumentation we could then propose different format to output the metrics. Thoughts?

**Comment by vvk** [comment]
I'm not familiar with the prometheus, but
> we could then propose different format to output the metrics

sounds good and may cover various scenarios.

**Comment by Code0x58** [comment]
A similar situation is coming up where I work, the best I can see to do with things in their current state is to use use the [hooks](http://docs.gunicorn.org/en/stable/settings.html#server-hooks) to plug something in.

A more generic way to add handlers to these hooks could be useful, e.g. like [Django's middleware](https://docs.djangoproject.com/en/1.11/topics/http/middleware/). This kind of thing would be a good way to the move statsd reporting out of the a Logger class (which I saw an issue about), and having isolated extensions (another issue).

**Comment by ykusakabe** [comment]
Hello @Code0x58 
I was trying to make as hook/plugin-style as possible in my pull request for #1564 .
However for things like instrumentation that counts the number of errors/warnings and so on, I thought it wouldn't be realistic to setup the hook execution points in all the log-related methods, so I wrapped the instrumentation methods by the log-related functions dynamically according to the setting.

I believe the implementation of this pull request is essentially the same as Django's middleware implementation in terms of loading methods in arbitrary classes into execution points.

Plz feel free to check it and give feedback on it. I'd like to find out what's the best solution here :)

**Comment by canberkkoc** [comment]
My situation is exactly as: 
> But StatsD is not always part of a solution and may be undesirable (by any reason).   

@vkaverin said.
I have Nagios up and running and i don't want to install Statsd(Node.js), so if we could make an API(or a service like this) for metrics it would be wonderful.

**Comment by benoitc** [comment]
closing issue. superseded by #1564
