### ISSUE TITLE
Worker class documentation error

### ISSUE THREAD

**Issue by jltchiu** [benoitc/gunicorn#1561]
http://docs.gunicorn.org/en/stable/settings.html

In your worker class documentation, you suggests

`-k STRING, --worker-class STRING`

but I think it should be fixed to `-k STRING, --worker_class STRING`

It took me a while after I see the title looks different than the content...

**Comment by vvk** [comment]
`worker_class` is format for a configuration file, but `--worker-class` is a command line argument. Dash-separator is a common practice for the ones.

**Comment by berkerpeksag** [comment]
Thank you for the report. @vvk is correct. `worker_class` should be used in a Python configuration file:

```py
worker_class = 'sync'
```

And `--worker-class` should be passed to the `gunicorn` CLI:

```sh
gunicorn test:app --worker-class sync -b 127.0.0.1:7878
```
