### ISSUE TITLE
gunicorn setting - timeout parameter

### ISSUE THREAD

**Issue by Kunal12** [benoitc/gunicorn#1563]
How to restart gunicorn worker after it is idle for "set through configurable" timeout period?
As per gunicorn doc. I set --timeout=60 secs, but after 60 secs of idle timeout period gunicorn workers are not restarting ....

**Comment by tilgovi** [comment]
The timeout parameter is for detecting workers that are stuck and fail to check in with the arbiter. In the case of synchronous workers, this often means they are handling a long request that exceeds the timeout. It is not for killing idle workers. If you need that feature, you can open a feature request. If you can find a way to update the documentation to make this more clear, please open a pull request for review. Thanks!

**Comment by benoitc** [comment]
@Kunal12 also what is your usage for such thing?

**Comment by Kunal12** [comment]
Thank you very much for the help.
And I have used 'max_requests' parameter to restart gunicorn workers.
It solved our problem...

**Comment by pietdaniel** [comment]
I have a simple app which uses `--worker-class gevent`. It seems the timeout behaves differently then with `--worker-class sync` in that it doesn't timeout at all. The app is as follows:

```python
def app(environ, start_response):
    time.sleep(1000)
    data = b"Hello, World!"
    start_response("200 OK", [ ("Content-Type", "text/plain"), ("Content-Length", str(len(data))) ])
    return iter([data])
```

Is this the expected behavior? If so, is the `--timeout` flag ignored completely when using gevent?

**Comment by tilgovi** [comment]
The timeout flag is not a request timeout. It is a timeout for worker heartbeats.

**Comment by tilgovi** [comment]
Looks like the original request for this issue is no longer open.

**Comment by jamadden** [comment]
When you use the gevent worker, your app is monkey-patched. That means that `time.sleep()` cooperates with gevent and other greenlets can run while the greenlet that called it sleeps. The heartbeat runs in its own greenlet, and runs concurrently, so the master process never misses a heartbeat.
