### ISSUE TITLE
gunicorn worker hanging issue 

### ISSUE THREAD

**Issue by saurabhprakash** [benoitc/gunicorn#1579]
We've an application running with gunicorn(version 19.7.1 , with supervisor and python3), Gunicorn settings looks like this:

    exec ../bin/gunicorn ${WSGI_MODULE}:application \
      --name $NAME \
      --workers $NUM_WORKERS \
      --bind unix:$SOCKFILE \
      --log-level=debug \
      -k gevent\
      --worker-connections 1001\
      --max-requests 200\
      --max-requests-jitter 500\
      --graceful-timeout 30\
      --log-file "gunicorn.log" \
      --timeout 60

Above works fine, but sometimes suddenly some workers goes to non-responding state or respond very late, at that time gunicorn.log looks like following:

    [2017-08-26 10:12:04 +0000] [19244] [DEBUG] GET /api/locator/
    [2017-08-26 10:12:24 +0000] [19249] [DEBUG] GET /api/locator/
    [2017-08-26 10:12:24 +0000] [19249] [DEBUG] Closing connection.

If you see above logs 2 GET request were made but only one was closed. 

On restarting through supervisor it works fine for some time, till again some of the workers become non-responsive. 

What can be reasons for same, how can we debug(fix) it? 

No other errors in logs other than sometimes it prints "[2017-08-26 10:14:53 +0000] [19249] [DEBUG] Ignoring EPIPE".

**Comment by tilgovi** [comment]
It's hard to know without a reproducible example. Is there any chance your application is actually get stuck somewhere, not Gunicorn? Could you add logging around that endpoint in your application code to know whether it completes?

**Comment by saurabhprakash** [comment]
@tilgovi : Couple of points in regard to your question:

1. We've checked other dependent components which seems to be working fine during same time.
2. Not all the workers die/hang, only some of them does, So during same instance other workers respond for similar requests.

Any suggested approach to do worker level monitoring(debugging), what issue it is facing ?

**Comment by tilgovi** [comment]
I would make sure you log when that handler returns. Then we can know if Gunicorn gets a response and hangs or if the app hangs.

**Comment by benoitc** [comment]
@saurabhprakash what does your code ? any possibility it could bloc the gevent event loop ?

**Comment by benoitc** [comment]
@saurabhprakash ?

**Comment by saurabhprakash** [comment]
@benoitc : Sorry for late reply, 

Figured it out that application workers while communicating with redis we were facing issue.. at tcp layer some of the connections were going non-responsive. So neither redis nor gunicorn were raising any errors as such.

But yes the issue was not with gunicorn. We can close the issue.

Thanks for the support.
