### ISSUE TITLE
How to run Gunicorn standalone and using https?

### ISSUE THREAD

**Issue by jenstroeger** [benoitc/gunicorn#1580]
(I guess this should go into the Forum.)

I’ve created a certificate and keyfile like so:
```bash
openssl req -newkey rsa:2048 -nodes -keyout myserver-dev.key -x509 -out myserver-dev.crt
```
in order to support https. I’m also using [Pyramid’s paste configuration](https://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/deployment/gunicorn.html) with the following settings:
```
[server:main]                                                                                       
use = egg:gunicorn#main                                                                             
host = 0.0.0.0                                                                                      
port = 6543                                                                                         
workers = 1                                                                                         
keyfile = myserver-dev.key                                                                           
certfile = myserver-dev.crt                                                                          
```
Running this seems to work:
```
> ./bin/gunicorn --paste myserver-dev.ini
[2017-08-30 07:38:53 +1000] [82477] [INFO] Starting gunicorn 19.7.1
[2017-08-30 07:38:53 +1000] [82477] [INFO] Listening at: https://0.0.0.0:6543 (82477)
[2017-08-30 07:38:53 +1000] [82477] [INFO] Using worker: sync
[2017-08-30 07:38:53 +1000] [82480] [INFO] Booting worker with pid: 82480
2017-08-30 07:38:53,973 INFO  [srv][MainThread] Starting web app
```
However, when I send an actual request to the server using [httpie](https://github.com/jakubroztocil/httpie), I receive an error:
```
> ./bin/http get https://0.0.0.0:6543/api/ping

http: error: SSLError: HTTPSConnectionPool(host='0.0.0.0', port=6543): Max retries exceeded with url: /api/ping (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)'),)) while doing GET request to URL: https://0.0.0.0:6543/api/ping
```
What am I missing here?

**Comment by berkerpeksag** [comment]
I think you need to either disable certificate verification or pass your `keyfile` and `certfile` to `http`. See https://github.com/jakubroztocil/httpie#https for details.

**Comment by berkerpeksag** [comment]
Passing `--verify=certificate.pem` worked for me. I think the correct file name would be `myserver-dev.crt` in your case.

```sh
$ http --verify=certificate.pem https://0.0.0.0:8888/
HTTP/1.1 200 OK
Connection: close
Content-Length: 14
Content-type: text/plain
Date: Wed, 30 Aug 2017 00:34:24 GMT
Server: gunicorn/19.7.1
X-Gunicorn-Version: 19.7.1

Hello, World!
```

Anyway, there is no issue with Gunicorn here so I'm closing this. Thank you for the report!

**Comment by jenstroeger** [comment]
Thanks @berkerpeksag! 

Looking at the [httpie docs](https://github.com/jakubroztocil/httpie#https) it seems that I have three options:
 1. `http --verify=no …` worked for me. ([doc](https://github.com/jakubroztocil/httpie#server-ssl-certificate-verification))
 2. I haven’t tried the custom CA bundle. ([doc](https://github.com/jakubroztocil/httpie#custom-ca-bundle))
 3. `http --cert=myserver-dev.crt --cert-key=myserver-dev.key …` did not work, with or without key. ([doc](https://github.com/jakubroztocil/httpie#client-side-ssl-certificate))

Passing the certificate to the `--verify` option didn’t actually work for me.

**Comment by berkerpeksag** [comment]
I've created my certificate with the following command:

```sh
$ openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
```

Then I passed `certificate.pem` to the `--verify` option. You may want to fill every field when creating your certificate (especially the "Common Name" field)

**Comment by bhushanbrb** [comment]
> Hi ,
> In which file of Gunicorn Server, have to add SSL configuration details.
> Please ...
> THanks
As he mentioned above in your gunicorn config file add following entry 
keyfile = myserver-dev.key                                                                           
certfile = myserver-dev.crt
