### ISSUE TITLE
Django+gunicorn in production:Job fail to start

### ISSUE THREAD

**Issue by helloSky30** [benoitc/gunicorn#1586]
here is my work files:
```
/home/hstk/
    sites/
        myservername/
            env/
            hstk/
```
the `hstk` is my project
and the `/etc/init/gunicorn.conf`
```
start on runlevel [2345]
stop on runlevel [!2345]

respawn
setuid hstk
setgid hstk
chdir /home/hstk/sites/myservername/hstk

exec /home/hstk/sites/hstk.club/hstk/env/bin/gunicorn --bind unix:/tmp/myservername.socket blogproject.wsgi:application
```
then I run `sudo service gunicorn start`,  error is come.

But, when i run `gunicorn --bind unix:/tmp/myservername.socket blogproject.wsgi:application`,its ok.
Please help me!

**Comment by benoitc** [comment]
what's the error?

**Comment by helloSky30** [comment]
when I run `sudo service gunicorn start`,
**error**:`start:Job fail to start`

**Comment by benoitc** [comment]
yeah but what logs return gunicorn? they should be displayed in the systemd
log console.

**Comment by helloSky30** [comment]
the system console display just this 
```
(env) hstk@localhost:~/sites/hstk.club/hstk$ sudo start gunicorn-hstk
start: Job failed to start
```
And i even don't have the file `/var/log/upstart/hstk.log`
Below is the error info in `/var/log/nginx/error.log`
```
2017/09/07 22:52:08 [crit] 479#0: *16 connect() to unix:/tmp/hstk.club.socket failed (2: No such file or directory) while connecting to upstream, client: 69.171.72.74, server: hstk.club, request: "GET / HTTP/1.1", upstream: "http://unix:/tmp/hstk.club.socket:/", host: "hstk.club"
2017/09/07 22:52:08 [crit] 479#0: *16 connect() to unix:/tmp/hstk.club.socket failed (2: No such file or directory) while connecting to upstream, client: 69.171.72.74, server: hstk.club, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/tmp/hstk.club.socket:/favicon.ico", host: "hstk.club", referrer: "http://hstk.club/"
```

**Comment by helloSky30** [comment]
I solve it by replace `/home/hstk/sites/hstk.club/hstk/env/bin/gunicorn` in `gunicorn.conf` to `/usr/local/bin/gunicorn`.
But i'm sure that gunicorn also exists in the `.../env/bin/`, i don't know why.

**Comment by benoitc** [comment]
you have some log given by that systemd that can give more info:

https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

if using virtualenv also have a look here:
http://docs.gunicorn.org/en/stable/deploy.html#using-virtualenv

**Comment by helloSky30** [comment]
Thanks

**Comment by funkyfuture** [comment]
can this issue be closed?

**Comment by tilgovi** [comment]
Seems like it. I'll close it. Please open a new issue for any further problems.

**Comment by npneeraj** [comment]
> I solve it by replace `/home/hstk/sites/hstk.club/hstk/env/bin/gunicorn` in `gunicorn.conf` to `/usr/local/bin/gunicorn`.
> But i'm sure that gunicorn also exists in the `.../env/bin/`, i don't know why.

can you please tell the path of Gunicorn.conf file? I have googled it but couldn't find it. Thank U in advance
