### ISSUE TITLE
ImportError: No module named 'gunicorn'

### ISSUE THREAD

**Issue by cjchengtw** [benoitc/gunicorn#1588]
I use gunicorn +supervisor to deploy django project in ubuntu server.

weather.conf
```
[group:weather_station]
programs=site

[program:site]
directory=/home/nhcc/campus-weather-station/weather_station
command=/home/nhcc/.local/bin/gunicorn -c /home/nhcc/campus-weather-station/weather_station/gunicorn.conf.py -p gunicorn.pod weather_station.wsgi
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor.log
```

When I execute `/home/nhcc/.local/bin/gunicorn -c /home/nhcc/campus-weather-station/weather_station/gunicorn.conf.py -p gunicorn.pod weather_station.wsgi`

It can work

But when I use this command with `sudo supervisorctl reload` 

Then the error message in the status

File "/home/nhcc/.local/bin/gunicorn", line 7, in <module>
    from gunicorn.app.wsgiapp import run
ImportError: No module named 'gunicorn'

**Comment by tilgovi** [comment]
How was Gunicorn installed? It is in `~/.local/bin/gunicorn` for the `nhcc` user. Is supervisor running this as root or as `nhcc`? It seems like the Python path might not be set correctly.

**Comment by cj10243** [comment]
I used pip to install the gunicorn .I use nhcc account to run `sudo supervisorctl reload` and `sudo /home/nhcc/.local/bin/gunicorn -c /home/nhcc/campus-weather-station/weather_station/gunicorn.conf.py -p gunicorn.pod weather_station.wsgi`

**Comment by tilgovi** [comment]
The error message you posted shows "/home/user/.local/bin/gunicorn", where the home directory is for "user" not "nhcc". I still suspect Python path issues. If you control the whole system you might want to `sudo pip install gunicorn` to get it systemwide and then just invoke it as `/usr/local/bin/gunicorn` (or wherever pip installs it). If you'd rather not do that, you might need to tell supervisor to run the task as the "nhcc" user and make sure you're installing gunicorn as that user.

**Comment by cj10243** [comment]
The  real path is `home/nhcc/.local/bin/gunicorn` and I have edited.I'm sorry  to mislead your estimation.
However, I used `whereis gunicorn`. It is located at /home/nhcc/.local/bin/gunicorn.And this configure was ever successed .But it suddenly broke in one day.Is there any possible reason?

**Comment by benoitc** [comment]
@cjchengtw did you fixed it?

**Comment by cjchengtw** [comment]
I changed into the new system, and the above cammand can worked now.

**Comment by benoitc** [comment]
thanks for the feedback.
