### ISSUE TITLE
choose worker depending on work 

### ISSUE THREAD

**Issue by jeremy-rutman** [benoitc/gunicorn#1605]
I have some work that needs to go to a particular worker depending on some incoming  params (the worker maintains history and the new result depends critically upon that) .  Is there a way to select what worker will be called (depending on said params)

**Comment by tilgovi** [comment]
There is no way to specify any kind of stickiness like this other than to utilize HTTP Keep-alive to send multiple requests over the same connection. Each new connection gets assigned to the first worker to accept it.

**Comment by tilgovi** [comment]
Depending on what you're doing, the typical approach would be to maintain some state on the server in a shared backend—such as a database—or to maintain the state on the client and send it with the request—such as happens with a cookie.

**Comment by BRIDGE-AI** [comment]
I need this feature and related extending methods.
It would be awesome if you support this. @tilgovi

**Comment by tilgovi** [comment]
Thanks for the feedback. Unfortunately, this would be a fundamental change to the way Gunicorn works.
