### ISSUE TITLE
Cannot connect to http://lists.gunicorn.org/user/

### ISSUE THREAD

**Issue by dsuch** [benoitc/gunicorn#1611]
Hello,

that may be related to #1474 but this is just to let you know that http://docs.gunicorn.org/en/stable/ points to http://lists.gunicorn.org/user/ which seems not to exist.

Regards.

**Comment by berkerpeksag** [comment]
> that may be related to #1474 but

It definitely is related to #1474. We decided to use GitHub issue tracker for usage questions. Would you like to send a PR to fix the broken link? The index page is located at https://github.com/benoitc/gunicorn/blob/master/docs/source/index.rst
