### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by yakman2020** [benoitc/gunicorn#1614]
gunicorn is used by dc/os which we are getting to work on windows. It looks like the changes required to get it to work in that environment would be pretty straightforward. Have you been thinking along those lines already? If not, would you be open to a PR to make that happen?

**Comment by tilgovi** [comment]
Please see #524.

**Comment by tilgovi** [comment]
I would definitely be open to any PRs that help get us to Windows support, but please check in with that issue and post there so we can coordinate steps.

**Comment by yakman2020** [comment]
Perfect!
