### ISSUE TITLE
Disable insane noise in logging

### ISSUE THREAD

**Issue by chppppp** [benoitc/gunicorn#1619]
I run gunicorn like this:

`gunicorn -w 4 -b 127.0.0.2 app:app --access-logfile /var/log/access.log --error-logfile /var/log/error.log --log-level warning`

my log is spammed every second with:

```
127.0.0.2 - - [10/Oct/2017:10:07:05 -0500] "HEAD / HTTP/1.1" 200 - "-" "-"
127.0.0.2 - - [10/Oct/2017:10:07:07 -0500] "HEAD / HTTP/1.1" 200 - "-" "-"
127.0.0.2 - - [10/Oct/2017:10:07:09 -0500] "HEAD / HTTP/1.1" 200 - "-" "-"
127.0.0.2 - - [10/Oct/2017:10:07:11 -0500] "HEAD / HTTP/1.1" 200 - "-" "-"

```

is there any way to disable this noise?

**Comment by tilgovi** [comment]
These look like legitimate requests being logged by Gunicorn. What behavior would you rather see?

**Comment by chppppp** [comment]
Thanks for your reply tilgovi. 

these logs occur when the site is not being accessed. I am wondering why gunicorn would show me log entries once a second if the site is not being accessed. 

Thanks

**Comment by tilgovi** [comment]
Unfortunately, I think the answer is most likely that the site is being accessed :-D.

**Comment by tilgovi** [comment]
Perhaps you have a load balancer that is performing a simple health check?

**Comment by tilgovi** [comment]
If not, maybe you can post a repo somewhere that reproduces the problem.

**Comment by chppppp** [comment]
I am an idiot. I am running HAPROXY in front of gunicorn. 

Thanks tilgovi.

**Comment by tilgovi** [comment]
No worries. Glad you figured it out.
