### ISSUE TITLE
https connection was not closed immediately after wsgi return

### ISSUE THREAD

**Issue by winglq** [benoitc/gunicorn#1620]
I have a wsgi app base on falcon.
The app was used to as a file upload server. 
I use four threads to upload files. On the server side if the connection count is more than 2, it will raise an exception. This should lead to two of the connections closed immediately. But in my situation these two connections' closure will delay to the time when the other two connections are about to close.
As the following log, two connection reached max connection count at about **17:57:34.316**,
but they were closed at about **17:58:08**. I checked that at **17:57:34.316** the wsgi have given the controll to gunicorn for these two connections.
The 4 connections are all from the same host.
```
2017-10-11 **17:57:34.316** 8977 INFO [-] Max connection count 2 reached.
2017-10-11 **17:57:35.506** 8977 INFO [-] Max connection count 2 reached.
[2017-10-11 17:58:07 +0000] [8977] [DEBUG] Closing connection.
[2017-10-11 17:58:08 +0000] [8977] [DEBUG] Closing connection.
[2017-10-11 17:58:10 +0000] [8977] [DEBUG] Closing connection.
[2017-10-11 17:58:10 +0000] [8977] [DEBUG] Closing connection.
```
Any idea why gunicorn does not close the connection immediately?

**Comment by tilgovi** [comment]
Can you provide your gunicorn settings? I am most interested in the worker type and keepalive setting.

**Comment by winglq** [comment]
@tilgovi , the configuration.
BTW, I have also tested sync greenevent worker, but got the same result. 
I'll do some debug  today, if anything useful I'll update here.
 ```
  6 [server:main]
  5 use = egg:gunicorn#main
  4 host = 0.0.0.0
  3 port = 4000
  2 workers = 1
  1 worker-class = gthread
13  threads = 20
  1 timeout = 3600
  2 backlog = 2048
  3 keepalive = 2
  4 proc_name = myapp
  5 loglevel = DEBUG
  6 keyfile = /path/to/domain.key
  7 certfile = /path/to/domain.crt
```

**Comment by winglq** [comment]
It is due to after the falcon app raise out the exception, gunicorn will reuse the connection and put it to the worker. When the worker tries to get the request iterator, it will first discard the previous content. I am uploading a file, so gunicorn will raise a StopIteration exception until all content been discarded.
It seems it's impossible to terminate a connection immediately on the wsgi app side, right? Any idea on this? Is there a way to configure gunicorn without reuse connections? @tilgovi 

```
parser.py
 17     def __next__(self):$
 16         # Stop if HTTP dictates a stop.$
 15         if self.mesg and self.mesg.should_close():$
 14             raise StopIteration()$
 13 $
 12         # Discard any unread body of the previous message$
 10         if self.mesg:$
  9             data = self.mesg.body.read(8192)$
  8             while data:$
  7                 data = self.mesg.body.read(8192)$
  6 $
  5         # Parse the next request$
  4         self.req_count += 1$
  2         self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)$
  1         if not self.mesg:$
45              raise StopIteration()$
```

**Comment by benoitc** [comment]
If an header "Connection: close" is found in the response, the connection should stop. Can you try it?

**Comment by winglq** [comment]
Yes, the connection stops with the header. Thanks.

**Comment by benoitc** [comment]
closing the issue.
