### ISSUE TITLE
latest gunicorn doesn't support umask '0' 

### ISSUE THREAD

**Issue by ricardokirkner** [benoitc/gunicorn#1622]
When running gunicorn 19.7.1 and passing

--umask=0

I get the following error

gunicorn: error: argument -m/--umask: invalid auto_int value: '0'

**Comment by tilgovi** [comment]
I think this is a bug in our parsing. As a workaround, you should be able to specify the value zero as an octal (`0o0`) or hex (`0x0`) literal.
