### ISSUE TITLE
no systemd service file description leads to unhelpful boot messages

### ISSUE THREAD

**Issue by kalbfled** [benoitc/gunicorn#1627]
Using the stock Gunicorn package in the repo for Debian Jesse:

`xxx:~$ systemctl cat gunicorn`
`# /run/systemd/generator.late/gunicorn.service`
`# Automatically generated by systemd-sysv-generator`

`[Unit]`
`SourcePath=/etc/init.d/gunicorn`
`Description=(null)`
`...`

The missing "Description" yields lines like this in our bootlog:

`[  OK  ] Started Prescriptive Topology Manager (PTM) Daemon..`
`         ...`
`         Starting (null)...`
`         ...`
`...`
`[  OK  ] Started (null).`

**Comment by tilgovi** [comment]
I'm not sure where that comes from. Did this unit file get installed automatically by debian's Gunicorn package or did you create it somehow? You may want to check in at https://github.com/lamby/pkg-gunicorn if it's a problem with the debian packages.

**Comment by kalbfled** [comment]
The service file is part of the Debian package.  I will take a look at the link.  Thanks.
