### ISSUE TITLE
How to use a custom Arbiter

### ISSUE THREAD

**Issue by mindojo-victor** [benoitc/gunicorn#1641]
I want to override `gunicorn.arbiter.Arbiter#spawn_worker` in order to wait a little bit after a worker was forker in order to give it time to fill our app cache.

What's the best way to tell Gunicorn to use my own Arbiter subclass?

**Comment by tilgovi** [comment]
You could override the #run method of the Application instance. See the documentation on using a custom application: http://docs.gunicorn.org/en/latest/custom.html

You'll have to look at the implementations in gunicorn/app/base.py and roll the `BaseApplication` and `Application` class run methods into a single one that works for you.

There is no documented / supported way to just override the arbiter.

**Comment by mindojo-victor** [comment]
Is it a terrible idea to monkey patch the `spawn` method?

**Comment by tilgovi** [comment]
Not sure :) It hasn't really changed signature or basic function for a long long time, but anything could happen!

**Comment by tilgovi** [comment]
This is not the first time someone has wanted a way to warm a worker, though. Eventually, we may need to do something about this that is more general.

**Comment by mindojo-victor** [comment]
This would be great!

**Comment by mindojo-victor** [comment]
>This is not the first time someone has wanted a way to warm a worker, though. Eventually, we may need to do something about this that is more general.

How can I contribute to make this happen? I think the implementation can be quite simple to understand and implement:

Add a config option to enable starting the next worker only when the current worker was fully imported and/or somehow notified the master about this. Maybe via a file.

**Comment by mindojo-victor** [comment]
Also, related, it's really strange to me that `pre_fork` hook is called in the master process while `post_fork` in the forked worker:
```python
    def spawn_worker(self):
        ....
        self.cfg.pre_fork(self, worker)
        pid = os.fork()
        if pid != 0:
            worker.pid = pid
            self.WORKERS[pid] = worker
            return pid

        # Process Child
        worker.pid = os.getpid()
        try:
            util._setproctitle("worker [%s]" % self.proc_name)
            self.log.info("Booting worker with pid: %s", worker.pid)
            self.cfg.post_fork(self, worker)
            worker.init_process()
            sys.exit(0)
        ...
```
Otherwise I could use the `post_fork` hook to wait until the forked worker finishes warming up. I guess it's an error which was not noticed and fixed because no one used this hook before. `worker.init_process()` is called right after `post_fork` is called, so most of the users, I guess, were using `init_process` hook.

**Comment by mindojo-victor** [comment]
Looking https://docs.newrelic.com/docs/agents/python-agent/web-frameworks-servers/python-agent-gunicorn-wsgi-web-server :

> If using preloading, you should then aim to restrict it to only being used to preload code and not triggering actual code execution to perform tasks. Any such processing when the WSGI script file or module is loaded should be deferred to worker processes by using Gunicorn's `post_fork` hook.

Looks like this was a deliberate choice and this can't be changed without breaking the client code. But adding `post_fork` hook for master process is not an option?

**Comment by benoitc** [comment]
issue has been closed, better to reopen a new one?  I'm not sure why you need it . What do you need to fill in the cache , why couln't it be done inside the worker, ie having a way for the cache instead of waiting randomly?

**Comment by mindojo-victor** [comment]
My app inside a worker needs a big cache to be loaded into RAM. Be default a Gunicorn arbiter forks all workers at the same time. This creates a load on the CPU and the db. I already implemented a way to make my workers and arbiter to work together around this. My newly forked worker notifies the arbiter when it finished filling up the cache. Only then the arbiter starts the next worker.

As @tilgovi said:

> This is not the first time someone has wanted a way to warm a worker, though. Eventually, we may need to do something about this that is more general.

So I thought it would be nice to have this functionality upstream, especially as it's not difficult to implement.

What do you think?

**Comment by benoitc** [comment]
First that's not totally true, workers are not sent at the same time, there is a random time between each spawn:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L617

We could of course make it configurable but i'm not sure I like it, it is introcing an extra complexity in handling workers exit. For example what would happen if the worker crash in between, in such case you don't want to do anything. I would rather wait before launching the first request . Anyway can you open a new issue describing the feature you want and what you expect from it that would be better to start discussiong of it before any discussing the implementation.

**Comment by mindojo-victor** [comment]
> there is a random time between each spawn

In my case it can take the worker > 10 seconds to fill the cache, so essentially it's "at the same time".

Ok, I'll create another issue.

**Comment by benoitc** [comment]
Thanks!

**Comment by mindojo-victor** [comment]
What about `post_fork` hook being called in the worker and not having a similar hook for the master process?
