### ISSUE TITLE
Graceful reload of workers one by one

### ISSUE THREAD

**Issue by mindojo-victor** [benoitc/gunicorn#1642]
I have 4 workers set up. If I send HUP message to the master process, it starts 4 new workers, then shut's down the 4 old.

For me it's an issue, because I have limit memory on my server.

Is there a problem I don't see to do this for each worker separately: start one new worker, kill one old, etc.?

**Comment by tilgovi** [comment]
You can use `SIGTTIN` and `SIGTTOU` to increase and decrease the number of workers directly or send `SIGTERM` to a gracefully shut down a worker directly and the arbiter will spawn a replacement.
