### ISSUE TITLE
Make "failed to find application" a bit more informative

### ISSUE THREAD

**Issue by JJ** [benoitc/gunicorn#1647]
When issuing `gunicorn myapp:app` and obtaining result `failed to find application myapp`, it would be better if it was clear whether there was a problem with `myapp` or with `app`.

**Comment by berkerpeksag** [comment]
Thank you for the suggestion. +1 from me. I'd suggest slightly different wording, though:

```py
'Failed to find application object %r in %r'
```

**Comment by JJ** [comment]
Sure!

**Comment by berkerpeksag** [comment]
@benoitc, @tilgovi: PR #1648 looks good to me. What do you think?

**Comment by tilgovi** [comment]
Good for me.
