### ISSUE TITLE
--capture-output does not capture stdout

### ISSUE THREAD

**Issue by DrorBenEliezer** [benoitc/gunicorn#1649]
using the following command:
gunicorn server:app -b 0.0.0.0:8002 --access-logfile /var/log/gunicorn.access --error-logfile /var/log/gunirn.error --log-level debug --capture-output

the error log does not capture this line:
sys.stdout.write('write stdout\n')
or
print 'printing'

it does capture this line:
sys.stderr.write('write stderr\n')

**Comment by tilgovi** [comment]
Is it possible that one of these is buffered and the other is not? If you add `sys.stdout.flush()`, does it fix the issue?

**Comment by DrorBenEliezer** [comment]
Yes, 
sys.stdout.flush() works fine. 
Thanks !
