### ISSUE TITLE
Gunicorn's preload option affects application thread in Docker

### ISSUE THREAD

**Issue by ddavtian** [benoitc/gunicorn#1666]
Perhaps I am making a silly mistake here but I noticed that if I use the `--preload` option the thread which normally runs fine on a regular development machine, OS X in my case doesn't fire repeatedly in Docker.

**This is how I start gunicorn:**

`gunicorn --bind 0.0.0.0:8000 --workers 4 -k gevent --preload -u asruser --timeout 120 --access-logfile - --log-level info octo.wsgi`

On Mac OS X, the thread runs every `5` seconds, but not within a Docker container.

**On Mac OS X**

```
2017-12-15 09:30:54,592 wsgi            line: 7    INFO     Running through WSGI in Gunicorn
report
report
report
```

**Same execution in Docker container**

```
2017-12-15 17:38:12,059 wsgi            line: 7    INFO     Running through WSGI in Gunicorn
< THEAD doesn't run >
```

**The class I am using is the following:**

```
class Reporter:

    def __init__(self, registry=None, reporting_interval=5, clock=None):
        self._loop_thread = Thread(target=self._loop, name="octo console_reporter {0}".format(get_qualname(type(self))))
        self._loop_thread.setDaemon(True)
        self.registry = registry or global_registry()
        self.reporting_interval = reporting_interval
        self.clock = clock or time
        self._stopped = Event()

    def start(self):
        print("started")
        if self._stopped.is_set():
            return False

        r = str(self._loop_thread)
        if "stopped" in r:
            self.create_thread()
        elif "started" in r:
            return False

        self._loop_thread.start()
        print("true")
        return True

    def stop(self):
        self._stopped.set()

    def _loop(self):
        print("looop")
        while not self._stopped.is_set():
            try:
                print("report")
                self.report_now(self.registry)
            except Exception as e:
                Logger.log.error(str(e))
            time.sleep(self.reporting_interval)

    def report_now(self, registry=None, timestamp=None):
        raise NotImplementedError(self.report_now)
```

This is how it's instantiated and started:

```
Logger.log.info("Starting metrics reporter")
reporter = EventHubReporter(reporting_interval=5,
        prefix=EnvironmentConfig.METRICS_PREFIX,
        event_hub_name=EnvironmentConfig.EVENT_HUB_NAME,
        application_name=EnvironmentConfig.APPLICATION_NAME,
        service_namespace=EnvironmentConfig.EVENT_HUB_SERVICE_NAMESPACE,
        shared_access_key_name=EnvironmentConfig.EVENT_HUB_SHARED_ACCESS_KEY_NAME,
        shared_access_key_value=EnvironmentConfig.EVENT_HUB_SHARED_ACCESS_KEY_VALUE,
        tags={}, ims_org_id=EnvironmentConfig.IMS_ORG_ID)
reporter.start()
```

**Comment by tilgovi** [comment]
You may want to read the last few comments on #1045. Mixing threads with process forking is not advised and gunicorn creates workers by forking.

**Comment by jamadden** [comment]
An additional subtlety is that greenlets *do* continue running after a fork. So if the process has been gevent monkey-patched such that `Thread` is really creating a greenlet, the OS X behaviour makes sense. Perhaps there's a difference in when the monkey patching is happening in these two environments?

**Comment by ddavtian** [comment]
thank you @tilgovi @jamadden, I have removed the `--preload` option and things are well. The only reason I was using the `--preload` option was due to me not getting my application issue reported properly. For example if anything was an issue in application code I would see Gunicorn's worker dying and me not being able to decipher what the issue truly was within the application layer. Using the `--preload` helped me with that visibility.

**Comment by tilgovi** [comment]
Could you refactor your application to set up some try/catch around your own initialization code?

**Comment by ddavtian** [comment]
I can, what would try/catch on the app init buy me?

**Comment by tilgovi** [comment]
I assumed that when you said you were not getting application issues reported properly without `--preload` that it was because the worker died without any traceback but that you got one in the master process using `preload`.

**Comment by ddavtian** [comment]
@tilgovi thanks
