### ISSUE TITLE
Primary documented gaiohttp config results in timeout exceptions.

### ISSUE THREAD

**Issue by bedge** [benoitc/gunicorn#1677]
IMO this is a common use case, ie: python 3.x, gunicorn, aiohttp and flask. 
Yet the documented option results in multiple exceptions.

http://docs.gunicorn.org/en/latest/design.html#asyncio-workers, option 1 states:
```
1. Install aiohttp version 1.3.5 instead of version 2:
$ pip install aiohttp==1.3.5
```
However, doing so results in this exception:
```
Jan  8 19:52:33 ip-10-16-153-89 [15156]: asyncio(default_exception_handler:1148) - ERROR: Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:225> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 254, in start
    message = yield from httpstream.read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 807, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 315, in start
    yield from self.handle_error(504, message)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 382, in handle_error
    self.log_access(message, None, response, self._loop.time() - now)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/_gaiohttp.py", line 24, in log_access
    self.logger.access(response, request, environ, datetime.timedelta(0, 0, time))
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/glogging.py", line 324, in access
    request_time))
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/glogging.py", line 267, in atoms
    'h': environ.get('REMOTE_ADDR', '-'),
AttributeError: 'NoneType' object has no attribute 'get'
```

This is a known bug in the aiohttp project:
https://github.com/aio-libs/aiohttp/issues/1687

which refers to the gunicorn bug:
https://github.com/benoitc/gunicorn/pull/1418

Which points to an example, https://github.com/benoitc/gunicorn/pull/1569/files#diff-1f6b29fd82cc0dd73e235049e03f00d0, that's not simple to add to all flask variants (flask-restplus in my case)

Could this `Note` be expanded to include the current implementation suggestion rather than rely on multiple other bug reports as an implied solution?

**Comment by benoitc** [comment]
what truggered this trace? can you describe the way you were using it? 

Nevertherless native support of async features in python 3 is coming this month.

**Comment by bedge** [comment]
It's a systemd managed service that runs
`
/usr/bin/python3 /usr/local/bin/gunicorn --bind unix:/var/tmp/nn-api-egress.sock -m 007 -t 400 --workers=16 --preload --worker-class gaiohttp --log-level=DEBUG app
`
flask-restplus==0.10.0
gunicorn==19.7.1
aiohttp==1.3.5

The 'app' is just:
```
from flask import Flask, jsonify
from apis import api

application = Flask(__name__)
api.init_app(application)
application.logger.setLevel(logging.DEBUG)

if __name__ == '__main__':
    application.run(debug=False)
```

Are there any docs/posts describing the upcoming python 3 async support?

thanks.

**Comment by tilgovi** [comment]
I don't see any `async` use in that example. To use flask with the aiohttp worker I think you may need to use some other library, like Flask-aiohttp: http://flask-aiohttp.readthedocs.io/en/latest/coroutine.html

**Comment by tilgovi** [comment]
I do not know if that's the issue. I honestly have not tried to use aiohttp myself.

**Comment by benoitc** [comment]
@bedge i'm focusing on some features right now to make a new release, but will take the time to draft a plan .

**Comment by bedge** [comment]
@tilgovi Does this not indicate async use?
```
Jan  8 23:06:45 ip-10-16-153-124 [10843] gunicorn.error(info:247) - INFO: Starting gunicorn 19.7.1
Jan  8 23:06:45 ip-10-16-153-124 [10843] gunicorn.error(info:247) - INFO: Listening at: unix:/var/tmp/nn-api-egress.sock (10843)
Jan  8 23:06:45 ip-10-16-153-124 [10843] gunicorn.error(info:247) - INFO: Using worker: gaiohttp
Jan  8 23:06:45 ip-10-16-153-124 [10998] gunicorn.error(info:247) - INFO: Booting worker with pid: 10998
Jan  8 23:06:45 ip-10-16-153-124 [10998] asyncio(__init__:53) - DEBUG: Using selector: EpollSelector
Jan  8 23:06:45 ip-10-16-153-124 [10998] asyncio(__init__:53) - DEBUG: Using selector: EpollSelector
```
Apologies for the noob questions. I am pretty new at python web service architecture.

I believe I'm replicating what is stated in the docs option 1 for asyncio use here: http://docs.gunicorn.org/en/latest/design.html#asyncio-workers

**Comment by tilgovi** [comment]
No apologies necessary! I'm learning right along with you.

I think you need to use `aiohttp_wsgi` to wrap your application as in this example: https://github.com/benoitc/gunicorn/blob/master/examples/frameworks/flaskapp_aiohttp_wsgi.py

I think without that, your handler runs on the main thread and not on an asyncio thread pool, which might prevent the worker from being truly async.

I am also not 100% sure that example is right. From what I remember of flask it should maybe look like:

```python
from aiohttp import web
from aiohttp_wsgi import WSGIHandler
from flask import Flask

app = Flask(__name__)
app.wsgi = WSGIHandler(app.wsgi)
```

**Comment by bedge** [comment]
Is the --worker-class <class> command line arg required if one uses @tilgovi's example of setting app.wgsi as above?
Or, are they different ways of doing the same thing?

it seems redundant to have to specify the worker-class in both the command line and in the app instance directly.

I had assumed that using the '--worker-class aiohttp.worker.GunicornWebWorker' would cause gunicorn to do the app.wgsi replacement with the `aiohttp` worker as documented.

**Comment by tilgovi** [comment]
The `aiohttp` worker expects your application to be an instance of `aiohttp.web.Application`. The `aiohttp.web.Application` expects to have route handlers that are coroutines (async functions). Flask applications (and WSGI apps, generally) are not coroutines. `aiohttp_wsgi` is used to wrap the Flask app in a coroutine. The coroutine buffers the request body (asynchronously), calls the Flask app once the body is read (synchronously), and streams the response of the Flask app (asynchronously).

Having now read more of the code of `aiohttp` and `aiohttp_wsgi` for a better understanding, I think that the example we have is correct: https://github.com/benoitc/gunicorn/blob/master/examples/frameworks/flaskapp_aiohttp_wsgi.py

**Comment by benoitc** [comment]
closing issue as answered
