### ISSUE TITLE
Buffering

### ISSUE THREAD

**Issue by tarnenaky** [benoitc/gunicorn#1686]
Does gunicorn have ability to buffer connections?

For example I have 5 workers and I want that gunicorn keeps max 10 connections simultaneously (5 in processing and 5 in buffer) and other connections will be rejected immediately.

**Comment by tilgovi** [comment]
The operating system can do this. Specify the `--backlog` setting.

**Comment by tarnenaky** [comment]
@tilgovi thank you for help
