### ISSUE TITLE
Can I call gunicorn from a py file?

### ISSUE THREAD

**Issue by 1067511899** [benoitc/gunicorn#1689]
I mean something like:

from gunicorn.app.wsgiapp import WSGIApplication
WSGIApplication().run('test:app')

when I do this,the console print someting like: error:No application module specified.

thanks.

**Comment by benoitc** [comment]
If you want to embed Gunicorn in you application this can be done by using a custom application object:
http://docs.gunicorn.org/en/stable/custom.html
