### ISSUE TITLE
Using two types of workers

### ISSUE THREAD

**Issue by ryanermita** [benoitc/gunicorn#1691]
Gunicorn have different types of workers, and we use async and sync workers in one gunicorn_config file. The question is which workers the gunicorn would use in this case? or gunicorn will use both of them and gunicorn will take care of the distribution of request to sync and async? 

sample gunicorn_config
```
bind = "0.0.0.0:9000"
workers = 3
worker_class = "gevent"
threads = 10
worker_connections = 2000
```

**Comment by tilgovi** [comment]
The threads setting is not compatible with the gevent worker. Threads implies `worker_class = "gthread"`. I can't remember off the top of my head which one takes precedence. Gunicorn will tell you at startup.

If you want to use both you should run Gunicorn twice and route appropriately.

**Comment by ryanermita** [comment]
oh I see. So `"gthreads"` are for `"AsyncIO Workers"`.

Is it okay to use two or even more types of workers? Or not because it would take a lot of resources?

**Comment by tilgovi** [comment]
Threads is for threaded worker.

You can run as many copies of gunicorn as you like. You will have to measure your own resource consumption.

**Comment by tilgovi** [comment]
The documentation is a little bit unclear. There is discussion about improving it in #1045. Reading that issue might help you.

**Comment by ryanermita** [comment]
after reading #1045 
**Important points:**
> threaded worker refers to gthread workers

> The gthread is neither a sync nor an async worker. It's a worker that handle different strategy to play around the GIL to handle the concurrency .

use --preload option so the app will load once instead of loading it per workers.

**This is how I understood how theaded worker works.**
to make use of threaded workers we need to use `-k gthread` option to select `gthread` as worker_class:
`gunicorn -w 4 --threads 2 -k gthread -b 0.0.0.0:5000 app:app`
or will this also work as the command above? 
`gunicorn -w 4 --threads 2 -b 0.0.0.0:5000 app:app`

^ this will  make 4 threaded workers with 2 threads each, which can handle 8 concurrent request?

*for clarification:* is it the same concept with async and other type of workers?
`gunicorn -w 4 -k gevent -b 0.0.0.0:5000 app:app`
which will spawn 4 asycn workers?

so our gunicorn_config should be updated like this to use gthread.
```
bind = "0.0.0.0:9000"
workers = 4
worker_class = "gthread"
threads = 2
preload=True
```

**Comment by tilgovi** [comment]
Yes. The `worker_class` is optional if you have `threads`, though. You are correct that with `-w 4 --threads 2` you can have 8 concurrent requests.

With `-w 4 -k gevent` you would have four workers, but each worker could handle many concurrent requests if they are I/O bound.

**Comment by ryanermita** [comment]
yay! awesome! 

Thanks @tilgovi
