### ISSUE TITLE
Gunicorn is idle for unresponding request

### ISSUE THREAD

**Issue by GowthamG11** [benoitc/gunicorn#1693]
Hi,
     In production server,some request cause blocking gunicorn.It is taking high cpu memory and it will idle upto receiving response and not receiving any request.What will be the issue ?

I have WORKERS=3 and TIMEOUT=6000

Regards,
Gowthaman G

**Comment by benoitc** [comment]
without much details about what your application is doing and logs it's hard to say. Most probably one part of your application is blocking the worker notifications. Can you provide more details?

**Comment by benoitc** [comment]
@GowthamG11 bump?

**Comment by benoitc** [comment]
closing issue since no feedback have been given.
