### ISSUE TITLE
Can i share the file in the different work process？

### ISSUE THREAD

**Issue by bywangxp** [benoitc/gunicorn#1694]
before start gunicorn， i read the file in memory， and timeing to change the memory。

**Comment by benoitc** [comment]
Gunicorn workers don’t share any data between them per design. You will need to use another way to share a data, like using a database . You can also obviously play around using a pipe,hooks... but I would advise against it. It would make your app less resilient.

If your file is used for some configuration setting you could also force reload of the workers either from a hook or externally using HUP or killing the user worker.

**Comment by benoitc** [comment]
No feedback since. i guess it has been answered. closing the issue.
