### ISSUE TITLE
Slowloris link is dead in documents 

### ISSUE THREAD

**Issue by Skorkmaz88** [benoitc/gunicorn#1697]
Slowloris link in documents is dead. Github link for the tool is: https://github.com/gkbrk/slowloris

**Comment by berkerpeksag** [comment]
There is no reference to slowloris in Gunicorn docs since 1025c4c55d11db35f98146c3623660096ee76727. You're probably looking at outdated documentation. Could you give us the link you saw the slowloris reference?

**Comment by berkerpeksag** [comment]
Closing this one as 'outdated'. There is no link to the slowloris project in our documentation since Gunicorn 19.4.2.
