### ISSUE TITLE
Workers freeze temporarily?

### ISSUE THREAD

**Issue by Urahara** [benoitc/gunicorn#1700]
So i'm running a [Quart](https://pgjones.gitlab.io/quart/) server, with methods that use [Scrapy](https://scrapy.org/) (for scraping content and then return to client) and [aiohttp](https://aiohttp.readthedocs.io/en/stable/) to perform  actions on site (make login, orders, etc) and [gunicorn](http://gunicorn.org) on top of that to manage workers and stuff.

When i receive a request from server first thing i do is to try perfom a login

I currently using 2 workers:
> gunicorn --worker-class quart.worker.GunicornWorker -w 2 server:app -b 0.0.0.0:8080 -t 600

My problem is: Strangely behavior occurs, in my code i try 5 times to perfom login with 10 seconds of timeout tolerance, but somethings this code is not respected. **I seens like my task is lost and then minutes later i see on log my task trying again make stuff"** even though I have configured these attempts to be second-rate, that lead my request task timeout on worker and don't do anything at all on site. 

I can't figure out what is wrong. But it seens that my task "freeze" on many requests even with workers configured properly.

Mostly part of time my code work 100% but sometimes this behavior occurs. Generally on rush hour, the site that i perfom action is not slow or anything.

Is there any config that i can rely on? Right now i changing my server to run with 8 workers.

**Comment by pgjones** [comment]
I think this is related more to asyncio than Gunicorn/Quart, as discussed in the referenced issue above.

**Comment by tilgovi** [comment]
Thanks! Feel free to re-open if you find any problem with Gunicorn.
