### ISSUE TITLE
Is it possible to serve an application on a path

### ISSUE THREAD

**Issue by sbrunner** [benoitc/gunicorn#1703]
I succeeded to serve an application on the root path like https://example.com/, but is it possible to serve the application on an url with a path like https://example.com/example/?

**Comment by sbrunner** [comment]
If a add a revere proxy who change my path from /example to / The issue I have is that the URL generated by pyramid are wrong because they miss the subfolder...

**Comment by benoitc** [comment]
sounds like a config issue. Either in pyramid or nginx. Would you mind to share

**Comment by sbrunner** [comment]
Actually I use apache as a revers proxy with this configuration:
```
ProxyPass "/example"  "http://localhost:8180/example"
ProxyPassReverse "/example"  "http://localhost:8180/example"
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
ProxyRequests Off
```
And the Pyramid Configuration:
```
[app:app]
use = egg:demo_geoportal
filter-with = proxy-prefix
pyramid.reload_templates = false
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.debug_templates = false
mako.directories = demo_geoportal:templates
    c2cgeoportal_geoportal:templates

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix

[pipeline:main]
pipeline =
    app

# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/logging.html

[loggers]
...
```

**Comment by tilgovi** [comment]
I think you're just missing a `prefix = /example` in the `filter:proxy-prefix` config.

**Comment by sbrunner** [comment]
Excellent, thanks :-)
