### ISSUE TITLE
--limit-request-field_size doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [benoitc/gunicorn#1704]
I have a case where the client sends an Authorization header that is about 11 kilobytes long. This is unacceptable to gunicorn, which is not unreasonable. I tried to up the limit with --limit-request-field_size but no value seems to work, except 0, which opens up a DoS attack. The value gets logged at gunicorn startup correctly, but it doesn't seem to affect behavior. A value of 1000000 seems to still be too small.

I'm using the Debian stretch package gunicorn3, version 19.6.0-10+deb9u1.

**Comment by benoitc** [comment]
closing the issue since wsgi.input_terminated is now supported.
