### ISSUE TITLE
workers unexpectedly time out if system time changes

### ISSUE THREAD

**Issue by flixr** [benoitc/gunicorn#1709]
Worker timeouts currently use the system clock for checking timeouts, delays, etc..
This is not robust as the system time might jump (e.g. due to NTP, PTP or other time updates)

IMHO these timeouts should use the monotonic clock as here we never care about the system time, but just the _real_ elapsed time to check whether we need to kill a worker.

**Comment by tilgovi** [comment]
Looks like `time.monotonic()` is only guaranteed to exist since Python 3.5, but if it's there we should, perhaps, use it for things.

**Comment by flixr** [comment]
It should be available since Python 3.3, but we could (IMHO should) use e.g. https://pypi.python.org/pypi/monotonic to also make this fix available on older Python versions.

Quickly looking through the code it doesn't seem to be too hard except that in https://github.com/benoitc/gunicorn/blob/2b839ca14437c61780d6eaaa8b24ad31e021f2c6/gunicorn/workers/workertmp.py#L50 we would have to actually store the monotonic time in the file (or something like that) instead of using ctime of the file itself.

**Comment by duffsterlp** [comment]
We use gunicorn on an embedded system where the clock ends up jumping ahead due to particular events. When the clock jump occurs, we see this same issue.

**Comment by tilgovi** [comment]
Closed by #1967.
