### ISSUE TITLE
gunicorn on AWS

### ISSUE THREAD

**Issue by mttomas** [benoitc/gunicorn#1710]
I have a fairly large app running on AWS with gunicorn on a 4 vcpu instance, where I was given the workers as 9 and worker threads as 200. When I perform a load test, I am getting only 4 requests/sec. Does it mean that the worker configuration is not read? If I change the instance to a 8 core instance, I get 8 req/sec. Is this behaviour a bug or something?

**Comment by tilgovi** [comment]
Can you share how you invoke gunicorn and set the workers and threads?

**Comment by benoitc** [comment]
@mttomas bump

**Comment by mttomas** [comment]
Sorry for the delayed response. We have set the configuration in the gunicorn configuration, the value for the worker, worker class and threads are mentioned. NGINX acts as a reverse proxy in the set up. The invocation is possibly handled by NGINX. I am interested to know if the spinning of threads is dependant on the number of processors.

**Comment by benoitc** [comment]
well can you paste the config and/or command line you're using to make sure? As [described in the doc](http://docs.gunicorn.org/en/stable/design.html#how-many-threads) there are N threads / number of workers you set

**Comment by benoitc** [comment]
closing the issue, no activeity since awhile.
