### ISSUE TITLE
mailing list for support & new features discussions

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1713]
I am able to setup a new mailing-list for gunicorn and would like to make it the only way to get help and advices on Gunicorn. Any tickets would be then closed in favour of a discussion to it. Thoughts?

**Comment by berkerpeksag** [comment]
+1 from me.

**Comment by tuukkamustonen** [comment]
There are some ancient messages at https://gitter.im/benoitc/gunicorn already - why not resurrect that instead?

Of course, mailing list vs. gitter serve different purpose, but I would say chat is more approachable and way more convenient when it comes to asking for help.

**Comment by benoitc** [comment]
cc @berkerpeksag @tilgovi thoughts? What's your preference?

**Comment by benoitc** [comment]
@tuukkamustonen sorry i missed that message :(

**Comment by berkerpeksag** [comment]
I'd prefer a mailing list (or anything other than GitHub) for support tickets. I think Gitter is also fine, but it's hard to archive or find quality responses for commonly asked questions (so we usually need to repeat the same response manually)

At Python, we've started to experiment with using [Discourse](https://discuss.python.org/). I don't know how hard to set up an instance (IIRC it's a Rails application) though.

**Comment by benoitc** [comment]
setting up a discourse is quite easy. I've done it myself a couple of time. And we can have mail replies too.

**Comment by benoitc** [comment]
It seems rust went to full forum but curious what @tilgovi think about it :)

**Comment by tilgovi** [comment]
I also prefer e-mail to GitHub for support tickets. I sometimes have users find my e-mail and send me mail directly anyway. I would like to be able to reply on a list, and have a searchable archive. Discourse is great forum software, and I'm happy to use that.

**Comment by benoitc** [comment]
@tilgovi it's unclear for me- sorry :) I understand you're OK with discourse but  prefer a mailing list?

**Comment by tilgovi** [comment]
I prefer email, not GitHub issues, for support. Discourse is great, because I can subscribe by email.

**Comment by jamadden** [comment]
FWIW (probably not much! 😄 ), I prefer GitHub issues...which I have subscribed to in email. I'm incredibly unlikely to subscribe to another mailing list.

**Comment by tilgovi** [comment]
I think that's the point for me :-). I would prefer users can have a support community and that GitHub is just for bug reports and development. But maybe that's wishful thinking and we'll still get support requests here no matter what we do.

I am fine to use GitHub for everything if others think it is best.

**Comment by jamadden** [comment]
gevent has a mailing list, and maybe 1/10 of the support requests go there. The vast majority wind up in github. Of course, I haven't particularly done anything to discourage that.

**Comment by benoitc** [comment]
@jamadden @tilgovi Long time ago I setup some [project management rules](https://github.com/benoitc/gunicorn/wiki/Project-management).

But just checked it I failed to update the contributing doc and we never enforced them. I think I'm all for having on github somehow since it doesn't require much to maintain (nothing to install) and the moderation is easy. I proposed to resurrect that and enforce it . To these Boards, it may be interresting to add running sprints/features in progress [like flutter does](https://github.com/flutter/flutter/projects)  

<img width="1399" alt="screenshot 2019-01-24 at 21 42 49" src="https://user-images.githubusercontent.com/14498/51707241-00be6c80-2021-11e9-867e-ccf504f36861.png">

We can also be improved using [templates](https://github.com/flutter/flutter/issues/new/choose):
<img width="1549" alt="screenshot 2019-01-24 at 20 36 28" src="https://user-images.githubusercontent.com/14498/51706599-411ceb00-201f-11e9-86e9-888f482d4b6a.png">

I would also  direct user either to irc or gitter. One advantage of using gitter is to setup the hooks to notify people about news on github. 

If we are all OK I propose the following plan:

- [ ] modify the contributing doc to reflect the project management as described in the wiki 

- [ ] tag issues to have them correctly assigned to projects.

- [ ] update readme with gitter link

- [ ] update website and doc

- [ ] prune old issues or retag/sort issues

Thoughts?

**Comment by tilgovi** [comment]
That sounds good.

**Comment by benoitc** [comment]
closing the issue , i will open a new one asap corresponding.
