### ISSUE TITLE
optimize example

### ISSUE THREAD

**Issue by Huaang** [benoitc/gunicorn#1715]
- target file: `gunicorn/examples/sendfile.py`
- target line: line 17, `f = open(fname, 'rb')`

Hi, I think `with open(fname, 'rb') as f` is strong than `f = open(fname, 'rb')`.

**Comment by tilgovi** [comment]
The file object needs to be kept open. It will be closed by Gunicorn after the data has been read completely and sent. Using `with` will cause the file to be closed before its data is sent.
