### ISSUE TITLE
Must explicitly define `setuptools` as a dependency

### ISSUE THREAD

**Issue by raliste** [benoitc/gunicorn#1716]
When running gunicorn in a hardened Python docker image (with most of the dependencies removed) `setuptools` might be missing.

For instance:

```
Traceback (most recent call last):
  File "/app/manage-docker.binary.runfiles/__main__/server.py", line 1, in <module>
    from gunicorn.app.base import BaseApplication
  File "/app/manage-docker.binary.runfiles/pypi__gunicorn_19_7_1/gunicorn/app/base.py", line 12, in <module>
    from gunicorn import util
  File "/app/manage-docker.binary.runfiles/pypi__gunicorn_19_7_1/gunicorn/util.py", line 12, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

Can be fixed by defining `setuptools` as a direct dependency within the project' `requirements.txt` file, however, it could be fix at the gunicorn codebase level by using `install_requires = ['setuptools']` in setup.py.

**Comment by berkerpeksag** [comment]
@benoitc if I remember correctly, you were against defining dependencies in `install_requires`. Do you still against the idea or can we now use `install_requires` since the Python packaging ecosystem is in a much better shape?

**Comment by jsirois** [comment]
I took a whack at this in #1931 in case folks minds have changed on using `install_requires`.
