### ISSUE TITLE
Use extras_require in setup for optional dependencies

### ISSUE THREAD

**Issue by browniebroke** [benoitc/gunicorn#1717]
Gunicorn [may require extra dependencies](http://docs.gunicorn.org/en/stable/install.html#async-workers) to be installed, but they seem to be optional. It looks like it should be possible to install these using [setuptools's extra](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

It looks like Gevent or Eventlet are 2 options, but the [worker option](http://docs.gunicorn.org/en/stable/run.html#commonly-used-arguments) seems to indicate there are more.

Would it make sense to add this? It has the advantage of documenting indirect dependencies.

**Comment by tilgovi** [comment]
Having extras for each worker type would make sense.

``` shellsession
$ pip install gunicorn[gevent]
```
