### ISSUE TITLE
Pass request start time to access logger

### ISSUE THREAD

**Issue by naechtner** [benoitc/gunicorn#1722]
Since the `request_start` time is saved and used to calculate the `request_duration` in [gunicorn/workers/sync.py:165](https://github.com/benoitc/gunicorn/blob/2b839ca14437c61780d6eaaa8b24ad31e021f2c6/gunicorn/workers/sync.py#L165) and [gunicorn/workers/async.py:90](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/async.py#L90) anyways, would it make sense to pass it to the access log to be able to use request time, duration, and response time for logging purposes?

**Comment by benoitc** [comment]
old issue closing,  the log handler willbe revisted soon
