### ISSUE TITLE
Passing system environment variables

### ISSUE THREAD

**Issue by ChaosCA** [benoitc/gunicorn#1724]
Is there a way for a gunicorn process to be able to read system environment variables? Or is that the default behavior?

Trying to get this to work in a Docker container. My only other option would be `printenv > .env` and passing that file to gunicorn which isn't ideal.

Thanks

**Comment by tilgovi** [comment]
You should be able to set any environment variables you want and read them from your Gunicorn application.

**Comment by ChaosCA** [comment]
Just confused as to why --env flags exist to Gunicorn then? If it reads system environment variables anyways

**Comment by tilgovi** [comment]
I do not know. Perhaps @benoitc can answer as the feature was introduced in 4e3428af0e1cde8574484fc54a5988f35d683142. Maybe there is some use for passing environment variables _only_ to the workers (and not setting it for the master) or maybe it's just for more control in environments where the user might control the command line but not the environment?

**Comment by ChaosCA** [comment]
The wording on the commit is unclear, as it says it allows passing environment variables to gunicorn. But shouldn't that be the expected behavior of system env variables? 

But yea I'll wait for @benoitc Just confused is all! Thanks @tilgovi

**Comment by tilgovi** [comment]
I routinely pass environment variables to my gunicorn apps without `--env`, so I would advise you to do it, too. If Benoit responds with a motivation for `--env` we can update the docs.

**Comment by benoitc** [comment]
Using the env commands would set it on fly for the application and do not force to reset the env after in the scripts. Also it makes it easier to handle some options cross platform.

Do we need to revisit that? I'm ,not sure it worth it

**Comment by tilgovi** [comment]
We can revisit in the future. I think we answered the question, though.
