### ISSUE TITLE
Gunicorn workers for multiple micro services.

### ISSUE THREAD

**Issue by jmgirven** [benoitc/gunicorn#1734]
I am separating my dockerized Python monolith API into multiple small docker API's. The monolith and each of the new Python API's are gunicorn running Flask. I then have an nginx docker container directing traffic to the relevant docker container.

Gunicorn recommends to specify a number of workers to manage your API (normally #_of_CPUs * 2 + 1). When having multiple (10, or even 100) micro services on a single machine, how would you decide how many workers to assign? (#_of_CPUs * 2 + 1) / #_of_services ?

I'm sure it depends on the application and knowing what API's are going to be used most frequently / take the longest to run. With the monolith (not that I ever want to go back), I didn't have to consider this. Gunicorn would just split the workers where they are needed. Do you have any advice on this situation?

**Comment by tilgovi** [comment]
In my own work, I make a decision based on the ratio of cpu to memory used by the service schedule (Amazon ECS) for making placement determinations. You can use the cpu and memory quota features of Docker to get an idea about how much machine you can reasonably expect the service to consume at steady state. That should give you starting point. From there, you can measure, increase workers, increase density of services on a machine, and generally push your performance until it's not helpful (no performance gain, too much time spent in the kernel scheduler) or you start getting out of memory errors. There's no formula.

**Comment by benoitc** [comment]
answered closing issue.
