### ISSUE TITLE
Rogue Threads

### ISSUE THREAD

**Issue by fredpalmer** [benoitc/gunicorn#1740]
I have a question about why I'm seeing more than one thread per worker process.  I am not specifying anything for the `--threads` option.  Also, I appear to only get this when there's a potentially long running request.  Sometimes, it results in a status code of `499` reported to the `nginx` reverse proxy. I _am_ queuing a `celery` task to execute with `apply_async` - could this be the source of the issue?

![1__ubuntu_ip-10-0-3-19_____ssh_](https://user-images.githubusercontent.com/32422/38213862-6a80b6e2-3688-11e8-9743-cde476287f74.png)

I'm using the following:

```
gevent==1.2.2
greenlet==0.4.12
gunicorn==19.7.1
```

**Comment by tilgovi** [comment]
@jamadden is there a thread pool in gevent for managing filesystem I/O or DNS resolution or anything like that?

**Comment by jamadden** [comment]
The default setting of gevent is to use a threadpool for DNS, yes.  http://www.gevent.org/dns.html  There is also a file object that can use the threadpool, but that is not the default on POSIX.

**Comment by fredpalmer** [comment]
I'm closing this issue as it was related to my application code taking a long time to process certain requests.  Optimizing the request and fixing the bottleneck prevented the rogue thread from manifesting.
