### ISSUE TITLE
Exception thrown when '--reload' option finds an AliasModule with `None` as __file__ value

### ISSUE THREAD

**Issue by alanmunguiacerda** [benoitc/gunicorn#1744]
### Problem description
When running gunicorn with the flag `--reload`, the following error is being thrown
![image](https://user-images.githubusercontent.com/12831236/38317574-f5379498-37f2-11e8-8a8c-6cff8a835b66.png)

After some debugging, found out that the problem is raised because an `AliasModule` does have a `__file__` attribute, but its value is `None`
![image](https://user-images.githubusercontent.com/12831236/38317660-2e8a9420-37f3-11e8-92e1-062fffda9357.png)

### Env
Python==3.6.4
Gunicorn==19.7.1

**Comment by tilgovi** [comment]
@alanmunguiacerda did you mean to close the issue?

**Comment by alanmunguiacerda** [comment]
Yeah, sorry, noticed that a fix is already on master, but hasn't been released.
