### ISSUE TITLE
Configuring gtornado Worker for Tornado App Keyword Arguments

### ISSUE THREAD

**Issue by nseidl** [benoitc/gunicorn#1748]
Is it possible to configure the [gunicorn gtornado worker](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/gtornado.py) so configurable/arbitrary keyword arguments can be passed to the server_class(...) constructor?

The Tornado app uses SSL and is run by invoking the following command:
`gunicorn <python_file_name>:app \
--ca-certs=<path/to/>.chain.pem \
--certfile=<path/to/>.cert.pem \
--keyfile=<path/to/>.key.pem \
--bind 0.0.0.0:9002 \
--workers 2 --threads 2 -k tornado \
--timeout 900;`  

When the app is run by simply running <python_file_name>.py (i.e. without gunicorn), the following line starts the app after it is configured:
`app.listen(os.environ.get("PORT", "9002"), max_buffer_size=constants.MAX_MEDIA_SIZE)`

The max_buffer_size keyword argument eventually gets passed to the [TCPServer constructor](http://www.tornadoweb.org/en/stable/_modules/tornado/tcpserver.html#TCPServer).

This is so that files larger than the [default 100MB limit](http://www.tornadoweb.org/en/stable/_modules/tornado/iostream.html#BaseIOStream) can be uploaded via the [stream_request_body](http://www.tornadoweb.org/en/stable/web.html#tornado.web.stream_request_body) decorator. 

However, when the [gunicorn gtornado worker](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/gtornado.py) creates the app via server_class(...), it does not offer the same keyword argument configuration.

Is there an alternative way of configuring gunicorn so that it creates Tornado apps with arbitrary keyword arguments?

**Comment by tilgovi** [comment]
There is no way to do this today, but you can subclass the worker.

If you wish to make a PR that makes an extensibility point for this constrictor by refactoring the tornado worker, I would gladly review it.

**Comment by benoitc** [comment]
is this something we want to support?

**Comment by tilgovi** [comment]
I am commenting to link this to #1049, because it's related. Otherwise, I don't know if we need it open.

**Comment by benoitc** [comment]
stalled
