### ISSUE TITLE
How to notify every worker to execute some method

### ISSUE THREAD

**Issue by loxop** [benoitc/gunicorn#1756]
Hello folks,

My system has multiple workers and threads, and each of them has the same data table in memory(as python data structure) for question answering.
The QA data table has to be updated often, but I don't want to restart the server processes at each data update.
I have a Redis server connected to the server so that I can feed data from the redis by calling a method (by REST request or..)

So I wonder if there is any way to notify every worker to execute a certain method, so that all workers pull data from Redis.

Thanks in advance!

**Comment by tilgovi** [comment]
I'm sorry, but there is no feature for this. This kind of coordination is up to you.

You could try spawning a thread in the `post_fork` hook that sleeps on a redis subscription and updates the table. This is one option, but I'm sure there are others.
