### ISSUE TITLE
Any reason it's been a year without releases?

### ISSUE THREAD

**Issue by elgalu** [benoitc/gunicorn#1761]
Hi, any reason it's been a year without releases?

19.7.1 - @tilgovi tilgovi released this on Mar 21, 2017 · 111 commits to master since this release

**Comment by tilgovi** [comment]
Only that we have been busy.

I stated a week and I half ago that I would prepare a release: https://github.com/benoitc/gunicorn/issues/1634#issuecomment-382045629

I've been going through issues today cleaning out some old things and seeing if anything needs to be resolved before I cut the new release.

Please follow #1634.
