### ISSUE TITLE
Support passing json file to --log-config-dict

### ISSUE THREAD

**Issue by Allu2** [benoitc/gunicorn#1775]
If I'm not mistaken currently `--log-config-dict` expects a dictconfig string as parameter.
I don't think this is intuitive as the other logging config flag `--log-config` accepts a file. 
Also I think any meaningful dictconfig string would be long enough that one would probably rather write code to load the dictconfig to python dict from a file in gunicorn's configuration file then have it typed as parameter to `--log-config-dict`

Perhaps we could have --log-config-dict use something like json.load() even if only as a fallback.

As an illustration here is how starting gunicorn with its default dictconfig would roughly look as parameter to log-config-dict:
`--log-config-dict '{"disable_existing_loggers": false, "version": 1, "handlers": {"console": {"formatter": "generic", "stream": "sys.stdout", "class": "logging.StreamHandler"}, "error_console": {"formatter": "generic", "stream": "sys.stderr", "class": "logging.StreamHandler"}}, "loggers": {"gunicorn.access": {"qualname": "gunicorn.access", "level": "INFO", "handlers": ["console"], "propagate": true}, "root": {"level": "INFO", "handlers": ["console"]}, "gunicorn.error": {"qualname": "gunicorn.error", "level": "INFO", "handlers": ["error_console"], "propagate": true}}, "formatters": {"generic": {"datefmt": "[%Y-%m-%d %H:%M:%S %z]", "format": "%(asctime)s [%(process)d] [%(levelname)s] %(message)s", "class": "logging.Formatter"}}}'`

What I'd want to see is usage similar to:
`--log-config-dict ./logging_debug.json`

I may have missed something obvious though 😕

**Comment by tilgovi** [comment]
You're not missing anything obvious.

You can use this in a configuration file, though:

gunicorn.conf.py
```python
logconfig_dict = json.load(open('logging_debug.json'))
```

**Comment by tilgovi** [comment]
Here's another snippet using `jq` if you want to use the command line:

`gunicorn --log-config-dict "$(jq -c @json logging_debug.json)" myapp`

**Comment by tilgovi** [comment]
None of this is to say we shouldn't have a way to pass a file. I just wanted to give you some workarounds while we figure out what a nice way to do that is.

**Comment by cuongtranx** [comment]
I added a `log-config-json` at #1917 to read config from JSON file, `log-config-dict` still takes precedence
