### ISSUE TITLE
old apt-get install

### ISSUE THREAD

**Issue by oziee** [benoitc/gunicorn#1779]
hello

wondering why the 'sudo apt-get install gunicorn' only installs version 19.6

can we get this updated so that it installs 19.8.1 ?? 19.6 has many socketio errors which have been fixed in newer versions

yes there is Backports.. but this too is only 19.7

Wondering why the apt-get is not keeping up with the latest releases?

thanks

**Comment by berkerpeksag** [comment]
> Wondering why the apt-get is not keeping up with the latest releases?

They follow their own release dates and upgrading a package to a newer version is not always a fully automated process (e.g. removing vendored dependencies from the PyPI version of a package)

Or sometimes they only provide the latest version of a package in their latest release. Unfortunately, we only have control over PyPI. You'll need to report this to Debian or Ubuntu Python maintainers.

**Comment by oziee** [comment]
on a RPi3b+ i did `pip install gunicorn` all things worked and installed 19.8.1

i then tried in a bash script `exec gunicorn -b blah blah` and all i get is 
exec: gunicorn: not found

even without exec it still does not work.. gunicorn not found

an I doing something wrong? or is the apt-get version the only way RPi can use gunicorn?

**Comment by tilgovi** [comment]
@oziee it sounds like `pip install gunicorn` is installing pip somewhere that is not in your PATH.

**Comment by benoitc** [comment]
closing the as it seems to have been answered. Feel free to open a new one if needed.
