### ISSUE TITLE
Can't run --check-config with environment variables

### ISSUE THREAD

**Issue by dmichalowicz** [benoitc/gunicorn#1792]
Hi there, I didn't see any similar issues on this so I've opened a new one. I'm trying to run an app with the `--check-config` flag to verify my config is setup properly, but am having an issue when my config file sets an environment variable because the creation of my app relies on this variable being set. I noticed that when `check_config` is True ([checked here](https://github.com/benoitc/gunicorn/blob/73cc860ead2e926e4d11bcf0cde0037dec8805ef/gunicorn/app/base.py#L198-L200)) then my app proceeds to [get imported](https://github.com/benoitc/gunicorn/blob/73cc860ead2e926e4d11bcf0cde0037dec8805ef/gunicorn/app/wsgiapp.py#L40-L41) before my configs [environment variables have been set](https://github.com/benoitc/gunicorn/blob/73cc860ead2e926e4d11bcf0cde0037dec8805ef/gunicorn/arbiter.py#L114-L117). Is this a flaw in the `check_config` logic? I would think that any configuration my app needs would be set before loading it.

I am running python 2.7.10 on macOS High Sierra 10.13.4. Here is a stripped down version of what my set up looks like:

This is `my_module.py`:
```python
import os
import tornado.web

my_env_var = os.getenv('MY_ENV_VAR')
# Do some setup with my_env_var...

app = tornado.web.Application([
    ...some handlers...
])
app.settings['my_env_var'] = my_env_var
```

This is `my_conf.py`:
```python
workers = 2
worker_class = 'tornado'
raw_env = ['MY_ENV_VAR=foo']
```

Then I run:

```
$ gunicorn --check-config my_module:app -c my_conf.py
```

which results in the call to `os.getenv('MY_ENV_VAR')` above giving `None` because the environment variable does not exist yet. This setup works perfectly fine ordinarily though when running without the `--check-config` flag.

Thanks in advance for any help!

**Comment by benoitc** [comment]
which error did you have?

**Comment by benoitc** [comment]
closing issue since no feedback have been given since awhile.

**Comment by krystiancha** [comment]
I just stumbled upon this issue. To reproduce:

In working directory create `printenv.py` with the following contents.

```python3
import os
print("MYENV =", os.environ.get("MYENV"))
```

Now run `gunicorn --env MYENV=foo printenv`, you get

```text
[2026-09-09 11:48:54 +0200] [29188] [INFO] Starting gunicorn 25.2.0
[2026-09-09 11:48:54 +0200] [29188] [INFO] Listening at: http://127.0.0.1:8000 (29188)
[2026-09-09 11:48:54 +0200] [29188] [INFO] Using worker: sync
[2026-09-09 11:48:54 +0200] [29189] [INFO] Booting worker with pid: 29189
MYENV = foo
[...]
```

Next run `gunicorn --env MYENV=foo --check-config printenv`, you get

```text
MYENV = None
[...]
```

If the application, in order to load, needs an environment variable to be set, `gunicorn --check-config` will always fail.
