### ISSUE TITLE
Logging dictionary defaults should reference streams as ext://sys.stdxxx

### ISSUE THREAD

**Issue by fgimian** [benoitc/gunicorn#1793]
Hey there friends, really love Gunicorn 😄 

There's a little issue which I will send you a pull request on shortly, but thought I'd document it here for tracking.

For testing, I'm using an extremely minimal logging `logconfig_dict` in my config file such as:

```python
logconfig_dict = {'version': 1}
```

As you know, in `glogging.py` this is merged with the default configuration via the following code:

```python
        if dictConfig and cfg.logconfig_dict:
            config = CONFIG_DEFAULTS.copy()
            config.update(cfg.logconfig_dict)
            try:
                dictConfig(config)
            except (
                    AttributeError,
                    ImportError,
                    ValueError,
                    TypeError
            ) as exc:
                raise RuntimeError(str(exc))
```

However, the default config references handler streams as `sys.stdout` and `sys.stderr` which is not what the logging library expects.  This results in some nasty errors when running Gunicorn:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
AttributeError: 'str' object has no attribute 'write'
```

The solution is to reference these using an `ext://` prefix as documented [here](https://docs.python.org/3.6/library/logging.config.html#access-to-internal-objects)

Thanks heaps
Fotis

**Comment by tilgovi** [comment]
Closed by #1794
