### ISSUE TITLE
The documentation for the Settings section includes 4 sub-sections named "Server Mechanics"

### ISSUE THREAD

**Issue by dvincelli** [benoitc/gunicorn#1798]
Here is a screenshot showing the side-bar navigation. Different items appear under each sub-section.

![screen shot 2018-05-31 at 9 55 56 am](https://user-images.githubusercontent.com/178305/40786431-02c89e16-64b9-11e8-832e-0b3ed533ef9b.png)

**Comment by berkerpeksag** [comment]
Thank you for the report. I can reproduce it with Sphinx 1.6.3. I guess we can store existing sections in a set to avoid duplicate items in `format_settings`:

https://github.com/benoitc/gunicorn/blob/ba4b927ae5e6ecc414f2cc1e301f1f3d506b1254/docs/gunicorn_ext.py#L40-L41

Would you like to submit a PR?

**Comment by dvincelli** [comment]
Do you think it would make more sense to fix in the source by combining the 4 sections that have the same name together?

Did an earlier version of Sphinx regroup the sections automatically?

**Comment by berkerpeksag** [comment]
> Do you think it would make more sense to fix in the source by combining the 4 sections that have the same name together?

Unfortunately, that would create a lot of noise and make `git blame` a bit useless.

> Did an earlier version of Sphinx regroup the sections automatically?

This is the first time I've seen this bug and to be honest I'm not sure what the problem is.

**Comment by tilgovi** [comment]
I noticed it a while ago but wasn't motivated enough to change it. I should have filed a ticket. It's been happening for a long time.
