### ISSUE TITLE
Missing metadata.json in 19.8.x whl packages

### ISSUE THREAD

**Issue by JonathanHuot** [benoitc/gunicorn#1800]
Hi,
We're using jFrog Artifactory to store `gunicorn` packages, basically it hosts a private pypi repository on-premise. However, when uploading latest `gunicorn` to it, a `metadata.json` containing pkg info is missing.

This file is missing only for latest releases 19.8.0 and 19.8.1. I tested 19.7.1 and the file was present. 

E.g. 
```
$ pip download gunicorn==19.7.1 gunicorn==19.8.1
(..)
$ unzip gunicorn-19.7.1-py2.py3-none-any.whl
(..)
$ ls -l gunicorn-19.7.1.dist-info/
-rw-rw-r--  1 doomsday  staff   1.4K Mar 21  2017 DESCRIPTION.rst
-rw-rw-r--  1 doomsday  staff   1.1K Mar 21  2017 LICENSE.txt
-rw-rw-r--  1 doomsday  staff   2.7K Mar 21  2017 METADATA
-rw-rw-r--  1 doomsday  staff   3.9K Mar 21  2017 RECORD
-rw-rw-r--  1 doomsday  staff   110B Mar 21  2017 WHEEL
-rw-rw-r--  1 doomsday  staff   184B Mar 21  2017 entry_points.txt
-rw-rw-r--  1 doomsday  staff   1.7K Mar 21  2017 metadata.json
-rw-rw-r--  1 doomsday  staff     9B Mar 21  2017 top_level.txt
$ unzip gunicorn-19.8.1-py2.py3-none-any.whl
(..)
$ ls -l gunicorn-19.8.1.dist-info/
-rw-r--r--  1 doomsday  staff   1.1K Apr 30 18:38 LICENSE.txt
-rw-r--r--  1 doomsday  staff   3.3K Apr 30 18:38 METADATA
-rw-r--r--  1 doomsday  staff   3.7K Apr 30 18:38 RECORD
-rw-r--r--  1 doomsday  staff   110B Apr 30 18:38 WHEEL
-rw-r--r--  1 doomsday  staff   184B Apr 30 18:38 entry_points.txt
-rw-r--r--  1 doomsday  staff     9B Apr 30 18:38 top_level.txt
```
You will notice `DESCRIPTION.rst` is missing, too. It will be great if we can have them back. Do you have changed your deployment instructions recently ?

Thanks

**Comment by JonathanHuot** [comment]
Looks like the `Metadata-Version` has been updated from `1.1` ([PEP314](https://www.python.org/dev/peps/pep-0314/)) to `2.1` ([PEP566](https://www.python.org/dev/peps/pep-0566/)). Probably due to an update of the deployment tools. Some others have raised the same behavior https://github.com/pypa/twine/issues/341

I'm looking forward to the [jFrog Artifactory issue](https://www.jfrog.com/jira/browse/RTFACT-16189) then.

Sorry for the noise.

**Comment by berkerpeksag** [comment]
No worries, thank you for following up with us!
