### ISSUE TITLE
Check Gunicorn worker contents and request queue

### ISSUE THREAD

**Issue by saurabhprakash** [benoitc/gunicorn#1808]
Suppose I've "N" number of gunicorn workers running, 

Is there away to check exact content(of request being served) of particular worker and contents of current request queue waiting to be processed by gunicorn ?

**Comment by tilgovi** [comment]
There is no way to do this right now.

Some third party worker types might have a queue, but Gunicorn does not provide any first-party worker types that have a request queue. Instead, requests are queued at the by the operating system in the TCP listen backlog of the server socket.

The workers have no exposed introspection API. The internal APIs vary by worker type.

You may be able to implement a feature by providing a `post_fork` hook and spawning a thread to serve an introspection API of your own, but it would have to be implemented with a specific worker type in mind. There is no public interface for inspecting the current request from code, and some workers may have many concurrent requests.

**Comment by saurabhprakash** [comment]
ok, Thanks for the information.
