### ISSUE TITLE
"gunicorn reload" doesn't reload logconfig_dict (dictConfig)

### ISSUE THREAD

**Issue by JonathanHuot** [benoitc/gunicorn#1811]
When gunicorn receive signal `HUP`, it reloads its configuration. However, `logconfig_dict` property is updated but not "reloaded".

In order to solve the problem, I have in my configuration:

```python
    def on_reload(server):
        server.log.setup(server.cfg)
```

However, I am not sure it is the wanted behavior. Any help ?

**Comment by benoitc** [comment]
How are you passing the config to gunicorn?

**Comment by JonathanHuot** [comment]
config is stored in a `yaml` file and loaded as a dict in my `appconfig.py`. Then I start gunicorn with `gunicorn -c appconfig.py` 


My `appconfig.py` is something like

```python
with open("logconfig.yaml", "r") as fd:
    import os.path
    import yaml

    logconfig_dict = yaml.load(os.path.expandvars(fd.read()))
```

**Comment by benoitc** [comment]
this should be fixed in last versions of gunicorn. feel free to open a new ticket if more is needed.
