### ISSUE TITLE
how can I know the master process was changed

### ISSUE THREAD

**Issue by xiazhibin** [benoitc/gunicorn#1814]
Recently, when I send signal `HUP` to Gunicorn,but it reports that `Parent was changed.Worker exiting`

So,I want to know why the parent changed.Can Gunicorn log some message if the parents was changed.

But, it is strange that Gunicorn works very well before.I believe that that is not an accidental event.It happens several times.

```
[2018-06-21 17:33:48 +0000] [31074] [INFO] Handling signal: hup
[2018-06-21 17:33:48 +0000] [31074] [INFO] Hang up: Master
[2018-06-21 17:33:49 +0000] [33720] [INFO] Parent changed, shutting down: <Worker 33720>
[2018-06-21 17:33:49 +0000] [33720] [INFO] Worker exiting (pid: 33720)
[2018-06-21 17:33:49 +0000] [33718] [INFO] Parent changed, shutting down: <Worker 33718>
[2018-06-21 17:33:49 +0000] [33718] [INFO] Worker exiting (pid: 33718)
[2018-06-21 17:33:49 +0000] [33717] [INFO] Parent changed, shutting down: <Worker 33717>
[2018-06-21 17:33:49 +0000] [33717] [INFO] Worker exiting (pid: 33717)
[2018-06-21 17:33:58 +0000] [33716] [INFO] Parent changed, shutting down: <Worker 33716>
[2018-06-21 17:33:58 +0000] [33716] [INFO] Worker exiting (pid: 33716)
[2018-06-21 17:33:58 +0000] [33719] [INFO] Parent changed, shutting down: <Worker 33719>
[2018-06-21 17:33:58 +0000] [33719] [INFO] Worker exiting (pid: 33719)
```

Is there any way to help me to find out the reason.

**Comment by tilgovi** [comment]
HUP does not change the master process. Something in your code or the way you run Gunicorn is listening to HUP and causing the master process to exit.

**Comment by xiazhibin** [comment]
@tilgovi Thanks.But the truth is that it does not get parent changed every time when I HUP to gunicorn.It is sometimes get parent changed when I HUP to gunicorn

**Comment by tilgovi** [comment]
It's not easy to help debug it. Gunicorn should not change the parent on HUP. What type of worker are you using? How do you run Gunicorn (supervisord, upstart, systemd, or ...)? Are you calling any code in Gunicorn's server hooks to run code before fork? Are you using `--preload`?

**Comment by xiazhibin** [comment]
@tilgovi there is my gunicorn config

```
path_of_current_file = os.path.abspath(__file__)
path_of_current_dir = os.path.split(path_of_current_file)[0]

_file_name = os.path.splitext(os.path.basename(__file__))[0]

sys.path.insert(0, path_of_current_dir)

worker_class = 'sync'
workers = multiprocessing.cpu_count() * 2 + 1

chdir = os.getenv("CURRENT_PATH")

worker_connections = 1000
timeout = 30
max_requests = 2000
graceful_timeout = 30
keepalive = 2

loglevel = 'info'

reload = False

shared_path = os.getenv("SHARED_PATH")
log_path = os.getenv("LOG_PATH")
bind = 'unix:/tmp/gunicorn_gizmohubviewer.sock'
pidfile = '%s/run/gunicorn.pid' % (shared_path)
errorlog = '%s/gunicorn_error.log' % (log_path)
accesslog = '%s/gunicorn_access.log' % (log_path)
```

I use supervisor to manage Gunicorn.Worker type is `sync` and I don`t use `--preload`

**Comment by tilgovi** [comment]
Are you sending `HUP` to the supervisor process or the gunicorn master process? There have been issues around reloading with supervisor that you can find by searching the issue.

**Comment by xiazhibin** [comment]
I am sending `HUP` to supevisor.
Thanks,I have a try

**Comment by tilgovi** [comment]
Sending HUP to supervisord will restart Gunicorn. Try sending HUP to the Gunicorn master process instead. If you need the pid, you can use the pidfile option.

Please re-open if you need more help.

**Comment by xiazhibin** [comment]
I still have on idea about the "parent changed".
Can gunicorn restart the worker when the parent changed?

PS: I  **cannot** re-open my own issues if a repo collaborator closed them
