### ISSUE TITLE
gevent monkey-patch earlier

### ISSUE THREAD

**Issue by buchmoyerm** [benoitc/gunicorn#1816]
Using gunicorn 19.8.1 i get the monkey-patch warning with only a single worker

I am using a pretty basic flask app.py

My command I am running is `gunicorn -b 0.0.0.0:9000 -k gevent -w 1 app:app` and the warning is being printed before my app.py event starts running

```
[2018-06-25 13:58:03 -0400] [149803] [INFO] Starting gunicorn 19.8.1
[2018-06-25 13:58:03 -0400] [149803] [INFO] Listening at: http://0.0.0.0:9000 (149803)
[2018-06-25 13:58:03 -0400] [149803] [INFO] Using worker: gevent
[2018-06-25 13:58:03 -0400] [149815] [INFO] Booting worker with pid: 149815
/(Redacted local path)/venv/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  monkey.patch_all(subprocess=True)
```

I looked and found 

https://github.com/benoitc/gunicorn/blob/bd833e0009b8b07d13117f71534eb28e8dc24c5d/gunicorn/workers/ggevent.py#L304 (file that does the patch_all)

and inside base_async.py

https://github.com/benoitc/gunicorn/blob/bd833e0009b8b07d13117f71534eb28e8dc24c5d/gunicorn/workers/base_async.py#L92 (file that imports ssl)

So I am not sure how this is supposed to work, but it doesn't seem like it can.

**Comment by jamadden** [comment]
I would expect that gevent 1.3.4 would silence the error here.

**Comment by buchmoyerm** [comment]
That seems to have fixed the issue. Looks like version 1.1rc3.3 just crashed the app (which is what I had on prod). And when testing locally I had version 1.3.1 installed which didn't crash the app but printed the message. 1.3.4 did not print the message at all. Thanks.
