### ISSUE TITLE
Monitoring sync workers idle/busy time

### ISSUE THREAD

**Issue by nailgun** [benoitc/gunicorn#1818]
## Background

My current project is migrating to microservice architecture. But unfortunately all code is written in synchronous style. To make refactoring process smoother we decided to migrate code to microservices and then try to rewrite it in async style. But now we should be prepared to correctly scale each service workers, because inter-service communication will generate many requests and many of them are long.

We want to find a solution to understand is current amount of workers for some service is enough. Or there is always requests waiting for a worker to free.

## Solution 1

One solution is to monitor system TCP backlog. But for some reason it's always empty on systems where I tested it. Also there is downside of this method. Precision is limited by frequency of backlog queries. So we can miss backlog length peaks between two queries.

## Solution 2

Otherwise we can add metric collector to gunicorn and export it in some format. For example, Prometheus:

```
# TYPE idle_time_seconds_sum summary
idle_time_seconds_sum{pid="8013"} 51.135032176971436
```

Then we can query Prometheus with `avg (irate(idle_time_seconds_sum[5m]))` to see floating-window average busyness.

This metric will be pretty precise because it is derivative of summarised idle time and nothing will be lost in between metric queries.

**Comment by benoitc** [comment]
stalled issue. Some separate work is on going anyway, let's continue on them.
