### ISSUE TITLE
Does Gunicorn Support 206 responses(ranged requests) with flask?

### ISSUE THREAD

**Issue by hpfm-2** [benoitc/gunicorn#1820]
I am sorry if this has been asked before but how to achieve support for ranged request with flasks send_file() option?

I have tried searching the docs but couldn't find anything.

Thanks!

**Comment by benoitc** [comment]
if flask is using the FileWrapper api then yes. Otherwise can you point me on doc/example about it?

**Comment by hpfm-2** [comment]
@benoitc http://flask.pocoo.org/docs/1.0/api/#flask.send_file

**Comment by benoitc** [comment]
closing issue since it has been answered and no action since.
