### ISSUE TITLE
Can gunicorn restart workers after parent changed?

### ISSUE THREAD

**Issue by xiazhibin** [benoitc/gunicorn#1825]
Since I send `HUP` to `supervisor` to signal the gunicorn master process but get 'parent changed',
and all workers are exited, so is there way to restart workers after "parent changed"?

**Comment by benoitc** [comment]
@xiazhibin what do you mean ? No new workers were spawned?

**Comment by xiazhibin** [comment]
Yes,it is.It just restart the master process but not the workers process

Benoit Chesneau <notifications@github.com> 于2018年7月6日周五 下午12:18写道：

**Comment by benoitc** [comment]
@ciazhibin why did you closed the issue? was it solved? Anything that can help us to figure what happened?
