### ISSUE TITLE
How to configure Gunicorn to distribute a request to specific worker based on cookie, session or http parameters information?

### ISSUE THREAD

**Issue by freewindwu** [benoitc/gunicorn#183]
Hi All,

I met a problem with my app based on gevent 0.13.3 and gevent-websocket 0.3dev working with multiprocessing.
The application is a web game. WE have many “rooms”, and users go to these rooms to play cards. I implemented it, and it works fine on single process model. But our server has 8 CPU cores, with the limitation of Python GIL, we can only make use of one CPU core. The waste is huge. I want to migrate it to multiprocessing model. I tried Gunicorn with gevent worker, and my problem comes: in our application, the master process needs to know which worker process the user should be distributed to, and that means we can’t randomly distribute users to idle workers, we must distribute him/her to a specific worker. My question is how to configure Gunicorn to distribute a request to specific worker based on cookie, session or http parameters information?

Thank you.

freewind

**Comment by guettli** [comment]
Just for the records, here is a related question on StackOverflow: http://stackoverflow.com/q/34172964/633961
