### ISSUE TITLE
Eventlet schedular cpu or supervisor limited ?

### ISSUE THREAD

**Issue by ibuler** [benoitc/gunicorn#1837]
Hi:

I run a django project in gunicorn with **eventlet** scheduler in docker(docker in vSphere platform vm), I see some instance run ok, but some not.
When I change to **threading** schedular, all instance ok.

Then, All instance change to **eventlet** type, I migrate some vm(instance not work) to the ok vm physics server, All run ok .

So, Does **eventlet** has cpu or supervisor limited ?

**My environment:** 
```
CentOS:    7
Python:    3.6
Docker:    18.03
Eventlet:  0.22.1
Gunicorn:  19.7.1
```

**Comment by benoitc** [comment]
I don't understand the question. What do you mean by limited?

**Comment by ibuler** [comment]
Just close now，I need more info from guest
