### ISSUE TITLE
Django deployment with gunicorn socket set up with systemd, gunicorn not honoring gunicorn.conf file settings on Debian 9.4

### ISSUE THREAD

**Issue by lajones86** [benoitc/gunicorn#1838]
I followed the systemd deployment instructions here at http://docs.gunicorn.org/en/stable/deploy.html

/etc/systemd/system/gunicorn3.service:

    [Unit]
    Description=gunicorn3 daemon
    Requires=gunicorn3.socket
    After=network.target
    
    [Service]
    PIDFile=/run/gunicorn3/pid
    User=feritsuser
    Group=feritsuser
    RuntimeDirectory=gunicorn3
    WorkingDirectory=/home/feritsuser/Ferits
    ExecStart=/usr/bin/gunicorn3 --pid /run/gunicorn3/pid   \
              --bind unix:/run/gunicorn3/socket Ferits.wsgi
    ExecReload=/bin/kill -s HUP $MAINPID
    ExecStop=/bin/kill -s TERM $MAINPID
    PrivateTmp=true
    
    [Install]
    WantedBy=multi-user.target

/etc/systemd/system/gunicorn3.socket

    [Unit]
    Description=gunicorn3 socket
    
    [Socket]
    ListenStream=/run/gunicorn3/socket
    
    [Install]
    WantedBy=sockets.target

/etc/tmpfiles.d/gunicorn3.conf:

    d /run/gunicorn3 0755 feritsuser feritsuser \
    --workers 2 \
    --timeout 300 \
    --error-logfile /var/log/gunicorn3/error.log \

I have gunicorn.conf symlinked to gunicorn3.conf as well.

My nginx proxy to the gunicorn socket is working. I can load the application and use it in a browser, but I'm getting a 502 timeout on one page. Nginx error log is:

>2018/07/25 10:31:18 [error] 614#614: *3 upstream prematurely closed connection while reading response header from upstream, client: 10.18.3.145, server: _, request: "GET /browse/expenses/ HTTP/1.1", upstream: "http://unix:/run/gunicorn3/socket:/browse/expenses/", host: "10.18.3.59", referrer: "http://10.18.3.59/"

The timeout is occurring after 30 seconds, and it's not writing to the log file specified in gunicorn3.conf/gunicorn.conf, so it appears that my socket implementation is not honoring the .conf file. What am I doing wrong? I've tried chowning the .conf files for feritsuser:feritsuser, and still, nothing.

I've also tried changing the ExecStart line in gunicorn3.service to 

ExecStart=/usr/bin/gunicorn3 --pid /run/gunicorn3/pid   \
          --bind unix:/run/gunicorn3/socket Ferits.wsgi  \
          --config /etc/tmpfiles.d/gunicorn3.conf

This gives me a 502 on all application pages.

**Comment by tilgovi** [comment]
The syntax of the conf file is Python and it should be called `gunicorn.conf.py`.

```
workers = 2
timeout = 300
error_logfile = '/var/log/gunicorn3/error.log
```

I think it would default to using a conf file in the current working directory. In your case, this file would need to be `/home/feritsuser/Ferits/gunicorn.conf.py`.

See if that helps!

**Comment by lajones86** [comment]
I ended getting it working by doing away with the .conf file and just specifying the parameters in the gunicorn3.service file like so:

```
[Unit]
Description=gunicorn3 daemon
Requires=gunicorn3.socket
After=network.target

[Service]
PIDFile=/run/gunicorn3/pid
User=feritsuser
Group=feritsuser
RuntimeDirectory=gunicorn3
WorkingDirectory=/home/feritsuser/Ferits
ExecStart=/usr/bin/gunicorn3 --pid /run/gunicorn3/pid \
          --bind unix:/run/gunicorn3/socket Ferits.wsgi \
          --workers 2 \
          --timeout 300 \
          --error-logfile /var/log/gunicorn3/error.log \
          --log-level=debug
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
