### ISSUE TITLE
Docker error gunicorn: error: unrecognized arguments: app:app

### ISSUE THREAD

**Issue by sevaho** [benoitc/gunicorn#1841]
Hi

I have a flask application which I want to run as a docker container. 
When I deploy the container as a docker container on my server it will run for +- 30 secondes good without any errors, and suddenly it crashes and gives me this output:

```
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
```

The weird thing is that it works fine the first 30 secondes and after it, it crashes.

But when running the same gunicorn version as non docker, just as dev it works fine and does not crash after 30 secondes.

Dockerfile:

```
# vim: set ft=dockerfile:

FROM python:3-alpine

RUN apk --update add

COPY ./app /app

RUN pip install -r /app/requirements.txt

RUN addgroup -S -g 1000 user && adduser -S -u 1000 -D -G user user
RUN chown -R user:user /app

USER user

WORKDIR /app

EXPOSE 8000

# ENTRYPOINT ["/usr/local/bin/gunicorn", "--access-logfile=-", "--workers=2", "--bind=0.0.0.0:8000", "app:app"]

CMD /usr/local/bin/gunicorn --access-logfile - --error-logfile - -b :8000 app:app
```

requirements.txt:

```
flask
flask-login
flask-wtf
gunicorn
```

Folder structure:

```
├── [sevaho    188]  app
│   ├── [sevaho    328]  app.py
│   ├── [sevaho    118]  config.py
│   ├── [sevaho    333]  forms.py
│   ├── [sevaho    775]  models.py
│   ├── [sevaho    312]  __pycache__
│   ├── [sevaho     47]  requirements.txt
│   ├── [sevaho   2.4K]  routes.py
│   ├── [sevaho     26]  static
│   └── [sevaho    138]  templates
├── [sevaho   1.9K]  debug.sh
├── [sevaho    609]  Dockerfile
```

app.py:

```
from flask import Flask
from flask_login import LoginManager
import sys
import logging
from config import Config

app = Flask(__name__)

app.logger.addHandler(logging.StreamHandler(sys.stdout))
app.logger.setLevel(logging.DEBUG)
app.config.from_object(Config)
login = LoginManager(app)
login.login_view = 'login'

import routes
```

**Comment by tilgovi** [comment]
Anything before that in the log?

**Comment by sevaho** [comment]
Yeah:

I tried with some older gunicorn versions but it happens wiht all of them.

```
[2018-07-30 16:44:30 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2018-07-30 16:44:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2018-07-30 16:44:30 +0000] [1] [INFO] Using worker: sync
[2018-07-30 16:44:30 +0000] [8] [INFO] Booting worker with pid: 8
[2018-07-30 16:45:20 +0000] [1] [INFO] Handling signal: term
[2018-07-30 16:45:20 +0000] [8] [INFO] Worker exiting (pid: 8)
[2018-07-30 16:45:20 +0000] [1] [INFO] Shutting down: Master
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: app:app
```

**Comment by tilgovi** [comment]
What happens after the "unrecognized arguments" messages? Does the container exit? What is scheduling your container (`docker run`, kubernetes, swarm, etc)? I wonder what sends the `SIGTERM` before the shutdown. Does this only happen right after the app shuts down?

**Comment by tilgovi** [comment]
So the container _does_ shut down, and then restart, after this happens. What causes the `SIGTERM` that comes before the errors and before "Shutting down: Master"?

**Comment by sevaho** [comment]
Ok so after some digging the problem was not related to gunicorn. The problem was (I think) with docker.

I am running a private container registry where I push locally build docker images to. Now instead of pushing the images to the server, I was building a new docker image on the server with the same name, so not pushing to registry.

So when I want to run the just build docker image om the server (which was not pushed to the registry), but had the same name as a container image in the registry, docker was confused.

the docker image != the latest docker image in registry (same name).

And when you add (--restart-always) I guess docker checks where the image is (stored), so it looked in the registry first, but that image was not the same.

The fix was simple: I need to push to the registry because (for reason still unkown) docker restarts the image and I am running private-docker-registry/my-container:latest instead of just private-docker-registry/my-container. With all my other containers (nodejs, go, php) I develop them the same way, pushing to registry all the same, it runs without the tag (:latest). But conclusion => IT WORKS NOW ;)

**Comment by antsarand** [comment]
@sevaho I am running into this issue too. Can you provide additional details on how you resolved this? instead of  something like `docker run private-docker-registry/my-container`, you just did `docker run private-docker-registry/my-container:latest` ? and just that resolved your issue?

**Comment by sevaho** [comment]
@antsarand I can't remember anymore if I fixed it or not, I don't use gunicorn anymore, am running Sanic with `python -m sanic ...`

**Comment by benoitc** [comment]
@sevaho removed your comment as there is no need to spam with another project there.

@antsarand since he doesn't remember, any logs you can add with debug mode enabled? Can you open a new ticket for it?

**Comment by sevaho** [comment]
@antsarad I don't remember anymore how I fixed it, am now using another flask like framework where I don't need Gunicorn.

**Comment by antsarand** [comment]
@sevaho and @benoitc I resolved my issue, which turned out to be somewhat unrelated since it was an issue with the code I inherited. In my case, `gunicorn` expected additional arguments.
