### ISSUE TITLE
gunicorn with eventlet doesn't perform eventlet monkey patching since 19.8.0

### ISSUE THREAD

**Issue by capnfabs** [benoitc/gunicorn#1847]
Hi there,

I think the fix for https://github.com/benoitc/gunicorn/issues/1584 (in commit 120f503f68929ef98d721a406745a1dbbb9d83fe) inadvertently prevents eventlet monkey patching from running upon worker startup.

My understanding is:
- EventletWorker.init_process now calls `super(EventletWorker, self).init_process()` _before_ `patch()`
- The super method `Worker.init_process()` enters a run loop, and never returns.

This means that eventlet never gets monkey patched by the gunicorn worker init process.

The workaround we've used in the meantime is to just run eventlet monkey patching on startup of our application code, but it's probably worth fixing this if we want to retain the expectation that gunicorn will install eventlet monkey patching.

Happy to send a PR, but wanted to check that I understood what was going on correctly first :)

**Comment by tilgovi** [comment]
Your understanding sounds correct to me. If you can take #1584 into account with a PR that would be great. Thank you!

**Comment by benoitc** [comment]
it actually does patching but after the process is initialized. What is the issue you're experimenting?

**Comment by tilgovi** [comment]
My understanding is that it does not, @benoitc, since `super(EventletWorker, self).init_process()` never returns.

**Comment by colincadams** [comment]
This is still an issue, what is blocking #1884 from being merged?

**Comment by travelsalesman** [comment]
@tilgovi Eventlet has fixed the issue by moving the module which needed the SIGCHILD handler to import time:
https://github.com/eventlet/eventlet/commit/82f1877ff5b950e1ee9debbb8be880ebedb8abcb

Which is before gunicorn starts handling  SIGCHILD, so https://github.com/benoitc/gunicorn/commit/120f503f68929ef98d721a406745a1dbbb9d83fe  can be reverted, i.e. this PR.

Currently eventlet workers run without greening so are pretty much pointless

**Comment by tilgovi** [comment]
Perfect. Let's merge the revert with a PR that bumps the required Eventlet version to 0.24.1.
