### ISSUE TITLE
Socket creation issue on Alpine based docker image

### ISSUE THREAD

**Issue by akshaybabloo** [benoitc/gunicorn#1849]
I have been trying to use Gunicorn on docker Alpine image and I get an error as `connection to /tmp/gunicorn.sock failed: [Errno 1] Operation not permitted`

This shouldn't be a problem because I'm running it as `root` user. More information of it at https://stackoverflow.com/questions/51664615/gunicorn-not-able-to-connect-to-sock-file-on-alpine

**Comment by tilgovi** [comment]
Is this only a problem on `/tmp`? What if you create the socket under `/run`?

**Comment by akshaybabloo** [comment]
That actually worked. I wonder why?

**Comment by jamadden** [comment]
Check how that filesystem is mounted.

**Comment by akshaybabloo** [comment]
Got it. Thanks.
