### ISSUE TITLE
Critical worker timeout while serving Flacon application

### ISSUE THREAD

**Issue by kalravibhor** [benoitc/gunicorn#1854]
Hi,

I am facing one-of-those issues that seems to occur without any provocation. But as is often the case, perhaps I am missing something. Detailed below is the case in question.

One of my repositories serving a `falcon` application through `gunicorn` runs on port `3547` on `localhost` with a `timeout` of 30s. When I start the application with `workers=1`, everything seems to be fine with the process booting as usual.

`[2018-08-11 12:03:22 +0530] [15660] [INFO] Listening at: http://127.0.0.1:3547 (15660)`
`[2018-08-11 12:03:22 +0530] [15660] [INFO] Using worker: sync`
`[2018-08-11 12:03:22 +0530] [15664] [INFO] Booting worker with pid: 15664`

Things get interesting when I hit an API endpoint served by the application. The primary worker timesout within 30s and consequently another worker is started, giving the impression that the process threads have multiplied. This happens every time I hit an endpoint. As a result I don't receive any response for the request. 

`[2018-08-11 13:43:21 +0530] [18194] [CRITICAL] WORKER TIMEOUT (pid:18197)`
`[2018-08-11 13:43:22 +0530] [18267] [INFO] Booting worker with pid: 18267`

What is perplexing is that none of my other repositories which serve the application re-using most of the code from the repository in question are encountering such an issue. Have tried everything from re-cloning the repository to comparing with my other repositories served using `gunicorn` to changing the port where `gunicorn` is running to no avail. 

Looking forward to insights from the community. Any help will be appreciated. TIA.

config.py

`bind = "127.0.0.1:3547"`
`reload = True`
`workers = 1`
`timeout = 30`

app.py

`import falcon`
`from api import Recognition, Feedback`
`from falcon_multipart.middleware import MultipartMiddleware`

`api = application = falcon.API(middleware=[MultipartMiddleware()])`

`try:`

`    recognition = Recognition()`
`    api.add_route('/recognize', recognition)`

`    feedback = Feedback()`
`    api.add_route('/feedback', feedback)`

`except Exception as e:`
`    print e`

Configuration and System Details : 
`macOS High Sierra 10.13.6`
`gunicorn (version 19.7.1)`
`Python 2.7.14`

Vibhor

**Comment by tilgovi** [comment]
Perhaps you can add some logging statements inside your route handlers to see how far things progress and where things might block.

**Comment by benoitc** [comment]
@kalravibhor can you send a pr adding  this flaconapp to the the example folder?

**Comment by kalravibhor** [comment]
@benoitc : Looks like the issue was with another library that I was using inside the `on_post` method. The library is not fork safe ultimately leading to a thread timing out. Closing the issue for now. Thanks !
