### ISSUE TITLE
"Contradictory scheme headers" error when X-Forwarded-Protocol set to 'https'

### ISSUE THREAD

**Issue by tisdall** [benoitc/gunicorn#1857]
see #1766 for some people having the same issue

I have the following in my nginx config:
```
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
```

This causes an error because the default setting for `secure_scheme_headers` is `{'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}`.  When it compares the `ssl` to the `https` the error is thrown in https://github.com/benoitc/gunicorn/blob/19.9.0/gunicorn/http/message.py#L118

**Comment by tilgovi** [comment]
You're correct about the cause. The value for `X-Forwarded-Protocol` should be `ssl` but `$scheme` will be `http` or `https`. You can either change your nginx configuration to set `X-Forwarded-Protocol` to `ssl` conditionally, based on the value of `$scheme`; change `secure_scheme_headers`; or remove `proxy_set_header X-Forwarded-Protocol` altogether.

I'm not familiar with any software that sets `X-Forwarded-Protocol` (only `X-Forwarded-Proto`), so I can't say whether the default `secure_scheme_headers` are correct.

I don't see any bug in Gunicorn. Thankfully, this seems like it could be solved with configuration changes.

**Comment by tisdall** [comment]
From the reading I did, it seems that `X-Forwarded-Protocol` was from before `X-Forwarded-Proto` being the agreed standard.  That would probably explain why some examples have "https" as a value and others have "ssl", there's no standard.

**Comment by tilgovi** [comment]
Makes sense!

**Comment by tilgovi** [comment]
We could see about rewriting that code to show all the headers and their values. I'm happy to review pull requests for that!

Saying that the value doesn't match the expected value isn't quite enough information. It's okay if a value doesn't match, that is the expected case when a client connects without SSL. What the error message means is that some header matches and some header does not, which is what it's a contradiction. Some header says the connection is secure and some other header says the connection is not secure.

**Comment by berkerpeksag** [comment]
We could add a note about `X-Forwarded-Protocol` to our nginx configuration example:

https://github.com/benoitc/gunicorn/blob/master/examples/nginx.conf

We already have a couple notes and hints on how to configure nginx with Gunicorn in the file.

**Comment by tisdall** [comment]
Yeah, my first version of that comment had the value, but then I was wondering if that might be a security issue leaking that info.  I guess it shouldn't be an issue if the value is hard coded in the proxy or otherwise unmodifiable by the end user.

**Comment by tisdall** [comment]
@berkerpeksag - I think the only issue is people with legacy configurations as no one really should be setting `X-Forwarded-Protocol` unless they're using old libraries that haven't adopted to the standard.

**Comment by tilgovi** [comment]
We might be fine to leave things as is. Our example nginx configuration should work. If people search for "Contradictory secure scheme headers" they'll land of one of the issues here and figure out what's going on.

**Comment by benoitc** [comment]
maybe adding a short note on our configuration file or in the deploying doc would worth it. Not sure about the phrasing. Any idea?

**Comment by tilgovi** [comment]
Either way. If someone wants to write it, I would review the PR, but I'm comfortable with the current documentation.

**Comment by tilgovi** [comment]
If you'd like to make a PR, I would be happy to review it.

`gunicorn.http.errors` has a `InvalidSchemeHeaders` exception that right now has no arguments. It is created in `gunicorn.http.message`, where the conflicting values should be available to you.

**Comment by llybin** [comment]
If you nginx and app not on one host, probably, this solution: https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips

**Comment by tilgovi** [comment]
Thanks for the discussion everyone! As this has now been open for a while with no action, I'm going to close it. I will still happily review any documentation PRs.

**Comment by akondas** [comment]
If you are unable to change the nginx configuration, there is one more way to work around this problem.
Create config file (for example: `gunicorn.py`):
```python
secure_scheme_headers = {'X-FORWARDED-PROTOCOL': 'https', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
```
Then run gunicorn with this configuration:
```bash
gunicorn --config /path/to/gunicorn.py
```
Then everything will work fine without changing the proxy.
I hope I helped someone :wink: :beers:

**Comment by aisk** [comment]
> You're correct about the cause. The value for `X-Forwarded-Protocol` should be `ssl` but `$scheme` will be `http` or `https`. You can either change your nginx configuration to set `X-Forwarded-Protocol` to `ssl` conditionally, based on the value of `$scheme`; change `secure_scheme_headers`; or remove `proxy_set_header X-Forwarded-Protocol` altogether.
> 
> I'm not familiar with any software that sets `X-Forwarded-Protocol` (only `X-Forwarded-Proto`), so I can't say whether the default `secure_scheme_headers` are correct.
> 
> I don't see any bug in Gunicorn. Thankfully, this seems like it could be solved with configuration changes.

Hi @tilgovi , I saw [mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto#directives) / [aws](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-proto) / [nginx](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/)'s documents said that, `x-forwarded-proto` should be https instead of ssl.

**Comment by tilgovi** [comment]
@aisk sorry for the late reply. That's correct. Gunicorn has the same behavior as these other systems for `X-Forwarded-Proto`. The strings for `X-Forwarded-Protocol` are different, though. I don't know what other systems support `X-Forwarded-Protocol` or the history of why Gunicorn has support for it in addition to `X-Forwarded-Proto`.

**Comment by artforlife** [comment]
> You're correct about the cause. The value for `X-Forwarded-Protocol` should be `ssl` but `$scheme` will be `http` or `https`. You can either change your nginx configuration to set `X-Forwarded-Protocol` to `ssl` conditionally, based on the value of `$scheme`; change `secure_scheme_headers`; or remove `proxy_set_header X-Forwarded-Protocol` altogether.
> 
> I'm not familiar with any software that sets `X-Forwarded-Protocol` (only `X-Forwarded-Proto`), so I can't say whether the default `secure_scheme_headers` are correct.
> 
> I don't see any bug in Gunicorn. Thankfully, this seems like it could be solved with configuration changes.

I have a site running on Gunicorn + Nginx. Upon moving DNS to Cloudflare and turning on "Always Use HTTPS", I was getting the same "Contradictory scheme headers" error. Commenting out `proxy_set_header X-Forwarded-Protocol $scheme;` in my Nginx config seems to have fixed the issue. Could you tell me if it is safe to leave it like that in production? What was the conflict in the first place?
