### ISSUE TITLE
Issues between gunicorn and juniper pyez library (workers timeout)

### ISSUE THREAD

**Issue by jbotello7381** [benoitc/gunicorn#1860]
Hi,

I'm been working on a project to provide a rest API using Flask and Gunicorn for multi-threading support on front of Flask.

I already open an issue on juniper pyez github repo

https://github.com/Juniper/py-junos-eznc/issues/867

I added logging entry points before and after where seems break.  

Please let me know if there's any detail information I could provide.  I haven't been able to figure this one out.

thanks

**Comment by benoitc** [comment]
it seems you closed the issue on juniper. I'm not sure how to check it on juniper. What does pyez? Maybe it's blocking?

**Comment by benoitc** [comment]
issue have been closed upstream but no update there. @jbotello7381 do you have more details to add?  Seems like the issue have been solved using geve,t wich would mean pyez is blocking but...

**Comment by jbotello7381** [comment]
anything to add for now.   It works using gevent worker and I haven't had much time to do more research on why or how.
