### ISSUE TITLE
HTTP to HTTPS redirect without NGINX/Apache/etc proxy.

### ISSUE THREAD

**Issue by sjmeyer** [benoitc/gunicorn#1864]
I am running an app on AWS and using an Application Load Balancer in front of my container instances. I have my SSL cert on the ALB, so SSL termination happens there. How can I setup HTTP to HTTPS redirection on  the Gunicorn side of things?

You can't do the redirection on the ALB, it's not supported at this time, so it has to happen on the application side. The documentation basically just says to use NGINX or something similar. I don't really want to put NGINX or Apache on my containers, too, it's not necessary with the ALB upfront.

**Comment by tilgovi** [comment]
Application Load Balancers pass `X-Forwarded-Proto` headers. If you have your ALB always connect to Gunicorn over HTTPS, regardless of whether the client connection is HTTP or HTTPS, you can determine the scheme by checking the WSGI environment key `wsgi.url_scheme`. Different frameworks may provide easy middleware you can add to your application or other configuration that will handle the redirect for you.

For this to work, you will also need to tell Gunicorn to trust the ALB's headers with the [--forwarded-allow-ips](http://docs.gunicorn.org/en/latest/settings.html#forwarded-allow-ips) setting. If the ALB is the only public route to Gunicorn, it is safe to set this to `*`.

**Comment by tilgovi** [comment]
> Different frameworks may provide easy middleware you can add to your application or other configuration that will handle the redirect for you.

See, for example:
- Django: https://docs.djangoproject.com/en/2.1/ref/settings/#secure-ssl-redirect
- Flask: https://github.com/kennethreitz/flask-sslify
- Falcon: https://github.com/falconry/falcon-require-https

**Comment by sjmeyer** [comment]
Thanks @tilgovi ,

I have the  --forwarded-allow-ips set to *. The ALB is indeed the only route to the ECS cluster, so I'm good on that front.

I'll take a look at the links you provided and report back if I have any further questions.

Thanks!

**Comment by benoitc** [comment]
looks like the issue have been answered. Closing the issue then :)
