### ISSUE TITLE
gunicorn: error: unrecognized arguments: --workers=2 server:app

### ISSUE THREAD

**Issue by cyzLoveDream** [benoitc/gunicorn#1867]
![image](https://user-images.githubusercontent.com/23023057/44768074-aebd0c00-ab92-11e8-959d-d7e76763a1e7.png)
how to solve this problem

**Comment by benoitc** [comment]
what's your command line? How do you launch gunicorn?

**Comment by teemukataja** [comment]
Make sure that you are in the same directory as `server.py` and that your function is named `def app()`. If you are in a directory above `server.py` you can add the directory name into the module with a dot `.` for example if the python script resides in `dir/server.py` you can say `gunicorn --workers=2 dir.server:app`.

**Comment by cyzLoveDream** [comment]
well, I have resolved this problem.  it ended up that I had ArgumentParser attempting to get arguments from CLI - I commented that out and it works. @benoitc  @teemukataja

**Comment by manishb-agnihotri** [comment]
@cyzLoveDream what did you comment out?

**Comment by casspop** [comment]
I've been beating my head on a similar problem.  Read this thread and recognized a possibility.

I was using the argparse module.  I removed it from my .py file and gunicorn started working.

**Comment by aiwithshekhar** [comment]
Really helpful!! gunicorn service file, nginx setting everything was perfect but still i was not getting error '**ERR_EMPTY_RESPONSE**'.
Then i changed the proxy buffer, timout nothing worked but as i removed the argparser it worked smoothly.

**Comment by lijiaoyang** [comment]
> 
> 
> well, I have resolved this problem. it ended up that I had ArgumentParser attempting to get arguments from CLI - I commented that out and it works. @benoitc @teemukataja

thx!!

**Comment by cy82359276** [comment]
if uses  gunicorn command  in a  shell script file , the last row must be empty.
