### ISSUE TITLE
Can't find process to restart when trying to set up logrotate with gunicorn3

### ISSUE THREAD

**Issue by arturioxas** [benoitc/gunicorn#1874]
Hi there, I'm using gunicorn to serve API calls from nginx to flask. I've already succesfully deployed all parts and added my log files to nginx logrotate. However, couldn't find default gunicorn logrotate file, tried my own but couldn't find my process in /var/run/ after starting. Tried with both using supervisor and from terminal.

What could be wrong? Is there a default gunicorn3 logrotate file?

**Comment by tilgovi** [comment]
It sounds like you're installing from a distribution's package manager, as `gunicorn` is the command if you install using `pip`. If there is a logrotate file, it might be provided by that downstream package but it is not provided here.

If your package does not provide it already, you can make one. Sending `USR1` to Gunicorn should re-open the log files. See here for all the documentation on signal handling: http://docs.gunicorn.org/en/latest/signals.html

**Comment by benoitc** [comment]
also make sure to correctly set the path of the pid file on launch : https://docs.gunicorn.org/en/stable/settings.html#pidfile

**Comment by benoitc** [comment]
@arturioxas you don't need to. See https://docs.gunicorn.org/en/stable/deploy.html?highlight=supervisor#supervisor for a simple way to launch it.

Supervisor will launch it as root or a privileged user so it should work without any issue.
