### ISSUE TITLE
Is log-config-dict broken?

### ISSUE THREAD

**Issue by fubel** [benoitc/gunicorn#1880]
I tried using the workaround described [here](https://github.com/benoitc/gunicorn/issues/1775) to pass a json dictconfig 

> exec gunicorn -b :8080 --log-config-dict "$(jq -c @json logging_debug.json)" app

But no matter what dictconfig I store in `logging_debug.json`, the command fails. 

> Error: Value is not a dictionary

and then listing the passed dictconfig string. The command also fails on the dictconfig from `gunicorn.glogging.CONFIG_DEFAULTS`: 

> Error: Value is not a dictionary "{\"disable_existing_loggers\":false,\"version\":1,\"handlers\":{\"console\":{\"formatter\":\"generic\",\"stream\":\"sys.stdout\",\"class\":\"logging.StreamHandler\"},\"error_console\":{\"formatter\":\"generic\",\"stream\":\"sys.stderr\",\"class\":\"logging.StreamHandler\"}},\"loggers\":{\"gunicorn.access\":{\"qualname\":\"gunicorn.access\",\"level\":\"INFO\",\"handlers\":[\"console\"],\"propagate\":true},\"root\":{\"level\":\"INFO\",\"handlers\":[\"console\"]},\"gunicorn.error\":{\"qualname\":\"gunicorn.error\",\"level\":\"INFO\",\"handlers\":[\"error_console\"],\"propagate\":true}},\"formatters\":{\"generic\":{\"datefmt\":\"[%Y-%m-%d %H:%M:%S %z]\",\"class\":\"logging.Formatter\"}}}"

Is there a workaround for this?

**Comment by tilgovi** [comment]
JSON is not a Python dict literal. I suspect that where you have values like `true` or `null` you would need `True` or `None`.

**Comment by tilgovi** [comment]
Oh, i see. That was my recommendation. I was wrong. I'll edit that comment to clarify that this won't always work.

**Comment by benoitc** [comment]
Closing the issue because no more activity. Feel free to open a **new** ticket if needed.
