### ISSUE TITLE
Worker timeout set to half the configuration timeout value

### ISSUE THREAD

**Issue by jblanchette** [benoitc/gunicorn#1886]
It appears that the `spawn_workers` method sets the timeout for the worker to half of the configured timeout value.

This seems to have been introduced ~9 years ago in this patch:
https://github.com/benoitc/gunicorn/commit/9e717b8f9c51c8d7a7a2c656a70512829c7b6b20#diff-057c7e5522ab065edb0f33fddc76ddd2R341

can we verify that this behavior is intentional?

it seems the expected behavior is that we set the timeout to be what configuration value is, but will be happy to understand why that's not the case

**Comment by benoitc** [comment]
it's intentional. The reasoning if I remember was that this timeout is only used to not wait to much in the worker. The timeout is also use in the arbiter. Why asking?

**Comment by tilgovi** [comment]
The worker updates a temporary file on an interval to signal to the arbiter that it is alive. If the worker updated the file at the timeout deadline there would be a race between updating the file and the arbiter noticing that the timeout has expired.

We can shorten the worker's heartbeat interval or extend the arbiter's heartbeat tolerance to provide a larger margin for error / race. We chose to shorten the worker's heartbeat interval by dividing it by two.

**Comment by tilgovi** [comment]
None of the worker implementations use this timeout because it is _not_ a request timeout. It is a liveness timeout for the arbiter to kill a worker that is stuck in a bad state. The fact that it works as a request timeout for the sync worker has caused a lot of confusion and there are open issues to make it clearer and/or implement a request timeout separately.

**Comment by tilgovi** [comment]
| None of the worker implementations use this timeout 

They use it to update the temporary file to signal that they are alive, but they don't use it for anything affecting requests, such as timing out a long request.

**Comment by benoitc** [comment]
I realised I have been elliptic :) @tilgovi thanks to be more clear :) Maybe we could add it to an implementation doc ? Thoughts?

**Comment by benoitc** [comment]
@jblanchette you closed the ticket, can you elaborate why?

**Comment by benoitc** [comment]
@BobbyJohansen the worker is asynchronously sending the heartbeat. Its sending depends how muych the event queue used by gevent is busy right now.
