### ISSUE TITLE
preload option hangs the flask app

### ISSUE THREAD

**Issue by gulshan-gaurav** [benoitc/gunicorn#1891]
@benoitc
I have a simple data science micro-service which loads 2 *.gzip* files and 1 *.pkl* scikit-learn model.
When I enable *--preload* option while running multiple worker, the flask app hangs.
I get all load successful messages.
On API request python objects are created using the loaded  *.gzip* files but it hangs without any error message when trying to predict using the *.pkl* model.

**Comment by gulshan-gaurav** [comment]
@benoitc 
In my Code I have Following Steps:
- Loads ML trained model(*.pkl*) and few Python Dictionary Objects
- Request Payload Is Parsed
- Features Generation Step
- Model Prediction Step
- Post Processing Step
- Return Results

When using with preload option , my application shows logs till Feature Generation Step then It hangs for *few minutes*  then I get Worker Timeout Message.
Things are working fine without the preload option.

```
Command To Start the guinicorn server
GUINICORN_WORKER_TIMEOUT is set to 200
CMD gunicorn -b 0.0.0.0:5000 --timeout $GUINICORN_WORKER_TIMEOUT --workers 2 --preload --access-logfile - "app:create_app()"
```
My Terminal Logs
![image](https://user-images.githubusercontent.com/7349925/46997142-8dad7c00-d13c-11e8-9bf6-d8fc31fd50e8.png)

**Comment by benoitc** [comment]
either generation of the feature was taking too long or a timeout is used with request which  is not threadsafe. Closing the issue since ni activity happened since 1 year.
