### ISSUE TITLE
Replace calls to ssl.wrap_socket() with SSLContext.wrap_socket()

### ISSUE THREAD

**Issue by javabrett** [benoitc/gunicorn#1894]
`ssl.wrap_socket()` [is deprecated](https://docs.python.org/3/library/ssl.html#ssl.wrap_socket) and has current and future security limitations:

> Deprecated since version 3.7: Since Python 3.2 and 2.7.9, it is recommended to use the SSLContext.wrap_socket() instead of wrap_socket(). The top-level function is limited and creates an insecure client socket without server name indication or hostname matching.

This issue recommends changing the [calls to this function](https://github.com/benoitc/gunicorn/search?q=wrap_socket&type=Code) per the recommendation above.  This will assist in issues such as #1810 where greater control of SSL socket-wrapping is needed via some new options.

**Comment by berkerpeksag** [comment]
This is a duplicate of #1140.
