### ISSUE TITLE
SIGUSR2 fails to start new master process

### ISSUE THREAD

**Issue by LunarSweeper** [benoitc/gunicorn#1898]
I have `gunicorn (version 19.9.0)` running on Ubuntu 16.04. When I send `USR2` signal to current master process the new process fails to start. I see following entries in syslog:

Oct 16 20:58:13 myserv env[26862]: Traceback (most recent call last):
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/bin/gunicorn", line 11, in <module>
Oct 16 20:58:13 myserv env[26862]:     sys.exit(run())
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
Oct 16 20:58:13 myserv env[26862]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/lib/python3.5/site-packages/gunicorn/app/base.py", line 223, in run
Oct 16 20:58:13 myserv env[26862]:     super(Application, self).run()
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
Oct 16 20:58:13 myserv env[26862]:     Arbiter(self).run()
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 199, in run
Oct 16 20:58:13 myserv env[26862]:     self.start()
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 157, in start
Oct 16 20:58:13 myserv env[26862]:     self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
Oct 16 20:58:13 myserv env[26862]:   File "/home/foo/.local/lib/python3.5/site-packages/gunicorn/sock.py", line 168, in create_sockets
Oct 16 20:58:13 myserv env[26862]:     sock_name = sock.getsockname()
Oct 16 20:58:13 myserv env[26862]: OSError: [Errno 88] Socket operation on non-socket

Is there something wrong in my setup or is this a bug? The unix socket file is there and the old master process along with its workers are still alive and well, but the new process fails to start. My intention is to do graceful reload of Gunicorn which is serving Django application:

kill -s USR2 $oldpid
kill -s WINCH $oldpid
kill -s TERM $oldpid

I have tried to reload my Django app by just sending HUP signal to Gunicorn. Unfortunately, even though Gunicorn master seems to reload new workers the actual Python code will not reload.

**Comment by tilgovi** [comment]
Can you describe how you run gunicorn? Do you use any process supervisor? What arguments do you pass? Do you have a configuration file for it you can share?

**Comment by LunarSweeper** [comment]
@tilgovi Just wanted to add that ideally I would want to just use reload command provided by systemd that will send SIGHUP to main process. Unfortunately that does not seem to reload my Django app at all even though it seemingly restarts all Gunicorn workers.

**Comment by benoitc** [comment]
@LunarSweeper can you increase the log level to debug? also which version are you talking?

about the HUP not reloading the app that weird. Please let me know of above.

**Comment by LunarSweeper** [comment]
@benoitc I'm running `gunicorn (version 19.9.0)` via systemd on Ubuntu 16.04. Below is the log output with debug level. I just sent SIGHUP to main PID. The workers seem to reload fine, but the actual Python code in my Django app does not seem to be reload even though preload option is not enabled.

Sending SIGUSR2 to main PID results in the same log output than what I already posted in my first post in this issue.

Do you see anything strange in the configuration?

```
[2018-10-18 23:18:58 +0300] [3901] [INFO] Handling signal: hup
[2018-10-18 23:18:58 +0300] [3901] [INFO] Hang up: Master
[2018-10-18 23:18:58 +0300] [3901] [DEBUG] Current configuration:
  reload: False
  default_proc_name: config.wsgi
  certfile: None
  do_handshake_on_connect: False
  accesslog: None
  sendfile: None
  spew: False
  errorlog: /local/apps/nano_backend/shared/logs/gunicorn/gunicorn.err
  workers: 5
  logconfig: None
  when_ready: <function WhenReady.when_ready at 0x7f1877fc3f28>
  child_exit: <function ChildExit.child_exit at 0x7f1877ad38c8>
  syslog_prefix: None
  preload_app: False
  keyfile: None
  cert_reqs: 0
  on_exit: <function OnExit.on_exit at 0x7f1877ad3bf8>
  graceful_timeout: 30
  reuse_port: False
  chdir: /local/apps/nano_backend/releases/1539866882
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  paste: None
  threads: 5
  keepalive: 2
  reload_extra_files: []
  limit_request_field_size: 8190
  logger_class: gunicorn.glogging.Logger
  on_starting: <function OnStarting.on_starting at 0x7f1877fc3d08>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f1877ad3510>
  pre_exec: <function PreExec.pre_exec at 0x7f1877ad3620>
  pidfile: /run/gunicorn/pid
  disable_redirect_access_to_syslog: False
  ciphers: TLSv1
  proxy_allow_ips: ['127.0.0.1']
  backlog: 2048
  config: /etc/gunicorn.conf
  limit_request_line: 4094
  reload_engine: auto
  initgroups: False
  pythonpath: None
  max_requests_jitter: 0
  daemon: False
  group: 1003
  post_fork: <function Postfork.post_fork at 0x7f1877ad31e0>
  worker_int: <function WorkerInt.worker_int at 0x7f1877ad3400>
  tmp_upload_dir: None
  limit_request_fields: 100
  worker_tmp_dir: None
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  syslog: False
  syslog_facility: user
  forwarded_allow_ips: ['127.0.0.1']
  proxy_protocol: False
  raw_paste_global_conf: []
  loglevel: debug
  ca_certs: None
  check_config: False
  max_requests: 0
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1877ad3ae8>
  enable_stdio_inheritance: False
  statsd_prefix:
  proc_name: None
  post_request: <function PostRequest.post_request at 0x7f1877ad37b8>
  bind: ['unix:/run/gunicorn/socket']
  capture_output: False
  syslog_addr: udp://localhost:514
  statsd_host: None
  on_reload: <function OnReload.on_reload at 0x7f1877fc3e18>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f1877ad32f0>
  worker_class: sync
  timeout: 30
  pre_fork: <function Prefork.pre_fork at 0x7f1877ad30d0>
  pre_request: <function PreRequest.pre_request at 0x7f1877ad3730>
  logconfig_dict: {}
  ssl_version: 2
  suppress_ragged_eofs: True
  worker_connections: 1000
  raw_env: []
  user: 1003
  umask: 0
  worker_exit: <function WorkerExit.worker_exit at 0x7f1877ad39d8>
[2018-10-18 23:18:58 +0300] [3926] [INFO] Booting worker with pid: 3926
[2018-10-18 23:18:58 +0300] [3930] [INFO] Booting worker with pid: 3930
[2018-10-18 23:18:58 +0300] [3927] [INFO] Booting worker with pid: 3927
[2018-10-18 23:18:58 +0300] [3928] [INFO] Booting worker with pid: 3928
[2018-10-18 23:18:58 +0300] [3929] [INFO] Booting worker with pid: 3929
[2018-10-18 20:18:58 +0000] [3907] [INFO] Worker exiting (pid: 3907)
[2018-10-18 20:18:58 +0000] [3909] [INFO] Worker exiting (pid: 3909)
[2018-10-18 20:18:58 +0000] [3911] [INFO] Worker exiting (pid: 3911)
[2018-10-18 20:18:58 +0000] [3910] [INFO] Worker exiting (pid: 3910)
[2018-10-18 20:18:59 +0000] [3905] [INFO] Worker exiting (pid: 3905)
```

**Comment by LunarSweeper** [comment]
@benoitc My Django application code path is a symlink to actual path containing the updated code. Does this cause any problems?

**Comment by LunarSweeper** [comment]
Apparently there was something borked in my OS installation. Reinstalled everything from scratch and now it seems to reload on SIGHUP.

**Comment by tilgovi** [comment]
Thanks for following up!
