### ISSUE TITLE
`python setup.py bdist_rpm` raises error

### ISSUE THREAD

**Issue by millefalcon** [benoitc/gunicorn#1900]
Steps to reproduce
-------------------------
1. wget https://files.pythonhosted.org/packages/47/52/68ba8e5e8ba251e54006a49441f7ccabca83b6bef5aedacb4890596c7911/gunicorn-19.9.0.tar.gz
2. tar -xvzf gunicorn-19.9.0.tar.gz
3. cd gunicorn-19.9.0
4. python setup.py bdist_rpm

The error raised:
-----------------------
[root@ip-172-31-42-156 gunicorn-19.9.0]# python setup.py bdist_rpm
running bdist_rpm
error: error in 'install_script' option: 'rpm/install' does not exist or is not a file

Please let me know, if you need anything more.

**Comment by han-ish** [comment]
Looks like it is only missing from tarball.

**Comment by han-ish** [comment]
And one question, did you guys make this python3 only ?

**Comment by tilgovi** [comment]
There has not been a release since, but `master` has moved to Python 3 only.

**Comment by tilgovi** [comment]
@benoitc @berkerpeksag should we continue to have distro packaging upstream here? It might make sense to either include it in the tarball or make it a downstream concern completely.

**Comment by han-ish** [comment]
@tilgovi Yeah, Okay.

**Comment by benoitc** [comment]
@tilgovi not sure what you mean by "should we continue to have distro packaging upstream here? ", you mean handling rpms ourselves? I don't think we should these days, this should rather be handled by the packager. Do we know any project that does it still?

**Comment by millefalcon** [comment]
I think, the packager should handle this.

**Comment by millefalcon** [comment]
Anyway, that file was not in the tarball which is why i just raised the
concern

**Comment by benoitc** [comment]
@tilgovi i would remove its support

**Comment by tilgovi** [comment]
Looking at the Fedora packaging, I don't think `bdist_rpm` is even used. I'll remove it. 

https://src.fedoraproject.org/rpms/python-gunicorn/blob/master/f/python-gunicorn.spec

**Comment by tilgovi** [comment]
https://github.com/benoitc/gunicorn/pull/2199

**Comment by benoitc** [comment]
Thanks! fixed via 20774b8331dfb76845bf4a3e4c3c3d4a9d6a8efb
