### ISSUE TITLE
my flask app is blocked when I use gunicorn and multiprocessing

### ISSUE THREAD

**Issue by chenxianpao** [benoitc/gunicorn#1903]
Is it not supported to use multiprocessing library in flask app when use gunicorn as container?
My flask app is blocked at multiprocessing.queues.Queue.get(). I heartd that multiprocessing can not be used togather with gunicorn, Is this real?

**Comment by benoitc** [comment]
maybe, which error do you have ? How do you start the queue?

**Comment by benoitc** [comment]
no feedback since. closing the issue.
