### ISSUE TITLE
500 internal error ONLY when running gunicorn as a service

### ISSUE THREAD

**Issue by innerself** [benoitc/gunicorn#1908]
Hello! I have the same issue as in #1059 .

[Traceback](https://github.com/benoitc/gunicorn/files/2531305/gunicorn_fetch_500.txt)

What else can I do to help you reproduce and solve this?

**Comment by ifduyue** [comment]
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

It's a selenium exception, not from gunicorn
