### ISSUE TITLE
log-config-dict cli option is broken, can't work as coded.

### ISSUE THREAD

**Issue by rthille** [benoitc/gunicorn#1909]
Despite https://github.com/benoitc/gunicorn/issues/1880 being closed, the `--log-config-dict` cli option is broken and can't work as coded because the CLI's `type` member isn't set, so the dict_validator tries to validate a string (what's coming from ARGV), unconverted, and that fails.
I tried hacking the code to use `type = json.loads` so that the string would be converted to a dict by ArgParse, but couldn't make that work either. (I think that *can* work, I was just screwing something up I'm guessing).

**Comment by rthille** [comment]
Just try starting gunicorn with the `--log-config-dict` option and some argument.  It will always fail.
```
# gunicorn --log-config-dict '{}' integrator.settings.wsgi:application --bind=0.0.0.0:8080 --workers=3 --config python:cariumlib.djangolib.gunicorn_config
Error: Value is not a dictionary: {} 
# gunicorn --log-config-dict {} integrator.settings.wsgi:application --bind=0.0.0.0:8080 --workers=3 --config python:cariumlib.djangolib.gunicorn_config
Error: Value is not a dictionary: {} 
# 
```
There's no way to pass a *python dict* from the shell. You can only pass a string, and the code in gunicorn isn't setup to do the conversion from the string representation of the dict to the python dict object.

**Comment by benoitc** [comment]
afaik i'm not sure what is expected to pass on the command line there. Giving a dict as a string seems odd. cc @berkerpeksag @tilgovi

**Comment by rthille** [comment]
It _seems_ like something like a json-encoded dict should be accepted:
```
gunicorn --log-config-dict "{'formatters': {'verbose': {'format': '\n%(levelname)s %(process)d %(asctime)s %(name)s %(pathname)s:%(lineno)d %(message)s'}},'handlers': {'console': {'class': 'logging.StreamHandler','formatter': 'verbose'}},'root': {'level': 'WARNING', 'handlers': ['console']}}"
```

**Comment by berkerpeksag** [comment]
I think `logconfig_dict` meant to be used in a configuration file. We need a way to disable a setting to be used via CLI.

In any case, we need to improve the `logconfig_dict` documentation with a note about using it via a configuration file and provide an example to show how to extend the logging configuration.

**Comment by berkerpeksag** [comment]
By the way, the following configuration file worked for me:

```py
logconfig_dict = {
    'formatters': {
        'verbose': {
            'format': 'XXX %(levelname)s %(process)d %(asctime)s %(name)s %(pathname)s:%(lineno)d %(message)s',
        },
        'generic': {
            'format': '%(asctime)s [%(process)d] [%(levelname)s] %(message)s',
            'datefmt': '[%Y-%m-%d %H:%M:%S %z]',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'error_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'generic',
            'stream': 'ext://sys.stderr',
        },
    },
    'version': 1,
    'disable_existing_loggers': False,
}
```

It can be tested as follows:

```sh
$ cd gunicorn/examples
$ gunicorn -c ../conf.py test:app
```

**Comment by javabrett** [comment]
CLI option was added in c5ae962dfa3c9a84dfef3af386c7b4f282d02e6e .  See also #1775.  Probably needs comment/review/docnote from @tilgovi as to how the CLI option can/should work, or if it can't it is easily reverted.

**Comment by benoitc** [comment]
i would go for (1) , can you provide a PR for it?

**Comment by ruloweb** [comment]
In the version `20.0.4` I can see the `--logging-config-dict` option, is this going to be removed?

**Comment by tilgovi** [comment]
https://github.com/benoitc/gunicorn/pull/2476
