### ISSUE TITLE
in the pressure test,cpu usage suddenly fall for a moment，it leads to that requests were time out 

### ISSUE THREAD

**Issue by naah69** [benoitc/gunicorn#1915]
i user gunicorn and thrift to create a service that provide RPC interface.
but when it was in pressure test,
cpu usage suddenly falled for a moment(about 10 seconds),then lots of requests were time out. 
then all of these were back to normal.but after several minutes.it repeated again.
i use gevent model and 6 workers.
can you help me ?

**Comment by tilgovi** [comment]
This is not something I expect we can debug without more information. If you have a chance to instrument your code or Gunicorn, or can trace the syscalls happening when this happens, we might be able to help. Does this happen consistently? How many workers, how many hardware threads on the machine? Have you tried other worker counts?  Is there any log message?

Please help us by investigating the issue more deeply, if you can.

**Comment by benoitc** [comment]
no feedback that can help to figure what is happening. closing the issue.
