### ISSUE TITLE
OpenSSL/libssl.so.1.0.0 conflict with Py3.7/MySqlClient libssl.so.1.1.1 one

### ISSUE THREAD

**Issue by classifaddict** [benoitc/gunicorn#1920]
Hi,
Py3.7/MySqlClient (1.3.13) requires libssl.so.1.1.1 to run but it prevents Gunicorn 19.9.0 from running.
Here are the error reported by systemctl trying to start my Gunicorn service:
gunicorn[86013]: from gunicorn.config import Config, get_default_config_file
gunicorn[86013]: File "/data/ipcpubprep/venv/lib/python3.7/site-packages/gunicorn/config.py", line 18, in <module>
gunicorn[86013]: import ssl
gunicorn[86013]: File "/data/ipcpubprep/venv/lib/python3.7/ssl.py", line 98, in <module>
gunicorn[86013]: import _ssl             # if we can't import it, let the error propagate
gunicorn[86013]: ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Is there a solution or do I have to wait for next Gunicorn version to be able to switch from Py3.6 to 3.7?

**Comment by jamadden** [comment]
You're using some Linux distributions package manager to install these packages?

**Comment by classifaddict** [comment]
No, I'm using conda and pip.

**Comment by jamadden** [comment]
This looks to me like a packaging problem specific to Conda and/or combining it with pip. (I can't claim to really understand conda but I didn't think it was supposed to be mixed with pip; I thought it was supposed to be 'conda install XXX'.)

**Comment by classifaddict** [comment]
Maybe but a question remains: Is Gunicorn linked to libssl.so.1.0.0 or could it be used with libssl.so.1.1.1 and how?

**Comment by jamadden** [comment]
No, gunicorn is *not* linked to `libssl.Any.Thing`. The file `/data/ipcpubprep/venv/lib/python3.7/ssl.py` is a standard part of the Python interpreter, as is the `_ssl.so` that file is trying to import. Something has broken your interpreter.

**Comment by classifaddict** [comment]
OK, I'm going to try to improve this mess.
Thanks!

**Comment by jamadden** [comment]
If you agree this problem is outside gunicorn, could you please close this issue?
