### ISSUE TITLE
 Django: Deploying Gunicorn and Channels

### ISSUE THREAD

**Issue by alekaizer** [benoitc/gunicorn#1921]
Hi y'all,

I set up an env lately that involves HTTP and WebSocket over Django and Channels, and when it was time to go in production I realised how little documentation there are about the subject.

The architecture includes Celery, for background tasks as well.

There is a documentation to deploy Channels -> [https://channels.readthedocs.io](url)
There is a documentation to deploy Gunicorn -> [http://docs.gunicorn.org](url)

But there seems to be a problem with those 2 documentations.

Channels requires to run **Daphne** for the Websocket, then to run **manage.py runworker** to handle the requests and tasks, pretty straight forward.

Gunicorn also docmentation is also straight forward, couple of lines and your set

And there lies what I think to be a problem:

1- **Runworker** is already running the app (let's say there are 4 workers)
2- **Gunicorn** will run the app as well (let's say 4 workers as well)
3- **Celery** will run the app as well (1 worker)

In my humble(maybe flawed) opinion, isn't that too overwhelming ?

Shouldn't Gunicorn be able to communicate with daphne/channels, to handle the tasks sent from it ?
To me, it seems like running 9 instances of the app, when there are 4 instances only replying to websockets.

Isn't there any other way to make at least Gunicorn and Channels work together ?

**Comment by tilgovi** [comment]
That would certainly be nice, but to my knowledge no one has done any work to integrate channels into Gunicorn. If you come up with anything, please let us know!

**Comment by benoitc** [comment]
there is a ticket for asgi support. support will land soon. closing this issue as it's superseded by more generic support of ashi.
