### ISSUE TITLE
why can't import _ssl?

### ISSUE THREAD

**Issue by zenglingyu** [benoitc/gunicorn#1922]
gunicorn --bind 0.0.0.0:8000 wsgi:app
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 7, in <module>
    from gunicorn.app.wsgiapp import run
  File "/usr/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/usr/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 14, in <module>
    from gunicorn.config import Config, get_default_config_file
  File "/usr/python/lib/python3.6/site-packages/gunicorn/config.py", line 18, in <module>
    import ssl
  File "/usr/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

based on centos7 
have install python3.6
when i into command line import ssl is ok,but when i test this command "gunicorn --bind 0.0.0.0:8000 wsgi:app" for test was done.

**Comment by ifduyue** [comment]
How did you install Python3.6?
Looking at your logs, python path located in /usr/python, was it manually compiled and installed? I guess you failed to build _ssl module.

**Comment by javabrett** [comment]
Please describe how you obtained/installed Python. Maybe you installed from source and omitted the `https://stackoverflow.com/a/5128893/452210` option.

**Comment by benoitc** [comment]
It means that didn't install Python with ssl support on your machine. Either use a package or follow the advices above :)

Closing the issue as it's not related to gunicorn.

**Comment by hemantmayatra** [comment]
I had same problem.
My python version is 3.7 (64 bit). I just relaunched installation, and clicked 'Repair'.
After repair i relaunched PyCharm, and the problem was solved.
