### ISSUE TITLE
sslclientverify/sslclientcert headers are getting removed from the request

### ISSUE THREAD

**Issue by jsjeannotte** [benoitc/gunicorn#1930]
Hi! 
I used to have Apache handling the Mutual TLS authentication for my web service, fronting Gunicorn/Flask. When the request was getting to Flask, I had access to the `sslclientverify` and `sslclientcert` headers, so that I could perform additional autz. I recently switched to using gunicorn directly for the Mutual TLS negotiation. It works, but I no longer have access to the `sslclientverify`/`sslclientcert` headers. I couldn't find any settings to whitelist/pass these headers, nor can I figure out where in the code are they getting stripped (they don't seem to reach `message.Message.parse_headers()`)

FYI, on Apache, these are passed this way:
```
RequestHeader set SSLCLIENTCERT "%{SSL_CLIENT_CERT}s"
RequestHeader set SSLCLIENTVERIFY "%{SSL_CLIENT_VERIFY}s"
```

Any idea how I can make this work?

**Comment by jamadden** [comment]
AFAICS, those values [are Apache specific](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html), not a standard part of HTTPS. An implementation would have to take special steps to hook into the SSL layer and promote them up to the HTTP layer. 

The WSGI standard does mention that WSGI implementations [may provide Apache SSL variables](https://www.python.org/dev/peps/pep-3333/#environ-variables), but it's optional (and offhand I can't think of any that actually do); specifically relying on them is documented as non-portable.

gunicorn's [SSL support](https://github.com/benoitc/gunicorn/blob/91974f0f44080fdd6f2885832d101474671c4b9b/gunicorn/workers/sync.py#L128) simply uses the standard library to handle wrapping sockets (or the standard method provided by gevent/gaiohttp/etc), which don't necessarily expose any details about the SSL process.

So there's unlikely to be a way to generically duplicate what you used to do that works with all worker types. You might find something that you can pull apart that works with a given worker (e.g., by looking at `environ['wsgi.input']` and checking to see if it happens to be an [SSLSocket](https://docs.python.org/3/library/ssl.html#ssl-sockets)), but I'm not aware of a supported way to access that information.

**Comment by jsjeannotte** [comment]
@benoitc After performing additional performance optimizations on my service, I migrated to a full async approach using aiohttp without gunicorn and figured out how to get the SSL context:
```
ssl_object = request.transport.get_extra_info('ssl_object')
```
Which returns a https://docs.python.org/3/library/ssl.html#ssl.SSLObject. 
So I'm assuming that by fronting my old Flask app with gunicorn, I'm loosing this context and cannot access it from Flask. If I'm wrong and there is a way to access it, let me know, but at the moment, I worked around the issue by using aiohttp.

But I'm still using gunicorn in other projects and will need similar sslobject inspection on those as well in the near future, so if there is a way to do this, it would prevent me from having to migrate all those projects to aiohttp. 

Merci et bonne journée!

**Comment by benoitc** [comment]
afaik if it's all what you need you already have access to the socket in the wsgi environment `gunicorn.socket` . I think you can get  the environ using the `request_context` callback in flask but that a long time I used it.

good luck with aiohttp. I think you will enjoy the coming python3 async worker in gunicorn though ;)

**Comment by benoitc** [comment]
http://flask.pocoo.org/docs/1.0/api/?highlight=request_context#flask.Flask.request_context

from there if the socket is ssl then you can do what you need.

**Comment by jsjeannotte** [comment]
Thanks @benoitc. I'll take another look when I open up the hood on my other projects. Feel free to close this issue for now.
