### ISSUE TITLE
(forum) logging from each worker

### ISSUE THREAD

**Issue by amitron72** [benoitc/gunicorn#1941]
A question from a new user regarding logging from workers:

I have a logging configuration where my app is logging to a file appender.
Therefore all the workers are using the same logging configuration and they all send logs to the same file.

Python documentation says logging from multiple processes to a single file is not supported::
https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes

> Logging to a single file from multiple processes
> Although logging is thread-safe, and logging to a single file from multiple threads in a single process is supported, **logging to a single file from multiple processes is not supported**, because there is no standard way to serialize access to a single file across multiple processes in Python. If you need to log to a single file from multiple processes, one way of doing this is to have all the processes log to a SocketHandler, and have a separate process which implements a socket server which reads from the socket and logs to file. (If you prefer, you can dedicate one thread in one of the existing processes to perform this function.) This section documents this approach in more detail and includes a working socket receiver which can be used as a starting point for you to adapt in your own applications.

Is there a best practice to work around this logging issue?
Is it possible to make a logging configuration where each worker sends logs to a different file?
do you suggest to implement this using the SocketHandler as the python manual suggests?

Thank you

**Comment by d4tech** [comment]
Use the gunicorn [pre_fork](http://docs.gunicorn.org/en/stable/settings.html#post-fork) server hook to set the `worker.log` attribute to your preferred logger object.

**Comment by tilgovi** [comment]
In practice it is often not an issue. When log messages are not larger than the OS page size, they typically are logged in one system call and they do not get mixed together.

If you have very high volumes of requests and large log lines that make this a problem in practice, the best practice is to move to a network logging system using the built-in syslog support or any Python logger of your choice.

**Comment by benoitc** [comment]
closing the issue as answered.
