### ISSUE TITLE
Cannot find package when running a Flask app with Gunicorn

### ISSUE THREAD

**Issue by ionicc** [benoitc/gunicorn#1942]
I am hosting a flask app on DigitalOcean using Gunicorn with Nginx. Now, When I run the server on Flask's development server (app.run()) the ffmpeg package installed on the Ubuntu 18.04 gets detected and the whole app works perfectly.
Now, When the app runs through Gunicorn, The server can't detect ffmpeg. I'm seriously confused about why is this even happening.

**Comment by benoitc** [comment]
make sure your application is on the PYTHON_PATH when gunicorn is loaded. Either by [loading your virtualenv](http://docs.gunicorn.org/en/stable/deploy.html#using-virtualenv) or manually using the `pythonpath` setting: http://docs.gunicorn.org/en/stable/settings.html#pythonpath
