### ISSUE TITLE
`--capture-output` abnormal when using systemd to manage gunicorn process

### ISSUE THREAD

**Issue by jkklee** [benoitc/gunicorn#1944]
I want to capture output in my application generated by `print()`.

At first, I start gunicorn directly: `gunicorn server:app -b 127.0.0.1:7000 -w 2 --chdir=/data/ --access-logfile=logs/server_access.log --error-logfile=logs/server_err.log --capture-output -u nobody -g nobody -D`
And when I make a request, the extra output appeared in the errorlog real-time.

Then, I try to use the systemd to manage gunicorn, like that
```
[Unit]
Description=The gunicorn server for spider project
After=network.target

[Service]
ExecStart=gunicorn server:app -b 127.0.0.1:7000 -w 2 --pid /run/gunicorn.pid --chdir=/data/ --access-logfile=logs/server_access.log --error-logfile=logs/server_err.log --capture-output -u nobody -g nobody 
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
KillMode=process
Restart=on-failure
RestartSec=1s

[Install]
WantedBy=multi-user.target
```
But the extra output in the errorlog become no real-time, it looks like there is a buffer somewhere, untile when buffer is full, it log into the errorlog.

Can someone help to explain why the different is comming? Thanks

**Comment by pvadam** [comment]
Does it help if you set `PYTHONUNBUFFERED=TRUE` as an environment variable?

For me it does.

**Comment by jkklee** [comment]
@pvadam Thanks ,it works!

**Comment by benoitc** [comment]
closing as it has been resolved.

**Comment by benoitc** [comment]
@jkklee btw you also have the [enable-stdio-inheritance](http://docs.gunicorn.org/en/stable/settings.html#enable-stdio-inheritance) setting to print everything from the workers.
