### ISSUE TITLE
Request header (xx_xx) was filtered by gunicorn

### ISSUE THREAD

**Issue by brandonbai** [benoitc/gunicorn#1946]
- Use the following code to get the data in the request header, and not get the value (the client also uses __access_token__ )

   ```
   access_token=request.headers.get_all("access_token")
   ```

- Use the following code to get the data in the request header, you can get the value (the client also uses __access-token__ )

   ```
   access_token=request.headers.get_all("access-token")
   ```

Does this require additional configuration?

I did not find the relevant configuration in the [example_config.py](https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py).

Personally think it should be similar to nginx's configuration __underscores_in_headers__ , but did not find a similar configuration for gunicorn.

**Comment by benoitc** [comment]
gunicorn do not filter any header, it just pass what the application gives to  it. Are you sure these headers are not filtered before they arrived on gunicorn?

**Comment by benoitc** [comment]
@brandonbai I'm not sure what does request or flask for it, but Gunicorn doesn't do anything header filtering it just pass what it received or what is given by the application. Maybe you can trace the headers before they are given to gunicorn to check if `access-token` is really set?

**Comment by benoitc** [comment]
@brandonbai can you share with me the environ you get on the server side from the wsgi object?

**Comment by brandonbai** [comment]
@benoitc 
- os: ubuntu 16.04
- gunicorn: 19.9.0
- flask: 1.0.2

gunicorn config:

```
import multiprocessing

bind = "127.0.0.1:8090"

workers = multiprocessing.cpu_count() * 2 + 1

proc_name = 'app'

```

**Comment by brandonbai** [comment]
@benoitc
When I using the configuration 
```
--access_log_format %({Header}i)s 
```
in the [document](http://docs.gunicorn.org/en/latest/settings.html#access-log-format), the console outputs "-"

**Comment by benoitc** [comment]
@brandonbai `Header` should be an header name, eg. `{Server}i` .

anyway can't you print the response headers from flask? what return curl -I YourGunicornUrl ? Maybe look if there is any error in debug mode. Again gunicorn doesn't filter the headers.

**Comment by brandonbai** [comment]
@benoitc 

The problem is solved. It turns out that there is still nginx in front.

You said it is very correct, thank you for your help.

pelase close it.
