### ISSUE TITLE
decide which python 3 version we should support

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1949]
what version of Python 3 should we support starting on gunicorn 20? We need to have a minimum. cc @tilgovi @berkerpeksag

**Comment by berkerpeksag** [comment]
I'd say 3.5 is a good starting point. It will be officially supported by the Python team until September 2020. See https://devguide.python.org/#status-of-python-branches for a full list of Python versions maintained by the Python team.

**Comment by benoitc** [comment]
@berkerpeksag i suggest to remove our tests on python 3.4 then. What do you think?

**Comment by javabrett** [comment]
Given Python 3.6 is now 2yo, perhaps it is also (as well as 3.5) a candidate for minversion for v20?

**Comment by rafaelsierra** [comment]
gunicorn v19 is now 5 years old, if we can expect that kind of life time for v20, then it would mean supporting python 3.5 for 4 years after it has been retired.

I agree with @javabrett that 3.6 is a good candidate

**Comment by tilgovi** [comment]
I have no strong opinion here. How do we make a decision?

**Comment by javabrett** [comment]
There's been no objection I know of to min 3.6. Are there any 3.7 must-haves? 3.5 is old but are the any must-support criteria?

If those questions yield nothing I suggest lock in 3.6 and anyone who needs to object can do so.

**Comment by berkerpeksag** [comment]
Most hybrid Django projects target Python 3.6 since Django 1.11 is the last version that supports both Python 2 and Python 3. At $WORK, we are planning to use Gunicorn 20 on our Python 3.6 deployment. I think Python 3.6 would be good enough to help projects migrating from Python 2 and Python 3.

**Comment by benoitc** [comment]
let's go for 3.6. and make this release :)

This is the last call for anyone if you want to add something for this release, please do it today. I will make a release on wednesday.

**Comment by benoitc** [comment]
python >= 3.5 is actually supported. i think we can remove support for it in 21 release in june. closing that issue then. thanks all for the feedback and comments!
