### ISSUE TITLE
reloader issue

### ISSUE THREAD

**Issue by veonua** [benoitc/gunicorn#1951]
```
File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/reloader.py", line 42, in run
    for filename in self.get_files():
  File "/usr/local/lib/python3.7/site-packages/gunicorn/reloader.py", line 30, in get_files
    for module in list(sys.modules.values())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/reloader.py", line 31, in <listcomp>
    if hasattr(module, '__file__')
  File "/usr/local/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by jamadden** [comment]
Can you provide some more context? Presumably you have a module that has a `__file__` that's not a string (it's probably `None`). Are you using exotic importers, loading from zip files, ...?

**Comment by veonua** [comment]
gunicorn -b 0.0.0.0:8080 main:api

it must be main(.py)

**Comment by berkerpeksag** [comment]
I think this has already been fixed in https://github.com/benoitc/gunicorn/commit/30554fdb4fdc169997b234e49ab93655a289d76d in master? Could you try the master branch?

```sh
$ pip install -U git+https://github.com/benoitc/gunicorn.git#egg=gunicorn
```

**Comment by benoitc** [comment]
closing issue as it seems to be resolved: no answer from the OP since. Thanks all!

**Comment by zgoda** [comment]
To verify this is indeed related to inotify reloader and was fixed with https://github.com/benoitc/gunicorn/commit/30554fdb4fdc169997b234e49ab93655a289d76d run app with `--reload-engine poll` and see if this happens.
