### ISSUE TITLE
Oracle connection errors after restart with preload option

### ISSUE THREAD

**Issue by jobec** [benoitc/gunicorn#1953]
I'm getting all sorts of weird errors when running Django + Oracle as the database + [Session pooling](https://cx-oracle.readthedocs.io/en/latest/session_pool.html) combined with the `--preload` option.

Some of the errors are:
```
cx_Oracle.DatabaseError: ORA-24371: data would not fit in current prefetch buffer
cx_Oracle.OperationalError: ORA-01013: user requested cancel of current operation
cx_Oracle.DatabaseError: ORA-03106: fatal two-task communication protocol error
django.db.utils.OperationalError: ORA-03113: end-of-file on communication channel
```

Removing the `--preload` option makes the errors go away.

**Comment by jamadden** [comment]
If you're establishing the database connections *before* the server forks, then in each child worker you will need to close the connections and re-open brand new ones (i.e., in `post_fork`) before continuing. 

It's almost certainly not safe to share the same database socket between different processes; any locks that they have are per-process, and so don't work, with the result being that messages are interleaved in unexpected ways leading to those sorts of failures.

**Comment by jobec** [comment]
I don't expect Django to already open a connection before gunicorn forks (But in reality I have no clue about the order of events.). It opens a connection when a requests comes in. My code also creates the pool the first time a connection is needed.

I also don't think it's worth all the effort of doing what you mentioned. Removing the preload is the most easy solution.

This issue is mostly to make other people aware of how to potentially fix it if they come across the same errors. Because I spent weeks searching for it, deep diving in tracing the oracle driver.

**Comment by tilgovi** [comment]
Thanks you both! I'll close the issue since there seems to be no action necessary.

**Comment by tilgovi** [comment]
If you find out that Django is opening a connection during initialization, please share your findings in case other people have a similar configuration.
