### ISSUE TITLE
Forum - Async worker timeout

### ISSUE THREAD

**Issue by elishaikatz** [benoitc/gunicorn#1955]
Timeout documentation has the following sentence:
"For the non sync workers it just means that the worker process is still communicating and is not tied to the length of time required to handle a single request."

So why does a gevent worker is getting a timeout after timeout time + graceful timeout time?

**Comment by tilgovi** [comment]
If your gevent worker is timing out it is probably because you are performing some operation that blocks the gevent loop. Commonly this happens in C extension modules.

**Comment by benoitc** [comment]
closing the ticket as it has been answered :) if you have more questions let us know :)
