### ISSUE TITLE
When given few resources gunicorn will spawn worker threads indefinitely

### ISSUE THREAD

**Issue by irufus** [benoitc/gunicorn#1956]
Docker base container: python:3.7-alpine

I am using nomad to deploy my container. In my configuration I noticed that if you give the container too few resources gunicorn (For example 20 mhz and 20 mb) it will cause gunicorn to continue to spin up worker processes indefinitely which will impact nomad's gui performance to the point it becomes unrepsonsive.

**Comment by javabrett** [comment]
Are values that small meaningful for such a container? Do you hope to run with such small values, or is this an experiment?

Are you embedding?

**Comment by tilgovi** [comment]
Related to #1937 and any solution there should solve for both.

**Comment by benoitc** [comment]
just to clarify `gunicorn will spawn worker threads`, do you mean workers as in `-w N`  options or with the `--threads setting`? How do you launch it?

**Comment by irufus** [comment]
> just to clarify `gunicorn will spawn worker threads`, do you mean workers as in `-w N` options or with the `--threads setting`? How do you launch it?

`gunicorn --workers=2 -b 0.0.0.0:5000 app:app`

>Are values that small meaningful for such a container? Do you hope to run with such small values, or is this an experiment?

It was an accident I came across.  Although it is strange that it would try to draw upon more resources than given. 

>Are you embedding?
No. We're trying to implement microservices but not on that level.

**Comment by benoitc** [comment]
a default python instance itself will use at least 20MB unless you're using a specific python. I would not run an http server with less than 64MB of ram. If you have 1 core also run it with the preload mode to reuse the memory.
