### ISSUE TITLE
Up-for-grabs issues on gunicorn?

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1973]
We should  make it easier for people to get started, so I propose to highlight  a list of issues on GitHub tagged with a new label: `up-for-grab` replacing the `Help Wanted` to make it more clear. and describe it on the readme. Thoughts?

**Comment by tilgovi** [comment]
Yes.

**Comment by tilgovi** [comment]
React has "good first issue".

**Comment by javabrett** [comment]
I also like `good first issue`/`Good First Issue`, and it seems like GitHub lore.  As long as it is applied judiciously.

It's (mostly) a subset of `Help Wanted` - which I often think exists to mean "help wanted from anywhere, non-project-member-contributors etc." - noting that GitHub doesn't allow issues to be assigned-to non-members.

Are there details on the lack-of-clarity or any misuse of `Help Wanted` here currently?  Seems OK to me.  Add `Good First Issue` if trying to make it easy for newcomers to chip-in.

New label would need to be pluralised if used: `up-for-grabs` is correct.

**Comment by di** [comment]
Github specifically suggests `help wanted` or `good first issue` labels: https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

**Comment by benoitc** [comment]
I would go for having both "help wanted" and "good first issue"  then as they seem to cover 2 different kind of issues where people would help. Thoughts?

**Comment by tilgovi** [comment]
Perfect for me.

**Comment by benoitc** [comment]
done both issues have been updated. We may want to check if we already have some good first issue. I will update the contributing doc separately. 

<img width="1103" alt="screenshot 2019-02-08 at 14 21 31" src="https://user-images.githubusercontent.com/14498/52480741-dd60f900-2bac-11e9-84b9-3b72ccd11159.png">

**Comment by benoitc** [comment]
also nitpicking but i may change the color scheme, this one is quite agressive ;)
