### ISSUE TITLE
Gunicorn runs and causes this error please help

### ISSUE THREAD

**Issue by alfonsomarineparts** [benoitc/gunicorn#1982]
# 504-Gateway-Time-out-nginx-1.10.3-Ubuntu-
504 Gateway Time-out nginx/1.10.3 (Ubuntu) On the Putty console gunicorn runs and causes this error please help

**Comment by benoitc** [comment]
can you provide more information to reproduce this etror? any log files from  gunicorn? how do you launch it? what does your application?

**Comment by javabrett** [comment]
ping @alfonsomarineparts

**Comment by benoitc** [comment]
closing the issue since no feedback given. thanks.
