### ISSUE TITLE
gunicorn using the same work process for all requests

### ISSUE THREAD

**Issue by jayhjha** [benoitc/gunicorn#1984]
I am running gunicorn with the gevent worker type and 3 workers on a 2 core system. I send about 15 concurrent requests to the server.
The avg time for each request when run individually is 20 seconds, but it goes up to 30 when run concurrently.
Looking at the logs for gunicorn, I can see that each request is being handled by the same worker (tracked using process id in logs). Could this be a possible reason why the avg time is so much higher? Since the same process is handling all requests, presumably there's constant context switches. How do I ensure that all the worker processes are used?
I tried increasing the number of workers, but that wasn't much help.

**Comment by tilgovi** [comment]
See whether the `--reuse-port` option works for you. That option enables new behavior that provides fairer distribution of requests when multiple processes are accepting connections on the same socket.

Background reading: https://lwn.net/Articles/542629/

**Comment by hijha** [comment]
@tilgovi 
That didn't help. For reference this is how I'm starting gunicorn:

`/usr/local/bin/gunicorn --pid /run/gunicorn/pid --bind unix:/run/gunicorn/socket myapp.wsgi:application -k gevent -w 3 --worker-connections 1000 --reuse-port --access-logfile /var/log/gunicorn/access.log --access-logformat "%(h)s %(l)s %(u)s %(t)s %(r)s %(s)s %(b)s %(f)s %(a)s %(p)s"`

**Comment by tilgovi** [comment]
What version of `gevent`?

**Comment by hijha** [comment]
It was 1.2.2 before, I just upgraded it to 1.4.0

**Comment by tilgovi** [comment]
No help?

**Comment by hijha** [comment]
No, I can still see the same process being used for all requests.

**Comment by hijha** [comment]
Some clarification on how these requests work:
When I get a request (let's say to  /test1), the first step is to do some verification. To do this I make a request to the /verify from within /test1. Based on the response from /verify, there are next steps. Similarly, the request to /test2 will make another request to /verify and then move on to the next steps.
I have 15 or so different endpoints (/test1, /test2, etc.).
I use asyncio.ensure_future and asyncio.gather to make all these 15 requests at the same time.

In the gunicorn logs, I can the request for /verify coming from different 'tests' and for these requests, diferent processes are used but the original requests to /test1, /test2, .. are all to the same worker.

I hope I have kinda clarified how this works.

**Comment by hijha** [comment]
Any updates/suggestions on this?

**Comment by benoitc** [comment]
do you have any simple code to reproduce it. My first assumption is that the OS choose preferably the process from where the request comes. But in any case it's the responsability of the OS to balance the requests. Also gevent will be enough fast to not ask another process to run.

Also i'm unsure on asyncio behaves when it queues the requests. Anyway any code that would help to reproduce the issue is welcome. I will try myself to come with something asap.

**Comment by yunstanford** [comment]
Yeah, observe very similar things, there're always several process with pretty high cpu, while the rest of workers are idle.

**Comment by tilgovi** [comment]
There's probably nothing to be done here if `--reuse-port` doesn't help. Gunicorn generally has no control over which process accepts a connection.

**Comment by yunstanford** [comment]
@tilgovi should it be default to true for multi-worker setup then ?

**Comment by tilgovi** [comment]
@yunstanford it was the default and changed it back because it can cause a very confusing development experience. When a Gunicorn process is running already, starting a new one will not get EADDRINUSE, but appear to start without trouble. Half the requests will then get served by old code, causing lots of confusion.

It's probably a good idea to turn it on in production, but we chose not to enable it by default after we got a few open issues that showed how it can cause confusion.

**Comment by berkerpeksag** [comment]
Perhaps we could introduce a `--dev` config that sets `--reload` and `--no-reuse-port` (assuming we  make `--reuse-port` default behavior again)?

**Comment by sharepusher** [comment]
I also observed similar issue, some CPU cores are very high(around 80-100%), some of them are not so busy. 
Per the per stat, I can see a high CPU migration and context switch
10322.403530 task-clock
107,911 context-switches
9,552 cpu-migrations

And the CPU is very high  (around 70%), but the load actually very low(16 cores, but the load is 0.x to 2.x).
I'm using the gevent mode, 16workers, 7k max connections per worker.

Any suggestions? Thank you.
