### ISSUE TITLE
Access log does not have access to environment variables from the OS

### ISSUE THREAD

**Issue by martinevong** [benoitc/gunicorn#1986]
I would like to log the `HOSTNAME` environment variable from the OS into the gunicorn access log. I have a custom formatter as follows:

`access_log_format = '%({HOSTNAME}e)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %({X-Forwarded-For}i)s'`

My issue is that `HOSTNAME` is not in the environment dictionary when it's logging. It seems as if `environ` doesn't copy the environment variables from the command line. Is this how it's supposed to work? I've also tried passing an environment variable when running gunicorn and that also does not work:

`$ gunicorn --graceful-timeout=0 --access-logfile=logs/access.log --error-logfile=logs/error.log --log-config=production.ini --paste production.ini -c gunicorn_access_log_formatting.conf --env HOSTNAME=a_hostname`

Thank you!

**Comment by tilgovi** [comment]
Those are WSGI environment variables, rather than process environment variables, unfortunately. https://www.python.org/dev/peps/pep-0333/#environ-variables

**Comment by poiyo** [comment]
Thanks for the quick response @tilgovi. Do you know if there is a way to get that information in the access log? I would like to use Docker and log which container is outputting the info. If not then I'll close this issue.

**Comment by tilgovi** [comment]
Docker collects the standard output and error streams of containers by default. You may want to capture this at a lower level.

What is your final log destination?

**Comment by cisarpavel** [comment]
May be it's late, but I solved this issue with python.
I use python config file for gunicorn
```
PROJECT_NAME = os.getenv('PROJECT_NAME')
PROJECT_ENVIRONMENT_TYPE = os.getenv('PROJECT_ENVIRONMENT_TYPE')

access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" "{}" "{}"'.format(
    PROJECT_NAME,
    PROJECT_ENVIRONMENT_TYPE
)
```
So it produces something like
```
2019-10-15 22:36:23,041 INFO <gunicorn.access> 127.0.0.1 - - [15/Oct/2019:22:36:23 +0200] "GET /login/?next=/ HTTP/1.1" 200 3330 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0" "my_project" "localhost"
```

**Comment by macmule** [comment]
I think i've hit this, i'm using a run.sh to load gunicorn with the below for the args:

```
export GUNICORN_CMD_ARGS="--bind=0.0.0.0:5000 \
           --access-logfile=./logs/access.log \
             --error-logfile=./logs/app.log \
--access-logformat='%(t)s %(l)s %({HOSTNAME}e)s %(l)s %({X-Forwarded-For}i)s %(l)s %(r)s %(s)s %(b)s %(f)s %(a)s'"
```

Sadly HOSTNAME is coming back as empty.

Looking at the earlier linked: https://www.python.org/dev/peps/pep-0333/#environ-variables shows that "SERVER_NAME" might work.. sadly not.

**Comment by benoitc** [comment]
you need to pass the environment to gunicorn. using the --env command. Otherwise workers will not know about it.

**Comment by macmule** [comment]
@benoitc apologies, but I'm still struggling.

I know my exports are working for the Flask app, just not gunicorn.

**Comment by benoitc** [comment]
stalled issue
