### ISSUE TITLE
url with two slashs

### ISSUE THREAD

**Issue by janiu-001** [benoitc/gunicorn#1993]
Dear expert: 

We use both unicorn 19.9.0 and 19.7.1 to start our bottle app in our dev env:

With version 19.7.1
http://127.0.0.1:5000//test(two slashes) and http://127.0.0.1:5000/test(one slash) can both get the right result.

Wiht version 19.9.0:
Can only get the result with http://127.0.0.1:5000/test(one slash).

What is the difference between  19.7.1 and 19.9.0? how can we support "//" with versioon 19.9.0?

**Comment by tilgovi** [comment]
Do you have two routes defined in your bottle app? In HTTP `//test` and `/test` are different. We fixed a bug in Gunicorn in #1512 and now you need to define both routes if you want both to work.

**Comment by berkerpeksag** [comment]
Closing this as the question has already been answered.
