### ISSUE TITLE
Hook/standard for when event loop should be initialized for asyncio workers 

### ISSUE THREAD

**Issue by golf-player** [benoitc/gunicorn#1999]
https://github.com/encode/uvicorn/blob/master/uvicorn/workers.py
has `post_worker_init` run before the ioloop is started

https://github.com/aio-libs/aiohttp/blob/master/aiohttp/worker.py
and https://github.com/huge-success/sanic/blob/master/sanic/worker.py
have `post_worker_init` running after.

I'm not aware of other asyncio gunicorn workers, but I expect they'll become more popular now ASGI is getting more mainstream.

(for now I think I'll submit an MR to uvicorn to get it to behave the same way because there's no way to run stuff _after_ the loop starts afaik)

Does it make sense for post_worker_init to run specifically either before or after ioloop is running?

IMO this would do better as a separate hook with maybe something else exposed to configure the ioloop (eg: uvicorn and sanic using uvloop)

Thoughts? Is it the intention of gunicorn to have full support for asyncio workers going forward?

**Comment by golf-player** [comment]
So...any thoughts on this one?

**Comment by tilgovi** [comment]
It seems reasonable to say that initializing an event loop is part of a worker initialization, and therefore `post_worker_init` should run after the loop is initialized.

**Comment by benoitc** [comment]
a worker should provide its initialization before inheriting `init_process`[ where the hook is executed](https://github.com/benoitc/gunicorn/blob/9f87c88819b901d4cd8ddf6c2bba1198b68903cb/gunicorn/workers/base.py#L130) .It seems for me that the uvworker is doing [the right thing](https://github.com/encode/uvicorn/blob/master/uvicorn/workers.py#L44). What let you think the hook is executed before?

**Comment by tilgovi** [comment]
Oh, you're right @benoitc. I missed that somehow and thought it was happening implicitly with `asyncio.get_event_loop()`.

**Comment by golf-player** [comment]
@benoitc I fixed the unicorn worker to get it to work the same way when I opened this issue. I believe the pull request is linked to this issue. 

So going forward, people making asyncio workers should start the ioloop before the post worker init hook is called. That answers my question I guess.

**Comment by benoitc** [comment]
@tilgovi  :) @golf-player yes that it. Now i’m not sure how to document that behaviour. To answer to your second question, some suppor of asyncio is coming. Hopfully i will be able to push it for review this month.

**Comment by golf-player** [comment]
Cool. Looking forward to it

**Comment by tilgovi** [comment]
Closing the issue, since it's seems there's consensus and nothing to change. I'll happily review any documentation updates if anyone wants to improve docs for worker authors.
