### ISSUE TITLE
Daemon option not working in standalone app

### ISSUE THREAD

**Issue by bharadwajyarlagadda** [benoitc/gunicorn#2000]
I tried to use daemon option in a standalone app (using this [gunicorn example](https://github.com/benoitc/gunicorn/blob/master/examples/standalone_app.py))

`example.py`:
```python
import multiprocessing
import gunicorn.app.base


def handler_app(environ, start_response):
    response_body = b'Works fine'
    status = '200 OK'
    response_headers = [('Content-Type', 'text/plain')]
    start_response(status, response_headers)
    return [response_body]


class StandaloneApplication(gunicorn.app.base.BaseApplication):
    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super(StandaloneApplication, self).__init__()

    def load_config(self):
        config = {key: value for key, value in self.options.items()
                  if key in self.cfg.settings and value is not None}
        for key, value in config.items():
            self.cfg.set(key.lower(), value)

    def load(self):
        return self.application


if __name__ == '__main__':
    options = {
        'bind': '%s:%s' % ('127.0.0.1', '8080'),
        'workers': 1,
        'daemon': True
    }
    StandaloneApplication(handler_app, options).run()
```

When I run the script:
```bash
$ python example.py
[2019-02-28 02:23:14 +0000] [62695] [INFO] Starting gunicorn 19.9.0
[2019-02-28 02:23:14 +0000] [62695] [INFO] Listening at: http://127.0.0.1:8080 (62695)
[2019-02-28 02:23:14 +0000] [62695] [INFO] Using worker: sync
[2019-02-28 02:23:14 +0000] [62700] [INFO] Booting worker with pid: 62700
```

It's running in the terminal session but not in the background. Generally, whenever we use `daemon` option, the app runs in  the background and we can exit the terminal.

Is there anything I am doing wrong (or) is there any other prerequisite for the `daemon` option to work in this case?

**Comment by tilgovi** [comment]
If you are overriding `BaseApplication` you would need to implement this in the `run()` method. The daemonization appears to happen in the `run()` method of a subclass, `Application`.

https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/base.py#L210

I'm not sure if there's a good reason some of this work is in the `Application` class but not in the `BaseApplication` class. @benoitc?

**Comment by benoitc** [comment]
@tilgovi that more a design decision than anything. Overriding Applications was originally done to [embed the engine in your application](https://docs.gunicorn.org/en/stable/custom.html) letting you handle the other bits like deciding if you want or not to daemonize your app. I would let it that way.

**Comment by tilgovi** [comment]
That makes sense. @bharadwajyarlagadda you could try subclassing `BaseApplication` instead, but you'll need to spend some time reading that module to make sure you understand how to set it up.

**Comment by johnnytolengo** [comment]
did you solve that ?

`'daemon': True`

**Comment by bharadwajyarlagadda** [comment]
@johnnytolengo I don't exactly remember the way I solved it. It's been long time. But, I do remember that I went with the above approach suggested (I am not sure whether we have deployed the application with those changes or not)

**Comment by johnnytolengo** [comment]
I have the same configuration as your example, of course when I run it from a parent process  proccess.Open(...mygunicornapp) the process never detaches, I am looking around how to fix that for hours  ..

**Comment by bharadwajyarlagadda** [comment]
Did you try @tilgovi's approach?

**Comment by johnnytolengo** [comment]
yes, but it seems that my python skills are not the best, I didn't find out how to do it :(
