### ISSUE TITLE
Best practice for long python imports

### ISSUE THREAD

**Issue by jsbroks** [benoitc/gunicorn#2004]
Hello,

During the initialization of the workers I import/load tensorflow models which can take a few mins.

Is there a better option then increase the timeout of gunicorn to handle theses time consuming tasks?

**Comment by jamadden** [comment]
Have you considered [application preloading](http://docs.gunicorn.org/en/latest/settings.html#preload-app) for your scenario?

**Comment by jsbroks** [comment]
Thanks! Guess I didn't look hard enough
