### ISSUE TITLE
gunicorn and crng init done

### ISSUE THREAD

**Issue by remusmp** [benoitc/gunicorn#2005]
Hello,

I'm using gunicorn on an embedded device without rdrand support. The thing is that crng initialization is slow taking around 84 seconds to complete (this a Linux kernel 4.14.36+ issue):
```
[   84.653764] random: crng init done
```

The problem is that the web server stalls until crng init is done. I'm not able to get any responses from gunicorn until I see crng init done in the logs. Afterwards everything works fine. I'm using gunicorn in the following way:
```
gunicorn --bind=127.0.0.1:5000 --chdir=/var/www/api/ --threads 1 --daemon app:api
```
Is there any configuration that I could do to gunicorn such that it would be usable before crng init is done?

**Comment by jamadden** [comment]
What version of Python are you using? This looks very similar to https://bugs.python.org/issue26839 which was addressed in a particular point release.

**Comment by remusmp** [comment]
Python version:
```
Python 3.7.1 (default, Feb 15 2019, 13:08:40)
```

Linux kernel:
```
Linux version 4.14.40
```

gunicorn version:
```
gunicorn (version 19.9.0)
```

I'll take a look at the link.

**Comment by benoitc** [comment]
@remusmp what was the result?

**Comment by remusmp** [comment]
@benoitc I am running gunicorn on an embedded Linux device where I build my own Linux (with buildroot). In the end I've figured out how to get `crng init done` faster by enabling hardware random number core support. See my ticket at TI http://e2e.ti.com/support/processors/f/791/t/787444?Linux-AM3359-crng-init-done-is-slow
