### ISSUE TITLE
Are there resources for learning how gunicorn async workers make synchronous code asynchronous?

### ISSUE THREAD

**Issue by kyleingraham** [benoitc/gunicorn#2006]
What would be the best way for one to learn how gunicorn takes code written in an synchronous manner and runs it asynchronously? For example, how does it know when to handle one request while waiting for another? Does it look for delays in response from my synchronous code? I see that the async worker libraries have their own implementations of common standard libraries (e.g. socket) but when this is not the case how is asynchronous operation achieved? 

My apologies if this is not the proper location for this question.

**Comment by tilgovi** [comment]
They all use non-blocking I/O internally and system calls that support multiplexing, such as `epoll` or `kqueue`. To make user code work this way, they either provide their own implementations of standard library I/O functions (like `socket` and `socket.recv` or `socket.send` in the case of Gevent and Eventlet) or provide an alternative I/O API (like Tornado). In all cases, these I/O functions are used to register an intent to send or receive before returning control to an event loop. The event loop drives the whole system by using `epoll` or `kqueue` to know when those sockets are ready to send or receive data to fulfill the scheduled asynchronous I/O work.

**Comment by tilgovi** [comment]
Here a starting point for more information: https://en.wikipedia.org/wiki/Asynchronous_I/O#Select(/poll)_loops

You can also read about `asyncio`, `gevent`, `eventlet` or `tornado` specifically, if you want to know more about how they work.

**Comment by kyleingraham** [comment]
Ah so the alternative I/O functions register and intent to send or receive, leave my synchronous code to work on its own while moving forward in the event loop, and then return to my code once it's signaled that it is ready? So as long as my synchronous code is wrapped automatically with proper asynchronous I/O code (through gevent, eventlet, or tornado workers) then the code will fall into the event loop just fine?

If I understand what I've read correctly, each worker must then control it's own event loop spawning the number of threads specified by the `--thread` option.

Thank you for the detailed response and resources. I'll dig into the code for gunicorn and the async workers to learn exactly what happens behind the scenes. Your response helped quite a bit.

**Comment by tilgovi** [comment]
> Ah so the alternative I/O functions register and intent to send or receive, leave my synchronous code to work on its own while moving forward in the event loop, and then return to my code once it's signaled that it is ready?

Exactly. Control flows from your code to the event loop and only comes back when that I/O operation is completed. During that time, the event loop may pass control to other code that was previously blocked on its own I/O.

> If I understand what I've read correctly, each worker must then control it's own event loop spawning the number of threads specified by the --thread option.

None of the asynchronous workers use the threads option. Using `--threads` implies `--worker-class gthread`. The threaded worker is distinct from the asynchronous workers and it uses multiple threads to handle concurrent requests rather than an event loop.

**Comment by tilgovi** [comment]
> Thank you for the detailed response and resources. I'll dig into the code for gunicorn and the async workers to learn exactly what happens behind the scenes. Your response helped quite a bit.

No problem! Glad I could help. I'll close the issue now, but if you feel like there's a good place to contribute some documentation, I would gladly review a PR. There are also related questions in #1045 and it sounds like there have been a number of users confused by `--threads`.

**Comment by kyleingraham** [comment]
I will take a look at the documentation after I've gotten a firm grasp on how all of this works. I found an excellent video on gevent that may help others trying to learn about how asynchronous workers operate:

Kavya Joshi - A tale of concurrency through creativity in Python: a deep dive into how gevent works. - https://www.youtube.com/watch?v=GunMToxbE0E
