### ISSUE TITLE
(gunicorn + flask) load deep learning Model

### ISSUE THREAD

**Issue by xikunlun001** [benoitc/gunicorn#2007]
I'm trying to use gunicorn and flask to deploy a pytorch model(3GB+) as an online service. And I set multi workers as well.

However, it seems every worker will load the pytorch model into ram once. And 8 workers cost 3*8 = 24GB ram. Any suggestions for only load model once for multi workers condition?

Many thanks

**Comment by tilgovi** [comment]
http://docs.gunicorn.org/en/latest/settings.html#preload-app

**Comment by xikunlun001** [comment]
@tilgovi 
Many thanks

**Comment by Divjyot** [comment]
@xikunlun001  Does that preload option helped or how did you used it ? I am in similar situation where I have a spacy NLP model that is 111MB and each request to API tends to load the model again instead of sharing the memory. Any help or recommendation would help. I am using django+docker
