### ISSUE TITLE
Static content (JS, CSS, Images) takes a long time (> 2 mins) to serve and the worker takes 100% CPU.

### ISSUE THREAD

**Issue by SpyRefused** [benoitc/gunicorn#2015]
I have a Python API made in Flask, it only has a small frontend view that is a single template and several js, css and some png. Everything is included in a Docker container. In debug (without being inside the container of Docker) everything works correctly, but inside the container, when entering to serve this page "Home" (Path "/") there are certain elements that take exaggeratedly in being served by the Flask, when I say exaggeratedly I mean even to 4 or 5 minutes, is as they were stuck. So I understand it's something to do with gunicorn.

Also, this makes Gunicorn workers take 100% CPU.

![image](https://user-images.githubusercontent.com/588203/56289875-466f6a80-6122-11e9-8da9-f9972f484ae5.png)

The stack in the container is meinheld + gunicorn + Flask. The configuration of the static content could not be simpler, the template is in the folder "/templates" and the static content in "/static", within the template I use:

<link href="{{url_for('static',filename='bootstrap.min.css')}}" rel="stylesheet">
I can't find the key of what the hell is going on with certain elements, which take an eternity to load and also, the gunicorn workers collapse. Any ideas?

Thanks.

**Comment by jamadden** [comment]
Can you show us your gunicorn configuration and how you're starting gunicorn? Particularly interesting is the type of worker.

(Do you also debug on Linux?)

**Comment by SpyRefused** [comment]
> Can you show us your gunicorn configuration and how you're starting gunicorn? Particularly interesting is the type of worker.
> 
> (Do you also debug on Linux?)


My image of Docker is based on this one:

https://github.com/tiangolo/meinheld-gunicorn-docker

gunicorn's configuration is as follows:

```
import json
import multiprocessing
import os

workers_per_core_str = os.getenv("WORKERS_PER_CORE", "2")
web_concurrency_str = os.getenv("WEB_CONCURRENCY", None)
host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "80")
bind_env = os.getenv("BIND", None)
use_loglevel = os.getenv("LOG_LEVEL", "info")
if bind_env:
    use_bind = bind_env
else:
    use_bind = f"{host}:{port}"

cores = multiprocessing.cpu_count()
workers_per_core = float(workers_per_core_str)
default_web_concurrency = workers_per_core * cores
if web_concurrency_str:
    web_concurrency = int(web_concurrency_str)
    assert web_concurrency > 0
else:
    web_concurrency = int(default_web_concurrency)

# Gunicorn config variables
loglevel = use_loglevel
workers = web_concurrency
bind = use_bind
keepalive = 120
errorlog = "-"

# For debugging and testing
log_data = {
    "loglevel": loglevel,
    "workers": workers,
    "bind": bind,
    # Additional, non-gunicorn variables
    "workers_per_core": workers_per_core,
    "host": host,
    "port": port,
}
print(json.dumps(log_data))
```

**Comment by jamadden** [comment]
Ah, so that appears to use a custom worker `egg:meinheld#gunicorn_worker`, which is almost entirely implemented in C.

I don't suppose you could try this with a different worker (e.g., gevent) and see if that solves your problem?

**Comment by SpyRefused** [comment]
Hi! sorry about the delay.

@jamadden, finally you were right, it seems that the problem was that worker. I could not replace it with the gevent because it does not suit too much to what we expect, but with the default sync worker of the gunicorn if it seems to go all right.

Thank you very much for the help.

Regards.
