### ISSUE TITLE
Create a list of commits to backport to 19.x branch

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#2022]
I think our plan was to make one more 19.x release before EOL for Python 2.7.

I would be nice to list all commits here to make backporting easier.

The difference between master and 19.x branches can be seen in https://github.com/benoitc/gunicorn/compare/19.x...master.

**Comment by berkerpeksag** [comment]
**Typos, documentation changes and other trivial fixes:**

* [ ] https://github.com/benoitc/gunicorn/commit/2ff595a02b88bddd50d0f0d2f99ebfeca9e8ef15
* [ ] https://github.com/benoitc/gunicorn/commit/ec3c1dbd9423b68e126f6a84d8830a045d49782d
* [ ] https://github.com/benoitc/gunicorn/commit/ab7541f7671037f45bdbbad574371c8eaf4f0ec5
* [ ] https://github.com/benoitc/gunicorn/commit/8bc11ff632a990cb521fcb583150f22306f5ea2e
* [ ] https://github.com/benoitc/gunicorn/commit/33162d190f14a1d36fba7c9549fb369231151bd2

**Comment by benoitc** [comment]
do we want to backport the change i just commited also?

**Comment by berkerpeksag** [comment]
I think it would be nice to backport `wsgi.input_terminated` support to 19.x.

**Comment by tilgovi** [comment]
Maybe these?

- [ ] 927fb2ba02b4bbc8e1c64fc0139fc0d91d72d188
- [ ] 6da84c614d5a5b60ebed146301e4ac7c436f8fb3
- [ ] 7ed20f6833c12d216a3b7241ff0f7e63f4eb50d2

**Comment by villebro** [comment]
In `19.9.0` setting `X-Forwarded-Proto` to `https` returns `http` in redirects. I tried looking through the existing issues and PRs, but due to my limited expertise in this area I was unsure if this was fixed or not. An example below:

`curl -v -H "X-Forwarded-Proto: https" http://url`

on `19.8.0` returns a `https://` address, while `19.9.0` returns `http://`.

**Comment by tilgovi** [comment]
That may be this commit:

- [ ] e179dc25759405159e0bedbf6a0780eff2e5f043

**Comment by tilgovi** [comment]
I'll add this one. Small and fixes compatibility for Tornado 6, apparently:

- [ ] dc7b5d5c4876b49f86ea2460698a335d0f5ef7c9

**Comment by zgoda** [comment]
https://github.com/benoitc/gunicorn/commit/30554fdb4fdc169997b234e49ab93655a289d76d fixes issue with inotify reloader that was previously fixed for poll reloader only.

**Comment by di** [comment]
I'd like to propose 879651b for backporting, it's a one-line change which fixes header value encoding.

**Comment by villebro** [comment]
There seems to be a good list of backports here; is there still a plan to release `19.9.1` in the near future?

**Comment by di** [comment]
I've created https://github.com/benoitc/gunicorn/pull/2114 to backport all the commits listed in this issue to the `19.x` branch.

If there's any other commits worth backporting, please mention them here.

**Comment by benoitc** [comment]
@di thanks for it! The PR looks good for me, let's wait for some feedback from others but I will make a release beginning of the week with them .

**Comment by tilgovi** [comment]
The only one mentioned here that I didn't see in the #2114 PR was the `wsgi.input_terminated` change. I just cherry picked and pushed that one to 19.x. I'm going to close this issue now, and start preparing the changelog and announcements.

Thanks for everyone's help!

**Comment by di** [comment]
Sorry, I must have missed that one because there wasn't a commit hash included in the comment. Thanks @tilgovi!

**Comment by tilgovi** [comment]
No worries at all. Thanks so much for that help, @di.
