### ISSUE TITLE
No callback to execute code between greenlet patching and app setup

### ISSUE THREAD

**Issue by aberres** [benoitc/gunicorn#2023]
When using the gevent worker the one might want to patch additional libraries manually. E.g. [opencensus](https://github.com/census-instrumentation/opencensus-python/issues/628).  
The monkey patching should happen after gevent did its patching but before the application code is loaded.

As of now there is no hook allowing this. `post_fork` is called before `Worker.init_process` is executed (which does the patching)nwhile `post_worker_init` is called once the application code is loaded.

Could a `pre_worker_init` hook be introduced which is triggered once `Worker.init_process` is finished?

**Comment by jamadden** [comment]
> When using the gevent worker the one might want to patch additional libraries manually. E.g. opencensus.

Beginning in gevent 1.3, monkey-patching [emits events](http://www.gevent.org/api/gevent.monkey.html#plugins) designed for exactly this purpose. There are a few ways to hook into them, including using `pkg_resources` entry points.

Maybe that can do what you need?

**Comment by aberres** [comment]
Ah, this looks good, thanks.

I guess this should do the trick. Will try and report.

**Comment by aberres** [comment]
@jamadden, your tip is golden. Works like a charm.

No need for any changes on the gunicorn side then.
