### ISSUE TITLE
How to issue HTTP error codes from Gunicorn?

### ISSUE THREAD

**Issue by shivdhar** [benoitc/gunicorn#2025]
`--timeout 30` will kill a worker after 30 seconds, but ends the connection with the client without response. ( A `curl`request, for instance, returns `curl: (52) Empty reply from server`.)

How can I tell Gunicorn to reply with, say, '413: Request Entity Too Large' on worker timeout?

**Comment by tilgovi** [comment]
There is no feature for this in Gunicorn.

The `--timeout` option is a timeout for non-responsive workers. It is not really a request timeout, though it sort of functions that way for the synchronous worker. It is enforced by the main process, not by the worker handling the request. The main process kills the worker without any opportunity for the worker to the signal and respond.

One problem with implementing a custom timeout response is that the application could send a status code and headers but then take a long time to send the response. The request may then time out but the status and headers are already sent. To solve that, you would need to buffer the whole response or risk cutting off a request mid-stream.

You could probably accomplish this with `asyncio`, or maybe even with `signal.alarm()`, but it is outside of what Gunicorn will handle for you.

**Comment by shivdhar** [comment]
Thanks for the reply.

My use case is this:
I have machine learning models that may take a long time to predict, depending on the input. I need to gracefully kill the worker and reply with an error code to the client if it takes too long.

`signal.alarm()` is indeed one possible way, but it will run into the same problem you described above: what if the alarm is sent in the middle of a reply?

I've been searching for a way for a long time, but this doesn't seem to have been implemented at any layer:

#### 1. Nginx:

http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_read_timeout

> Defines a timeout for reading a response from the uwsgi server. The timeout is set only between two successive read operations, not for the transmission of the whole response. If the uwsgi server does not transmit anything within this time, the connection is closed.

'The connection is closed' --> no error code is sent

#### 2. Gunicorn:

Your answer above ;)

#### 3. Flask

I found [this on StackOverflow](https://stackoverflow.com/questions/23144622/how-to-set-http-request-timeout-in-python-flask/26774635):
> how to set http request timeout in python flask

> WSGI server
Flask servers only to create logic of the server. On run your Flask application should be server by WSGI server. Most common is uWSGI ( & nGinx like facade between outer world and your server). 
But you can use whichever WSGI server suits you best (nichol.as/benchmark-of-python-web-servers).

which passes the buck to the WSGI server/Nginx.

The closest I could find was https://devcenter.heroku.com/articles/request-timeout#timeout-behavior

While it appears unlikely that something so basic hasn't been requested/implemented yet by anybody., it seems that this is really is the situation. 

Would you be willing to accept a pull request on this/Is there an existing way to do this?

**Comment by benoitc** [comment]
> How can I tell Gunicorn to reply with, say, '413: Request Entity Too Large' on worker timeout?

Such response could only be sent if you already got the full request though. Ie. you can't interrupt a request on the server side to send a response. (to be exact you can only do it using the `Expect: continue` header. That's not feasible then since the timeout is especially here to prevent a blocking request.

If you want to accept large requests you can use any async worker which solves the issue you have.
