### ISSUE TITLE
when to kill post_fork worker 

### ISSUE THREAD

**Issue by toywei** [benoitc/gunicorn#2029]
gunicorn wsgi_dev:application --bind=0.0.0.0:8001 --workers=4  --timeout=300 -k gevent;

![请求发来后-进行阶段-随着jmeter-线程数和循环数的增加-worker增加](https://user-images.githubusercontent.com/16590605/57435234-68669380-726f-11e9-811f-4550ec5fb170.png)

**Comment by tilgovi** [comment]
@toywei can you say more about your question, "when to kill post_fork worker". I do not understand what you are asking or why.

**Comment by toywei** [comment]
the lifecycle of grandson workers，please

**Comment by toywei** [comment]
@tilgovi  green

**Comment by benoitc** [comment]
closing the issue-.  Feel free to reope,n it if you have can provide more details that could help us to understand the issue.

**Comment by toywei** [comment]
Please explain the lifecycle of the worker process in green color.Thanks.
