### ISSUE TITLE
why don't gunicorn start  a new process ?

### ISSUE THREAD

**Issue by ninghongbo123** [benoitc/gunicorn#2032]
I  want to  start a new  process beside my  program  when  receiving  a  different type of request . But, using  gunicon  framework, it  won't  work. that is to say, a new  process  was  blocked. So
       #gunicon  has  a fixed  process ,and don't  allow to create   new  process  dynamicly , is  it real?
       #anyone  meet same question?  other  solutions?

**Comment by tilgovi** [comment]
Gunicorn does not prevent starting new processes. How are you doing it?

**Comment by ninghongbo123** [comment]
@tilgovi 
my code snippet is as follows:
    from multiprocessing import Process
    model_dic={}
    @server.route('/modelManagement', methods=['POST'])
    def modelManagement():
          id=args["id"]
          model_dic[id]=Process(target=mymodel,args=(id))
          model_dic[id].start()
when  receiving  a  request  with a new  modelId,  I  will  start  a new  process.
It  works  without  gunicorn  framework, but  it doesn't  work  using  gunicorn.
That's  my  question!  Thank you for  your  reply.

**Comment by ninghongbo123** [comment]
@tilgovi
Maybe you can give me a reply please . Thank you !

**Comment by benoitc** [comment]
@ninghongbo123 what is the error returned?

**Comment by berkerpeksag** [comment]
You're using multiprocessing module wrong. You'll need to call `process.join()` and probably do this inside `if __name__ == '__main__':` to avoid side effects. You'll probably need to separate the process creating code from the request-response circle (especially if the computation will take time) or use Celery instead. Please read multiprocessing documentation for further information. There is no Gunicorn bug here.
