### ISSUE TITLE
Output to stdout/stderr in daemon mode

### ISSUE THREAD

**Issue by theintz** [benoitc/gunicorn#2045]
Is there a way to have Gunicorn print its access and error logs to stdout/stderr when running in daemon mode?

I am running Gunicorn inside a Docker container, which also contains an nginx powering a Django based web application. For ease of logging I would like to have all the output (of all processes) simply printed to stdout/stderr where the Docker daemon can pick it up and forward it elsewhere.
Since there are running multiple processes inside of the container, I use the `--daemon` option to put Gunicorn in the background. However, this seems to disable all capabilities of printiny any form of output to the standard streams. I've tried the `--access-log` and `--error-log` options with various parameters like `-`, `/dev/stdout`, even `/proc/1/fd/1`, all to no avail. There is no output at all, unless written to a file (which is a bad idea inside a long running Docker container).

Looking at the `daemonize()` function in https://github.com/benoitc/gunicorn/blob/3701ad9f26a7a4c0a081dfd0f6e97ecb272de515/gunicorn/util.py#L417 it appears that all streams that are attachted to a TTY (as stdout and stderr are by default) are redirected to `/dev/null` upon startup. Is there another way to achieve my goal, bar using bash tricks or supervisord?

Thanks!

**Comment by benoitc** [comment]
the capture_stdout setting allows that: http://docs.gunicorn.org/en/stable/settings.html#capture-output sorry for the delay to answer.

**Comment by danstewart** [comment]
`--enable-stdio-inheritance` was what I needed.

Here's a full example:
```
gunicorn \
    --workers 4 \
    --threads 4 \
    --bind 0.0.0.0:5000 \
    --worker-tmp-dir /dev/shm \
    --log-level debug \
    --capture-output \
    --enable-stdio-inheritance \
    --daemon \
    'app:create_app()'

exec nginx -g 'daemon off;'`
```
