### ISSUE TITLE
Gunicorn closing connection with gthread and expensive SQLAlchemy calls

### ISSUE THREAD

**Issue by paymog** [benoitc/gunicorn#2055]
I'm running a flask application with gunicorn and gthread workers - I start the application with `gunicorn --config config/gunicorn.py api_intent:make_app()` and `my config/gunicorn.py` file looks like:
```
bind = ['0.0.0.0:80']
worker_class = "gthread"


__all__ = ['bind']
```
One of my flask endpoints makes complex database calls that require minutes to execute. I sometimes see the following error on the client side: `Remote end closed connection without response`. However, I also find that if I issue a subsequent identical call that error doesn't arise on the client side AND I find in the server logs that the expensive database calls takes less time (still on the order of minutes though), presumably because the data that endpoint cares about is pulled into memory.

I've looked at the [gunicorn docs](http://docs.gunicorn.org/en/stable/settings.html#timeout) and specifically the `timeout `option but I have a hard time understanding the consequences of changing the timeout for threaded workers. My understanding is that with `gthread` the workers provide heartbeats to some master process and it's not clear to me why a default value of 30 seconds for that value would only sometimes cause the server to close the connection to the client. Could it be that if a single DB call requires > 30 seconds the execute, a gthread worker will be considered dead?

I've also tested using `gevent` as a worker and almost immediately saw an error of `[CRITICAL] WORKER TIMEOUT (pid:21)` (the logs suggest this failure happened 30 seconds after the request was received) which I guess makes sense because of the IO complexity of the endpoint I care about and the fact that the default timeout is 30 seconds.

How can I correctly instruct gunicorn to wait longer before closing connections with `gthread`? Can I configure this per endpoint? Some research I've done suggests that async workers like `gevent` and `eventlet` are better suited to IO bound tasks, is that correct? If so, how come using `gevent` resulted in more immediate failures?

**Comment by jamadden** [comment]
> how come using gevent resulted in more immediate failures?

Most likely because the database driver you are using is not gevent compatible, and thus blocked the event loop from running and the heartbeat from being processed. That’s a common issue with database drivers implemented with C libraries. If you can say what database driver you use now, we may be able to suggest an alternative that works with gevent.

**Comment by paymog** [comment]
I'm using psycopg2 to connect to postgres (I hope that psycopg2 is a DB driver, though I'm not sure).

**Comment by paymog** [comment]
https://bitbucket.org/dvarrazzo/psycogreen/src/master/ suggests that maybe `eventlet` is the way to go with `psycopg` and gunicorn.

**Comment by jamadden** [comment]
gevent will work with psycopg2 just fine, but you do need to use `psycogreen.gevent.patch_psycopg()`.
