### ISSUE TITLE
how can GeventPyWSGIWorker use max_requests options?

### ISSUE THREAD

**Issue by mrwang1992** [benoitc/gunicorn#2056]
i not see PyWSGIHandler can restart worker logic.

**Comment by tilgovi** [comment]
The `PyWSGIHandler` is used as the handler class for the `GeventPyWSGIWorker`. `GeventPyWSGIWorker` inherits from `GeventWorker` and `GeventWorker` inherits from `AsyncWorker`. The implementation of the `max_requests` happens in `AsyncWorker.handle_request`.

**Comment by mrwang1992** [comment]
gunicorn.__version__
19.9.0

`
class PyWSGIHandler(pywsgi.WSGIHandler):


server = self.server_class(
                    s, application=self.wsgi, spawn=pool, log=self.log,
                    handler_class=self.wsgi_handler, environ=environ,
                    **ssl_args)
`

self.server_class  is PyWSGIServer
self.wsgi_handler is PyWSGIHandler 

so it not use AsyncWorker.handle_request

**Comment by tilgovi** [comment]
My apologies, @mrwang1992. You're correct that it does not appear possible to use this option with the `GeventPyWSGIWorker` right now.

**Comment by mrwang1992** [comment]
Ok,  some plan fix it ?  and thx you comment.

**Comment by tilgovi** [comment]
If you can find a way to fix it, I would happily review a PR.

**Comment by mrwang1992** [comment]
ok, i try.

**Comment by benoitc** [comment]
shouw we do something there? @tilgovi @jamadden

**Comment by tilgovi** [comment]
I leave this to @jamadden to decide if it's reasonable to support a max requests option for the PyWSGIHandler.

**Comment by tilgovi** [comment]
It's probably possible to implement it by wrapping the request handling in `PyWSGIHandler`, like overriding `process_one_response()` to keep track of the request count. However, we don't seem to pass the gunicorn config into the PyWSGIServer in any way, so I don't think the request count can be known right now.

**Comment by benoitc** [comment]
That could be a `partial` method. 

I wonder however if we want to support all the feature in that handler instead of improving our own. We don't really need to deprecate but we can advertise it with its limits. Also maybe if some optons are not exposed, expose them in a way or another. 

Thoughts?
