### ISSUE TITLE
Https is not working

### ISSUE THREAD

**Issue by gosrinin** [benoitc/gunicorn#2062]
My site was working perfect without https i.e) domainname:8001 but after adding the letsencrypt certificate when i tried to access domain name:8001 it's taking to https redirect automatically as coded in the ngnix but the server is not responding.
I am sharing the gunicorn configuration file along with nginx and supervisor.

Gunicorn.conf.py

proc_name = 'myapp'
bind = 'ip:8001'
workers = 4
timeout = 1800
graceful_timeout=1800
user = 'root'
group = 'www-data'
loglevel = 'debug'
errorlog = '/home/logs/gunicorn.error.log'
accesslog = '/home/logs/gunicorn.access.log'

Nignx Configuration:

server {
    server_name domainname.com www.domainname.com;
	
location / {
        root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
  }
  
    location /api/ {
        proxy_pass http://127.0.0.1:8001; 
        proxy_set_header Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = www.domainname.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = domainname.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name domainname.com www.domainname.com;
    return 404; # managed by Certbot

}

Supervisor:

[program:app]
environment=LANG="en_US.utf8", LC_ALL="en_US.UTF-8", LC_LANG="en_US.UTF-8"
command = /usr/local/bin/bin/gunicorn app.app:application -c /home/conf/gunicorn.conf.py
directory =/home/app
user = root
loglevel = debug
stdout_logfile = /home/logs/supervisor.log
stderr_logfile = /home/logs/supervisor.error.log
autostart = true
autorestart = true
redirect_stderr = true

**Comment by tilgovi** [comment]
Anything in the Gunicorn logs?

**Comment by gosrinin** [comment]
> 
> 
> Anything in the Gunicorn logs?

Ignored premature client disconnection. No more data after: b'

**Comment by HewittJC** [comment]
We're seeing something similar. Gunicorn workers segfaults now when trying to connect using SSL.

**Comment by benoitc** [comment]
work pretty well there.  Make sure to ue the `proxy_redirect off;` setting in proxy configuration.
