### ISSUE TITLE
Cython build

### ISSUE THREAD

**Issue by lucianmarin** [benoitc/gunicorn#2063]
It would be nice if setup.py could include ext_modules built with Cython. Latency for each request would probably be much better.

See setup.py from https://github.com/falconry/falcon

**Comment by tilgovi** [comment]
Thank you for the suggestion. We have investigated using an HTTP parser written in C before, but if I recall correctly it was not clearly a good choice at the time. That may have changed now, in 2019.

If there are specific areas of Gunicorn that you think could be faster, please let us know if you benchmark it or open PRs with any WIP you'd like feedback on.
