### ISSUE TITLE
504 with gevent workers and Celery

### ISSUE THREAD

**Issue by DanielP77** [benoitc/gunicorn#2068]
Hi,

I have a Flask Restplus application that offers several REST GET and POST methods, using nginx 1.14.0 as reverse Proxy and Gunicorn 19.9.0 as WSGI Server. Most of the methods are simply administrative, like creating users or setting properties. The main POST methods receives an image in the request body (in form-data) and uses Celery with gevent workers to send it to several external APIs for processing, waits for the responses and returns these responses to the caller.
When using the default sync worker in Gunicorn, everything works fine - except for Gateway Timeouts on heavy loads. From the docs I learned that this kind of task is better solved with async workers, so I changed the Gunicorn worker to gevent. Now the main POST method does not respond any more, I always get a 504 Gateway Timeout. The other REST methods still work fine, only this one does not respond at all. The timeouts for nginx and Gunicorn are set to high levels, so this can't be the problem (I tested with up to 600 seconds, and the external API calls normally take no more than 5-10 seconds). The most noticeable difference between the methods that send responses and the one that doesn't respond is that the not responding one uses Celery with gevent workers to process the external API calls. Could this be the reason for running into the Gateway Timeout somehow? I can see that the Celery tasks do respond successfully, only the final response is not being returned by Gunicorn.

I attach an excerpt from the Gunicorn error log, maybe there is some useful information in it.
[Gunicorn_error.log](https://github.com/benoitc/gunicorn/files/3335198/Gunicorn_error.log)

Any help or hint is highly appreciated. Thank you in advance! And if you need any more information, please let me know.

**Comment by jamadden** [comment]
If those external requests are dispatched in parallel, my first guess would be that something is blocking due to the difference between preemptive multitasking vs cooperative multitasking, but without seeing the code, it's difficult to guess. There could be lots of possibilities.

I would suggest enabling gevent's [blocking monitor thread](http://www.gevent.org/monitoring.html) and see if it reports anything.

**Comment by DanielP77** [comment]
@jamadden Thank you for your response. I enabled gevent's blocking monitor thread and indeed there seems to be a blocking immediately after a few seconds:
```
Jun 28 05:55:57 bai-staging systemd[1]: Started Gunicorn instance to serve bai.
Jun 28 05:56:00 bai-staging gunicorn[22345]: /home/dp/bai-env/lib/python3.6/site-packages/gevent/_monitor.py:282: MonitorWarning: Unable to monitor memory usage. Install psutil.
Jun 28 05:56:00 bai-staging gunicorn[22345]:   MonitorWarning)
Jun 28 05:56:00 bai-staging gunicorn[22345]: ================================================================================
Jun 28 05:56:00 bai-staging gunicorn[22345]: 2019-06-28T05:55:59Z : Greenlet <greenlet.greenlet object at 0x7f052375df20> appears to be blocked
Jun 28 05:56:00 bai-staging gunicorn[22345]:     Reported by <gevent.__tracer.GreenletTracer object at 0x7f05209f6e08>
Jun 28 05:56:00 bai-staging gunicorn[22345]: Blocked Stack (for thread id 0x7f05269c5740):
```
The complete log is here:
[syslog_bai.log](https://github.com/benoitc/gunicorn/files/3338999/syslog_bai.log)
I can't see anything suspicious in the log, though. I also don't know where this early blocking could come from. 

Btw.: When using the default `max_blocking_time` of 0.1 seconds, I also get blockings in the Celery Tasks, but when setting `max_blocking_time` to 1.0 seconds, there are no blockings for the Celery Tasks.

**Comment by jamadden** [comment]
Thanks for the info! Unfortunately, the log didn't seem to catch anything actually *doing* anything. It appears to only be the first few seconds during startup, and it appears that your application takes quite a while to load, so all we're seeing is the process of importing your application (naturally that doesn't switch). We'll need to see the log for when a worker handles a request. That probably means you'll need to give your workers more time to boot and come to a steady state. Ideally, when they're sitting there idle waiting for a request, the monitor thread isn't outputting anything. 

You might be able to preload your application in the main gunicorn process to reduce worker boot time and noise. Or, you could manually (via code, not an environment variable) start the monitor thread in each worker as the last step of loading your application --- or even just as the first step in processing this particular request. (I need to document this better.)

```python
import gevent
gevent.config.monitor_thread = True
gevent.get_hub().start_periodic_monitoring_thread()
```

The one thing I see that could be potentially suspicious is the presence of an instance of `'asyncio.events._RunningLoop`. All that actually means is that `asyncio` has been imported, which by itself is innocuous. But if something were to actually try to run an asyncio loop, that wouldn't play well with the gevent loop.

**Comment by DanielP77** [comment]
Hi @jamadden,

Thanks again for the info and sorry for the late reply.

I was trying to find the source of the ```asyncio``` import in the third-party packages I use, but without success. I have no idea where this comes from.

I also started the monitor thread via code as the first step in processing the request, as you recommended, and ran one request with Postman a Minute or two after my application was started. Please find the syslog file attached. I didn't shorten it (except for everything before starting my application), so it is quite big. But I didn't want to accidentially cut out anything relevant, so I apologize for this huge log file. I tried to see if I find anything suspicious in it, but without success.
[syslog_bai_1.log](https://github.com/benoitc/gunicorn/files/3363068/syslog_bai_1.log)

Just out of curiosity, I tried Gunicorn with Eventlet workers, and there my request was successfully responded. Not sure if this information helps.

**Comment by jamadden** [comment]
>  the not responding one uses Celery with gevent workers

Ah, so if the thing that's supposed to read results from Celery died that might cause a problem like this? It seems that might have happened: 

```
Jul  5 13:53:14 bai-staging gunicorn[2616]: Traceback (most recent call last):
Jul  5 13:53:14 bai-staging gunicorn[2616]:   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
Jul  5 13:53:14 bai-staging gunicorn[2616]:   File "/home/dp/bai-env/lib/python3.6/site-packages/celery/backends/async.py", line 82, in run
Jul  5 13:53:14 bai-staging gunicorn[2616]:     self.result_consumer.drain_events(timeout=1)
Jul  5 13:53:14 bai-staging gunicorn[2616]:   File "/home/dp/bai-env/lib/python3.6/site-packages/celery/backends/redis.py", line 119, in drain_events
Jul  5 13:53:14 bai-staging gunicorn[2616]:     m = self._pubsub.get_message(timeout=timeout)
Jul  5 13:53:14 bai-staging gunicorn[2616]: AttributeError: 'NoneType' object has no attribute 'get_message'
```

Debugging that might lead to the source of the problem?

It was kicked off independently here; I'm not sure exactly where that is, but it hangs around from the failure until the end of the log, so something still has a reference to it and is probably expecting it to do stuff that it's never going to do:
```
Jul  5 13:58:14 bai-staging gunicorn[2616]:                       {}
Jul  5 13:58:14 bai-staging gunicorn[2616]:            +--- <Greenlet "Greenlet-1" at 0x7f5d0937e248: <bound method greenletDrainer.run of <celery.backends.async.geventDrainer object at 0x7f5d09304048>>>; finished with exception AttributeError("'NoneType' object has no attribute 'get_message'",)
Jul  5 13:58:14 bai-staging gunicorn[2616]:                         Parent: <Hub '' at 0x7f5d1ed33c18 epoll default pending=0 ref=3 fileno=8 resolver=<gevent.resolver_thread.Resolver at 0x7f5d09ae2ac8 pool=<ThreadPool at 0x7f5d09ae2a58 0/1/10 hub=<Hub at 0x7f5d1ed33c18 thread_ident=0x140038010181440>>> threadpool=<ThreadPool at 0x7f5d09ae2a58 0/1/10 hub=<Hub at 0x7f5d1ed33c18 thread_ident=0x140038010181440>> thread_ident=0x7f5d23da1740>
Jul  5 13:58:14 bai-staging gunicorn[2616]:                         Spawned at:
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/gevent/hub.py", line 549, in run
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def run(self):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/gevent/baseserver.py", line 193, in _do_read
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def _do_read(self):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/gevent/baseserver.py", line 173, in do_handle
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def do_handle(self, *args):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/gevent/pool.py", line 377, in spawn
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def spawn(self, *args, **kwargs): # pylint:disable=arguments-differ
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/canvas.py", line 1256, in run
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def run(self, header, body, partial_args, app=None, interval=None,
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/canvas.py", line 1075, in freeze
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def freeze(self, _id=None, group_id=None, chord=None,
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/result.py", line 870, in __init__
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def __init__(self, id=None, results=None, parent=None, **kwargs):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/result.py", line 498, in __init__
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def __init__(self, results, app=None, ready_barrier=None, **kwargs):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/vine/synchronization.py", line 38, in __init__
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def __init__(self, promises=None, args=None, kwargs=None,
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/vine/synchronization.py", line 57, in <listcomp>
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             [self.add_noincr(p) for p in promises or []]
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/vine/synchronization.py", line 78, in add_noincr
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def add_noincr(self, p):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/result.py", line 118, in then
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def then(self, callback, on_error=None, weak=False):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/backends/async.py", line 150, in add_pending_result
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def add_pending_result(self, result, weak=False, start_drainer=True):
Jul  5 13:58:14 bai-staging gunicorn[2616]:                           File "/home/dp/bai-env/lib/python3.6/site-packages/celery/backends/async.py", line 87, in start
Jul  5 13:58:14 bai-staging gunicorn[2616]:                             def start(self):
```

> so it is quite big.

Yeah...the monitoring could be smarter about reporting. I thought it was supposed to ignore the threadpool threads, for instance, but they're being reported here. Or perhaps that's only in 1.5a1 that I made that happen; either way, I need to take another look.

**Comment by DanielP77** [comment]
@jamadden: And thanks again for your response and your help!

After debugging and researching for a while I think I found the cause for the issue (or at least I managed to make it work): It looks like as if this was caused by a race condition that can happen when using Celery with Redis backend and Gevent workers pool. This is fixed in the current stable Celery version 4.3.0, after upgrading Celery the request finally responded in time.

Again, thank you a lot for your help and pointing me in the right direction - and, of course, for Gevent in general!

**Comment by jamadden** [comment]
I'm glad you figured it out! Do you have a link to a corresponding Celery issue/PR/commit you can put here for historical purposes?

**Comment by DanielP77** [comment]
Sure!
[This is the issue #4105] (https://github.com/celery/celery/issues/4105 "ResultConsumer greenlet race condition") where the issue is reported.
[And this is the PR #5345] (https://github.com/celery/celery/pull/5345 "Fix redis ResultConsumer.drain_events when called before start") that solves the issue in Celery 4.3.0.

This exception seems to indicate this issue:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/async.py", line 83, in run
    self.result_consumer.drain_events(timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 69, in drain_events
    m = self._pubsub.get_message(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'get_message'
<Greenlet at 0x7efd9d8ba550: <bound method geventDrainer.run of <celery.backends.async.geventDrainer object at 0x7efd9d99f550>>> failed with AttributeError
```
