### ISSUE TITLE
Cannot access gunicorn server when used with docker

### ISSUE THREAD

**Issue by kmehant** [benoitc/gunicorn#2074]
### Context
I have used gunicorn to run the flask application on a gevent worker. I have exposed the required port and even used the corresponding -b flag. But when I run the gunicorn server I everything run well but unable to access it.

**Comment by Indigo-Tech** [comment]
@kmehant can you give more info?

I tested it now and it worked perfectly, 

Dockerfile:
```
FROM python:3.6

WORKDIR /usr/src/app

RUN pip install flask gunicorn gevent

COPY flask_main.py .

CMD ["gunicorn", "-k", "gevent", "-b", "0.0.0.0:9000", "flask_main:app"]

```

flask_main.py
```
from flask import Flask, Response

app = Flask(__name__)


@app.route('/say_hello')
def say_hello():
    return Response('Hello World!')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9000)
```

build the image with "docker build -t gunicorn:test ."

and lastly, run the image with "docker run -d -p 9000:9000 gunicorn:test"

**Comment by tilgovi** [comment]
Closing this after almost a month of no follow-up since help was provided.
