### ISSUE TITLE
Define a __repr__ for gunicorn.config.Setting descendants

### ISSUE THREAD

**Issue by aawilson** [benoitc/gunicorn#2075]
I did search old issues for this, so if it's already been accepted and rejected, please direct all blame at Github.

Sometimes it's helpful for debugging purposes to be able to just dump all the settings at a go. Currently, all Settings subclasses use the default object `__repr__` (which looks like `<[module.classname] object at [memory location]>`), which isn't particularly useful. I propose that it either prepend self.value to the default (which has the advantage of showing that it is a gunicorn.config.Settings type), or that it just use the repr of self.value (which has the advantage of showing what you probably actually care about).

**Comment by benoitc** [comment]
merged. Thanks!
