### ISSUE TITLE
running gunicorn error

### ISSUE THREAD

**Issue by yxleung** [benoitc/gunicorn#2079]
ENV：python3.7.4

When I import run function,I got this error info

Traceback (most recent call last):                                                                                     
  File "/opt/python3.7.4/bin/gunicorn", line 6, in <module>                                                            
    from gunicorn.app.wsgiapp import run                                                                               
ModuleNotFoundError: No module named 'gunicorn.app'; 'gunicorn' is not a package

**Comment by DineshGuptaa** [comment]
I am facing the same issue. Please guide me how you resolved the issue

**Comment by jamadden** [comment]
In this case, it looks like the original poster had a file named `gunicorn` that was on the current (python) path and was running it. That was shadowing the actually installed version of gunicorn. The simple solution: don't name your file 'gunicorn'.

**Comment by DineshGuptaa** [comment]
I found the solution. Gunicorn need to have executable permission. That's a problem. After giving proper permission it was working fine
