### ISSUE TITLE
setproctitle isn't in extra_requires

### ISSUE THREAD

**Issue by jwhitlock** [benoitc/gunicorn#2085]
The [FAQ says](https://docs.gunicorn.org/en/latest/faq.html#how-can-i-name-processes):

> If you install the Python package setproctitle Gunicorn will set the process names to something a bit more meaningful. This will affect the output you see in tools like ``ps`` and ``top``. This helps for distinguishing the master process as well as between masters when running more than one app on a single machine. See the proc_name setting for more information.

If this was added to ``extras_require`` in ``setup.py``, then ``pip install gunicorn[gevent,setproctitle]`` or similar could pick up this optional dependency, and advertise it a little more: 

```
extras_require = {
    'gevent':  ['gevent>=0.13'],
    'eventlet': ['eventlet>=0.9.7'],
    'tornado': ['tornado>=0.2'],
    'gthread': [],
    'setproctitle': ['setproctitle'],
}
```

**Comment by tilgovi** [comment]
A PR would be most welcome. Thanks!

**Comment by berkerpeksag** [comment]
PR #2094 has been merged. Closing this as 'fixed'. Thank you for the report and for the PR!
