### ISSUE TITLE
ModuleNotFoundError: No module named 'gunicorn'

### ISSUE THREAD

**Issue by ronnielivingsince1994** [benoitc/gunicorn#2088]
Hi, 

I'm trying to use **Supervisor** to manage **gunicorn** services for my **Django** app.

I installed **gunicorn** using the command `pip3 install gunicorn` and gunicorn relevant modules were saved in `/home/ubuntu/.local/lib/site-package/gunicorn` directory (default location).

I'm not using virtual environment, and `/home/ubuntu/.local/bin` directory contains my **gunicorn** script..

```
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from gunicorn.app.wsgiapp import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```
Directly running the command `gunicorn --bind 0.0.0.0:8000 my_project.wsgi:application` works perfectly fine.

However it crashes when executed via **Supervisor**. Here is my **Supervisor** script which is crashing,

```
[program:gunicorn]
directory=/home/ubuntu/django_app
command=/home/ubuntu/.local/bin/gunicorn --workers 3 --bind unix:/home/ubuntu/django_app/app.sock my_project.wsgi:application
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn/gunicorn.err.log
stdout_logfile=/var/log/gunicorn/gunicorn.out.log

[group:gunit]
programs:gunicorn
```
Error logged in the `gunicorn.err.log` file:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/gunicorn", line 7, in <module>
    from gunicorn.app.wsgiapp import run
ModuleNotFoundError: No module named 'gunicorn'
```
I referred to issue #1588 , but no acceptable answers/finding were found there.

Any clue where I could have gone wrong?

**Comment by ronnielivingsince1994** [comment]
While writing about the issue, I thought why am I not using the virtual environment. And so I ended up setting one for myself, the **gunicorn** script is now in `/home/ubuntu/(virtual-env)/bin/gunicorn`, thats the only change I made and boom. Its working now!

Anyways shout out to @benoitc for this amazing open source project!

**Comment by IngoKl** [comment]
I was able to solve the problem by explicitly specifying the PYTHONPATH in my Supervisor config.
Specifically, I added:

`environment=PYTHONPATH=/home/user/.python-env/lib/`

**Comment by Autopaquete** [comment]
> IngoKl

no work 

[program:autopaquete_api]
command=/srv/autopaqueteapienv/bin/gunicorn_start                    ; Command to start app
user=root                                                        ; User to run as
stderr_logfile=/srv/autopaqueteapienv/logs/gunicorn_supervisor.err.log         ;Where to write log messages
stdout_logfile=/srv/autopaqueteapienv/logs/gunicorn_supervisor.out.log         ;Where to write log messages
redirect_stderr=true                                                ; Save stderr in the same log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8                       ; Set UTF-8 as default encoding
environment=PYTHONPATH=/srv/autopaqueteapienv/lib/
