### ISSUE TITLE
How to get headers from pre_reuqest

### ISSUE THREAD

**Issue by septyy** [benoitc/gunicorn#2089]
Hi, 
I want to add api interceptor in guincron pre_request hooks to get header to check token, but I can't get header from the request, so could you please help on this? Thanks.

def pre_request(worker, req):
    worker.log.debug("%s %s" % (req.method, req.path))

It seems that guincron doesn't provide header from request.

**Comment by tilgovi** [comment]
The headers should be available as `req.headers`.

I would advise you to consider implementing whatever you need to do as middleware at the WSGI level or with whatever framework you use, so that your application is less tightly coupled to Gunicorn.

**Comment by septyy** [comment]
Ok. Thanks.
