### ISSUE TITLE
Python Simplified GIL State API

### ISSUE THREAD

**Issue by djstrong** [benoitc/gunicorn#2092]
Does this problem apply also for Gunicorn https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api ? Is in Gunicorn something like `WSGIApplicationGroup %{GLOBAL}`? I am experiencing 2 times slow down of inference of TensorFlow model on CPU using Flask and Gunicorn.

**Comment by tilgovi** [comment]
I don't _think_ so, but I could be wrong. The included Gunicorn workers do not use the C Python APIs to create sub-interpreters. However, I do not know enough about the implementation of CPython to say for sure that sub-interpreters are not created implicitly by some Python-level code paths in Gunicorn.

Gunicorn itself has no C extension code.

**Comment by tilgovi** [comment]
> I am experiencing 2 times slow down of inference of TensorFlow model on CPU using Flask and Gunicorn.

Slow down as compared to what baseline? Using the TensorFlow model offline, without a web server?

**Comment by djstrong** [comment]
Yes, compared to offline use without a web server. I experience the same issue with builtin Flask development server.
What is more, there is no such difference if calculations are made on GPU.

**Comment by tilgovi** [comment]
Any other differences between the environments? Same hardware and same resource limits? Any parallelism? Can you provide your Gunicorn config?

**Comment by djstrong** [comment]
Everything is the same, my code is not using processes or threads (except tensorflow). I have profiled both environments and only tensorflow functions are slower.
I have not created/changed Gunicorn config. I am using `gunicorn -w 1 -k sync -t 3600`.

**Comment by jamadden** [comment]
You didn't mention what version of Python you're using. Under Python 2, up until the first time a Python thread is started, CPython runs the interpreter single threaded. There's no GIL and no associated overhead (there are a few other things that can turn CPython multi-threaded, like using `ctypes`). Once a second thread has been started, though, the GIL is created and there's some added overhead. I wonder if you notice a slowdown in your offline example if you create and destroy a simple dummy thread? If that's the case, setting the checkinterval very large might help.

Under Python 3, things are a bit different. The GIL is enabled all the time, but it uses a faster strategy to switch, and if it's there's no contention (just one thread running), it's still just a memory check  to determine that it doesn't need to do anything and can keep running without going through much lock release/acquire overhead. You could try adjusting the switch interval, but if the process truly is single threaded, that probably won't make much difference. (Or if you have anything that uses extra threads enabled, like gunicorn's reloader, you could try disabling them.)

https://speakerdeck.com/dabeaz/inside-the-new-gil goes into some of the details.

You could also try setting the switchinterval very high to help reduce overhead.

**Comment by djstrong** [comment]
Thank you for your help! Sorry, actually it was my mistake, I have tested offline version on the different TensorFlow model (smaller)...
Now, I don't see any overhead in web server version.
