### ISSUE TITLE
Unable to restrict insecure ciphers

### ISSUE THREAD

**Issue by pixelrebel** [benoitc/gunicorn#2096]
Perhaps someone may have some guidance for me? I have been struggling with this for a while now. Here's my environment:
```
Python 3.4.3
gunicorn==19.9.0
pyOpenSSL==18.0.0
cryptography==2.4.2
```

I'm also using the gunicorn flag --ssl-version 5
My server seems to be serving up TLS 1.2, but it allows a ton of insecure cipher suites. How can I limit the cipher suites? I tried the --ciphers flag, but had no luck with that.

Thanks!

**Comment by benoitc** [comment]
cc @berkerpeksag

**Comment by benoitc** [comment]
it's unclear for me what did't work. Do we miss some support of them internally? How it failed?

**Comment by pixelrebel** [comment]
Hi @benoitc I eventually figured this out.  It took me a while to figure out the `--ciphers` syntax.  The following combo worked for me:

`--ssl-version 5 --ciphers "ECDH+AESGCM"`

Closing this case, but it might be nice to include some examples in the docs. 

https://docs.gunicorn.org/en/stable/settings.html#ssl

The docs above link to unhelpful (broken link?) openssl documentation.
