### ISSUE TITLE
Can't successfully send http request in gunicorn

### ISSUE THREAD

**Issue by pushiqiang** [benoitc/gunicorn#2099]
When making an http request from a django views, the request will always hang on. gunicorn doesn't return any response when urllib or requests is used in docker.
but if i use django's shell or runserver, it can work good, Who can help me?

```
docker + nginx + django + gunicorn(bind unix socket) + urllib
python3.6
gevent==1.3.7
gunicorn==19.9.0

req = urllib.request.Request(url, headers=headers)
try:
    response = urllib.request.urlopen(req)
except Exception as e:
    return
```

**Comment by pushiqiang** [comment]
because I used ` bind = "unix:/tmp/run/gunicorn.sock"` , I have solved it through ` bind = "0.0.0.0:8000"`.
but i don't know why？

**Comment by benoitc** [comment]
@pushiqiang uh? if you're using a unix socket you need to read the response directly from it...

**Comment by pushiqiang** [comment]
@benoitc  thanks, but how should i read the response directly from unix socket for `response = urllib.request.urlopen(req)`

**Comment by tilgovi** [comment]
I'm not sure that urllib supports connecting to a UNIX socket. The requests library has an extension for it: https://pypi.org/project/requests-unixsocket/

Typically, if you have Gunicorn running on a UNIX socket you would have a reverse proxy, like NGINX, running on a TCP socket. The NGINX server listens for clients and forwards them to Gunicorn over the UNIX socket.

**Comment by pushiqiang** [comment]
Whether the http request in gunicorn is sent through the bound container host or socket(by `bind`)
I don't think this request that from gunicorn will go through nginx.

Thank you very much, I will continue to try it.
