### ISSUE TITLE
groups.io? 

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#2113]
I recently discovered groups.io and was thinking it could be useful to improve the communications between users and developers on Gunicorn. 

Groups IO would us to handle a group mail, sub-discussions and easy moderation. Groups.io is actually used by some foundation like the CNCF or the CI foundations. 

Thoughts?

**Comment by benoitc** [comment]
any thoughts on that ?

**Comment by tilgovi** [comment]
Let's try it out.
