### ISSUE TITLE
gunicorn restart logs out everybody

### ISSUE THREAD

**Issue by alper** [benoitc/gunicorn#2129]
I have no idea where to start debugging this but we have the behaviour that stopping the gunicorn application inside Docker removes our django database backed session from the database.

Running gunicorn outside of the container does not have this problem. Running uWSGI inside the container also does not have the problem.

Anybody else have this problem? Any hints how to approach solving this?

**Comment by alper** [comment]
Closing this since the session created with uWSGI also does not seem to survive container restart.

**Comment by benoitc** [comment]
you should make sure your env is correctly and configuration reused. How did you stop gunicorn anyway?

**Comment by alper** [comment]
Reopening because we confirmed that restarting gunicorn would log out everybody, but maybe that's not so much a gunicorn specific thing but `-k gevent`?

We swapped out that entire line for uWSGI and now we can restart the container and not be logged out.

Restarting the container is a simple Ctrl-C on `docker-compose`.

**Comment by benoitc** [comment]
did you try setting the worker via the configuration file? Why don't you restart gunicorn inside the os contained in the container?

**Comment by benoitc** [comment]
also not sure but it may be related to the way you give the args to gunicorn in the dockerfile

**Comment by alper** [comment]
The line in `entrypoint.sh` was:

```
exec gunicorn proj.wsgi --worker-tmp-dir=/dev/shm --bind=0.0.0.0 -k gevent --max-requests 1000 --max-requests-jitter 50
```

**Comment by alper** [comment]
Also, the normal behaviour that happens is that `docker-compose` starts and stops the entire container. I would expect that if the session is in the database that it then should be persistent across events such as that.

It does not seem to happen outside of Docker for some strange reason.

**Comment by benoitc** [comment]
cc @jamadden any idea?

**Comment by jamadden** [comment]
No idea, at least not without much more information. What database is being used, and what driver? How/when are the sessions supposed to be saved to the database? Is it only done on shutdown? Then perhaps something in signal handling isn't working correctly.

I can't think of anything I've encountered like that.

**Comment by benoitc** [comment]
@jamadden ok thanks :)

closing the issue  since there isn't any update since 1 month. Feel free to reopen it if needed.

**Comment by alper** [comment]
Sorry for this, to follow-up on it, I think this was caused by some weird configuration (scripts that run before application startup) on our side and poor documentation.

**Comment by ikvk** [comment]
The most common suggestion is to change the SECRET_KEY
And most likely it's static, although it's worth checking.

In my case, the problem was loading data into the "**accounts.User**" table during release with the "**loaddata**" command. 
I had a custom model inherited from the default one.

```
from django.contrib.auth.models import AbstractUser
class User(AbstractUser):
```

Possible reasons for resetting the session:
* last_login change
* user data changes, then the hash _auth_user_hash will change
* changing the user's password hash
* +it is worth checking the encoding of the data file for loaddata
