### ISSUE TITLE
19.10 release

### ISSUE THREAD

**Issue by eykd** [benoitc/gunicorn#2132]
With the merging of #2114 a couple of days ago, when can we expect to see a 19.10 release?

**Comment by tilgovi** [comment]
We are working on preparing the changelog and NEWS this week, and hopefully preparing a 20.0 release at the same time. Please subscribe to product releases with the watch function. If you'd like to help out, please feel free to familiarize yourself with the commits and changes surrounding past releases and open PRs to help us get our papers in order!

**Comment by tilgovi** [comment]
Oh, help resolving #2123 would be great, too!

**Comment by villebro** [comment]
I believe I speak for the broader community when I say that the 19.10 release is eagerly anticipated. @tilgovi is there an updated plan for the release?

**Comment by tilgovi** [comment]
Version 20 was just released this past week. We still plan another 19.x maintenance release, but if it's possible to update to version 20, that may be the best choice!

**Comment by villebro** [comment]
Thanks @tilgovi , will give it a try.

**Comment by tilgovi** [comment]
I'll re-open this, though, just to remind myself to post an update when it's done.

**Comment by eykd** [comment]
We're testing v. 20 and so far seems to be working fine for our purposes (we use both sync workers for a Django-based project and tornado workers for a tornado-based project).

**Comment by villebro** [comment]
I tested v 20 with gevent from behind an SSL terminated LB, and dynamic flask stuff worked well, but for some reason serving static content caused errors. I can open an issue with a stacktrace.

**Comment by jamadden** [comment]
> I  tested v 20 with gevent from behind an SSL terminated LB, and dynamic flask stuff worked well, but for some reason serving static content caused errors. I can open an issue with a stacktrace.

I would guess you're seeing #1925

**Comment by villebro** [comment]
Thanks @jamadden , that's precisely the error I was getting.

**Comment by tilgovi** [comment]
We'll try to fix #1925 for a v20 patch release and backport it for the forthcoming v19.x release.

**Comment by tilgovi** [comment]
19.10 is released.
#1925 is released in v20.0.2.
