### ISSUE TITLE
gunicorn socket permission error

### ISSUE THREAD

**Issue by technikamateur** [benoitc/gunicorn#2137]
Hi,
I'm using gunicorn3 on debian buster and followed your guide (http://docs.gunicorn.org/en/stable/deploy.html) for deployment with nginx and systemd.

It seems like there is a racecondition between the systemd socket unit and the creation of the runtimedir via the the service unit.

First the socket unit creates `/run/gunicorn/socket` with root as owner of the directory.
Because `/run/gunicorn/socket` is already present systemd does not create it with proper permissions and gunicorn crashes:

```
Okt 16 21:57:05 Voyager gunicorn3[1063]: Traceback (most recent call last):
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/bin/gunicorn3", line 11, in <module>
Okt 16 21:57:05 Voyager gunicorn3[1063]:     load_entry_point('gunicorn==19.9.0', 'console_scripts', 'gunicorn')()
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
Okt 16 21:57:05 Voyager gunicorn3[1063]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 223, in run
Okt 16 21:57:05 Voyager gunicorn3[1063]:     super(Application, self).run()
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 72, in run
Okt 16 21:57:05 Voyager gunicorn3[1063]:     Arbiter(self).run()
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 199, in run
Okt 16 21:57:05 Voyager gunicorn3[1063]:     self.start()
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 139, in start
Okt 16 21:57:05 Voyager gunicorn3[1063]:     self.pidfile.create(self.pid)
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3/dist-packages/gunicorn/pidfile.py", line 36, in create
Okt 16 21:57:05 Voyager gunicorn3[1063]:     fd, fname = tempfile.mkstemp(dir=fdir)
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3.7/tempfile.py", line 479, in mkstemp
Okt 16 21:57:05 Voyager gunicorn3[1063]:     return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
Okt 16 21:57:05 Voyager gunicorn3[1063]:   File "/usr/lib/python3.7/tempfile.py", line 397, in _mkstemp_inner
Okt 16 21:57:05 Voyager gunicorn3[1063]:     fd = _os.open(file, flags, 0o600)
Okt 16 21:57:05 Voyager gunicorn3[1063]: PermissionError: [Errno 13] Permission denied: '/run/gunicorn/tmpg06tvo0e'
```

After that the service is restarted and recreates  `/run/gunicorn/socket` with proper permissions but the socket file is gone, which indicates that the socket unit was not restarted.

An easy way out is to use `/run/gunicorn.socket` for the socket (and the bind flag in the gunicorn service) and dont touch the runtime dir.

Is there a way to tell the socket unit which permissions to set on the folder or should the documentation be revised?

Cheers,
Daniel

**Comment by tilgovi** [comment]
Maybe some change to the socket file that adds [`DirectoryMode`](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#DirectoryMode=)?

**Comment by vale981** [comment]
That would not change the owner of  that directory, so that the permissions would be too open!

**Comment by technikamateur** [comment]
Yes, setting DirectoryMode to 777 helps, but is a huge security risk.
The folder is created by the socket, which means as root.
As far as I know, there is now way setting the user of the folder containing the socket.
I solved the problem by using the SocketUser option and changed the path simply to /run.
Now the service creates the /run/gunicorn and everything is fine.

**Comment by tilgovi** [comment]
You could set the mode to `711` or something like this that enables traversal, but not listing files or writing. If the socket mode is correct, this should allow referring to the socket, but not overwriting it, listing the contents of the directory, or writing other files into it.

**Comment by technikamateur** [comment]
Yeah, that would also work, but I still don't think that giving 777 to a folder is an good idea. Creating the socket in /run/gunicorn.socket as root without touching _socket mode_ or _directory mode_ should be the best way.

Anyway: The example configuration in the guide, mentioned above, doesn't work for systemd. It should be corrected.

**Comment by tilgovi** [comment]
I think you're right. It's simpler that way. Both the pidfile and the socket could be created in `/var/run` and this seems like common things that daemons do. Would you please open a PR to change the systemd example? It's in `docs/source/deploy.rst`.

**Comment by technikamateur** [comment]
Yes I can. I will do it tomorrow :)

**Comment by technikamateur** [comment]
It has already been changed in PR #1950 
It just needs to be updated on the website.
