### ISSUE TITLE
Running Gunicorn using non-root user

### ISSUE THREAD

**Issue by galCohen88** [benoitc/gunicorn#2138]
Hey, I'm currently dealing with moving gunicorn from root to non-root user. 

My question is about file system permissions / usage. Besides PID file, are there any files written to the disk? for instance once a large request payload received, is it buffered to the disk?

**Comment by tilgovi** [comment]
Request and response bodies are never buffered to disk. If you bind to a UNIX domain socket, that will be a socket file on disk.

**Comment by benoitc** [comment]
> Hey, I'm currently dealing with moving gunicorn from root to non-root user.

Best practice is to start the gunicorn arbiter user as root and let workers run with a different user. 
To add to what @tilgovi  said, with a specific user yo need to check if Gunicorn has access to the temporary dir (which can be set via the options or config), the log dir and indeed the pid file.

**Comment by benoitc** [comment]
@galCohen88 fo you have more questions about it?

**Comment by galCohen88** [comment]
No, thanks
