### ISSUE TITLE
I can't run the second flask project by gunicorn

### ISSUE THREAD

**Issue by HerbertHe** [benoitc/gunicorn#2139]
## my gunicorn configure as follow:

bind = '127.0.0.1:6000'
backlog = 2048

workers = 4
worker_class = 'gevent'
worker_connections = 2000
daemon = 'false'
pidfile = '/var/run/gunicorn.pid'
accesslog = '/var/log/gunicorn_acess.log'
errorlog = '/var/log/gunicorn_error.log'
loglevel = 'warning'

## when I run the command as follow:

> gunicorn -D -c gunicorn_conf.conf app:app
> pstree -ap | grep gunicorn

but I only get the processes as before, there is no more processes added...and can't find the answer to solve

**Comment by HerbertHe** [comment]
the configure is the same one as before

**Comment by tilgovi** [comment]
Is there any output? What happens if you remove the `-D` to keep it in the foreground?

**Comment by tilgovi** [comment]
Also, is there any output in the error log?

**Comment by HerbertHe** [comment]
Thank you, I have solved this error!
