### ISSUE TITLE
Could you add a feature for supporting specific module to patch?

### ISSUE THREAD

**Issue by Catelemmon** [benoitc/gunicorn#2148]
My current project rely on [watchdog](https://github.com/gorakhargosh/watchdog) library based on [threading](https://docs.python.org/3/library/threading.html), so after `monkey.patch_all`, the watchdog doesn't works. After search in gunicorn documentation, I didn't get anything about configuring patch list. So I have to fork gunicorn and change the `monkey.patch_all()` to `monkey.patch_all(subprocess=False, thread=False)`, it works again. Have you considered  finishing the feature to add patch list in  configure file like `gunicorn.conf`.
And another question, the HEAD of master, [`os.send_file`](https://github.com/benoitc/gunicorn/blob/a05a447e76f811e67fd619e4b5e77ce808f8e917/gunicorn/workers/ggevent.py#L36) causes `flask.send_file`  to be unusable,  reset to [version19.9.0](//github.com/benoitc/gunicorn/tree/19.9.0) it works again, may it's wrong?

**Comment by tilgovi** [comment]
@Catelemmon let's take these issues separately.

I would be hesitant to expose a patch list. It's hard to guarantee that any particular setup other than patching everything won't break something in gunicorn itself. I would recommend creating a [custom application] if you need this level of control. You might also ask the watchdog project if it can function with gevent. If you are using watchdog to handle some kind of reload of Python imports, consider using the built-in `--reload` support in gunicorn.

For the `os.send_file` problem, it would be really nice if you could share a repository that reproduces the issue, or help bisect the difference between 19.9.0 and master. As we're currently preparing releases, it'd be very good to know if this is a regression and also if the regression is on the 19.x branch. Thanks for reporting this!

[custom application]: http://docs.gunicorn.org/en/latest/custom.html

**Comment by Catelemmon** [comment]
very thanks for your sugesition for the first problem.

And secondly, I tried the HEAD of master a few times to reproduce the issue, and when I try to call `flask.send_file()` like this
```python
@app.route("/download")
def download():
    return send_file("xxx.zip", as_attachment=True)
```
In fact, `xxx.zip` is a file_name or fp,  and I use  `gevent` as work class, gunicorn will catch ` RecursionError` as follow
```log
[2019-11-01 14:54:57 +0800] [125078] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/cicada/.pyenv/versions/3.6.5/envs/landau/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 111, in handle_request
    resp.write_file(respiter)
  File "/home/cicada/.pyenv/versions/3.6.5/envs/landau/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/home/cicada/.pyenv/versions/3.6.5/envs/landau/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += os.sendfile(sockno, fileno, offset + sent, count)
  File "/home/cicada/.pyenv/versions/3.6.5/envs/landau/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "/home/cicada/.pyenv/versions/3.6.5/envs/landau/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "/home/cicada/.pyenv/versions/3.6.5/envs/landau/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  [Previous line repeated 965 more times]
RecursionError: maximum recursion depth exceeded
```
and I find this error seems to be not catched first time, and it is only occured when the file is  binary, maybe checking this issue [issue](https://github.com/benoitc/gunicorn/issues/1925) will bring some inspirations.
And after comparing with HEAD and v19.9.0, differents can be detected clearly.
version 19.x is follow from [19.x](https://github.com/benoitc/gunicorn/blob/2bf26c1c86472b50508155a8ffde6c80e91099bc/gunicorn/workers/ggevent.py#L35)
```python
### version 19.x
from gevent.socket import wait_write, socket
import gunicorn
from gunicorn.http.wsgi import sendfile as o_sendfile
def _gevent_sendfile(fdout, fdin, offset, nbytes):
    while True:
        try:
            return o_sendfile(fdout, fdin, offset, nbytes)
        except OSError as e:
            if e.args[0] == errno.EAGAIN:
                wait_write(fdout)
            else:
                raise
```
HEAD of master is follow, from [master](https://github.com/benoitc/gunicorn/blob/a05a447e76f811e67fd619e4b5e77ce808f8e917/gunicorn/workers/ggevent.py#L33)
```python
from gevent import hub, monkey, socket, pywsgi
def _gevent_sendfile(fdout, fdin, offset, nbytes):
    while True:
        try:
            return os.sendfile(fdout, fdin, offset, nbytes)
        except OSError as e:
            if e.args[0] == errno.EAGAIN:
                socket.wait_write(fdout)
            else:
                raise
```
maybe python `os.sendfile(fdout, fdin, offset, nbytes)` function causes this problem? version 19.x seems to base on libc? I have no idea.

**Comment by tilgovi** [comment]
There is discussion of the sendfile issue in #1925. Can we close this and continue over there?

**Comment by Catelemmon** [comment]
This problem seems to be solved I'll close this issue. very thx.
