### ISSUE TITLE
How gunicorn behave with multiple bind addresses

### ISSUE THREAD

**Issue by myaser** [benoitc/gunicorn#2151]
when binding gunicorn to multiple addresses it means there are multiple tcp backlogs
requests coming to different addresses are piled up into different backlogs
my question is how the workers handle the load from different backlogs? are they doing any balancing like round robin or what?

**Comment by benoitc** [comment]
It doesn't change we are binding for one or more sockets. The system will load balance the connections between processes waiting for one.
