### ISSUE TITLE
v20 release

### ISSUE THREAD

**Issue by bboe** [benoitc/gunicorn#2153]
Hi,

I see that the news file was updated to state v20 was released on 10/30, however, such a release doesn't yet appear to exist. Perhaps there's more to a release, but if not I merely wanted to point it out.

Thanks!

**Comment by benoitc** [comment]
yes. people got side tracked ;) Howerver 2.0 is on pypi now. Only doc has stil to be updated and may require some delay for the announce:  #2158.

**Comment by benoitc** [comment]
fixed. 20.0 is public.
