### ISSUE TITLE
RecursionError in v20.0.0 from Docker

### ISSUE THREAD

**Issue by FSalazarH** [benoitc/gunicorn#2164]
I'm developed several python web services from Docker-compose, I'm using following Docker images:

* python:3.7
*  nginx:1.13.3

So I'm create two services (containers) that communicates between them. 

We have no errors until today, and I think that the error is the version of gunicorn that in my requirements.txt is being used (was a gunicorn without specified version). 

So in the latest days, after remove containers and images, it was installed the latest version of gunicorn (that's a fact) v20.0.0, and we have now errors like this:

`nginx    | 172.19.0.1 - - [11/Nov/2019:19:21:55 +0000] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 0 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"
nginx    | 2019/11/11 19:21:55 [error] 6#6: *10 upstream prematurely closed connection while reading upstream, client: 172.19.0.1, server: docker_flask_gunicorn_nginx, request: "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1", upstream: "http://172.19.0.2:8888/swaggerui/swagger-ui-standalone-preset.js", host: "localhost", referrer: "http://localhost/"`

`api      | [2019-11-11 19:21:55 +0000] [12] [DEBUG] GET /swaggerui/favicon-16x16.png
api      | [2019-11-11 19:21:55 +0000] [12] [ERROR] Error handling request
api      | Traceback (most recent call last):
api      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 111, in handle_request
api      |     resp.write_file(respiter)
api      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
api      |     if not self.sendfile(respiter):
api      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
api      |     sent += os.sendfile(sockno, fileno, offset + sent, count)
api      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
api      |     return os.sendfile(fdout, fdin, offset, nbytes)
api      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
api      |     return os.sendfile(fdout, fdin, offset, nbytes)
api      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile 
api      |     return os.sendfile(fdout, fdin, offset, nbytes)
api      |   [Previous line repeated 868 more times]
api      | RecursionError: maximum recursion depth exceeded
`

The command that I used to run the application over gunicorn from docker-compose is this:

`gunicorn --worker-class gevent --timeout 1000 --graceful-timeout 10000 --log-level debug -w 5 -b :8888 manage:app`

I have a manage.py file (flask_script) from which I create the app, and it's work. 

## Resolution

Specify v19.9.0 for gunicorn in requirements.txt solve the issue for now. 

Is an issue in v20.0.0? or there is something wrong with what I did?

**Comment by mattbriancon** [comment]
For what it's worth, I suspect this isn't related to Docker. A service I work on updated to Gunicorn 20 and we saw the same error (Python 3.7.4, gevent 1.4.0, gunicorn 20.0.0). Interestingly, we only see the issue when we serve a static file from Django with Whitenoise.

http://whitenoise.evans.io/en/stable/

**Comment by jamadden** [comment]
Thanks for the report! Yes, this is definitely a bug in gunicorn; Closing in favor of the earlier report https://github.com/benoitc/gunicorn/issues/1925
