### ISSUE TITLE
gunicorn times out starting with systemd service Type=notify

### ISSUE THREAD

**Issue by darthmall** [benoitc/gunicorn#2165]
I think there might be some missing or incorrect info in the docs on monitoring with systemd.

The example configuration for `gunicorn.service` includes

```
[Service]
Type=notify
```

When I follow the example and set up `gunicorn.service` like this, it times out whenever I try to start it.

According to the [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=), when setting `Type=notify` "it is expected that the service sends a notification message via sd_notify(3) or an equivalent call when it has finished starting up." I presume gunicorn is not doing this, because if I remove `Type=notify` from my configuration, everything works just fine.

Is there some flag that needs to be passed when executing gunicorn to cause it to notify systemd that it has started, or is it a mistake that the example starts the service as `Type=notify`?

**Comment by tilgovi** [comment]
What version of Gunicorn? Support for `sd_notify` was added in #1897, which is only on the v20 releases.

**Comment by darthmall** [comment]
Ah, that could be the problem. I've got 19.9.0 on this server.

**Comment by benoitc** [comment]
i recently installed a 19.10 and i can confirm . you should use the old install process with systemd.

**Comment by bastiencyr** [comment]
I had the same problem on Debian 10 but starting from Debian 11, gunicorn is upgraded to 20.1 : https://packages.debian.org/fr/bullseye/gunicorn . 
I have simply change type=notify to simple. Btw, why not keep type=simple ? After all, the socket file is configured, so systemd doesn't need to wait the service is ready.  The main issue is that the systemd start command will not show any error if the User or the binary file doesn't exist. So maybe type=exec is the better solution.

**Comment by javabrett** [comment]
Closing, `Type=notify` support was added in Gunicorn 20.0.
