### ISSUE TITLE
Clarify request distribution and worker ordering

### ISSUE THREAD

**Issue by seizethedave** [benoitc/gunicorn#2168]
I am running Gunicorn with 7 Eventlet workers and 64 max green threads each.

Once an HTTP request comes in to the listening address/port, what determines which worker will accept the request? My read of the code is that each of the 7 workers will have a 64-wide GreenPool, all blocked on `accept`. Could it be that the first worker fortunate enough to start up will have all 64 of its workers at the front of that queue? Don't know if there's a O/S level queue ultimately dictating the request balancing - that's exactly what I want to learn.

Thanks!

**Comment by tilgovi** [comment]
I believe this is unspecified and varies at the OS level.

Changing the way `accept()` distributes connections has been discussed in Linux and ultimately some changes were made that are opt-in by using `SO_REUSEPORT`, exposed in Gunicorn as `--reuse-port`. Here's a starting point for reading about this: https://lwn.net/Articles/542629/

**Comment by seizethedave** [comment]
Thanks!
