### ISSUE TITLE
SSL Key and Cert Strings instead of file path

### ISSUE THREAD

**Issue by smiles3983** [benoitc/gunicorn#2174]
Is it possible to pass to gunicorn, the private key and cert strings instead of the file paths?

**Comment by smiles3983** [comment]
or better yet, the ability to pass a key pair and password, and have gunicorn do the work to separate the key and the cert.

**Comment by tilgovi** [comment]
I don't think it is possible right now. In light of #2076 let's be careful if we do this that we don't accidentally end up with the possibility of dumping key material into logs during a crash or something.

**Comment by smiles3983** [comment]
Or, be able to handle key stores.  That would make my life easier. We have a new key store server that gives me 4 different options, but I have to extract the private key and cert, store them to files and then reference them to gunicorn. So if it accepted a key store and password then that would be easier.

**Comment by tilgovi** [comment]
Is it possible to handle fetching the key and cert from the keystore and then setting it inside a `gunicorn.conf.py`? You'd still have to store it locally, but securing file permissions is maybe easier than securing the command line from being seen in `ps` output :-D.

**Comment by javabrett** [comment]
This should be enabled with access to provide `cadata` via [`SSLContext.load_verify_locations(cafile=None, capath=None, cadata=None`](https://docs.python.org/3/library/ssl.html?highlight=sslkeylogfile#ssl.SSLContext.load_verify_locations) as part of `SSLContext` extension access via #2649 .
