### ISSUE TITLE
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors

### ISSUE THREAD

**Issue by blcksrx** [benoitc/gunicorn#2177]
I use **gunicron** with **async** worker class using **gevent** and it returns this error:
```
/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py:53: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.contrib.pyopenssl (/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py)']. 
  monkey.patch_all()
```
And because of this error, the gunicorn workers can't boot up!

**Comment by jamadden** [comment]
That's just a warning. What's stopping the workers from running? Do you have PYTHONWARNINGS=error or something?

**Comment by blcksrx** [comment]
> That's just a warning. What's stopping the workers from running? Do you have PYTHONWARNINGS=error or something?

**Comment by benoitc** [comment]
@blcksrx why did you reopened it?

**Comment by benoitc** [comment]
is there anything to do there?

**Comment by benoitc** [comment]
closing issue since it was answered

**Comment by allen-munsch** [comment]
i got the "warning" by using the `--preload` flag

**Comment by rdpravin1895** [comment]
What does this warning signify? Will the libraries that did not get monkey patched not work as expected?

**Comment by spex66** [comment]
thx @allen-munsch for the pointer!
in our case:
- we had the recursion-issue reusing a gunicorn project, but switched to single-process + threaded (for scaling k8s replicas instead)
```
      - --workers=1
      - --worker-class=gevent
      - --worker-connections=1000
```

- the former project used a `--config=/gunicorn.conf.py` which set the `preload_app = True`
- removed it and 
  - the DEBUG warning on startup is gone 
  - and app works w/o recursion error

What a mess this debugging was!
Hopefully working now as expected :)
