### ISSUE TITLE
Version 20.0.0 errors out on solaris (SmartOS) getting getsockopt 

### ISSUE THREAD

**Issue by gaige** [benoitc/gunicorn#2184]
The backwards compatibility function in gunicorn.socketfromfd fails in SmartOS, due to a naming difference in the getsockopt function in libc.  In SmartOS (19.3.0), it is in a _so namespace, and thus is at `libc._so_getsockopt` instead of `libc.getsockopt`.

I've got a working patch which checks for `SunOS` platform and uses the correct symbol, and I'll submit a pull request.

**Comment by benoitc** [comment]
can you send a PR for it?

**Comment by gaige** [comment]
Yeah, I did the PR earlier, just didn't know how to link it.

https://github.com/benoitc/gunicorn/pull/2185

**Comment by benoitc** [comment]
thanks! just comited it in master

**Comment by gaige** [comment]
Thank you!
