### ISSUE TITLE
Requests go to blocked worker using gthread worker class with 1 thread

### ISSUE THREAD

**Issue by vasa-chi** [benoitc/gunicorn#2191]
An example Flask app:

```python
import time

from flask import Flask

app = Flask(__name__)


@app.route('/slow')
def slow():
    time.sleep(100)
    return ''


@app.route('/fast')
def fast():
    return ''
```

If I run it with `gunicorn --workers 4 --threads 1 --worker-class gthread app:app` (multiple workers, one thread each), and issue a request to `/slow`, then requests to `/fast` are often stuck on the worker that is processing the request to `/slow`.

If I use more then one thread, even with one worker, requests are steadily routed to free worker threads.

Is this expected?

**Comment by vasa-chi** [comment]
```
Linux buster 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

```
Flask==1.1.1
gunicorn==20.0.0
```

**Comment by benoitc** [comment]
you have 1 thread and multiple workers it would be better to use the sync worker. Anyway in this setup you can run at most 4 concurrent connections. So it's kind of excepted unless I miss some details?

**Comment by vasa-chi** [comment]
Well, yes. But why **1 worker 4 threads** setup processes multiple parallel requests completely fine, and **4 workers 1 thread** setup almost always routes request to busy worker and they get stuck there?

**Comment by jamadden** [comment]
On Linux, load distribution of requests to sockets isn't fair unless you use `SO_REUSEPORT`. The backlog also comes into play. There was a discussion with links at #2183.

**Comment by benoitc** [comment]
Also the GIL may enter in action. I think at some point we may want to have the reloader in its own process instead of a thread. That would help us to reuse the logic of graceful shutdown and co. Maybe worth a new ticket? @tilgovi @jamadden

**Comment by benoitc** [comment]
@vasa-chi in the case "1 worker 4 threads" the worker is asynchronous so it may be able to accept more requests at a time, where in the case "4 workers, 1 threads", accepting is in blocking mode, so once a worker accepted a connection it will block until the request is processed. 

So yes it's expected.

**Comment by benoitc** [comment]
closing as answered. Feel free to reopen it if you need more details.
