### ISSUE TITLE
How gunicorn selects worker for each task?

### ISSUE THREAD

**Issue by carter54** [benoitc/gunicorn#2192]
I have a question when using gunicorn gthread worker type.
the basic configs I have are as follow:
```
worker_class = gthread
workers = 20
threads = 1
max_requests = 50000
max_requests_jitter = 3 
timeout = 70
graceful_timeout = 30
limit_request_line = 0
limit_request_fields = 200
limit_request_fields_size = 0
preload_app = True
```
As in the config, I set 20 workers, which can be seen when I start the test
![image](https://user-images.githubusercontent.com/26741594/69402172-00baf600-0d32-11ea-8974-c6b8707d695d.png)
each worker only has one thread.
Then I sent 3 groups of test, each group has 4 concurrent post requests. From the document, I understand that 20 workers should be able to handle 20 concurrent tasks at the same time. However, I found that one worker is used twice (for two tasks) in the test, which causedthe second task did not start until the first task had finished. I'm wondering why didn't gunicorn choose free worker to handle the second task? (there should be some free workers in this situation)  

following figures shows some details of my test:
the response time obtained from the post side.
![image](https://user-images.githubusercontent.com/26741594/69402963-51cbe980-0d34-11ea-9db5-3c72bdd67242.png)
the actual processing time in each workers (from gunicorn log):
![image](https://user-images.githubusercontent.com/26741594/69403046-8f307700-0d34-11ea-89d7-fab5b3092845.png)
from these two figures, it is clear that the response time of the 11th requests from post side (0.41s) is different with the actual processing time in the worker (0.25s). To figure out the reason, I found that the 9th and 11th requests used the same woker with pid 56596. This also happened for 5th, 7th and 8th requests. Why did gunicorn ignore other free wokers?

Anying wrong in my config settings? What's  the logic in gunicorn to select wokers for each task?

Thanks for any help in advance!

**Comment by benoitc** [comment]
Gunicorn doesn't select the process able to accept a connection. Balancing of requests is done at the OS level. Each free worker is waiting to accept a socket in the backlog.

See the [design](http://docs.gunicorn.org/en/stable/design.html) page for more information.

**Comment by benoitc** [comment]
also thre is no need to use the threading worker if you have only 1 thread. The sync worker is more efficient.
