### ISSUE TITLE
what happens when backlog is full?

### ISSUE THREAD

**Issue by a70babat** [benoitc/gunicorn#2200]
backlog settings will set "The maximum number of pending connections."
what happens when a worker receive connection after backlog is full? which status code is returned?

Also is there anyway to see how many connections are pending?

**Comment by jamadden** [comment]
The socket backlog is handled entirely by the TCP stack in the operating system. Thus, gunicorn has no ability to set a status code (it can't return an HTTP response at all, as HTTP is built on top of TCP) --- gunicorn never even knows about pending connections. The TCP stack will simply refuse the connection, I think, but the exact details are probably operating system dependent (on both client and server). Likewise, knowing the state of any pending connections is operating system dependent. Tools like `lsof` and `netstat` may provide information.

**Comment by a70babat** [comment]
thank you.
