### ISSUE TITLE
OSError: getsockaddrlen: bad family starting 20.0.3 with systemd and unix socket

### ISSUE THREAD

**Issue by shorton3** [benoitc/gunicorn#2207]
I am building a new Centos VM from scratch, pulling packages from pip. Previous VM builds worked. I am getting the following error, which makes me believe it is trying to bind to ipv6 somewhere, but I am starting gunicorn using a systemd service file binding to a systemd socket file.  My gunicorn invocation line in the systemd service file is:

ExecStart=/usr/local/bin/gunicorn --pid /run/gunicorn/app.gunicorn.pid --worker-tmp-dir /tmpfs-gunicorn --bind unix:/run/gunicorn/app.gunicorn.socket --chdir /home/centos/app --config /home/centos/app/gunicorn.py app:app

Any ideas what has changed to cause this?  Thank you!

Nov 25 22:49:26 test1125c-centos-server gunicorn: [2019-11-25 22:49:26 +0000] [30028] [INFO] Starting gunicorn 20.0.3
Nov 25 22:49:26 test1125c-centos-server gunicorn: Traceback (most recent call last):
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/bin/gunicorn", line 11, in <module>
Nov 25 22:49:26 test1125c-centos-server gunicorn: sys.exit(run())
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
Nov 25 22:49:26 test1125c-centos-server gunicorn: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
Nov 25 22:49:26 test1125c-centos-server gunicorn: super().run()
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
Nov 25 22:49:26 test1125c-centos-server gunicorn: Arbiter(self).run()
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 198, in run
Nov 25 22:49:26 test1125c-centos-server gunicorn: self.start()
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 155, in start
Nov 25 22:49:26 test1125c-centos-server gunicorn: self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
Nov 25 22:49:26 test1125c-centos-server gunicorn: File "/usr/local/lib/python3.6/site-packages/gunicorn/sock.py", line 172, in create_sockets
Nov 25 22:49:26 test1125c-centos-server gunicorn: sock_name = sock.getsockname()
Nov 25 22:49:26 test1125c-centos-server gunicorn: OSError: getsockaddrlen: bad family

**Comment by benoitc** [comment]
from which version are you upgrading?

**Comment by shorton3** [comment]
I last built a VM about 4-5 weeks ago, and my automation installed 19.9.0 gunicorn from pip. Thanks
    On Monday, November 25, 2019, 05:00:51 PM CST, Benoit Chesneau <notifications@github.com> wrote:  
 
 
from which version are you upgrading?

**Comment by benoitc** [comment]
I confirm the issue. The code checking from the file descriptor type is not cross platform. A fix should land today.

**Comment by shorton3** [comment]
Thank you!
    On Monday, November 25, 2019, 06:53:48 PM CST, Benoit Chesneau <notifications@github.com> wrote:  
 
 
I confirm the issue. The code checking from the file descriptor type is not cross platform. A fix should land today.

**Comment by dangelsaurus** [comment]
same here. excited to see there's a fix in the works!

**Comment by benoitc** [comment]
please test  #2208  and let me know :)

**Comment by q121212** [comment]
trhe same problem after update gunicorn module today

**Comment by benoitc** [comment]
@q121212 did you try #2208 ?

**Comment by dangelsaurus** [comment]
2208 fixed it for me

**Comment by benoitc** [comment]
fixed in latest master. release is coming

**Comment by benoitc** [comment]
20.0.4 is out

**Comment by dvtan** [comment]
haha this is so cool, I've been stuck on this all day, thought I made a mysterious breaking change in my project... then I thought to check the issue tracker, and it just got fixed!

That's what I get for not specifying versions in my setup script lol

**Comment by q121212** [comment]
in my case rollback to version 19.9.0 helped me.  there was no time to test fix https://github.com/benoitc/gunicorn/pull/2208

**Comment by benoitc** [comment]
@q121212 well this is not really hepful. Anyway problem is fixed. You can also upgrade to 19.10 is you  don't want to go yet on 20.x.
