### ISSUE TITLE
Unable to run subprocess

### ISSUE THREAD

**Issue by AtulCIS** [benoitc/gunicorn#2212]
Hi I am working on Django and used gunicorn for its deployment. When I run my Django server with Django's "python manage.py runserver" my subprocess works file, but when I use gunicorn my subprocess is not working. 
In this subprocess, I am converting .docx file to pdf with LibreOffice headerless command. The error says unable to find LibreOffice. I have updated its path to an absolute path and added symlink also. It can not be a LibreOffice command since a simple "ls" command is not working with subprocess. I am using Ubuntu 18.04 on the server.
Please help me with this. Thanks in advance.

**Comment by tilgovi** [comment]
What worker type?

**Comment by AtulCIS** [comment]
This is what my service is looks like 

[Unit]
Description=Gunicorn instance to serve myproject
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/root/form_builder
Environment="PATH=/root/form_builder/.county_form/bin"
ExecStart=/root/form_builder/.county_form/bin/gunicorn --workers 10 --bind unix:county_form.sock --access-logfile /root/form_builder/logs/gunicorn-access.log --error-logfile /root/form_builder/logs/gunicorn-error.log --log-level warn --timeout 3600 -b 0.0.0.0:8001 --limit-request-line 0 --limit-request-field_size 0 county_form.wsgi:application

[Install]
WantedBy=multi-user.target

**Comment by jamadden** [comment]
Can you post the full exception and traceback you get?

**Comment by AtulCIS** [comment]
I am using a package preview-generator to generate the pdf from .docx file and having this error.

Command '['libreoffice', '--headless', '--convert-to', 'pdf:writer_pdf_Export', '/root/form_builder/static/temp_folder/d2f851423dd1fecb2ed535c04a603705.pdf.docx', '--outdir', '/root/form_builder/static/temp_folder/', '-env:UserInstallation=file:///tmp/LibreOffice_Conversion_${USER}']' returned non-zero exit status 127

This package runs a subprocess and uses LibreOffice to generate pdf.

**Comment by jamadden** [comment]
>> The error says unable to find LibreOffice. I have updated its path to an absolute path and added symlink also. 

> Command '['libreoffice', '--headless', '--convert-to', 'pdf:writer_pdf_Export', '/root/form_builder/static/temp_folder/d2f851423dd1fecb2ed535c04a603705.pdf.docx', '--outdir', '/root/form_builder/static/temp_folder/', '-env:UserInstallation=file:///tmp/LibreOffice_Conversion_${USER}']' returned non-zero exit status 127

That doesn't look like a full path to `libreoffice`. Since you're explicitly setting the `PATH` environment variable to only be a single directory, I guess you have the executable `libreoffice` (and anything it needs to launch) installed in `/root/form_builder/.county_form/bin`?

**Comment by AtulCIS** [comment]
I have created symlink for libreoffice and also tried full path which is /usr/sbin/libreoffice. If I run this command gunicorn --bind 0.0.0.0:8001 county_form.wsgi:application, then subprocesses works fine.
 
When using a custom subprocess which is only to list the directory "ls", I am having error command not found.

**Comment by jamadden** [comment]
Exit status 127 is what the shell sets when a command isn't found.

Directly running the command from your login shell is very different than running it as a systemd service. The environments will be very different. For instance, directly running the command will inherit your PATH, which very likely includes `/bin`, which is where `ls` is usually found. But your systemd process is setting a specific PATH that doesn't include that directory. You need to either use the full (absolute) path or set an appropriate PATH environment variable.

If you can get `ls` to work using a full path, but you can't get `libreoffice` to work using a full path, it's likely that `libreoffice` is trying to launch other commands. For example, it could be implemented as a shell script or launch helper executables (on my system, libreoffice comes with a python executable it can launch). Setting a more inclusive PATH variable may be the only option.

If you can't get even `ls` to work using a full path, can you post the output of actually using a full (absolute) path to the executable for both it and `libreoffice`? Please include the traceback and any other associated output.

**Comment by AtulCIS** [comment]
Hi @jamadden, I have tried ls with full path and it works. Still, LibreOffice is not working for me.

b'/usr/sbin/libreoffice: 46: /usr/sbin/libreoffice: dirname: not found\n/usr/sbin/libreoffice: 48: /usr/sbin/libreoffice: basename: not found\n/usr/sbin/libreoffice: 49: /usr/sbin/libreoffice: ls: not found\n/usr/sbin/libreoffice: 49: /usr/sbin/libreoffice: sed: not found\n/usr/sbin/libreoffice: 51: /usr/sbin/libreoffice: dirname: not found\n/usr/sbin/libreoffice: 138: /usr/sbin/libreoffice: grep: not found\n/usr/sbin/libreoffice: 144: /usr/sbin/libreoffice: uname: not found\n/usr/sbin/libreoffice: 180: exec: /root/form_builder/static/temp_folder/2/oospla

I have added the full path of LibreOffice but it does not work. I am new in python. So can you explain to me how I can fix this?

**Comment by jamadden** [comment]
That output strongly suggests that `/usr/sbin/libreoffice` is a shell script that invokes other commands. You need to have those commands all available. Using the correct PATH is probably the easiest way to do this.

At any rate, this doesn't seem to be a gunicorn issue.
