### ISSUE TITLE
Gunicorn worker shared class

### ISSUE THREAD

**Issue by abhishekduttagupta** [benoitc/gunicorn#2216]
Hello,

I would like to know how we can share class/context across different gunicorn?
That means suppose I have a class which is getting created and updated by worker 1, and 2nd worker is trying to fetch it first and then update it?

What is the way possible to achieve this in gunicorn?

**Comment by jamadden** [comment]
Beyond preloading the application, which shares a certain amount of memory and class data that is *copied* by each worker, gunicorn doesn't have any mechanism for sharing data between workers (and preloading does nothing about updating data). That is, gunicorn doesn't provide any IPC facilities. You'll need to pick and implement a method appropriate to your application.

 Some people use a shared database like Redis or MySQL/PostgreSQL, often with subscribers/listeners. Others use libraries like 0MQ to establish sockets between workers and communicate that way.

**Comment by jeffin143** [comment]
why don't we inland support that, I mean ship an api, Which has some way to communicate across workers

Or at least let's mention that in docs, Like Data sharing across workers aren't there, I wasted a whole week just debugging why My code didn't break in dev mode and broke using unicorn

Skimmed through the docs but couldn't find and apt ans, Thanks to this issue 

Re wrote the code using Redis Django
