### ISSUE TITLE
Add milliseconds to access logs when logging request time.

### ISSUE THREAD

**Issue by Anmar85** [benoitc/gunicorn#2217]
I need to log the request time in milliseconds and as per Gunicorn [settings](https://docs.gunicorn.org/en/stable/settings.html#access-log-format ) I can either use seconds , microseconds or decimal seconds.
It should be a simple 1 line change and another couple of lines to document it.
Would that be possible?

**Comment by mirobertod** [comment]
#2218

**Comment by tilgovi** [comment]
Fixed by #2218.
