### ISSUE TITLE
How does gunicorn prevent Slow HTTP Attacks?

### ISSUE THREAD

**Issue by BofengDuke** [benoitc/gunicorn#2222]
Dose gunicorn has some measures to prevent Slow HTTP Attacks like Apache?

**Comment by tilgovi** [comment]
Can you expand on what kind of attacks, in particular, you are thinking about?

**Comment by benoitc** [comment]
@BofengDuke was the issue answered?

**Comment by benoitc** [comment]
if you were talking about https://blog.qualys.com/securitylabs/2011/11/02/how-to-protect-against-slow-http-attacks apart not implementing the rate check (which is kind of hard to figure anyway) yes. Also the worker will timeout if a request is too long. In any case it is advised to run gunicorn behind a buffering proxy like nginx .  

Please next time care to elaborate there. It's kind of rude to close an issue like this after we asked for more details.

**Comment by BofengDuke** [comment]
@benoitc I am sorry abort closing issue. 
Yeh, what I want to talk about is a mechanism similar to https://blog.qualys.com/securitylabs/2011/11/02/how-to-protect-against-slow-http-attacks.
I found gunicorn has not implementing such a mechanism，so I close this issue.

**Comment by benoitc** [comment]
This is untrue. Timeout, Backlogs are handled and the values can be changed. It's the responsibility of the application to reject http verb if they need to be rejected not gunicorn. For the  "minimum incoming data rate" i find this solution quite impracticable , in real world it is expected that some connections may be slow., but this can be added optionnaly.
