### ISSUE TITLE
PyPy: module 'os' has no attribute 'sendfile'

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [benoitc/gunicorn#2223]
#2172  seems to cause the following error with PyPy.

```
  File "xxx/pypyenv/site-packages/gunicorn/workers/ggevent.py", line 33, in <module>
    def _gevent_sendfile(fdout, fdin, offset, nbytes, _os_sendfile=os.sendfile):
AttributeError: module 'os' has no attribute 'sendfile'
```

**Comment by javabrett** [comment]
Please confirm your platform and python versions.

**Comment by HIRANO-Satoshi** [comment]
The latest PyPy, 7.3.0 on Mac OS X 10.14.6.

Since PyPy does not have os.sendfile, `_os_sendfile=os.sendfile` causes the error when ggevent.py is imported.

```
$ pypy
Python 3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:17)
[PyPy 7.3.0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import os
>>>> os.sendfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'sendfile'
>>>> 
```

**Comment by jamadden** [comment]
I think gunicorn uses `os.sendfile` because it was added back in Python 3.3, and before that there were some third-party packages that provided a similar function to call the operating system. 

Python 3.5, however, added `socket.socket.sendfile()` as a member function to socket objects. This is a higher level, portable, abstraction. PyPy *does* implement `socket.sendfile`; more importantly, gevent monkey-patches `socket.sendfile` (and presumably eventlet does too). So perhaps the simplest thing to do here is to have gunicorn drop its own monkey-patches for os.sendfile and simply use `self.sock.sendfile()`?

https://github.com/benoitc/gunicorn/blob/9c1438f013cdc0771640961ed3562599a1359aed/gunicorn/http/wsgi.py#L351-L393

**Comment by tilgovi** [comment]
@jamadden you've been closer to the recent churn around sendfile than I have. Is there any reason we didn't do this before? Is it just because we hadn't pushed the minimum version to 3.5?

**Comment by javabrett** [comment]
@jamadden  thanks for the analysis. I’ll take a look. I’m unassigning myself for now but can pick this up again if it makes sense.

**Comment by jamadden** [comment]
> Is there any reason we didn't do this before? Is it just because we hadn't pushed the minimum version to 3.5?

For #2172 we applied the simplest, least invasive fix possible in order to get a release ready. 

Also, it simply hadn't occurred to me 😄

**Comment by HIRANO-Satoshi** [comment]
@jamadden Thanks.

**Comment by sumanthratna** [comment]
This is still an issue for me with:
- gunicorn (version 20.0.4)
- PyPy 7.3.1 (Python 3.6.9)

**Comment by berkerpeksag** [comment]
@sumanthratna this has been fixed in master branch. We haven't released it on PyPI yet.

**Comment by OnePieceLv** [comment]
> @sumanthratna this has been fixed in master branch. We haven't released it on PyPI yet.

there is same issue
 - gunicorn version 20.0.4
 - PyPy 7.3.0 (Python 3.6.9)
when can I pip install latest version？

**Comment by sumanthratna** [comment]
> > @sumanthratna this has been fixed in master branch. We haven't released it on PyPI yet.
> 
> 
> 
> there is same issue
> 
>  - gunicorn version 20.0.4
> 
>  - PyPy 7.3.0 (Python 3.6.9)
> 
> 
> 
> when can I pip install latest version？

try:

```sh
python -m pip install "git+https://github.com/benoitc/gunicorn.git@master
```

**Comment by OnePieceLv** [comment]
> > > @sumanthratna this has been fixed in master branch. We haven't released it on PyPI yet.
> > 
> > 
> > there is same issue
> > 
> > * gunicorn version 20.0.4
> > * PyPy 7.3.0 (Python 3.6.9)
> > 
> > when can I pip install latest version？
> 
> try:
> 
> ```shell
> python -m pip install "git+https://github.com/benoitc/gunicorn.git@master"
> ```

thanks, fixed.
when will it released on PyPI

**Comment by OnePieceLv** [comment]
> @sumanthratna this has been fixed in master branch. We haven't released it on PyPI yet.

when will it released on PyPI yet

**Comment by tilgovi** [comment]
@OnePieceLv you can watch releases of this project. When we make a release, GitHub will notify you.
