### ISSUE TITLE
How can I report a security issue?

### ISSUE THREAD

**Issue by ZeddYu** [benoitc/gunicorn#2224]
How can I report a security issue? It seems security@gunicorn.org could be found at the moment.

**Comment by berkerpeksag** [comment]
First of all, thank you for wanting to make Gunicorn safer! You can email me directly by using the email address in my profile. Then I'll ping the rest of the team off-list. Please note that we are in the middle of holiday season, so it may take a while to process your findings.

**Comment by berkerpeksag** [comment]
We got in touch with @ZeddYu and am closing this issue for now.
