### ISSUE TITLE
gunicorn: error: unrecognized arguments:

### ISSUE THREAD

**Issue by casspop** [benoitc/gunicorn#2231]
#1867 was closed, so I opened this one in case it helps anyone else.

I struggled for hours getting this error:
`gunicorn: error: unrecognized arguments: --bind=unix:/home/greg/out/gunicorn.sock out:app
[2020-01-04 20:03:24 -0600] [2122] [INFO] Worker exiting (pid: 2122)` 

It was quite frustrating because I have gunicorn running perfectly on another Raspberry Pi with a very similar configuration.  Anyway, after much head-banging, I finally stumbled across Issue #1867 which prompted me to double-check my broken code.  Sure enough, I was trying to use the 'argparse' module in my Flask app.  When I removed it, the gunicorn error went away.

**Comment by casspop** [comment]
It could be that was some sort of rookie mistake, I don't know.  At any rate, I wanted to document it here in case someone else was searching for an answer.

**Comment by wksuixin** [comment]
Add the parameters used by gunicorn to the program, such as：

**Comment by wksuixin** [comment]
Add the parameters used by gunicorn to the program, such as：parser.add_argument("--bind", type=str, default=False)

**Comment by WenQinghua** [comment]
> Add the parameters used by gunicorn to the program, such as：parser.add_argument("--bind", type=str, default=False)

Thank you very much!
