### ISSUE TITLE
Bounty/Patreon/Sponsor support?

### ISSUE THREAD

**Issue by dumblob** [benoitc/gunicorn#2235]
Any bounty/Patreon/sponsoring possibilities?

Even GitHub supports a [sponsor button](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository ). Speaking for myself, I'd like to sponsor some SSL advancements in "bounty-like" manner - i.e. if developers will consent to prioritize issues chosen by me and will implement them in an acceptable time frame (agreed beforehand), they'll get a bounty from me :wink:.

**Comment by benoitc** [comment]
This kind of approach is planned. .Chek the github soon.
