### ISSUE TITLE
Send Http error code to client on worker timeout

### ISSUE THREAD

**Issue by nadwir** [benoitc/gunicorn#2236]
Hi,

I would like to send an Http error code to the client, if a gunicorn timeout occurred. I found the server hook "worker_abort", which seems suitable to me.
How can I use it to send back an http error code?

My server start-up looks like this (in Dockerfile):
gunicorn --timeout 60 --workers=${N_WORKERS-2} -b 0.0.0.0:3000 --log-level=${LEVEL} --config gunicorn_config.py 'app:create_app(config="ProductionConfig")'

**Comment by benoitc** [comment]
The worker timeout happen only when it's too much busy to notify the arbiter it's alive. Ie. when the application is busy or when an unknown error happened. So it is not possible to send an error directly from the app. 

If Gunicorn is behind a proxy you can configured it to send the correct answer (502), which is the default for nginx or haproxy.

**Comment by benoitc** [comment]
no activty since awhile. Closing the issue then.
