### ISSUE TITLE
Disabling access logs

### ISSUE THREAD

**Issue by victornoel** [benoitc/gunicorn#2240]
Hi,

I'm trying to disable access logs from gunicorn, but I just can't find how to do it.

I know that uvicorn, for example, has a specific cli option to do that: `--no-access-log`.

It would make sense for gunicorn to have the same I believe.

**Comment by benoitc** [comment]
By default the access log is disabled until you set the setting. Just not pass the `--access-logfile` argument and you will be good.

**Comment by benoitc** [comment]
note that with syslog enabled you will have to set `--disable-redirect-access-to-syslog`

**Comment by victornoel** [comment]
@benoitc I don't pass that option… but I'm passing `--log-config` though, containing:
```
    [logger_gunicorn]
    level=INFO
    handlers=console
    propagate=0
    qualname=gunicorn
```

I couldn't find any way to disable just `gunicorn.access` from there but I may be missing something in my python knowledge?

**Comment by benoitc** [comment]
@victornoel 

Pass

**Comment by victornoel** [comment]
@benoitc yes but what should I set to disable it? It is not possible to disable loggers with the ini style log configuration (hence my request to have it disabled via gunicorn cli).

A workaround would be to set the level to WARNING I suppose…

**Comment by benoitc** [comment]
or `DEBUG` . I don't like to add another option, rather this logger shouldn't be set by default.

I will check. In the mean itme, either increase the log level or send it to /dev/null.

**Comment by victornoel** [comment]
@benoitc thx for the workaround in any case :)

**Comment by tilgovi** [comment]
Closing as addressed by configuration.
