### ISSUE TITLE
The umask parameter seems does not effect or what wrong with my usage?

### ISSUE THREAD

**Issue by xiaopeipei123** [benoitc/gunicorn#2245]
I want modify the default logger file right 644 to 640. When i add umask = 0027 to gunicorn configuration file, it seems that does not work. what's wrong with my usage?
below is my usage:
gunicorn.conf
...
reuse_port = True
worker_class = "gevent"
umask = 0027
daemon = True
...
i delete the old log file, and restart the gunicorn server to generate new logs, here is the new files, but the file access right does not what i want.
this is the start command
 gunicorn -c "${HOME}/etc/gunicorn.conf" "main:create_app()"

-rw-r--r-- 1 org users    0 Jan 21 15:58 gunicorn-access.log
-rw-r--r-- 1 org users  275 Jan 21 15:58 gunicorn-error.log

**Comment by xiaopeipei123** [comment]
any wrong with my usage???

**Comment by xiaopeipei123** [comment]
i try it again today, it actually take effect this time. but i don't what's wrong with my configuration for last time.
all in, it seem that is not a problem.

**Comment by xiaopeipei123** [comment]
i  figure out that 'daemon = True' do effect, when i change the  daemon to the default , the umask can take effect.

**Comment by tilgovi** [comment]
Is there a bug then?

**Comment by Sturmtiger** [comment]
Encountered the same problem. --umask parameter doesn't work when gunicorn runs in the foreground (which is preferred because I'm using docker). 
But the regular system umask works fine. 
So the workaround for me was to run umask before gunicorn

**Comment by benoitc** [comment]
which error do you have. does the use in foreground have the rights?

**Comment by elibroftw** [comment]
```python
umask = 0o007
```

**Comment by adi-** [comment]
I want to open this ticket because gunicorn still doesn't respect umask setting for log files. I have set `umask 002` for the user and have also set gunicorn's setting to `umask = 0o002`. Files are created with `-rw-r--r--` permissions. Am I missing something?
