### ISSUE TITLE
Gunicorn changes its listening interfaces when PORT is in environment

### ISSUE THREAD

**Issue by kmichel2** [benoitc/gunicorn#2247]
Hi,

When the `PORT` variable is in the environment, [the default value of the --bind option changes](https://github.com/benoitc/gunicorn/blob/73ae195068d99ea8c9f26a999178a2cfb8fb057f/gunicorn/config.py#L562) from `127.0.0.1` to `0.0.0.0`.

I can see how this can be useful on some deployments (such as on Heroku) but this behaviour might be surprising and possibly a security issue when suddenly you're listening on a public interface in addition to localhost.

Changing this might be hard and break too many things but I think it should at least be documented : I haven't found any trace of this in the documentation except for an [2012 entry in the changelog](https://docs.gunicorn.org/en/stable/2012-news.html#id3), specifically mentioning Heroku.

[The Configuration documentation](https://docs.gunicorn.org/en/stable/configure.html) very clearly enumerates the three places when gunicorn can read its configuration but does not include the environment.

[The Settings list](https://docs.gunicorn.org/en/stable/settings.html) does mention a few environment variables: `GUNICORN_CMD_ARGS`, `PYTHONUNBUFFERED`, `SENDFILE`, `FORWARDED_ALLOW_IPS`, `WEB_CONCURRENCY` but not the `PORT` variable. The default value of `--bind` is documented as only `['127.0.0.1:8000']`

The automatic binding to the public interface makes [Honcho](https://github.com/nickstenning/honcho) harder to use safely as a local dev server since Honcho will always set the PORT variable.

I can work on improving the documentation and/or removing the behaviour (maybe for a new major version) with a documented migration path (such as reading the environment in the configuration file), depending on what you prefer.

PS: There are 4 more undocumented environment dependencies, but not really specific to gunicorn:
  - `LD_LIBRARY_PATH` in [util.py](https://github.com/benoitc/gunicorn/blob/73ae195068d99ea8c9f26a999178a2cfb8fb057f/gunicorn/util.py#L656) but it seems to be dead code.
  - `NOTIFY_SOCKET` in [systemd.py](https://github.com/benoitc/gunicorn/blob/73ae195068d99ea8c9f26a999178a2cfb8fb057f/gunicorn/systemd.py#L62)
  - `LISTEN_PID` and `LISTEN_FDS` also in [systemd.py](https://github.com/benoitc/gunicorn/blob/73ae195068d99ea8c9f26a999178a2cfb8fb057f/gunicorn/systemd.py#L43)

**Comment by tilgovi** [comment]
I would happily review PRs for all of the mentioned documentation changes!

I do think it might be too much breakage to change the behavior of `PORT`.

**Comment by benoitc** [comment]
stalled issue.
