### ISSUE TITLE
Unable to Synchronize Gunicorn Lock process

### ISSUE THREAD

**Issue by bhushanbrb** [benoitc/gunicorn#2251]
With  2 workers and 1 thread unable to use Lock() , even if using lock it fails to synchronize
as per mentioned issue here https://stackoverflow.com/questions/18213619/sharing-a-lock-between-gunicorn-workers

# dummy.py
from multiprocessing import Lock
import time
lock = Lock()
def start():
    lock.acquire()

    # TODO do work
    for i in range(0,10):
        print "did work %s" % i
        time.sleep(1)

    lock.release()
@tilgovi  Assuming gunicorn workers are processing , unable to synchronize those using multiprocessing.Lock()

**Comment by benoitc** [comment]
don’t make your lock global if you want to use it.  gunicorn workers are not based on multiprocessing.

**Comment by benoitc** [comment]
no feedback from the reporter since awhile. Closing the issue then.
