### ISSUE TITLE
New option to spawn workers synchronously

### ISSUE THREAD

**Issue by warvariuc** [benoitc/gunicorn#2256]
Hi. I would like to add support for a configuration option which would allow synchronous spawning of workers. I have this functionality in our project in form of monkey-patching. I think this would be useful for many users ( https://github.com/benoitc/gunicorn/issues/1641#issuecomment-343761618 ).

There is a random delay when spawning workers 
https://github.com/benoitc/gunicorn/blob/7d8c92f48a6d9cee6b15fbdade6981721182d073/gunicorn/arbiter.py#L617  but it's insignificant in some cases. And in case of reloading (SIGHUP) there is no delay at all  https://github.com/benoitc/gunicorn/blob/7d8c92f48a6d9cee6b15fbdade6981721182d073/gunicorn/arbiter.py#L479-L481 

The idea:

1. Add a new configuration option called something like `sync_spawn` which would be False by default (the current behavior)
2. `gunicorn.arbiter.Arbiter.spawn_worker` would be updated https://github.com/benoitc/gunicorn/blob/7d8c92f48a6d9cee6b15fbdade6981721182d073/gunicorn/arbiter.py#L568
in case `sync_spawn` is enabled, the master would wait for the spawned worker to be completely loaded and ready to serve requests. Only then the master will start spawning next worker. To save RAM we will call here

```python
    # Remove one of older workers
    workers = self.WORKERS.items()
    workers = sorted(workers, key=lambda w: w[1].age)
    while len(workers) > self.num_workers:
        (pid, _) = workers.pop(0)
        self.kill_worker(pid, signal.SIGTERM)
```

so that when a new worker has started during reload, the oldest one would be shut down --  to avoid situation that all new workers are spawned and only then the old ones are shut down. 
3. After calling `post_worker_init` in a worker, if `sync_spawn` is enabled we will notify the master that the worker is ready to serve requests.
https://github.com/benoitc/gunicorn/blob/7d8c92f48a6d9cee6b15fbdade6981721182d073/gunicorn/workers/base.py#L137

I am willing to make a PR, but before starting the work, I'd like to know if you are interested in accepting such code.

**Comment by benoitc** [comment]
What is the purpose of this feature?

**Comment by warvariuc** [comment]
@benoitc as described in the linked issue, this is useful for cases when workers need some significant time to warm up. For example to load a large cache from a database into memory. If all workers will start loading the cache at the same time, it's a significant load on the database and local CPU.

**Comment by benoitc** [comment]
I don't really like the idea. If your application really depends on loading a large cache inside the python process  before beeing able the requests it will be soon an issue in production, if the worker crash for any reason (memory, io,...). 

IMO the best way to handle such case is to share that cache between instance on the local machine or over the network. Another way is to make this load asynchronous, in the worst cases the first requests will have to be longer, but it's far better than delaying the launch of a worker during operations. Maybe we could offer some api for it but unsure which yet.

I will let the ticket open for some times to see if we need to do more.

**Comment by mindojo-victor** [comment]
>  Another way is to make this load asynchronous, in the worst cases the first requests will have to be longer

We tried this, and the result is unacceptable for us. Cache filling takes sometimes > 10s.

> IMO the best way to handle such case is to share that cache between instance on the local machine or over the network.

To use the cache of the network is not much different from using the DB. We use cache to make things even faster.

> but it's far better than delaying the launch of a worker during operations

I don't understand why delaying the launch of a worker is so bad. And given our circumstances it's the best option.

Anyway, if you think this approach is bad or useless, close the issue.

**Comment by warvariuc** [comment]
>  Another way is to make this load asynchronous, in the worst cases the first requests will have to be longer

We tried this, and the result is unacceptable for us. Cache filling takes sometimes > 10s.

> IMO the best way to handle such case is to share that cache between instance on the local machine or over the network.

To use the cache of the network is not much different from using the DB. We use cache to make things even faster.

> but it's far better than delaying the launch of a worker during operations

I don't understand why delaying the launch of a worker is so bad. And given our circumstances it's the best option.

Anyway, if you think this approach is bad or useless, close the issue.

**Comment by benoitc** [comment]
You can also pre-load the cache and pass it to the workers using hooks. 

Ex.
```
when_ready(Server):
    server.my_cache = preload_cache(...)

post_fork(server, worker):
   """ add server.my_cache to worker thread or worker)

```

Only issue with that is that all modules used to load the data won't be reloaded on sighup until you take care of it. You can also use the preload setting and share this cache globally.

Making worker launch synchronous makes all the supervision loop and error handling more complicated. If your application requires a local ca he It's safer to share a cache between workers once. 

You can also have a cache locally (using a unix socket) or fork a process and share a pipe with it.

**Comment by warvariuc** [comment]
Thanks for the alternatives. Maybe in the future we will see if we can use one of them.

**Comment by benoitc** [comment]
OK.

Also note you could also implement your logic using hooks in the `pre_fork` worker:

```
prefork_worker(server, worker):
   while True:
      if (len(server.WORKERS) == server.worker_age): break
      sleep(0.1)
```
