### ISSUE TITLE
Timeout with Tensorflow

### ISSUE THREAD

**Issue by meocong** [benoitc/gunicorn#2259]
Hi, I have a problem with mixing Tensorflow and Gunicorn but I don't know how to fix it, please help. 

I have an unpublished library that automatic wrap AI models to serve as APIs, everything is just fine except one case:
Please check this code: https://github.com/meocong/FlaskMnistTutorial/blob/gunicorn_error/gunicorn_server.py

I start Gunicorn server that wraps a flask app import from server.py, so the TensorFlow model session is loaded to a different thread, then when I call a POST to the server, it will be stuck in this [line](https://github.com/meocong/FlaskMnistTutorial/blob/gunicorn_error/tensorflow_mnist/model.py#L23)

There's two way I can fix: 
Method 1: Call Gunicorn from command line, it's not ok because I want to call gunicorn as an option. Like this:
`FlaskServer().run(model, bind=['127.0.0.1:8004', 'unix:/tmp/gunicorn.sock'], debug=False, gunicorn=True, workers=1, threads=1, timeout=50, max_requests=100)`

Method 2: Change the way to call prediction, start a session whenever call predict:
Change:
`pd = self.sess.run(self.output, feed_dict={self.X: X})`
to
`with tf.Session(graph=self.graph) as sess:
            pd = sess.run(self.output, feed_dict={self.X: X})`
It make me to change the code. 

So is there any way to make this work all the time? Thanks in advance!

**Comment by tilgovi** [comment]
Where is `FlaskServer().run`? I don't see it in your code.

**Comment by tilgovi** [comment]
Oh, I think I understand. You would _like_ to have a generic server class that takes a `gunicorn` option but right now starting a gunicorn application programmatically is causing problems for you.

Can you show how you call Gunicorn from the command line?

**Comment by meocong** [comment]
I fixed it by calling Gunicorn command line, many thanks!
