### ISSUE TITLE
Does gunicorn take responsibility for managing the logs of the apps it runs?

### ISSUE THREAD

**Issue by erichiggins** [benoitc/gunicorn#2265]
It's unclear from the gunicorn documentation whether it's dealing with application logs or just its own.

There's extensive documentation on the settings available for logging.
https://docs.gunicorn.org/en/stable/settings.html#logging

And even a [reference example `logging.conf` file](https://github.com/benoitc/gunicorn/blob/master/examples/logging.conf).

Searching Google for [how to manage logs with gunicorn + flask suggests using](https://medium.com/@trstringer/logging-flask-and-gunicorn-the-manageable-way-2e6f0b8beb2f):

```
logger = logging.getLogger('gunicorn.error')
```

But, this didn't actually work for me -- it didn't seem to provide an existing handler.
Then I found [this warning in the gunicorn docs](https://docs.gunicorn.org/en/stable/deploy.html#logging):

> Gunicorn error log is here to log errors from Gunicorn, not from another application.

I'd like to get some clarity -- **is gunicorn responsible for handling/managing the logs from the application it runs?** If so, how? If not, can that be more explicitly mentioned in the docs?

The following are configs/references from how my app is being run.

How my app is started (via systemd):
```
/bin/gunicorn -c file:gunicorn_conf.py devicectrl.wsgi
```

Relevant contents of `gunicorn_conf.py`
```
accesslog = '/var/log/gunicorn/access.log'
# See proxy_pass in nginx config
bind = 'unix:/run/gunicorn/socket'
capture_output = True
errorlog = '/var/log/gunicorn/error.log'
group = 'www-data'
keepalive = 10
pidfile = '/run/gunicorn/pid'
# Timeout after 5 mins.
timeout = 300
umask = 0o007
user = 'www-data'
workers = 3
forwarded_allow_ups = '*'
```

**Comment by benoitc** [comment]
gunicorn only take care about its log which is explicitly said in the [doc](https://docs.gunicorn.org/en/stable/deploy.html#logging) as you mentionned. The application should take care about its own logs. Also Flask can probably handle the errors using wsgi: https://www.python.org/dev/peps/pep-3333/#error-handling or use `wsgi.errors` in the environ.
