### ISSUE TITLE
ModuleNotFoundError: No module named '/src/myproject'

### ISSUE THREAD

**Issue by TZubiri** [benoitc/gunicorn#2268]
In order to pass python code to gunicorn, one has to use this command, as per the documentation:

    gunicorn myproject:app

by this they mean that you need to have a myproject.py file with an app class in it. Why remove the .py I'm not sure. Of course if we run this command from a different directory than the myproject.py file an error we occur, so naturally we run:

    gunicorn /src/myproject:app

This doesn't work and yields the following error:

    ModuleNotFoundError: No module named '/src/myproject'

/src/myproject.py didn't work either, it's basically down to the fact that there is no absolute path support, one needs to be on the same directory, so one needs to use cd, if one is using docker, we need to use the workdir directive. This is horrible because we don't want to introduce state dependent operations, but we must now.

There's also the existence of --chdir, I haven't looked much into it, but whoever implemented this option absolutely missed implementing absolute path support instead. Now a user has 3 subpar ways of working around this issue. 

Sometimes you don't need to add a feature, you just need to fix a bug.

**Comment by TZubiri** [comment]
Here is the Dockerfile I'm using. For deterministic testing:

FROM python:3.8-buster

RUN pip3 install flask
RUN pip3 install gunicorn

ADD aegis.py /src/aegis.py

ENTRYPOINT gunicorn /src/aegis:app

Removing the word

**Comment by jamadden** [comment]
This is not a bug.

gunicorn uses Python's standard [import mechanism](https://docs.python.org/3/library/importlib.html) to [locate the application](https://github.com/benoitc/gunicorn/blob/7d8c92f48a6d9cee6b15fbdade6981721182d073/gunicorn/util.py#L57). That means that Python's [sys.path](https://docs.python.org/3/library/sys.html#sys.path) must contain the module.

The exact details to arrange that will depend on the exact deployment scenario. It the simplest case on the command line, one could achieve that with by setting an appropriate [PYTHONPATH environment variable](https://docs.python.org/3/using/cmdline.html?highlight=pythonpath#envvar-PYTHONPATH), for example, `$ PYTHONPATH=/src gunicorn myproject:app`. More often, the project is installed in a virtual environment that also contains gunicorn so that they automatically share the same value for `sys.path`.

**Comment by TZubiri** [comment]
Hello, thank you for the quick response.

Ok. So gunicorn looks on the sys.path. My definition of bug is pretty broad. I hope we can find middle ground in calling this an issue, an issue that, were to be fixed, would reduce the number of errors new users encounter.

Just take a look at the amount of people who have asked for help with this issue https://www.google.com/search?client=ubuntu&channel=fs&q=ModuleNotFounderror+gunicorn&ie=utf-8&oe=utf-8

Using sys.path is cool, but it's kind of obscure. Could gunicorn try to understand whether it was passed a path instead of a module name, and if so, try to fetch the file from that path? Implementation wise, this seems like it could simply be calling os.path.isdir(module) and calling doing whatever --chdir does.

**Comment by jamadden** [comment]
While taking a single file path might work for trivial toy applications, most real applications have dependencies or otherwise consist of multiple files, at which point the whole thing would fall apart again.

Learning about sys.path is a core part of developing in Python.

**Comment by TZubiri** [comment]
I understand, there might be more complex scenarios that I am not considering here. 

Are there situations where the following command would find all dependencies of the entry point:

> python3 /src/myproject.py

but the following command could not feasibly do so?

> gunicorn /src/myproject:app

Presumably, if there are errors in finding dependencies, they would also exist in the above command, and gunicorn would no longer concern itself with the resolution of that error. But the error message would be more helpful (and occasional)

> ModuleNotFoundError: No module named 'dependency'

Myself, if I were to have dependencies, I would have included them as a folder in the /src/dependency directory, it's important that this dependency is found as well, I don't think this should be too hard.

Is there another scenario I might be missing?

**Comment by TZubiri** [comment]
Ok, by looking at the gunicorn source I found a couple:

 let's say that the wsgi function is found in dependency.wsgi:app and this has a dependency on the root directory ( dependency/..) It's necessary to define the root directory in this case.
So --chdir serves a nice purpose here, (so does cd and workdir)

Another case is where the module is installed via setup.py rather than a simple directory structure.

So the issue here is that there's a lot of cases where the wsgi function already resides in the root directory, and this simpler setup still has to pay for the complexities of these other cases. I'd still ike to see support for file/directory based arguments. But I propose this pull request as a more moderate but unarguable improvement.
https://github.com/benoitc/gunicorn/pull/2269
