### ISSUE TITLE
Is it possible to extract the number of in-flight requests?

### ISSUE THREAD

**Issue by deliahu** [benoitc/gunicorn#2273]
Is there a way to extract the total number of in-flight requests across all workers/threads? (i.e. the number of requests that have been received and not yet responded to)

If so, how can it be consumed? E.g. can I create an endpoint like `/requests` which responds with the number? Or perhaps a cron task which can query the number so I could send it to a stats database?

For context, I'd like to trigger autoscaling events based on the number of in-flight requests.

**Comment by benoitc** [comment]
you can handle a counter using gunicorn hooks per worker  for it that report the an external process or a file. If you want to have an HTTP endpoint for it the best way to eventually do it is to have a custom request opening the files or anything else and sum the result for example. Hope it helps.

**Comment by deliahu** [comment]
@benoitc thank you for your response! Yes that makes sense. Are you referring to the [pre_request](https://docs.gunicorn.org/en/stable/settings.html#pre-request) and [post_request](https://docs.gunicorn.org/en/stable/settings.html#post-request) hooks? Also, if there is a backlog, will these hooks run when the request comes in, or only when the request is pulled off the queue?

**Comment by benoitc** [comment]
> @benoitc thank you for your response! Yes that makes sense. Are you referring to the [pre_request](https://docs.gunicorn.org/en/stable/settings.html#pre-request) and [post_request](https://docs.gunicorn.org/en/stable/settings.html#post-request) hooks? Also, if there is a backlog, will these hooks run when the request comes in, or only when the request is pulled off the queue?

yes these hooks. They only happen when the request is accepted from the backlog.

**Comment by deliahu** [comment]
Sounds good, thank you!
