### ISSUE TITLE
Gunicorn StopIteration thrown on term signal.

### ISSUE THREAD

**Issue by dmplotzke** [benoitc/gunicorn#2274]
Hello, I've found myself running into an issue where Gunicorn runs into a StopIteration exception 1 minute and 30 seconds after starting up. 

I followed the [instructions](https://docs.gunicorn.org/en/stable/deploy.html) in the documentation when setting up Gunicorn with Nginx. 
Please advise, is this a known issue and if so are there any workarounds?

**Here is the stacktrace:**
Feb 21 01:25:23 raspberrypi systemd[1]: Starting gunicorn daemon...
Feb 21 01:25:27 raspberrypi gunicorn3[1152]: [2020-02-21 01:25:27 +0000] [1152] [INFO] Starting gunicorn 19.6.0
Feb 21 01:25:27 raspberrypi gunicorn3[1152]: [2020-02-21 01:25:27 +0000] [1152] [INFO] Listening at: unix:/run/gunicorn.sock (1152)
Feb 21 01:25:27 raspberrypi gunicorn3[1152]: [2020-02-21 01:25:27 +0000] [1152] [INFO] Using worker: sync
Feb 21 01:25:27 raspberrypi gunicorn3[1152]: [2020-02-21 01:25:27 +0000] [1157] [INFO] Booting worker with pid: 1157
Feb 21 01:26:53 raspberrypi systemd[1]: gunicorn.service: Start operation timed out. Terminating.
Feb 21 01:26:53 raspberrypi gunicorn3[1152]: [2020-02-21 01:26:53 +0000] [1152] [INFO] Handling signal: term
Feb 21 01:26:53 raspberrypi gunicorn3[1152]: Traceback (most recent call last):
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 211, in run
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     handler()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 246, in handle_term
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     raise StopIteration
Feb 21 01:26:53 raspberrypi gunicorn3[1152]: StopIteration
Feb 21 01:26:53 raspberrypi gunicorn3[1152]: During handling of the above exception, another exception occurred:
Feb 21 01:26:53 raspberrypi gunicorn3[1152]: Traceback (most recent call last):
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/bin/gunicorn3", line 11, in <module>
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 192, in run
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     super(Application, self).run()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 72, in run
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     Arbiter(self).run()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 214, in run
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     self.halt()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 331, in halt
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     self.stop()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 370, in stop
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     l.close()
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:   File "/usr/lib/python3/dist-packages/gunicorn/sock.py", line 123, in close
Feb 21 01:26:53 raspberrypi gunicorn3[1152]:     os.unlink(self.cfg_addr)
Feb 21 01:26:53 raspberrypi gunicorn3[1152]: PermissionError: [Errno 13] Permission denied: '/run/gunicorn.sock'
Feb 21 01:26:53 raspberrypi systemd[1]: gunicorn.service: Main process exited, code=exited, status=1/FAILURE
Feb 21 01:26:53 raspberrypi systemd[1]: Failed to start gunicorn daemon.
Feb 21 01:26:53 raspberrypi systemd[1]: gunicorn.service: Unit entered failed state.
Feb 21 01:26:53 raspberrypi systemd[1]: gunicorn.service: Failed with result 'timeout'.

**Comment by benoitc** [comment]
not reproduced
