### ISSUE TITLE
Loading config file creates __pycache__ directory

### ISSUE THREAD

**Issue by jfly** [benoitc/gunicorn#2278]
Hey all! Not sure if this is a bug or not, but I thought it was worth filing an issue to get more information.

```
$ mkdir -p /tmp/jfly-test
$ echo 'bind = "0.0.0.0:5000"
worker_class = "gevent"
workers = 2

accesslog = "-"
errorlog = "-"' > /tmp/jfly-test/gunicorn.conf
$ ls -alh /tmp/jfly-test
total 8.0K
drwxr-xr-x  2 jeremy jeremy  80 Feb 25 11:20 .
drwxrwxrwt 24 root   root   840 Feb 25 11:20 ..
-rw-r--r--  1 jeremy jeremy  91 Feb 25 11:20 gunicorn.conf
$ gunicorn -c /tmp/jfly-test/gunicorn.conf wsgi_app:wsgi_app
...
ModuleNotFoundError: No module named 'wsgi_app'
[2020-02-25 11:50:38 -0800] [448998] [INFO] Worker exiting (pid: 448998)
[2020-02-25 11:50:38 -0800] [448993] [INFO] Shutting down: Master
[2020-02-25 11:50:38 -0800] [448993] [INFO] Reason: Worker failed to boot.
$ ls -alh /tmp/jfly-test
total 8.0K
drwxr-xr-x  3 jeremy jeremy 100 Feb 25 11:20 .
drwxrwxrwt 24 root   root   840 Feb 25 11:20 ..
-rw-r--r--  1 jeremy jeremy  91 Feb 25 11:20 gunicorn.conf
drwxr-xr-x  2 jeremy jeremy  60 Feb 25 11:20 __pycache__
```

Note how the `__pycache__` directory did not exist before running gunicorn, and does exist after!

I dug a bit, and confirmed that this seems to be happening as a result of `get_config_from_filename`: https://github.com/benoitc/gunicorn/blob/7d8c92f48a6d9cee6b15fbdade6981721182d073/gunicorn/app/base.py#L93-L118
Specifically, when `spec.loader.exec_module(mod)` runs, the `__pycache__` directory gets created.

Is this intentional? Some thoughts:

1. It feels a bit weird to me that loading the config file could have this sort of a side-effect on the filesystem.
2. We also use flask, and I dug enough into flask's source code to learn that it is able to load its config file *without* creating the `__pycache__` directory (relevant code here: https://github.com/pallets/flask/blob/64ba43411fbfb2e435455b0df2453d7809b7c5a8/src/flask/config.py#L113-L139). Maybe it would make make sense to load gunicorn's config file in a similar way?

**Comment by tilgovi** [comment]
What's nice about the way we have it is that we support loading config from bytecode if that's all that's available. This makes it possible to redistribute gunicorn with an application in a minimal way. I remember seeing this use case come up in a previous issue.

We could, however, use our own loader for the case where we load from source (suffix in importlib.machinery.SOURCE_SUFFIXES, usually just `.py) that is derived from `SourceFileLoader` but implements a no-op `set_data` method. That will skip writing the bytecode cache.

**Comment by priyanka03thakur** [comment]
Facing same issue, any clue?

**Comment by tilgovi** [comment]
I outlined how this might be done. If there are other ideas, please post them.
This is not a bug, but I see that some people find it surprising.

**Comment by benoitc** [comment]
stalled issue.
