### ISSUE TITLE
Server Error - Custom Response Format

### ISSUE THREAD

**Issue by skeezus** [benoitc/gunicorn#2281]
I'm using gunicorn to host django-rest-framework with nginx as reverse proxy. My api returns all responses in JSON format however when there's a server error (404 Not Found (url), 500 class, etc) the server responds with an html formatted text string. 

I was looking at your documentation and you show the ability to configure custom error pages in the server block as shown below. If I comment out the `location /` block that forwards to gunicorn the 404 response works as expected (responds with JSON). But If I uncomment it and the proxy passes to gunicorn and I look for a resource that doesn't exist in the application, the server responds with the aforementioned text string. Any ideas as to why this is happening?

EDIT: If you add `proxy_intercept_errors on;` in the application server's location block it will work. Of course NGINX then intercepts all errors of a particular status code which works fine for 500 class but not 400 class.

```
server {
   ...
   location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
   error_page 404 /404.html;
       location = /404.html {
         return 404 '{"error": {"status_code": 404,"status": "Not Found"}}';
    }
  ...
}
```

**Comment by tilgovi** [comment]
Gunicorn itself only generates responses for server errors where the application raised an exception. If you are seeing an HTML 404, that is coming from your application and should be fixable in your application.
