### ISSUE TITLE
Is using "--timeout 0" officially supported?

### ISSUE THREAD

**Issue by di** [benoitc/gunicorn#2291]
It appears that using `--timeout 0` results in disabling worker timeouts entirely:

https://github.com/benoitc/gunicorn/blob/e636bf81989bb833d2b99104feb11e86c3f2c43a/gunicorn/arbiter.py#L486-L491

Is this considered a supported feature? I couldn't find any documentation indicating that this can be depended on.

If not, can it be? Should it be? I see some other settings (`--limit-request-line`, `--limit-request-field_size`) that have similar behavior that are documented.

**Comment by benoitc** [comment]
@di relative ticket is https://github.com/benoitc/gunicorn/pull/370 so the timeout can be disabled in some cases. Others are for the same goal but different reasons so you don't want to check such limits.

**Comment by di** [comment]
Gotcha, thanks! Given how long this has existed, would you be open to a PR to document & officially support it?

**Comment by benoitc** [comment]
@di please do :)

**Comment by di** [comment]
Done: #2292.

**Comment by di** [comment]
@benoitc Anything else I need to do here? We'd like to tell our users to use this, but don't want to do so until it's documented. Thanks!
