### ISSUE TITLE
Does SIGHUP work correctly?

### ISSUE THREAD

**Issue by unittolabs** [benoitc/gunicorn#2296]
Hey! I faced the issue during tests with SIGHUP.

I use Gunicorn as a web-server for Django (2.2.11).
I tried 20.0.4 and 19.10.0 versions of Gunicorn with config for 1 and 4 workers and 4 threads.

To create payload I use locust (0.14.5).
All tests running at the local machine, P50 ~10 ms, P90 ~18 ms, with 30 RPS.

When I sending SIGHUP to the master process of gunicorn, the server is restarting but 4-16 requests were failed (depends on the count of workers).

I also tried to use rainbow-saddle(0.4.0) it helps a little bit - count of failed requests down to 2-8 but it still not zero. Also, I noticed that the count of failed requests is lower when workers count is lower too, so maybe the problem is in SIGWARN \ SIGTERM that close requests before it actually done.

Does anybody face the same problem?

upd: Gunicorn 19.9.0 has the same problem

**Comment by benoitc** [comment]
Hi it's hard to answer. So first HUP is supposed to work. What kind of requests is sending Locust and what what does P50 or P90 mean? 

when you say " 1 and 4 workers and 4 threads" foes it means you start gunicorn with the -w4 --threads 4 option? How much the request is supposed to. last? If you have any application example and locust scenario to share that would help.

**Comment by unitto1** [comment]
Tested at a simple Django application.
It sends GET requests to the login page.
P50 and P90 mean percentiles - 50 and 90.

Yes, I tried to start the server in a few configurations:
`--threads 3 --workers 1` and `--threads 3 --workers 4`
I use the scenario below with 30 users.

```python
# locustfile.py
from locust import HttpLocust, TaskSet, constant, task


class ConferenceLoginTasks(TaskSet):
    @task
    def login(self):
        self.client.get('/login/?next=/')


class User(HttpLocust):
    host = 'http://127.0.0.1:8000'
    task_set = ConferenceLoginTasks
    wait_time = constant(1)
```
P.S. test case with the one worker has a lower error rate then test case with 4 workers
P.P.S. test also Gunicorn 19.5.0 + rainbow-saddle 0.3.2 but the result is the same =(

**Comment by benoitc** [comment]
ah that was the perf result ok ... what is happening if you're not using --threads? Also are requests kept alive ?

**Comment by unitto1** [comment]
hm, not even try. so you propose to try the default `--threads 1` or even to specify this?

**Comment by benoitc** [comment]
no i propose to use just the worker setting, don't set --threads=1 at all :)

**Comment by unitto1** [comment]
you have right! removing `--threads` help, even with `-w 1` so one request is failed

**Comment by benoitc** [comment]
Hrm it should work the same way or mostly the same. I will revisit the source tomorrow to check.

**Comment by unitto1** [comment]
Can I help you somehow?

I using the k8s to deploy apps and prefer to scale via threads instead of workers to limit process CPU usage to single core. So it's a little bit weird for me =)

**Comment by benoitc** [comment]
threads or workers should be the same when it's about the CPU usage. I think the issue may come because some request are actually waiting on the event loop but unsure. Do you have any log failure of the requests?

**Comment by unitto1** [comment]
The single process in python can't consume more than one core, so it's the reason - opportunity to set the resource limit of CPU to one. I little bit scaring that scaling via workers can consume for then one CPU and pod will be killed by OOM.

From the server-side - no errors, just dropped connection in the locust web page.

**Comment by benoitc** [comment]
@unitto1 but if you use multiple worker you will have more safety. There is no issue to have multiple processes on one CPU or core. Afaik a process is technically just a type of thread at the kernel level.

**Comment by unitto1** [comment]
Not sure about kernel-level =) But sure that if I will use more then one worker it can consume more than one CPU, at least in theory. Also, if the process will die, k8s service (intern LB) will stop route traffic to the pod immediately (tested), so safeties not a big problem for me.

BTW the scaling via pods produces more efficient hardware utilization.
Some time ago I tested gunicorn, waitress and uwsgi.
On the constant hardware, it produces 100, 80 and 120 RPS in -w1 -t 4 configuration and (100% of one CPU usage).
When I scale workers up to the 2 I expected 200 RPS via gunicorn (because a single worker produces 100 RPS), but actually I got 160 only. So I take a decision to scale via pods =)

**Comment by unitto1** [comment]
@benoitc hey! any updates?

**Comment by tilgovi** [comment]
@unitto1 do you have a resource budget on your pod? If you start two workers, make sure to also give Gunicorn more CPU in your pod allocation.

**Comment by unitto1** [comment]
> @unitto1 do you have a resource budget on your pod? If you start two workers, make sure to also give Gunicorn more CPU in your pod allocation.

sure, I always use 1 CPU per gunicorn worker
