### ISSUE TITLE
gunicorn workers multiprocessing for different process and avoid racing condition

### ISSUE THREAD

**Issue by sherwin7** [benoitc/gunicorn#2298]
**Flask-socketIO with gunicorn workers**
I have created a streaming api where the MEAN stack based web-application will be sending a continuous audio stream to the API written in flask-socketIO.

if I use gunicorn and gevent worker class for deployment with one worker (only master) it is working fine where the flask-socketIO API is perfectly emitting back to the web-application.

if i use gunicorn with more number of worker the audio stream is continuously getting shifted to different worker and if a child or slave worker processes or worker emits the signal it is not going to the web-application since it is looking at the master process port in (my case 3010)

**Expected behavior (Senario-1)**
audio stream from web-app -> flask api port (master - 3010) -> free worker process -> flask api port (master - 3010) -> web-app 

**Current behavior (Senario-2)**
audio stream from web-app -> flask api port (master - 3010) -> free worker process -> goes some where...

Also  i want to avoid to race condition between the workers for one process, I want each process is runned by one worker

if multiple user audio streaming is happening at the same time then each worker has to process one stream and sent the according signal to the particular clinets

**The wanted behavior  (Senario-3)**
audio stream from web-app from **client-1**-> flask api port (master - 3010) -> **free worker-1** -> flask api port (master - 3010) -> web-app 

audio stream from web-app from **client-2**-> flask api port (master - 3010) -> **free worker-2** -> flask api port (master - 3010) -> web-app 

audio stream from web-app from **client-3**-> flask api port (master - 3010) -> **free worker-3** -> flask api port (master - 3010) -> web-app 

the above senario-3  has to happen parallel

**THANKS IN ADVANCE !!**

**Comment by benoitc** [comment]
stalled issue. imo that was more an application work, ensuring you know which socket it is to retrieve  its status from any http connection. Since a websocket will be handled in //. Sorry for the late reply anyway.
