### ISSUE TITLE
Flask Request.stream's type comes as gunicorn.http.body.Body (instead of expected werkzeug.wsgi.LimitedStream)

### ISSUE THREAD

**Issue by kiranpers** [benoitc/gunicorn#2300]
In gunicorn 20.0.0 version, flask's `request.stream` type is `werkzeug.wsgi.LimitedStream` . But in gunicorn 20.0.4,  flask's `request.stream` type comes as `gunicorn.http.body.Body` .  This is causing flask post request failure. 

Here are more details of my application's requirements.txt
```
 flask==1.1.1
 flask_cors==3.0.8
 flask-log-request-id==0.10.1
 gunicorn==**20.0.4**
```
```python
 @app.route('/test', methods=['POST'])
 def create_func():
     log.info(str(type(request.stream)))
     result = compute_result(request.stream, sample_size=request.args.get('sample_size', type=int))
     return jsonify(result)
```
In the above example, just changing the gunicorn version from 20.0.4 to 20.0.0 fixed the issue.  None of the other versions of _gunicorn <=20.0.4 and > 20.0.0_ worked.  I see this issue **only** in docker containers, and not when running flask application directly. here is my docker file snippet. 

> FROM python:3.8-slim-buster
> ADD ./requirements.txt /app/requirements.txt
> RUN pip install --upgrade pip
> RUN pip install -r /app/requirements.txt

**Comment by jamadden** [comment]
What's the actual failure you get?

**Comment by kiranpers** [comment]
in my code, I have a `request.stream.exhaust()` which only works when request.stream returns a `werkzeug.wsgi.LimitedStream` , but request.stream returns a `gunicorn.http.body.Body` when I use gunicorn 20.0.4 .  so I get the python error: `'Body' object has no attribute 'exhaust'`.   interestingly this issue , happens only in **docker** containers ( both python:3.8-slim-buster and python:3.7-slim-buster)

**Comment by jamadden** [comment]
What you're seeing is the expected behaviour. 

gunicorn properly sets `wsgi.input_terminated` starting with 20.0.1. This causes Werkzeug to pass `wsgi.input` through instead of wrapping it with a `LimitedStream` because *`LimitedStream` is not necessary.* gunicorn handles request termination itself.

If you can depend on gunicorn >= 20.0.1, you can drop any calls to `exhaust()`. Otherwise, if you don't know what server you'll be running on, you'll need to make it conditional.

**Comment by kiranpers** [comment]
> What you're seeing is the expected behaviour.
> 
> gunicorn properly sets `wsgi.input_terminated` starting with 20.0.1. This causes Werkzeug to pass `wsgi.input` through instead of wrapping it with a `LimitedStream` because _`LimitedStream` is not necessary._ gunicorn handles request termination itself.
> 
> If you can depend on gunicorn >= 20.0.1, you can drop any calls to `exhaust()`. Otherwise, if you don't know what server you'll be running on, you'll need to make it conditional.

Thank you for your super fast response. I will follow your guidance and remove the calls to  exhaust() . I will confirm, if that solves the problem.
