### ISSUE TITLE
ValueError: '<path_to_sock.sock>' is not a socket

### ISSUE THREAD

**Issue by ravilkashyap** [benoitc/gunicorn#2302]
I am running a simple flask application on gunicorn  with nginx as proxy server. I keep getting this error, I am not able to figure out why.

**Comment by jamadden** [comment]
Without more information (e.g., your gunicorn configuration), all we can do is guess. 

My only guess is that your configuration is wrong. It looks like you're using the literal value `<path_to_sock.sock>` as the thing you want gunicorn to listen to. Most likely, that is not a valid socket file. You'll need to update your configuration to point to the actual socket file on disk that you want gunicorn to listen to (and make sure it matches the socket file that nginx is trying to connect to).

**Comment by ravilkashyap** [comment]
@jamadden I thought gunicorn takes care of creating sock file in the path I specify right?
I have attached the required files for your reference. 

This is my python conf file -
```
bind = 'unix:/home/ubuntu/<app_folder>/<service name>.sock'
worker_class='gevent'
worker_connections=1000
workers=6
preload_app=True
timeout=600

```


I am using a systemctl service to start gunicorn -
```
[Unit]
Description=Gunicorn service to serve requests for <service_name>
PartOf=global_wsgi_starter.service
After=global_wsgi_starter.service
[Service]
User=ubuntu
Group=www-data
WorkingDirectory=<path to code>
Environment="PATH=/home/ubuntu/miniconda3/envs/virtual_env/bin"
ExecStart=/home/ubuntu/miniconda3/envs/virtual_env/bin/gunicorn -c <path_to_conf.py> server:app
[Install]
WantedBy=global_wsgi_starter.service
```

And this is the global_wsgi_starter.service - 
```
[Unit]
Description=Starter process for all wsgi processes.
[Service]
# The dummy program will exit
Type=oneshot
# Execute a dummy program
ExecStart=/bin/true
# This service shall be considered active after start
RemainAfterExit=yes
[Install]
# Components of this application should be started at boot time
WantedBy=multi-user.target

```

**Comment by jamadden** [comment]
>  I thought gunicorn takes care of creating sock file in the path I specify right?

If possible, yes. But it can't always do that. For example, if the parent directories don't exist, gunicorn won't try to create them. 

You don't specify what version of gunicorn or Python you're using, and you don't provide gunicorn's output, so we still have to guess, but using Python 3.8 and gunicorn 20.0.4 with the literal configuration file you gave, (where obviously the bind path doesn't exist) I get this failed output:

```console
$ gunicorn -c /tmp/gunicorn_conf.py server:listen
[2020-04-11 05:56:35 -0500] [25100] [INFO] Starting gunicorn 20.0.4
[2020-04-11 05:56:35 -0500] [25100] [ERROR] Retrying in 1 second.
[2020-04-11 05:56:36 -0500] [25100] [ERROR] Retrying in 1 second.
[2020-04-11 05:56:37 -0500] [25100] [ERROR] Retrying in 1 second.
[2020-04-11 05:56:38 -0500] [25100] [ERROR] Retrying in 1 second.
[2020-04-11 05:56:40 -0500] [25100] [ERROR] Retrying in 1 second.
[2020-04-11 05:56:41 -0500] [25100] [ERROR] Can't connect to /home/ubuntu/<app_folder>/<service name>.sock
```

I get almost identical output on gunicorn 19.10 on Python 3.8 and Python 2.7. I checked gunicorn versions back to 0.15 and got the same output. 

It would help to have more information.

**Comment by ravilkashyap** [comment]
@jamadden I am running it on python 3.7.4 and gunicorn 20.0.4.
The error was coming because the sock file existed, which I had manually created via touch (my bad, I am still learning about socket programming)

It works fine now. Thank you for your help @jamadden 
Closing this issue
