### ISSUE TITLE
Why gunicorn spawns more than 1 thread per sync worker?

### ISSUE THREAD

**Issue by drnextgis** [benoitc/gunicorn#2308]
![image](https://user-images.githubusercontent.com/866124/79361226-4f696680-7f45-11ea-88ee-5899bddc7836.png)

```
bind = '0.0.0.0:8000'
workers = 3  # not more than the numbers of cpus
pidfile = '/run/gunicorn.pid'
timeout = 600
max_requests = 10000
worker_class = "sync"
```

Is it expected?

**Comment by tilgovi** [comment]
Were you able to answer this question, @drnextgis?

**Comment by drnextgis** [comment]
Yeah those additional threads were spawned by Sentry client library.
