### ISSUE TITLE
Getting [ERROR] Exception in worker process with Gunicorn + NGINX on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by zhangdongasia** [benoitc/gunicorn#2309]
![hello py](https://user-images.githubusercontent.com/39986266/79524977-69fe2580-8094-11ea-95f1-191f31475412.jpg)

**Till now , it's working well. 
However, under identical/same circumstance, gunicorn bind a "DYNAMIC" myproject.py, it's not working ...**

![myproject py-1](https://user-images.githubusercontent.com/39986266/79525093-a7fb4980-8094-11ea-9638-acdf24e9023d.jpg)

![myproject py-2](https://user-images.githubusercontent.com/39986266/79525102-ad589400-8094-11ea-92e0-c227606f8ddc.jpg)

In order to be able to put the output entirely in one screenshot, the font size was reduced. Any unclear, please point it out. Thanks
![myproject py-3-1](https://user-images.githubusercontent.com/39986266/79525415-628b4c00-8095-11ea-9528-c0099e2a6e81.jpg)
![myproject py-3-2](https://user-images.githubusercontent.com/39986266/79525423-67500000-8095-11ea-8329-c59da30086cb.jpg)

**Comment by jamadden** [comment]
(In the future, please do not post screenshots. The text of the output is far more helpful.)

Look closely at the error message gunicorn is producing. And then compare closely the two versions of the files you're running. You'll see that one of them is unconditionally doing something at module scope that the other one is not. Once you see that think about the error message again, and hopefully the problem becomes clear.
