### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 209-214: ordinal not in range(256)

### ISSUE THREAD

**Issue by lishulongVI** [benoitc/gunicorn#2319]
https://github.com/benoitc/gunicorn/blob/b2dc0364630c26cc315ee417f9c20ce05ad01211/gunicorn/http/wsgi.py#L322

### Env
- gunicorn (version 20.0.0)
- Python 3.7.7
- apache-superset        0.35.2
 
### Question

1. When use gunicorn start superset, feature  `export csv`, raise exception: ` UnicodeEncodeError: 'latin-1' codec can't encode characters in position 209-214: ordinal not in range(256)`

2. can use 'U8' replace 'latin-1' to fix it?
```util.write(self.sock, util.to_bytestring(header_str, "latin-1")) -> util.write(self.sock, util.to_bytestring(header_str)) ```

**Comment by benoitc** [comment]
Unfortunately no. Headers should be provided as Latin1 it is already a convenience as they really should be ascii: 

> Historically, HTTP has allowed field content with text in the ISO‑8859‑1 charset [ISO-8859-1], supporting other charsets only through use of [RFC2047] encoding. In practice, most HTTP header field values use only a subset of the US-ASCII charset [USASCII]. Newly defined header fields SHOULD limit their field values to US‑ASCII octets. A recipient SHOULD treat other octets in field content (obs‑text) as opaque data.

https://httpwg.org/specs/rfc7230.html#field.parsing

**Comment by benoitc** [comment]
also one way to fix your issue is to url-encode the value before sending it/
