### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by rowillia** [benoitc/gunicorn#2323]
Can we cut a new release?

We've seen large performance improvements with https://github.com/benoitc/gunicorn/commit/f145e90e322256f1c4e1eea8e175d2e188ceab43 and would love to be able to use it without forking 😄.  If master isn't ready to go out can we publish a hotfix with that commit on top of 20.0.4?

**Comment by jamadden** [comment]
👍 for this and it’s backport

**Comment by tilgovi** [comment]
Is it already backported?

**Comment by tilgovi** [comment]
Looks like it's already backported. I invite everyone to take a look through recent changes on master and propose additional backports in this thread. Please also flag anything breaking, otherwise we can release as 20.0.5.

**Comment by tilgovi** [comment]
Help preparing the changelog / news most welcome, too!

**Comment by benoitc** [comment]
i can take care about the release tomorrow. please yes flag any breaking change.

**Comment by tilgovi** [comment]
I propose this release be Gunicorn 20.5.0, unless someone sees breaking changes.
I also to propose to include #1450, since it is a backwards compatible change.

**Comment by tilgovi** [comment]
Ack, I said "20.5.0" but that's because I thought we were at "20.4.0". Instead, we have done four patch releases of "20.0.x".

I think I propose "20.1.0" then. Does that seem right?

**Comment by benoitc** [comment]
@tilgovi why ? Is there any change outside a patch?

**Comment by tilgovi** [comment]
There are some new features, but small:

- New `--print-config` CLI flag
- Millisecond token in access logs
- Maybe #1450 adding the `wsgi_app` config value

None of these are major. I don't worry about breaking anything, but I default to calling it a minor release because there are these new features.

**Comment by benoitc** [comment]
i agree, it should be a minor release :)

**Comment by rowillia** [comment]
@tilgovi @benoitc anything I can do to help this release get out?

**Comment by benoitc** [comment]
i have been side tracked. I will take care about a release on thursday

**Comment by benoitc** [comment]
@rowillia any test on current master is welcome :) Thanks!

**Comment by tilgovi** [comment]
@benoitc if there's anything I can do to help prepare, let me know. I'm happy to update NEWS or anything like that.

**Comment by jamadden** [comment]
Ditto

**Comment by tibudiyanto** [comment]
Will this release include #2304 and #2313? First time user of gunicorn and in here. I am happy to help what I can!

**Comment by tilgovi** [comment]
Yes, @tibudiyanto. The new version will include everything on master.

**Comment by benoitc** [comment]
@jamadden @tilgovi sorry i have been side tracked. I will come back to you asap. Lest plan a release on next Tuesday .

**Comment by rowillia** [comment]
Friendly ping - anything I can do to help this get out?  We've been running these patches for a while and it's been great for us.

**Comment by benoitc** [comment]
superseded by #2370. I take about it today.
