### ISSUE TITLE
Gunicorn worker getting restarted for long concurrent API calls.

### ISSUE THREAD

**Issue by jobyywilson** [benoitc/gunicorn#2327]
I have a flask application which is running using Gunicorn.

This flask application have an API which takes two hours to complete.

If the same API is called twice after a 30 minutes gap between two , then the process handling the first API call is getting restarted after the second API call.

Example: Initial process starts with API_1 After 30 mins API_1 is called again , then the process handling previous API_1 call is getting restarted.

Command used to start the Gunicorn server:

nohup gunicorn --bind 0.0.0.0:5000 --workers=8 run:app --timeout 7200  --preload> output.log& 
No of core : 8

I am not facing any issue while running flask in development mode.

Any idea why its behaving like this ?

Is there any way to prevent restart of the worker , if it is not idle ?

**Comment by benoitc** [comment]
AFaik if your worker stp to respond to requests answer for the timeout it will be killed per design by the arbiter. Such long call shoul dbe done asynchronously by your application. If you need to return some feedback to the users about the progression I would suggest then to use an async worker and making sure to not block the event loop.

**Comment by KumarManoj-S** [comment]
Hi, I'm facing the same issue and I'm using an async worker (`aiohttp.worker.GunicornWebWorker`). The workers reboot abruptly when I test with many concurrent requests. How to prevent the workers from rebooting?
