### ISSUE TITLE
Running gunicorn using SSL

### ISSUE THREAD

**Issue by ntx2020** [benoitc/gunicorn#2331]
I have a CENTOS 7.8 server (can't change that) that is running apache (can't change that) and is configured to run SSL (https) only.  The main application is HTML with PHP, but a module that was developed for the website is in Flask.  I installed Flask and it is running, but it was recommended that I use a production-ready Flask WSGI server, which I chose gunicorn.  I have the pages up and running on port 8000, which is fine.  What I need to do next is have the Flask pages run under https (secure) as well.  Leaving it a different port number is ok, I just need it to run encrypted.  I have watched a lot of videos and read a lot of docs, but no one really explains how to accomplish this.  Can gunicorn run as a service with apache using (https) or is this strictly an HTTP only server. I could use an example of how to configure for https and to run as a service if this is possible.  Thank you.

**Comment by benoitc** [comment]
Gunicorn can be set to run as an https server: https://docs.gunicorn.org/en/stable/settings.html#ssl

But it's rather recommended to use a termination server like nginx or haproxy on top when you arre using the sync worker.
