### ISSUE TITLE
Recommended Nginx reverse proxy

### ISSUE THREAD

**Issue by slashben** [benoitc/gunicorn#2334]
I have started to use Gunicorn to serve Flask based microservices. I see that the recommendation is to put Nginx reverse proxy before the Gunicorn. My services are running in Kubernetes and they already have a Nginx based ingress. 

Should I add another reverse proxy in between?

I'd love to hear the reason for the recommendation in general also.

**Comment by benoitc** [comment]
IMO if buffering is enabled in NGINX,  it's probably not needed.
