### ISSUE TITLE
Question about the eventlet workers number

### ISSUE THREAD

**Issue by ceshihao** [benoitc/gunicorn#2341]
Hi

I use **eventlet** workers, and find it is recommended `workers = multiprocessing.cpu_count() * 2 + 1` in some docs.
https://github.com/benoitc/gunicorn/blob/master/docs/source/configure.rst#configuration-file

However, in my testing, I find some workers are idle all the time, and the others are busy.

How does gunicorn decide whether to handle the request on busy workers or idle ones?
How can i decide the workers number?

**Comment by benoitc** [comment]
The system will load balance the workers. There is a page describing the models: https://docs.gunicorn.org/en/stable/design.html
