### ISSUE TITLE
How to config Gunicorn in Supervisor?

### ISSUE THREAD

**Issue by vladimirteddy** [benoitc/gunicorn#2349]
I config with format: ```[program:superset]
command=gunicorn -w 4 --timeout 120 -b  0.0.0.0:8084 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
user=nobody
autostart=true
autorestart=true
stderr_logfile=/var/log/superset.err.log
stdout_logfile=/var/log/superset.out.log```
But when start Supervisor, but status is: ```superset             BACKOFF            Exited too quickly (process log may have details)```.

**Comment by tilgovi** [comment]
There is an example here: https://docs.gunicorn.org/en/latest/deploy.html#supervisor

**Comment by tilgovi** [comment]
That status message makes it seem as though Gunicorn is unable to start. Are you able to start the application outside Gunicorn? Is there anything in `/var/log/superset.err.log`?

**Comment by vladimirteddy** [comment]
> There is an example here: https://docs.gunicorn.org/en/latest/deploy.html#supervisor

I'm missing ```redirect_stderr```. Thank @tilgovi.

**Comment by yashas123** [comment]
Does using numprocs in this do load balancing between the spawned processes?
