### ISSUE TITLE
API call is failing on a flask server run through gunicorn

### ISSUE THREAD

**Issue by ShetGanesh** [benoitc/gunicorn#2357]
I have python snippet which clones a GitHub repo over https access tokens, creates a branch modifies the content and pushes back. Below code works perfectly fine if run directly via python interpreter on the command line. But I have a use case where I m exposing this functionality as an API via python's flask server. Flask server is run through a python's "gunicorn" framework which is a Python WSGI HTTP Server. Now when I use the API call, it is throwing errors while cloning the repo. I have tested it by only running the flask server without gunicorn and the API call works perfectly fine and does the work without raising exceptions. But the same Flask API when called while running through Python's gunicorn I m getting this error.

Not sure how to get rid of that error.

Code Snippet:
```
 import git
    .........
    .........
    .........
    try:
        _repo = git.Repo.clone_from(
            f"https://{_token}:x-oauth-basic@{self.git_url}", _repo_dir
        )
        _new_branch = _repo.create_head(_branch)
        _repo.head.set_reference(_new_branch)
    except Exception as e:
        return False, str(e)
    _update_path = os.path.join(
        _repo_dir, f"repo1/config/"
    )
    if not os.path.exists(_update_path):
        os.mkdir(_update_path)
    with open(f"{_update_path}/users.json", "w+") as _fd:
        json.dump(_users_json, _fd, indent=4)
    _repo.git.add(A=True)
    _repo.git.commit(m=_title)
    _repo.git.push("origin", _branch)
```

DEBUG LOG:
```
2020-06-11 17:18:16,714 DEBUG: Popen(['git', 'clone', '-v', 'https://<ACCESS_TOKEN>:x-oauth-basic@github.com/ganesh/repo1.git', '/tmp/folder-1234_1591895896.185123'], cwd=/opt/ganesh, universal_newlines=True, shell=None, istream=None)
2020-06-11 17:18:16,739 DEBUG: Cmd(['git', 'clone', '-v', 'https://<ACCESS_TOKEN>:x-oauth-basic@github.com/ganesh/repo1.git', '/tmp/folder-1234_1591895896.185123'])'s unused stdout: Cloning into '/tmp/folder-1234_1591895896.185123'...

2020-06-11 17:18:16,740 DEBUG: AutoInterrupt wait stderr: b'Error reading command stream\n'
```

ERROR returned by the API:
```
{"data":"Cmd('git') failed due to: exit code(-13)\n cmdline: git clone -v https://<ACCESS_TOKEN>:x-oauth-basic@github.com/ganesh/repo1.git  /tmp/DSPE-1234_1591895896.185123\n stderr: 'Error reading command stream\n'","message":"error","status":1}
```
It looks more like gitpython is outputting something while doing the clone as a stream and nothing is reading/listening to it and it goes and raise an exception? This issue is not faced while directly cloning the repo using the commands in debug log nor when running the script via python interpreter directly. It only happens only when flask server is run via gunicorn.

Can someone tell me what in the gunicorn settings is causing this? Any way to address this issue?

**Comment by jamadden** [comment]
I *think* an exit code of -13 means the process terminated with signal 13. Assuming you're on a Linux or macOS system, I think that's SIGPIPE — which fits with your guess that something is being output but nothing is there to read it. 

You don't say how you're launching gunicorn, but is it possible it's disconnected from a TTY (i.e., in the background via some daemon manager), while your successfull test isn't (i.e., launched manually in a shell)? If so, perhaps you may need to supply stdin/stdout/stderr pipes to your cloning process? (I don't know anything about this library that you're using.)

**Comment by ShetGanesh** [comment]
Thanks for sharing the details @jamadden . Sorry, I missed those details earlier.
Yes, the gunicorn runs as a daemon where its erroring out. And in the case API call is working its not running as a daemon and bound to shell.

```
#!/usr/bin/env bash

cd $(dirname $0)/
_workers=$(awk '/processor/ {++n} END {print ((n*2)+1)}' /proc/cpuinfo)

gunicorn srv-md5:app \
--bind 0.0.0.0:4443 \
--name apiServer \
--certfile /home/y/conf/yapache/ssl.crt/server.crt \
--keyfile /home/y/conf/yapache/ssl.key/server.key \
--workers ${_workers} \
-D && echo "API Server started." || echo "API Server refused to start."
```

Running processes:
```
-bash-4.2$ ps -ef|grep -i srv
gshet     4960  2691  0 13:12 pts/1    00:00:00 grep --color=auto -i srv
root      5272 19956  0 Jun11 ?        00:01:20 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19956     1  0 Jun11 ?        00:00:25 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19960 19956  0 Jun11 ?        00:01:43 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19961 19956  0 Jun11 ?        00:01:45 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19962 19956  0 Jun11 ?        00:01:50 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19966 19956  0 Jun11 ?        00:01:42 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19971 19956  0 Jun11 ?        00:01:39 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     19973 19956  0 Jun11 ?        00:01:44 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     24166 19956  0 02:56 ?        00:00:56 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
root     30332 19956  0 Jun11 ?        00:01:49 /home/y/bin/python3.6 /home/y/bin/gunicorn srv-md5:app --bind 0.0.0.0:4443 --name apiServer --certfile /home/y/conf/yapache/ssl.crt/server.crt --keyfile /home/y/conf/yapache/ssl.key/server.key --workers 9 -D
```

Do you know how we can handle this in case of a daemonized process? (Making sure something is reading the output provided by the clone processes)

**Comment by jamadden** [comment]
No idea in general. I use a daemon manager (supervisor) that keeps the standard streams bound and directed to log files. You might check your library to see if it has the ability to direct output through pipes and capture it that way; it's using Popen so it might

**Comment by ShetGanesh** [comment]
I added below options to the gunicorn command i shared earlier
```
--enable-stdio-inheritance \
--error-logfile /tmp/gunicorn_error.log \
--capture-output \
```

and it did the trick. Now the API is working even in daemonized mode.

@jamadden Thanks for all your inputs. It helped.

**Comment by jamadden** [comment]
Ah, cool, I forgot about those gunicorn options. 

If this is solved for you, would you mind closing the issue please?
