### ISSUE TITLE
PyPI page should link to GitHub repo

### ISSUE THREAD

**Issue by cool-RR** [benoitc/gunicorn#2359]

**Comment by benoitc** [comment]
the project link is gunicorn.org why should it link to github?

**Comment by cool-RR** [comment]
I want to do create a pull request (#2360 ) and even though I was on the PyPI page, I had to google "gunicorn github" to find the GitHub homepage. 95% of other projects do link to their GitHub page. Your call.

**Comment by benoitc** [comment]
> I want to do create a pull request (#2360 ) and even though I was on the PyPI page, I had to > google "gunicorn github" to find the GitHub homepage. 95% of other projects do link to their GitHub page. Your call.

well you could have clicked on the project homepage then "view source". But we should point better to the ticket page? 

Gunicorn by itself shouldn't be attached that much to github. I will see if i can add a second link to pypi to link to the tracker.

**Comment by jamadden** [comment]
It's now easy to add multiple links! In setup.py, something like this:
```python
setup(…
        url='http://www.gevent.org/',
        project_urls={
            'Bug Tracker': 'https://github.com/gevent/gevent/issues',
            'Source Code': 'https://github.com/gevent/gevent/',
            'Documentation': 'http://www.gevent.org',
        },
…
)
```

Renders on PyPI like the following; certain URL names are recognized and get icons, and as a bonus, it also recognizes the github repo info and renders extra details:

![Screen Shot 2020-06-12 at 05 35 59](https://user-images.githubusercontent.com/1256082/84494201-b158fa80-ac6e-11ea-9c86-e775c8e4524d.png)

**Comment by hugovk** [comment]
Please see PR #2363.
