### ISSUE TITLE
How to filter out accesslog?

### ISSUE THREAD

**Issue by skaa** [benoitc/gunicorn#2361]
How to configure gunicorn to filter out access log by ip address? I need to log only remote requests. For example, nginx has [conditional logging](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#enabling-conditional-logging) as configuration onption.

**Comment by tilgovi** [comment]
This is not a feature of Gunicorn at this time, but you can completely configure Gunicorn logging with the Python logging module. You can start from this example: https://github.com/benoitc/gunicorn/blob/master/examples/logging.conf

**Comment by benoitc** [comment]
closing as answered.

**Comment by mRoca** [comment]
Just for the record, this is a way to achieve this:

```bash
gunicorn --logger-class app.logger.CustomGunicornLogger
# or in the gunicorn config file:
# logger_class = 'app.logger.CustomGunicornLogger'
```

```python
# file app.logger

from gunicorn.glogging import Logger as GunicornBaseLogger

class CustomGunicornLogger(GunicornBaseLogger):

    def access(self, resp, req, environ, request_time):
        if "/health" not in req.path:
            super().access(resp, req, environ, request_time)

```
