### ISSUE TITLE
Gunicorn with gevent worker having an issue with send_file on python 2.7.7

### ISSUE THREAD

**Issue by bimhud** [benoitc/gunicorn#2362]
See the actual issue at https://github.com/pallets/flask/issues/3655

**Comment by jamadden** [comment]
On Python 2, gunicorn attempts to call the C system call `sendfile` directly. That tends to fail when the socket is in non-blocking mode, and under gevent, sockets are usually non-blocking. 

On Python 3, gunicorn will use the standard library functions (`socket.sendfile` in recent gunicorn versions). gevent is aware of that and monkey-patches it appropriately to work with non-blocking sockets.

On Python 2, and with older versions of gunicorn, when using gevent your best bet is probably just to disable gunicorn's attempts at using `sendfile` with [`—no-sendfile` or equivalent](https://docs.gunicorn.org/en/latest/settings.html#sendfile).

**Comment by benoitc** [comment]
@jamadden is there anything to do on that topic?

**Comment by jamadden** [comment]
The only thing to do would be to patch versions of gunicorn that maintain Python 2 support to not call `sendfile` if non-blocking sockets are in use. Since there's an easy workaround, I'm not sure it's worth the cost.

**Comment by benoitc** [comment]
@jamadden by "tend to fail" you mean not always? it was working in my small tests, one workaround also would be blocking the socket until the call en. Otherwise I am fine to document the -- `no-sendfile` option workaround. Thoughts?

**Comment by jamadden** [comment]
Right, not always. It heavily depends on buffering and client behaviour. Also the behaviour on `localhost` is very different than on IP connections (at least on linux).

> one workaround also would be blocking the socket until the call en.

I don't quite understand that, but there's no way to block on anything. The operating system has full control of the socket at this time. I suppose one might repeatedly try to loop across `sendfile`, catching errors, watching for EOF, etc, but that's not really any more efficient than using the existing socket methods.

**Comment by benoitc** [comment]
> I don't quite understand that, but there's no way to block on anything. 

I meant blocking the socket before giving it to the sendfile function. Not sure it wouldn't change anything though. Should we make a note somewhere about that usage of the `--no-sendfile` option?

**Comment by jamadden** [comment]
> Should we make a note somewhere about that usage of the --no-sendfile option?

That would probably be nice for those still using Python 2 (which includes my organization and many others still).
