### ISSUE TITLE
Do something only for one worker and share that with the rest

### ISSUE THREAD

**Issue by HeyItsMeNobody** [benoitc/gunicorn#2365]
I get that I am gonna need some kind of database for this, I have MongoDB.
I could use a cronjob, But this would need to be seperate again.

Is there anyway to say, Run a Python script that uses APScheduler to fetch data and put it in an API without needing to create something like a cronjob?

**Comment by benoitc** [comment]
you can always start your own local storage in a hook. but unfortunately there is no api yet to do that.
