### ISSUE TITLE
Tensorflow saved_model in flask app causes gunicorn WORKER TIMEOUT

### ISSUE THREAD

**Issue by cmutrufflepig** [benoitc/gunicorn#2369]
I know `[CRITICAL] WORK TIMEOUT` is a pretty frequently asked question, but I don't see anyone with the same source of error I've pinpointed.

So I have a flask app which does prediction using Tensorflow. I load the model using [`my_model = tf.saved_model.load(path_to_model)`](https://www.tensorflow.org/api_docs/python/tf/saved_model/load) , instantiate the service class with` my_service=Service(my_model)` , test run it using [`my_service.predict(sample_user_input)`](https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators) (note this works). And then start flask, so basically:

```
#API.py
my_model = tf.saved_model.load(path_to_model)
my_service=Service(my_model)
assert my_service.predict(sample_user_input, "neuralNets").is_ok  #this passes
@app.route('/')
def foo(user_input):
    results = my_service.predict(user_input, "neuralNets")        #this does not
    return results.toJson()
```
I can pinpoint the source of error to `tf_model.signatures['predict']` in the` .predict` method. Because when .predict receives "linear" instead of "neuralNets" as arg, everything works. And the only difference between those two is` tf_model.signatures.`

I can also confirm this is a gunicorn issue, because if I just run `python3 API.py` use Flask's builtin server, which is pretty crap, it works fine.

So I followed [this](https://github.com/benoitc/gunicorn/issues/1440), and [this](https://github.com/benoitc/gunicorn/issues/1801) thread, and played with gunicorn configs, I tried:

updating gunicorn from 19.9.0 to 20.0.4
--timeout=120
--worker-class=gthread/gevent
--threads 2/3/4...
--workers=1 + multiprocessing.cpu_count() * 2
--preload 

Nothing works. So here I am, any help is appreciated. Also I've reproduced the same result on two different ubuntu machines and docker image running on k8s. So this is definitely not a "just reboot" problem.

Some logs to refer to:
```
[2020-07-01 11:28:14,194] [12489] [INFO] [utils.utils] ISM ranking time  :  0.3613 sec (the test call using neuralNets which works)
[2020-07-01 11:28:14 +0200] [12489] [INFO] Starting gunicorn 20.0.4
[2020-07-01 11:28:14 +0200] [12489] [INFO] Listening at: http://0.0.0.0:5099 (12489)
[2020-07-01 11:28:14 +0200] [12489] [INFO] Using worker: gthread (i also tried gevent)
[2020-07-01 11:28:14 +0200] [12634] [INFO] Booting worker with pid: 12634
>calls the API here with neuralNets arg
[2020-07-01 11:28:58 +0200] [12489] [CRITICAL] WORKER TIMEOUT (pid:12634)
[2020-07-01 11:28:59 +0200] [12780] [INFO] Booting worker with pid: 12780
```
System
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)
tensorflow==2.0.0
gunicorn==20.0.4/19.9.0 neither works
python 3.7.0 , 3.6.6 neither works

 worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: True
  reuse_port: False
  loglevel: debug
  capture_output: False
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']

**Comment by benoitc** [comment]
why do you think it is a gunicorn issue? If the request is too long the worker will time out and be killed. The same behaviour happen on the threaded worker but less often. Afaik you need to make sure your long request is not blocking the scheduler. 

Generally speaking the common patterns to handle ML requests are:

* poll at client level your server to retrieve the result kept outside of gunicorn 
* use an asynchronous worker and make sure to handle the result asynchronously to not block the scheduler

Remember that HTPP is a stateless protocol...

**Comment by cmutrufflepig** [comment]
Makes sense, thank you. I'll investigate further. Closing issue for now.

**Comment by SagiMedina** [comment]
@cmutrufflepig hey, how did you solve it?
I'm facing similar issue, when worker heavily use CPU it been shutdown with this timeout message.
Multiple runs end the same way after different duration...
@benoitc any thoughts?

**Comment by bzamecnik** [comment]
IMHO the problem might in in `--preload`. It seems that gunicorn pre-loads the app, including the TF session, which is not fork-safe. So then after workers are forked it fails. Try avoiding `--preload` or setting `preload_app=False` in the config file.

**Comment by AdityaSoni19031997** [comment]
re-visiting this thread, what would be a better choice or deciding factors when it comes to pre_fork Vs post_fork init method? Does this impact the concurrency overall the gunicorn can achieve or it mainly impacts let's say (when it comes to ML), lesser memory footprint as model is only loaded once into memory rather than being loaded multiple times wrt post_fork + multiple workers?
