### ISSUE TITLE
freezing gunicorn for 20.1 release

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#2370]
I would like to make a release of gunicorn. If you have any issues you want it to be merged please let me know now. Otherwise it will be for the next release.

**Comment by benoitc** [comment]
please don't merge anything in master.

**Comment by tilgovi** [comment]
Bump. If you don't have time please let me know if I should prepare the release. We have some PRs I'd like to merge.

**Comment by JordanP** [comment]
@benoitc hi. I'd love to have https://github.com/benoitc/gunicorn/pull/2277 merged before a new release. Thanks !

**Comment by benoitc** [comment]
@tilgovi there is a need for one patch was struggling to put it online. Can you confirm all examples pass on your end ? 

@JordanP sorry for the delay to take cae care about the PR, I commented. we can discuss it oonline on IRC too

**Comment by ludwiktrammer** [comment]
@benoitc Is there an update on when the 20.1 release will be able to come out finally?

**Comment by DancingPete** [comment]
Forgive a likely silly question, but "20.1 coming out" means making it available on pypi for installation through pip? The documentation lists 20.1 as the current stable version. I'm hoping to see it appear on pypi, but think this thread may have been about moving the status to stable rather than making it available on pypi. Sorry for the trouble.

**Comment by benoitc** [comment]
I will publish it this week-end on pypi. I wanted to tag before going off for some days

**Comment by DancingPete** [comment]
> 
> 
> I will publish it this week-end on pypi. I wanted to tag before going off for some days

Thanks very much for the info.

**Comment by garhiggins** [comment]
Any update on when 20.1 will be released? Sorry to pester, but I'm also very excited to upgrade :)

**Comment by benoitc** [comment]
i am waiting for a feedback but this should be good tomorrow.
