### ISSUE TITLE
Type stubs / Type annotations / mypy

### ISSUE THREAD

**Issue by MartinThoma** [benoitc/gunicorn#2374]
I'm currently annotating types for my codebase. While doing so, I was wondering what the types of the parameters of [glogging.access](https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py) are:

    def access(self, resp, req, environ, request_time): ...

Maybe it would even be possible to add a type stub file?

**Comment by tilgovi** [comment]
This has been covered a bit in #1393. I would welcome and champion contributions to add types to Gunicorn. The code is Python 3 only so there is nothing to prevent it.

**Comment by tilgovi** [comment]
I'm going to close this because I believe the question of whether we would add a type stub (or types directly) has been answered already, but so far no one has taken this initiative. Thank you for bumping the issue, though. It's good to know that it's wanted.

**Comment by foobacca** [comment]
For anyone who lands here looking for type hints, they are now in typeshed, as mentioned in https://github.com/benoitc/gunicorn/issues/3420

The direct link to the folder in typeshed, if you want to browse for types, is https://github.com/python/typeshed/tree/main/stubs/gunicorn/gunicorn
