### ISSUE TITLE
Version 19.8+ not importing app correctly

### ISSUE THREAD

**Issue by dsbowen** [benoitc/gunicorn#2378]
I have the following folder structure:

```
folder0/
  app.py
folder1/
  app.py
```

In both `app.py` files is an app instance named `app`. In `folder0` I run:

```bash
$ gunicorn app:app
```

Using gunicorn 18.0-19.7, this works as expected (i.e. runs the `app` instance from `app.py` in `folder0`). Using gunicorn 19.8+, this runs the `app` instance from `app.py` in `folder1`.

Further details:

1. If I rename `folder1` to something else, gunicorn 19.8+ simply can't find the app.
2. Passing `--chdir /path/to/folder0` doesn't fix the issue.
3. Clearing `__pycache__` and `*.pyc` folders/files doesn't fix the issue.
4. `folder1` appears before `folder0` in my `sys.path`. I don't know if this is relevant.

**Comment by jamadden** [comment]
19.8 subtly changed the timing and way in which gunicorn manipulates sys.path (see #1481). 

> folder1 appears before folder0 in my sys.path. I don't know if this is relevant.

That's definitely relevant. `app:app` is a Python module specification. Those are loaded from the Python `sys.path`. If `folder1` is on the path before `folder0`, `app:app` will refer to `folder1/app.py:app`. Consider explicitly setting your PYTHONPATH to contain the `app` module you want, or neither, allowing gunicorn's path manipulations to take effect. This can be done in the gunicorn configuration, or with the environment variable.

> Passing --chdir /path/to/folder0 doesn't fix the issue.

I can understand why that would be surprising. While gunicorn will make sure that the `chdir` is on the path, it won't change its priority if it's already there. So if the path is `folder1:folder0`, using `folder0` as the chdir won't make any difference.

**Comment by benoitc** [comment]
fixed in latest releases
