### ISSUE TITLE
allocating memory while forking gunicorn workers 

### ISSUE THREAD

**Issue by punespirit** [benoitc/gunicorn#2383]
Hi, I am using gunicorn for serving flask REST APIs and doing some NLP jobs which uses tensorflow. The challenge I am facing is workers are getting killed in middle because of memory issue (reason I can say this is because jobs run successfully when I run them without gunicorn worker).

So I need to play with allocation of memory to gunicorn workers. I could not find any help on documents.
Any config parameters and example will be appreciated.

**Comment by jamadden** [comment]
gunicorn has no control over memory allocation: That's all up to Python and your application.

The only knob I know of to turn is to enable preloading the application into the gunicorn master. That can result in sharing some memory between workers, and speed up forking workers. It doesn't work for all applications, though.

**Comment by punespirit** [comment]
thanks for sharing the information on gunicorn side.

could you please share any authentic tested link/references on how it can be done on Python side.
I am using nginx which is using gunicorn sock and starting Flask REST APIs, and I need to increase/decrease memory of these gunicorn worker Python http API processes.

Any help will be great. Thanks.

**Comment by jamadden** [comment]
There are lots of great resources about tuning Python memory usage if you search for them. One common trick [is to apply `__slots__` to small, common classes](https://dev.nextthought.com/blog/2018/08/cpython-vs-pypy-memory-usage.html).

**Comment by jamadden** [comment]
This doesn't seem related to gunicorn anymore, so I'm going to close this issue. Please feel free to reopen it with new information if it relates to gunicorn.
