### ISSUE TITLE
documentation code block not displayed properly

### ISSUE THREAD

**Issue by antoine-gallix** [benoitc/gunicorn#2386]
In the [following file](https://github.com/benoitc/gunicorn/blob/5d0c7783008d4df87d579a576d19182c4a95caf7/docs/source/run.rst) of the documentation, one code block is not displayed properly. Very minor typo in ReStructuredText probably. Just after the line `You can now run the app with the following command:`

**Comment by berkerpeksag** [comment]
Good catch, thanks! There are two possible fixes:

1. Drop the second : in:

   ```rst
   You can now run the app with the following command::
   ```
2. Remove the next line:

   ```rst
    .. code-block:: text
    ```

We are using both ways in the file so both solutions look good to me. Would you liked to submit a PR?

**Comment by antoine-gallix** [comment]
I don't know how I end up looking at this branch in particular, but it seems that the problem doesn't appear any more on the published docs, and I also can see that the typo is corrected on the master branch, so something did happen that fixed the thing.
