### ISSUE TITLE
A subprocess of a gunicorn gevent worker cannot use the network #347

### ISSUE THREAD

**Issue by namenameshuai** [benoitc/gunicorn#2388]
1 parent 5afb03e commit 33f7c96db62ee1e7ecade8cb0613cff1e58e6447

how use mul-process in gevent?

@app.route("/")
def test():
    p = Process(target=test_func)
    p.start()
    return response

def test_func():
    import time
    time.sleep(10)

in this issue #348 had changed,but 1 parent 5afb03e commit 33f7c96db62ee1e7ecade8cb0613cff1e58e6447 is changed again, why is this?

**Comment by benoitc** [comment]
that's a question for the gevent project.
