### ISSUE TITLE
GUnicorn==20.0.4 not working on GPU image

### ISSUE THREAD

**Issue by adeepsri** [benoitc/gunicorn#2397]
I tried serving gunicorn with worker=1 and gthreads=4 in GPU Container. But it is failing with error:
`Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method`

Similiar issue been raised at https://stackoverflow.com/questions/61120314/cannot-launch-gunicorn-flask-app-with-torch-model-on-the-docker

Can someone please check once.

**Comment by benoitc** [comment]
gunicorn is not using multiprocessing. Which library is triggering the issue? do you have any example to reproduce the issue?

**Comment by benoitc** [comment]
looking at your example it seems you embed gunicorn your app which may be the issue. Do you reproduce it when you put everything in a simple wsgi app loaded by gunicorn?

**Comment by adeepsri** [comment]
Thanks for replying I am using pytorch  in my application. 
This is the issue raised in pytorch https://github.com/pytorch/pytorch/issues/40403 when using multiprocessing .

I am using this configuration while running the Gunicorn

`
settings = {                                                                                                                                                                                                                                                                        'bind': '%s:%s' % ('0.0.0.0', port),                                                                                                                                                                                                                                            'access_logfile': '-',                                                                                                                                                                                                                                                          'loglevel': 'info',                                                                                                                                                                                                                                                             'timeout': 5000,                                                                                                                                                                                                                                                                'reload': 'true',                                                                                                                                                                                                                                                               'workers': int(os.environ.get("GUNICORN_WORKERS", "1")),                                                                                                                                                                                                                        'threads': int(os.environ.get("GUNICORN_THREADS", "4")),                                                                                                                                                                                                                        'worker_class': 'gthread'                                                                                                                                                                                                                                                   }
--
`

UserModelApplication(app, model_object, settings=settings).run()
--



class StandaloneApplication(gunicorn.app.base.BaseApplication):                                                                                                                                                                                                                     def __init__(self, application, settings = None):                                                                                                                                                                                                                                   self._application = application                                                                                                                                                                                                                                                 self._settings = settings or {}                                                                                                                                                                                                                                                 super(StandaloneApplication, self).__init__()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               def load_config(self):                                                                                                                                                                                                                                                              config = dict(                                                                                                                                                                                                                                                                      [                                                                                                                                                                                                                                                                                   (key, value)                                                                                                                                                                                                                                                                    for key, value in self._settings.items()                                                                                                                                                                                                                                        if key in self.cfg.settings and value is not None                                                                                                                                                                                                                           ]                                                                                                                                                                                                                                                                           )                                                                                                                                                                                                                                                                               for key, value in config.items():                                                                                                                                                                                                                                                   self.cfg.set(key.lower(), value)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def load(self):                                                                                                                                                                                                                                                                     return self._application                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class UserModelApplication(StandaloneApplication):                                                                                                                                                                                                                                  """                                                                                                                                                                                                                                                                             Gunicorn application to run a Flask app in Gunicorn loading first the                                                                                                                                                                                                           user's model.                                                                                                                                                                                                                                                                   """                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             def __init__(self, app, user_object, settings = None):                                                                                                                                                                                                                              self.user_object = user_object                                                                                                                                                                                                                                                  super().__init__(app, settings)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             def load(self):                                                                                                                                                                                                                                                                     logger.debug("LOADING APP %d", os.getpid())                                                                                                                                                                                                                                     try:                                                                                                                                                                                                                                                                                logger.debug("Calling user load method")                                                                                                                                                                                                                                        self.user_object.load()                                                                                                                                                                                                                                                     except (NotImplementedError, AttributeError):                                                                                                                                                                                                                                       logger.debug("No load method in user model")                                                                                                                                                                                                                                return self._application
--

**Comment by benoitc** [comment]
First thing to check imo is to try without the StandaloneApplication. Ie by using a command line like `gunicorn ... ` . Also I would always recommend to run more than one worker to make the work more // than it is with the threads.

**Comment by adeepsri** [comment]
ok sure, I will run and update you

**Comment by benoitc** [comment]
@adeepsri ?

**Comment by adeepsri** [comment]
@benoitc This issue is with torch library https://github.com/pytorch/pytorch/issues/40403 . I think fix is required in torch not in gunicorn

**Comment by eladrich** [comment]
Any update on this issue? I'm trying to do inference with Pytorch and Gunicorn and encounter a `Cuda error: initialization error.`

**Comment by zzvara** [comment]
Same here with Seldon Operator `1.9.1`.

**Comment by benoitc** [comment]
GPU process are not designed for running http apps.

**Comment by rlleshi** [comment]
> GPU process are not designed for running http apps.

@benoitc could you please elaborate on what you mean by that? I have been able to deploy seldon-microservices (which use gunicorn) on cuda devices.
