### ISSUE TITLE
Does Gunicorn --keyfile support encrypted private keys?

### ISSUE THREAD

**Issue by bsolomon1124** [benoitc/gunicorn#2410]
Does Gunicorn offer any means for SSL support where the private key is password-protected/encrypted?

With Flask (which is what I'd like to get away from here, since it's not intended for production), this looks like:

```python
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH, cafile='xxx')
ssl_context.load_cert_chain(certfile='xxx', keyfile='xxx', password='xxx',)
ssl_context.verify_mode = ssl.CERT_REQUIRED
app.config.from_mapping({"SSL_CONFIG": sslconfig})
app.run(host='0.0.0.0', ssl_context=ssl_context)
```

(Notice that the underlying `.load_cert_chain()` is what takes an optional passphrase.

**Comment by bsolomon1124** [comment]
Similarly with `gevent` I see that it can be run from a Python-script entry point and take an ssl context param, e.g.:

```python
from gevent.pywsgi import WSGIServer
from gevent.ssl import SSLContext

context = SSLContext()
context.load_verify_locations(cafile=CA_FILE)
context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE, password=PASSPHRASE)

http_server = WSGIServer(..., ssl_context=context)
```

**Comment by bsolomon1124** [comment]
Edit: to clarify the question, it would seem that the answer for the command line is _no_, but I'm wondering if maybe `WSGIApplication` could be subclassed (or something like that) to permit this argument.  Looking through the source, I see the call to [`wrap_socket()`](https://github.com/benoitc/gunicorn/blob/e636bf81989bb833d2b99104feb11e86c3f2c43a/gunicorn/workers/sync.py#L131), so now wondering if it might work to add an [option](https://github.com/benoitc/gunicorn/blob/b80a3293542739b878f12c0b777ed3640aad5b37/gunicorn/config.py#L174) with `value.section == 'SSL'`.

**Comment by bsolomon1124** [comment]
A "yes" or "no" would be much appreciated.

**Comment by tilgovi** [comment]
Perhaps solving #1140 would make this possible.

**Comment by benoitc** [comment]
Closing the issue since the new [ssl_context](https://github.com/benoitc/gunicorn/blob/master/docs/source/settings.rst#ssl_context) hook should fix it.

**Comment by Kuldip-Nanda** [comment]
Hi,
When will the new ssl_context function will be available? If it is already available, can you point me to how to use it for an encrypted private key?
Thanks in advance.
Regards
Kuldip

**Comment by vishwaslokeshappa** [comment]
Will Gunicorn service start successfully if the SSL private key is password-protected/encrypted without prompting for the password?
