### ISSUE TITLE
API Endpoint timed out with error code 500 when Gunicorn worker restarts

### ISSUE THREAD

**Issue by qingyangtan** [benoitc/gunicorn#2417]
- API endpoint is loaded with Flask & Nginx & Gunicorn, housing memory intensive ML models. It takes ~30s for the model to be fully loaded.
- With 3 gunicorn workers, everything runs smoothly during load testing
- Bumped up to 5 gunicorn workers,  everything runs smoothly during load testing as well

The issue came is when the gunicorn worker starts to restart after hitting max request. At the time of testing with 5 workers, when 1 is restarting, 4 is still up and should be able to withstand the load. But instead, the test returns a server timed out error 500 proportional to the number of testing users. 

We tried adding --preload, but all the requests start to fail (probably not safe-threaded).

Any advice is greatly appreciated.

**Comment by jamadden** [comment]
Why are you setting a maximum number of requests? Do you have a memory leak?

**Comment by qingyangtan** [comment]
There was an occasion of memory leak. And restarting workers help to clear the memory.

**Comment by benoitc** [comment]
it's unclear what the issue was. did all workers beeing closed at the same time?

**Comment by benoitc** [comment]
stalled issue.
