### ISSUE TITLE
How to fetch client ip

### ISSUE THREAD

**Issue by ii-Python** [benoitc/gunicorn#2426]
I'm using flask, and I have a webserver set up with Cloudflare pointing to it. I'm relying on the Cloudflare headers to figure out the IP of the user. This works fine when I run the app using Python, however, using gunicorn it gives me an error where I fetch the longitude, latitude of the client's IP. Any ideas?

**Comment by jamadden** [comment]
What's the error and traceback?

**Comment by ii-Python** [comment]
It's the default error message for referencing an object that doesn't exist.
Ex. `somedict['thatdoesntexist']`

Again, it errors when I try to fetch the location data from https://ipinfo.io after passing in the IP address **that I obtain from the cloudflare headers**, so I'm not sure if gunicorn messes with headers, or if something else is the problem. Although I can 100% confirm the application works if I do not launch it via gunicorn.

**Comment by jamadden** [comment]
If you won't post details about the error and how you're producing it, then can you tell us what steps you've taken to debug the issue? Have you actually looked at what headers your app gets in both situations? You should easily be able to tell if "gunicorn messes with headers" (it doesn't. Not beyond what's required in the WSGI specification, as far as I recall).

**Comment by ii-Python** [comment]
Sorry about that, I've been at school all day so that's why I haven't posted any _logical_ debug information. The minute I get home I plan on seeing what I get for the headers, thanks though.

**Comment by ii-Python** [comment]
So, I did some debugging and without gunicorn I receive a normal JSON response containing lon/lat data. However, upon using gunicorn, I get a 403 back from the server (saying my token is invalid).

Nevermind, I'm just spazzing out today. I've been using gunicorn from the command line and forgot that I need to load my .env file. I'll go look for how to make a gunicorn start file type thing. Thanks for the help :)
