### ISSUE TITLE
Just a check on SSL progress

### ISSUE THREAD

**Issue by pipeti** [benoitc/gunicorn#2429]
Hi,

This is just a check on the "Improve SSL UX" and associated issues' (including TLSv1.3 and newer Python versions) status. It's somewhat unclear if it's dropped, stopped or waiting for contributors.
Appreciate the update!

Cheers,
Peter

**Comment by benoitc** [comment]
look at https://github.com/benoitc/gunicorn/pull/2012 any feedback/testing is welcome . TLSv1.3 is already supported though.
