### ISSUE TITLE
gunicorn.sock failed

### ISSUE THREAD

**Issue by praveencqr** [benoitc/gunicorn#2433]
I have been using gunicorn with nginx for a CPU intensive django application. 
I see 502 error almost 99% of the times. I checked nginx log and got these error message.
connect() to unix:/run/gunicorn.sock failed (11: Resource temporarily unavailable) while connecting to upstream. ...

please help me to get rid of the issue

**Comment by benoitc** [comment]
you probably found a solution, but I would check the permissions and ensure the order of you start (gunicorn need to be started first).
