### ISSUE TITLE
How should I use gunicorn to improve the performance of falcon

### ISSUE THREAD

**Issue by idbeta** [benoitc/gunicorn#2434]
hi, I used gunicorn+falcon to build a test server, but its performance is no good enough, my AWS machine configuration is 8 vCPUs, 21 G memory, I have tested the following methods: 
1. gunicorn --worker-class=gevent --worker-connections=3000 --workers=17 falcontest:app -b 0.0.0.0:8000
2. gunicorn --worker-class=gthread --workers=16 --threads=2000 falcontest:app -b 0.0.0.0:8000
3. gunicorn --worker-class=eventlet --worker-connections=1000 --workers=16 falcontest:app -b 0.0.0.0:8000
4. gunicorn --workers=16 falcontest:app -b 0.0.0.0:8000
Is there any other better way？

**Comment by benoitc** [comment]
do you put gunicorn behind nginx?  what do you mean by "performance is ngo ood enough"? What does your application? 

Generally speaking you should ensure your HTTP application is mostly doing HTTP and ensure any call behind is fast enough. Don't try to handle long processes and such thing on direct call.

For gunicorn:

- use async workers when you think keepalive would be useful, or want to handle detached requests like websockets .
- use sync worker when you can do fast requests. 
- The number of worker to starts (and threads) depends on the number of Cpus you have or real // process units. 
- Ensure your backlog queue is ok
- optimize your system about accepting or lingering.

Have a look to the docs there:
https://docs.gunicorn.org/en/stable/design.html
or 
https://docs.gunicorn.org/en/stable/faq.html


Some professionals consultants may help you around also.

**Comment by idbeta** [comment]
Thanks for your reply, I know how to do now.
