### ISSUE TITLE
 [11] [ERROR] Exception in worker process in flask app

### ISSUE THREAD

**Issue by mynk007** [benoitc/gunicorn#2437]
![image](https://user-images.githubusercontent.com/72708920/95786896-147a9c80-0cf6-11eb-92ec-749bfb60e9c0.png)

![image](https://user-images.githubusercontent.com/72708920/95787016-4ee43980-0cf6-11eb-8b5b-fa847eb9f765.png)

here is my Procfile
![image](https://user-images.githubusercontent.com/72708920/95787231-b1d5d080-0cf6-11eb-8550-46bbfe30a990.png)

anyone help me to fix this

**Comment by larawehbe** [comment]
it seems that you are running another flask app on the same address/port
make sure that no application is running on the same address ( ie : localhost or 127.0.0.1, check the address its running on ) 
and make sure that the port is not being allocated to another running application
