### ISSUE TITLE
[Forum] Gunicorn statsd metrics

### ISSUE THREAD

**Issue by juneauwang** [benoitc/gunicorn#2440]
Hi guys,

versions:
Gunicorn: 20.0.4
Python: 3.8
telegraf: 1.15.3
Superset: 0.37.1

I am new to gunicorn and I am using it in Superset. I'd like to use telegraf statsd plugin to collect gunicorn metrics and send to grafana. Have correct set configuration and gunicorn worker value can now be seen in grafana. 
However, I read https://docs.gunicorn.org/en/stable/instrumentation.html , there are more than numbers I can see.  I would like to check whether gunicorn send the metrics, how can I do it?

info:
My gunicorn start command:
`gunicorn -w 100  -k gevent --timeout 120 -b 0.0.0.0:8088 --limit-request-line 0  --limit-request-field_size 0  --access-logfile /var/log/superset/access.log --error-logfile /var/log/superset/error.log --log-file /var/log/superset/server.log --log-level DEBUG --statsd-host=127.0.0.1:9124 --statsd-prefix=superset "superset.app:create_app()" `

**Comment by juneauwang** [comment]
Also, I find that only when gunicorn started, it will send metric once. Can't get any info with tcpdump -i any -w statsd-ts.dump "(port 9124)" after

**Comment by willejs** [comment]
@juneauwang did you ever resolve this?
