### ISSUE TITLE
When use preload the HUP signal will not work

### ISSUE THREAD

**Issue by MrRace** [benoitc/gunicorn#2449]
I start  my service like `gunicorn --preload -c gunicorn.conf.py --pid /var/run/gunicorn.pid server:app`,  When I try to use the command `kill -HUP master_pid` to quit the old works quit and start new works. However it seems not work.   From the guide note:
https://docs.gunicorn.org/en/stable/signals.html, it say:
```
HUP: Reload the configuration, start the new worker processes with a new configuration and gracefully shutdown older workers.
 If the application is not preloaded (using the preload_app option), Gunicorn will **also** load the new version of it.
```
The "Also" seems mean, both use or not use the preload , Gunicorn can load a new version of the configuration?

**Comment by tilgovi** [comment]
Gunicorn cannot reload the application with `preload`.
