### ISSUE TITLE
Forum Question: how to properly start up  multiprocessing workers programmatically?

### ISSUE THREAD

**Issue by johann-petrak** [benoitc/gunicorn#2450]
All examples I found for how to run k processes of an app show using the `gunicorn` command line. Is there a proper way for how to do this programmatically? Is this documented somewhere?

**Comment by johann-petrak** [comment]
What I mean is does gunicorn have a well documented stable API so that everything that can be done from the command line or config files can be done programmatically from Python code? I was not able to find this and I feel hesitant to just look at the gunicorn source code and figure things out: unless the internals I am using then are meant to be a stable API that might break in the future.

**Comment by benoitc** [comment]
Th configuration is a standard python module that can be abused to do such things. You can find an example in the sources for it.

**Comment by johann-petrak** [comment]
Thanks! I
I think I found it : https://github.com/benoitc/gunicorn/blob/master/examples/standalone_app.py

**Comment by benoitc** [comment]
i wouldn't suggest that. This will reduce the possibility of gracefully reload your application. I was instead suggesting thing like importing some code and use a function there: https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py#L70

see: https://docs.gunicorn.org/en/stable/configure.html#configuration-file

What you  are linking is documented there: 
https://docs.gunicorn.org/en/stable/custom.html
