### ISSUE TITLE
murder_worker does not let enough time for sigabort

### ISSUE THREAD

**Issue by tardyp** [benoitc/gunicorn#2454]
Hello,

We are debugging some cases where our worker are getting overloaded, and we hit the murder timeout.

In this code, we don't see an additional delay between SIGABRT and SIGKILL
https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L500

In practice, we never see the SIGABRT hook on our workers, so we cannot dump the thread stacks to see where we are at that point

De we miss another timeout mechanism?
Shall we patch arbiter to add another graceful timeout?

**Comment by tilgovi** [comment]
The delay is only supposed to be one second here as a best effort to let the worker respond to the abort by logging or otherwise dumping some state.

I'm working on fixing the graceful shutdown for all the async worker types so that they can notify the arbiter not to kill them during graceful shutdown. Abort is not a graceful shutdown, though.

**Comment by tardyp** [comment]
In our case, the goal was to let the worker dump stack traces for all its threads. So that we can know what is causing the large load.

I kinda insist on the specificity of this bug, and the need to be taken in account. Can we keep the bug open until your fix is in?

**Comment by tardyp** [comment]
Also, you mention that the delay is supposed to be one second, while in my tests, there is *no delay*. 

This is because the following check will be true for the second check (after we first aborted the worker), as it was for the first check. last_update() won't be updated as we are in a case of worker lock.

```
    if time.time() - worker.tmp.last_update() <= self.timeout:
```

**Comment by tilgovi** [comment]
There should be a delay because the arbiter only runs its main loop once per second unless it receives a https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L351
