### ISSUE TITLE
How to set access/error log format to JSON

### ISSUE THREAD

**Issue by evandam** [benoitc/gunicorn#2457]
Hi folks,

Is there an "official" method of setting Gunicorn logging to JSON? Having a format like the following example would be very helpful for ingesting logs easily.

```json
{"method": "GET", "path": "/ping", "status": 200, "client_ip": "127.0.0.1", "timestamp": "2020-11-12T15:49:43.333500Z", "user_agent": "curl/7.64.1", ...}
```

**Comment by aaron-trout** [comment]
I have just implemented this for one of our services. Here is what my gunicorn config file looks like:

```python
import json

bind = '0.0.0.0:8080'
workers = 3
accesslog = '-'

access_log_format = json.dumps({
    'remote_address': r'%(h)s',
    'user_name': r'%(u)s',
    'date': r'%(t)s',
    'status': r'%(s)s',
    'method': r'%(m)s',
    'url_path': r'%(U)s',
    'query_string': r'%(q)s',
    'protocol': r'%(H)s',
    'response_length': r'%(B)s',
    'referer': r'%(f)s',
    'user_agent': r'%(a)s',
    'request_time_seconds': r'%(L)s',
})
```

If you want to customise the fields which it outputs then see https://docs.gunicorn.org/en/stable/settings.html#access-log-format

**Comment by evandam** [comment]
That's the solution I ended up going with, thanks for sharing! I think I was hoping there would be a more "native" way to do this without templating out the JSON ourselves but it works well and is easy enough to change as needed.

**Comment by codeinthehole** [comment]
Here's a way of ensuring all output is JSON formatted:
https://til.codeinthehole.com/posts/how-to-get-gunicorn-to-log-as-json/

**Comment by FANGOD** [comment]
> Here's a way of ensuring all output is JSON formatted: https://til.codeinthehole.com/posts/how-to-get-gunicorn-to-log-as-json/

I have tried many solutions and this is the best.
