### ISSUE TITLE
How to handle signals in (flask) app

### ISSUE THREAD

**Issue by lz006** [benoitc/gunicorn#2462]
Hi everyone,

We're planning to migrate from Waitress to Gunicorn because of capability to shutdown gracefully. But we couldn't find a way to react to signals in our flask app. We are used to do some cleanup tasks using "signal" lib. Unfortunately it seems that signals aren't visible anymore when serving flask app by Gunicorn instead of Waitress.

It is clear that Gunicorn allows workers to finish their work before they get killed. But we need to have a piece of code that comes into play when we are in some kind of a "shutdown process".

Hoping that someone understands the pain.

thanks

**Comment by benoitc** [comment]
can't use you use hooks for it? I think you can probably attach a custom function using atexit also.

**Comment by lz006** [comment]
thanks for pointing to server hooks we didn't notice before.
