### ISSUE TITLE
Directory of gunicorn script added to PYTHONPATH unconditionally

### ISSUE THREAD

**Issue by cryvate** [benoitc/gunicorn#2466]
It seems that gunicorn adds the directory where the `gunicorn` script is (e.g. `<virtualenvironment>/bin/`) to the `PYTHONPATH` even when `--pythonpath` is set. I guess this helps if there is a script (file) one wants to run using gunicorn, but it is not normal python behaviour and caused me some grief (shadowing a PEP420 namespace package), and I have to now manually change the path to remove it.

Is this expected behaviour? Is it helpful? Should it be documented or be configureable?

**Comment by tilgovi** [comment]
I think there is only one place where we add an additional path, and it's the current working directory. I think this was done to make it easy for people to deploy without putting their code in a proper package. That code lives here: https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/base.py#L89

Maybe you can change the current working directory? You can specify `--chdir` for that, too.

**Comment by cryvate** [comment]
You are correct and I should have realized: Python is doing this by default. I could add `-I` to prevent this behaviour, however, as `gunicorn` is a script and it seems `-I` for Python seems like it does not allow setting by environment variable it seems the invocation will have to become `python -I <path_to_gunicorn_script> <gunicorn arguments>` which is a bit verbose, but is better than the hack I put in place before (which was clobbering the path in the WSGI file). Apologies for the noise, maybe it will help somebody in the future...
