### ISSUE TITLE
customize gevent monkey patch

### ISSUE THREAD

**Issue by royling** [benoitc/gunicorn#2468]
When using `gunicorn` with `gevent 20.x` as worker type, now it [monkey-patch everything done by gevent](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/ggevent.py#L38).

In my case, this was preventing from using `select.epoll`/`selectors.EpollSelector` within `asyncio` in my application, because in aggressive mode [`epoll`](https://github.com/gevent/gevent/blob/20.9.0/src/gevent/select.py#L338-L347)/[`EpollSelector`](https://github.com/gevent/gevent/blob/20.9.0/src/gevent/selectors.py#L288-L297) is removed in the monkeypatch.

So, I want to know:

1. Do you think whether it makes sense to customize the monkey patch in `GeventWorker`? e.g. adding an option/env variable to suppress the aggressive mode.

1. any other thoughts for supporting this?

If we can find out an agreement on this, I can submit a PR for it.
Thanks!

**Comment by jamadden** [comment]
Using `asyncio` in that way within a gevent worker is going to prevent the worker from handling any other requests, thus defeating the point of using an asynchronous gevent worker. That seems rather counter productive. Maybe you want to be using an asyncio based worker, or use gevent insted of asyncio.

**Comment by royling** [comment]
@jamadden thanks for the reply.

I am a newbie in python/asyncio, sorry for my naive questions:

> Using asyncio in that way within a gevent worker is going to prevent the worker from handling any other requests

Did you mean that the worker can only handle one request at a time? In the other word, [are other greenlets blocked](http://www.gevent.org/intro.html#cooperative-multitasking) if asyncio is used (e.g. another event loop is created) in one greenlet?

> That seems rather counter productive.

I did see some odd behaviors, like CPU usage was very high, in that way. And, I worked around the issue by switching to use `PollSelector` when creating event loop like below.

```python
selector = selectors.PollSelector()
loop = asyncio.SelectorEventLoop(selector)
asyncio.set_event_loop(loop)
```
However, I did not fully understand why `GeventSelector` caused the problem though. I guess that's the "counter productive" effect you mentioned here. Would you mind explaining more on this?

With the above workaround, I read the source code of gunicorn and gevent and got that `epoll`/`EpollSelector` is removed in gevent monkeypatch. So, I opened this issue and thought to provide a custom option to enable it for use, now it looks like I was on a wrong track.

> Maybe you want to be using an asyncio based worker, or use gevent insted of asyncio.

Thanks for the suggestion and I need to learn more about gunicorn and gevent to find out a right way.
And, I did see an open issue in gevent https://github.com/gevent/gevent/issues/982 that you self-assigned, really look forward to the enhancement in gevent.

**Comment by jamadden** [comment]
> Did you mean that the worker can only handle one request at a time? In the other word, are other greenlets blocked if asyncio is used (e.g. another event loop is created) in one greenlet?

Yes. If anything is making native `select()`, `poll()` or `epoll()` calls (i.e., those that have not been monkey-patched) in the same thread that gevent's hub is running, that will block the hub.

As to whether a monkey-patched `select()` or `poll()` will actually work with asyncio, I have no idea (but that would be two layers of multiplexed IO in user space, which doesn't sound like a great idea). Also, asyncio "tasks" are non-cooperative blocking functions as far as gevent is concerned, just as with any other CPU-bound function that doesn't make monkey-patched IO or other requests.

**Comment by royling** [comment]
Thanks for your explanation.

> As to whether a monkey-patched select() or poll() will actually work with asyncio

I think the workaround worked because the monkey-patched `poll()` can work with asyncio, though it may not be productive as you mentioned.

> asyncio "tasks" are non-cooperative blocking functions as far as gevent is concerned

I'll do some tests to prove this.

Closing this issue, because it may not be a valid use case.
