### ISSUE TITLE
Split logging files 

### ISSUE THREAD

**Issue by awbx** [benoitc/gunicorn#2469]
Please can we split the access.log or error.log as the following example:
access_12_2020.log
access_11_2020.log
error_12_2020.log
error_11_2020.log

**Comment by benoitc** [comment]
It's possible: use logrotate or anything equivalent in systemd ecosystem and send an USR1 signal to reload the log. See this nginx doc for some details: https://www.nginx.com/resources/wiki/start/topics/examples/logrotation/

**Comment by awbx** [comment]
thanks, I found the solution! now, I used Linux logrotate its more practical
