### ISSUE TITLE
Odd behavior when using Pydantic for Settings Management

### ISSUE THREAD

**Issue by devsetgo** [benoitc/gunicorn#2484]
I am using Gunicorn to manage the Uvicorn Workers for FastAPI. I just started using [Pydantic for Settings Management](https://pydantic-docs.helpmanual.io/install/) and found an odd behavior. When starting Gunicorn I get an error on the Pydantic Settings. It works perfectly fine running Uvicorn directly, but I get the below failure when running Gunicorn.

If I remove the gunicorn_cfg.py and just give "gunicorn main:app --workers 2 --bind 0.0.0.0:5000 --worker-class uvicorn.workers.UvicornH11Worker" it runs fine.

~~~
gunicorn -c gunicorn_cfg.py main:app

Invalid value for config: workers=4 loguru_logging_level='DEBUG'
Error: Not a string: workers=4 loguru_logging_level='DEBUG'
~~~

**gunicorn_cfg.py**
```python
# -*- coding: utf-8 -*-
"""
Configuration of Gunicorn to serve application utilizing Uvicorn
gunicorn config reference:
https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py
"""
import multiprocessing
from settings import config

# ip and port to bind
bind = "0.0.0.0:5000"

workers = config.workers

# set worker class to uvicorn
worker_class = "uvicorn.workers.UvicornH11Worker"

# loglevel - the granularity of log output
# a string of "debug", "info", "warning", "error", "critical"
loglevel = str(config.loguru_logging_level.lower())
```

**settings.py** 

```python

from pydantic import BaseSettings,AnyUrl



class Settings(BaseSettings):
    workers: int = 2
    loguru_logging_level: str = "DEBUG"

'''

**Comment by LucasRxTx** [comment]
I had the same issue.  Turns out if you have an object called `config` in the `gunicorn_conf.py` it shadows something in gunicorn when it reads the file.  Aliasing my import of `config` solved my issue.

```python
# gunicorn_config.py
from settings import config as conf

workers = conf.workers
```

**Comment by devsetgo** [comment]
@LucasRxTx That was it... Thank you.
