### ISSUE TITLE
Orphan Processes Systemd

### ISSUE THREAD

**Issue by monteksingh** [benoitc/gunicorn#2485]
I have deployed an application using Systemd. 
The Application starts many other processes [1] during its execution.
When a worker gets terminated due to timeout, these other processes [1] do not terminate.
This leads to OOM errors when this cycle repeats.
Is there any way to kill all these child processes [1] when the worker is terminated due to timeout?
Pls help....

**Comment by monteksingh** [comment]
**UPDATE**
SHOULD I BE USING SUPERVISORD
https://thomas.skowron.eu/blog/supervisor-orphaned-processes/

**Comment by benoitc** [comment]
look at the documentation to use gunicorn with systemd: https://docs.gunicorn.org/en/stable/deploy.html#systemd

**Comment by monteksingh** [comment]
I think my question was not clear.
Gunicorn is not killing all the sub-processes running under it when the 'worker' crashes and restarts. How should I fix it?
