### ISSUE TITLE
Try to find a parameter to return a request when timeout

### ISSUE THREAD

**Issue by NewLanded** [benoitc/gunicorn#2486]
Hello everyone
  I try to find a parameter to return a request when the request is timeout. it's like I only can stand 10s for one request, so if a 
 request call function like this which will take 60s, then I except gunicorn return this request and tell me the request is timeout. 
Is there a parameter or someting can do this?
```python
@app.post()
def simple_request():
    time.sleep(60)
``` 

I tried --timeout parameter but it is not work as I excepted.  

I am hoping for any suggetion, thanks.

**Comment by benoitc** [comment]
what is not working as expected?

**Comment by benoitc** [comment]
what is not working as expected?
