### ISSUE TITLE
limit-request-line errors are not logged 

### ISSUE THREAD

**Issue by sergeypeloton** [benoitc/gunicorn#2491]
For example when url is too long, gunicorn will respond with 400 and a [short html](https://github.com/benoitc/gunicorn/blob/master/gunicorn/util.py#L302), but access or error logs [are not written](https://github.com/benoitc/gunicorn/blob/86eac4ce94630c1fb4df7b7451bb8c9a7cb6b93b/gunicorn/workers/base.py#L256).
This makes it harder to diagnose an issue when all you have is server side metrics/logs.

There are [debug logs](https://github.com/benoitc/gunicorn/blob/86eac4ce94630c1fb4df7b7451bb8c9a7cb6b93b/gunicorn/workers/base.py#L248) but debug level is too noisy to enable in production.

Does it make sense to add access/error/exception logging to `handle_error` for this class of issues?

**Comment by benoitc** [comment]
maybe a warning without the exception?

**Comment by sergeypeloton** [comment]
Yeah that would work.
