### ISSUE TITLE
Question on debugging keepalive issue.

### ISSUE THREAD

**Issue by dmccracken** [benoitc/gunicorn#2498]
I have a Flask app running on top of gunicorn which works fine on centos8 and rhel8. I'm trying to bring the app up on an rhel8 derivative which is hardened for FIPS compliance. This new os constantly sees workers timing out and no REST messages are logged using --log-level debug. 

I've studied the code and see that you use a notify mechanism which relies on updating the permissions on temporary files. I've been looking around for these files but can't seem to find them. I've looked in /tmp (which I believe to be the default) and even set --worker-tmp-dir /tmp/gunicorn with no luck. Both are empty.

Any advice on how to proceed here will be appreciated.

[root@host-172-23-14-219 ~]# ls -ltr /tmp/gunicorn/
total 0
[root@host-172-23-14-219 ~]# ls -latr /tmp/gunicorn/
total 0

[2021-01-15 16:33:21 +0300] [9120] [CRITICAL] WORKER TIMEOUT (pid:14483)
[2021-01-15 16:33:21 +0300] [9120] [CRITICAL] WORKER TIMEOUT (pid:14485)
[2021-01-15 16:33:21 +0300] [9120] [CRITICAL] WORKER TIMEOUT (pid:14488)
[2021-01-15 16:33:21 +0300] [14483] [INFO] Worker exiting (pid: 14483)
[2021-01-15 16:33:21 +0300] [14485] [INFO] Worker exiting (pid: 14485)
[2021-01-15 16:33:21 +0300] [14488] [INFO] Worker exiting (pid: 14488)
[2021-01-15 16:33:21 +0300] [14782] [INFO] Booting worker with pid: 14782
[2021-01-15 16:33:21 +0300] [9120] [DEBUG] 1 workers
[2021-01-15 16:33:21 +0300] [14783] [INFO] Booting worker with pid: 14783
[2021-01-15 16:33:21 +0300] [14785] [INFO] Booting worker with pid: 14785
[2021-01-15 16:33:21 +0300] [9120] [DEBUG] 3 workers

**Comment by dmccracken** [comment]
Discovered that keepalives are not working because each worker process is hung when calling load_wsgi(). This is where the Flask framework gets loaded. Specifically, gunicorn hangs when calling importlib.import_module() to pullin our flask app. Any ideas why this would be happening?

**Comment by benoitc** [comment]
Are you using an asyncrhonous worker or the option `--threads`? They are needed to handle keepalive connections.

**Comment by dmccracken** [comment]
No, I'm using the basic sync worker.

I've been putting debug statements into the code and have traced it to the importlib.import_module() statement in util.py. This is where the worker process is hanging. Though I have no idea why.

```
Running base::init_process()
base::init_process() set_owner_process()
base::init_process() waking ourselves up
base::init_process() preventing fd inheritance
base::init_process() init_signals()
base::init_process() load_wsgi()
util.py:import_app()
util.py:import_app() calling importlib.import_module()
```

**Comment by jamadden** [comment]
Can you post a full traceback of a hung process? (Using a tool like [py-spy](https://pypi.org/project/py-spy/): `py-spy dump --pid PID --native`.)

**Comment by benoitc** [comment]
keepalive doesn't work and is not supported with the "sync" worker. You have to use an async worker or enable threads `--threads`to handle keepalive.

**Comment by dmccracken** [comment]
The problem can be seen using the python interpreter. The interpreter command prompt never returns.
```
[root@dbaas1 restapi]# python3
Python 3.6.8 (default, Aug 18 2020, 08:33:21) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import __init__
```

**Comment by benoitc** [comment]
@dmccracken again the sync worker can't handle keepalive connections. It will close the connection once the request is answered. You should see if using the `--threads` option is performing enough for your usage or use another async worker if needed.

**Comment by jamadden** [comment]
One doesn't normally `import __init__`; `__init__` is a special module used to make a directory a package. So if there is `directory/__init__.py`, one would just `import directory`.

What are the contents of your `__init__.py`? Is it doing something at import time that it shouldn't be?

**Comment by benoitc** [comment]
> No, I'm using the basic sync worker.
> 
> I've been putting debug statements into the code and have traced it to the importlib.import_module() statement in util.py. This is where the worker process is hanging. Though I have no idea why.
> 
> ```
> Running base::init_process()
> base::init_process() set_owner_process()
> base::init_process() waking ourselves up
> base::init_process() preventing fd inheritance
> base::init_process() init_signals()
> base::init_process() load_wsgi()
> util.py:import_app()
> util.py:import_app() calling importlib.import_module()
> ```

do you have any simple example that help to reproduce this behaviour? It looks like a race condition

**Comment by dmccracken** [comment]
Sorry for the noise here. The problem turned out to be in the Flask application startup. I had put code in to try and determine if the network interfaces were up before allowing the flask app to launch. The network interface I was waiting on does not exist in this new environment. Thank you for your support.
