### ISSUE TITLE
Deploy Gunicorn behind Nginx docs 

### ISSUE THREAD

**Issue by 0leg53** [benoitc/gunicorn#2500]
Hi, after reading [this article](https://docs.gunicorn.org/en/stable/deploy.html), I'm assuming that the use of the Nginx `$scheme` variable is incorrect because of the value was incorrect (HTTP instead of HTTPS), so I preferred to use `$http_x_forwarded_proto` in the line
```
proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
```

Am I right to do this and is it worth changing this point in the documentation?
_______
Also, my stack is `traefik -> Nginx -> gunicorn` and traefik has SSL, not Nginx.

**Comment by tilgovi** [comment]
For your case this is correct if Traefik sets this header.

In general, you want your edge proxy to ignore or clear this header, and set it to the correct value for the upstream connections. In this way, a client cannot lie about the protocol.
