### ISSUE TITLE
Is there a  way for a worker signal "ready to accept requests" after boot?

### ISSUE THREAD

**Issue by kebabhans** [benoitc/gunicorn#2502]
1) This is a question, maybe a "request for a feature", rather than a bug report. 
2) Thanks for maintaining this! :) You people are awesome! 

I'm reaching out to you, since I failed to get any answers [to my question on stackoverflow](https://stackoverflow.com/questions/65772953/how-to-signal-ready-to-accept-requests-to-gunicorn-in-django-application)

I have 5 Gunicorn workers in my setup, configured with `max-requests` to 1000, and `max-requests-jitter` to 50. After a worker A is replaced by a worker B, then B's handling of the first request sent to B is "superslow" (seconds vs. otherwise in the tens of miliseconds). Profiling will show me that it is most likely (I haven't confirmed yet) due to the worker being busy loading the application (a Django application, with a Redis, a Postgres database, a mail-service, celery-workers etc.). 

While I do realize I have something to do about the app loading time (if possible), any application will in general always need _some_ time to start, incurring a "penalty" in the request-response time. 
Hence, my question is: Is there a way for a worker to signal to master: "I'm ready now to accept accept requests"?
If not, do you know how other handle this type of problem?

**Comment by tilgovi** [comment]
The arbiter process does not select workers, the workers accept connections when they're ready and the OS distributes the connections among the workers that are accepting.

The first thing that workers do after forking from the main process is to call the `post_fork` hook and then to import the application code (the module specified on the command line). You should try to ensure that your worker is ready by the time the code has imported. Some frameworks deliberately lazy load some things on the first request. You also might find that your code or the framework or a middleware has caches that need to warm up. You'll have to profile this yourself to figure out what is going on.

**Comment by kebabhans** [comment]
Thank you for explaining me! I'll look into what I can do, specifically if I have lazy-loaded code and if so, if there's something I can do about it. Thank you again :)
