### ISSUE TITLE
Bind workers and gpus

### ISSUE THREAD

**Issue by vignesh34v** [benoitc/gunicorn#2506]
I am trying to bind workers with separate GPUs. Deployed the same by modifying ```arbiter.py```. 

Can we add as feature enhancement? 

_Originally posted by @vignesh34v in https://github.com/benoitc/gunicorn/issues/1434#issuecomment-770765947_

**Comment by tilgovi** [comment]
I commented on your PR. Feel free to post back here if you are unable to use the Server Hooks to achieve what you want.
