### ISSUE TITLE
Gunicorn auto restarting while ThreadPoolExecutor is still running?

### ISSUE THREAD

**Issue by 777GE90** [benoitc/gunicorn#2510]
Hello, I am currently using Gunicorn to front a Flask restful based app.  All is working great and I am taking advantage of the `max-requests` parameter to avoid long term / slow memory leaks.

However, I have a problem.  Some of my Flask restful endpoints will spawn a background job using a ThreadPoolExecutor and then immediately return a response, while that background job is still running.  The advantage of this is that the user doesn't have to wait for the background job and gets a near immediate response form the endpoint, they get given an ID of the transaction so they can track the status later on.

This all works great, but when Gunicorn triggers an auto restart, it assumes it is safe to restart the moment my flask resteful app returns a HTTP JSON response to the endpoint, when in actual fact the worker is still running a ThreadPoolExecutor in the background, gunicorn then terminate the worker and the ThreadPoolExecutor gets cut off mid way through it's request.

So my question is, how do I get around this? Is there a way to make sure that Gunicorn does not auto restart until my ThreadPoolExecutor completes?

I normally run gunicorn like this, I have set max-requests to 1 because that will immediately trigger this error if you wanted to reproduce:
```
gunicorn server:app \
 --bind 0.0.0.0:5000 \
 --timeout 120 \
 --max-requests 1 \
 --workers 2 \
 --worker-class gthread
```

**Comment by tilgovi** [comment]
Gunicorn cannot track anything else your worker is doing. You could make a custom worker type that tries to do something different with the shutdown signals, but the typical way to solve this would be to use a separate set of task workers and a work queue like Celery to get tasks off the Gunicorn workers and onto background job processes.
