### ISSUE TITLE
Gunicorn duplicates file upload request

### ISSUE THREAD

**Issue by keremnymn** [benoitc/gunicorn#2512]
Hello,
I'm using Flask + Gunicorn on  localhost. I have this endpoint at which I accept multiple files:
```
@foo.route('/foo/bar/', methods=['GET', 'POST'])
@login_required
def foo():
    ##other lines
    if form.validate_on_submit():
        for picture in form.pictures.data:
            filename = secure_filename(picture.filename.lower())
            fn, ext = os.path.splitext(filename)
            if ext not in dosya_turleri:
                for imgfile in os.listdir(path):
                    os.remove(os.path.join(path, imgfile))
                    flash('Supported extensions: JPG, PNG, BMP, PDF.', 'danger')
                    return redirect(url_for("foo.bar"))
            else:
                save_img(picture)
    ##other lines
```

```
def save_img(picture):
    ##other lines
    picture_full = picture_path + '.png'
    picture = Image.open(picture)
    picture = picture.resize([2400, 3000], Image.LANCZOS)
    picture.save(picture_full, 'PNG',optimize=True, quality=100)
```

It works without a flaw on Werkzeug. It even works when I set Gunicorn like this:
`gunicorn --workers=3 run:app --timeout 200 --log-file -`

But when I set Gunicorn more than 3 workers, Gunicorn saves all the images that the endpoints receives again. For example when I upload 10 images, it uploads the same images again. And stop answering.

Where am I doing the mistake? I just don't understand. If anybody could help me I'd be happy.

**Comment by benoitc** [comment]
gunicorn is stateless. Thtat seems an issue either from the app or the client requesting the api. closing it anyway since that issue was opened a long time ago.
