### ISSUE TITLE
Failure when running in Docker-in-Docker setup

### ISSUE THREAD

**Issue by suncowiam** [benoitc/gunicorn#2517]
Getting the following exception when only running a Docker-in-Docker environment used for GitLab CI.

# docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Recreating flock ... done
Attaching to flock
flock  | Traceback (most recent call last):
flock  |   File "/usr/local/bin/gunicorn", line 8, in <module>
flock  |     sys.exit(run())
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
flock  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 223, in run
flock  |     super(Application, self).run()
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
flock  |     Arbiter(self).run()
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 60, in __init__
flock  |     self.setup(app)
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 120, in setup
flock  |     self.app.wsgi()
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
flock  |     self.callable = self.load()
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
flock  |     return self.load_wsgiapp()
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
flock  |     return util.import_app(self.app_uri)
flock  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
flock  |     __import__(module)
flock  | ModuleNotFoundError: No module named 'app'

**Comment by tilgovi** [comment]
Gunicorn cannot import your app. Check the `PYTHONPATH` and the current working directory when CI executes Gunicorn for you. Perhaps check your Dockerfile to ensure that it is correct and works outside of Docker-in-Docker and outside of CI. Check that the container image gets built with the files you expect copied into it.
