### ISSUE TITLE
Gunicorn unresponsive ~24h after server start with LightGBM

### ISSUE THREAD

**Issue by lucy-collins** [benoitc/gunicorn#2520]
I have a Python app which uses a LightGBM model. Initially I had problems running this on a Gunicorn server, due to the app hanging at the 'predict' function. Although there is no explicit multiprocessing in the app, it seems that the issue was somehow related to multiprocessing threads within the model. I stumbled across a solution to set worker-class=gthread, and this allowed the app to run. However, since deploying, the API seems to freeze and stop accepting traffic approximately 24h after the server was started. This does not seem to be related to hanging requests, since there were no incoming requests within the time that the issue started. There are no Gunicorn logs around this time. 

Could this be related to the issue I was having with Gunicorn/LightGBM incompatibilities?

I am using Gunicorn version 20.0.4 with 2 workers, running on a Kubernetes cluster. The Kubernetes pod continues to be in a running state after the API is unresponsive, unless action is taken.

**Comment by benoitc** [comment]
incompatbility I don't know; It's probably blocking the worker to notiy the arbiter by detaching it (forking?). Maybe there is a way to wortk around?
