### ISSUE TITLE
can not share the tensort engine by --preload

### ISSUE THREAD

**Issue by githublsk** [benoitc/gunicorn#2521]
Hi, @tilgovi @benoitc 
My Envrionment:
CUDA Version: 11.1
CUDNN Version: 8.0.4
Operating System + Version: ubuntu18.04
Python Version: 3.6.10
PyTorch Version: 1.7.0
gunicorn command:
<img width="889" alt="command" src="https://user-images.githubusercontent.com/77612906/108591043-9b750b00-73a1-11eb-827c-3a3be8fb0225.png">
Below is the test code:
<img width="423" alt="code" src="https://user-images.githubusercontent.com/77612906/108591055-a465dc80-73a1-11eb-9779-4b966d111598.png">
Test result:
<img width="893" alt="result" src="https://user-images.githubusercontent.com/77612906/108591072-b2b3f880-73a1-11eb-811d-1986b47015dc.png">

From the result ,  the context can not creat by the share model ENGINE, the reason is may be that the ENGINE in main process can not share by sub process? can you give me some suggestion?

**Comment by tilgovi** [comment]
Does it work without --preload?

**Comment by githublsk** [comment]
> Does it work without --preload? @tilgovi Yes, it dose,  it seems that the ENGINE can not share by sub process when using in --preload, can you give me some ideas?  Because the ENGINE is so lager that our gpu resource is limited, so we want to share the ENGINE by sub process, Thans in advance!

**Comment by tilgovi** [comment]
I cannot give you any advice here. You will have to do some research about PyTorch and CUDA and cannot tell you whether it's possible to do what you want. You may want to move the execution into a separate process using a task queue and process it with a single instance of the engine in another application, outside your Gunicorn workers.

**Comment by benoitc** [comment]
i would suggest to launch the engine as  a separate process and discuss it to it over a pipe. You can also eventually launch it per worker (untested) and ensure the context is cleaned at the end of the task... The doc is quite sparse about it.
