### ISSUE TITLE
Question: catching OOM error that terminate workers

### ISSUE THREAD

**Issue by tigrankh** [benoitc/gunicorn#2522]
Hi,

I'm having an issue and was wondering if you could help me out.
So, one of the tasks I run exceeds the allocated RAM usage and OS errors out with out of memory error. 
In the service logs I see that gunicorn worker restarted. There's no message about failure, just one for a worker that starts.

There is no access to node-level logs/errors so I never see OOM errors on my cloud platform, so it becomes just a matter of guessing, that "maybe its a memory error", then trying to replicate on a local container and actually see the error.

My goal is to detect/record that the OS error happened and ideally be able to tell which exact error happened.

My assumption is that I could achieve that by detecting errors by Gunicorn master process.
In the Gunicorn docs I see the server hooks, and I think maybe I could you use child_exit or worker_exit for my goal.
Could you advice if by using server hooks I can catch OS/OOM errors? If not, what other ways I could possibly utilize to achieve that?

There's not much documentation on server hooks, so if you could give some example on what info I can extract from server and worker arguments of child_exit and worker_exit, that would be really helpful?

Thanks for the great project!

Thanks,
Tigran

**Comment by sonthonaxrk** [comment]
This was merged recently

https://github.com/benoitc/gunicorn/pull/2475

Which should log your OMM messages.  This was difficult because SIGKILL is sent to the offending worker, and SIGKILLs can't really be handled.

---

In my personal experience, Gunicorn need to define some best practices for being deployed in K8.  Multiprocess deployments, don't really mesh well with K8.  Typically, when I deploy a Gunicorn application I do away with the multiprocess facets, and let K8 do the things the arbiter class would normally do.

This is the code snippet that I use to run gunicorn in K8. 

```
import os

from gunicorn import sock
from gunicorn.app.wsgiapp import WSGIApplication


class NonArbiterGunicron(WSGIApplication):

    def __init__(self):
        super().__init__()
        self.logger = self.cfg.logger_class(self.cfg)

    def run(self):
        sockets = sock.create_sockets(self.cfg, self.logger)
        worker = self.cfg.worker_class(
            # Not relevant - gunicorn has an option to kill old workers
            age=None,
            # Slight hack, gunicorn checks if it's parent is alive - we
            # that's never not going to happen.
            ppid=os.getppid(),
            # The important part
            sockets=sockets,
            # This doesn't matter because it's K8 that kills
            # unresponsive workers
            timeout=None,
            # How our options are passed
            cfg=self.cfg,
            log=self.logger,
            app=self
        )

        worker.init_process()
        worker.run()


if __name__ == '__main__':
    NonArbiterGunicron().run()
```
