### ISSUE TITLE
Question: Implementing TLS Security

### ISSUE THREAD

**Issue by rns350** [benoitc/gunicorn#2523]
Hi everyone! I'm currently building a microservice that leverages Gunicorn and which is using the TLS protocol to manage security.  I have the app running and it works great, but I am unsure based on the documentation how to properly implement the security.

I have the app configured properly using --ca-certs, --certfile, and --keyfile.  My browser prompts me to put in a password for the cert before routing me to the site as I have required.  I have questions surrounding a couple of other arguments for the app.  

Firstly, what is the difference between --cert-reqs 1 and 2.  From what I can tell, 1 signifies optional required certificate (and I am not clear on the implications of this), while 2 signifies that a client certificate is required.  Is this the correct assumption, and should I essentially just set it to 2?

Secondly, I am new to security and it has been quite the rabbit hole.  I have read and heard that I should perform a common name validation between the server's cert and the client's cert to ensure that they have the same server name.  Is this depricated from SSL, or is it something I should be doing to secure my app.  If it is, does Gunicorn take care of that, or do I need to intercept with a custom Worker to perform the validation?

Thankyou so much for your help! I am still new to security, and considering how important it is, I want to get it right.  I apologize if any of my terminology/ assumptions are wrong.

**Comment by benoitc** [comment]
stalled
