### ISSUE TITLE
Allow setting worker threads via environment variable

### ISSUE THREAD

**Issue by mriedem** [benoitc/gunicorn#2527]
This is a feature request. It'd be really nice to be able to set the worker threads value [1] using an environment variable like you can for the workers value using `WEB_CONCURRENCY` [2]. The reason being we're deploying an application into different Kubernetes clusters using Helm and it's nice to be able to configure the application (workers and threads) per cluster using environment variables in the Deployment template of the helm chart and keep that deployment/cluster-specific information out of the Dockerfile.

[1] https://github.com/benoitc/gunicorn/blob/20.1.0/gunicorn/config.py#L695
[2] https://github.com/benoitc/gunicorn/blob/20.1.0/gunicorn/config.py#L640

**Comment by jpmckinney** [comment]
Use GUNICORN_CMD_ARGS https://docs.gunicorn.org/en/stable/settings.html

**Comment by benoitc** [comment]
that's the right answer :) thanks
