### ISSUE TITLE
Child processes respawning when idle on Ubuntu 20.04

### ISSUE THREAD

**Issue by drcongo** [benoitc/gunicorn#2534]
Hello. We have a bunch of servers running various versions of Ubuntu, but we recently noticed that the servers running 20.04 have very high PID values - watching what's going on in `htop` I can see the Gunicorn child processes respawning and getting a new PID every 10 seconds or so, even on a freshly brought up server that's not connected to Nginx / Caddy so Gunicorn isn't actually having to do anything at all. The servers are all running different Django apps, nothing is showing up in the Gunicorn error log or the supervisor logs. Is this something I should worry about? Is it normal? Does anyone have any ideas on how I can track down what's causing it? We're on the latest Gunicorn, but so are the servers where this isn't happening.

**Comment by drcongo** [comment]
To clarify, I think it's _threads_ that are respawning (the green ones in htop). The entire gunicorn config is...

```
bind = '127.0.0.1:8000'
backlog = 2048

workers = 9
worker_class = 'gthread'  # same issue with `sync`
worker_connections = 1000
timeout = 30
keepalive = 2
preload = True

spew = False
daemon = False
umask = 0
user = "deploy"
group = "deploy"
tmp_upload_dir = "/tmp"

errorlog = "/var/log/gunicorn/gunicorn-error.log"
accesslog = "/var/log/gunicorn/gunicorn-access.log"
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
```

**Comment by benoitc** [comment]
application issue?
