### ISSUE TITLE
Reload gunicorn on certificate change

### ISSUE THREAD

**Issue by MohamedAmineOuali** [benoitc/gunicorn#2536]
Hello,

Thank you for this great project.

I am using Gunicon for production.

I was wondering if I should use `reload_extra_files` on production and listen for a certificate file change in order to reload the Gunicorn. Or should I use the HUP signal?

If a HUP signal is the way to go how can I **easily** send a signal to the "gunicron" (automatically) without searching for its PID.  

I think the best option for me is to have a scheduled task in my app that renews the certificate and then reloads gunicorn. Not sure if this will create a problem if I have multiple workers.

 I am using gunicorn, uvicorn , fastapi.

Note I am using a self-signed certificate for mtls so I don't want to use a reverse proxy. 

Thank you very much.

**Comment by benoitc** [comment]
I would do it explicitely by running HUP when needed. This would be maybe more efficient. But this is up to you :)
