### ISSUE TITLE
CRITICAL WORKER TIMEOUT using generator function in Flask to stream video

### ISSUE THREAD

**Issue by tylersweat** [benoitc/gunicorn#2537]
I have a setup to stream video from a webcam to a web interface. It works great for 30 seconds and then we get the worker timeout. Gunicorn is started with the following command.
```
gunicorn3 --bind 0.0.0.0:5001 wsgi_cameras:app
```
To confirm that it is Gunicorn timing out the worker and killing it, we started it with this command:
```
gunicorn3 --bind 0.0.0.0:5001 --timeout 42 wsgi_cameras:app
```
When running with this command, it times out the worker at exactly 42 seconds. 

```
def rear_frames():
    while True:
        success, frame = rear.read()
        if not success:
            error_msg = cv2.imread(CAMERA_FAILED_IMG, cv2.IMREAD_UNCHANGED)
            ret, buffer = cv2.imencode('.jpg', error_msg)
            data = buffer.tobytes()
            yield (b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + data + b'\r\n')
            break
        else:
            # Resize to standard width and height.
            frame = cv2.resize(frame, (FRAME_WIDTH, FRAME_HEIGHT))
            # Convert data to bytes and yield result.
            ret, buffer = cv2.imencode('.jpg', frame)
            data = buffer.tobytes()
            yield (b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + data + b'\r\n')

@app.route('/rear_feed')
def rear_feed():
    return Response(rear_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')
```

```rear_frames()``` is defined as a generator sending the multipart image to stream the video. The worker stays alive the whole time as evidenced by the successful video stream. However, it seems like the worker doesn't let the master know that it is still alive. 

One workaround we've thought of is setting the timeout very high but we would like to have it restart quickly in the event that the worker dies while also not having it get killed when it still is running correctly.

What solutions could there be?

Edit: In reading the documentation, it sounded like if I simply printed from the worker then it would avoid the timeout. I tried that and it still killed it after reaching the timeout. Also worth noting that the time doesn't start until I load up the page and select the camera to start streaming meaning that it is getting hung up in the generator function.

**Comment by phwolf** [comment]
Ran into the same problem. Any news on this?

**Comment by tylersweat** [comment]
Nothing. My workaround was to set the timeout to an insanely long time. It wasn't a big deal if the video stream crashed occasionally and in my application, all you had to do was switch to another feed then back and it was reset.
