### ISSUE TITLE
Gunicorn 20.0.4 is incompatible with greenlet 1.0

### ISSUE THREAD

**Issue by bburtin** [benoitc/gunicorn#2541]
A `pip install` of SQLAlchemy 1.4 causes greenlet 1.0 to be installed.  As a result, we started getting the error below during Gunicorn startup.  We were able to avoid the problem in the short term by pinning SQLAlchemy to 1.3.x.  It would be good if Gunicorn supported later versions of greenlet.  This will allow us to upgrade SQLAlchemy in the future.

```
Error: class uri 'egg:meinheld#gunicorn_worker' invalid or not found: [Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 72, in load_class
    return pkg_resources.load_entry_point(dist, section, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (greenlet 1.0.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('greenlet<0.5,>=0.4.5'))
```

**Comment by jamadden** [comment]
This isn't coming from gunicorn (gunicorn has no version pin for greenlet). It appears to be coming from the [meinheld project](https://github.com/mopemope/meinheld/blob/master/setup.py#L77); I suggest you open an issue there. Good luck!

There are no API or ABI differences from the previous release of greenlet to 1.0, so they should have no problem bumping their version pin to `<2.0`. (Prior to greenlet 1.0 there were no semantic meanings attached to greenlet versions — API and ABI regularly changed from 0.4.x to 0.4.x+1, so their current pin doesn't make much sense anyway.)

**Comment by bburtin** [comment]
Oops, thanks for responding quickly slapping me around.  You're right, I misread the traceback.  I'll file a bug with meinheld.

**Comment by jamadden** [comment]
cf https://github.com/mopemope/meinheld/issues/122
