### ISSUE TITLE
limit_request_line bigger than 8190

### ISSUE THREAD

**Issue by adamlofts** [benoitc/gunicorn#2546]
https://docs.gunicorn.org/en/stable/settings.html#limit-request-line

I would like to increase the max request line length because my app stores some state in the url. 

e.g. chrome allows a 2MB URL https://chromium.googlesource.com/chromium/src/+/master/docs/security/url_display_guidelines/url_display_guidelines.md#:~:text=Chrome%20limits%20URLs%20to%20a,is%20used%20on%20VR%20platforms.

I don't want to set it to unlimited because of the risk it poses to reliability.

**Comment by benoitc** [comment]
Welll this is why you have this setting :) I don't think it's a good idea anyway as it open the doors to DOS.
