### ISSUE TITLE
asyncio synchronization primitives

### ISSUE THREAD

**Issue by kosciej16** [benoitc/gunicorn#2553]
Hi, I have quick question.

I use gunicorn with uvicorn.workers.UvicornWorker and would like to protect some resources from shared access.

Could I use asyncio.Lock for that? The documentation said it's not thread-safe, but how is it related to gunicorn workers?
My understanding is one such worker is like one thread, so with --workers 1 asyncio.Lock will work, but in other case not. Am I right?

**Comment by elingsoft** [comment]
so，i am

**Comment by benoitc** [comment]
you should ask directly in the uvicorn project :)
