### ISSUE TITLE
Wheel not published for gunicorn 20.1.0

### ISSUE THREAD

**Issue by edmorley** [benoitc/gunicorn#2556]
Hi!

gunicorn 20.1.0 currently only has an sdist available:
https://pypi.org/project/gunicorn/20.1.0/#files

In comparison, gunicorn 20.0.4 had both an sdist and a wheel:
https://pypi.org/project/gunicorn/20.0.4/#files

The lack of a wheel means pip has to spend time creating one during install, eg:

```
       Building wheels for collected packages: gunicorn, ...
         Building wheel for gunicorn (setup.py): started
         Building wheel for gunicorn (setup.py): finished with status 'done'
         Created wheel for gunicorn: filename=gunicorn-20.1.0-py3-none-any.whl size=78918 sha256=31cf6259d9f936d5565df167c93a9901bdd93d7daaf7ef915631f720750126bf
         Stored in directory: /tmp/pip-ephem-wheel-cache-orcrzfks/wheels/ee/ca/72/3e9be4033d3993d4d78e2f4accdfcfff6c690921fef5ea0d57
```

Would it be possible to publish the wheel for 20.1.0 and also future releases?

Many thanks :-)

**Comment by johnthagen** [comment]
This would be great, the advantages of wheels are detailed here: https://pythonwheels.com/

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

**Comment by johnthagen** [comment]
Pinging @benoitc. Given the popularity of `gunicorn`, there are a lot of CI pipelines that would be made a little more efficient if a wheel was published rather than each pipeline needing to rebuild it every time from sdist.

**Comment by benoitc** [comment]
done.

@johnthagen thanks for the reminder!
