### ISSUE TITLE
Where are the release notes for 20.1.0 version?

### ISSUE THREAD

**Issue by LorhanSohaky** [benoitc/gunicorn#2560]

**Comment by johnthagen** [comment]
Changelog is here: https://docs.gunicorn.org/en/stable/news.html#id1

It looks like the version was tagged in Git, but wasn't a full "GitHub" release so it doesn't show up as a release: https://github.com/benoitc/gunicorn/releases

I wonder if that can be fixed retroactively. GitHub currently shows the last "release" as 20.0.4.

**Comment by LorhanSohaky** [comment]
Ah okay! I had run `pip list -o` and the` v20.1.0` version appeared, when I looked at the release notes on github there was nothing
