### ISSUE TITLE
Not able to host a dash application on Gunicorn

### ISSUE THREAD

**Issue by kkkarthik** [benoitc/gunicorn#2561]
I want to deploy a dash application on Gunicorn. But I am not able to do so. I see no errors appearing on the screen when I execute the `gunicorn <module_name>:<variable_name>`

Versions:
```
gunicorn (20.0.4)
dash (1.17.0)
dash-core-components (1.13.0)
dash-html-components (1.1.1)
dash-renderer (1.8.3)
dash-table (4.11.0)
```

my dash application, file name: analyzer.py

```
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import pandas as pd
import flask

<data_frame definitions>


app = dash.Dash()
server = app.server

<app.layout>

<Call backs>

## at the end

if __name__ == '__main__':
    app.run_server()
```

When I use the below command, I see no errors on the screen, but yet I can’t reach the application from the browser.

```
[user1@myHost]$ gunicorn analyzer:server -b:8000

[2021-04-16 16:57:58 +0200] [8334] [INFO] Starting gunicorn 20.0.4
[2021-04-16 16:57:58 +0200] [8334] [INFO] Listening at: http://0.0.0.0:8000 (8334)
[2021-04-16 16:57:58 +0200] [8334] [INFO] Using worker: sync
[2021-04-16 16:57:58 +0200] [8345] [INFO] Booting worker with pid: 8345
```

I see that the port is listening, however, I am not able to open my dashboard on the server’s public IP and 0.0.0.0
The port 8000 is in listen mode

```
sudo lsof -i -P -n | grep LISTEN

gunicorn  13003     user1    5u  IPv4 49878669      0t0  TCP *:8000 (LISTEN)
gunicorn  13015     user1    5u  IPv4 49878669      0t0  TCP *:8000 (LISTEN)
```

Could you please tell me where I am going wrong. Kindly forgive me if I have made any fundamental mistake. I would really appreciate if you could guide me and show a path towards resolution.

Thanks and Regards
Karthik

**Comment by bw984** [comment]
I have never tried to run Dash directly on gunicorn so I apologize in advance.  I do however maintain a large Flask application running on gunicorn that happens to have Dash endpoints.  If you are unable to find a way to run Dash directly I'd suggest setting up the app as a Flask app first, get gunicorn configured and working, and then register your Dash app as an endpoint during the Flask "create_app()" phase of the application factory pattern. I can provide more details if you decide to try this route.

Callbacks when running a multiple worker gunicorn server are interesting.  Be prepared to use something like redis for session management if you have authentication checks in your codebase.

**Comment by kkkarthik** [comment]
> I have never tried to run Dash directly on gunicorn so I apologize in advance. I do however maintain a large Flask application running on gunicorn that happens to have Dash endpoints. If you are unable to find a way to run Dash directly I'd suggest setting up the app as a Flask app first, get gunicorn configured and working, and then register your Dash app as an endpoint during the Flask "create_app()" phase of the application factory pattern. I can provide more details if you decide to try this route.
> 
> Callbacks when running a multiple worker gunicorn server are interesting. Be prepared to use something like redis for session management if you have authentication checks in your codebase.

Hello 
Thanks for responding. I would love to explore this route to overcome my roadblock. Eagerly waiting for your guidance.

**Comment by bw984** [comment]
Here is a link to a template project I've setup for demonstrating how to host multiple Dash apps on a single outer Flask application.  [https://github.com/bw984/Flask-Dash-App-Factory-Template](url).  If you point gunicorn to the main app in app.py you should be good to go.  If you are launching gunicorn with multiple workers you should see multiple print statements with each worker's PID when booting the app.  The template shows dash as embedded elements in jinja templates as well as fully organic page layouts which is my preferred method when building off this pattern.   Let me know if you have any issues or questions.

**Comment by benoitc** [comment]
Dash? This https://dash.plotly.com ? Can you share the debug log? What does mean "can’t reach the application from the browser." ?

**Comment by kkkarthik** [comment]
> Dash? This https://dash.plotly.com ? Can you share the debug log? What does mean "can’t reach the application from the browser." ?

Hello @benoitc ,
Yes, I am referring to the same Dash that you have mentioned. What I mean by "cant reach the application from the browser" is that, my code works on local setup. Next, I wanted to deploy on Linux machine. While there are no errors on the terminal when I execute `gunicorn analyzer:server -b <public IP of server> :8000` , my dashboard does not open on the browser. "This site can’t be reached" appears on the browser. 

Also, the port is in LISTEN state. Verified in `netstat` output.
`[user1@~]$ netstat -an | grep -i 8000`
`tcp        0      0 10.61.216.128:8000      0.0.0.0:*               LISTEN`



Debug logs:

`[user1@host]$ gunicorn analyzer:server -b 10.61.216.128:8000 --log-level debug`

[2021-04-19 16:37:05 +0200] [11499] [DEBUG] Current configuration:
  config: None
  bind: ['10.61.216.128:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/user1/automation/MyDataViz/MyPoC
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1002
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: analyzer:server
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7ff0504a80d0>
  on_reload: <function OnReload.on_reload at 0x7ff0504a81e0>
  when_ready: <function WhenReady.when_ready at 0x7ff0504a82f0>
  pre_fork: <function Prefork.pre_fork at 0x7ff0504a8400>
  post_fork: <function Postfork.post_fork at 0x7ff0504a8510>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7ff0504a8620>
  worker_int: <function WorkerInt.worker_int at 0x7ff0504a8730>
  worker_abort: <function WorkerAbort.worker_abort at 0x7ff0504a8840>
  pre_exec: <function PreExec.pre_exec at 0x7ff0504a8950>
  pre_request: <function PreRequest.pre_request at 0x7ff0504a8a60>
  post_request: <function PostRequest.post_request at 0x7ff0504a8ae8>
  child_exit: <function ChildExit.child_exit at 0x7ff0504a8bf8>
  worker_exit: <function WorkerExit.worker_exit at 0x7ff0504a8d08>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7ff0504a8e18>
  on_exit: <function OnExit.on_exit at 0x7ff0504a8f28>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2021-04-19 16:37:05 +0200] [11499] [INFO] Starting gunicorn 20.0.4
[2021-04-19 16:37:05 +0200] [11499] [DEBUG] Arbiter booted
[2021-04-19 16:37:05 +0200] [11499] [INFO] Listening at: http://10.61.216.128:8000 (11499)
[2021-04-19 16:37:05 +0200] [11499] [INFO] Using worker: sync
[2021-04-19 16:37:05 +0200] [11502] [INFO] Booting worker with pid: 11502
[2021-04-19 16:37:05 +0200] [11499] [DEBUG] 1 workers


Am I missing anything?

**Comment by kkkarthik** [comment]
Hi All

Even though the port was listening, I had to add port to `firewalld `a firewall management solution for Linux. It’s embarrassing really, such a basic miss. I am truly sorry and apologize for wasting your time.

Thanks and Regards
Karthik
