### ISSUE TITLE
Make tests of alternative workers optional

### ISSUE THREAD

**Issue by mkszuba** [benoitc/gunicorn#2563]
At present the GUnicorn test suite fails unless both eventlet and gevent are present in spite of those worker types being optional. It would be nice for their respective tests to be optional as well - and it is fairly simple to achieve this. The way I have done it is by using the pytest feature "importorskip", e.g. by putting:

`import pytest`
`pytest.importorskip('eventlet')`

near the beginning of _tests/workers/test_geventlet.py_ as well as an analogous check near the beginning of _tests/workers/test_ggevent.py_. Then again, perhaps there are even easier ways of handling this.

**Comment by benoitc** [comment]
well tests are for our own purpose. While the workers are optional, they should always be working during a release. Ie. tests are not optionals.
