### ISSUE TITLE
How to return custom json formatted error pages with nginx & drf

### ISSUE THREAD

**Issue by charles-co** [benoitc/gunicorn#2565]
Been trying to return custom json formatted errorpages but somehow seems to be intercepted my gunicorn which then return an HTML page, but I need it to be json. Any help?

**Comment by benoitc** [comment]
did you solve the issue. also why do you need it?

**Comment by charles-co** [comment]
It just started to work when i purchased a domain name, initially was using the IP address that was provided.

**Comment by charles-co** [comment]
I was using django api as a backend service for a mobile app that was being developed so i needed every information to be json formatted.
