### ISSUE TITLE
Deploying Gunicorn with AWS ALB

### ISSUE THREAD

**Issue by harneksidhu** [benoitc/gunicorn#2568]
I am investigating what the appropriate deployment setup would look like in AWS Fargate. Is it still necessary to use NGINX or is ALB sufficient since it already acts as a proxy server?

The document says NGINX is strongly recommended https://docs.gunicorn.org/en/latest/deploy.html?highlight=nginx#nginx-configuration.

I found the following related issues that discuss the usage of ALB & Gunicorn without Nginx. 

https://github.com/benoitc/gunicorn/issues/1864#issuecomment-416303631

https://github.com/benoitc/gunicorn/issues/1296#issuecomment-547779477

Is it safe/recommended to use Gunicorn and ALB alone without NGINX in an AWS Fargate environment?

**Comment by benoitc** [comment]
As a side not i think this documentation needs to be updated. I will take care of it soon.

**Comment by harneksidhu** [comment]
We reached out to AWS Support and concluded that AWS ALB does indeed buffer data between the client and target.
