### ISSUE TITLE
Gunicorn processes requests from clients that have already timed out 

### ISSUE THREAD

**Issue by aflopes** [benoitc/gunicorn#2577]
After reading #1190 and #1492 I was led to believe that Gunicorn would not process requests that had timeout on the client-side. Given I'd recently observed some situations that could potentially indicate that this was not the case or that the clients were not behaving nicely when reaching a timeout, I decided to assemble a small test setup to determine the root cause of having timed out requests being processed by Gunicorn workers.

The Gunicorn app code:
```python
import time

count = 0

def app(environ, start_response):
    global count

    print(f"start {count}")
    if count == 0:
        time.sleep(10)
    else:
        print("UNEXPECTED!!!!!")
        print("Second request should not be processed, because the client as timedout and closed the connection!")
        exit(1)

    resp = "Done {}".format(count)
    print(resp)
    data = resp.encode()
    start_response("200 OK", [
        ("Content-Type", "text/plain"),
        ("Content-Length", str(len(data)))
    ])
    count = count + 1
    return iter([data])
```

The client code that receives the timeout in seconds as an argument
```python
import sys
import socket

if __name__ == "__main__":

    timeout = int(sys.argv[1])
    print(f"timeout set to{timeout}")
    s = socket.socket()
    s.settimeout(timeout)

    host = "localhost"
    port = 8000
    s.connect((host,port))

    s.send('GET / HTTP/1.0\r\n\r\n'.encode()) 
    try:
        data = ''
        data = s.recv(1024).decode()
        print (data)
    except Exception as e:
        print(f"recv exception: {e}")
    finally:
        try:
            s.shutdown(socket.SHUT_RDWR)
            s.close()
        except Exception as e:
            print(f"shutdown/close exception: {e}")
```

With this server and client I've started the Gunicorn server with  `gunicorn -w 1 myapp:app` and then did in 2 separate shell instances the following client executions:
   * `python httpcall.py 20`
   * `python httpcall.py 1`

After this, I was expecting to have only the first request processed, but in fact the second request was always processed. Also, a closer inspection of the TCP connections state with the `ss` command showed the following state after the timeout of the second request on the client-side and while the first request was being processed:
```
State           Recv-Q      Send-Q           Local Address:Port              Peer Address:Port
FIN-WAIT-2      0           0                    127.0.0.1:43566                127.0.0.1:8000
ESTAB           18          0                    127.0.0.1:8000                 127.0.0.1:43564
CLOSE-WAIT      1           0                    127.0.0.1:8000                 127.0.0.1:43566
ESTAB           0           0                    127.0.0.1:43564                127.0.0.1:8000
```

I've also created a small repo with this setup: https://github.com/aflopes/gunicorn-tcp-timeout

So, given the mentioned issues (#1190 and #1492) and what is said on them have I done anything wrong in my test scenario, or it's not possible to avoid the processing of requests of timed-out TCP connections that are in CLOSE_WAIT?

**Comment by raqib-hayder** [comment]
@aflopes: I am experiencing similar behaviour on my end.  

In my scenario, the client sends a request with times out set to `n` seconds, but the server (`gunicorn` with `UvicornWorkers`) does not drop the requests after `n` seconds. The server ends up processing the requests even though the client is no longer listening for responses to those requests 😕 .

Basically, my goal is to drop the request on the server if `n` seconds have elapsed since the client dispatched the request.

**Comment by benoitc** [comment]
That is expected since the socket have been put in the queue. Normally the client should take care to remove itself by properly closing its connection. What worker were you using?

**Comment by aflopes** [comment]
This was a long time ago, but in the [test setup that I've put in place](https://github.com/aflopes/gunicorn-tcp-timeout) I was using the `sync` worker.
