### ISSUE TITLE
option to disable auto restart in case of an error

### ISSUE THREAD

**Issue by kmille** [benoitc/gunicorn#2584]
Hey
I use gunicorn in Docker:
```docker
CMD /usr/bin/gunicorn --bind 0.0.0.0:5000 app:app
```
If the application is misconfigured, it just exits with a non-zero return value. Then gunicorn automatically re-runs the python script (and obviously fails again). From the outside, it looks like the container is running. Is there a way to disable the auto-respawn feature if an error occurs? I couldn't find something in the docs.

Thank you!

**Comment by benoitc** [comment]
There is no such options. Gunicorn itself will stop to restart after some times. You can however check if you're application run before launching it using the `--check-config` parameter. And of course testing the launch before :) Hope it helps.
