### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by Hamza-Lachi** [benoitc/gunicorn#2591]
i have a Django application, that i need to deploy

so when i was running this command

`gunicorn p_crm_rapi.wsgi:application --bind 127.0.0.1:8002 &`

and then i run this command 

`curl 127.0.0.1:8002`

i get this output

```
root@crm-prod-rapi-b54b8ff55-2v78t:/usr/src/app# curl 127.0.0.1:8002
Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /

<!doctype html>
<html lang="en">
<head>
  <title>Bad Request (400)</title>
</head>
<body>
  <h1>Bad Request (400)</h1><p></p>
</body>
</html>
root@crm-prod-rapi-b54b8ff55-2v78t:/usr/src/app#
```

i have set my ALLOWED_HOSTS to ["*"] but still the same error, even I'm not using nginx but still same

please let me know what to do, i have spend my days to find out what's the issue, please guide me.

**Comment by dwdewang** [comment]
you can receive the response, so your web application has started up, 400 error because your request params error, check you api and confirm your params are correct

**Comment by benoitc** [comment]
closing as not activity since.
