### ISSUE TITLE
what happens with unestablished connections when term signal is received 

### ISSUE THREAD

**Issue by rohanil** [benoitc/gunicorn#2593]
Hi, I am investigating 502 and 503 errors from my flask application which is running on gunicorn. I have 8 workers. The infrastructure is using Kubernetes orchestration system. I have 6 pods running of my application. Worker timeout is set to be 8sec and graceful_timeout is 60sec. I am using sync workers. There is nginx proxy in front of application. While processing the requests, if pod is restarted, the workers on that pod get term signal. They finish processing current request and exit. They don't wait until 60sec (graceful_timeout). There are few requests routed to that pod return 502 in nginx logs. Kubernetes has graceful timeout of 60sec so it doesn't send kill signal until 60sec but all workers are exited before. I am suspecting that those 502s are for the requests which were the connections in SYN queue and waiting to move to be established connections. Is my suspicion reasonable ? If yes, how to handle unestablished connections in this case? Could ther be any other cause for above behaviour?

**Comment by benoitc** [comment]
Graceful time out is to let the worker try to finish accepted connections. Others will be discarded by the system and Nginx should close them after some times. Hope it answers to your question.
