### ISSUE TITLE
Invalid responses to HEAD requests

### ISSUE THREAD

**Issue by Changaco** [benoitc/gunicorn#2598]
**Current behaviour:** Gunicorn silently sends invalid responses to HEAD requests if an application generates them.

**Desired behaviour:** Gunicorn discards any body generated by an application in response to a HEAD request, and emits a warning.

**Background:** Five years ago the commit 53329b19cc35fe8a841ea52cf3af80477586dc27 changed the way HEAD requests are handled. The commit's short description was “Ensure response to HEAD request won't have message body”, however that was misleading, because the commit's long description says that “The application is still responsible for ensuring no message body is actually generated in response to a HEAD request.”

**Comment by benoitc** [comment]
It's not the responsibility of gunicorn to discard silently what the application send when using WSGI.

 Fixing the application is the solution there otherwise you will always notice. Maybe Gunicorn should fail with a 500 error there if it's happening but it's not in the spec.

**Comment by benoitc** [comment]
I will review 53329b19cc35fe8a841ea52cf3af80477586dc27 anyway , in the particularly the `should_close` behaviour

**Comment by Changaco** [comment]
I think it is the responsibility of Gunicorn to ensure that the HTTP specification isn't violated. [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.2) clearly states that “the server MUST NOT send a message body in the response [to a HEAD request]”.

I didn't say that Gunicorn should silently discard the body, I said that it should emit a warning.

**Comment by benoitc** [comment]
no it's not its responsability: https://www.python.org/dev/peps/pep-3333/#id34 . 

If we do something I would rather crash early so the developer can fix its application than emitting a warning. It shouldn't be acceptable to have an application deployed with such error. 

I don't deny that having a 'strict-http' option support would be useful though. But then it would imply some others changes around to respect other parts actually delegated to the application.

**Comment by benoitc** [comment]
i think we should probably return a 500  and log it anyway if this happen. That would make thins easier for the client. Thoughts?

**Comment by Changaco** [comment]
If you think that Gunicorn should act like a reverse proxy, then the proper status code is 502. However, this isn't necessarily what a real reverse proxy would do (it could first see a valid HEAD response and forward it to the client, then close the connection to the upstream server for violating the HTTP spec).

(I'm not going to argue further about what you should do. I mostly opened this issue for the benefit of others, I started working on migrating away from Gunicorn and WSGI last week.)

**Comment by benoitc** [comment]
I appreciate your intention but your passive-agressive conclusion is not very constructive at all. I hope you enjoyed the free work at least.

Anyway Gunicorn is as for now is a "WSGI HTTP Server for UNIX, fast clients and sleepy applications". So we should respect this specifications in WSGI workers. There is nothing to discuss about it. The real thing we can make is to help the applications to know early how to return the proper response. I think there is a lot to do about it. 

What you say about reverse proxies is true. And this is why it's advised to use gunicorn behind a server like nginx/haproxy/envoy, so such application error is handled. This is the original intent of gunicorn and we can't break this expectation just like this. This is why if we want to support either body discarding or crashing that should be done by enabling an option. To be explicit.

Support for true HTTP server and other standards is about to land after months of work and will be handled by a different kind of worker base.  This base will  also allows workers to handle things like "ASGI" but not only.
