### ISSUE TITLE
IP_FREEBIND for TCP sockets

### ISSUE THREAD

**Issue by wombatonfire** [benoitc/gunicorn#2599]
Hi,

I can guess in production most of the Gunicorn deployments use the UNIX sockets with a local reverse proxy, but in case there is no proxy, and the server is bound to the TCP socket, a useful option would be to support binding to an IP address that does not yet exist.

When you bind to a specific IP address, and the interface is configured dynamically, there may be no address yet assigned when Gunicorn starts. It leads to lots of "Invalid address" errors in the log and retries. I expect this should happen pretty often when using Gunicorn with systemd, as most of the unit files I've seen online ([here](https://docs.gunicorn.org/en/stable/deploy.html#systemd) as well) use `After=network.target`, which does not guarantee the actual network availability. Even `After=network-online.target` will not provide 100% guarantee, since it depends on the network manager implementation, and requires a "wait" service, such as `systemd-networkd-wait-online.service`.

A simple solution would be to use `IP_FREEBIND` option for TCP sockets, which is available since Linux kernel 2.4. The systemd authors also recommend it for network servers ([see the last paragraph](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)). Among similar projects uWSGI [seems to support it](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#freebind).

I had a quick look at the code, and it looks to me this can be done in `create_sockets()` in `sock.py`. I can submit a pull request, but there are some implementation considerations to be made, specifically:

- Should `IP_FREEBIND` be used for all TCP sockets by default? Allowing the server to bind to a non-existing address has a downside of not throwing an error, when it's bind to the wrong IP. A user should be aware of the implications of the option.
- Considering the above, should `IP_FREEBIND` be an optional, configurable setting? If yes, when and how it should be configured?  I just started using Gunicorn, so I don't know what would be the best place.

**Comment by wombatonfire** [comment]
After creating this issue I found the [ticket](https://trac.nginx.org/nginx/ticket/1741) for nginx, where `net.ipv4.ip_nonlocal_bind` kernel parameter is mentioned.

I haven't tried it myself yet, but it seems like a better option to enable binding to the yet unavailable address, when it's really needed, rather than implement support for `IP_FREEBIND`.

**Comment by benoitc** [comment]
I agree it's sseems better to use the system in suc case.
