### ISSUE TITLE
wait for response timeout

### ISSUE THREAD

**Issue by amg-web** [benoitc/gunicorn#2600]
I run Flask application with gunicorn:
`ExecStart=/usr/local/bin/gunicorn --workers 2 --bind 127.0.0.1:5512 -m 007 wsgi:app --log-level=warn --timeout 100 --log-file /var/log/bbb-visitor.log
`
Short commands is ok
I have subprocess module which is executed for about 20-30 sec.
I make Ajax request once and see in the log:
```
[2021-06-29 14:33:27 +0000] [12168] [DEBUG] GET /visitor/bbbconf
[2021-06-29 14:33:44 +0000] [12168] [DEBUG] Ignoring EPIPE
[2021-06-29 14:33:44 +0000] [12168] [DEBUG] GET /visitor/bbbconf
[2021-06-29 14:34:02 +0000] [12168] [DEBUG] Ignoring EPIPE
```
I tryed to change nginx proxy timeouts and add other timeouts - it did not helped.
problem code part
```
    if operation == "clean":
        result = subprocess.run(
            ["sudo", "bbb-conf", "--clean"], stdout=subprocess.PIPE
        ).stdout
        return render_template("ajax.html", color="blue", result=result.decode("utf-8"))
```

**Comment by benoitc** [comment]
stalled
