### ISSUE TITLE
Per-websocket process

### ISSUE THREAD

**Issue by noamgat** [benoitc/gunicorn#2603]
Hi,
The default model for gunicorn is per-request process pool.
I would like to achieve something similar to websockets - every time a websocket connection is encountered, a process is created and it handles the messages of that websocket.
I have not found evidence that this is possible. Is it something that is possible to execute with correct flags / a few lines of code?

**Comment by benoitc** [comment]
> Hi,
> The default model for gunicorn is per-request process pool.

I am not sure what you mean there. There are different concurrency model in gunicrn:

- The basic one: 1 process = 1 req
- The async one using an eventloop generally, which have a number of threads / processes


> I would like to achieve something similar to websockets - every time a websocket connection is encountered, a process is created and it handles the messages of that websocket.
> I have not found evidence that this is possible. Is it something that is possible to execute with correct flags / a few lines of code?

https://github.com/benoitc/gunicorn/blob/master/examples/websocket/websocket.py is based on gevent but could be adapted for threads.

If you want one websocket / process this would be different. Not impossible though but a mechanism need to be found to detach the process (worker) from the arbiter.

**Comment by noamgat** [comment]
Thanks for the response. I'm thinking of a different approach perhaps - I would use gunicorn + flask-websocket +
