### ISSUE TITLE
[Question] - Worker signal send behavior  

### ISSUE THREAD

**Issue by Kludex** [benoitc/gunicorn#2604]
Hi there! :wave: 

When gunicorn receives a SIGINT and SIGQUIT, it sends a SIGQUIT to the worker, instead of sending the same signal that it received. Is that on purpose?

Related snippets:
https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/arbiter.py#L259-L267 
https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/arbiter.py#L386-L387

**Comment by benoitc** [comment]
yes. on SIGINT we really want to terminate the process and clear the resources . SIGTERM is used for graceful shutdown. Also it's more simple that way. 

https://programmergamer.blogspot.com/2013/05/clarification-on-sigint-sigterm-sigkill.html

**Comment by Kludex** [comment]
Hey @benoitc , thanks for the reply!

I guess the question I meant is more: why not forwarding the `SIGINT` gunicorn receives to the worker? 

My issue is that we don't handle `SIGQUIT` on [uvicorn](https://github.com/encode/uvicorn), which we could, but I don't understand why the forwarding doesn't happen. Would you mind enlighten me?

**Comment by benoitc** [comment]
There is some history behind. I will look at my notes and come back to you
later this evening.

Maybe you could handle both cases? In any case, I think  it should be
expected that SIGINT behaves like SIGQUIT and terminate immediately the
workers .

**Comment by Kludex** [comment]
> There is some history behind. I will look at my notes and come back to you
later this evening.

Thanks! It's really appreciated. :+1: 

> Maybe you could handle both cases? In any case, I think  it should be
expected that SIGINT behaves like SIGQUIT and terminate immediately the
workers .

I guess. What we do is: `SIGTERM` and `SIGINT` give the time to the worker to shutdown gracefully, and if those signals are send again, it terminates immediately. I understand that they should not behave the same way, and `SIGINT` should terminate immediately. I'll discuss to other maintainers and look to why that decision was made.

Anyway, I'll be looking forward to what you can find about the different forwarding signal. Thanks for the efforts! :smile:

**Comment by sandys** [comment]
> 
> I guess. What we do is: `SIGTERM` and `SIGINT` give the time to the worker to shutdown gracefully, and if those signals are send again, it terminates immediately. I understand that they should not behave the same way, and `SIGINT` should terminate immediately. I'll discuss to other maintainers and look to why that decision was made.
> 
> Anyway, I'll be looking forward to what you can find about the different forwarding signal. Thanks for the efforts! 😄

@Kludex thanks for bringing up this issue. there is a long awaited bug #2339 which manifests in uvicorn worker. If you're filing a bug on uvicorn about this, could you please link here ?

**Comment by Kludex** [comment]
@sandys I've created an issue on `uvicorn`, but it's not the issue presented here. It's only related.
I still want to understand the _signal forwarding_ happening here. :cry:

**Comment by benoitc** [comment]
i am not sure what forwarding SIGINT means, but the reason we send a separate signal is that the arbiter acts as a kin dof supervisor.  I am closing it as it' an aold question. Feel free to join me directly if you want to discuss it.

**Comment by Kludex** [comment]
My goal here was to understand `gunicorn`'s logic there, so I can act on `uvicorn` accordingly.

>  [...] the reason we send a separate signal is that the arbiter acts as a kin dof supervisor.

I see this more as an excuse to way this is not something `gunicorn` should be worried (which is fine), than a reasoning for the decision that was taken there.

In any case, I'll modify the `UvicornWorker` worker, and add a `SIGQUIT` handler.
