### ISSUE TITLE
How to shut down gunicorn from inside worker?

### ISSUE THREAD

**Issue by neuneck** [benoitc/gunicorn#2617]
I use gunicorn to host a worker that makes use of multiprocessing. The Process pool I use for that can end up in a broken state, which makes it unable to handle requests. I can catch and handle the corresponding exception in the flask handler and would like to shut down gunicorn (with a non-zero exit code) in these instances (we depoy on K8S, so after a broken state I'd like K8S to handle the cleanup / restart).

What is the recommended way of shutting down gunicorn with a non-zero exit code from inside a worker?

I've tried `sys.exit(1)` and `sys.exit(4)`, but to no avail.

**Comment by benoitc** [comment]
kill its parent? os.ppid() will return its pid.Though I would not advise to do it.
