### ISSUE TITLE
TypeError at startswith('basic') in access logging 

### ISSUE THREAD

**Issue by fdemmer** [benoitc/gunicorn#2618]
While the request/response is successful, I get the following exception during access logging, when receiving a `HTTP_AUTHORIZATION` header containing a byte-string, eg.: `'HTTP_AUTHORIZATION': b'Token ff005e7e84e634332ab1476f279279317b'`

```
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
  File "gunicorn/workers/base_async.py", line 119, in handle_request
    self.log.access(resp, req, environ, request_time)
  File "gunicorn/glogging.py", line 345, in access
    self.atoms(resp, req, environ, request_time)
  File "gunicorn/glogging.py", line 286, in atoms
    'u': self._get_user(environ) or '-',
  File "gunicorn/glogging.py", line 449, in _get_user
    if http_auth and http_auth.lower().startswith('basic'):
```

https://github.com/benoitc/gunicorn/blob/839d5dc66c086ec5aa0a97443fcd768eca1190f0/gunicorn/glogging.py#L449

The circumstances, how or why a byte-string is passed in the WSGI environ are not 100% clear to me and I am not sure if the standard allows it, but it's happening :(. 

Gunicorn 20.1.0/Python 3.8.7 is running behind an apache using [mod_proxy](https://httpd.apache.org/docs/current/rewrite/flags.html#flag_p).

Might be a good idea to decode `http_auth` before checking for `'basic'`?

**Comment by benoitc** [comment]
which worker are you using?

**Comment by fdemmer** [comment]
> which worker are you using?

sorry, did not think this would be relevant for request logging; i am using "gevent" workers.

**Comment by riwatt** [comment]
FWIW the [WSGI PEP](https://peps.python.org/pep-3333/) says that:
> CGI-defined variables must be native strings, if they are present at all. It is a violation of this specification for _any_ CGI variable’s value to be of any type other than `str`.

gunicorn itself conforms to this when it parses the http request lines to headers:
https://github.com/benoitc/gunicorn/blob/88fc4a43152039c28096c8ba3eeadb3fbaa4aff9/gunicorn/http/message.py#L75

A faulty app or middleware might mutate the environ header(s) before gunicorn gets to access logging.

**Comment by fdemmer** [comment]
Thank you for the feedback @riwatt! I tried to reproduce again tonight without success. Closing the issue, assuming it was outside of gunicorn's responsibility.
