### ISSUE TITLE
[BUG] Gunicorn `preload_app` issue

### ISSUE THREAD

**Issue by rkoystart** [benoitc/gunicorn#2621]
Hi, I have a ctranslate model that needs to be loaded into the ram and serve it using gunicorn. I have the following queries:
1)I am having a problem to load the ctranslate model when starting the gunicorn server with `preload_app` argument as True. But with `preload_app` argument as False i am able to server the model. 
2) There is a argument called `workers` in gunicorn which indicates how many request can be served simultanously. There is same ram memory usage for different workers count with `preload_app` True(pytorch model). But with `preload_app` False the ram memory usage for different workers count was increasing as the worker count increase.
Is there a way where I can serve the ctranslate model using gunicorn with `preload_app` as True

**Comment by jamadden** [comment]
> Is there a way where I can serve the ctranslate model using gunicorn with preload_app as True

I don't think so, because you said it has something to do with PyTorch. Please [search this repository](https://github.com/benoitc/gunicorn/issues?q=is%3Aissue+pytorch) and you'll find other issues, particularly #2478 that show that PyTorch is incompatible with preloading.

Closing this because it's been answered in other issues. Feel free to reopen if I'm wrong.

**Comment by rkoystart** [comment]
But i am able to load a fairseq model with `preload_app` as True in gunicorn.?

**Comment by jamadden** [comment]
If RAM is the limiting factor, you might consider restructuring your application into a web front-end that runs in gunicorn, and a separate server process that loads your PyTorch model and handles the processing that needs to use it. You would then be responsible for managing the communication between the front-end and the server process using an IPC mechanism of your choice (sockets, Unix sockets, celery, redis, etc); you would also be responsible for managing the lifetime of the server mechanism, again with a mechanism of your choice (I personally use [supervisor](https://pypi.org/project/supervisor/).

**Comment by jamadden** [comment]
I have no idea what `fairseq` or `ctranslate` are. All I know is that at least some uses of PyTorch are not capable of being preloaded. Please read the other issues for details.
