### ISSUE TITLE
Couldn't get username: 'utf-8' codec can't decode byte 0xa7 in position 21: invalid start byte  

### ISSUE THREAD

**Issue by spaceone** [benoitc/gunicorn#2625]
https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L452

```python
                try:
                    # b64decode doesn't accept unicode in Python < 3.3
                    # so we need to convert it to a byte string
                    auth = base64.b64decode(auth[1].strip().encode('utf-8'))
                    # b64decode returns a byte string
                    auth = auth.decode('utf-8')
                    auth = auth.split(":", 1)
                except (TypeError, binascii.Error, UnicodeDecodeError) as exc:
                    self.debug("Couldn't get username: %s", exc)
                    return user
```

auth is `cWhtbDZnNGxobzpjZ2gyZHNrMHNzpyQhKg==` which is `qhml6g4lho:cgh2dsk0ss\xa7$!*` containing `ISO8859-1` (`§`).

Since when does HTTP define that basic auth content is UTF-8? It does not. It only supports this nowadays optionally.
My client is python-request, which encodes it with `ISO8859-1`: https://github.com/psf/requests/blob/main/requests/auth.py#L63

Therefore you need to adjust that logic, to either use `ISO8859-1` or make it configurable, so that the server can choose. Or support both.

**Comment by benoitc** [comment]
what request has to do with logging? can you paste the failure you see?

**Comment by spaceone** [comment]
```
[2021-08-12 14:21:00 +0200] [13422] [DEBUG] GET /foo/bar/
[2021-08-12 14:21:00 +0200] [13422] [DEBUG] Couldn't get username: 'utf-8' codec can't decode byte 0xa7 in position 21: invalid start byte
```

This also wasn't easy to debug. Maybe it would be better if you respond with `500 Internal Server Error` in that case.
