### ISSUE TITLE
I send "application/json" but Gunicorn seems to change the Content-Type to "text/plain"

### ISSUE THREAD

**Issue by blockjon** [benoitc/gunicorn#2629]
When I run my Flask app without Gunicorn, the Content-Type header I'm sending is correctly received by my Flask app.

However, when I integrate Gunicorn, my app seems to be getting text/plain as the content type. This causes the app to malfunction.

I'm hoping someone who reads this will know the obvious setting I need to adjust to get the headers to work normally.

**Comment by blockjon** [comment]
Here are some clues:
gunicorn==20.1.0
Flask==2.0.1

The request I'm sending is an HTTP PUT.

When I run tests directly on the localhost of my server, this seems to work. However, when i send requests to my production server from a different server, it seems to fail.

**Comment by benoitc** [comment]
gunicorn doesn't change the headers.

**Comment by ocmob** [comment]
I have the same thing happening here, unfortunately. When using a single uvicorn worker the header is correct, but when running from behind gunicorn it is changed to text/plain. @blockjon did you find any solution to this issue?
