### ISSUE TITLE
gunicorn run tornado app failed

### ISSUE THREAD

**Issue by ljcjc** [benoitc/gunicorn#2630]
gunicorn version 20.1.0 and worker class is tornado
tornado version 6.0.0
app class  is tornado.web.Application

gunicorn run this app and rais error below
File "/.venv/lib/python3.8/site-packages/tornado/wsgi.py", line 113, in __call__
    app_response = self.wsgi_application(
TypeError: __call__() takes 2 positional arguments but 3 were given"

I found that the causes of this problem in gunicorn/workers/gtornado.py line113 and 114
`
elif not isinstance(app, WSGIContainer):
       app = WSGIContainer(app)
`

**Comment by alviezhang** [comment]
Reproduce this bug too, tested version 6.0 and version 6.1.

This line breaks code execution.
https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/gtornado.py#L113

**Comment by duanhongyi** [comment]
This RP is really a problem. I think he can be like this:
```
        if tornado.version_info[0] < 6:
            if not isinstance(app, tornado.web.Application) or \
                    isinstance(app, tornado.wsgi.WSGIApplication):
                app = WSGIContainer(app)
        elif not isinstance(app, WSGIContainer) and \
                not isinstance(app, tornado.web.Application):
            app = WSGIContainer(app)
```

**Comment by duanhongyi** [comment]
I'll submit an RP to fix this later.
