### ISSUE TITLE
In-code reference not available anymore

### ISSUE THREAD

**Issue by Kludex** [benoitc/gunicorn#2632]
On: https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/util.py#L463 there's a reference to http://www.svbug.com/documentation/comp.unix.programmer-FAQ/faq_2.html#SEC16, but the page is not available anymore.

I couldn't find the page in any web archive. I don't know if you want a replacement (I can't help) or a deletion.

**Comment by benoitc** [comment]
Thanks! we can probably replace  it by a link to http://www.faqs.org/faqs/unix-faq/programmer/faq/ section 1.7. Maybe we should cache it ourself?
