### ISSUE TITLE
Fix CI: replace Travis CI.

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#2641]
Travis CI doesn't work any more . This should be replaced. We can use Github CI but preferably an independent system should be used.

**Comment by javabrett** [comment]
#2677 was merged to provide GitHub Actions for now.  This issue could stay open for a search for alternatives or for GH Actions improvements - it is bare-bones at the moment, doesn't use the correct set of Python versions in a matrix etc., so needs a bit of work for sure.

**Comment by benoitc** [comment]
closing issue. GH Actions are fine for now.
