### ISSUE TITLE
Recommended number of workers with Gevent (async)

### ISSUE THREAD

**Issue by altaha** [benoitc/gunicorn#2642]
I've read the documentation on setting the number of workers https://docs.gunicorn.org/en/latest/design.html#how-many-workers, and the default recommendation of `(2 x $num_cores) + 1`. To me, setting more workers than `$num_cores` only makes sense when using the default synchronous workers to account for any blocking. As the docs explain "the formula is based on the assumption that for a given core, one worker will be reading or writing from the socket while the other worker is processing a request".

As I understand, that logic does not apply for async workers (specifically gevent which we're using), and the default number of workers should be set `$num_cores`. Gevent will provide concurrency when a request is blocked, so you only need to set number of workers to `$num_cores` to get maximum parallelism while reducing memory footprint.

**Comment by syazwan0913** [comment]
@benoitc Hi. Is it true that for gevent worker we need to set based on `$num_cores`? Or still need to follow the recommendation `(2 x $num_cores) + 1` ?

**Comment by trendels** [comment]
You should probably run a benchmark with your specific app to see what the best number of workers for your particular workload is. In general I would agree that for async workers the maximum amount that makes sense is one worker process per CPU.

**Comment by benoitc** [comment]
> @benoitc Hi. Is it true that for gevent worker we need to set based on `$num_cores`? Or still need to follow the recommendation `(2 x $num_cores) + 1` ?

Setting the number of workers to 2N+1 is still true with the gevent worker. This provide more safety when (re)-loading a new worker and ensure the requests will be more  balanced between workers.

**Comment by houmie** [comment]
Sorry @benoitc 

This is my system: AMD Ryzen 5 3600 6-Core Processor (Cores 12). Each core has two threads.

I don't quite understand the formula. Is it (2 x 6) +1 = 13 or (2 x 12) + 1 = 25
I have a feeling the former is correct.

And then there is [PGTune](https://pgtune.leopard.in.ua) which recommends to only enter the resources that are meant to be used by postgres database.  Hence I was thinking of allocating half of the CPU cores to PostgresDB and the other half to gunicorn (fastapi).

In which case (2x3)+1 = 7 

Does my approach make sense?
Thank you so much for clarifying this as I'm confused.
