### ISSUE TITLE
Gunicorn worker is not releasing the memory(RAM) after completing the request(if application is in idle state) 

### ISSUE THREAD

**Issue by umesh11111** [benoitc/gunicorn#2645]
we have deployed our Apache Superset application in kubernetes env by using Gunicorn webserver.when application started,default ram utilized size is 500MB,after accessing the superset application, memory got utilized 1.5GB out of 2 GB RAM.
when there is not superset application usages, still memory utilization is same 1.5GB,its not releasing the memory.
RAM will be cleared only if we restart the application(Kubernetes Pod).
Why worker is not releasing the memory if application is in idle state.

**Comment by benoitc** [comment]
no follow up. Closing the issue then.
