### ISSUE TITLE
Print logs to stdout

### ISSUE THREAD

**Issue by jplu** [benoitc/gunicorn#2647]
Hello,

It seems that gunicorn prints by default on `sys.stderr`, as when I run the command:
```
gunicorn -k uvicorn.workers.UvicornWorker -w 2 main:app 2> /dev/null
```
I see nothing to be printed but the `uvicorn` logs.

How to make all the `gunicorn` logs print on `sys.stdout` ?

**Comment by zurgeg** [comment]
I'm having a similar problem here. To be completely honest, I think using an alternative logging system is a better idea. You could try removing `2> /dev/null`

**Comment by jplu** [comment]
That's my point, I don't want to remove `2> /dev/null` for several reasons. This is why I'm asking how to get the logs printed on `std.stdout`. And having `2>&1` instead is not a solution neither.

**Comment by zurgeg** [comment]
> 
> 
> That's my point, I don't want to remove `2> /dev/null` for several reasons. This is why I'm asking how to get the logs printed on `std.stdout`. And having `2>&1` instead is not a solution neither.

@jplu Correct me if I'm wrong, but doesn't doing that remove all output period?

**Comment by benoitc** [comment]
Did you try `--log-file=/dev/stdout` ?

**Comment by jplu** [comment]
> @jplu Correct me if I'm wrong, but doesn't doing that remove all output period?

Yes, it removes all the logs that are printed on stderr, that's why I'm asking how to have them on stdout instead.

> Did you try --log-file=/dev/stdout ? Or redirect to the file you want to?

Perfect! Thanks a lot @benoitc, `--log-file=/dev/stdout` does perfectly the work!!
