### ISSUE TITLE
Dedicate gunicorn threads to a specifc set of APIs in flask. 

### ISSUE THREAD

**Issue by dingusagar** [benoitc/gunicorn#2648]
I am using flask + gunicorn with 2 workers and 2 threads for each worker. 
I wanted to know if there is any way to customize the thread delegation which is happening in gunicorn. Basically i want one thread to be allocated to one type of API in my flask app and the rest of the threads to be allocated to all other APIs in the flask app.

For eg: 
API 1 = /api/functionA 
API 2 = /api/funnctionB 

lets say these are 2 APIs. 
i want to allocate only one gunicorn thread to API 1.  And rest of the available threads to API 2. Do we have any way to do this level of customization?

**Comment by pipeti** [comment]
Probably not. Let's say there is the single server socket, once a client starts to process a request (accepts the connection, optionally wraps into SSL, plus it has to look into the request to figure out the api, right?) it can't put the request back to the socket as unprocessed for the other thread to pick it up.
You could though create a custom worker class on your own which acts as a dispatcher, if this is needed, but then you will have the worker process/thread + 2 backend/API processing threads.

**Comment by benoitc** [comment]
Request handling can't be customised like this. It wouldn't make sense anyway since it would break the concurrency. One way to do it is using nginx to send the path on different gunicorn instances.
