### ISSUE TITLE
gunicorn: error: unrecognized arguments: -c config.py app:app

### ISSUE THREAD

**Issue by doraemonlei** [benoitc/gunicorn#2651]
ubuntu 18
cuda10.2
python 3.6
pytorch 1.7

**gunicorn: error: unrecognized arguments: -c config.py app:app**

config.py

```python
import multiprocessing

bind = '127.0.0.1:5000'
workers = multiprocessing.cpu_count() * 2 + 1

backlog = 2048
worker_class = "gevent"
worker_connections = 1000
daemon = False
timeout = 600
debug = True
proc_name = 'xxx'

pidfile = '/root/xxx/logs/gunicorn.pid'
accesslog = '/root/xxx/logs/gunicorn_acc.log'
errorlog = '/root/xxx/logs/gunicorn_err.log'
```

**The following error occurred when I tested the deep learning API.**

usage: gunicorn [-h] [--checkpoint_path CHECKPOINT_PATH] [--resize_outputs]
                [--test_batch_size TEST_BATCH_SIZE]
                [--test_workers TEST_WORKERS] [--n_images N_IMAGES]
                [--n_iters_per_batch N_ITERS_PER_BATCH]
                [--model_1_checkpoint_path MODEL_1_CHECKPOINT_PATH]
                [--model_2_checkpoint_path MODEL_2_CHECKPOINT_PATH]
gunicorn: error: unrecognized arguments: -c config.py app:app

**Comment by gittjob** [comment]
老师，你解决了吗？

**Comment by userzsy1108** [comment]
> 老师，你解决了吗？

我也想知道老师
