### ISSUE TITLE
Feature request: add optional socket timeout

### ISSUE THREAD

**Issue by tsaarni** [benoitc/gunicorn#2652]
Currently it is possible for misbehaving client to block workers for quite some time, from 30 seconds to eternity.

Having a separate option to set timeout for socket read/write would minimize the impact of these, while still allowing longer work to be executed after socket I/O.  For example option `--socket-timeout=5` could be implemented to limit the time spent with socket I/O, while keeping `--timeout=30` as separate timeout for the worker to process the complete request.

Following table summarizes current behavior:

|   | sync | gthread | eventlet | gevent | tornado |
|----------------------|--------|------------|------------|-----------|-----------|
| client connects but does not send HTTP request | 30s | infinity | 2s | 2s | infinity |
| client connects but does not proceed with TLS handshake | 30s | infinity | 2s | 2s | infinity |
| client sends request with keep-alive, then stays idle | 0s | 2s | 2s | 2s| infinity |

* 30 seconds is from default `--timeout`
* 2 seconds is from default `--keepalive`
* 0 seconds means immediately disconnected (according to docs, sync intentionally ignores keep-alive)

**Comment by trendels** [comment]
In the case of sync workers, a timeout doesn't really help. Even with a very short timeout it is still trivial to exhaust all server resources by opening _n_ requests in parallel where _n_ is >= the number of workers. This cannot be solved within gunicorn itself. The correct solution is to only run gunicorn with sync workers behind a proxy such as nginx, where the proxy buffers requests and responses. This is well documented: https://docs.gunicorn.org/en/stable/deploy.html

**Comment by tsaarni** [comment]
Right, it would not make it impossible to block workers, but wouldn't it still be reasonable ask to have two different deadlines

1) shorter initial timeout for client to send its request
2) longer timeout for worker to handle the request

**Comment by benoitc** [comment]
fixed in https://github.com/benoitc/gunicorn/commit/e7781d2c2c669a87532ec6dd5d04490085ef7559 . Sync worker are expected to run behind  a buffered proxy wich alreaady mitigate such issues.
