### ISSUE TITLE
Add support for RFC8297 - An HTTP Status Code for Indicating Hints

### ISSUE THREAD

**Issue by bradleystacey** [benoitc/gunicorn#2654]
This week [Cloudflare announced](https://blog.cloudflare.com/early-hints/) support for [RFC8297 - An HTTP Status Code for Indicating Hints](https://datatracker.ietf.org/doc/html/rfc8297). The RFC adds the status code 103 to the HTTP standard to hint to a browser which assets are required. A user agent can then load those assets while they are waiting for the body of the response, before the body is delivered and parsed.

Example requests and responses from the RFC are below.

Client request:

     GET / HTTP/1.1
     Host: example.com

Server response:

     HTTP/1.1 103 Early Hints
     Link: </style.css>; rel=preload; as=style
     Link: </script.js>; rel=preload; as=script

     HTTP/1.1 200 OK
     Date: Fri, 26 May 2017 10:02:11 GMT
     Content-Length: 1234
     Content-Type: text/html; charset=utf-8
     Link: </style.css>; rel=preload; as=style
     Link: </script.js>; rel=preload; as=script

     <!doctype html>
     [... rest of the response body is omitted from the example ...]

I feel this could be a helpful feature for the project and downstream projects that depend on Gunicorn.

Reviewing the existing `wsgi.py` file it looks like the following enhancements will be required:

* Add an `early_hints` array of tuples to the `Response` class to hold early hints
* Add an `early_hints_sent` flag to the response object as per the existing `headers_sent` flag
* Add a `process_early_hints` method to validate supplied early hints
* Add a `send_early_hints` method to write early hints to the output stream
* Amend the `send_headers` function to also enumerate the early hints in line with the RFC response
* Reference `send_early_hints` in the `write` method of the `Response` class 
* Add and import an `InvalidEarlyHintAs` exception type to report invalid early hint "as" parameters

As you can sense a lot of the above is similar to how headers are already implemented in the `wsgi.py` file. On that basis I feel the interface for the end developer should be similar to how headers are supplied, i.e. changing the method signature of `start_repsonse` to:

    def start_response(self, status, headers, early_hints, exc_info=None):

Where `early_hints` is an array of  `string, string` tuples describing the early hints for the response. Those early hints can then be processed using the `process_early_hints` method like headers are.

I appreciate this is an experimental RFC which might not be in the spirit of the project, that my suggested changes are significant (esp. changes to `start_response`) and we'd need to write some good tests to cover the changes.

This is also my first contribution to the project - so sorry if I've gotten anything wrong above or have misunderstood the process, the current header implementation or any other aspect of the project.

If you're happy with the general idea and my suggested implementation I can start work and open a pull request. I'm sure there is feedback though - so I look forward to reading what the project team think.

**Comment by jamadden** [comment]
The signature of `start_response` is [defined by the WSGI PEP 3333](https://www.python.org/dev/peps/pep-3333/#the-start-response-callable), so it's not something that gunicorn can change.

Many WSGI servers provide the WSGI application with access to the raw socket that's used to communicate with the client; under gunicorn, this is the `gunicorn.socket` key in the `environ`. It's possible this could be used to write data in the 103 style before returning the regular response.

**Comment by bradleystacey** [comment]
Ahh I think I understand @jamadden. On that basis would you suggest 103 should be added to a deployed Gunicorn instance externally through use of the raw socket rather than within the Gunicorn project itself? If so I'll close the issue. Thank you for your help and sorry if I've misunderstood.

**Comment by jamadden** [comment]
Right, that's exactly what I'm suggesting 😄 I think an application/middleware/framework that desires to do this *should* already have the tools it needs. 

Disclaimer: I haven't tried, nor have I read the RFC, so I don't know how current clients would actually handle such a situation, especially in the presence of other HTTP features like pipelining, or if I'm missing some reason this wouldn't ever work in gunicorn.
