### ISSUE TITLE
How do threads behave when a flask app is used with Gunicorn with worker type gevent?

### ISSUE THREAD

**Issue by shydefoo** [benoitc/gunicorn#2661]
## Question 
Lets say a flask app with 1 endpoint `/run` uses a queue and has a separate thread to process the queue to do some work and signal that the response is ready:
Items are inserted into the queue when the endpoint is called, and blocks until we get a response from the queue - 
```python
# app.py
from queue import Queue
from flask import Flask

app = Flask(__name__)
start_thread()
q = Queue()

def start_thread():
    t1 = threading.Thread(target=process_q, daemon=True)
    t1.start()

def process_q():
      # some function

@app.route("/run")
def post(request):
     api_payload = request.get_json()
     ref_queue_item = {"req": api_payload}
     queue.put(payload, False)
     while 'results' not in ref_queue_item:
        sleep(0.001)
     return {
        "results": ref_queue_item["results"],
      }

```
Let's say the server is started using this command:
```
gunicorn -w 1 -b 0.0.0.0:${PORT:-5001} --worker-class=gevent -t 60 'app:app'
```
When the flask app is called using gunicorn with worker type gevent, I understand for each incoming request, a greenlet is spawned. How will the threads behave in this set up and are they monkey patched as greenlets? How does the thread switch tie in together with the use of gevent?

Any help explaining would be greatly appreciated, also if this is not the right place to ask this pls point me to the correct place to air this discussion.

**Comment by jamadden** [comment]
[gunicorn](https://github.com/benoitc/gunicorn/blob/ff58e0c6da83d5520916bc4cc109a529258d76e1/gunicorn/workers/ggevent.py#L37-L38) uses [`gevent.monkey.patch_all()`](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_all) to turn standard Python APIs into non-blocking versions. That includes threads — thread objects become backed by a cooperative greenlet instead of a native thread — and it includes `Queue`, which also becomes cooperative with gevent.

**Comment by shydefoo** [comment]
thanks @jamadden, that would mean for each worker there would just be 1 thread, but with multiple coroutines since all calls to `threading.Thread` being backed by a cooperative greenlet instead?

**Comment by jamadden** [comment]
Correct.

You can spread some work across multiple native threads using gevent's threadpool, but only work that drops the GIL (and doesn't interact with greenlets from other threads) will benefit from that. For most cases, that means native extensions (e.g., numpy calculations).

**Comment by shydefoo** [comment]
i see, ok thanks for clarifying!
