### ISSUE TITLE
Ignore Timeouts during post_worker_init

### ISSUE THREAD

**Issue by Jwuthri** [benoitc/gunicorn#2663]
Hi guys,

I have to load multple tensorflow models on the same worker

``` config.py
bind = "0.0.0.0:8000"
workers = 2
worker_class = "eventlet"
capture_output = True
accesslog = "-"
errorlog = "-"
timeout = 5
```

I wonder, is there a way to load the model (without considering the timeout)
``` this takes ~35 sec
def post_worker_init(worker):
    load_model1..
    load_model2...
```

once the worker has been init, I wanna be able to timeout or cancel a query which takes more than 5 seconds.

Do you have any idea on how to do this?

thank you

**Comment by benoitc** [comment]
this is not the right way to do it. A new internal  is needed to handle such case.
