### ISSUE TITLE
A hook that knows when all workers have been initialized

### ISSUE THREAD

**Issue by nialloh23** [benoitc/gunicorn#2664]
## Context
I'm running a gunicorn server with 2 workers.
Each worker downloads files from S3 and loads them into memory.

## Problem
After all of the workers have been initialized I want to clean-up/delete all of the downloaded files in the local /tmp folder on disk.

## Some things I've tried  
1. post_worker_init -> sometimes one worker reaches this point before another worker has loaded the models into memory
2. pre_request -> runs on every request which feels wasteful

I guess what I'm looking for is something which runs off the master process once all of the workers have reached their post_worker_init state.

Thanks for any help with this.

**Comment by trendels** [comment]
Workers can be spawned by gunicorn even after the initial workers have started, for example if a worker process crashes or runs into a timeout, it will be restarted. In this case the new worker would no longer have access to the files. I think your only option is to keep the files around.
