### ISSUE TITLE
413error request body size problem

### ISSUE THREAD

**Issue by minsuk1** [benoitc/gunicorn#2668]
this is my gunicorn.service  code
```
[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/django-boilerplate/mysite
ExecStart=/home/ubuntu/django_env/bin/gunicorn \
        --workers 3 \
        --bind 0.0.0.0:8000 \
        --limit-request-line 0 \
        --limit-request-filed_size 0 \
        mysite.wsgi:application

[Install]
WantedBy=multi-user.target
```

below is the code where the problem is. 'data' i put as a request body to send this data to other server. and when i printed res.status_code i got 413 error. It's because the data size is big.(1GB) the size of the request body depends on the platform or webserver. I think this is the problem in gunicorn. i found that on the issues that using wsgi.input_terminated is the solution. but i have no idea how to use that code. it would be really thankful if anyone can help me

```
class test(BaseListView):
  def post(self,request):
     data=json.loads(request.body.decode('utf-8'))
     url = 'other server API'
     res=requests.post(url, json=json.dumps(data))
     print(res.status_code)

     return 'ok'

```

**Comment by benoitc** [comment]
stalled issue.
