### ISSUE TITLE
why is the id(GreenThread) always the same?

### ISSUE THREAD

**Issue by ggwakaka** [benoitc/gunicorn#2671]
Env:
```
django: 2.0.4
gunicorn: 19.7.1
eventlet: 0.30.2
greenlet: 1.1.2
PyMySQL: 0.9.3
```

Gunicorn config:
```
bind = "192.168.1.11:8000"
worker_class = 'eventlet'
workers = 1
worker_connections = 1
```
Django Setting:
```
import pymysql
pymysql.install_as_MySQLdb()
```
Test Api:
```
    @action(methods=['GET',], detail=True)
    def beds(self, request, *args, **kwargs):
        count = Student.objects.count()
        return APIResponse(data=[])
```
Test Steps:
1. Add print to `GreenThread.__init__`
```
class GreenThread(greenlet.greenlet):
    def __init__(self, parent):
        greenlet.greenlet.__init__(self, self.main, parent)
        self._exit_event = event.Event()
        self._resolving_links = False
        self._exit_funcs = None
        print(id(self)) # add print
```
2. ab -n 1000 -c 100 http://192.168.1.11:8000/api/eboard/123123123123/beds/
3. View logs:
    All have the same `id(GreenThread)`.

Question:
How to keep the same `id(GreenThread)` in the greenlet.greenlet?

**Comment by javabrett** [comment]
In Python, objects are only guaranteed a unique id for their own lifetime, not the program's lifetime.  See https://stackoverflow.com/a/20753425/452210 for a good explanation.

You'll need a different uniqueness generator if you need such a thing.
