### ISSUE TITLE
WINCH is not working when systemd is involved.

### ISSUE THREAD

**Issue by boatcoder** [benoitc/gunicorn#2673]
USR2 works as expected, but WINCH just prints:
```
localhost gunicorn[3150978]: [2021-10-29 05:48:49 +0000] [3150978] [INFO] Handling signal: winch
```

adding `--daemon` to the command line options causes `gunicorn` to exit after it is started by systemd, so, it seems that WINCH is useless with systemd

**Comment by benoitc** [comment]
gunicorn must be started as main process with systemd.
