### ISSUE TITLE
Request failures while working with gthread worker instead of sync

### ISSUE THREAD

**Issue by eranseer** [benoitc/gunicorn#2676]
Hi

Lately I've been trying to move **flask** application i'm working on that uses gunicorn from **sync** workers to **thread** workers.
The reason for the move is to able to use keepalive as there are only 3 services calling it and not a large group of clients.
The app is CPU bound, not doing any IO operations besides writing to log and takes around 30ms work.

When running locust for load testing I saw 0.1% failures when using **gthread** worker and when tested on **sync** worker I had 0 failures.

using gunicorn 20.0.1
gunicorn config :

worker type : sync / gthread
workers 7 (seems like best performing when I tested it)
threads : 1
worker timeout default
worker connections default
keep_alive 20 (also tried 2, 30 , 50 , 70)
mutual ssl

```
1.  POST | /v1/predict/ | ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
2.  POST | /v1/predict/ | ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

It's hard to see in gunicorn.error log because when it's on debug I see every request. when it's on ERROR I see nothing.
also no errors from flask. 
I optimized max file descriptors and more configurations in sysctl.conf but no luck. that's why I came here to

Few questions related : 
1.Is there any open issue about it that I missed ? or maybe you can give me hint on what can cause it.
2.Is there other way of seeing errors i'm not aware of for debug purposes ?
3.Why when threads=1 and there is load I see multiple threads on each worker in pstree ? 

Thanks

**Comment by eranseer** [comment]
Tested with Jmeter and had no errors so i'm closing this issue.
still would love to heat about questions 2 and 3 if someone can answer. thanks

**Comment by benoitc** [comment]
what does your application ?
