### ISSUE TITLE
should greenlet be listed as a dependency in configuration files?

### ISSUE THREAD

**Issue by yuluc123** [benoitc/gunicorn#2681]
Hi, 
I notice that greenlet is used in the files- gunicorn/workers/geventlet.py. So should greenlet be listed as a dependency for the project? 
![image](https://user-images.githubusercontent.com/93640935/140649960-a4d63552-79e1-4890-8c51-e4afde54fa1c.png)

**Comment by javabrett** [comment]
It's a transitive dependency of `gevent` which can be installed via `pip install gunicorn[gevent]` extras.
