### ISSUE TITLE
Gunicorn 404 error from seperate Docker container on same host machine

### ISSUE THREAD

**Issue by dale-wahl** [benoitc/gunicorn#2682]
This is a weird one. I am using Gunicorn to run a Flask app in a Docker container. This works fine. I have another application that I needs to retrieve files from the Flask app. It works fine unless the two applications are hosted by docker on the same machine. That of course made me think it was a Docker issue (and it still may be) for a while, but the odd thing is that as far as I can tell Gunicorn receives the same request, but responds differently. I am not sure how to troubleshoot and looking for some help.

If I run `curl http://localhost` from my host machine, Gunicorn access log shows this: `172.19.0.1 - - [10/Nov/2021:16:39:05 +0000] "GET / HTTP/1.1" 302 239 "-" "curl/7.55.1"` and I receive my expected page.

If run `curl http://host.docker.internal` from the Docker container where my other app on the same host machine runs, Gunicorn access log shows this: `172.19.0.1 - - [10/Nov/2021:16:40:59 +0000] "GET / HTTP/1.1" 404 232 "-" "curl/7.58.0"`!

I cannot for the life of me imagine why Gunicorn produces a 404! Any ideas or directions you could point me in would be much appreciated. Thanks for your help.

**Comment by dale-wahl** [comment]
Just updating for fun since I wanted to do something that required the same idea and ran into this same issue. We have an application called [4CAT](https://github.com/digitalmethodsinitiative/4cat) that has a backend Docker container and a frontend Docker container that is running Gunicorn on port 5000 which is routed to port 80 externally from the Docker network.

From within the backend container:
`curl host.docker.internal/login/` causes Gunicorn's access log entry:
`172.22.0.1 - - [31/Aug/2022:10:34:48 +0000] "GET /login/ HTTP/1.1" 404 232 "-" "curl/7.74.0"`
`curl 4cat_frontend:5000/`, with 4cat_frontend being the name of the Docker container, causes Gunicorn's access log entry:
`172.22.0.3 - - [31/Aug/2022:10:37:58 +0000] "GET /login/ HTTP/1.1" 404 232 "-" "curl/7.74.0"`
But from outside the Docker network (i.e. my host machine):
`curl localhost/login/` works with the access log entry:
`172.22.0.1 - - [31/Aug/2022:10:38:27 +0000] "GET /login/ HTTP/1.1" 200 3527 "-" "curl/7.83.1"`
It looks identical to the first entry (baring some version bump of curl which I tried to adjust, but they are different OS).

Trying with python `requests` or a browser reproduces the same results with just an updated user agent. I don't get it; the request and even referrer are the same, but the response from Gunicorn is different.

Oh, this is interesting. From outside the Docker network (host machine):
`curl 127.0.0.1/login/` results in:
`172.22.0.1 - - [31/Aug/2022:10:43:05 +0000] "GET /login/ HTTP/1.1" 404 232 "-" "curl/7.83.1"`
I think therefore that this has something to do with how the application is configured, namely that `app.config.SERVER_NAME` is set to `localhost`, but I'm not sure how to confirm that in Gunicorn's logs.

**Comment by benoitc** [comment]
stalled issue. closing.
