### ISSUE TITLE
Cannot upload image to the gunicorn server. connections reset from 5000.

### ISSUE THREAD

**Issue by zedler** [benoitc/gunicorn#2702]
I am trying to upload an image to a webservice. Image size is 132 KB. I am getting the exception when i am uploading.
here is my java code where i am writing the stream to httpconnection output stream.
```java
 DataOutputStream  dos = new DataOutputStream(conn.getOutputStream());
	            byte [] imgData = Files.readAllBytes(imgFile.toPath());
	            
	            //byte [] imgData = "".getBytes();
	            os = new DataOutputStream(conn.getOutputStream());
	            os.write(imgData);
//	            os.write(urlParameters.getBytes());
	            os.flush();
```

```
java.io.IOException: Error writing to server
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:753)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:765)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1686)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at FlaskClient.main(FlaskClient.java:136)
```

**Comment by jamadden** [comment]
Can you please explain why you think this is related to gunicorn? You've only mention Java code here.

**Comment by zedler** [comment]
First of all to set the context
i hava an API written in Flask deployed in Ubuntu+gunicorn. Error is occuring when i tried to call the flask api with with image byte array (contenttype as image.jpg) from java client. Normal calls are workign fine.
1. I am getting socket exception internally when i step into the java HttpClientConnection code.
**java.net.SocketException: An established connection was aborted by the software in your host machine**
2.  This error occurs only in the case i am sending the byte array (image).
3.  When i post the byte array with "somestring".tobytes() the call is gettign successfull.
4. I tried this in post man as well. 
![image](https://user-images.githubusercontent.com/1465318/147053669-44ea1aec-81e8-4c91-8fff-97f15dc7c951.png)
5. The flask api is just two lines. I have removed the lines for easy debugging purpose.  Code is simple enough. When you send the binary data it is not returning the result. But it will print the statement. 

@app.route('/vision', methods=['POST'])
def extractData():
    print("***************inside extractData*****************")
    result = " data............................."
return result

No error is loggedin the gunicorn error log. it is showing though i am getting error in the java client.
2021-12-22 07:16:46 +0000] [2375] [DEBUG] POST /vision
[2021-12-22 07:16:46 +0000] [2374] [DEBUG] POST /vision
[2021-12-22 07:17:09 +0000] [2373] [DEBUG] POST /vision
[2021-12-22 07:17:19 +0000] [2375] [DEBUG] POST /vision
Here is my <app>.service 

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/var/www/visionapp
Environment="PATH=/var/www/visionapp/visionappenv/bin"
ExecStart=/var/www/visionapp/visionappenv/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 wsgi:app --limit-request-line 0 --limit-request-field_size 0

I tried to set the field size to 0 so that i do not want to limit the size of the byte array.

-Prince

**Comment by zedler** [comment]
HI @jamadden 
Another pointer is i ran wireshark. The connection is being reset by server. Please see the RST flag. I am not saying this is gunicorn issue. In fact even with this reset the call is the call is going to the API. But because the connection is reset the exception is thrown are the client. 

Not sure if the connection is reset from EC2 or some intermediary. any helpfull pointer is appreciated.

![image](https://user-images.githubusercontent.com/1465318/147232204-e23add4e-cc58-4f2b-a048-e381c50ebdba.png)

**Comment by benoitc** [comment]
we were missing some informations tehre: HTTP messages and also possible errorsin gunicorn logs. I have the feeling it's an issue in the HTTP messaging. Anyway closing it as stalled.
