### ISSUE TITLE
this is a security vulnerabilities?

### ISSUE THREAD

**Issue by minjianfeng76** [benoitc/gunicorn#2704]
https://github.com/benoitc/gunicorn/commit/b3f9815aba51bd7a24b614d46c277159ce689c40#diff-7e884e24484c7ac02a634681dfd68ba4d1830cdf0204768b2fabbf84dd0adcd3
![image](https://user-images.githubusercontent.com/96512189/147045698-e445eca8-7e19-4182-8291-7b0dcfcd8ab4.png)

**Comment by benoitc** [comment]
the contrary. i is safer to not expect a specific content length:
https://meteatamel.wordpress.com/2010/11/09/websocket-handshake-and-content-length/amp/
