### ISSUE TITLE
Gunicorn cannot release cpu usage after response

### ISSUE THREAD

**Issue by shuhaojie** [benoitc/gunicorn#2710]
I use Gunicorn to start my Django project, here is the command.
`command=gunicorn myproject.asgi:application --workers 4 --threads 3 --timeout 1200 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:778`

However, I found my CPU load is around 100% one or two minutes after responding a `GET` request. As a compare, I changed to `python manage.py` or `uwsgi --ini uwsgi.ini` to start my project, the same request reponsed, the CPU load is not higher than 10%. I have a total of 16 CPUs in my system. Thanks in advance.

**Comment by ahmedbilal** [comment]
@shuhaojie Please share your `uwsgi.ini` file as well.

**Comment by shuhaojie** [comment]
`[uwsgi]
http-socket=0.0.0.0:778
wsgi-file=myproject/wsgi.py
processes=4
threads=8
vacuum=true
enable-threads=True
master=True
;py-autoreload=1
max-requests=1000 
pidfile=uwsgi.pid
logformat=%(ltime) "%(method) %(uri) %(proto)" status=%(status) res-time=%(msecs)ms`

**Comment by benoitc** [comment]
what does your appplication?

**Comment by shuhaojie** [comment]
> 

Sorry, what do you mean by 'appplication'?

**Comment by shuhaojie** [comment]
> 

Sorry, what do you mean by 'appplication'?

**Comment by shuhaojie** [comment]
Let me add more details. I have found that my CPU load is over 100% when a `GET`  is reponsed after finishing a long time task.  To be compare, if I started my project by `python manage.py`, CPU load is not higher than 10% in the same scenary.

**Comment by ahmedbilal** [comment]
@shuhaojie Is it possible to share your complete application? using Github or something... If you can, it would greatly simplify things for `gunicorn` developer and reduce the back/forth questions/answer frequency.

**Comment by shuhaojie** [comment]
I am sorry

> @shuhaojie Is it possible to share your complete application? using Github or something... If you can, it would greatly simplify things for `gunicorn` developer and reduce the back/forth questions/answer frequency.

I am sorry, this application cannot be shared. And I am going to use [this author's method ], seems my problem is same as his. (https://ifconfiger.com/articles/debug-high-cpu-useage-with-gunicorn-deployment)

**Comment by benoitc** [comment]
@shuhaojie that doesn't help to possibly fix the issue :(  What happen during a GET request on your application? What does it do ? Which dependencies are used during this GET request? Are you sharing a global object? Please provide more details. That can be done offline by mail if you need to.

**Comment by benoitc** [comment]
no answer from reporter on requested details. closing the issue
