### ISSUE TITLE
Can gunicorn configure a global variable to be placed in memory for multiple processes to share

### ISSUE THREAD

**Issue by guantao18** [benoitc/gunicorn#2711]

**Comment by nodarai** [comment]
There are actually multiple ways of achieving it and there is a nice article about that: 
https://medium.com/@jgleeee/sharing-data-across-workers-in-a-gunicorn-flask-application-2ad698591875

**Comment by benoitc** [comment]
not as of today but a related feature  is  planned.

**Comment by sboudouk** [comment]
any news about this feature ? @benoitc Thanks !
