### ISSUE TITLE
Listening to ports 80 (HTTP) & 443 (HTTPS) at the same time - is it possible?

### ISSUE THREAD

**Issue by smontanaro** [benoitc/gunicorn#2713]
I am brand new to Gunicorn. Please forgive me (and point me in the right direction) if this is not the right place to ask questions.

I'm using Gunicorn+Flask for a small personal website. (No need to add `nginx` or anything else to the mix at this point.) I created SSL certificate plumbing using Let's Encrypt. (This is also the first time I've set up a web server for SSL/TLS.) When run as root (Ubuntu 20.04, Python 3.10, Gunicorn 20.1.0, Flask 2.0.2, FWIW) I bind to both ports 80 and 443, just port 8080 if not:

```
IAM_ROOT = os.getuid() == 0
...
if IAM_ROOT:
    bind = [
        '0.0.0.0:443',
        '0.0.0.0:80',
    ]
else:
    bind = [
        '0.0.0.0:8080',
    ]
```

HTTPS to port 443 works fine. HTTP to port 80 does not. (I'm just `telnet`ing directly to port 80 for this):

```
[2022-01-06 20:36:09 +0000] [1910] [DEBUG] Error processing SSL request.
[2022-01-06 20:36:09 +0000] [1910] [DEBUG] Invalid request from ip=127.0.0.1: [SSL: HTTP_REQUEST] http request (_ssl.c:2536)
[2022-01-06 20:36:09 +0000] [1910] [DEBUG] Failed to send error message.
```

The SSL bits of my config look like this, falling back to the defaults in the non-root case:

```
if IAM_ROOT:
    # SSL
    LETS_ENCRYPT = "/etc/letsencrypt"
    SERVER = "smontanaro.net"

    CERT_DIR = os.path.join(LETS_ENCRYPT, "live", SERVER)

    ca_certs                          = None
    certfile                          = os.path.join(CERT_DIR, "fullchain.pem")
    cert_reqs                         = 0
    ciphers                           = None
    do_handshake_on_connect           = False
    keyfile                           = os.path.join(CERT_DIR, "privkey.pem")
    ssl_version                       = "TLS"
    suppress_ragged_eofs              = True
```

When running as me where it just listens to port 8080, things also work as expected. It seems that by telling Gunicorn to bind to port 443 and setting the necessary config bits to handle SSL/TLS that it forces all ports into that mode as well. Is it not possible to listen to both secure and insecure ports at the same time, or have I messed up my config in some fashion? I've attached my full config file. There should be nothing secret in there.

[gcfg.py.txt](https://github.com/benoitc/gunicorn/files/7824630/gcfg.py.txt)

**Comment by javabrett** [comment]
Related, poss duplicate #1466.

**Comment by benoitc** [comment]
I don't see any reason to do this behind a proxy. I would rather launch 2 gunicorn instances for such case if I launch it standalone. That makes the expectation easier with a small overhead.
