### ISSUE TITLE
Press `CTRL+C` `Shutting down: Master` not work.

### ISSUE THREAD

**Issue by shenwpo** [benoitc/gunicorn#2716]
Run `python run.py` in terminal, is work. However, Press `Ctrl+C` can't shutdown the thread.
Env: `flask==2.0.2 gunicorn==20.1.0`

**Comment by shenwpo** [comment]
run.py

`import multiprocessing

import gunicorn.app.base

from app import app


def number_of_workers():
    return (multiprocessing.cpu_count() * 2) + 1


class StandaloneApplication(gunicorn.app.base.BaseApplication):

    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super().__init__()

    def load_config(self):
        config = {key: value for key, value in self.options.items()
                  if key in self.cfg.settings and value is not None}
        for key, value in config.items():
            self.cfg.set(key.lower(), value)

    def load(self):
        return self.application


if __name__ == '__main__':
    options = {
        'bind': '%s:%s' % ('127.0.0.1', '8088'),
        'workers': number_of_workers(),
    }
    StandaloneApplication(app, options).run()
`

app.py

`import time
from threading import Thread

from flask import Flask

app = Flask(__name__)


def test():
    while True:
        print("test code")
        time.sleep(5)


t = Thread(target=test)
t.start()
`

**Comment by javabrett** [comment]
@shenwpo there's a problem with the test code here - you are starting an unmanaged, non-daemon `Thread`, `t`, which isn't being shutdown via any hook etc. when you try to shutdown the server and app.  This might be the same in actual application.  That thread will prevent Python from exiting properly.

e.g. in `app.py`, adding:

```
t.daemon = True
```

... will result in a clean shutdown.

**Comment by shenwpo** [comment]
> t.daemon = True

It's work. Thanks a lot for your help.
