### ISSUE TITLE
Interactions between --reload-dir, --reload-include, and --reload-exclude are not very intuitive or well explained (and may even be wrong)

### ISSUE THREAD

**Issue by posita** [benoitc/gunicorn#2722]
I am trying to get `uvicorn` to automatically reload in a dev environment based on source file changes and config file changes. I have two Python src directories (`/path/to/first_dir` and `/path/to/second_dir`) and a config directory (`/path/to/env_dir`) which contains `*.env` files that my application loads.

It is _**really**_ hard to understand what `uvicorn` intends to do, much less what it actually does with regard to tuned reload behavior. Consider:

``` sh
% uvicorn \
     --reload \
     --reload-exclude '*_flymake.py' \
     --reload-exclude 'flycheck_*.py' \
     --reload-dir /path/to/first_dir \
     --reload-dir /path/to/second_dir \
     mm.txns.main:app
```

The above will _**only**_ ignore files matching `*_flymake.py` and 'flycheck_*.py' in `/path/to/first_dir`, _**not**_ `/path/to/second_dir`. So it looks like one needs to repeat the exclude patterns prior to each `--reload-dir`:

``` sh
% uvicorn \
     --reload \
     --reload-exclude '*_flymake.py' \
     --reload-exclude 'flycheck_*.py' \
     --reload-dir /path/to/first_dir \
     --reload-exclude '*_flymake.py' \
     --reload-exclude 'flycheck_*.py' \
     --reload-dir /path/to/second_dir \
     mm.txns.main:app
```

There is not mention of the need for repeated uses of `--reload-exclude` _**in advance of**_ any `--reload-dir` options that I can find.

Further, (in what I am perceiving as a contradiction of the docs), this won't work:

``` sh
% uvicorn \
     --reload \
     --reload-exclude '*_flymake.py' \
     --reload-exclude 'flycheck_*.py' \
     --reload-dir /path/to/first_dir \
     --reload-exclude '*_flymake.py' \
     --reload-exclude 'flycheck_*.py' \
     --reload-dir /path/to/second_dir \
     --reload-include '*.env' \
     --reload-dir /path/to/env_dir \
     mm.txns.main:app
```

Adding, deleting, or modifying `/path/to/env_dir/foo.env` will _**not**_ trigger a reload.

The [documentation for ``--reload-exclude``](https://www.uvicorn.org/settings/#development) makes it clear (or at least strongly suggests) I should be able to expand the patterns matched for reload detection (**_emphasis_** mine):

> `--reload-exclude <glob-pattern>` - Specify a glob pattern to match files or directories which will excluded from watching. May be used multiple times. By default the following patterns are excluded: `.*, .py[cod], .sw.*, ~*`. **_These defaults can be overwritten by including them in `--reload-include`._**

That's not what I'm seeing by including `*.env` files. Then there's this, which seems to contradict the inclusion docs (**_emphasis_** mine):

> By default Uvicorn uses simple changes detection strategy that compares **_python files_** modification times few times a second. If … or you need watching of **_non python files_** you can install [watchgod](https://pypi.org/project/watchgod/) or install uvicorn with `uvicorn[standard]`, which will include watchgod.

Does that mean there's some "upper bound" of patterns uvicorn is capable of considering? Is it `*.py`? That can't be correct, because the counterexample explicitly states that `*.py[cod]` is excluded by default, but could be included via `--reload-include`. It's not clear where the limitations are, even after spending dozens of minutes reading, re-reading, re-re-reading, experimenting, etc.

If the answer is, "Use watchgod," I can't find any documentation of how to do that or what additional configuration steps I would need to meet my use case.

**Comment by posita** [comment]
P.S. I'm not the only person to be confused by this. [This StackOverflow question](https://stackoverflow.com/questions/64118680/reload-flag-with-uvicorn-can-we-exclude-certain-code#comment123408591_64118929) poses something very similar, but remains unanswered:

> Could you advise on how to exclude [*.json] using this method while preserving the reload functionality? I tried: [uvicorn main:app --reload-exclude '*.json'] however it generated this warning: WARNING: Current configuration will not reload as not all conditions are met, please refer to documentation.

**Comment by posita** [comment]
P.P.S. [This comment](https://github.com/benoitc/gunicorn/issues/2339#issuecomment-651270632) from @Andrew-Chen-Wang suggests there is some magic around merely making watchgod available to uvicorn, but fails to go into detail, so I have no way of verifying:

> … [I]f you have watchgod installed, uvicorn should automatically pick that up to make the reloading process better. …

**Comment by Andrew-Chen-Wang** [comment]
The way uvicorn picks up watchgod is via import error checking. Visit uvicorn/supervisors/__init__.py. This only works if you use uvicorn without gunicorn (ie your main command is uvicorn, as recommended by the uvicorn docs) to start the reloading process since gunicorn does not have uvicorn's reload watchers.

**Comment by Andrew-Chen-Wang** [comment]
This belongs in the uvicorn repo, not here I believe. In terms of resolving the issue, I believe you're not supposed to reuse reload-include several times. Instead, wrap all your values in double quotes and make them csv

**Comment by posita** [comment]
Oh shoot! You're right! (I need my glasses this morning.) Closing. I'll refile there.
