### ISSUE TITLE
How to access POST request data in a Python3 application running Gunicorn, without using frameworks like Flask and Django

### ISSUE THREAD

**Issue by aleks-daliton** [benoitc/gunicorn#2725]
An Nginx server + Gunicorn is configured. Gunicorn runs a Python application file. GET request headers, parameters can be accessed via environ variable. I can't figure out how to access parameters received in POST request body.

**Comment by javabrett** [comment]
Have you checked the contents environment `wsgi.input`?

https://www.python.org/dev/peps/pep-3333/#environ-variables
SO: https://stackoverflow.com/questions/530526/accessing-post-data-from-wsgi

**Comment by aleks-daliton** [comment]
> Have you checked the contents environment `wsgi.input`?
> 
> https://www.python.org/dev/peps/pep-3333/#environ-variables SO: https://stackoverflow.com/questions/530526/accessing-post-data-from-wsgi

Thanks for the reply, I'll look into it
