### ISSUE TITLE
gunicorn on Termux

### ISSUE THREAD

**Issue by artynet** [benoitc/gunicorn#2729]
Hello folks, I'm trying to run gunicorn on the latest Termux system for Android-based devices. The default python3 release of the packages manager is **v3.10.2*....

Running this simple app:

```python
def app(environ, start_response):
        data = b"Hello, World!\n"
        start_response("200 OK", [
            ("Content-Type", "text/plain"),
            ("Content-Length", str(len(data)))
        ])
        return iter([data])
```
returns me this error when launching the server with:
```
~ $ gunicorn -w 3 myapp:app
[2022-01-25 16:56:47 +0100] [21631] [INFO] Starting gunicorn 20.1.0
[2022-01-25 16:56:47 +0100] [21631] [INFO] Listening at: http://127.0.0.1:8000 (21631)
[2022-01-25 16:56:47 +0100] [21631] [INFO] Using worker: sync
[2022-01-25 16:56:47 +0100] [21640] [INFO] Booting worker with pid: 21640
[2022-01-25 16:56:48 +0100] [21631] [WARNING] Worker with pid 21640 was terminated due to signal 31
[2022-01-25 16:56:48 +0100] [21646] [INFO] Booting worker with pid: 21646
[2022-01-25 16:56:48 +0100] [21631] [WARNING] Worker with pid 21646 was terminated due to signal 31
[2022-01-25 16:56:48 +0100] [21656] [INFO] Booting worker with pid: 21656
[2022-01-25 16:56:48 +0100] [21660] [INFO] Booting worker with pid: 21660
[2022-01-25 16:56:48 +0100] [21631] [WARNING] Worker with pid 21656 was terminated due to signal 31
[2022-01-25 16:56:48 +0100] [21670] [INFO] Booting worker with pid: 21670
[2022-01-25 16:56:48 +0100] [21672] [INFO] Booting worker with pid: 21672
```
that not happens if the same command/source is run under the **proot-distro** environment running on the very same termux. I think it might be related to the different Termux filesystem paths, any ideas about this ? I also tried to use different worker classes (gevent, tornado) but without any result....

Thanks in advance for your help...

**Comment by benoitc** [comment]
what’s the issue?

**Comment by artynet** [comment]
Sorry @benoitc , clicked too much far the 'comment' button. The issue has been correctly edited...thank you !

**Comment by javabrett** [comment]
Maybe Termux is disallowing some system call made by Gunicorn/Python - do you have a way to see what that might be?  Or open a Python interpreter on the platform and try a few out - start with `os.fork()` ...

**Comment by artynet** [comment]
thank you @javabrett, I'll give it a try and let you know as soon as I run some tests...

**Comment by javabrett** [comment]
Nice, looks like you've confirmed it's coming from `seccomp` - looks like maybe `setuid`?  Termux is known to disallow that.

I've not tested this recently, but can you try adding config to set user and group to `None`, to prevent this call?

**Comment by artynet** [comment]
@javabrett I am using this one as reference, should do the trick:

https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py#L132

then launching the command:
```
gunicorn -c example_config.py -w 3 myapp:app
```
brings me to the same issue anyway...

**Comment by vstavrinov** [comment]
I have the same problem on Android 12, aarch64. But there are not such problem on Android 5.5, arm. They are different termux builds. Set user and group to None doesn't help because this value is ignored as shown by --print-config option.

**Comment by yoni13** [comment]
Same problem on Asus Zenfone 8, Android 13.
Flask debugs mode works fine.

**Comment by vstavrinov** [comment]
This is neither android nor termux issue. This is  bug of gunicorn because it shouldn't try change user (calling setuid) if current (calling) user is not differ from configured (or default) user, but it doing so. Doing so doesn't make sense at all but in case of android this is moreover not allowed.  Please, check if user differ before calling setiud.

**Comment by benoitc** [comment]
> This is neither android nor termux issue. This is bug of gunicorn because it shouldn't try change user (calling setuid) if current (calling) user is not differ from configured (or default) user, but it doing so. Doing so doesn't make sense at all but in case of android this is moreover not allowed. Please, check if user differ before calling setiud.

This has been fixed:
https://github.com/benoitc/gunicorn/blob/98653df9da1acdbf70bbccd6d1ac32eca9ac158c/gunicorn/util.py#L148C1-L149
