### ISSUE TITLE
gunicorn 20+ breaks django with database connections?

### ISSUE THREAD

**Issue by raphaelm** [benoitc/gunicorn#2730]
We run gunicorn 19 with eventlet 0.24 in production for our Django-based application with a PostgreSQL database backend.

As soon as we try to upgrade to gunicorn 20 (and recent eventlet, but also without IIRC), we have a production outage because the app starts creating hundreds of database connections until the maximum connection limit of postgresql is reached.

Something about gunicorn 20 seems to prevent Django from either properly closing connections or from re-using connections properly.

I have no idea where to look deeper for this. Has anyone else seen something like this?

**Comment by raphaelm** [comment]
So to get closer to this we've done an experiment and basically ran ``git bisect`` with this – applying load to our pre-production system in every version. Through all tests we used eventlet 0.29 and the same versions of all other packages. We only changed the gunicorn version between tests and we could clearly determine the problem was introduced with commit a542a07773adce68574ff9e1ef64824a8b811cbc.

**Comment by benoitc** [comment]
do you have any log/code that could help to reproduce the issue?

**Comment by raphaelm** [comment]
The regular stdout/stderr of gunicorn looked entirely normal (basically silence after bootup, no high frequency worker restarts) or I'd already have posted it. I will try if I can build a reproducible setup for this. But if I can't, any ideas what to look for in logs or other debug output?

**Comment by raphaelm** [comment]
I did some further testing.

- This still happens with gunicorn 20.1.0 and  eventlet 0.33.2 on python 3.10
- This still applies with gunicorn at 69bf1d0cf44abffeeb469d4c36e1ff978b6e5769 (can't test newer version due to #2904)
- This also happens with gevent workers, but here it also happens already with gunicorn 19
- This does not happen with the sync worker class

I think what we're seeing *might* just be #996 and the gunicorn19+eventlet combination just worked "by accident"?

**Comment by raphaelm** [comment]
Yeah, I believe this is just #996 again that weirdly hit us by surprise with the update for unknown reasons :( Not worth looking into this further, I guess.

**Comment by mandarva** [comment]
@raphaelm did it work with gunicorn==19.10.0 and gevent==22.10.2 and greenlet==2.0.1 ?

**Comment by raphaelm** [comment]
I don't recall
