### ISSUE TITLE
-D error

### ISSUE THREAD

**Issue by xiongda777** [benoitc/gunicorn#2732]
I run my flask app with no error when there is no -D.But with -D it rise internal server error.why I get this error?

**Comment by javabrett** [comment]
What error do you get? What command did  you run?

**Comment by xiongda777** [comment]
> What error do you get? What command did you run?

I run gunicorn with `gunicorn -w 4 -b 0.0.0.0:3003 flasky:app --timeout 0 -D`
but my app get internal server error.
when I run gunicorn with `gunicorn -w 4 -b 0.0.0.0:3003 flasky:app --timeout 0 `,
there is no "-D",my app is normal.

**Comment by javabrett** [comment]
- Can you test and see if it makes any difference to inherit stdio with `-R` at the same time e.g. `gunicorn ... -D -R >out.log 2>err.log`?
- What logic in your Flask application can result in `pic_ave` being `0`?

**Comment by xiongda777** [comment]
I'm sorry for replying so late. I use gunicorn... -D -R >out.log 2>err.log. I'm on err. The log sees 'the input device is not a TTY'. I understand that the problem is in the docker command, before I used docker exec -it to enter docker, but when gunicorn is running in the background -it parameter will report an error. Now I removed -it and my app works fine. Thanks
