### ISSUE TITLE
Multiple Worker doens't revoke jwt token on python HELP

### ISSUE THREAD

**Issue by vinceplayer** [benoitc/gunicorn#2733]
Hi, I noticed that when I deployed my api server with gunicorn using flask, the process of revoking the token on logout or other conditions no longer worked.
Everything worked when i put worker 1, do you know how i could fix it please?
`@account.route('logout', methods=['DELETE'])

@viewer_required()
def logout():

    jti = get_jwt()["jti"]

    main.blacklist.add(jti)

    return jsonify({"msg": "Successfully logged out"}), 200`

`@jwt.token_in_blocklist_loader

def check_if_token_in_blacklist(jwt_header, jwt_payload):

    jti = jwt_payload['jti']

    return jti in blacklist

`

**Comment by javabrett** [comment]
Are you storing the jwt blacklist in a global or other scoped variable in a single Gunicorn worker, but expecting all workers to see a shared set of jwt tokens?  That won't work and you'll have to rethink the application design on how you share that state.

I'll close this but please add a comment if you believe you have found a Gunicorn bug.
