### ISSUE TITLE
Gunicorn executable missing in recent release

### ISSUE THREAD

**Issue by chrisspen** [benoitc/gunicorn#2737]
After a recent upgrade to gunicorn 20.1.0 in Python 3.10.1 on Ubuntu 20.04, the `gunicorn` executable no longer exists in my virtual environment.

    $ python -V
    Python 3.10.1
    $ which python
    /usr/local/myproject/.env/bin/python
    $ which pip
    /usr/local/myproject/.env/bin/pip
    $ pip freeze | grep -i gunicorn
    gunicorn==20.1.0
    $ which gunicorn
    $ gunicorn --help
    
    Command 'gunicorn' not found, but can be installed with:
    
    sudo apt install gunicorn

The docs still indicate we should be able to call `gunicorn` as a command line script. Has this changed and the docs not yet been updated?

**Comment by javabrett** [comment]
Could you provide an environment description and set of commands to reproduce missing `gunicorn` in venv?

`cat Dockerfile`

```
# syntax=docker/dockerfile:1.3-labs

FROM python:3.10.2-slim-bullseye

RUN python -m venv .venv

RUN <<-EOF
    . .venv/bin/activate
    pip install -U pip
    pip install gunicorn
    which gunicorn
    python --version
    gunicorn --version
EOF
```

`docker buildx build --progress=plain .`

```
#10 [3/3] RUN <<-EOF (. .venv/bin/activate...)
#10 0.450 Requirement already satisfied: pip in /.venv/lib/python3.10/site-packages (21.2.4)
#10 0.592 Collecting pip
#10 0.677   Downloading pip-22.0.3-py3-none-any.whl (2.1 MB)
#10 0.910 Installing collected packages: pip
#10 0.910   Attempting uninstall: pip
#10 0.911     Found existing installation: pip 21.2.4
#10 1.002     Uninstalling pip-21.2.4:
#10 1.148       Successfully uninstalled pip-21.2.4
#10 2.038 Successfully installed pip-22.0.3
#10 2.609 Collecting gunicorn
#10 2.719   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
#10 2.752      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 2.3 MB/s eta 0:00:00
#10 2.760 Requirement already satisfied: setuptools>=3.0 in /.venv/lib/python3.10/site-packages (from gunicorn) (58.1.0)
#10 2.784 Installing collected packages: gunicorn
#10 2.836 Successfully installed gunicorn-20.1.0
#10 2.905 /.venv/bin/gunicorn
#10 2.906 Python 3.10.2
#10 2.996 gunicorn (version 20.1.0)
#10 DONE 3.1s
```

**Comment by chrisspen** [comment]
I think my venv may have been created with the wrong user, forcing local/bin to be used instead. When I deleted and re-ran my script to create my venv, it appears to have correctly installed everything into bin.
