### ISSUE TITLE
Question: gunicorn support for native UNIX function calls

### ISSUE THREAD

**Issue by martiousteam** [benoitc/gunicorn#2745]
This is a question for forum.

Does gunicorn support native UNIX function calls (NON-pure python libraries) without any issues? I would like to call pdfkit for pdf generation which in turn calls native commands (based on c) wkhtmltopdf.

I have tried to do the same through Apache HTTPD but there are issues related to threads and processes. Hence the question.

Thanks

**Comment by benoitc** [comment]
late answer. But the only requirement is to ensure the response returned is not blocking, ie be enought fast or can be run asynchronously.
