### ISSUE TITLE
Run gunicorn with packaged django (PyInstaller)

### ISSUE THREAD

**Issue by ziXet** [benoitc/gunicorn#2749]
I saw this for flask.
https://github.com/benoitc/gunicorn/issues/669

Is there any way to achieve this with pacakged django?

Something like this maybe? https://github.com/benoitc/gunicorn/blob/0.12.1/gunicorn/management/commands/run_gunicorn.py

Any hint is appreciated.

Thanks

**Comment by benoitc** [comment]
this can be done by creating a custom application : https://docs.gunicorn.org/en/stable/custom.html to control the start.
