### ISSUE TITLE
heroku 404

### ISSUE THREAD

**Issue by wanghaisheng** [benoitc/gunicorn#2754]
i have a https://github.com/wanghaisheng/TikTokDownloader_PyWebIO/blob/main/Procfile

gunicorn is in requirement.txt

1. deploy heroku as this way is fine
web: python  TikTok_ZH.py --port=$PORT

2.but constant give me 404 
 web: gunicorn TikTok_ZH:app

3. my main.py
https://github.com/wanghaisheng/TikTokDownloader_PyWebIO/blob/main/TikTok_ZH.py

anyone know ?

**Comment by benoitc** [comment]
any log?

**Comment by wanghaisheng** [comment]
i kind of figure it  but dont know why and behind logic 
no log

```
web: python  TikTok_ZH.py --port=$PORT

```

and 
```

    if (os.environ.get('PORT')):
        port = int(os.environ.get('PORT'))
    else:
        port = 5000
        
    app.run(host='0.0.0.0', port=port)
```

**Comment by benoitc** [comment]
I believe this is a none issue today with the end of heroku.
