### ISSUE TITLE
Worker signal deaths are not logged by gunicorn

### ISSUE THREAD

**Issue by ScoreUnder** [benoitc/gunicorn#2762]
If a worker gets SIGABRT/SIGSEGV/SIGILL/etc, gunicorn will silently reap it and then loudly relaunch it. It isn't clear from logs that it has failed abnormally, it just looks like gunicorn going wild.

This is related to how I came across #2761, and the code at https://github.com/benoitc/gunicorn/blob/933b210f2eff943f4cd9502c676f3d93c82f171c/gunicorn/arbiter.py#L513-L534

It would be nice for debugging reasons if it logged that the worker has died for an unexpected reason when it gets these signals.

**Comment by benoitc** [comment]
tey are but at a different location in the arbiter module.

**Comment by ScoreUnder** [comment]
Is there a procedure to enable this logging?

**Comment by ScoreUnder** [comment]
to be clear I don't see where this is handled and have not been receiving any type of log that the worker has ended, let alone that it has crashed due to segmentation fault. is it something that needs enabling on my end? @benoitc
