### ISSUE TITLE
Socket error processing request

### ISSUE THREAD

**Issue by sh00076227** [benoitc/gunicorn#2763]
Gunicorn Version: 20.0.4
OS :CentOS 7.4

 "Socket error processing request" error occurred on  /var/log/messages in Gunicorn.
We are trying to solve this problem, is there a good solution?

there was a very similar case, but it doesn't seem to fit my environment.
https://github.com/benoitc/gunicorn/issues/1913

**Comment by benoitc** [comment]
old issue without details to reproduce it. I am closing it. If it's still reproducable please open a *new* ticket with more details.
