### ISSUE TITLE
overriding server header in response

### ISSUE THREAD

**Issue by udit-pandey** [benoitc/gunicorn#2771]
I have added few headers using [secure package](https://pypi.org/project/secure/) in my fastapi application. I wanted to overwrite the server header(having default value "uvicorn") to something else. All the added headers using secure package are replicated in the responses except the server header which is coming twice(once with value given by me and other with uvicorn) as shown the postman api response below:

![image](https://user-images.githubusercontent.com/18224381/161194376-1ff92c6c-ed3e-41c6-9578-39993ea17179.png)

I run my application using:
`gunicorn -k uvicorn.workers.UvicornWorker ${APP_MODULE} --bind 0.0.0.0:80`

I tried using gunicorn config as suggested in this [stackoverflow question](https://stackoverflow.com/questions/16010565/how-to-prevent-gunicorn-from-returning-a-server-http-header), but this did not work.
Why is this header not being overriden?

**Comment by benoitc** [comment]
this has been answered in different tickets. there is no need real good security reason to hide the server info.
