### ISSUE TITLE
Revert random `time.sleep` in `spawn_workers`

### ISSUE THREAD

**Issue by blueyed** [benoitc/gunicorn#2777]
I came across the following code added in https://github.com/benoitc/gunicorn/commit/3ade8e8d78586621f735c62abc1c4bf0b497ff44:
https://github.com/benoitc/gunicorn/blob/933b210f2eff943f4cd9502c676f3d93c82f171c/gunicorn/arbiter.py#L617

This adds (random) overhead/slowdown during startup, and from skimming the comments in the issue it was meant for (https://github.com/benoitc/gunicorn/issues/514) it is not confirmed to be helping really.

I suggest removing it for faster, more predictable startup.

(A related issue that might help with adding delay during startup: https://github.com/benoitc/gunicorn/issues/514)

**Comment by benoitc** [comment]
imo this 10 year changes is still useful as it ensure to not make the system too busy. I will close it for now, but if you have any production example where it can be useful, I am happy to revisit this isssue.
