### ISSUE TITLE
Listen only after (first) worker is started/ready

### ISSUE THREAD

**Issue by blueyed** [benoitc/gunicorn#2778]
It would be useful if gunicorn could be configured to listen only after workers have been spawned, and possibly/maybe the first one being ready.

While looking into this I've found that the call to `sock.listen` in https://github.com/benoitc/gunicorn/blob/933b210f2eff943f4cd9502c676f3d93c82f171c/gunicorn/sock.py#L56 would need to be done later.

**Comment by benoitc** [comment]
Worker need to ensure the socket is already listening when started. closing the issue.
