### ISSUE TITLE
Using preload parameter and How to pass the value from master to workers

### ISSUE THREAD

**Issue by Brain-Maxwell** [benoitc/gunicorn#2779]
Hello, I have a problem in using gunrcorn in flask app.  I created 4 workers using gunicorn, There is a timer task in worker  that will query the database and then refresh a dict in the worker. The problem is : When I start the project, the database is loaded four times during 
app initialization phase, which means that each worker has a separate database connection，and also in the timer task.
I have tried using the preload parameter. When the project starts in this way, only one database query is executed. But the time task just work in master, it can refresh the dict in master but can't  pass the new dict  to workers. Is there any way to solve this problem?

**Comment by benoitc** [comment]
workers doesn't share any memory by themselves. A database connection shoud be started per workers. If you want to share a data baetween themselves you have to rely for now o an external memory database or a process started in master that share a context with other worker.
