### ISSUE TITLE
gunicorn execution with Mac M1 crash immidiatly

### ISSUE THREAD

**Issue by Yoniseg** [benoitc/gunicorn#2788]
Hi
we have 2 machines with Mac OS with M1 processor that can't run gunicorn (version 20.1.0)
After executing:

> gunicorn --timeout 9999999 --log-level debug --bind 0.0.0.0:5001 --worker-class=gevent --workers=1 services.api.start_gunicorn:app

We get a "Python quit unexpectedly" message with crash details (attached in a file)
Versions list in the attached file

![Screen Shot 2022-04-27 at 14 15 40](https://user-images.githubusercontent.com/33287172/165506546-c18d4845-bd48-4d24-9d35-b53cbb674353.png)
[gunicorn crash.txt](https://github.com/benoitc/gunicorn/files/8571495/gunicorn.crash.txt)

**Comment by zhangw** [comment]
I encountered the segmentation fault from python3.8 on my mac m1,  disabling proxy settings should be a workaround for my case.

![image](https://user-images.githubusercontent.com/196561/204472784-81ae4c95-52b3-46c0-9e91-d06886dbf9bb.png)

export NO_PROXY=* and the gunicorn works.

[gunicorn crash](https://github.com/benoitc/gunicorn/files/10110980/draft13.txt)

**Comment by rady-msaad** [comment]
@zhangw : spent hours on this issue. Your solution worked for me. (Using airflow gunicorn aws-connection)

**Comment by MatsLanGoH** [comment]
Thank you @zhangw. Adding `NO_PROXY=*` to our run configurations fixed the problem. 

Background:
We ran into a similar issue when running a Flask app via gunicorn gevent workers. 

Any calls to `requests.request` would cause our app to crash. Stepping through the code we discovered that the error would trigger anytime a call to `_scproxy._get_proxy_settings()` was made. 

We could reproduce this on both M1 as well as Intel machines. 
Our linux machines were not affected - the issue itself might be related to #2261.

**Comment by herlambang** [comment]
This also happened to me where segmentation fault raised by _scproxy.c module

osx: 12.6 Monterey (intel)
python: 3.10.9
gunicorn: 20.1.0

I'm able to fix this by reinstalling my python using openssl configuration option (`CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl@3)"`) which I didn't add on previous installation.

```bash
LDFLAGS="-L/usr/local/opt/openssl@3/lib" \
CPPFLAGS="-I/usr/local/opt/openssl@3/include" \
CONFIGURE_OPTS="--with-openssl=$(brew --prefix openssl@3)" \
pyenv install 3.10.9
```
_This also works for ssl 1.1_

Calling `_scproxy._get_proxy_settings()` within gunicorn worker now output something like 
```
{'exclude_simple': False, 'exceptions': ('*.local', '169.254/16')
``` 
instead of raising segmentation fault.

**Comment by petroslamb** [comment]
Adding the flag to my M1 laptop did indeed change the `signal 11`, to another error:

```
objc[28662]: +[NSCheapMutableString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

```

**Comment by benoitc** [comment]
request is not threadsafe. maybe it worth to tru another http client.

**Comment by petroslamb** [comment]
> request is not threadsafe. maybe it worth to tru another http client.

@benoitc thanks for your answer. I did find the workaround of using the `--preload` flag for M1/OSX. But i'll look into your suggestion in more detail too.
