### ISSUE TITLE
Is INI configuration file supported in gunicorn

### ISSUE THREAD

**Issue by jimnac** [benoitc/gunicorn#2789]
Hello,

I am trying to run my gunicorn application with custom configurations. I understand config file can be a .py file. I would like to know is .ini file type supported by gunicorn. As the end user has to modify the no of workers based on the lab configuration in production, setting the configurations in .py file would not be helpful as the end user would not have access to this location.

**Comment by benoitc** [comment]
No ini is supported directly. You can build a wrapper and load it in config.py or use Paster for this.
