### ISSUE TITLE
Metrics collection by gunicorn

### ISSUE THREAD

**Issue by jimnac** [benoitc/gunicorn#2791]
Hello,

For metrics collection, gunicorn supports --statsd-host (https://docs.gunicorn.org/en/stable/instrumentation.html) parameter where we have to tell gunicorn where the statsD server is running. Here gunicorn has  dependency on additional dameon process(statsD). I would like to know is there any plan for gunicorn to collect the metrics by itself without depending on any other external server.

**Comment by benoitc** [comment]
@jimnac next version of gunicorn has support of openmmetrics and provide an optionnal /metrics handler for it.
