### ISSUE TITLE
gunicorn master making hidden requests

### ISSUE THREAD

**Issue by anjalisi** [benoitc/gunicorn#2792]
I am using multiple gunicorn workers (`workers=multiprocessing.cpu_count() * 2 + 1`). The request handling is pretty fast, but on some debugging we found that even after the requests are handled, and the response is returned, uwsgi processes are still making some requests despite no requests being made on the server(which can be shown in the grafana dashboard)
![11_11_51](https://user-images.githubusercontent.com/47551578/167543423-941cbe45-6955-4931-bbfd-f6550b7f4714.jpg)

Currently I am using gunicorn as a kubernetes deployment with 4 replicas. All the pods are logging the requests which it recieves, but I do not see any request which can explain the behaviour in the graph. There are no requests out of place, and no additional resources are created. 

When I scale down the workers to 1, I do not see this anomaly. It works as expected. It gets the request -> processes and sends the response -> no abnormal activity in the graph.

I am using the latest gunicorn version.

- Entrypoint defined in Dockerfile: `ENTRYPOINT ["gunicorn", "-c", "myid_groups_api/gunicorn.conf.py", "myid_groups_api.__main__:app"]`
- conf file:
```
import logging.config
import multiprocessing
import os
workers = multiprocessing.cpu_count() * 2 + 1
threads = 5
bind = "0.0.0.0:8080"
logging_level = os.getenv("LOGGING_LEVEL", "INFO")
worker_class = 'sync'
backlog = 2048
worker_connections = 2000
timeout = 120
errorlog = '-'
error_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
loglevel = 'info'
accesslog = '-'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
```
- python version: `python3.10`

Does anyone know why I am facing this issue? Is it because of the number of workers I am using? If so, why?

**Comment by benoitc** [comment]
I don't understand this issue. Gunicorn doesn't make any requests at all. maybe an issue in the counters? Anyway closing it as it seems not related to gunicorn.
