### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 18 (char 17)

### ISSUE THREAD

**Issue by amroghoneim** [benoitc/gunicorn#2794]
I am using gunicorn + Flask + Docker with async gevent workers. My application receives a request with a json body that contains a base64 encoded image. I then load this json, extract the image using its key and continue with my processing before return the response. This works fine, but for some requests I do not receive the full json body and get the error shown above. What could be the problem here?

```
from flask import Flask, Response, jsonify, request
import json

@app.route("/ocr", methods=["POST"])
def ocr():
    data = json.loads(request.data) # error happens here
     ...
```

gunicorn command:
```
gunicorn wsgi:app --bind  0.0.0.0:443--log-level=debug --worker-tmp-dir /dev/shm --workers=4 --worker-class gevent --reload --timeout 300 --graceful-timeout 300 --log-file=-
```
Note that my endpoint is called by an app (users from different locations/phones/networks)

I noticed that I am missing some of the json body that I was expecting for these images, which I believe is the reason why I get this error when loading the json.

Is this an issue of slow connections/ large json body? if so how can I fix this to handle such requests?

**Comment by benoitc** [comment]
do you have any issue on gunicorn side? Did you check that the content length was ok when reading the body on client side? To me it looks more an error either in the framework used or the client. Let me know.

**Comment by EeyoreLee** [comment]
I think the error is caused by the client. Put another way, you did not parse the request according to the content type. You just use `json.loads` and you can't ensure the data comes from `request.data`. like `form` or others. Or you have agreed with the client in advance to transmit in json mode. Then it's the client's fault. otherwise it's your fault. please read the HTTP  protocol and flask `request` object more details. you can just run the flask web server and The issue is same.Maybe my English is not clear or rude. Sorry in advance if it is .

**Comment by amroghoneim** [comment]
@benoitc 
Apologies for not replying quickly to I don't receive any notifications for some reason

I was flooded with other projects so I didn't check/try much of what you guys said.

Issue still somewhat persists.

I changed the worker class to use gevent_pywsgi ( mainly out of why not )
```
gunicorn wsgi:app --bind  0.0.0.0:443 --log-level=info --worker-tmp-dir /dev/shm --workers=4 -k gevent_pywsgi --reload --timeout 300 --graceful-timeout 300 --log-file=-
```

I keep getting the following in gunicorn logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/wsgiref/simple_server.py", line 118, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 292, in write
    self._write(data)
  File "/usr/local/lib/python3.7/wsgiref/handlers.py", line 466, in _write
    result = self.stdout.write(data)
  File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
TimeoutError: [Errno 110] Connection timed out
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/wsgiref/simple_server.py", line 126, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/local/lib/python3.7/http/server.py", line 322, in parse_request
    "Bad request syntax (%r)" % requestline)
  File "/usr/local/lib/python3.7/http/server.py", line 481, in send_error
    self.wfile.write(body)
  File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```

I also receive alot of invalid requests ( I think because of port 443 I am using? )
```
----------------------------------------<gevent._socket3.socket at 0x7f313ca4bf30 object, fd=124, family=2, type=1, proto=6>: Invalid HTTP method: '\x16\x03\x01\x00\x85\x01\x00\x00\x81\x03\x03;bYà\x06r¶+4\x8f\x8eºyx\x97â\x1bê&iÕ¾\x10\x9f\x9eã\x7f\x18\x8eM\x088\x00\x00 À/À0À+À,Ì¨Ì©À\x13À\tÀ\x14À\n'
<gevent._socket3.socket at 0x7f312efbd130 object, fd=124, family=2, type=1, proto=6>: Invalid HTTP method: '\x16\x03\x01\x00â\x01\x00\x00Þ\x03\x03È\x0c;\x00gl£\r\x07\x1eOD\x01¢OÚc7°Ýè\x1f´2ïs@Æ\x93\x14lR Ô\x1c³\x94m Bz\x81s«xÜóîá°\x8a<üp}Âp¨\x0fÐ{[ØxB\x00\x08\x13\x02\x13\x03\x13\x01\x00ÿ\x01\x00\x00\x8d\x00\x00\x00\x0c\x00\n'
<gevent._socket3.socket at 0x7f312efbd130 object, fd=124, family=2, type=1, proto=6>: Invalid http version: '\x16\x03\x01\x01\x11\x01\x00\x01\r\x03\x03+Ë\x9c¶ÿ\x8c.Èår\x9d\x19\x8e1¡a\x1dÉÕçº\x99\x80Í{pñ±"½\x88q\x00\x00|À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀSÀ+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$À(\x00k\x00jÀ#À\'\x00g\x00@À\n'
<gevent._socket3.socket at 0x7f312efbd130 object, fd=124, family=2, type=1, proto=6>: Invalid http version: '\x16\x03\x01\x01\x11\x01\x00\x01\r\x03\x02â\t\x89$\x88\x00«î<\x94ï\x96\x98:\x04\x1aÝ\x98®V\x02-§zù\x95i¾þ:^5\x00\x00¢À\x14À\n'
<gevent._socket3.socket at 0x7f312efbd130 object, fd=124, family=2, type=1, proto=6>: Invalid http version: '\x16\x03\x01\x01\x11\x01\x00\x01\r\x03\x01¹¿ôd\x84\tüx¼©\x0füóÅo°-ÚróèM_È\x0fºçîå\x00=\x8c\x00\x00¢À\x14À\n'
<gevent._socket3.socket at 0x7f312efbd130 object, fd=124, family=2, type=1, proto=6>: Invalid HTTP method: '\x16\x03\x00\x00Î\x01\x00\x00Ê\x03\x00ÎgÈU"\x94 \x1f\x11\x19\x97Î\x18®<7\x89WZ\x9d\x1elP\x14\x94\x83É \x04\x01>p\x00\x00¢À\x14À\n'
<gevent._socket3.socket at 0x7f312efbd130 object, fd=124, family=2, type=1, proto=6>: Invalid HTTP method: '\x16\x03\x01\x01\x19\x01\x00\x01\x15\x03\x03\x8eíO:\x01¯p·p\x84\\]Q\x07{\x00\x02\x14àÞ½\x14\x04iÎ\x90ªî0+^\x96\x00\x00\x86À0À,À(À$À\x14À\n'
```

**Comment by amroghoneim** [comment]
@EeyoreLee Not at all thank you for trying to help!
Can you please elaborate on your point?
I did agree with the client that the data to be received by the server should be ```application/json``` if that is what you mean.
Can you refer me to some resources that I should check to make sure I am doing things correctly from my side?

**Comment by amroghoneim** [comment]
@benoitc We suspected that the client might be having some issues sending large images over a slow connection (which could be the case in a third world country). The images were resized from the client side to send smaller requests, yet I still see the issues above (approx. 9% of our daily users face an issue when running this service, so solving the issue is definitely important).

**Comment by EeyoreLee** [comment]
@amroghoneim I looked again the title of the issue. I can give a sample to reproduct it. 
```
from flask import Flask, Response, jsonify, request
import json

app = Flask(__name__)

@app.route("/ocr", methods=["POST"])
def ocr():
    data = json.loads(request.data) # error happens here
    ...

app.run(host="0.0.0.0", port=8080)
```
This is a easiest app to warp your code segment. And a request like below can get the same error in server side.
```
curl --location --request POST 'http://localhost:8080/ocr' \
--header 'Content-Type: text/plain' \
--data-raw '{"aaaaaaaaaaaaaa":"a'
```
So I think you should first to tell the collaborator or the client to check weather the data that the client sent is json format and second you should to schema the request param to give the 4XX http code if the data that the client sent is json format instead of 500 with an error in you server.  
Anyway this is not a problem with gunicorn
