### ISSUE TITLE
Issue connecting to mysql database.

### ISSUE THREAD

**Issue by TheTravelingJester** [benoitc/gunicorn#2795]
Hi I'm new to web hosting and learning things. I was looking to host my school project using nginx and gunicorn. My python file works and connects to database(localhost:5000) but when I try to run it from vps through gunicorn(localhost:8000) it doesn't connect.

Error:
    File "/root/myproject/database.py", line 106, in getUserInDatabaseByLogin
    cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
    AttributeError: 'NoneType' object has no attribute 'connection'

python code its referring to:

      def getUserInDatabaseByLogin(db):
      '''
      Get a user from the database
  
      **USE THIS METHOD WHEN A USER IS ATTEMPTING TO LOG IN**
  
      return the user object if the account exist in the database 
      '''
      # fetch form data
      userDetails = request.form
      username = userDetails['username']
      password = userDetails['password']
  
      # checks if user exists in the database
      cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)
      cursor.execute('SELECT * FROM accounts WHERE username = %s AND password = %s', (username, password,))
      account = cursor.fetchone()
  
      # if account exists in the database
      if account:
          if account["type"] == 'customer':
              cursor.execute('SELECT * FROM customer WHERE customer_id = %s', (str(account["id"]),))
              customer = cursor.fetchone()
              flash('Logged in successfully!', category = 'success')
              return convertUser(account, customer)
          if account["type"] == 'manager':
              cursor.execute('SELECT * FROM employee WHERE employee_id = %s', (str(account["id"]),))
              manager = cursor.fetchone()
              return convertUser(account, manager)
          if account["type"] == 'chef':
              cursor.execute('SELECT * FROM chef WHERE chef_id = %s', (str(account["id"]),))
              chef = cursor.fetchone()
              return convertUser(account, chef)
          if account["type"] == 'delivery':
              cursor.execute('SELECT * FROM delivery WHERE delivery_id = %s', (str(account["id"]),))
              delivery = cursor.fetchone()
              return convertUser(account, delivery)
  
      else:
          # account does not exist or username/password is incorrect
          flash('Username/password is incorrect.', category = 'error')
          return None

**Comment by benoitc** [comment]
you should ensure the db connection exists in the worker context. Ie not declared globally in a module.
