### ISSUE TITLE
LogRecords should not format variables into message

### ISSUE THREAD

**Issue by fdemmer** [benoitc/gunicorn#2801]
The `msg` of logging calls should be format strings and not include variables.

> msg – The event description message, possibly a format string with placeholders for variable data.

https://docs.python.org/3/library/logging.html#logrecord-objects

One example is at https://github.com/benoitc/gunicorn/blob/cf55d2cec277f220ebd605989ce78ad1bb553c46/gunicorn/workers/ggevent.py#L113

Pre-formatting variables into the `msg` prevents aggregation of logs in tools/services like sentry.

**Comment by benoitc** [comment]
I don't understand how this change is related to the issue.  How it is preventing aggregation with sentry?

**Comment by danlamanna** [comment]
> I don't understand how this change is related to the issue.  How it is preventing aggregation with sentry?

Sentry treats each error as a separate issue since it has a different message. 

+1 on this issue, I also experience it.

**Comment by fdemmer** [comment]
> Sentry treats each error as a separate issue since it has a different message.

Exactly that.

**Comment by antonpirker** [comment]
Yes. This would make investigating Gunicorn timeouts for everyone that uses Sentry way easier.

**Comment by benoitc** [comment]
low priority for me as I am not using sentry, but a patch for it would be accepted.

**Comment by fdemmer** [comment]
hiere is my pr: https://github.com/benoitc/gunicorn/pull/2802

**Comment by benoitc** [comment]
I missed that sorry. Committed. Thanks!
