### ISSUE TITLE
Gunicorn is throwing Out of Memory with max request and max requests jitter

### ISSUE THREAD

**Issue by mecatheclau** [benoitc/gunicorn#2803]
Gunicorn is throwing Out of Memory
----------------------------------

I have tried to add max request and max requests jitter but still getting Out of Memory

``exec gunicorn myproject.wsgi:application --bind unix:/webapps/run/myproject/gunicorn.sock --max-requests 500 --max-requests-jitter 50 --workers 3 --timeout 300 --user=root --group=webapps``

I have tried to check the gunicorn process ID it consumes 95% of memory out of 20GB and started in 18 hours ago
what I am doing wrong. Any help appreciated

**Comment by benoitc** [comment]
how much your application is consuming?

**Comment by benoitc** [comment]
@mecatheclau gunicorn is not consuming memory itself. What does your application?

**Comment by benoitc** [comment]
stalled issue
