### ISSUE TITLE
Gunicorn started the worker beyond my configuration

### ISSUE THREAD

**Issue by besty99** [benoitc/gunicorn#2813]
I use gunicorn to deploy flask applications through configuration files.
I set four workers in the configuration file，all configurations are
```
workers = 4
bind = '0.0.0.0:6062'
daemon = True
timeout = 120
accesslog = './gunicorn_acess.log'
errorlog = './gunicorn_error.log'
```
Then start with a shell command
`pipenv run gunicorn app:app -c gunicorn.py`

However, according to the deploy log, after starting four workers, gunicorn tried to start the fifth worker and failed.
![image](https://user-images.githubusercontent.com/47911511/172548347-2612b941-a1cf-4498-986b-3da8f470322a.png)

**Comment by benoitc** [comment]
what does your app? it seems some code is trying to fork or send a signal to gunicorn arbiter.

**Comment by benoitc** [comment]
closing as not reproduced.
