### ISSUE TITLE
Not reloading Python modules when inside k3s+docker

### ISSUE THREAD

**Issue by diogobaeder** [benoitc/gunicorn#2814]
Hi folks,

I'm not sure if this is a bug or if I'm doing something wrong, but I'm building a project where I need to run my app inside Kubernetes pods on my own computer, so I use k3s for that. However, I've set it up to reload my gunicorn instance running inside my pod, using `poll` as the reload engine (gave up using inotify, wasn't working reliably inside the pod), and, even though gunicorn says it detected file changes and is reloading the workers, they don't really seem to be reloaded, as I keep getting the same contents over and over.

To test this inside my app, which is basically a FastAPI-based API, I created an endpoint that provides me a certain JSON payload. Every time I change this payload, I see gunicorn saying it's reloading the modules, but if I hit the endpoint again I get the old payload back.

Maybe Gunicorn is caching something that I don't know? Do you guys see anything wrong in my approach?

Thanks!

**Comment by diogobaeder** [comment]
This is super odd, I put my app to run locally, on the host itself (not inside k3s or docker), and it still keeps caching the content somehow. This doesn't seem to be a feature from FastAPI, from what I can read in their docs, so maybe there's something else going on?

**Comment by benoitc** [comment]
fixed. thanks for your feedback.
