### ISSUE TITLE
Gunicorn Workers aren't used equally.

### ISSUE THREAD

**Issue by bashirmindee** [benoitc/gunicorn#2817]
After running a lot of tests with Gunicorn. I noticed that the workers aren't used in an equal manner. 
By using 8 workers and 4 threads with gthread inside of docker; and by using top, I can see the consumption of RAM and the TIME+ which indicates an unequal usage of some workers:

![image](https://user-images.githubusercontent.com/91077790/175548928-fbd0ca96-c618-4f98-9c28-a0fd3cdf7acf.png)

I want all the workers to work in paralelle as much as possible and to only use the threads inside a single process in extreme cases (i.e. when all the processes are busy doing some work). Is this already the case ? 

This [StackOverflow](https://stackoverflow.com/questions/40008387/why-isnt-work-being-distributed-across-gunicorn-workers-evenly) discusses this issue but there doesn't seem to be a clear answer to it.

Thank you

**Comment by benoitc** [comment]
late answer but this is expected. Depending on the scheduling method used in your kernel the work will be balanced differently.
