### ISSUE TITLE
participants.db not being updated

### ISSUE THREAD

**Issue by smcgrat** [benoitc/gunicorn#2818]
Hello,

Apologies if this is the wrong place for this and my internet research failed to turn up the documented answer to this.

We have a gunicorn instance running where the experimental applications seem to work but the data is not saving for some reason. The `participants.db` where I think the data is suppossed to be saved to hasn't been updated since June 17th and the application has definitely been used in the interim. On the 17th all the gunicorn processes where killed and then have restarted. I'm not sure if that is responsible. Since then this issue has manifested.

Server details
Scientific Linux release 7.9 (Nitrogen)
Kernel: 3.10.0-1160.66.1.el7.x86_64
gunicorn version: 18.0
Python 2.7.5 and Python 3.6.8 installed.

gunicorn is being run with
```
/usr/bin/python /usr/bin/gunicorn --access-logfile access-log.txt --error-logfile error-log.txt --log-file=- -c config_gunicorn.py app:app
```

`config.txt` contents
```
[AWS Access]
aws_access_key_id: <snip>
aws_secret_access_key: <snip>
[HIT Configuration]
using_sandbox: false
title: "Make Choices for Money (Safari or Chrome)“
description: "Make a series of choices."
keywords: "Psychology, Neuroscience"
question_url:  https://dawlab.cns.nyu.edu:5424/mturk 
max_assignments: 1     ; Number of turkers who can accept this HIT
HIT_lifetime: 24        ; In hours, how long the HIT will be available
reward: 5              ; In dollars
duration: 2             ; How long turkers have to complete once accepted.
US_only: true
Approve_Requirement: 95   ; What % of previous assignments have been approved.
[Database Parameters]
database_url: sqlite:///participants.db
table_name: turkdemo
[Server Parameters]
host: localhost
port: 8000
cutoff_time: 120         ; Time in minutes when we assume a subject gave up
support_IE: true       ; Whether to support Internet Explorer
logfile: app_log.txt
loglevel = 2 ; 0=DEBUG, 1=INFO, 2=WARNING, 3=ERROR, 4=CRITICAL
debug: false             ; NEVER leave this on when exposing the server to the public.
login_username: <snip>
login_pw: <snip>
[Task Parameters]
code_version: 1.0
num_conds: 1            ; Number of conditions of interest
num_counters: 1         ; Number of counterbalance alternatives
```

`config_gunicorn.py` contents
```
import multiprocessing
workers = multiprocessing.cpu_count() * 2 + 1
#import multiprocessing
workers = 1

# Gunicorn doesn't like our import of config, so we wrap it in a funciton.
def from_config_file():
    global bind, accesslog, errorlog, loglevel
    from config import config
    
    # Address to bind
    #bind = config.get("Server Parameters", "host") + ":" + config.get("Server Parameters", "port")
    
    bind = "localhost" + ":" + config.get("Server Parameters", "port")
    
    # Logging
    # I can't tell if this would be too verbose:
    #accesslog = config.get("Server Parameters", "logfile")
    errorlog = config.get("Server Parameters", "logfile")
    loglevels = ["debug", "info", "warning", "error", "critical"]
    loglevel = loglevels[config.getint("Server Parameters", "loglevel")]
    
from_config_file()

print "Running on:", bind
print "Logging to:", errorlog
```

Users can interact with the server.

The access and app logs are being updated.

The `participants.db` is not being updated.

Any help would be gratefully received.

Sean

**Comment by smcgrat** [comment]
Correction. Sorry about this. This `participants.db` is not where the session data is stored. Instead it is stored in csv files in `data` or `quitters` directories, depending on participants that complete or don't the experiments, respectively. Apologies for the error. Any advice or help would be much appreciated please.

Sean

**Comment by benoitc** [comment]
if you run multiple worker you need to ensure that they can all write to your files. You can check by running gunicorn in interactive mode.

**Comment by benoitc** [comment]
no feedback since. closing theissue.
