### ISSUE TITLE
Gunicorn keeps date until restart

### ISSUE THREAD

**Issue by moreplavec** [benoitc/gunicorn#2822]
I have simple Django code, but crucial part is:

```
yesterday = timezone.now() - timedelta(days=1)

y_start = yesterday.replace(hour=0, minute=0, second=0, microsecond=0)
y_end = yesterday.replace(hour=23, minute=59, second=59, microsecond=999999)

cheats = CheaterShort.objects.filter(datetime__range=(y_start, y_end))
```

but with Gunicorn/Nginx server running, next day this returns 0 rows (i can see data in DB). If i restart Gunicorn or run another Gunicorn instance or run django devel server, cheats are shown and contains data i see in DB. Is it this some Gunicorn issue? Or is it just wrong settings?

I have problem like this with more apps after migrating from Apache2/WSGI to Nginx/Gunicorn.

Socket file:
```
[Unit]
Description=VKCRM

[Socket]
ListenStream=/run/vkcrm.sock

[Install]
WantedBy=sockets.target
```

Service file:

```
[Unit]
Description=VKCRM daemon
Requires=vkcrm.socket
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/virtuals/crm/vkcrm
ExecStart=/var/www/virtuals/crm/bin/gunicorn --access-logfile - --workers 1 --timeout 100 --bind unix:/run/vkcrm.sock vkcrm.wsgi:application

[Install]
WantedBy=multi-user.target
```

Tried with gunicorn==20.1.0 and gunicorn==20.0.4. Thanks for replay.

**Comment by benoitc** [comment]
this looks lime this object is initialized before a worker start. or something like it. how is inializwd the app?

**Comment by moreplavec** [comment]
I followed Digital ocean tutorial, nothing more or less, something like this: https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-22-04

If you mean wsgi.py, it's default Django file in all apps, for example for this project:

```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "vkcrm.settings")

application = get_wsgi_application()
```

**Comment by moreplavec** [comment]
Any progress? I just have to run, all my servers, to restart each Gunicorn app every night. Thanks cron my apps are running in current time.

**Comment by moreplavec** [comment]
I have new VPS, Ubuntu 22, fresh install, same problem. If server is running more days, Gunicorn keeps date in date it was last rebooted or started. So all things like reports to some date aso. keeps date from start.

**Comment by benoitc** [comment]
where is set this date? is it global to the module or via a function?

**Comment by moreplavec** [comment]
In views.py i call queries with dates. All these are fixed to date gunicorn was last restarted/started. I tried few distros, still the same problem. All other things works fine. For example all day shifts like:

`today = datetime.datetime.today()`
`instance.date_stop = datetime.date.today() + datetime.timedelta(days=30)`
`display = today - datetime.timedelta(days=4)`

stays in past. When i restart gunicorn (systemctl restart gunicorn) suddenly all works in "now". I use crontab to restart each Gunicorn app every day at 2:00am, problem solved, but I think it's not right.

**Comment by jass-walia** [comment]
Just make sure, you don't use any date function as default value to python function, which would retain until reload/restart.

e.g. def test(date=datetime.datetime.today()) is wrong.

**Comment by adi-** [comment]
Same problem here...

**Comment by benoitc** [comment]
@adi- please share an example of your code and where it it is used the first time.

**Comment by adi-** [comment]
Sorry, my fault. Date works fine.

**Comment by benoitc** [comment]
@adi- thanks for the feedback

closing as not reproduced.
