### ISSUE TITLE
gunicorn + worker_class In addition to the default sync, events like gevent and eventlet cannot be used

### ISSUE THREAD

**Issue by Jerry95two7** [benoitc/gunicorn#2838]
python=3.9， gunicorn = 20.1.0，  gevent  =21.12.0
```
gunicorn -b 0.0.0.0:5000 app:app --worker-class gevent --timeout 120
```
I can only use worker-class `sync` to make the request successful. In other modes, I wait for nearly a minute to return 502 Bad Gateway, and the code does not report an error. Where is the problem? ? ?

I currently speculate that the use of gevent or eventlet is blocked, and it has not been successfully run, but it does not feel like this.

The following is running in `gevent` mode, and it has been stuck here. If it is `sync` mode, the printing information in my code will be printed anyway. So I'm guessing it's blocking, but don't know why...

```
[2022-08-01 10:12:11 +0000] [3170259] [INFO] Starting gunicorn 20.1.0
[2022-08-01 10:12:11 +0000] [3170259] [INFO] Listening at: http://0.0.0.0:5000 (3170259)
[2022-08-01 10:12:11 +0000] [3170259] [INFO] Using worker: gevent
[2022-08-01 10:12:11 +0000] [3170260] [INFO] Booting worker with pid: 3170260
```

Except for `sync` mode, every time I quit (CTRL+C) it takes a long time to exit. Why?

Above is my first time using `gunicorn`

**Comment by benoitc** [comment]
without showing the code it ill be hard to tell. Can you share a snippet?

**Comment by Jerry95two7** [comment]
Hmm... I forgot how to solve it. This question is my own fault. sry.
