### ISSUE TITLE
Replace the use of `pkg_resources` with `importlib.metadata`

### ISSUE THREAD

**Issue by webknjaz** [benoitc/gunicorn#2840]
Hello, using `pkg_resources` in `gunicorn.util` causes a deprecation warning to be issued down the stack (it's coming from `sre_constants` imported py the vendored `pyparsing`).

The use of `pkg_resources` has been heavily discouraged over the past years and nowadays the recommended alternative exists. It's called `importlib.metadata` and it's present in the modern CPython stdlib. For older interpreter versions, there's also an `importlib_metadata` backport packaged and published separately to PyPI. It can be used as a fallback.

https://importlib-metadata.readthedocs.io/en/latest/api.html#importlib_metadata.entry_points

**Comment by Htermotto** [comment]
Any interest in getting this merged?

**Comment by tilgovi** [comment]
I believe this was closed by #2963.
