### ISSUE TITLE
worker failed to boot

### ISSUE THREAD

**Issue by manlulu07** [benoitc/gunicorn#2857]
![Screenshot 2022-08-31 120612](https://user-images.githubusercontent.com/103286494/187654387-8c62fddf-8b1d-4308-af68-7e81c1497e2b.png)

can someone please help me with this

**Comment by benoitc** [comment]
it's late. Check the gevent version you're running. If the error still happen please reopen a new ticket with all the informations and possibly a way to reproduce it.
