### ISSUE TITLE
Read-only filesystem

### ISSUE THREAD

**Issue by dr1v3** [benoitc/gunicorn#2859]
Is there any possibility to run Gunicorn in read-only filesystem? I'm trying to launch Gunicorn in Fargate with r/o filesystem and got errors about failed writes to /tmp folder.

**Comment by benoitc** [comment]
to make it workd you will have to mount the temporary folder in memory. You don't need a large folder for it.

**Comment by dr1v3** [comment]
> you may have to mount the temporary folder in memory
Unfortunately this is not possible in AWS Fargate, tmpfs is disabled

> precompile python filed and start on the pyc.
Thanks, I'll try this solution

**Comment by benoitc** [comment]
for aws fargagate maybe this is still working ?
https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-adds-support-for-shm-size-and-tmpfs-parameters/

**Comment by dr1v3** [comment]
This is related to EC2 launch type, not Fargate

**Comment by benoitc** [comment]
I don't really see the point to make a file system as ready only when you control the container but you need to have a temporary place where you put files. Maybe you can have a small volume for it.

**Comment by dr1v3** [comment]
Read-only filesystem is some kind of business requirement in my case, may be someone will try to launch Gunicorn on Raspberry Pi with r\o slow flash storage or something like this. Anyway I solved this problem with EFS mounted volume to /tmp.

**Comment by jpf18** [comment]
Being in the same boat as dr1v3, I added the following to the Dockerfile of the image that runs Gunicorn:
<code>VOLUME ["/tmp"]</code>
Running gunicorn==20.1.0. Without further configuration, Gunicorn picked up the volume for the location of temporary files .

**Comment by tilgovi** [comment]
Sounds like there are workarounds. I'll close.
