### ISSUE TITLE
why gthread worker connections counter "self.nr_conns" doesn't need a lock ?

### ISSUE THREAD

**Issue by flowell** [benoitc/gunicorn#2861]
## in gunicorn.workers.gthread.py

In order to avoid race condition, ```self.nr_conns -= 1```  need a lock for protection or self.nr_conns need to be an automic integer? 
```python
...
    fs.add_done_callback(self.finish_request) # this mean "finish_request" will be execute in main thread or child thread?
...

def finish_request(self, fs):
    ...
    self.nr_conns -= 1 # race condition?
    ....
```

## related issue
#2041

**Comment by benoitc** [comment]
I'm sorry, but did you noticed any race conditions?

**Comment by benoitc** [comment]
answered in related issue.
