### ISSUE TITLE
Starting gunicorn from python code is not working

### ISSUE THREAD

**Issue by jinyeng** [benoitc/gunicorn#2866]
I have an external python process that must start gunicorn for a Django application located in a subfolder. I have tried following and its not working.

1) python subprocess with command "gunicorn -c web/api/conf/gunicorn_config.py web/api/api.wsgi"
2) https://docs.gunicorn.org/en/stable/custom.html but I am getting import gunicorn.app.base ModuleNotFoundError: No module named 'gunicorn'

Would appreciate any help solving this.

**Comment by benoitc** [comment]
you need to set the correct PYTHONPATH. There is a setting for it.
