### ISSUE TITLE
Will CPUs interfere with each other if we spawn several workers (with multithreaded pytorch)?

### ISSUE THREAD

**Issue by lyriccoder** [benoitc/gunicorn#2873]
Suppose, I have a pytorch model.  I have 24 CPUs.  I have set `torch.set_num_threads(16)` for torch.

Suppose, I run 2 workers for gunicorn and will have 2 parallel requests (each one will run model prediction). Will those CPUs interfere with each other? I mean if we spawn a worker (process) and use `torch.set_num_threads(16)`, will those cpus be used separately, not interfering with each other?

If they will interfere with each other, can I make an isolation with some argument for gunicorn? E.g., the first worker must use ONLY first 4 CPUs, and the other worker must use ONLY other 4 CPUs?

**Comment by benoitc** [comment]
gunicorn workers are isolated form each other's. I am not sure it is a good idea to start torch in each workers. Maybe this can be started as a separate application/worker you can discuss with ? Which worker model are you using?

**Comment by lyriccoder** [comment]
I am using Roberta. I tried to set 16 threads, it gave me the best performance for a single prediction. Also, I tried to use 1 or 2 workers with 4, 8, 16 CPU for each worker in the experiment. I noticed that I had the best throughput for 8 CPUs, despite the fact that I have 24 CPUs. 

Also, 16 threads was the worst case with 2 workers. That's why I thought that threads were not isolated.

**Comment by benoitc** [comment]
workers are system processes. When you start gunicorn in without the preload option, they are isolated from each others. I iwll provide soon a way to run your AI Model with your web in a simple way.
