### ISSUE TITLE
Fork before preload

### ISSUE THREAD

**Issue by ikonst** [benoitc/gunicorn#2890]
Right now the arbiter forks once when creating a worker, which then proceeds to load the WSGI app (which causes additional modules to be loaded and possible side-effects).

The `preload_app` feature is appealing, but the undesirable effect is that it "pollutes" the arbiter.

Would it be a reasonable idea, in the case of `preload_app`, to fork once to create a"stem cell" process, and then control the "stem cell" process (e.g. with a signal) to fork into workers?

**Comment by benoitc** [comment]
Can you elaborate ? I think you would lost the main interest in such case which would be preloading and sharing modules across the workers... What is your goal?

**Comment by ikonst** [comment]
I do want the preload to happen just once, but it's concerning that a lot goes on in the loading of a large web service, and that might affect the arbiter. A way to think about it: how would you implement it if the arbiter was written in another language?

**Comment by benoitc** [comment]
in another language i would not have to take care of this ;) anyway i don't this is the right solution. I will aharr soon a new feature for such car.
