### ISSUE TITLE
[Clarification] Datadog's Guarddog output on gunicorn 20.1.0 

### ISSUE THREAD

**Issue by maciejstromich** [benoitc/gunicorn#2898]
Hey team,

Datadog's new supply chain analysis tool called guarddog reports: 

```
Found 1 potentially malicious indicators in gunicorn version 20.1.0

potentially_compromised_email_domain: The domain name of the maintainer's email address was re-registered after the latest release of this package. This can be an indicator that this is a custom domain that expired, and was leveraged by an attacker to compromise the package owner's PyPi account.
```
Based on https://github.com/benoitc/gunicorn/blob/master/setup.py#L95 I see that the domain in fact was re-registered after latest release of the package

```
whois e-engura.com
[...]
Domain Name: E-ENGURA.COM
[...]
Updated Date: 2022-07-11T21:12:18Z
Creation Date: 2022-07-11T21:12:15Z
```

Is it anything to be concerned about?

**Comment by benoitc** [comment]
Thanks for the report. For the record, this email wasn't use since awhile for the project even in Pypi so it has never been an issue. I fixed it in setup.py in 008d81d0227cbc324f4e0814011e5d3cc4ec47e7 to reflect the correct email.
