### ISSUE TITLE
logger_class req body is empty

### ISSUE THREAD

**Issue by unihon** [benoitc/gunicorn#2900]
I make gunicorn custom logger, and I create a POST request with data, but I can't get any thing with request's body. 

```python
class CustomLogger(glogging.Logger):
    """Custom logger for Gunicorn log messages."""
    def access(self, resp, req, environ, request_time):
        print(req.body.read())
        print(req.body.readline())
        print(req.body.readlines())
```
all output is `b''`

How to get the request's body on gunicorn logger

**Comment by rafmsou** [comment]
I was able to see the data using `req.body.read()` for json body but not for multi-part/form-data body.

**Comment by benoitc** [comment]
you need to storw it in gunicotn process/threwd and discard it when req is finished. tothersisr it is not kept in memory.
