### ISSUE TITLE
one workers and one threads, worker_class is "sync", but why are more than 25 gunicorn processes started？

### ISSUE THREAD

**Issue by DAAworld** [benoitc/gunicorn#2902]
I use htop in terminal, and find more than 25 guncorn process started. Do they consume more memory？
![image](https://user-images.githubusercontent.com/46104689/207547270-60a670e3-b836-45e5-a371-f8149a867dc2.png)

**Comment by benoitc** [comment]
Can you share your command line or config?

**Comment by benoitc** [comment]
closing issue, no answer from the reporter to the requests.
