### ISSUE TITLE
gUnicorn starts processing same request with different workers if processing is long

### ISSUE THREAD

**Issue by evil-shrike** [benoitc/gunicorn#2905]
I have an app on Google AppEngine (Python/std) running on gUnicorn and Flask. I've found that gUnicorn processes same request several times, which completely breaks my app and definitely is not something that anyone can expect.
Details are below.

I have a server controller:
```
@app.route("/api/campaign/generate", methods=["GET"])
def campaign_generate():
  logging.info('Entering campaign_generate');
  # some very long processing here
```

The controller is called by clicking a button from the UI app. I checked the network in DevTools in the browser that only one request fires. And I can see that one request in server logs.

In my app.yaml I have:
```
entrypoint: gunicorn -b :$PORT server.server:app --timeout 0 --workers 2
```
So it's 2 workers. But I was sure those workers shouldn't process the same request, but concurrent ones.

The the processing starts and the client is blocked waiting for a response.
Timing is following:
13:00:59 Entering campaign_generate
..skipped
13:39:13 Starting generating zip-archive (that's something that takes a while)
14:25:49 Entering campaign_generate

So, at 14:25, 1:25 after a request came another processing of the same request started!
And now there're two request processings in parallel. 
Needless to say that this increase memory pressure and often leads to a failure because it's not suppose to happen

And when the first "thread" finished (14:29:28 in our example) its processing, its request isn't being returned to the client. It looks like gUnicorn simple abandoned the first request. And client has to wait till the second thread finishes processing. And it can never ends. Then gUnicorn spins another process when the second took 'too long'.

What can I do with this?

**Comment by evil-shrike** [comment]
It worth mentioned specifically that `--timeout` set to 0, so gunicorn shouldn't kill a worker at all (it was first thing I though is happening)

**Comment by benoitc** [comment]
There are different points in your ticket.

1) timeout set to 0 mean timeout is 0. If you want to increase the timeout , it should be increased in the limit of an integer. It's advised to keep a timeout.
2) 2 workers means the request will be balanced between  2 workers. Gunicorn itself don't retry a request but accept any request sent to it until it can't. You don't say which kind of worker  is used but I assume you're using a threaded or async worker?  in such case more requests can land in the same worker depending on the kernel scheduler.  ie. this depends on the system and how fast a worker makes its shared socket available so the request is dispatched from the backlog.

**Comment by evil-shrike** [comment]
>timeout set to 0 mean timeout is 0. If you want to increase the timeout , it should be increased in the limit of an integer. It's advised to keep a timeout.

in docs it's [stated](https://docs.gunicorn.org/en/stable/settings.html#timeout) that:
> Value is a positive number or 0. Setting it to 0 has the effect of infinite timeouts by disabling timeouts for all workers entirely.

isn't it the case?

>. You don't say which kind of worker is used but I assume you're using a threaded or async worker? 

well, I provided the command that used to start gunicorn, it doesn't specify a worker type, so according to [the doc]('sync') it should be 'sync'

**Comment by danpiovanelli** [comment]
I'm having the exact same problem... Suppose I have 3 workers, 1001, 1002 and 1003, and worker 1001 is executing some long code after receiving request X. After 5 minutes of worker 1001 running request 1 without completing the route method (it would take about 10 minutes to finish it), worker 1002 runs the code in the route method again, even if there isn't another request call. 

That's my service command: "gunicorn --workers 3 --timeout 600 --bind unix:project.sock -m 007 wsgi:app"

For some reason, it's not observing the 10min timeout in the command. I already tested if with timeout 0, which is also not working...

Those anyone  have any idea how to solve this problem?

Thank you!

**Comment by GdeGordon** [comment]
For anyone stumbling upon it, it's probably your nginx server retrying GET requests after whatever proxy_read_timeout is set to

**Comment by tilgovi** [comment]
Gunicorn will not do this because it cannot accept the same socket on multiple workers. This issue is likely a proxy in front of Gunicorn retrying the request.
