### ISSUE TITLE
Gunicorn threads are not being killed, ends up throwing "Can't start new thread" error.  

### ISSUE THREAD

**Issue by OceanRahan** [benoitc/gunicorn#2906]
--access-logfile - \
          --workers 3 \
          --bind unix:/run/staging.sock:7000 \
          --threads 5 \
          --keep-alive 5 \
          --max-requests 5 \
          --max-requests-jitter 4 \
          --graceful-timeout 15 \
          medai_django_boilerplate.wsgi:application
          
          This is my service file.
          I want the threads to be killed after finishing a request on its own.

**Comment by benoitc** [comment]
stalled. The only way I think you can do it is to use a custom worker to exit it once the request is done.
