### ISSUE TITLE
Gunicorn freezing: Stops listening to requests

### ISSUE THREAD

**Issue by kamaledge** [benoitc/gunicorn#2914]
I stumbled across an issue which lead to **gunicorn** freezing in the production environment.

Description: The application is a flask microservice with **flask restplus**, the application server being guncorn. There is no reverse proxy/load balancer like nginx as such.

The application is catering to **requests by another application(rest calls)** or by swagger/postman, using explicit port and endpoints.

Sometimes(weekly or so), **gunicorn receives some junk** request at the port with wrong methods/endpoints/protocols, and after being flooded for a while, it stops listening and just **becomes non-responsive**, not crashing though. It needs to be restarted to work again. All the request sent for period in between is not catered.

The gunicorn here is **multi-worker** and **multi-threaded** and error/access logs show no error even in **debug mode** when it **freezes**, it just **not register anything** after that.

Can someone please suggest on how to tackle/resolve this?

I already tried to access logs in debug mode as well. Searched across the community for solutions, but to no avail.

Below is the part of config:

  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 5
  worker_class: sync
  threads: 4
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1200
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']

**Comment by benoitc** [comment]
any example of app to share? or at least the error and access logs? you can share to me in private if needed.

**Comment by javiertejero** [comment]
I wonder if this was solved after #2917 @kamaledge

**Comment by kamaledge** [comment]
Hi,

This was resolved after some digging. Seems the gunicorn logs in debug mode
showed some unusual records, pointing to blocking of requests from sone
unknown ip. It was found out that it was Crowdstrike scanner doing a random
scan across the network and was sending junk requests to gunicorn, and
eventually shutting it down, assuming it as malicious software.
It was resolved once gunicorn was taken out of the scope of the scanner.

Regards and Thanks,
Kamal Nath Tiwari
