### ISSUE TITLE
How to dispose of shared resources in --preload mode

### ISSUE THREAD

**Issue by vincent-grosbois** [benoitc/gunicorn#2925]
Hello !

I'm using gunicorn to call fastapi server with --preload mode.

This works fine to share static data (as the processes are forked once the shared data is loaded in memory).
However, it there a way from my main "shared" code to register an event handler that will be called when the gunicorn process is stopping ?

Here I'm facing the following situation that I can't solve:

- in the before-fork code, I'm creating a [Manager](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Manager) object 
- my fastapi workers that are created post-fork get automatically the instance of this manager, so they can communicate with it in cross-process way -> this works fine
- I would like to fill this manager with data periodically (like every 1 minute)
- From the before-fork code, I just spawn a thread that will periodically update the manager by connecting to outside source. This thread is only existing in the before-fork code (threads aren't forked) -> this works fine
- **the issue**: when gunicorn is attempting to stop (ctrl+C) , I have no way to tell my background thread to stop (no signal to attach to it seems). So gunicorn is hanging forever. I think that python is calling `join()`  on my background thread, which makes everything stuck as indeed it's looping forever

Is there a way to handle this ? It seems that I can't catch either SIGINT/SIGTERM

thanks !

**Comment by vincent-grosbois** [comment]
Although.... I just realized that this simply works if I use daemon threads :D 

But my question is still relevant IMO : is there a way to catch gunicorn signals to do resource clean-up at the end?

**Comment by benoitc** [comment]
you can use the hooks for it: https://docs.gunicorn.org/en/stable/settings.html#server-hooks

**Comment by vincent-grosbois** [comment]
Thanks ! it seems that solves it
