### ISSUE TITLE
proc_name not being assigned to the server process

### ISSUE THREAD

**Issue by tamruta** [benoitc/gunicorn#2932]
Hi, I am trying to run a server that provides a custom proc name but it is not being used while starting gunicorn or its workers. Here is a snippet of the log file 

```
Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['localhost:22362']
  backlog: 2048
  workers: 17
  worker_class: gevent
  threads: 1
  worker_connections: 1000
  pidfile: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /dev/null
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: server.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  proc_name: server_054
  default_proc_name: gunicorn
[68693] [INFO] Starting gunicorn 20.1.0
[68693] [DEBUG] Arbiter booted
[68693] [INFO] Listening at: http://127.0.0.1:22362 (68693)
[68693] [INFO] Using worker: gevent
[68694] [INFO] Booting worker with pid: 68694
[68695] [INFO] Booting worker with pid: 68695
[68696] [INFO] Booting worker with pid: 68696
[68697] [INFO] Booting worker with pid: 68697
```
``ps aux | grep server_054`` gives no results. The app works (I can open the website) and the process 68693 is running as the script used to start gunicorn [``python server_script.py``]. 

```
amruta      68693    S+    2:14PM   /bin/python /server_script.py

```

**Comment by jacob-lee** [comment]
We've determined that this appears to be an issue with using conda environment and pip install of setproctitle. I believe it can be closed.

**Comment by jacob-lee** [comment]
Yes, and possibly version of Mac. I'll link to the full git issue discussion I raised at the github repo for setproctitle

https://github.com/dvarrazzo/py-setproctitle/issues/128

**Comment by jacob-lee** [comment]
> I'm using conda environment and pip install of setproctitle and it works fine, so I guess it may relate to the sofeware version?

Yes, and possibly version of Mac. I'll link to the full git issue discussion I raised at the github repo for setproctitle

https://github.com/dvarrazzo/py-setproctitle/issues/128

**Comment by benoitc** [comment]
i am closing the issue as it's lekyly an issue wiht conda environement. Feel free to reopen it if needed.
