### ISSUE TITLE
kill -9 kills parent process, child process still are alive and memory increases suddenly after new reqeust comes in 

### ISSUE THREAD

**Issue by lian0090** [benoitc/gunicorn#2939]
I am uisng gunicorn to serve a flask application wich has around 100 Gb data.  I started gunicorn with --preload mode so memory are shared among parent and subprocess.  However, when i use kill -9 kill parent process, the child processes are still alive until new request comes in . Even worse, when the new request comes in, the momory consumption suddently increase a lot and all the free memory on the machine are gone which causes the machine to restart. 

why would this happen and what should i do to avoid this huge memory increase by "kill -9 parent process"?

I am using gunicorn version 19.9.0

**Comment by PanQiWei** [comment]
you should'nt use kill -9 to kill the master process, because this will kill the master immediately and left no time to shutdown the chidren, instead using `kill [master_proc_id]`  or `pkill [master_proc_name]` should work fine in most cases.

**Comment by lian0090** [comment]
actually, this sudden increase in memory happends with kill SIGTERM and kill SIGQUIT.  This happends to be a python GC problem.

This post has a similar problem 
https://www.cnblogs.com/haolujun/p/9778939.html

here is how i solved this problem:
creat a user defined pre_fork function that has gc.freeze(), the problem has been solved

**Comment by benoitc** [comment]
do you reqlly nerd to start with the preload mode?

**Comment by benoitc** [comment]
actually this idea of using gz.freeze may be interresting. I will keep a note to test this change in gunicorn. I"m closing this ticket in between.
