### ISSUE TITLE
Python 3.11 support? 

### ISSUE THREAD

**Issue by frosk1** [benoitc/gunicorn#2941]
Hey when is python 3.11 support planned?

**Comment by guiklimek** [comment]
Yes please + eventlet update :pray:

**Comment by bolinocroustibat** [comment]
Same here?

**Comment by davidism** [comment]
This works fine on Python 3.11, are you encountering a specific issue? If so, you should report that issue.

**Comment by frosk1** [comment]
@davidism
https://stackoverflow.com/questions/74628159/gunicorn-worker-gevent-failed-to-boot-using-python-3-11

**Comment by davidism** [comment]
That's a link to a Q&A site, not a specific bug report on the issue tracker.

**Comment by frosk1** [comment]
This issue is not meant to be a bug report. Since the readme.md of this github repo does not show python 3.11 as supported (it shows python 3.9) the question might arise. And I guess the users should expect a suitable answer to this question.

**Comment by bolinocroustibat** [comment]
Should we really post an issue related to Python 3.11 even though Python 3.11 is not officially supported?

**Comment by AyushAgnihotri2025** [comment]
Yes please release eventlet update too🙏

**Comment by slocke716** [comment]
Looks like cutting a release is incredibly easy https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes .

Maintainers:
@benoitc 
@sirkonst
@tilgovi 
@berkerpeksag 
@jamadden 
@javabrett 

Could someone please cut a release?

**Comment by benoitc** [comment]
for me this looks supported ;) https://github.com/benoitc/gunicorn/blob/master/tox.ini#L2  release is landing soon. Check https://github.com/benoitc/gunicorn/milestone/20  about the progress.

**Comment by si14** [comment]
@benoitc do you think 3.12 might also happen at the same time?
