### ISSUE TITLE
Why does nginx have hardcoded external DNS resolver?

### ISSUE THREAD

**Issue by osmaa** [benoitc/gunicorn#2942]
It took me longer than I care to admit to understand that the proxy timed out because it was trying to resolve addresses using 

`resolver 9.9.9.9 149.112.112.112 ipv6=off`

while my environment was firewalled to the max, and external DNS was not among permitted services. Regular DNS was of course working just fine, because it was accessing a network-local resolver..

Opening the firewall for UDP/53 and TCP/53 of course worked around this, but why would the local resolver be bypassed?

**Comment by osmaa** [comment]
my bad, inadvertently in wrong project

**Comment by benoitc** [comment]
np :)
