### ISSUE TITLE
PyPI wheel does not match the git tagged version

### ISSUE THREAD

**Issue by ret2libc** [benoitc/gunicorn#2945]
Latest PyPI wheel (https://pypi.org/project/gunicorn/20.1.0/) does not match the tagged version https://github.com/benoitc/gunicorn/commit/61ccfd6c38d477a908e0f376757bbb884438053a / https://github.com/benoitc/gunicorn/tree/20.1.0 .

For example, at https://github.com/benoitc/gunicorn/blob/20.1.0/gunicorn/config.py#L109 you see `"threads"`, but in the wheel you download from PyPI you see `"gthread"`. Apparently these two commits are in the PyPI version, but not in the git tagged version:
- https://github.com/benoitc/gunicorn/commit/b83448bfb42184f43adf155f86bcd2a570a1139d
- https://github.com/benoitc/gunicorn/commit/fb05e333776348651d1b2d759a5857969cb2f476

Would it be possible to fix this somehow?

**Comment by benoitc** [comment]
later versions should be OK. thanks for the feedback anyway :)
