### ISSUE TITLE
Gunicorn freezes intermittently

### ISSUE THREAD

**Issue by alcher-dwm** [benoitc/gunicorn#2951]
Hi! I have a Django project served via gunicorn. Unfortunately gunicorn freezes intermittently, sometimes after a few days of running, sometimes within hours of restarting. The weird thing is that I use the same configuration on 4 of my servers, all running **different code**, and they all experience the **outage at the same time**.

The following are my config files:

```
[Unit]
Description=Gunicorn Socket

[Socket]
ListenStream=/run/gunicorn.sock

[Install]
WantedBy=sockets.target
```

```
[Unit]
Description=Gunicorn Daemon
Requires=gunicorn.socket
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/opt/app_repo
Restart=always
ExecStart=/opt/app_repo/venv/bin/gunicorn \
          --access-logfile /opt/app_repo/gunicorn.access.log \
          --error-logfile /opt/app_repo/gunicorn.error.log \
          --timeout 1000 \
          --workers 9 \
          --bind unix:/run/gunicorn.sock \
          --log-level DEBUG \
          --capture-output \
          app_repo.wsgi:application

[Install]
WantedBy=multi-user.target
```

... I was able to confirm the Gunicorn freezing by running the following commands:

```console
$ systemctl status caddy # -> up and running, curl-ing to the website's URL without a slash will return a Caddy redirect to its slashed version
$ systemctl status gunicorn # -> up and running as well
$ curl --unix-socket /run/gunicorn.sock http:// # this hangs between 2-45 minutes, in which at this point the server is responsive again
```

Versions:

```
gunicorn==19.9.0
Django==2.2.3
```

... note that I also tried updating to the latest gunicorn version, but I had the same issue so I reverted back. Things that I also tried:

1. Daily scheduled reboot
2. Testing both nginx and caddy as the reverse proxy
3. Checking for oom errors (`dmesg -T | egrep -i 'memory'`, `dmesg -T | egrep -i 'oom'`) in which I didn't find anything gunicon related.

Would greatly appreciate any input. Please let me know what/how I can provide more information. Thanks!

**Comment by benoitc** [comment]
What does your application ? Any dependencies or example to share?

**Comment by tilgovi** [comment]
No followup. Closing.
