### ISSUE TITLE
gunicorn BaseApplication with tensorflow.keras terminated due to signal 11

### ISSUE THREAD

**Issue by pvardanis** [benoitc/gunicorn#2954]
Hi,

I've implemented a custom `BaseApplication` that takes a Flask app and runs with the following options:
```
{
            "bind": "127.0.0.1:5001",
            "workers": 1,
}
```

My custom application looks like this (taken exactly as is from the docs):

```
class GunicornApplication(BaseApplication):
    """This class implements a wrapper for a Flask
    app in order to be served with Gunicorn."""

    # pylint: disable=W0223

    def __init__(
        self, app: Optional[Flask], options: Optional[dict] = None
    ) -> None:
        """Initialize the class with a Flask app.

        :param app: Flask app
        :param options: Dictionary with Gunicorn options
        """
        self.options = options or {}
        self.application = app
        super().__init__()

    def load_config(self) -> None:
        """Loads the configuration for Gunicorn."""
        config = {
            key: value
            for key, value in iteritems(self.options)
            if key in self.cfg.settings and value is not None
        }

        for key, value in iteritems(config):
            self.cfg.set(key.lower(), value)

    def load(self) -> Optional[Flask]:
        """Getter for the Flask app."""
        return self.application
```
I run the server via the `run()` method.

In my Flask app I have a tensorflow model and within the endpoints the `model.predict()` method is called but the worker exits with the following error: `[WARNING] Worker with pid 14776 was terminated due to signal 11`.

However, the same flask app runs just fine with werkzeug in development mode. I'm wondering, could this be due to gunicorn using many workers?

I'm running this under `gunicorn=20.1.0`, `mlflow=1.30.0`, `tensorflow=2.8.0` on a `M1` processor.

Any help would be much appreciated.

**Comment by pvardanis** [comment]
Update: I've managed to make it work only by using `gevent` as a standalone like this:

```
from gevent.pywsgi import WSGIServer

wsgi_server = WSGIServer(
            ("127.0.0.1", 8000), application=self._flask_app
        )
wsgi_server.serve_forever()
```

However, using `gevent` with `gunicorn` is still leading to the same error.

**Comment by tilgovi** [comment]
It's possible that it's not safe to load your application before workers fork. Does it work if you defer the import of your Flask app until the `load` method?

**Comment by benoitc** [comment]
@pvardanis ?

**Comment by tilgovi** [comment]
No response for a while. Closing.
