### ISSUE TITLE
exec /user/local/bin/gunicorn exec format error

### ISSUE THREAD

**Issue by tkapuria** [benoitc/gunicorn#2968]
Dear Altruists,

I'm trying to create a docker image locally and whenever I push the code into the gcr, in gke container logs I can see the following error message " exec /user/local/bin/gunicorn exec format error" . 

If I run "which gunicorn" command on my mac terminal, it shows "/Users/taposhkumar/Desktop/project/Manpower_dev/planner/venv_dev/bin/GUNICORN"

Whats need to be done to solve the issue? Am I need to install it in /user/local/bin/gunicorn...if so what are the steps need to be followed? 

Thanks

**Comment by benoitc** [comment]
answered
