### ISSUE TITLE
How to get request headers in logs ?

### ISSUE THREAD

**Issue by sboudouk** [benoitc/gunicorn#2971]
Hi.

I want to get the request headers in my logs, but there's no documentation on how to do this with a `.ini` file.

```
    [loggers]
    keys=root, gunicorn.error, gunicorn.access
    
    [handlers]
    keys=console
    
    [formatters]
    keys=generic
    
    [logger_root]
    level=INFO
    handlers=console
    
    [logger_gunicorn.error]
    level=INFO
    handlers=console
    propagate=1
    qualname=gunicorn.error
    
    [logger_gunicorn.access]
    level=INFO
    handlers=console
    propagate=0
    qualname=gunicorn.access
    
    [handler_console]
    class=StreamHandler
    formatter=generic
    args=(sys.stdout, )
    
    [formatter_generic]
    format= [%(asctime)s] [%(process)d] [%(name)s] XXX %(funcName)s XXX [%(levelname)s] %(message)s
    datefmt=%Y-%m-%d %H:%M:%S
    red=
    class=logging.Formatter
```

Here is my log configuration right now. 

Any indication on how to include the header ? (already tried with the syntax presented in gunicorn acces_log_format documentation but it doesn't seems to work)

**Comment by benoitc** [comment]
@sboudouk what did you try ? ntomally including the header name between `{...}` is notmally working.

**Comment by ashukla411** [comment]
Did you try it with the same format as [here](https://docs.gunicorn.org/en/stable/settings.html#access-log-format)? Something like `{header}i` for `[access_log_format]` or inside your ini file `access_log_format = "{header}i"`

**Comment by jrg091** [comment]
I've been trying to do something similar but I may not getting how to actually doing using this config file, some of the thing I tried:
* Adding a `access_log_format` or similar property in the formatter 
* Adding it in the `format` string in the `formatter_generic` section in a file identical to the one shared by sboudouk 
```
[formatter_generic]
format=%(asctime)s [%(process)d] [%(levelname)s] %({request-id}i)s %(message)s
```


I only got a change in the second case, but the change I'm seeing is getting an error like the following one:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 440, in format
    return self._format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 436, in _format
    return self._fmt % record.__dict__
KeyError: '{request-id}i'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 671, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 640, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 442, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: '{request-id}i'
Call stack:
...
Message: '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
Arguments: {'h': '127.0.0.1', 'l': '-', 'u': '-', 't': '[21/Jun/2023:12:34:44 +0000]', 'r': 'GET /_heartbeat HTTP/1.1', ... '{request-id}i': '1b8858c7-1104-4935-a49b-8993aef30d9a', ..., '{server_port}e': '8000', '{path_info}e': '/_heartbeat', '{script_name}e': '', '{werkzeug.request}e': None}
```


I'm able to make the change using the `--access-logformat` flag in the CLI and see the change in the access log but if possible I would like to have the configuration in a single place.

**Comment by tilgovi** [comment]
This is possible, but gunicorn calls `info(<access format>, tokens)`, rather than passing the tokens in the `extra` keyword argument. As such, the tokens are only available through the `args` attribute, and indexing into that requires switching the style of the formatter to an interpolation style that supports that syntax.

For example, this will log just the user agent:

```ini
[formatter_access]
format={args[{user-agent}i]}
class=logging.Formatter
style={
```

You'll want to use a different handler for `gunicorn.access` and `gunicorn.error`, though, so you can specify a different formatter for each.
