### ISSUE TITLE
gunicorn + gevent detect blocked event loop?

### ISSUE THREAD

**Issue by Chris-Leeworthy** [benoitc/gunicorn#2975]
Please can someone tell me how to activate the `gevent` monitoring thread from inside an app using Flask, Gunicorn and Gevent?

We are running the API containers in AWS ECS Fargate.  Each container runs the API with 4 gevent workers.

Every so often one of the containers will stop responding and eventually be killed.  I think this is because something is blocking the event loop but (so far) I can't prove it.

Looking at `gevent` documentation it seems I should be able to enable a monitor thread to detect a blocked event loop and specify a timeout after which it should report any blocking greenlets.

I've managed to get some sample code using `gevent` to work using the code found in the link below but I don't know how to do this with our app which doesn't  appear to use `gevent` directly.

https://stackoverflow.com/questions/13146206/gevent-debug-spinning-thread

**Comment by miaokela** [comment]
Was the monkey patch neglected in the program?

**Comment by Chris-Leeworthy** [comment]
@miaokela Thanks for getting in touch.

My understanding is that if we use gunicorn and set the worker type to `gevent` then it sets all of that stuff up for us and we don't need to manually run the monkey patch process.  Perhaps I have that wrong?

Also I think our software would fail all of the time if the monkey patch hadn't happened, but that is not the case.  The API will run happily for days and then suddenly have the problem.  That is why I suspect something may be blocking the event loop.

**Comment by benoitc** [comment]
@Chris-Leeworthy monkey patch is done at *worker* level when the gevent worker is used. However if you do some blocking task inside your request  then you will need to use the geevnt API for it. Either sleeping between tasks or such things. 

To enable a gevet task at the very beginning you can use the `post_worker_init` hook.

 If for some reason you are using preload you can also monkey patch at that level (not supported) and start any thread there.

**Comment by Chris-Leeworthy** [comment]
@benoitc Thanks.  I finally managed to figure out what was happening and gunicorn is not the problem but I'll put the info here in case it's useful to others.

Our API service uses the `psycopg2` library to provide access to our Postgres database backend.

It turns out that `psycopg2` is not compatible with the pseudo multitasking provided by `gevent` and it's possible to lock the event loop.
The fix is to use another tool called `psycogreen` (made by the same team who make `psycopg2`) to patch `psycopg2` calls and make them co-operate with `gevent` properly.
