### ISSUE TITLE
pidfile write to execution dir prevents setting K8s readOnlyRootFilesystem=true

### ISSUE THREAD

**Issue by AmoghSInamdar** [benoitc/gunicorn#2976]
[Gunicorn writes its pidfile to the program execution directory](https://github.com/benoitc/gunicorn/blob/master/gunicorn/pidfile.py#L33)

Due to this, Kubernetes cannot be configured with `securityContext.readOnlyRootFilesystem=true`. Mounting a volume to the execution directory is not an option as it interferes with program execution. Having the root fs be read-only is a security best practice and a requirement at my company.

Potential remedies are to make the pidfile write target configurable, or to write to `/tmp` instead of this directory.

**Comment by benoitc** [comment]
@AmoghSInamdar  You can already  set the directory using this setting : `https://docs.gunicorn.org/en/stable/settings.html#pidfile`

This should fix your issue .

**Comment by AmoghSInamdar** [comment]
Thanks for the clarification!
