### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kloczek** [benoitc/gunicorn#2987]
https://github.com/benoitc/gunicorn/compare/20.1.0...master shows +120 commits since last release. +1.5y ago.
Do you have any plans to flush all those commits and release new veesion soon? 🤔

**Comment by mattwang44** [comment]
Yes, there would be a new release soon, [according to the maintainer](https://github.com/benoitc/gunicorn/issues/2967#issuecomment-1537432939).

**Comment by benoitc** [comment]
Hi, watch https://github.com/benoitc/gunicorn/milestone/20 . This will land this week.

**Comment by kloczek** [comment]
Thank you 👍
