### ISSUE TITLE
When new version of gunicorn will release.

### ISSUE THREAD

**Issue by JugeshHM** [benoitc/gunicorn#2988]
We are actively using gunicorn in our python-flask application. The latest gunicorn 20.1.0 version was released on Mar 27, 2021.
Can you please tell me is there any plan of releasing the new version of gunicorn in near future? 
TIA

**Comment by benoitc** [comment]
already answered. watch the 21.0 milestone https://github.com/benoitc/gunicorn/issues?q=is%3Aopen+is%3Aissue+milestone%3A21.0 for any progress.

**Comment by JugeshHM** [comment]
Thank you for your reply.

**Comment by benoitc** [comment]
I forget to add that the release will land this week

**Comment by JugeshHM** [comment]
Great news.. Thanks once again :)

**Comment by JugeshHM** [comment]
Hi,
Any update on release?

**Comment by durgaswaroop** [comment]
Does this thread indicate that the project is abandoned or ready to be abandoned?
