### ISSUE TITLE
any update on new version release?

### ISSUE THREAD

**Issue by JugeshHM** [benoitc/gunicorn#3002]
Hi,
Any update on release?

_Originally posted by @JugeshHM in https://github.com/benoitc/gunicorn/issues/2988#issuecomment-1567004376_

**Comment by durgaswaroop** [comment]
It is supposed to happen in a week, according to @benoitc in the thread. But a month has passed since. I wonder when that release will be.

**Comment by durgaswaroop** [comment]
@benoitc, Can you comment? Is there a new release in planning?

**Comment by benoitc** [comment]
@durgaswaroop new version will be tagged today. Release will happen soon after.
