### ISSUE TITLE
hiding Server header in the response (Docker + Django + gunicorn)

### ISSUE THREAD

**Issue by DragosChirila** [benoitc/gunicorn#3006]
Hi there,

We have dockerized a Django application starting from 3.10.9-slim-bullseye and we have used gunicorn to run Django like this:
```
gunicorn \
    --bind 0.0.0.0:8000 \
    --workers $DOCKER_SERVER_WORKERS \
    --threads $DOCKER_SERVER_THREADS \
    --config <ETC_DIR>/gunicorn.conf.py \
    --access-logfile <LOG_DIR>/access.log \
    --error-logfile <LOG_DIR>/error.log \
    project.wsgi:application
```

where `gunicorn.conf.py` is
```
import gunicorn

gunicorn.SERVER = 'undisclosed'
gunicorn.SERVER_SOFTWARE = 'undisclosed'

```
(we want to hide the `Server: gunicorn` header in the response)

Now, our services are running in ECS (AWS) and the user request hits the following resources:
- Route 53
- CloudFront
- the container running in ECS

Yes, we are not using a web server like Nginx on top of gunicorn.

**The problem** is that we get different `Server` values for different clients:
- wget - gunicorn !
- curl - CloudFront !
- Firefox - undisclosed `ok`
- Chrome - undisclosed `ok`
- Python requests - gunicorn !

Any thoughts? Would you know a better way of removing/hiding that `Server` header?
Any help is highly appreciated. 

Dragos

**Comment by benoitc** [comment]
Why would you want to remove this server header?

**Comment by DragosChirila** [comment]
Maybe because we don't want to disclose that information, that we're using gunicorn :)
Anyway, we fixed the problem by overriding that header in CloudFront - it reports now `CloudFront` for all clients.

On the other hand, I am keen to understand the behavior described above.

**Comment by benoitc** [comment]
Well that behavior is not supported at all. That's is a good practice to ensure the error are correctly reported to the original project. No option will be provided to override it. 

 I assume cloudfront or other rewrite the header when you do L7 proxying. I do think that opeople should let the server signature.  Do you have a pcap or an HTTP verbose log to share?

**Comment by DragosChirila** [comment]
Thanks @benoitc ,

I don't have a pcap nor a HTTP verbose log, sorry.

Here https://github.com/benoitc/gunicorn/blob/master/gunicorn/__init__.py 
```
version_info = (20, 1, 0)
__version__ = ".".join([str(v) for v in version_info])
SERVER = "gunicorn"
SERVER_SOFTWARE = "%s/%s" % (SERVER, __version__)
```

and according to the docs you can overwrite that through `gunicorn.conf.py` like I did. Why the SERVER value is not overwritten then?

**Comment by benoitc** [comment]
I didn't find where it is told in the configuration that such settings can be overriden  which would be a mistake. I will look at it. This server header can't be overwritten.

**Comment by DragosChirila** [comment]
Hey @benoitc ,

You are right, it doesn't explicitly say that you can overwrite `SERVER` value that way. I just assumed after reading this paragraph:
```
...
Any Python is valid. Just consider that this will be run every time you start Gunicorn
(including when you signal Gunicorn to reload).
```
https://docs.gunicorn.org/en/stable/configure.html?highlight=gunicorn.conf.py#configuration-file

and after looking at the code:
```
from gunicorn import SERVER_SOFTWARE, SERVER

...

class Response(object):

    def __init__(self, req, sock, cfg):
        self.req = req
        self.sock = sock
        self.version = SERVER
        ...
```
https://github.com/benoitc/gunicorn/blob/ab9c8301cb9ae573ba597154ddeea16f0326fc15/gunicorn/http/wsgi.py

Like I mentioned in my initial comment:
```
The problem is that we get different Server values for different clients:

    wget - gunicorn !
    curl - CloudFront !
    Firefox - undisclosed ok
    Chrome - undisclosed ok
    Python requests - gunicorn !
```

However, I totally agree with your point that the server header shouldn't be overwritten. Not an issue for us anymore.

Thanks a lot for you time!
