### ISSUE TITLE
21.0.1: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [benoitc/gunicorn#3028]
On building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.
Here is the output with warnings:

<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v6.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 26 added, 0 changed, 0 removed
reading sources... [100%] signals
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-gunicorn.3 { install run configure settings instrumentation deploy signals custom design faq community news 2023-news 2021-news 2020-news 2019-news 2018-news 2017-news 2016-news 2015-news 2014-news 2013-news 2012-news 2011-news 2010-news } /home/tkloczko/rpmbuild/BUILD/gunicorn-21.0.1/docs/source/settings.rst:315: WARNING: undefined label: 'logconfigjson'
/home/tkloczko/rpmbuild/BUILD/gunicorn-21.0.1/docs/source/custom.rst:9: WARNING: py:class reference target not found: gunicorn.app.base.BaseApplication
/home/tkloczko/rpmbuild/BUILD/gunicorn-21.0.1/docs/source/custom.rst:22: WARNING: py:class reference target not found: gunicorn.app.wsgiapp
done
build succeeded, 3 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/frostming/unearth/issues/14
https://github.com/jaraco/cssutils/issues/21
https://github.com/latchset/jwcrypto/pull/289
https://github.com/latchset/jwcrypto/pull/289
https://github.com/pypa/distlib/commit/98b9b89f
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/sqlalchemy/sqlalchemy/commit/5e88e6e8

**Comment by benoitc** [comment]
fixed
