### ISSUE TITLE
last release (21.1.0) sends a lot of errors

### ISSUE THREAD

**Issue by dkr-sahar** [benoitc/gunicorn#3032]
Throwing random errors

```python
[2023-07-18 13:04:10 +0000] [3150] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 232, in run
    self.murder_keepalived()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 176, in murder_keepalived
    self.poller.unregister(conn.sock)
  File "/usr/local/lib/python3.11/selectors.py", line 366, in unregister
    key = super().unregister(fileobj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 249, in unregister
    key = self._fd_to_key.pop(self._fileobj_lookup(fileobj))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
[2023-07-18 13:04:10 +0000] [3150] [INFO] Worker exiting (pid: 3150)
[2023-07-18 13:04:11 +0000] [1] [ERROR] Worker (pid:3150) exited with code 255
[2023-07-18 13:04:11 +0000] [1] [ERROR] Worker (pid:3150) exited with code 255.
```

The previous versions did not have this issue at all, was triggered in our latest build, so we’ll rollback version but still the problem remains in your latest release.

**Comment by rafaeljuzwiak** [comment]
I was about to create a ticket regarding this update as well. I manage an API that processes around 2k-3K calls / second distribuite a couple of pods inside Kubernetes with an average of 150ms.

Yesterday I had a hotfix regarding the API applied and I didn't notice I didn't have freeze the gunicorn in the requirements.txt file. As a result, Gunicorned instaled the latested version. I didn't notice at the time but, I notice after applying the patch my response times were averaging 600ms. It was a prod workload, so I undo de PR asap but couldn't get the response back to 150ms regardless what I did.

Only today I decided to compare the packages and notice this in gunicorn. Put it back to 20.1.0 and now it looks beutiful again. Maybe that is related to the "send a lot of errors" above, that is taking too much CPU time away, idk, I know that performance to the 21.1.0 compared to the 20.1.0 went down by a LOT.

**Comment by benoitc** [comment]
@dkr-sahar 21.1.0 fix this error that was in 21.0.1. Look at #3026. Are you sure about the version ? I don't reproduce it anymore after applying the fix.

**Comment by rafaeljuzwiak** [comment]
Positive, I did restart my pods and built again (on version 21) this morning and I still had issues.
Only after locking down the requirements.txt to 20.1.0 I got fixed.
You can see attachment, Purple is stage, Yellow Sandbox and Blue production.

![response times](https://github.com/benoitc/gunicorn/assets/4010377/718319e2-4118-471f-bad9-ce3451d64036)

**Comment by rafaeljuzwiak** [comment]
Ps: Morning I mean around 8AM UTC, not sure what tz you are in and if I still got the previous unpatched version when I made the rebuild.

**Comment by benoitc** [comment]
i don't reproduce it. I don't see how it can be rzproduced in current version with the error catched. can you provide an example? Or more contewt ? What return the command line `gunicorn --version` ?

**Comment by benoitc** [comment]
Please provide a way to reproduce it. I don't anymore since the patch :(

**Comment by xkobal** [comment]
I will try. 

Meanwhile, I am using the `gunicorn[gthread]==20.1.0` version.

**Comment by xkobal** [comment]
I confirm that it seems to happen only when my backend (django too) is raising an exception.

**Comment by dkr-sahar** [comment]
> I confirm that it seems to happen only when my backend (django too) is raising an exception.

It could also arise in the following sequence:
- backend takes too much time to answer (but still succeed to proceed the HTTP request)
- gunicorn raise this exception with bad file descriptor
- returns a 500 anyway.

**Comment by xkobal** [comment]
Same as @dkr-sahar. 
And when I call a second time the same endpoint, it works, I have a normal 500 error.

All of this is happening in Docker in my case.

**Comment by geudrik** [comment]
Our CI (shame on us) installed 21.1.0 at 10:45 EST this am, upgrading us from 20.1.0, and we get tons of the following, causing 502's to return from nginx (sitting in front of gunicorn)

```
│ overwatch-api-green-67c57565dd-fg225 api [2023-07-18 17:33:38 +0000] [55] [ERROR] Socket error processing request.                                                                                                         │
│ overwatch-api-green-67c57565dd-fg225 api Traceback (most recent call last):                                                                                                                                                │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 285, in handle                                                                   │
│ overwatch-api-green-67c57565dd-fg225 api     keepalive = self.handle_request(req, conn)                                                                                                                                    │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 357, in handle_request                                                           │
│ overwatch-api-green-67c57565dd-fg225 api     util.reraise(*sys.exc_info())                                                                                                                                                 │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/util.py", line 641, in reraise                                                                             │
│ overwatch-api-green-67c57565dd-fg225 api     raise value                                                                                                                                                                   │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 343, in handle_request                                                           │
│ overwatch-api-green-67c57565dd-fg225 api     resp.write(item)                                                                                                                                                              │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 326, in write                                                                          │
│ overwatch-api-green-67c57565dd-fg225 api     self.send_headers()                                                                                                                                                           │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 322, in send_headers                                                                   │
│ overwatch-api-green-67c57565dd-fg225 api     util.write(self.sock, util.to_bytestring(header_str, "latin-1"))                                                                                                              │
│ overwatch-api-green-67c57565dd-fg225 api   File "/root/.pyenv/versions/3.8/lib/python3.8/site-packages/gunicorn/util.py", line 299, in write                                                                               │
│ overwatch-api-green-67c57565dd-fg225 api     sock.sendall(data)                                                                                                                                                            │
│ overwatch-api-green-67c57565dd-fg225 api OSError: [Errno 9] Bad file descriptor 
```

**Comment by isra17** [comment]
Same here, we have emissary in front of gunicorn. My logs shows around 10% of upstream connection closed with the following logs:

```
2023-07-18T17:52:40Z: [error] Socket error processing request.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    req = next(conn.parser)
          ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/message.py", line 184, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/message.py", line 55, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/message.py", line 196, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/message.py", line 187, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
```

**Comment by bandwith** [comment]
Not sure what I can add here... 

I have `gunicorn>=20.1.0,!=21.0.1,!=21.0.0` in requirements.txt

```
# gunicorn --version
gunicorn (version 21.1.0)
```

Not seeing the errors experienced on `21.0.0` or `21.1.0`

**Comment by benoitc** [comment]
can someone test with the `gh-thread` branch ? https://github.com/benoitc/gunicorn/pull/3033

**Comment by alpden550** [comment]
Python 3.10.12 and latest gunicorn stil nas this error:

```OSError: [Errno 9] Bad file descriptor```

**Comment by revanthmahesh** [comment]
@alpden550 you can use `pip install git+https://github.com/benoitc/gunicorn.git@fix-gthread` or downgrade the gunicorn version for now. Until the fix is deployed by @benoitc

**Comment by alpden550** [comment]
@revanthmahesh
thanks, I know and fixed gunicorn as gunicorn==20.1.0

**Comment by oxtime** [comment]
Python 3.6.7

OSError: [Errno 9] Bad file descriptor

**Comment by benoitc** [comment]
can someone test with the gh-thread branch ? https://github.com/benoitc/gunicorn/pull/3033 Complaining that current release has an issue doesn't help that much. I don't reproduce the issue myself.

**Comment by geudrik** [comment]
If it helps others down the road, we had a flask endpoint that would reliably fail here using 21.1.0. All it did was use requests to make an API call upstream and return the results.

**Comment by benoitc** [comment]
gunicorn 21.2.0 has been released which is fixing this issue.

**Comment by vae1207** [comment]
as gunicorn=20.0.4-1, it has same error, could be update gunicorn to solve this problem?
  File "/opt/services/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    req = next(conn.parser)
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/message.py", line 186, in __init__
    super().__init__(cfg, unreader)
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/message.py", line 198, in parse
    self.get_data(unreader, buf, stop=True)
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/message.py", line 189, in get_data
    data = unreader.read()
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/opt/services/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/lib64/python3.7/ssl.py", line 1056, in recv
    return self.read(buflen)
  File "/usr/lib64/python3.7/ssl.py", line 931, in read
    return self._sslobj.read(len)
OSError: [Errno 0] Error
