### ISSUE TITLE
Documentation for ssl_context mentions nonexistent version 20.2 (should be 21.0)

### ISSUE THREAD

**Issue by uedvt359** [benoitc/gunicorn#3043]
> [ssl_context](https://docs.gunicorn.org/en/stable/settings.html#ssl-context)
> New in version 20.2.

There is no such version, this is probably a remnant of before the decision was made to bump the major version. similarly, `ssl_version` says "Deprecated since version 20.2".

**Comment by tilgovi** [comment]
Thank you!
