### ISSUE TITLE
Suggestion: Drop support for python < 3.7

### ISSUE THREAD

**Issue by aqeelat** [benoitc/gunicorn#3045]
title

**Comment by bcail** [comment]
It [looks](https://github.com/benoitc/gunicorn/blob/master/.github/workflows/tox.yml#L13) [like](https://github.com/benoitc/gunicorn/commit/f5d73aa73d53ef7838c128b7c3a582c536670c5e) the tests are run on Python 3.7 and higher, so it seems like this could be closed.
