### ISSUE TITLE
Version 21.0.1 or higher breaks with python 3.5

### ISSUE THREAD

**Issue by nicolaszein** [benoitc/gunicorn#3046]
I am currently running an older application with Python 3.5, and I encountered an error when attempting to update the Gunicorn version to the latest one:

```
NameError: name 'ModuleNotFoundError' is not defined
```

After some investigation, I realized that the 'ModuleNotFoundError' is only available for Python 3.6 or higher. My suspicion is that this bug was introduced in [this commit](https://github.com/benoitc/gunicorn/commit/f628dd9730f965b1917397ea1846c68844b1fe7a).

As a result, it seems that Gunicorn is not fully compatible with Python 3.5

**Comment by bcail** [comment]
It [looks](https://github.com/benoitc/gunicorn/blob/master/.github/workflows/tox.yml#L13) [like](https://github.com/benoitc/gunicorn/commit/f5d73aa73d53ef7838c128b7c3a582c536670c5e) the tests are run on Python 3.7 and higher, so I'm not sure Gunicorn is trying to be compatible with Python 3.5.
