### ISSUE TITLE
events not sent when using morethan 1 gunicorn workers

### ISSUE THREAD

**Issue by naolaregaqena** [benoitc/gunicorn#3069]
Issue

When using multiple `gunicorn` workers with `uvicorn.workers.UvicornWorker` using [sysid/sse-starlette](https://github.com/sysid/sse-starlette) for a `FastAPI` application, only the first event is sent. the subsequent event are not reaching the client.

**Comment by benoitc** [comment]
the lib need to ensure to detach the connection from the worker. Check with the dev how ot support it. I'm happy to answer to the question there .

**Comment by benoitc** [comment]
close issue as stalled.
