### ISSUE TITLE
Gunicorn - websockets only doesn't evenly distribute connections to workers

### ISSUE THREAD

**Issue by LiteWait** [benoitc/gunicorn#3071]
I have a websocket app that has Gunicorn running in production with 4 workers. In my example I have 16 clients connecting, and judging by my debug output the sockets are not distributed evenly across workers when the connect. This results in very uneven performance under load. Is there a way to coerce Gunicorn to share better?

Task 2 with pid 38607 finished after 138.70 seconds
Task 0 with pid 38607 finished after 142.74 seconds

Task 9 with pid 38606 finished after 149.22 seconds
Task 3 with pid 38606 finished after 150.29 seconds
Task 13 with pid 38606 finished after 151.40 seconds

Task 5 with pid 38605 finished after 196.03 seconds
Task 15 with pid 38605 finished after 197.42 seconds
Task 12 with pid 38605 finished after 197.42 seconds
Task 14 with pid 38605 finished after 197.45 seconds
Task 4 with pid 38605 finished after 197.24 seconds

Task 11 with pid 38608 finished after 205.61 seconds
Task 7 with pid 38608 finished after 207.46 seconds
Task 8 with pid 38608 finished after 207.37 seconds
Task 10 with pid 38608 finished after 207.35 seconds
Task 6 with pid 38608 finished after 207.56 seconds
Task 1 with pid 38608 finished after 207.53 seconds

**Comment by benoitc** [comment]
This is depending on the linux scheduler policy of the OS. One way to work around is to dedicate a number of cpus to the application . This would improve it.
