### ISSUE TITLE
Trouble with 'worker_exit' hook

### ISSUE THREAD

**Issue by ArijitSinghEDA** [benoitc/gunicorn#3077]
I have a FastAPI app which I am running with gunicorn like this:
`gunicorn  main:app --config gunicorn_config.py`

My `gunicorn_config.py` file:
```
import uvicorn
import main_run as work_fn


workers = 4
worker_class = "uvicorn.workers.UvicornWorker"
bind = "0.0.0.0:8046"
timeout = 86400
graceful_timeout = 300
worker_exit = work_fn.worker_exit
```

My `main_run.py` file contains:
```
def worker_exit(server, worker):
    global cb, obj, down_path_
    if down_path_ is not None:
        _path = f"{down_path_}models/"
        model_ls = []
        for model in os.listdir(_path):
            if "." not in model:
                model_ls.append(model)
        obj.load_model(save_path=down_path_)
        obj.fit_model(model_ls, trainer_callback=cb.model_callback)
        cb.final_model_callback()
    else:
        print(f"Not inside this process: {os.getpid()}")
```

When I try to exit the worker where the process is running, using `kill -s TERM <pid>`, I get no response. It is only when I hit `Ctrl+C` multiple times, then at the end it shows the result.

**Comment by tilgovi** [comment]
I cannot reproduce this issue with a simple uvicorn test project. If you still experience this issue without the `worker_exit` hook, please reply and I can re-open the issue. Otherwise, it sounds like your `worker_exit` hook is running code that blocks.
