### ISSUE TITLE
WebSockets and --max-requests does not reload Workers

### ISSUE THREAD

**Issue by lesc6** [benoitc/gunicorn#3086]
If you use independent server for websocket connection, you expect that Worker process will be killed after N requests, but it will never killed it consume more and more memory.

`gunicorn --bind=unix:/tmp/ws.sock --worker-class=uvicorn.workers.UvicornWorker --workers=1 --max-requests=10`

use any ws client to reproduce.

**Comment by tilgovi** [comment]
I've tested that the UvicornWorker correctly receives the argument and handles it, but tracking request counts for WebSockets seems not to work. Please open an issue with uvicorn.
