### ISSUE TITLE
Mixed content in 21.2.0 version

### ISSUE THREAD

**Issue by ValeriiaNesterova** [benoitc/gunicorn#3092]
Hello. After upgrading Gunicorn version to 21.2.0 (the latest), my website started to show "Mixed Content" error. I am using Nginx as a reverse proxy. My current Nginx config:

     server {
        listen 8080 default_server;
        server_name _;
    
        #
        # Basic location config
        #
        location / {
          add_header Strict-Transport-Security "max-age=31536000" always;
          proxy_intercept_errors on;
          proxy_pass http://frontend;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $http_x_real_ip;
          proxy_set_header X-Forwarded-For $http_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
          proxy_hide_header X-Tm;
          proxy_hide_header X-Trace;
        }
    
      }

Maybe someone knows what could be changed?

**Comment by benoitc** [comment]
can you paste the whole log?

**Comment by ValeriiaNesterova** [comment]
@benoitc The whole browser's console log "Mixed Content: The page at 'https://website/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://website/search?q=Mobile+Phone&count"

Previously we used Gunicorn 19.9.0, and when we switched to a higher version this error appeared, starting with 20.0 where there were significant changes. 

Do you happen to know if this can be fixed on Gunicorn/Nginx side, or only inside the code?
