### ISSUE TITLE
Web site build accidentally included in pypi releases

### ISSUE THREAD

**Issue by tsaarni** [benoitc/gunicorn#3109]
Request: remove the `docs/build` directory from future pypi releases.

Background:

Recent pypi release packages contain the full web site docs in `docs/build/` directory, while the older releases only contained the placeholder files e.g. `docs/site/install.html` which redirects to https://gunicorn.org/. 

For example, see 21.2.0 release [here](https://files.pythonhosted.org/packages/06/89/acd9879fa6a5309b4bf16a5a8855f1e58f26d38e0c18ede9b3a70996b021/gunicorn-21.2.0.tar.gz).

The website files can mistakenly cause gunicorn to be flagged to contain GPL license by license scanners. The files `docs/build/html/_static/js/html5shiv.min.js` and `docs/build/html/_static/js/html5shiv-printshiv.min.js` in the release package, coming via Read the Docs theme, have GPL2 license text ([link](https://github.com/aFarkas/html5shiv/blob/daa5fd1169cf8c1b63b0659754b4d13b037c0e54/src/html5shiv.js#L2)). However, this is false flag: even when considering these are now part of gunicorn release, it is clarified [here](https://www.github.com/aFarkas/html5shiv/issues/94) in html5shiv project, that those files are dual-licensed and user is free to pick MIT over GPL2.

**Comment by benoitc** [comment]
hrm odd I will fix it.
