### ISSUE TITLE
Gunicorn and Supervisor(Monitoring Tool)

### ISSUE THREAD

**Issue by knana1662** [benoitc/gunicorn#3121]
Please I would like to know if the supervisor(monitoring tool) commands or settings overrides the configuration files of gunicorn?

**Comment by tilgovi** [comment]
Can you be more specific about which settings?

**Comment by zffocussss** [comment]
> Please I would like to know if the supervisor(monitoring tool) commands or settings overrides the configuration files of gunicorn?

you had better look into the details in supervisor docs first.

**Comment by benoitc** [comment]
supervisor will only start gunicorn with the arguments you pass to it. It won't override the configuration other than passing arguments to the command line of gunicorn that will override the configuration file.
