### ISSUE TITLE
Gunicorn with FastAPI causing CUDA Error

### ISSUE THREAD

**Issue by ciliamadani** [benoitc/gunicorn#3130]
Hello, I have been developing a FastAPI application where we can access a HuggingFace model and use it for text generation. On top of it, I'm launching the service with Gunicorn so that we can handle concurrent users. 
My goal is to load the model only once to GPU and allow the works to share the same model concurrently.

To do this, I loaded the model and tokenizer outside of the FastAPI endpoint, I  also clearly stated the use of **spawn** method and the --**preload** flag. 
However, I'm still running into the following error, does anyone have an idea about this? I tried almost all the solutions I found on internet.

> RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

I'm launching Gunicorn using:
_nohup gunicorn --workers 2 --preload --worker-class=uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 hf_enpoint:app &_

**Versions** 
Python: 3.10.12 
torch: 2.1.1+cu121
transformers: 4.32.1
FastAPI: 0.104.1
Gunicorn: 20.1.0

**hardware** 
EC2 instance: g4dn.4xlarge
GPU:  NVIDIA 
GPU memory: 16GB

**Code**
````
## imports 
torch.multiprocessing.set_start_method('spawn')
multiprocessing.set_start_method('spawn', force=True)

memory = ConversationBufferWindowMemory(k=20, memory_key="history",input_key="input")
model_id = "TheBloke/Llama-2-13B-chat-GPTQ"
model_basename = "model"
tokenizer = AutoTokenizer.from_pretrained(model_id, is_split_into_words=True)
model = AutoGPTQForCausalLM.from_quantized(model_id,
        model_basename=model_basename,
        use_safetensors=True,
        trust_remote_code=True,
        device="cuda:0",
        use_triton=use_triton,
        quantize_config=None)
#model = AutoGPTQForCausalLM.from_quantized(quantized_model_dir, device="cuda:0")


app = FastAPI()
@app.post("/get_response")
async def get_response(data : Dict[Any, Any]):

## use model 
       
```

**Comment by benoitc** [comment]
you need to ensure that your model is only initialized once. Looking at your one module code it looks like this module will be used during spawn or fork. Maybe try to initialize your workin a hook and ensure to use ite  else where. Also don't use spawn it shouldn't be needed.

**Comment by benoitc** [comment]
closing as answered since no feedback from the requestor.

**Comment by myzf** [comment]
> Hello, I have been developing a FastAPI application where we can access a HuggingFace model and use it for text generation. On top of it, I'm launching the service with Gunicorn so that we can handle concurrent users. 
> My goal is to load the model only once to GPU and allow the works to share the same model concurrently.
> 
> To do this, I loaded the model and tokenizer outside of the FastAPI endpoint, I  also clearly stated the use of **spawn** method and the --**preload** flag. 
> However, I'm still running into the following error, does anyone have an idea about this? I tried almost all the solutions I found on internet.
> 
> > RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
> 
> I'm launching Gunicorn using:
> _nohup gunicorn --workers 2 --preload --worker-class=uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 hf_enpoint:app &_
> 
> **Versions** 
> Python: 3.10.12 
> torch: 2.1.1+cu121
> transformers: 4.32.1
> FastAPI: 0.104.1
> Gunicorn: 20.1.0
> 
> **hardware** 
> EC2 instance: g4dn.4xlarge
> GPU:  NVIDIA 
> GPU memory: 16GB
> 
> **Code**
> ````
> ## imports 
> torch.multiprocessing.set_start_method('spawn')
> multiprocessing.set_start_method('spawn', force=True)
> 
> memory = ConversationBufferWindowMemory(k=20, memory_key="history",input_key="input")
> model_id = "TheBloke/Llama-2-13B-chat-GPTQ"
> model_basename = "model"
> tokenizer = AutoTokenizer.from_pretrained(model_id, is_split_into_words=True)
> model = AutoGPTQForCausalLM.from_quantized(model_id,
>         model_basename=model_basename,
>         use_safetensors=True,
>         trust_remote_code=True,
>         device="cuda:0",
>         use_triton=use_triton,
>         quantize_config=None)
> #model = AutoGPTQForCausalLM.from_quantized(quantized_model_dir, device="cuda:0")
> 
> 
> app = FastAPI()
> @app.post("/get_response")
> async def get_response(data : Dict[Any, Any]):
> 
> ## use model 
>        
> ```
> 
how do you work it?i am have a same problem
