### ISSUE TITLE
failing to run gunicorn in aws lightsail

### ISSUE THREAD

**Issue by tendaysaweek** [benoitc/gunicorn#3139]
please see below, I'm running my flask code with no issues with screen, but thought to improve to gunicorn, followed the text, used gpt4, cannot get this thing to work, any assistance would be highly appreacited!

e/bitnami/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi    self.wsgi = self.app.wsgi()  File "/home/bitnami/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi    self.callable = self.load()  File "/home/bitnami/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load    return self.load_wsgiapp()  File "/home/bitnami/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp    return util.import_app(self.app_uri)  File "/home/bitnami/.local/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app    mod = importlib.import_module(module)  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module    return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlockedModuleNotFoundError: No module named '/opt/bitnami/wordpress/adirQ/a7prompt'[2024-01-13 21:23:33 +0000] [3626] [INFO] Worker exiting (pid: 3626)[2024-01-13 21:23:33 +0000] [3625] [ERROR] Worker (pid:3626) exited with code 3[2024-01-13 21:23:33 +0000] [3625] [ERROR] Shutting down: Master[2024-01-13 21:23:33 +0000] [3625] [ERROR] Reason: Worker failed to boot.(venv)

**Comment by benoitc** [comment]
What command line do you pass to start gunicorn ?

**Comment by benoitc** [comment]
closing. no answer from the requestor.
