### ISSUE TITLE
Can someone help me with this error below

### ISSUE THREAD

**Issue by ziyaxservers** [benoitc/gunicorn#3140]
i am trying to make may flask aplication to run automatically but he gives me this error "Changing to the requested working directory failed: Permission denied, Failed at step CHDIR spawning /root/gamingfocus/venv/bin/gunicorn: Permission denied, Main process exited, code=exited, status=200/CHDIR, Failed with result 'exit-code'." here is my .service file "[Unit]
Description=gamingfocus Flask app
After=network.target

[Service]
User=flaskroot
Group=flaskroot
WorkingDirectory=/root/gamingfocus  # Path to the directory containing gamingfocus.py
Environment="PATH=/root/gamingfocus/venv/bin"
ExecStart=/root/gamingfocus/venv/bin/gunicorn -w 4 -b 127.0.0.1:6161 gamingfocus:app

[Install]
WantedBy=multi-user.target
" it has nothing to do with nginx bwcouse all works but only when I run it manually I think it has something to do with the permission of the file and user that is trying to access it I have checked everything but nothing seems to work I'm open to suggestions

**Comment by benoitc** [comment]
you need to ensure that gunicorn can still st have access to your folder. I would start gunicorn as root and start the user under your flaskroot user to make it simpler.

**Comment by benoitc** [comment]
closed. thanks for your feedback.
