### ISSUE TITLE
Add a minimun time before restart when `max_requests` is defined

### ISSUE THREAD

**Issue by ecdatadog** [benoitc/gunicorn#3141]
Hello,

Currently, when `max_requests` is defined, your workers can restart very often if they have to handle important worload. 

For some cases, when the throughput spiked, workers can restarts very often . As it takes time (and CPU) to restart, I would like to have a `max_requests_minimum_duration` (or similar name) so that when the `max_requests` is reached it doesn't immediately restarts but wait the minimum duration. It can be a good trade-off between memory (and leaks for which `max_requests` is used) and CPU (worker startup can be costly) 
I looked in the code and it doesn't seems to complicated to implement.

**Comment by benoitc** [comment]
I'm not a fan of thid. max_request must be a temporary measure to fix temporary leaks in your application until it is fixed. What do you set it in your case?

**Comment by benoitc** [comment]
Beside my comment maybe we could make the feature a little less immerfiate indeed but instead of having a delay i would introduce a time that chrck how long the leak is existing. But that maybe more the scope a tool like prometheus

**Comment by ecdatadog** [comment]
> I'm not a fan of thid. max_request must be a temporary measure to fix temporary leaks in your application until it is fixed. Easing its usage would en encourage the issue to stay longer imo.

I agree it should be a temporary fix but with the variation of traffic we want our workers not always restart.

**Comment by ecdatadog** [comment]
Thank for your comments. We will how to manage it !
