### ISSUE TITLE
Unable to report vulnerability

### ISSUE THREAD

**Issue by kenballus** [benoitc/gunicorn#3143]
From the security page:
> If you believe you are found a problem in Gunicorn software, examples or documentation, we encourage you to send your report privately via [email](mailto:security@gunicorn.org?subject=Security%20issue%20in%20Gunicorn), or **via Github using the Report a vulnerability button in the [Security](https://github.com/benoitc/gunicorn/security) section.**

There is no such button on the security page.

**Comment by benoitc** [comment]
button enabled. Thanks for the report.
