### ISSUE TITLE
Security mailbox seems broken

### ISSUE THREAD

**Issue by psmoros** [benoitc/gunicorn#3160]
Hi team,
I'm trying to email you regarding a vulnerability but I keep getting the following error from your mail server.

<img width="630" alt="Screenshot 2024-02-23 at 12 33 30" src="https://github.com/benoitc/gunicorn/assets/17127410/5941b0a4-bdf8-46db-92ab-b3faf5728483">

I've emailed security@gunicorn.org from 3 different emails and I keep getting the same error.

Thanks for everything you're doing!

**Comment by benoitc** [comment]
DNS have been fixed. This email shoujld work again.
