### ISSUE TITLE
How to route traffic when using gunicorn?

### ISSUE THREAD

**Issue by 94929** [benoitc/gunicorn#3169]
Gunicorn let OS handle the routing to its workers (e.g. uvicorn).
Is there a way to handle the traffic manually?

The issue i'm facing is as follow:

I'm running gunicorn with number of uvicorn workers (fastapi applciation).
While running the workers, the uvicorn workers is killed for some reason.
And gunicorn respawns the uvicorn worker but the respawned worker is not ready to accept the requests.
So I want to block traffic to the non-ready workers. Is that possible?

**Comment by benoitc** [comment]
respawned worker should already been able to accept a connection. If not there is an issue. There is no way to block a traffic for a specific worker. 

closing as answered
