### ISSUE TITLE
[Question] TLS certificate rotation

### ISSUE THREAD

**Issue by t-yrka** [benoitc/gunicorn#3182]
What is the recommended way of performing TLS certificate rotation with gunicorn?

Based on https://github.com/benoitc/gunicorn/blob/master/gunicorn/sock.py#L219 it seems (by default) the certificate is picked up on each request, so the gunicorn should automatically use the newest one available (and it works fine based on my testing). But I've not found this mentioned anywhere in the docs - is it an undocumented feature(?), or we shouldn't rely on this?

I was going to use the `HUP` signal to reload the workers, but it seems redundant when the certificates are not pre-loaded.

**Comment by chadr123** [comment]
@benoitc Hello. I'm also interested in this topic. Could you take a look at this question? :D

**Comment by benoitc** [comment]
certificates are not cached yet. If in the future it will this will be documented. I think it's safe anyway to force that reload when you rotate SSL certificates so you make sure that future changes are covered.

**Comment by ohads-MSFT** [comment]
@benoitc the current behavior (support cert file rotation) is highly desirable, and compatible with industry best practices (especially combined with a CSI driver, e.g. Azure CSI Key Vault driver). Removing this in the future would be a breaking change in practice (even if not strictly speaking, as it's undocumented).

If I may humbly make a suggestion, future changes should maintain this behavior. On possible implementation is file polling, employed by ASP.NET: https://github.com/dotnet/aspnetcore/pull/50251
