### ISSUE TITLE
SCRIPT_NAME header is dropped/rejected by header map validation

### ISSUE THREAD

**Issue by jhominal** [benoitc/gunicorn#3200]
From the [Gunicorn documentation](https://docs.gunicorn.org/en/latest/faq.html#how-do-i-set-script-name), and the [corresponding code](https://github.com/benoitc/gunicorn/blob/22.0.0/gunicorn/http/wsgi.py#L119-L130), it is possible to use a `SCRIPT_NAME` HTTP header to set the `SCRIPT_NAME` key in the WSGI environment for the corresponding request.

However, as `SCRIPT_NAME` contains an underscore, it is dropped by the new code in [`parse_headers`](https://github.com/benoitc/gunicorn/blob/22.0.0/gunicorn/http/message.py#L142-L152) by default.

I think that `SCRIPT_NAME` should be special-cased by the header validation logic, as it cannot be confused (it never gets added as `HTTP_SCRIPT_NAME` in the WSGI environment, so it would never conflict with a `Script-Name` header anyway).

**Comment by burnettk** [comment]
here's a minimalish repro, in case it's helpful to anyone: https://github.com/sartography/repro-gunicorn-22-0-0-regression
