### ISSUE TITLE
Gunicorn-22.0.0 egg file not building properly. Missing directories.

### ISSUE THREAD

**Issue by ajayhb** [benoitc/gunicorn#3203]
On downloading the source code and building it locally in ubuntu / freebsd box, 
I see only the following directories created inside the egg file:
```
EGG-INFO        
__init__.py    
__main__.py    
__pycache__     
arbiter.py      
config.py      
debug.py        
errors.py       
glogging.py     
pidfile.py      
reloader.py     
sock.py        
systemd.py      
util.py
```

I get the error while starting / stopping the services:
```
/usr/local/bin/python: can't open file 
'/var/python/lib/python3.9/site-packages/gunicorn-22.0.0-py3.9.egg/gunicorn/app/wsgiapp.py': 
[Errno 2] No such file or directory
```

As it does not have the following path inside the egg file: "gunicorn/app/wsgiapp.py", Therefore the services are not starting / stopping.

I am trying to build gunicorn by creating a manual setup.py inside the root dir, with the following content inside setup.py:

```
from __future__ import annotations

from setuptools import setup

setup(name='gunicorn', version='22.0.0', packages=[''], package_dir={"": "gunicorn"})
```

What am I missing?

**Comment by ajayhb** [comment]
1) My services were running on gunicorn-21.1.0
2) I replaced all the occurrences of gunicorn-21.1.0 with gunicorn-22.0.0 in the codebase
3) Then in my submodule where I kept gunicorn-22.0.0 source code, I created a setup.py file to build it., which has the 3 line code mentioned above. 
4) I associated the commit id of submodule in my main repo where the services are using gunicorn, that is inside the submodule.
5) On building my main source code (which in turn builds the source code of gunicorn via my setup.py), I get this error where the services are not starting.

**Comment by ajayhb** [comment]
Bound to use ```setup.py``` for all the packages because of some dependencies. Will take sometime to move to ```pyproject.toml``` for building packages in my repo

**Comment by ajayhb** [comment]
Hi @pajod  , 
I incorporated your changes of  ```setup.py``` file and tried building the package from scratch.
However, I still do not see ```gunicorn/app/wsgiapp.py``` file inside the directory.

```
[root@makesh_FB222 /usr.src/contrib/python/var/python/lib/python3.9/site-packages/gunicorn-22.0.0-py3.9.egg]# ls
EGG-INFO        __init__.py     __main__.py     __pycache__     arbiter.py      config.py       debug.py        errors.py       glogging.py     pidfile.py      reloader.py     sock.py         systemd.py      util.py
```

**Comment by ajayhb** [comment]
```
pip==22.0.4
setuptools==46.1.3
packaging==21.3
```
Sequence of commands might not be possible.

**Comment by benoitc** [comment]
Maybe we should try to find a way to still ship a setup.py for those who need it?  We should make sure the ux is goof. thoughts?

**Comment by ajayhb** [comment]
Workaround I did:

The directories are missing in my egg file after building the source code in freebsd machine.
So in my Makefile, When building gunicorn-22.0.0, I am manually copying the missing directories inside the newly created egg file.

This made my python services up and running.

However, My headers with Hyphen and Underscores are now missing and APIs are giving me 400 error.

To solve this, I am adding a flag: "--header-map dangerous"

```
/usr/local/bin/python /var/python/lib/python3.9/site-packages/gunicorn-22.0.0-py3.9.egg/gunicorn/app/wsgiapp.py --header-map dangerous -t 10000 -w 2 -k gevent -b 127.0.0.1:5800 abc.__init__:app 2>&1 &
echo $! > /var/run/abc.pid
```

But I am still facing the same issue.
Am I missing something?

**Comment by ajayhb** [comment]
Issue with freebsd machines on my setup. Have a workaround for now. Closing this.
