### ISSUE TITLE
Multiple Vulnerability Reports and security email address issue

### ISSUE THREAD

**Issue by byt3bl33d3r** [benoitc/gunicorn#3215]
Heya,

I work for ProtectAI and we run a bug bounty platform [Huntr](https://huntr.com). We received multiple reports for Gunicorn (the oldest one dating back to December 2023). W'eve been trying to contact the security@ email address since last year but it seems to be misconfigured and the email bounces with an error. I also sent an email to all of the core maintainers listed in the MAINTAINERS file with no response.

Just FYI that we'll be validating and making these reports public by the end of this week unless someone gets back to us as we've more than exceeded the timeline for responsible disclosure. You can either login to [Huntr](https://huntr.com) or check your email(s) (sender is marcello@protectai.com) to get access to the reports.

Thanks

**Comment by byt3bl33d3r** [comment]
I've also contacted benoitc on Twitter/X a few months ago about the security@ email address issue but it still isn't fixed.

**Comment by benoitc** [comment]
email have been fixed. There was a dns misconfiguration. 

 Reports should be done there , please send those who have been created on your service  using the security features that have bene opened in github. This ease the support and ensure all the info is collected on the project and would trigger some review. 
 
 @pajod would you be interrested to join the project to help me on this?

**Comment by benoitc** [comment]
I appears that these "vulnerabilities" requires me to open an account to the huntr website. I don't find this approach very useful.  Reports should be made there or by mail. Can you forward me properly this report to my mail or open a private disclosure there? Otherwise I will just wait for the public release of these reports.

**Comment by benoitc** [comment]
@pajod that is an interresting approach. Let me figure by the end of the day. Some vulnerabilities are indeed related to HTTP parsing. i will review the tickets above.

**Comment by byt3bl33d3r** [comment]
hey @benoitc , you don't need to open an account on Huntr to view the reports. We usually send automated magic links to maintainers to view reports without having to create an account. you didn't receive because of the email issues.

I just resent the magic link to the security@ address.

Thanks

**Comment by benoitc** [comment]
@byt3bl33d3r thanks. Looking at them now.
