### ISSUE TITLE
Bypass connection queue for load balancer health checks : Latest

### ISSUE THREAD

**Issue by sandeep2632** [benoitc/gunicorn#3222]
Using the solution mentioned in the issue : https://github.com/benoitc/gunicorn/issues/1417. 
I did try binding multiple ports to gunicorn running 1 worker only, thinking that health check request will be redirect to secondary port while the primary one is busy processing. But its throwing 499 to health check API.

**Comment by benoitc** [comment]
the main purpose of health endpoint is to check if your serice answer in a timely fashion. Why would you handle such endpoint out of the normal request path?
