### ISSUE TITLE
模型部署问题

### ISSUE THREAD

**Issue by myzf** [benoitc/gunicorn#3224]
我启用了preload参数初始化一些模型，避免重复在worker重复加载，但是中间遇到了不少问题，能否给一个这种场景的demo？

**Comment by zffocussss** [comment]
please describe your questions in English only.

**Comment by benoitc** [comment]
@myzf if you have any issue please create a separate issue with logs and a clear definition on how you start ypour application . --preload is supposed to load all your app in main runtime ans share this with other.
