### ISSUE TITLE
Veracode Scan Vulnerability: Improper Neutralization of Special Elements used in an OS Command (OS Command Injection)

### ISSUE THREAD

**Issue by rootVIII** [benoitc/gunicorn#3229]
Hi Team:

Our Veracode scan is showing a Very High vulnerability in the Gunicorn source code in arbiter.py line 432:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L432

```os.execvpe(self.START_CTX[0], self.START_CTX['args'], environ)```

We are using the latest Pypi version (22.0.0).

Is this something that can be mitigated somehow?

Thank you for the support and great web server.

**Comment by ThiefMaster** [comment]
why do you think it's a vulnerability? this looks like a simple "re-execute itself" logic...

**Comment by rootVIII** [comment]
I don't think it is a vulnerability necessarily, but our Veracode scanner is rating it as "Very High" (the highest possible). Hopefully I can mark it off as "reported to library maintainer" or "false-positive".

**Comment by benoitc** [comment]
5hanks for the report. Does it provides more i fo about it? Any more logs? I don't see any issue with this code myself.

**Comment by rootVIII** [comment]
I'm gonna close this... sorry for wasting your time. I don't see much other information and it just links to https://cwe.mitre.org/data/definitions/78.html. Some of the other flaws it found in other libs were kinda silly or vague too except for Flask signing their session cookies with sha1.

**Comment by rootVIII** [comment]
Thank you @pajod !
