### ISSUE TITLE
Gunicorn accepts requests with empty URIs

### ISSUE THREAD

**Issue by kenballus** [benoitc/gunicorn#3235]
The ABNF rule that defines request URIs (`request-target`) doesn't match the empty string. Thus, requests with empty URIs don't match the grammar, and should be rejected.

Currently, Gunicorn doesn't do this. You can see this for yourself by sending the following request to an instance of Gunicorn:
```
GET  HTTP/1.1\r\n
Host: whatever\r\n
\r\n
```
(Notice the two spaces between the method and version.)

**Comment by benoitc** [comment]
i have edited this issue. There is nonissue to list all others implementations when you post an issue. Just describing the issue and linking to the spec is enough.
