### ISSUE TITLE
gunicorn + gevent(worker class) generating exception when terminating the process with `ctrl+c`

### ISSUE THREAD

**Issue by Kalebe16** [benoitc/gunicorn#3239]
### gevent-version: `24.2.1`
![image](https://github.com/benoitc/gunicorn/assets/87911732/2fab3cf5-4103-4bb9-8251-b9097f09049f)
![image](https://github.com/benoitc/gunicorn/assets/87911732/c71c4384-f483-460e-b034-44f4f5c1aaa5)
![image](https://github.com/benoitc/gunicorn/assets/87911732/d89e7f5a-54d9-40c2-b734-3f20b6160fd8)

**Comment by benoitc** [comment]
This is not really an issue. I guess exit is not expected but then ctrl-c is also kind of a brutal  way to exit the process. closing as none issue.

**Comment by Kalebe16** [comment]
From my point of view, terminating the program with an exception is inelegant, anyway, my solution was this:

```python
from gunicorn.app.base import BaseApplication
from gunicorn.workers.ggevent import GeventWorker

def monkey_patch_gevent_worker() -> None:
    def handle_quit(self, sig, frame):
        self.alive = False   # This is enough to stop the gevent worker

    GeventWorker.handle_quit = handle_quit

monkey_patch_gevent_worker()
```
