### ISSUE TITLE
Docs: What are AsyncIO Workers?

### ISSUE THREAD

**Issue by vanschelven** [benoitc/gunicorn#3241]
The [design documentation](https://github.com/benoitc/gunicorn/blob/79b9a52cc8cd664f77d43efe173291a5397df130/docs/source/design.rst?plain=1#L75) mentions "AsyncIO Workers".

It is unclear what is being meant by those, i.e. how it maps to one of [the choices mentioned in the settings documentation for worker-class](https://github.com/benoitc/gunicorn/blob/79b9a52cc8cd664f77d43efe173291a5397df130/docs/source/settings.rst?plain=1#L1504). What _is_ said is that this mysterious [superclass of?] worker is compatible with Python 3, but that's hardly surprising given that Python 2 was deprecated 5 years ago.

It then goes on to mention `aiohttp`, which apparently comes with its own non-wsgi way of deploying applications and would require a full rewrite of your application. Mentioning this option is surprising, given Gunicorn's tagline, which includes the word "WSGI"... shouldn't this just be left over at the aiohttp docs instead?

**Comment by benoitc** [comment]
Thanks for the feedback. I have updated the doc for now with a simpel sentence in 2c38b036a2ec41a3016d2277ffba8f9b5d929b75 . .

asyncio is just an async framework, so it's totally possible as of today to use third party workers ro ruuse asyncio frameork in the backend .

**Comment by myw** [comment]
I am still extremely confused by this comment in the documentation. Upon reading it, my brain immediately asks: What? How? Where are the resources for doing this?

Are there links that could be added to simplify/clarify how this would work?

**Comment by mattjwarren** [comment]
i';m jsut trying to figure out if my django app uses acyncio calls inside it as it calls external API's,  what kind of workers do i need to use for gunicorn?
