### ISSUE TITLE
gthread timeout during launch

### ISSUE THREAD

**Issue by phwhite-coh** [benoitc/gunicorn#3242]
Hello,
 We are starting our app with the following:
`/usr/local/bin/gunicorn --bind 0.0.0.0:5000 -k gthread --threads=32 --workers=1 --timeout=1200 --log-level=debug --access-logfile=- --error-logfile=- app:create_app()`

However, we expect the app to take a long time to load, close to an hour. At the 20 minute mark we are hitting a timeout during app launch:
[2024-07-09 04:50:03 +0000] [11] [CRITICAL] WORKER TIMEOUT (pid:13)

Is there someway to change the timeout at runtime so it doesn't apply to this initial launch stage?

Thank you,
Philip

**Comment by benoitc** [comment]
If the application takes a long time to load I suggest to move th it in a separate service that could be queried using a ueue service or having this part acting a client updating the state in the web app. Either way you can use one of the wok to before the workers are started to l wait your app is loaded.  But imo it's not good to have a web app having a long time to start .
