### ISSUE TITLE
TransportError and KeyError Encountered in Flask Application

### ISSUE THREAD

**Issue by Harini080922** [benoitc/gunicorn#3249]
Our Flask application, running with Gunicorn, is encountering two critical issues:

TransportError: The application experiences a TransportError when attempting to fetch data from Google Sheets. This error, ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), indicates that the connection to the Google Sheets API is unexpectedly closed, preventing data retrieval.

KeyError: After handling the transport error, a KeyError occurs when the application tries to access the 'village','assignedmobile' keys in the data. This happens because the expected key does not exist in one or more records retrieved from Google Sheets.

These issues are disrupting the application's functionality and require immediate attention to restore proper operation.

**Comment by Harini080922** [comment]
It is showing internal sever error 500.So we thought it might be error from server

**Comment by benoitc** [comment]
@Harini080922 looks like a failure in your app that made gunicorn crashing there.
