### ISSUE TITLE
Workers time out during `sock.sendall`

### ISSUE THREAD

**Issue by the-sun-will-rise-tomorrow** [benoitc/gunicorn#3259]
Hello,

I'm not sure if this is normal behavior, but I also couldn't find anything about this specifically on the web.

Occasionally, my website crashes with the following:

```
[2024-07-30 12:34:56 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:22)
 - - [30/Jul/2024:12:34:56 +0000] "GET /some/long/audio-file.mp3 HTTP/1.0" 206 765432 "https://example.com/"
[2024-07-30 12:34:56 +0000] [22] [ERROR] Error handling request /some/long/audio-file.mp3
Traceback (most recent call last):
  File "/site/python-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/site/python-packages/gunicorn/workers/sync.py", line 184, in handle_request
    resp.write(item)
  File "/site/python-packages/gunicorn/http/wsgi.py", line 355, in write
    util.write(self.sock, arg, self.chunked)
  File "/site/python-packages/gunicorn/util.py", line 299, in write
    sock.sendall(data)
  File "/site/python-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
 - - [30/Jul/2024:12:34:56 +0000] "GET /some/long/audio-file.mp3 HTTP/1.0" 500 0 "-" "-"
[2024-07-30 12:34:56 +0000] [22] [INFO] Worker exiting (pid: 22)
```

I run Gunicorn with the default worker parameters: `gunicorn --access-logfile - app:app`

`app` is a Flask application.

In the application, the relevant file is sent using `flask.send_from_directory(...)`.

Gunicorn runs behind an Nginx reverse proxy.

I'm aware that sending static files via Gunicorn is not *optimal*, but is this behavior expected? I did not think the entire worker would crash...

What is more puzzling is that I cannot reproduce this behavior without Nginx. I thought I could make this happen if I ran Gunicorn by itself and then ran a `curl` with `--limit-rate 100`, but this works just fine, even with 1 worker and many `curl` instances.

Thanks!

**Comment by the-sun-will-rise-tomorrow** [comment]
More information:

- Happens only when `proxy_buffering` is turned off in Nginx.
- Happens with the `sync` worker class, but not `gevent`.

I ended up switching the worker class to `gevent` to work around this problem. Turning on `proxy_buffering` is probably not great when you do need to serve big files from your application...

**Comment by benoitc** [comment]
It is expecetd to run the sync worke behind a buffered proxy. You need to use an async worker or route yuuploads differently using the proxy with a sync worker.
