### ISSUE TITLE
Increase request related max limits or stop enforcing them

### ISSUE THREAD

**Issue by gnotaras** [benoitc/gunicorn#376]
Please either increase the maximum limits for --limit-request-line & --limit-request-field-size (currently hardcoded at 8190) or stop enforcing those limits once the user has used the aforementioned options in the configuration file or in the command line.

IMHO, enforcing a maximum size is not useful. I'd suggest that you provided some information in the documentation about how the application performance and security would be affected by setting those settings too high or too low, instead of hardcoding a max limit.

Thank you

**Comment by janaki-sasidhar** [comment]
> What kind of line can be > 8192 ?

datatables
