### ISSUE TITLE
Log messages from Flask's app.logger

### ISSUE THREAD

**Issue by nickhs** [benoitc/gunicorn#379]
Messages from Flask's logger such as app.logger.info("This is a message") are not saved in the gunicorn log files.

**Comment by tlatorre-uchicago** [comment]
@benoitc Is it still possible to log stderr to the logfile somehow?

**Comment by collinanderson** [comment]
`--log-file /dev/stderr`

**Comment by collinanderson** [comment]
ohh. backwards. sorry. nevermind.
