### ISSUE TITLE
WorkerTmp unlinking of temporary file causes issues under Cygwin

### ISSUE THREAD

**Issue by leftshoe** [benoitc/gunicorn#407]
The "os.unlink(name)" call in WorkerTmp seems to cause Gunicorn to be totally non-functional (crash on run) on my windows machine under cygwin. Commenting it out fixes the issue. I'm not sure if the leaking of temporary files that a comment above refers to is occuring though. This could be some posix corner case, as the code is creating a file, getting a file descriptor for it, deleting it by name (not descriptor), then opening it with the file descriptor from before it was deleted.

**Comment by WoLpH** [comment]
When using vagrant synced folders with virtualbox (`vboxsf`) this problem still occurs.

This problem can be circumvented by using the `--worker-tmp-dir` parameter and setting it to a local (non synced) filesystem.

**Comment by liquiddandruff** [comment]
Thank you @WoLpH , telling gunicorn to use a local temp dir like that fixed this problem for us.
