### ISSUE TITLE
gevent worker Exception KeyError

### ISSUE THREAD

**Issue by tbarbugli** [benoitc/gunicorn#492]
Hi,
I have a Flask app I am running with gunicorn and gevent, I noticed that when using
--log-level=critical ctrl-c triggers this exception
Exception KeyError: KeyError(4397906352,) in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
while that does not show up with default log-level

**Comment by pembo13** [comment]
With "--worker-class gevent" at least, this message fills up stderr
