### ISSUE TITLE
Nonsense tracebacks (traceback hijacking?)

### ISSUE THREAD

**Issue by aehlke** [benoitc/gunicorn#512]
I'm using gunicorn-0.16.1.

I have a Django middleware that under special circumstances (whenever the response is a 403), inside process_response, calls `traceback.format_exc()`. I would expect it to contain Django internals and the process_response method from which it was called. However, it is always the following:

File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 34, in run
    client, addr = self.socket.accept()

  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()

error: [Errno 11] Resource temporarily unavailable

I can't make any sense of this. It's obfuscating a bug I'm trying to investigate since I can't get a useful stack trace. Any hints would be appreciated, thanks!

**Comment by sohamnavadiya** [comment]
I am also facing same issue in gunicorn.

**Comment by tilgovi** [comment]
@sohamnavadiya please open a new issue and provide as much detail as you can.
