### ISSUE TITLE
error: [Errno 11] Resource temporarily unavailable - gunicorn and flask

### ISSUE THREAD

**Issue by thomaswhitcomb** [benoitc/gunicorn#514]
Related to https://github.com/benoitc/gunicorn/issues/416

I'm running flask, gunicorn and am getting the exception: [Errno 11] Resource temporarily unavailable exception in the @app.teardown_request

I'm running these versions: Flask==0.9 and gunicorn==0.17.2
Here is my stack trace:
Traceback (most recent call last):
  File "/home/tom/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 39, in run
    client, addr = sock.accept()
  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()

**Comment by michaelsd** [comment]
I don't know if it's related, but I'm also receiving the ```[Errno 11] Resource temporarily unavailable``` message when using Gunicorn with Flask and MySQL. After adding some debug statements to the ```@teardown``` method in Flask-SQLAlchemy i got the ```[Errno 11] Resource temporarily unavailable``` error in ```response_or_exc``` but only when using the autocommit feature, so changes without an explicit commit were never submitted to the database. (```SQLALCHEMY_COMMIT_ON_TEARDOWN``` was activated) 
```
@teardown
def shutdown_session(response_or_exc):
  print response_or_exc
  if app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN']:
    if response_or_exc is None:
      self.session.commit()
  self.session.remove()
  return response_or_exc
```

After a lot of searching I switched from sync worker to gevent worker (found this solution here: http://serverfault.com/questions/427600/gunicorn-django-nginx-unix-socket-failed-11-resource-temporarily-unavail/606371#606371) and now everything works as expected. I also tried the ```somaxconn``` before switching workers but was still receiving the error message. I don't know what consequences switching workers has (still new to Python and Flask) so I would like to know how I could use the sync worker without getting this message.

**Comment by tilgovi** [comment]
Maybe the sync worker is not always closing requests properly when there are error responses?

**Comment by pdodde** [comment]
If it helps, I found that our code was logging an exception when it should have been logging an error. If I remember correctly, there is one global variable in python that holds the last stack trace. Since gunicorn polls the socket over and over and catches this Errno 11 exception every time, this is the stack trace you will see if you print a stack trace when an exception hasn't actually been raised.

**Comment by michaelsd** [comment]
@tilgovi How would I debug this? There seem to be no errors in the response in my development environment where I don't use gunicorn and neither are there any errors using the gevent worker.

**Comment by ohadpartuck** [comment]
I tried the `gevent` solution and it's not closing old workers. did anyone else encounter this behaviour?

**Comment by benoitc** [comment]
@ohadpartuck what is the gevent solution? Anything reproducible?

Also this ticket has been closed if you have an issue please open a new one eventually linked to that one. It's hard to track the other way.

**Comment by ohadpartuck** [comment]
`worker_class = 'sync'` vs `worker_class = 'gevent'`

**Comment by benoitc** [comment]
still. what is the gevent solution? How can we reproduce the issue?

This ticket has been closed anyway and new discussion should happen on a new ticket. the issue may or may not be different...

**Comment by rafaelosoto** [comment]
Hey guys, just wondering if this was still being addressed or not? I've been having a similar issue. Flask seems aware but reluctant to do anything: https://github.com/mitsuhiko/flask/issues/984

**Comment by pawl** [comment]
I was able to reproduce this issue here (using the `ab` command in the readme): https://github.com/pawl/somaxconn_test

Increasing the `net.core.somaxconn` on only the container ended up fixing it.

**Comment by ilanbiala** [comment]
Is there a new issue where this is being discussed?

**Comment by eedwards-sk** [comment]
@benoitc 

I'm seeing this same trace when running with the datadog ddtrace-py library (with gunicorn 19.7.1):

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
```

```
ddtrace-run gunicorn core.app:create_app() -b 0.0.0.0:5000 -w 3
```
