### ISSUE TITLE
Gevent Worker sends requests to Django too early

### ISSUE THREAD

**Issue by Pewpewarrows** [benoitc/gunicorn#527]
Apologies in advance if this ends up being a gevent issue and not gunicorn's, but I figured I'd start here first to see if more details about this problem could be dug up.

Essentially, when using gunicorn with the gevent worker and my Django WSGI app, and the system is under heavy load, occasionally the first request a worker receives will throw this exception:

```
ImproperlyConfigured: The included urlconf myapp.urls doesn't have any patterns in it

Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "django/middleware/common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "django/core/urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "django/core/urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "django/core/urlresolvers.py", line 332, in url_patterns
    raise ImproperlyConfigured("The included urlconf %s doesn't have any patterns in it" % self.urlconf_name)
```

All subsequent requests complete successfully, and the urlconf is properly filled for them. I have not been able to reproduce this behavior when using `worker_class = 'sync'`, only with gevent.

The problem becomes even more apparent when gunicorn's `max_requests` configuration variable is set. Workers are then often reloading, and this exception becomes thrown more and more during peak traffic conditions.

Here are the relevant snippets from my requirements.txt:

```
Django==1.4.2
gevent==1.0rc1
gunicorn==0.17.2
```

I'm using supervisord to manage gunicorn, and this is the command it's running:

```
/opt/myapp/venv/bin/gunicorn -c /etc/myapp/gunicorn/myapp.conf.py myapp.wsgi:application
```

The `wsgi.py` in my project is the standard Django one, exposing the `application` variable.

Some additional settings from my gunicorn conf:

```
backlog = 2048
max_requests = 250
preload_app = True
worker_class = 'gevent'
daemon = False
```

Finally, I was able to see this issue described in two other places, linked here:
- https://groups.google.com/forum/?fromgroups=#!topic/django-users/ungIZ-JD7s4
- https://github.com/getsentry/raven-python/issues/257

**Comment by brockhaywood** [comment]
@ahmedtalhakhan Did you have any success resolving this? I'm also using tastypie and cannot find a resolution so far.

**Comment by kpshameem** [comment]
@brockhaywood Did you try reverse_lazy() instead of reverse()
