### ISSUE TITLE
Neither gevent nor eventlet are Python3 compatible. Alternatives?

### ISSUE THREAD

**Issue by zakdances** [benoitc/gunicorn#544]
I find it deeply disturbing that `Gunicorn` is Python3 compatible, but the worker classes it critically depends on are not.

What alternative Py3-compatible workers are currently available for async Gunicorn-powered apps?

**Comment by ourway** [comment]
eventlet is available for python 3.5 now

**Comment by jamadden** [comment]
gevent 1.1 is Python 3.3+ compatible, and includes Pypy support. It's currently in late beta but is stable and tested with gunicorn, and expects a final release soon. (Apologies for commenting on a closed issue but there was other traffic that might draw searchers so I hope it would be helpful.)

**Comment by berkerpeksag** [comment]
Thanks for the update, @jamadden :)
