### ISSUE TITLE
Lack of security report/update/notification policies

### ISSUE THREAD

**Issue by garrison** [benoitc/gunicorn#582]
The release notes for Gunicorn 17.5 claim

> Gunicorn is stable since a long time and there is no point to release a "1.0" now. It should have been done since a long time. 0.17 really meant it was the 17th stable version.

However, Gunicorn still lacks a coherent security policy as would be expected for a project of this claimed maturity.

* Currently, there is no documented way to privately report a security issue to the Guincorn team.

* If somehow an issue were to be reported privately, there is no documented way for how the Gunicorn developers would respond.  Would all development stop until the security issue were resolved?  Would only the most recent stable version receive an update?

* Currently, there is no good way for a user of Gunicorn to learn of security updates.  There ought to be an "announce" mailing list, which would provide people a low-traffic opportunity to receive such updates.  And the release notes ought to clearly mark (at the top) any release that has security-related patches.  [Issue 424](https://github.com/benoitc/gunicorn/issues/424) brought this up in the past, and the reporter was told to look at the release notes at <http://docs.gunicorn.org/en/latest/news.html>.  However, not a single historical item there is tagged as security-related.  One should not need to manually decode the release-notes line-by-line to decipher whether there is anything security-related requiring an immediate upgrade.

For an excellent example of a comprehensive security policy, I recommend looking at [Django's policy](https://docs.djangoproject.com/en/dev/internals/security/).

**Comment by benoitc** [comment]
fixed. security issues can be sent to security@gunicorn.org .

**Comment by tilgovi** [comment]
I don't think this is documented anywhere. Please close again if I'm wrong.

**Comment by benoitc** [comment]
mmm true forgot to add to the doc. It's only on the main site right now. I am fixing it.
