### ISSUE TITLE
Body.read(), Body.readline() and Body.readlines() are broken for Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by fafhrd91** [benoitc/gunicorn#605]
If request uses 'chunked' transfer encoding and chunk size is smaller than 1024 bytes
then Body's readxxx methods blocks forever.

**Comment by genxstylez** [comment]
@benoitc 

I am having issue with nginx + gunicorn + django.

When I am using chunked transfer encoding, the file I get is a partial one, not a complete jpg.

Not really sure where my problem is, maybe you can help me out here.

client:
`curl -v -X POST  --header "Transfer-Encoding: Chunked" -d @a.jpg "http://127.0.0.1/upload/"`

nginx:
```
location / {
            proxy_pass http://localhost:8000;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 20m;
            client_body_buffer_size 128k;
            proxy_connect_timeout 90;
            proxy_send_timeout 90;
            proxy_buffering off;
            proxy_temp_file_write_size 64k;
        }
```

django:
```python
@csrf_exempt
def upload(request):
    print('body:', request.body)
    # print('meta:', request.META)
    mode = 'wb'
    if os.path.exists('a.jpg'):
        mode = 'ab'
    with open('a.jpg', mode) as f:
        f.write(request.body)

    return HttpResponse('yes')
```

gunicorn:
```python
import multiprocessing

workers = (2 * multiprocessing.cpu_count()) + 1
worker_class = 'gevent'
loglevel = 'debug'
accesslog = '-'
errorlog = '-'
forwarded_allow_ips = '*'
secure_scheme_headers = {
    # 'X-FORWARDED-PROTOCOL': 'ssl',
    'X-FORWARDED-PROTO': 'https',
    # 'X-FORWARDED-SSL': 'on',
}
preload_app = False
limit_request_line = int(4094 / 4)
limit_request_fields = int(100 / 2)
keepalive = 2 * 2
```

**Comment by benoitc** [comment]
hrm what's your version of django?

**Comment by genxstylez** [comment]
1.9.6

I just tried with a 114 bytes text file, and the upload works, but the `\r\n` is truncated

e.g.
original 
```
first line here
second line here
```

uploaded
```
first line here second line here
```

**Comment by benoitc** [comment]
@genxstylez what's your version of python?

**Comment by benoitc** [comment]
@genxstylez so far on a simple wsgi app I can't reproduce. I uploaded a new example using readline in d3307cdfa52246354527995722fd652ed9ffa2e8 which gave me the following results:

On server side:

```sh
(gunicorn_py3)[examples] gunicorn -w3 readline:app                                                  17:24:12  ☁  master ☂ ⚡ ✭
[2016-05-14 17:24:13 +0200] [16716] [INFO] Starting gunicorn 19.5.0
[2016-05-14 17:24:13 +0200] [16716] [INFO] Listening at: http://127.0.0.1:8000 (16716)
[2016-05-14 17:24:13 +0200] [16716] [INFO] Using worker: sync
[2016-05-14 17:24:13 +0200] [16719] [INFO] Booting worker with pid: 16719
[2016-05-14 17:24:13 +0200] [16720] [INFO] Booting worker with pid: 16720
[2016-05-14 17:24:13 +0200] [16721] [INFO] Booting worker with pid: 16721
b'test\\r\\ntest2\\r\\n'
```

On the client side:

```sh
(gunicorn_py3)[examples] curl -XPOST -d'test\r\ntest2\r\n' -H"Transfer-Encoding: Chunked" http://localhost:8000
test\r\ntest2\r\n% 
```

Do you have any simple django app I could use for a test?

**Comment by genxstylez** [comment]
@benoitc let me upload it, I think my python is 2.7.10, btw, I am using gevent worker

**Comment by benoitc** [comment]
@genxstylez ok i didn't tested under python 2.7 (using latest 3.5) but gevent definitly works (at least 1.1.1)

On server side:

```sh
(gunicorn_py3)[examples] gunicorn -w3 -k gevent readline:app                                          17:54:37  ☁  master ☂ ✭
[2016-05-14 17:54:39 +0200] [17306] [INFO] Starting gunicorn 19.5.0
[2016-05-14 17:54:39 +0200] [17306] [INFO] Listening at: http://127.0.0.1:8000 (17306)
[2016-05-14 17:54:39 +0200] [17306] [INFO] Using worker: gevent
[2016-05-14 17:54:39 +0200] [17309] [INFO] Booting worker with pid: 17309
[2016-05-14 17:54:39 +0200] [17310] [INFO] Booting worker with pid: 17310
[2016-05-14 17:54:39 +0200] [17311] [INFO] Booting worker with pid: 17311
b'test\\r\\ntest2\\r\\n'
```

On client side:

```sh
(gunicorn_py3)[examples] curl -XPOST -d'test\r\ntest2\r\n' -H"Transfer-Encoding: Chunked" http://localhost:8000
test\r\ntest2\r\n% 
```

**Comment by benoitc** [comment]
@genxstylez ok waiting for the app so i can possibly reproduce it :)

**Comment by genxstylez** [comment]
@benoitc https://github.com/genxstylez/test_chunked_upload

**Comment by genxstylez** [comment]
just run `gunicorn -b 0.0.0.0:8000 -c config/gunicorn.py test1.wsgi`

**Comment by benoitc** [comment]
@genxstylez thank! I reproduced it.

So it appears that django doesn't handle anymore chunked encoded request. Just sending line and reading the body failed for me. The lines causing the issue are there:

https://github.com/django/django/blob/master/django/core/handlers/wsgi.py#L109-L112

If it doesn't find a content-length it set the size to 0. Which stop the body to be read:
https://github.com/django/django/blob/master/django/core/handlers/wsgi.py#L41

**Comment by benoitc** [comment]
@genxstylez look #1265 . It is solving your issue. Maybe you can see with people from Django what they think about it?

**Comment by genxstylez** [comment]
Thanks, so there's no workaround at the moment?

**Comment by benoitc** [comment]
https://docs.djangoproject.com/en/dev/ref/request-response/#streaminghttpresponse-objects may fix your issue. Let me know :)

**Comment by benoitc** [comment]
nm it's about the response. I need some cafe

**Comment by genxstylez** [comment]
@benoitc ye.. it's response, not request. I read it.
