### ISSUE TITLE
Don't use do_handshake_on_connect=False for SSL sockets

### ISSUE THREAD

**Issue by dsuch** [benoitc/gunicorn#617]
Hello,

I'm working on a feature to make it possible to easily access client certificates in gunicorn-based servers but there is one thing I believe is a bug that was not unearthed before.

In GeventWorker.run, when creating ssl_args, there is explicit 

``` python
do_handshake_on_connect=False
```

However, a couple of lines later there is

``` python
for s in self.sockets:
    s.setblocking(1)
```

They can't really be used together. do_handshake_on_connect=False means that your socket is non-blocking and you will call do_handshake on a socket later on.

http://docs.python.org/2.7/library/ssl.html#ssl.wrap_socket

But this is a blocking socket and do_handshake is never called.

So, when in the feature I'm working on I make a call to sock.getpeercert(True), the certificate is always None, as reported in Python tracker

http://bugs.python.org/issue19095

Hence I propose doing anyway with explicitly assigning do_handshake_on_connect=False - it was probably part of some other code originally and should never be used in this place, if I'm not mistaken?

Many thanks!

**Comment by benoitc** [comment]
@malthe  what is the ELB  configuration?

**Comment by malthe** [comment]
@benoitc what part of it do you mean specifically? Also, note that we eventually decided on ``uwsgi`` (because of this issue mostly) and no longer use ``gunicorn`` so I am not really able to follow up much on this issue.

**Comment by benoitc** [comment]
@malthe I didn't get the notification on the closed issue, sorry for that. (and a good reason to tell in the contributing doc to only link to closed issue but opening a new one).

About waiting to read more on the SSL sockets, did you configured keepalive? was connection draining enabled?Using the eventlet client to solve the issue could mean indeed that was a keepalive issue.

**Comment by malthe** [comment]
It might simply be a keep-alive timeout mismatch that causes ``gunicorn`` to slowly drain on available connections such that eventually, no new connections can be made.

**Comment by benoitc** [comment]
OK, thanks anyway and sorry for my very late answer again

**Comment by pankit** [comment]
Hi @dsuch ,

I am trying to access the client cert so that I can load it and verify a few things.
I know that gunicorn can do basic handshake stuff by verifying the signing authority on the client cert but I want to open it inside my python app.
My set up is gunicorn server + flask app

Let me know if you have an idea.

Thanks,
Pankit

**Comment by dsuch** [comment]
Hi @pankit - I have not used this part of gunicorn in quite a while but essentially, when you accept and HTTP request, there should be a WSGI key called ```gunicorn.socket``` or in a similar manner (sorry, I really forget).

This key points to the TLS socket that accepted the connection, i.e. this is the object that is returned by ```ssl.wrap_socket``` so you can call ```.getpeercert()``` on it to obtain the client certificate.

That's how it worked like the last time I used it which was some two years ago around September 2013.

**Comment by pankit** [comment]
Are you pointing to gunicorn.sock?

**Comment by dsuch** [comment]
@pankit - I honestly can't recall its name. I remember the principle but not any exact details, it was two years ago. Thanks.

**Comment by pankit** [comment]
Thanks! Not a problem.  I l try to find it. But ultimately you were able to make it work. right?
Were you also using flask app?

**Comment by dsuch** [comment]
Yes, I was able to make it work without problems. Ultimately for reasons unrelated I went a different route but I even found a piece of code that read TLS certificates from client connections.

I wasn't using Flask but it doesn't matter. The certificate is part of the WSGI environment, it's just a dictionary, no matter the framework.

https://github.com/zatosource/zato/blob/3a804fecaeb331f93c1393db2024122cfa3eaafe/code/zato-server/src/zato/server/base/parallel.py#L126

**Comment by pankit** [comment]
Just putting for someone who has  similar doubt in future.
The way I got hold of the socket object is the same as pointed out by @dsuch 
I was using flask + gunicorn
Here is  code snippet
@app.before_request
def checkssl():
  sock = request.environ['gunicorn.socket']
  cert = sock.getpeercert(binary_form=True)
  x509 = crypto.load_certificate(crypto.FILETYPE_ASN1, cert)

Now you can use X509 object to validate whatever you need. :)
