### ISSUE TITLE
Including the address information in error log messages.

### ISSUE THREAD

**Issue by aronkyle-lightspeedretail** [benoitc/gunicorn#664]
It would be nice if the error logs include the address info of the remote connection attempting (and failing) to connect of SSL.

**Comment by benoitc** [comment]
Rethinking of it, we don't always have it and such address is already be part of the access logs. It's easy to compare both logs when needed. So closing this issue.

**Comment by tilgovi** [comment]
All the worker types I test just now (gevent, eventlet, sync, threaded) report a debug message in the error log.

If anyone finds this and wants to harmonize behavior, there does appear to be work to be done making sure that all worker types log similarly and that connections are consistently dropped. Some workers seem to drop the connection immediately, others will cause the request to hang.
