### ISSUE TITLE
Setting SCRIPT_NAME results in error

### ISSUE THREAD

**Issue by C-o-r-E** [benoitc/gunicorn#679]
I am trying to run a django app on a path that looks like mysite.com/foo.

When setting SCRIPT_NAME to /foo gunicorn would error with an index out of bounds. The offending line can be found here: https://github.com/benoitc/gunicorn/blob/master/gunicorn/http/wsgi.py#L193

A little bit of debugging revealed that 

``` python
path_info = '/' 
```

and

``` python
script_name = '/foo'
```

so doing 

``` python
path_info = path_info.split(script_name, 1)[1]
```

results in error. Looks like a quick fix, but I'm not sure about the implications of modifying this.

**Comment by Rendiere** [comment]
Hey, I'm experiencing the same issue as @C-o-r-E. 

The temp fix posted above - commenting out `path_info.split(script_name, 1)[1]` fixes the issue for me. However, thats a temp fix...

Unfortunately I've already tried removing the trailing slash and it didnt fix the issue. 

I'm also using nginx with a pretty-much exact configuration (just a different context route). 

Any ideas?

**Comment by benoitc** [comment]
@Rendiere what let you think it's the same issue? :) Can you open a new ticket that may relate to this one with the log you get and the conf you're using ? That would help a lot.

**Comment by krsnik93** [comment]
seeing same...

**Comment by benoitc** [comment]
@krsnik93 please open a new ticket reffering this one with the config you're using. Check also your proxy path.
