### ISSUE TITLE
Add HAProxy config to deploy page

### ISSUE THREAD

**Issue by davisp** [benoitc/gunicorn#73]
<pre>
# HAProxy Config
#===========================

global
    daemon

# nginx
backend nginx
    mode http
    timeout connect 10s
    timeout server 30s
    server nginx 127.0.0.1:8080 maxconn 512

# gunicorn
backend gunicorn
    mode http
    timeout connect 5s
    timeout server  86400000
    server gunicorn 127.0.0.1:8000 maxconn 10000 check

frontend http_proxy
    bind :80
    mode http
    timeout client 86400000
        default_backend nginx
    acl websocket hdr(Upgrade) -i WebSocket
        use_backend gunicorn if websocket
    option forwardfor
    

# Nginx Config
#===========================

upstream gunicorn {
    server 127.0.0.1:8000;
    # server unix:/tmp/gunicorn.sock fail_timeout=0;
}

server {
    listen 8080 default;
    
    location / {
        proxy_pass http://gunicorn;
    }
}

# credit: http://stackoverflow.com/questions/2419346/can-nginx-be-used-as-a-reverse-proxy-for-a-backend-websocket-server/2600901#2600901
</pre>

**Comment by luhn** [comment]
Important to note is that HAProxy can't actually buffer requests.

> With `option http-buffer-requests`, HAProxy still won't buffer the whole
> request in all cases. This would be mostly impossible since HAProxy
> buffers requests in memory which is often pretty limited.

https://www.mail-archive.com/haproxy@formilux.org/msg23074.html
