### ISSUE TITLE
got 504 when running multiple Gunicorn instances

### ISSUE THREAD

**Issue by pengfei-xue** [benoitc/gunicorn#734]
Hi,

Not sure if this issue has been found before, but i got this for my deployment using supervisord and gunicorn for two django sites within one server. I'm sure my nginx configuration and gunicorn configuration is correct(different server name, different port).

supervisord==3.0b1
gunicorn==18.0
Django==1.6.2

Only one Django site can run, the other only can get request for nginx, but no response, the result is 504, this is very weird.

If i stop that running django instance, the another `cannot run` instance now become runnable.

**Comment by benoitc** [comment]
not reproduced. feel free to open a new ticket if it happens again.

**Comment by pengfei-xue** [comment]
sorry, i didnt provide feedback in time, already lost the environment, agree to close this issue for now, if someone got this again, we can reopen it. :)

thanks.

**Comment by rohitkriitkgp** [comment]
Guys,
Even i have the same issue. If i use multiple workers, it is giving me django keyerror but If i use 1 worker, it is working perfectly fine. 
Any Help will be appreciated. Thanks

**Comment by pengfei-xue** [comment]
this may cause by supervisor, try to kill supervisor, and make sure all your instances are killed. then try to restart it again. it may work.

**Comment by rohitkriitkgp** [comment]
@pengfei-xue , I am not using any supervisor.

**Comment by benoitc** [comment]
@rohitkriitkgp how to reproduce it? can you providena full trace? what return the check-config command line argument?

i tested wit the example appliction and I can't reproduce it right now so any detail is welcome :)

**Comment by rohitkriitkgp** [comment]
@benoitc, check-config is not giving any result/error. I am working on nginx, gunicorn and django application. Below is my gunicorn setting:

import multiprocessing
bind = '0.0.0.0:8182'
backlog = 2048
workers = multiprocessing.cpu_count() * 2 + 1
worker_class = 'sync'
worker_connections = 100
timeout = 300
keepalive = 2
debug = False
spew = False
daemon = True
pidfile = None
umask = 0
user = None
group = None
tmp_upload_dir = None
loglevel = 'debug'
proc_name = None
logfile = some directory 
errorlog = some directory
accesslog = some directory

wsgi configuration:
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "foo")
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

Thanks

**Comment by rohitkriitkgp** [comment]
Found the solutions. I was using local cache and the session was not able to communicate with multiple workers. I changed to memcached and it starts working. 

Thanks
