### ISSUE TITLE
add flapping option 

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#744]
#568 discussed the possibility to have an option to retry worker restart on failure. This could be done by adding a flapping option. Using this option it would be possible to set the number of allowed restart available in a time window before considering that the worker can't be booted.

Thoughts?

**Comment by adampiskorski** [comment]
It would be useful for development with hot reloading, where you accidentally have an import error for example while your server is up.

**Comment by bsplosion** [comment]
Has there been any progress on this front?  We restart workers frequently (via max_requests settings) to prevent certain symptoms from arising, and it's possible for a restart to randomly experience an import error, though with extreme infrequency (once for several thousand restarts).  

This random import error during worker restart had the effect of shutting down the entire service, which is highly undesirable, and a reattempted worker boot would have corrected the issue.  If there's no way to request the master retry the worker boot, we'll have to resort to monitors from outside the service to trigger a restart, which is not ideal.

**Comment by tilgovi** [comment]
No progress. No one has submitted a PR.
