### ISSUE TITLE
gunicorn 19.0: empty remote addr on unix domain socket?

### ISSUE THREAD

**Issue by jeroenp** [benoitc/gunicorn#797]
Hi,

I've just upgraded gunicorn 18.0 to 19.0. Now REMOTE_ADDR is an empty string, where before it listed the remote ip ("real ip"). 

Is that an intentional change? 

My setup snippets:

gunicorn:

```
...
bind = 'unix:/var/run/webapp/xyz.sock'
```

reverse proxy, nginx (1.4.1):

```
    upstream xyz_server {
        server unix:/var/run/webapp/xyz.sock;
    }
...
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $server_name;
    proxy_redirect off;
    proxy_pass http://xyz_server;
```

My Django says that request.META['REMOTE_ADDR'] == ""

**Comment by benoitc** [comment]
It appeared that we also removed the code handling the X-Forwarded-Header so I am postponing to the next release. Also see my comment in python-web-sig/wsgi-ng#11 .
