### ISSUE TITLE
Fix utils.is_fileobj for streaming responses from requests

### ISSUE THREAD

**Issue by davisp** [benoitc/gunicorn#805]
Turns out that the utils.is_fileobj breaks for streamed responses from the requests library due to how we check for a fileno() function and the exception raised by urllib3.

https://github.com/benoitc/gunicorn/blob/19.0/gunicorn/util.py#L511-L521
https://github.com/kennethreitz/requests/blob/v2.3.0/requests/packages/urllib3/response.py#L294-L301

Obvious fix is to add the IOError type to the exception list. PR to follow shortly.

**Comment by fmarczin** [comment]
This bug can still be triggered by file-like objects which wrap objects without a `.fileno()` method. This happened to me in combination with pyfilesystem (https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/iotools.py#L31).

The simplest fix would be to add `AttributeError` to the list of exceptions, just like in the commit above (https://github.com/benoitc/gunicorn/commit/fc364cca7d406464d09cb628756d81dc52a4204d).

**Comment by tilgovi** [comment]
@fmarczin this code isn't used anymore on master as of 6b92575e004da36deed0a952cf342a2eb8d461c7. If you could reproduce problems before and can check again on master that would be great.
