### ISSUE TITLE
How to prevent SIGWINCH?

### ISSUE THREAD

**Issue by JohnHerry** [benoitc/gunicorn#811]
Hi, I use gunicorn to start a new app. but after a while the master will use SIGWINCH to kill the worker, and as a result, I can not access the page any more. Is there any way to ignore WINCH  signal in worker?

**Comment by rlrosa** [comment]
i have a similar issue, but i think the winch messages are unrelated. when my server is running fine i see them and it keeps running.
i suspect i have a bug that is causing a deadlock somewhere, and this is unrelated.
you may have a similar issue. try resizing the window while your sever still runs ok to see if the winch messages cause problems or are unrelated.
