### ISSUE TITLE
Improve the user experience: plugin everywhere

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#837]
Today workers, loggers and application (way to launch the gunicorn runtime) can be easily customised. You can use your own worker, logger or embed gunicorn in your own application. But until now most of the time they are included in the code of gunicorn, which imply that any revision of a worker needs a full update where the runtime didn't need any change. Also a worker upgrade due to a library change (like in gevent, tornado, aiohttp) will have to wait sometimes due to other waiting changes in master.

I propose to fix that by introducing a way to install plugin directly using the gunicorn command line (or by just using pip if possible).

For example the command line `gunicorn install gunicorn-gevent` would install the worker for gevent.  Ideally we could install it using pip, but then **we need a way to register it** in gunicorn so we can simply use the command line `gunicorn -k gevent myapp:app` to use the gevent worker instead of passing a full python path.

Workers/Loggers that could be extracted:
- gevent
- eventlet
- tornado
- asyncio*
- logger-estatsd
- logger-syslog
- ..

Things to consider:
- how to install worker/loggers dependencies
- how to extend easily the options given to the command-line that depends on the worker

> **Note**:  such feature would allows someone to provides a simple http worker without the WSGI interface...

Thoughts?

**Comment by berkerpeksag** [comment]
> But maybe we can also have a gunicorn-legacy or gunicorn1 package ?

We can just announce gunicorn 20 as a backward incompatible release. Of course, that means we need to maintain 19.x for a while, but that's easier than maintain two separate package and probably two separate repos.

Recent versions of pip won't install beta packages directly, so we can mark gunicorn 20 as beta and if people just do `pip install -U gunicorn` to upgrade their gunicorn installation, it won't break anything. Once we're happy with the quality of gunicorn 20, we can just release gunicorn 20 final.

**Comment by benoitc** [comment]
sounds like a good plan. 


If we are all agree to that I will move the code first to the org and then we could start in a branch.
