### ISSUE TITLE
Connection not closed properly after responding with 401

### ISSUE THREAD

**Issue by c-nichols** [benoitc/gunicorn#872]
Running gunicorn behind nginx.  Been having a strange issue where sometimes my server responds with a 502 Bad Gateway instead of a 401 Unauthorized.  (this is bad for me because someone else's legacy software is looking for a 401 before resubmitting request w/ username and password.)

After some tcpdump sleuthing, here's what I found:
Gunicorn is indeed sending a 401 Unauthorized response.  It sends it quickly; before nginx is finished sending the POST body in fact.  But Gunicorn also sends a RST packet to nginx right behind the 401 unauthorized message.  This causes a race between the OS and nginx.  It's a race to see if nginx can process the 401 message before the OS processes the RST packet and closes the socket for good.  If the RST packet gets processed first, when nginx goes to dig the 401 message out of the socket, the call errors out and lacking a response, nginx returns a 502 Bad Gateway.

Gunicorn should close the socket gracefully in this case, sending a fin packet instead of a RST packet.  This will allow nginx to dig the 401 Unauthorized response out of the socket even if it has already been closed.

I know this might be a tough one to test, if I can be of any more help please let me know.

**Comment by tilgovi** [comment]
Verdict? Should we do anything?

**Comment by benoitc** [comment]
@tilgovi impo we should open a new ticket to discuss the design of the lingering pool. Thoughts?

**Comment by tilgovi** [comment]
+1

**Comment by benoitc** [comment]
superseded by #1025 all discussions now happen in that ticket.
