### ISSUE TITLE
Threaded workers accept connections even when no ready thread exist

### ISSUE THREAD

**Issue by tahajahangir** [benoitc/gunicorn#908]
When using threads (with sync worker class), worker accepts connection even when all threads is busy. In our environment,  sometimes (because a deadlock in cairocffi library) all threads of a worker are locked, but worker continues accepting connections until limit of open-files is reached.

I looked at the code in `gthread.py` and it regards the `worker_connections` setting (despite what the documentation says, that it only affects Eventlet and Gevent workers).

I think in threaded workers, `worker_connections` always should be set to number of threads.

**Comment by eino** [comment]
Hi, 
we met a very similar-looking issue with the current version (20.1). Using gthread workers, gunicorn sometimes sent requests to workers already handling a request, despite other ones being available.
The specificity of our case (which maybe generates the issue) is that those workers were handling a persistent connection (websocket). Thus they were occupied, but not necessarily "busy" handling data at the moment the request arrived.
This happened with gthread workers, even if using only 1 thread.

Switching to gevent workers solved the issue for us.
Anyway, thank you for the great tool! Sorry that I can't create a prototype reproducing the bug right now.
