### ISSUE TITLE
Close listening socket immediately after stop signal received

### ISSUE THREAD

**Issue by tahajahangir** [benoitc/gunicorn#922]
When stopping gunicorn, server should wait for current requests to complete, but this may take several seconds (even 30 seconds, with the default timeout). Clients connecting in this interval, will wait forever, and will receive connection-reset error after server successfully stopped.

When using two or more gunicorn servers behind a reverse proxy (like nginx), this behavior leads to unreasonable raise in total upstream time (normally, real clients won't wait for 30 seconds, and will close tab, or hit refresh).

This also reduces impact of #901 (locked connections). Also related to #908

**Comment by pikeas** [comment]
Was this ever fixed?

**Comment by benoitc** [comment]
I din't tested it yet. thanks for the head-up it's on the todo for today
now!

**Comment by mleventi** [comment]
+1 on getting this in

**Comment by benoitc** [comment]
Re-reading this issue, I think we are missing some details, was the server closed using SIGQUIT or SIGTERM? It's totally expected to not close immediately  the socket on SIGTERM while SIGQUIT close it immediately. What did I miss?

**Comment by tilgovi** [comment]
We're not closing the socket immediately which I think means that a
downstream proxy will keep trying to pass connections to gunicorn. I think
the request here is that during shutdown we close the listening socket
quickly.

**Comment by tilgovi** [comment]
- [x] Close in arbiter shutdown (#1221)
- [ ] Close in workers at graceful termination
  - [x] sync (not applicable)
  - [x] gevent
  - [ ] eventlet (#1222)
  - [ ] thread
  - [ ] asyncio

**Comment by tilgovi** [comment]
I believe that this can be marked complete as soon as the two PRs I have open for eventlet and the threaded worker are merged.

**Comment by benoitc** [comment]
@tilgovi :+1:

**Comment by tilgovi** [comment]
Closing as all my open PRs have been merged. Opened #1236 to track future work arising from this discussion and related PRs.
