### ISSUE TITLE
For Flask applications, can you specify a custom request handler?

### ISSUE THREAD

**Issue by gregeinfrank** [benoitc/gunicorn#934]
I'm looking to do something like this: http://blog.sendhub.com/post/48832423565/hacking-flask-a-success-story which is using a subclass of werkzeug's BaseRequestHandler. You can specify a request_handler in flask's web server directly like so:

`app.run(host='0.0.0.0', port=port, request_handler=MyFancyRequestHandler)`

But is there a way to specify a `request_handler` if I'm running my Flask app through `gunicorn`?

Thanks!

**Comment by anhdv-teko** [comment]
> Since you've installed Gunicorn globally, you probably need to append the current directory to `PYTHONPATH`. Please try something like `PYTHONPATH=.:$PYTHONPATH`.

This worked for me!
