### ISSUE TITLE
BrokenPipeError being occasionally thrown with eventlet worker

### ISSUE THREAD

**Issue by kaniini** [benoitc/gunicorn#939]
In some cases on a very busy application, we get:

```
[2014-11-17 04:18:49 -0500] [13520] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gunicorn/workers/async.py", line 108, in handle_request
    resp.write(item)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/http/wsgi.py", line 344, in write
    util.write(self.sock, arg, self.chunked)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 301, in write
    sock.sendall(data)
  File "/usr/local/lib/python3.4/site-packages/eventlet/greenio.py", line 375, in sendall
    tail = self.send(data, flags)
  File "/usr/local/lib/python3.4/site-packages/eventlet/greenio.py", line 358, in send
    total_sent += fd.send(data[total_sent:], flags)
  File "/usr/local/lib/python3.4/site-packages/eventlet/greenio.py", line 351, in send
    return fd.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe
```

The reason why is because the user closed out of the tab while it is loading (or otherwise halted navigation).  As such, it is probably not worthwhile to log this as a fatal error.

**Comment by benoitc** [comment]
working on it.

**Comment by benoitc** [comment]
so EnvironmentError is an alias to OSError in python 3.4, same for socket.error. I wonder why the exception is not catched then...

**Comment by kaniini** [comment]
Please let us know if you have any patches you would like tested in a production environment, we would like to remove this false-positive from our error logs.

**Comment by berkerpeksag** [comment]
The patch may cause regressions on Python 2 and Python 3.2.

In Python 2 and Python 3.2:

* socket.error is a subclass of IOError
* IOError is a subclass of EnvironmentError

In Python 3.3+:

* socket.error and EnvironmentError are aliases of OSError

Another subtle bug is that ssl.SSLError is also a subclass of OSError on Python 3.3+.

We'll probably need to add some shim to `gunicorn/_compat.py`. I also don't understand this exception reraising logic: https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/async.py#L57-64

**Comment by berkerpeksag** [comment]
Oh, and IOError is also a an alias of OSError on Python 3.3+. So socker.error wasn't catched because `gunicorn.http.errors.NoMoreData` is a subclass of IOError which is an alias of OSError on Python 3.3+.

Here is a WIP branch without compat shim: https://github.com/berkerpeksag/gunicorn/compare/exc-refactor Please try it on Python 3.3+.

**Comment by kaniini** [comment]
@berkerpeksag I am seeing errors on that branch :(
