### ISSUE TITLE
Gunicorn freeze

### ISSUE THREAD

**Issue by rtpm** [benoitc/gunicorn#942]
Gunicorn 19.1.1
Django 1.7.1
nginx 1.0.10

After upgrading to the latest gunicorn I am having weird problem (gateway timeout 504) with backend running
Django + PostgreSQL.
It hangs after few days. I see gunicorn (master + workers) processes running fine, but no traffic is being served.

I am using damontools package for running gunicorn with command:

exec setuidgid $USER gunicorn -b ${TCP} -w 3 --timeout=60 --max-requests=1000 site.wsgi 2>&1

NO entries in daemontools/ django logs. 
Restarting gunicorn (svc -d service && svc -u service) helps.

Has similar problems some time ago, but upgrading gunicorn resolved the problem. After few months of stable serving, I upgraded gunicorn and the problem appeared again.

**Comment by rtpm** [comment]
Oups It happened again.  I will run another gunicorn instance and switch nginx to this. Maybe that will let me do some process debugging.

**Comment by rgdaddio** [comment]
Is there any follow up to this since Jan 9?

**Comment by benoitc** [comment]
well are you reproducing it? Any help to reproduxing the issue would be helpful anyway since i never reproduced it myself. Can you alao tell me which version did you try?

**Comment by rgdaddio** [comment]
Thanks for you reply & sorry for the late response. Not able to reproduce in a repeatable way yet but the issue we saw was similar to the OP.

We are using version 19.1.1.

**Comment by benoitc** [comment]
old issue. no action since awhile. closing it.

**Comment by Immortalin** [comment]
@benoitc ...I am getting this issue now

**Comment by tilgovi** [comment]
@Immortalin there's a lot in this thread from different people and it may not all be the same. Can you open a new issue and provide as much detail as you can that will help us debug with you?

**Comment by Immortalin** [comment]
Actually ignore this, issue fixed.

**Comment by anpjai** [comment]
Can anyone suggest if the issue is fixed. I amm using gunvorn with --dameon option to make my flask web app up and running in edgenode. After some hours of inactivity I see my app  is not responding.As soon as I login back to edgenode it is up again and then remains up and running.Can ny one suggest what is the problem here.

**Comment by benoitc** [comment]
@anpjai issue has been closed, please open a ticket with a way to reproduce it if you still have some issues as it may be a different topic.

**Comment by Krisnadi** [comment]
> Oups It happened again. I will run another gunicorn instance and switch nginx to this. Maybe that will let me do some process debugging.

Hi @rtpm do you have any update about this issue?
Currently I'm experiencing the same issue. My django hang almost everyday and i need to restart the gunicorn to make it run again. The log is similar with yours, have a lot of `Ignoring EPIPE`.
Before this issue happened, recently I installed Nginx amplify for monitoring, but not sure that this is the cause.
Any help would be appreciated. Thanks.

**Comment by rtpm** [comment]
@Krisnadi  Haven't found the reason, sorry. Changed my infrastructure since then. Try with different gunicorn versions. Hope you find the solution!

**Comment by jddeltoro** [comment]
I'm sorry to say that the same thing is happening to me:
gunicorn=20.1.0
Django==3.2.12

**Comment by DmytroLitvinov** [comment]
We also started to get freezes of Gunicorn workers. For last days we can't indentify the root caouse of that problem. Any glues/ideas/thoughts in lead would be appreciated.

We have Django, DjangoCMS, django-channels stack.
Our packages:
gunicorn==20.1.0
uvicorn[standard]==0.18.2
django==3.2.14
channels==3.0.5
channels-redis==3.4.0

CMD to run gunicorn:
`gunicorn asgi -w 12 -b unix:/home/ourProjectName/tmp/ourProjectName_main_gunicorn.sock -k core.workers.DjangoUvicornWorker --log-level debug --max-requests 2000 --max-requests-jitter 400 --timeout 75`

Where DjangoUvicornWorker is next class:
```
class DjangoUvicornWorker(UvicornWorker):
    """
    Fixing issue at Sentry:
    TypeError: An asyncio.Future, a coroutine or an awaitable is required

    https://github.com/encode/uvicorn/issues/185
    """

    CONFIG_KWARGS = {
        'loop': 'uvloop',
        'http': 'httptools',
        'lifespan': 'off',  # lifespan is not handled by django channels for now
        'ws': 'wsproto',
    }
  ```

**Comment by KyleDulay** [comment]
> I'm sorry to say that the same thing is happening to me: gunicorn=20.1.0 Django==3.2.12

Were you able to figure this out?
