### ISSUE TITLE
Integrate flake8 into Travis CI

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#947]
We can ignore E126, E128, E129, E501, E302 checkers and vendored files such as `argparse_compat.py`, 'six.py`and`selectors.py`.

**Comment by benoitc** [comment]
what about linking lanscape.io results also?

**Comment by benoitc** [comment]
bump?

**Comment by berkerpeksag** [comment]
Many of the landscape.io results are false-positives. It looks like a good service, but I don't think it's worth to use it now. See https://landscape.io/github/Swiftea/Swiftea-Crawler/19/modules/crawler/stats.py for example. `FileNotFoundError` is in Python for almost 5 years now.

**Comment by berkerpeksag** [comment]
I also saw landscape.io results in a project that I contributed and its reports looked similar to the example I gave in my earlier comment.

**Comment by tilgovi** [comment]
Hmmm. I've been using it with great results. It uses prospector, which is
very configurable. We may just need a config file that fits our level of
strictness.

I can take a stab.

**Comment by berkerpeksag** [comment]
That would be great :)

**Comment by benoitc** [comment]
is this ticket still actual? If not maybe we can close it?

**Comment by berkerpeksag** [comment]
I can take a stab next week if @tilgovi doesn't beat me to it.

**Comment by benoitc** [comment]
bump.Can someone describe the change needed to close the issue?
