### ISSUE TITLE
Reloader should survive SyntaxErrors

### ISSUE THREAD

**Issue by frabcus** [benoitc/gunicorn#964]
When using `--reload` if you save a file with a syntax error, gunicorn exits completely. This defeats the point and use of `--reload` during development.

The code is in `init_process` in `gunicorn/workers/base.py`. The callback for the Reloader kills the worker, forcing them to reload. The process exits when there is a syntax error.

Obvious ways to fix it would be: 1) Make the callback or reloader check the syntax of the Python files that have changed (with "compile") and output the syntax error and don't kill the process if they have a syntax error, 2) When in `--reload` mode catch SyntaxErrors in the process startup code.

[Flask-Failsafe](https://pypi.python.org/pypi/Flask-Failsafe/) handles a similar case for simpleserver, and might have useful code in.

**Comment by ohadpartuck** [comment]
+1 any ETA on this @benoitc

**Comment by GMLudo** [comment]
+1 for this feature.
We use Gunicorn in [API-Hour](www.api-hour.io/#api-hour) on prod and dev environment, it's certainly a nice to have.

**Comment by tilgovi** [comment]
@ohadpartuck @GMLudo open a pull request

**Comment by tilgovi** [comment]
Closed by #994

**Comment by benoitc** [comment]
thanks I forgot that!
