### ISSUE TITLE
OSError: Bad file descriptor raised when using Python 3.4 and USR2 signal

### ISSUE THREAD

**Issue by prestontimmons** [benoitc/gunicorn#978]
After upgrading a Python 2 application to Python 3.4, I noticed an ``OSError`` is raised when sending a ``USR2`` signal to the process. I believe the problem is related to a change in socket behavior in Python 3.4:

https://docs.python.org/3.4/library/os.html#fd-inheritance

I don't know if this is a correct fix, but adding the below lines to ``Arbiter.start`` made the ``OSError`` go away:

```python
for sock in self.LISTENERS:
    sock.set_inheritable(True)
```

This is using version ``19.2.1``.

**Comment by berkerpeksag** [comment]
The fix LGTM. We probably will need to add a helper function in `gunicorn/_compat.py`.

**Comment by tilgovi** [comment]
LGTM
