### ISSUE TITLE
Allow configuring a different reloader

### ISSUE THREAD

**Issue by dstufft** [benoitc/gunicorn#984]
Currently the only way to customize the ``Reloader`` implementation is to either monkeypatch it or subclass the worker. It would be great if there was a way, even if it was only really available via ``gunicorn.app.base.Application`` subclassing, to configure our own ``Reloader``.

Alternatively a way to specify additional files (maybe with a glob?) would be useful instead.

**Comment by berkerpeksag** [comment]
We probably can add a `reloader_class` attribute to `gunicorn.app.base.Application`.

**Comment by tilgovi** [comment]
Even just assigning the new `Reloader` instance to `self.reloader` would make it available to the `post_worker_init` hook. The `Reloader` has a method `add_extra_file`.

Would that be sufficient for what you need for this issue or do you really want to customize it in some other way?

**Comment by dstufft** [comment]
That would be good enough for what I need it for I believe.

**Comment by tilgovi** [comment]
Done.
