### ISSUE TITLE
Reloader doesn't trigger reload hooks

### ISSUE THREAD

**Issue by dstufft** [benoitc/gunicorn#985]
Currently the ``Reloader`` has a thread per worker and when it detects a change it just ``SIGQUIT``s the current worker. This enables the ``Reloader`` to take place after the WSGI application has been imported so all the needed modules are inside of the ``sys.modules``. However this means that a reload looks like, to gunicorn, that the worker died and just needs to be restarted which means that the reload hooks don't get fired. Would it be possible to move the ``Reloader`` onto the arbiter and have it send a ``SIGHUP`` instead? This will probably require doing something smarter in ``Reloader.get_files`` but it would mean that the reload hooks get fired.

**Comment by tilgovi** [comment]
The reloader is intended for development. What's the use case that requires your reload hook to be called? Making this work would not be easy, since the workers would have to communicate back to the arbiter about what modules they have loaded.

**Comment by tilgovi** [comment]
Or maybe we could just have the workers send HUP to their parent process? That might cause problems with multiple workers, but that may also been an unusual setup for development.

**Comment by dstufft** [comment]
Essentially I was hoping to use the reload hook in development so that I could trigger a regeneration of the static files so that whenever gunicorn reloads it also picks up any new static file changes.

**Comment by tilgovi** [comment]
So do you really want the reload hook that HUP triggers or do you want to watch your static sources with an external script and add the output files to the reloader so that the worker reloads after the assets are built?

Alternatively, could you not configure the way you're serving static assets to not cache the files in development?

**Comment by dstufft** [comment]
Well I'd rather not watch my static source with an external script when I already have gunicorn running which is watching files and reloading when they change. It's simpler to have a single command to run than to have multiple commands to run. I jsut got this working, but it relies on overriding a good bit of the built in support for things, it'd be great if it was easier to do, see https://bpaste.net/show/6c0a78b5a54c.

**Comment by tilgovi** [comment]
Any reason not to simply generate them at worker start?

**Comment by dstufft** [comment]
Ah hm, that could be done I think.

**Comment by tilgovi** [comment]
Alright. I closed the other issue by making sure that `self.reloader` is the `Reloader` instance in the worker so you should be able to access it from hooks. If you need more, please re-open this, but I'll close it for the time being. Thanks, @dstufft.
