### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by berkerpeksag** [benoitc/gunicorn#991]
There are a lot of stale branches in the repo. I'm not sure they are still useful. Can we delete them?

Here is the list of the stale branches: https://github.com/benoitc/gunicorn/branches/stale

**Comment by tilgovi** [comment]
I'm okay to delete them. I think we should leave open any that are pull requests and just bump those threads separately so we can discuss what to do with each.

**Comment by benoitc** [comment]
+1

**Comment by berkerpeksag** [comment]
Ok, I've deleted some 5 years old branches.

**Comment by benoitc** [comment]
@berkerpeksag that's awesome! Should we close the ticket or any other branch in mind?

**Comment by tilgovi** [comment]
Deleted some more of my branches.

**Comment by berkerpeksag** [comment]
I haven't investigate all the branches yet, we can keep this open for a while :)

**Comment by benoitc** [comment]
right :)i also saw some branches i should take care...

**Comment by tilgovi** [comment]
bump

**Comment by tilgovi** [comment]
Can we delete the python2.5 and the py24 branches yet? :-P

**Comment by tilgovi** [comment]
I just deleted these branches that were fully merged:

- 0.14x
- fix/309
- fix/478
- fix/567
- gh1157
- gh-355
- gh-358
- headers
- release/1.0.x
- sphinxdoc-and-newsite

I left feature/tcp_fastopen because it was recently reverted.

**Comment by benoitc** [comment]
:+1:

**Comment by benoitc** [comment]
@tilgovi totally supporting py26 is already something we should consider to stop imo also...

**Comment by berkerpeksag** [comment]
I also just deleted fix/1174 and djangoreload branches. The latter is not needed anymore since djangoapp.py will be removed by #1076.

**Comment by benoitc** [comment]
also thanks for the work :)
